mage_ai/orchestration/monitor/monitor_stats.py
mage_ai/server/api/monitor.py

Add block run stats.
Doc: https://www.notion.so/mageai/Orchestration-engine-a5ed63c71c594801897fb9df3c9fefb7#51720c3e8d004fc2a023931d5ec8f436
tested locally
cc:

[xy] Add block run stats.

---

mage_ai/orchestration/monitor/monitor_stats.py

I forgot to commit this in [previous PR](https://github.com/mage-ai/mage-ai/pull/1088)
* Support filtering by schedule_id
* Count block run by status
tested locally
cc:

[xy] Support filtering by schedule_id.

---

mage_ai/orchestration/db/models.py

Add API schedule_type.
n/a
cc:

[xy] Add API schedule_type.

---

mage_ai/server/utils/output_display.py

Allow using bash command in scratchpad.
tested locally
cc:

[xy] Allow using bash command in scratchpad.

---

mage_ai/orchestration/pipeline_scheduler.py

Run queued blocks.
tested locally
cc:

[xy] Run queued blocks.

---

mage_ai/io/snowflake.py

Fix snowflake table exist error.
tested locally
cc:

[xy] Fix snowflake table exist error.

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/Triggers/utils.ts

Fix date parsing error on safari.
tested locally on safari
cc:

[dy] Use moment for date parsing

---

scripts/deploy/terraform/azure/files.tf
scripts/deploy/terraform/azure/main.tf
scripts/deploy/terraform/azure/storage.tf
scripts/deploy/terraform/azure/variables.tf

Add terraform scripts to deploy to azure.
TODOs
tested locally
cc:

[xy] Add terraform scripts to deploy to azure.

---

docs/deploy/aws/README.md
scripts/run_ec2.sh

[td] Update EC2 script and README

---

scripts/deploy/terraform/azure/main.tf
scripts/deploy/terraform/azure/networking.tf
scripts/deploy/terraform/azure/variables.tf

Set up virtual network for azure deployment.
* Create virtual network
* Create application gateway
* Restrict IP address access to the application gateway via Network Security Group
tested locally
cc:

[xy] Set up virtual network for azure deployment.

---

docs/deploy/terraform/AWS.md
docs/deploy/terraform/Azure.md
docs/deploy/terraform/README.md
scripts/deploy/terraform/azure/main.tf

[td] Terraform Azure

---

scripts/deploy/terraform/azure/storage.tf
scripts/deploy/terraform/azure/variables.tf

Make storage account name a variable so that it can be configurable.
tested locally
cc:

[xy] Make storage account name a variable.

---

mage_ai/orchestration/notification/sender.py
mage_ai/orchestration/pipeline_scheduler.py

Improve email templates to include pipeline run url.
tested locally
cc:

[xy] Improve email templates.

---

mage_ai/orchestration/notification/sender.py

Update notification message.
n/a
cc:

[xy] Update notification message.

---

mage_ai/server/api/orchestration.py

Fix pipeline run fetch error.
tested locally
cc:

[xy] Fix pipeline run fetch.

---

mage_ai/frontend/components/shared/Paginate/index.tsx

Update pagination prev and next buttons so you can't scroll past the valid pages.
tested locally
cc:

[dy] Fix pagination buttons

---

mage_ai/orchestration/monitor/monitor_stats.py

Not show negative runtime.
tested locally
cc:

[xy] Not show negative runtime.

---

mage_ai/frontend/api/utils/url.ts
mage_ai/server/api/orchestration.py

Update websocket url for https links.
tested on gcp
cc:

[dy] Update websocket url

---

mage_ai/frontend/components/shared/Paginate/index.tsx

When there are no pages, don't show the pagination
tested locally
cc:

[dy] Fix empty state

---

README.md
docs/README.md

[td] Add metrics to docs

---

Dockerfile
scripts/deploy/terraform/gcp/fs.tf
scripts/deploy/terraform/gcp/main.tf
scripts/deploy/terraform/gcp/variables.tf
scripts/run_app.sh

Set up NFS in GCP deployment
tested locally
cc:

[xy] Set up NFS in GCP deployment

---

docker-compose.yml
mage_ai/autocomplete/utils.py
mage_ai/cluster_manager/aws/emr_cluster_manager.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/interfaces/CloudProviderType.ts
mage_ai/frontend/interfaces/ClusterType.ts
mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/api/clusters.py
mage_ai/services/aws/emr/launcher.py
mage_ai/services/aws/emr/resource_manager.py
scripts/dev.sh

[td] Change clusters and fix PySpark output

---

scripts/deploy/terraform/gcp/load_balancer.tf
scripts/deploy/terraform/gcp/main.tf

Limit IP address access for GCP app.
Ref: https://cloud.google.com/armor/docs/integrating-cloud-armor
tested locally
cc:

[xy] Limit IP address access for GCP app

---

Dockerfile

Copy run_app script to another folder so that it doesn't overlap with the mounted file folder.
tested locally
cc:

[xy] Copy run_app script to another folder.

---

README.md
docs/README.md
docs/deploy/terraform/AWS.md
docs/deploy/terraform/Azure.md
docs/deploy/terraform/GCP.md
docs/deploy/terraform/README.md
scripts/deploy/terraform/gcp/variables.tf

[td] Add docs for GCP

---

mage_ai/frontend/components/ContextMenu/index.tsx

[jk] Remove pipeline file context menu that is no longer relevant

---

docs/deploy/terraform/Azure.md
scripts/deploy/terraform/azure/key_vault.tf
scripts/deploy/terraform/azure/main.tf
scripts/deploy/terraform/azure/networking.tf
scripts/deploy/terraform/azure/service_principal.tf
scripts/deploy/terraform/azure/variables.tf

Set up key vault and grant access in terraform script
tested locally
cc:

[xy] Set up key vault and grant access in terraform script

---

mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.style.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
mage_ai/frontend/oracle/components/PopupMenu/PopupMenuContainer.tsx
mage_ai/frontend/oracle/components/PopupMenu/index.tsx
mage_ai/frontend/oracle/elements/Text/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx

- Allow user to create a new pipeline or delete the current pipeline from a dropdown menu in the header.
Delete pipeline:
Create pipeline (from header menu):

[jk] Delete pipeline from pipeline detail page

---

mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- We are no longer displaying all of the pipelines in the Pipeline Editor view, so we can remove its api calls.
- Local
cc:

[jk] Remove pipeline list api calls in pipeline editor

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/Sidekick/constants.ts
mage_ai/frontend/components/Sidekick/index.style.ts
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/Terminal/index.style.tsx
mage_ai/frontend/components/Terminal/index.tsx
mage_ai/frontend/oracle/components/ClickOutside/index.tsx
mage_ai/frontend/oracle/elements/Text/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/utils/hooks/keyboardShortcuts/constants.ts
mage_ai/server/websocket.py

[td] Git terminal

---

mage_ai/frontend/components/Terminal/index.tsx

[td] Show command for git docs

---

mage_ai/data_preparation/models/block/__init__.py

Catch dataframe analysis error so that malformed dataframe analysis json file won't corrupt the UI.
tested locally
cc:

[xy] Catch dataframe analysis error.

---

docs/guides/blocks/Sensors.md

See title. Fixed broken gif in readme
Checked link

[kh] Fixed broken sensor gif

---

mage_ai/frontend/pages/pipeline-runs/index.tsx

Add pagination to `/pipeline-runs`
local
cc:

[dy] Add pagination to pipeline runs page

---

mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx

[td] Fix double fetching logs

---

mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

[td] Only save content and outputs when running block

---

mage_ai/io/config.py

Fix AWS Secret Loader.
tested locally
cc:

[xy] Fix AWS Secret Loader.

---

docs/core/abstractions.md
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx

- The time input was previously a freeform input without validation until a user tries to save the Trigger, which would show an error if the format was incorrect. This PR uses dropdown inputs instead so input validation is not required.
- Minor update to README
Before (freeform input):
After (select dropdowns):

[jk] Revised datetime input when editing Trigger

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/templates/data_loaders/streaming/kafka.yaml
mage_ai/data_preparation/templates/template.py
mage_ai/data_preparation/templates/transformers/default_streaming.jinja
mage_ai/server/websocket.py
mage_ai/streaming/constants.py
mage_ai/streaming/sinks/base.py
mage_ai/streaming/sinks/opensearch.py
mage_ai/streaming/sinks/sink_factory.py
mage_ai/streaming/sources/base.py
mage_ai/streaming/sources/kafka.py
mage_ai/streaming/sources/source_factory.py
mage_ai/tests/data_preparation/test_templates.py
requirements.txt
setup.py

* Support streaming pipeline execution.
* Streaming pipeline should follow the structure: source -> transformer -> sink
* Add Kafka as the source and Opensearch as the sink.
tested locally
cc:

[xy] Execute streaming pipelines.

---

mage_ai/data_preparation/executors/executor_factory.py
mage_ai/data_preparation/executors/pipeline_executor.py
mage_ai/data_preparation/executors/pyspark_pipeline_executor.py
mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/orchestration/execution_process_manager.py
mage_ai/orchestration/pipeline_scheduler.py

Support streaming pipeline orchestration
* Add streaming pipeline executor to executor factory.
* Schedule pipeline instead of blocks for streaming pipelines
* Manage the execution processes for pipeline runs
* Auto restart when there's no live process for streaming pipeline
TODOs:
tested locally
cc:

[xy] Support streaming pipeline orchestration

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/orchestration/execution_process_manager.py

[xy] Some improvements on streaming pipelines

---

mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.ts
mage_ai/frontend/components/PipelineDetail/Runs/Table.style.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx

- Default to `@once` frequency for streaming pipeline "schedule" triggers.
- Remove fixed priority when adding streaming pipeline blocks.
- Remove spacing above block delete button.
- Fix "Run is in progress" popup overflow when running pipelines.
- Local
cc:

[jk] Bugfixes for streaming pipelines

---

Dockerfile
docker-compose.yml
docs/README.md
docs/guides/pipelines/StreamingPipeline.md
docs/tutorials/quick_start/setup.md
requirements.txt

Add documentation on how to set up Kafka locally and run it with Mage.
Also, provide guide on how to build a streaming pipeline.

[td] Add docs for streaming pipeline

---

docker-compose.yml
docs/guides/pipelines/StreamingPipeline.md

Update docker compose and doc for kafka.
n/a
cc:

[xy] Update docker compose and doc for kafka.

---

integrations/connections/base.py
integrations/connections/google_analytics/__init__.py
integrations/connections/postgresql/README.md
integrations/connections/postgresql/__init__.py
integrations/connections/utils/sql.py
integrations/requirements.txt

- Added a very lightweight connection for PostgreSQL

[td] Added basic connection for PostgreSQL

---

scripts/deploy/terraform/aws/main.tf

Update security group for aws deployment. Only expose ECS service to load balancer and whitelisted IPs.
tested locally
cc:

[xy] Update security group for aws deployment.

---

mage_ai/data_preparation/templates/data_loaders/streaming/kafka.yaml
mage_ai/shared/config.py
mage_ai/streaming/sources/kafka.py
mage_ai/tests/data_preparation/test_templates.py

Support connecting to kafka via SSL.
tested locally
cc:

[xy] Support connecting to kafka via SSL.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/storage/base_storage.py
mage_ai/data_preparation/storage/local_storage.py
mage_ai/data_preparation/storage/s3_storage.py
mage_ai/data_preparation/variable_manager.py
mage_ai/services/aws/s3/s3.py
mage_ai/shared/constants.py
mage_ai/shared/urls.py

Add storage module and S3 storage to save variables.
Example configuration in metadata.yaml:
```yaml
variables_dir: s3://[variable_bucket]
```
TODOs
tested locally
cc:

[xy] Add storage module and S3 storage.

---

mage_ai/data_preparation/models/variable.py

Catch the exception of writing sample data.
tested locally
cc:

[xy] Catch the exception of writing sample data.

---

templates/github_actions/build_and_deploy_to_ecs.yml

Add github action template to deploy to ECS.
tested in a test repo
cc:

[xy] Add github action template to deploy to ECS.

---

mage_ai/orchestration/pipeline_scheduler.py

Fix import error.
```
File "/home/src/mage_ai/cli/main.py", line 146, in <module>
main()
File "/home/src/mage_ai/cli/main.py", line 54, in main
from mage_ai.server.server import start_server
File "/home/src/mage_ai/server/server.py", line 27, in <module>
from mage_ai.server.api.events import (
File "/home/src/mage_ai/server/api/events.py", line 3, in <module>
from mage_ai.orchestration.triggers.event_trigger import EventTrigger
File "/home/src/mage_ai/orchestration/triggers/event_trigger.py", line 1, in <module>
from mage_ai.orchestration.pipeline_scheduler import schedule_with_event
File "/home/src/mage_ai/orchestration/pipeline_scheduler.py", line 18, in <module>
from mage_integrations.sources.utils import update_source_state_from_destination_state …
```

[xy] Fix import error.

---

mage_ai/server/scheduler_manager.py
mage_ai/server/server.py

Auto restart scheduler if it crashes with exception.
tested locally
cc:

[xy] Auto restart scheduler if it crashes with exception.

---

mage_ai/data_integrations/logger/utils.py
mage_ai/data_integrations/utils/config.py
mage_ai/data_preparation/models/block/__init__.py
mage_integrations/destinations/base.py
mage_integrations/sources/utils.py

- You can interpolate values into your data integration pipeline settings:
```yaml
config:
api_key: "{{ env_var('API_KEY') }}"
secret_key: "{{ env_var('SECRET_KEY') }}"
table: "test_{{ variables('table_name') }}"
```

[td] Support variable interpolation in integration pipeline

---

docs/deploy/terraform/AWS.md
docs/deploy/terraform/Azure.md
docs/deploy/terraform/GCP.md

Add docs for configuring HTTPS for deployed app in AWS.
tested by following the instructions.
cc:

[xy] Add docs for setting up HTTPS in AWS

---

mage_ai/server/scheduler_manager.py

Don't retry deadlock. The scheduler was keeping retrying and failing when there's a DB deadlock.
We'll recreate a subprocess when scheduler crashes.
tested locally
to be tested on cloud
cc:

[xy] Don't retry deadlock.

---

mage_ai/frontend/pages/pipeline-runs/index.tsx

Update pipeline runs page to use the updated `PipelineRunsTable`.
cc:

[dy] Update pipeline runs page

---

mage_ai/data_preparation/logging/logger.py
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/frontend/utils/models/log.ts

[jk] Show logs in reverse chronological order

---

mage_integrations/sources/catalog.py

Some code in the Catalog class was not very intuitive, which was cleaned up.
CI
cc:

Simplify the code related to the Catalog class

---

mage_ai/data_integrations/destinations/constants.py
mage_integrations/connections/snowflake/__init__.py
mage_integrations/connections/sql/base.py
mage_integrations/destinations/postgresql/TEST_CONFIG.json
mage_integrations/destinations/postgresql/__init__.py
mage_integrations/destinations/snowflake/__init__.py
mage_integrations/destinations/snowflake/templates/config.json
mage_integrations/destinations/snowflake/utils.py
mage_integrations/destinations/sql/base.py
mage_integrations/destinations/sql/utils.py
mage_integrations/requirements.txt

- Added Snowflake connection
- Added Snowflake destination (aka target)
- Refactored SQL connections and SQL destinations

[td] Add Snowflake connection and destination

---

mage_ai/orchestration/db/process.py

Fix pickle error issue.
tested locally with new python virtualenv

[dy] Update start_session_and_run

---

requirements.txt

Not require signer package since it's included in mage_integrations
tested locally
cc:

[xy] Not require signer package.

---

mage_ai/server/api/logs.py

> Filtering pipeline logs by start and end timestamps (UNIX epoch)
> Tested locally with different start and end timestamp combinations
cc:

[sg] Filter pipeline run logs by start_timestamp and end_timestamp

---

mage_ai/frontend/components/ContextMenu/index.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_integrations/destinations/snowflake/__init__.py
mage_integrations/sources/salesforce/client/tap_salesforce/__init__.py
mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/__init__.py
mage_integrations/sources/salesforce/client/tap_salesforce/sync.py

- Don’t require bookmark properties when syncing
- Add links to GitHub when configuring sources and destinations

[td] Don’t require bookmark properties

---

docs/data_integrations/README.md
docs/data_integrations/destinations/README.md
docs/data_integrations/sources/README.md
docs/guides/data_integrations/sources/AddNewSource.md
mage_integrations/sources/base.py
mage_integrations/sources/titanic/__init__.py
mage_integrations/sources/titanic/schemas/passengers.json
mage_integrations/sources/titanic/templates/config.json

- How to add a new custom source

[td] Add source docs

---

docs/guides/data_integrations/sources/AddNewSource.md
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/oracle/components/CopyToClipboard.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Add instructions on the UI for adding variables

[td] Add variable instructions on UI

---

mage_ai/frontend/components/Triggers/utils.ts

Revert previous UTC date change.
tested locally
cc:

[dy] Revert date change

---

mage_ai/frontend/components/Terminal/index.style.tsx
mage_ai/frontend/components/Terminal/index.tsx

- Add copying highlighted text functionality to terminal.
- Allow moving cursor with left and right arrows on keyboard.
- Tested copy and paste functionality in terminal (not able to record gif with active keyboard shortcuts in app).
- Tested moving cursor left and right and deleting chars in middle of command.

[jk] Terminal enhancements

---

mage_ai/tests/orchestration/db/test_models.py

Fix broken tests on master.
CI
cc:

[dy] Fix unit tests

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/r/__init__.py
mage_ai/data_preparation/models/block/r/templates/data_exporter.jinja
mage_ai/data_preparation/models/block/r/templates/data_loader.jinja
mage_ai/data_preparation/models/block/r/templates/transformer.jinja

Improve sample output and perform data analysis for R blocks
tested locally
cc:

[xy] Improve sample output for R blocks

---

mage_integrations/MANIFEST.in

- Add manifest file to mage integrations package to include templates and schemas

[td] Add manifest file to mage integrations package

---

mage_ai/frontend/components/ContextMenu/index.tsx
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/interfaces/FileType.ts

- See title.
- Also fixed broken mage_integrations README links.

[jk] Add pipelines folder with metadata file visible

---

mage_ai/tests/orchestration/test_execution_process_manager.py

Add unit test to ExecutionProcessManager.
unit tests
cc:

[xy] Add unit test to ExecutionProcessManager.

---

scripts/deploy/terraform/azure/networking.tf

Allow outbound traffic for any ports in Azure terraform.
tested locally
cc:

[xy] Allow outbound traffic for any ports.

---

mage_ai/data_preparation/logging/__init__.py
mage_ai/orchestration/db/__init__.py
mage_ai/orchestration/db/database_manager.py
mage_ai/orchestration/db/migrations/env.py
mage_ai/orchestration/db/models.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/shared/logger.py
mage_ai/tests/__init__.py
mage_ai/tests/base_test.py
mage_ai/tests/factory.py
mage_ai/tests/orchestration/db/test_models.py

Improve the performance of fetching active runs.
* Filter pipeline run in sql query
* Join load block runs
Improve the performance of fetching active pipeline schedules
* Filter pipeline schedules in sql query
tested locally
unit tests
cc:

[xy] Improve performance of fetching active runs.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/r/__init__.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/storage/local_storage.py

* Fix data exporter of R block. Check whether output_variable_object is None for data_exporter block.
* Convert parquet to csv for R blocks.
tested locally
cc:

[xy] Fix data exporter of R block.

---

Dockerfile
dev.Dockerfile

Install R in docker images.
TODO: separate docker images for different type of pipelines
tested locally
cc:

[xy] Install R in docker images.

---

mage_ai/orchestration/pipeline_scheduler.py
mage_ai/shared/retry.py
mage_ai/tests/shared/test_retry.py

Retry on_block_complete and on_block_failure.
Handle error:
tested locally
unit test
cc:

[xy] Retry on_block_complete and on_block_failure.

---

Dockerfile
dev.Dockerfile

Install pacman R package in dockerfile.
`pacman` can be used to manage and load packages.
Example
```
library("pacman")
pacman::p_load(here, pracma, tidyr, dplyr)
```
tested locally
cc:

[xy] Install pacman R package in dockerfile.

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.ts
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/FileType.ts
mage_ai/frontend/oracle/components/Badge/index.tsx
mage_ai/frontend/oracle/styles/themes/dark.ts

- See title.
- Also added badge indicator for block language type.
cc:

[jk] Support R language code blocks in UI

---

Dockerfile

Fix R package installation.
tested locally
cc:

[xy] Fix R package installation.

---

mage_ai/frontend/interfaces/BlockType.ts

[jk] Capitalize python language badge for code blocks

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/streaming/constants.py
mage_ai/streaming/sinks/base.py
mage_ai/streaming/sinks/opensearch.py
mage_ai/streaming/sources/azure_event_hub.py
mage_ai/streaming/sources/base.py
mage_ai/streaming/sources/kafka.py
mage_ai/streaming/sources/source_factory.py
mage_ai/tests/base_test.py
mage_ai/tests/data_preparation/models/test_block.py
mage_ai/tests/data_preparation/models/test_pipeline.py
mage_ai/tests/data_preparation/models/test_variable.py
mage_ai/tests/data_preparation/test_variable_manager.py
mage_ai/tests/io/test_config.py
mage_ai/tests/orchestration/db/test_models.py
mage_ai/tests/orchestration/notification/test_sender.py
mage_ai/tests/orchestration/test_execution_process_manager.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py
mage_ai/tests/orchestration/triggers/test_loop_time_trigger.py
mage_ai/tests/streaming/sinks/test_opensearch.py
mage_ai/tests/streaming/sinks/test_sink_factory.py
mage_ai/tests/streaming/sources/test_azure_event_hub.py
mage_ai/tests/streaming/sources/test_kafka.py
mage_ai/tests/streaming/sources/test_source_factory.py
requirements.txt

Add AzureEventHub source to streaming pipeline
tested locally
added unit tests
cc:

[xy] Add AzureEventHub source to streaming pipeline

---

README.md

[td] Update main README

---

mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
mage_ai/frontend/components/Dashboard/index.style.tsx
mage_ai/frontend/components/Logs/Toolbar/index.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/PipelineDetailPage/constants.ts
mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/interfaces/PipelineRunType.ts
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx

- Add status filter for pipeline runs.
- Move "Edit pipeline" button to vertical navigation instead of at top of page taking space of an entire row.

[jk] Pipeline runs status filter

---

mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx

- See title.
Github issue: https://github.com/mage-ai/mage-ai/issues/1118

[jk] Add pipeline runs status filter to individual trigger page

---

docs/blocks/README.md

Added a blocks image in introduction
Adds a graphic representation of blocks into the readme
Validated preview

Added image to blocks readme

---

mage_ai/server/websocket.py

[jk] Fix cd command in terminal

---

docs/README.md
docs/guides/blocks/R.md

Add doc for R language.
n/a
cc:

[xy] Add doc for R language.

---

docs/guides/data_integrations/sources/AddNewSource.md
mage_ai/data_integrations/sources/constants.py
mage_ai/server/api/integration_sources.py
mage_integrations/mage_integrations/connections/amplitude/README.md
mage_integrations/mage_integrations/destinations/postgresql/__init__.py
mage_integrations/mage_integrations/sources/amplitude/__init__.py
mage_integrations/mage_integrations/sources/base.py
mage_integrations/mage_integrations/sources/google_search_console/README.md
mage_integrations/mage_integrations/sources/google_search_console/__init__.py
mage_integrations/mage_integrations/sources/google_search_console/client.py
mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_country.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_custom.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_date.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_device.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_page.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_query.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/sitemaps.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/sites.json
mage_integrations/mage_integrations/sources/google_search_console/streams.py
mage_integrations/mage_integrations/sources/google_search_console/sync.py
mage_integrations/mage_integrations/sources/google_search_console/templates/config.json
mage_integrations/mage_integrations/sources/google_search_console/transform.py
mage_integrations/mage_integrations/sources/mysql/__init__.py
mage_integrations/mage_integrations/sources/redshift/__init__.py
mage_integrations/mage_integrations/sources/salesforce/__init__.py
mage_integrations/mage_integrations/sources/stripe/__init__.py
mage_integrations/mage_integrations/sources/utils.py

Add Google Search Console source.
tested locally
cc:

[xy] Add Google Search Console source.

---

mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/data_preparation/models/block/sql/redshift.py
mage_ai/data_preparation/models/block/sql/snowflake.py
mage_ai/data_preparation/models/block/sql/utils/shared.py

- If upstream blocks differ in profile, cache the SQL results locally to pass into the downstream block’s inputs

[td] Cache SQL results if upstream differs in profile

---

mage_integrations/mage_integrations/connections/bigquery/__init__.py
mage_integrations/mage_integrations/connections/google_analytics/__init__.py
mage_integrations/mage_integrations/connections/google_analytics/constants.py
mage_integrations/mage_integrations/connections/utils/google.py
mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/bigquery/README.md
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/bigquery/templates/config.json
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/sql/utils.py
mage_integrations/requirements.txt

Add BigQuery destination.
tested locally
cc:

[xy] Add BigQuery destination.

---

mage_ai/data_integrations/destinations/constants.py
mage_ai/data_preparation/templates/data_loaders/streaming/azure_event_hub.yaml
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.ts
mage_ai/frontend/interfaces/DataSourceType.ts

* Add BigQuery to UI.
* Add Azure Event Hub to UI.
tested locally
cc:

[xy] Add new sources to UI.

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx

Add transformer block in data integration pipeline frontend.
tested locally
cc:

[dy] Add transformer in frontend

---

mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_country.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_custom.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_date.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_device.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_page.json
mage_integrations/mage_integrations/sources/google_search_console/schemas/performance_report_query.json

Remove multipleOf from the schema to fix schema validation error.
tested locally
cc:

[xy] Remove multipleOf from the schema.

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/pipelines/integration_pipeline.py
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx

Update styling of integration pipeline transformers, and update `Pipeline.get` method to return `IntegrationPipeline`
tested locally
cc:

[dy] Update integration pipeline

---

mage_ai/frontend/components/IntegrationPipeline/index.tsx

Messed up tag spacing in previous PR
cc:

[dy] Fix spacing

---

docs/spark/setup/README.md

- See title.
- Confirmed image rendered on github.

[jk] Replace and resize Sparkmage image in readme

---

mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx

[jk] Do not auto-filter logs when viewing pipeline or block run logs

---

docs/guides/data_integrations/sources/AddNewSource.md
mage_integrations/mage_integrations/connections/amplitude/__init__.py
mage_integrations/mage_integrations/sources/amplitude/__init__.py
mage_integrations/mage_integrations/sources/base.py
mage_integrations/mage_integrations/sources/google_search_console/__init__.py
mage_integrations/mage_integrations/sources/redshift/__init__.py
mage_integrations/mage_integrations/sources/sql/base.py
mage_integrations/mage_integrations/sources/titanic/__init__.py

Update data integration source to sync streams with pagination so that it can scale to sync large datasets
tested locally on sources
* google search console
* postgres
* mysql
* titanic
cc:

[xy] Sync streams with pagination

---

README.md

- See title.
cc:
@MageKai @wangxiaoyou1993

[jk] Add github and stars links to readme

---

mage_ai/frontend/components/IntegrationPipeline/index.tsx

- Allow user to select which columns to add as key properties for the data stream.
cc:

[jk] Data integration key properties

---

mage_ai/frontend/components/Logs/Toolbar/constants.ts

[jk] Increase log count interval to 100

---

mage_integrations/mage_integrations/sources/redshift/__init__.py
mage_integrations/mage_integrations/sources/sql/base.py

Fix Redshift source.
Will add unit tests to the data integration sources and update Redshift to inherit from base SQL source in a separate PR.
tested locally
cc:

[xy] Fix Redshift source.

---

mage_ai/data_preparation/models/pipelines/integration_pipeline.py
mage_ai/frontend/components/IntegrationPipeline/SourceConfig.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/server/api/integration_sources.py
mage_ai/server/server.py
mage_ai/shared/parsers.py
mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/sources/amplitude/__init__.py
mage_integrations/mage_integrations/sources/base.py
mage_integrations/mage_integrations/sources/google_search_console/__init__.py
mage_integrations/mage_integrations/sources/redshift/__init__.py
mage_integrations/mage_integrations/sources/salesforce/__init__.py
mage_integrations/mage_integrations/sources/sql/base.py
mage_integrations/mage_integrations/sources/stripe/__init__.py
mage_integrations/mage_integrations/sources/titanic/__init__.py
mage_integrations/mage_integrations/sources/utils.py

Test source and destination connection from integration pipeline view. I added a `test_connection` method to the source and destination classes, so all subclasses need to implement this method.
tested locally with all sources and destinations

[dy] Test source and destination connection

---

mage_ai/frontend/components/Logs/Detail/index.tsx

[jk] Show and hide full log message in log details

---

mage_integrations/mage_integrations/sources/base.py
mage_integrations/mage_integrations/sources/bigquery/README.md
mage_integrations/mage_integrations/sources/bigquery/__init__.py
mage_integrations/mage_integrations/sources/bigquery/templates/config.json
mage_integrations/mage_integrations/sources/mysql/__init__.py
mage_integrations/mage_integrations/sources/sql/base.py

Add BigQuery source to data integration pipeline.
tested locally
`python3 mage_integrations/sources/bigquery/__init__.py --config TEST_CONFIG_BIGQUERY_SOURCE.json --discover > TEST_CATALOG_BIGQUERY.json`
`python3 mage_integrations/sources/bigquery/__init__.py --config TEST_CONFIG_BIGQUERY_SOURCE.json --state TEST_STATE.json --catalog TEST_CATALOG_BIGQUERY.json`
cc:

[xy] Add BigQuery source to data integration pipeline.

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/r/__init__.py
mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/data_preparation/models/block/sql/redshift.py
mage_ai/data_preparation/models/block/sql/snowflake.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/server/api/blocks.py
mage_ai/tests/data_preparation/models/test_block.py

Handle unstructured data in blocks. Each block now can return a list of output variables of dataframe, dictionary, or primitive data types.
tested locally
cc:

[xy] Handle unstructured data in blocks.

---

docs/README.md
docs/guides/dbt/run_model.md
docs/guides/dbt/run_models.md
docs/tutorials/dbt/quick_start.md

[td] Add more guide docs for DBT

---

SUMMARY.md
docs/tutorials/dbt/quick_start.md
mage_integrations/mage_integrations/sources/postgresql/README.md

- See title.
- Checked gitbook preview.

[jk] Update documentation hosted on docs.mage.ai

---

mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/Triggers/utils.ts

[jk] Set default datetime when creating schedule trigger

---

mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/oracle/components/PopupMenu/PopupMenuContainer.tsx
mage_ai/frontend/oracle/components/PopupMenu/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

- Allow user to delete triggers.

[jk] Delete triggers

---

README.md

[td] Add DBT to features

---

mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/io/bigquery.py
mage_ai/server/server.py

Support BigQuery in DBT blocks.
tested locally
cc:

[xy] Support BigQuery in DBT blocks.

---

mage_ai/data_preparation/models/block/sql/utils/shared.py

Don't cache upstream data if upstream block is sensor.
tested locally
cc:

[xy] Don't cache upstream data if upstream block is sensor.

---

mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx

Show transformer block without needing to set a destination block. Also, remove the "data source" option from the transformer for itnegration pipelines
tested locally 
cc:

[dy] Show transformer block earlier

---

mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/models/block/sql/snowflake.py
mage_ai/io/snowflake.py

Support Snowflake in DBT block.
tested locally
cc:

[xy] Support Snowflake in DBT block.

---

mage_ai/data_preparation/models/block/sql/snowflake.py
mage_ai/io/snowflake.py

Fix snowflake table name existence check.
tested locally
cc:

[xy] Fix Snowflake table name.

---

mage_integrations/mage_integrations/sources/mysql/README.md

Update the README of MySQL source.
n/a
cc:

[xy] Update the README of MySQL source.

---

mage_integrations/mage_integrations/sources/sql/base.py

ROW_NUMBER() OVER is not supported in some SQL syntax. Thus, replace it with `LIMIT X OFFSET Y`
https://docs.aws.amazon.com/dms/latest/sql-server-to-aurora-mysql-migration-playbook/chap-sql-server-aurora-mysql.sql.windowfunctions.html
tested with Aurora MySQL, BigQuery, Postgres, MySQL
cc:

[xy] Fix data integration source SQL query

---

mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

[jk] Add spacing between edit and delete trigger buttons

---

SUMMARY.md
docs/README.md

- See title.
- Checked gitbook preview.

[jk] Include new DBT docs

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeEditor/autocomplete/index.ts
mage_ai/frontend/components/PipelineDetail/index.tsx

Update output name in UI.
tested locally
cc:

[xy] Update output name in UI.

---

mage_ai/data_integrations/utils/config.py
mage_ai/data_preparation/models/pipelines/integration_pipeline.py
mage_ai/frontend/components/IntegrationPipeline/SourceConfig.tsx

Add interpolation when testing connection for source and destination.

[dy] Interpolate variables in test_connection

---

mage_ai/data_preparation/models/block/sql/utils/shared.py

Don't create upstream table for sensor upstream block.
tested locally
cc:

[xy] Fix dbt sensor upstream block.

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx

[jk] Rerun successful pipeline runs

---

mage_ai/data_integrations/utils/config.py
mage_ai/shared/dates.py

Support variable n_days_ago.
Example
```yaml
start_date: "{{ n_days_ago(7) }}"
```
tested locally
cc:

[xy] Support variable n_days_ago.

---

docs/deploy/terraform/GCP.md
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_integrations/mage_integrations/destinations/mysql/utils.py
mage_integrations/mage_integrations/destinations/snowflake/utils.py
templates/docker/Dockerfile

[td] Remove print statement and update Dockerfile templates

---

mage_ai/data_integrations/sources/constants.py
mage_integrations/mage_integrations/connections/google_sheets/__init__.py
mage_integrations/mage_integrations/sources/google_search_console/__init__.py
mage_integrations/mage_integrations/sources/google_sheets/README.md
mage_integrations/mage_integrations/sources/google_sheets/__init__.py
mage_integrations/mage_integrations/sources/google_sheets/templates/config.json
mage_integrations/mage_integrations/sources/google_sheets/transform.py

Add google sheets source.
tested locally
cc:

[xy] Add google sheets source.

---

mage_integrations/mage_integrations/sources/google_sheets/__init__.py
mage_integrations/mage_integrations/sources/google_sheets/transform.py

Update google sheet column names
tested locally
cc:

[xy] Update google sheet column names

---

mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/bigquery/utils.py
mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/destinations/sql/utils.py

[td] Fix BigQuery insert command syntax

---

mage_ai/data_preparation/models/block/dbt/utils/__init__.py

Not create loader when no upstream blocks.
tested locally
cc:

[xy] Not create loader when no upstream blocks.

---

mage_ai/data_integrations/utils/config.py
mage_ai/data_integrations/utils/scheduler.py
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/executors/executor_factory.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/orchestration/db/models.py
mage_ai/orchestration/pipeline_scheduler.py
mage_integrations/mage_integrations/sources/utils.py

- Create a data loader block run for each stream
- Create a transformer block run for each stream
- Create a data exporter block run for each stream

[td] Sync multiple streams

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_integrations/mage_integrations/sources/base.py
mage_integrations/mage_integrations/transformers/base.py
mage_integrations/mage_integrations/transformers/utils.py

As title.
tested locally with a simple transformer that adds a new column

[dy] Support creating new column in transformer

---

mage_ai/data_integrations/utils/scheduler.py
mage_ai/server/api/orchestration.py

Fix integration pipeline run retry. Dynamically create block runs for integration pipeline.
tested locally
cc:

[xy] Fix integration pipeline run retry.

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/index.tsx
mage_ai/frontend/components/IntegrationPipeline/SelectStreams/index.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/interfaces/IntegrationSourceType.ts
mage_ai/frontend/oracle/components/Panel/v2/index.style.tsx
mage_ai/frontend/oracle/components/Panel/v2/index.tsx
mage_ai/orchestration/pipeline_scheduler.py

[td] Select multiple streams in the UI

---

mage_integrations/mage_integrations/sources/stripe/__init__.py

[td] Fix stripe function

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/interfaces/IntegrationSourceType.ts

[jk] Add toggle for automatically adding new fields to stream

---

mage_integrations/mage_integrations/sources/google_sheets/__init__.py

Increase batch size for google sheets request.
tested locally
cc:

[xy] Increase batch size for google sheets request.

---

mage_integrations/mage_integrations/destinations/sql/utils.py

Fix alter table command typo.
tested locally
cc:

[xy] Fix alter table command.

---

mage_integrations/mage_integrations/transformers/base.py

Fix import statement in data integration transformer.
tested locally
cc:

[xy] Fix import statement in data integration transformer.

---

mage_ai/orchestration/db/__init__.py
mage_ai/orchestration/db/process.py
mage_ai/server/utils/output_display.py

Fix sensor block run. Start db session before executing blocks.
tested locally
cc:

[xy] Fix sensor block run.

---

mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

[jk] Set upstream and downstream blocks when adding existing transformer to integration pipeline

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx

[jk] Apply auto_add_new_fields changes to all streams

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/components/IntegrationPipeline/index.style.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/shared/Table/index.style.tsx
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/interfaces/IntegrationSourceType.ts

- Allow user to select which columns they want to use from their data source as partition keys.
cc:
@wangxiaoyou1993 @dy46 @tommydangerous

[jk] Add optional partition key columns to UI

---

Dockerfile
mage_ai/data_preparation/repo_manager.py
scripts/run_app.sh
templates/docker/Dockerfile

Update dockerfile for user code deployment
tested locally
cc:

[xy] Update dockerfile for user code deployment

---

mage_ai/cli/main.py
mage_ai/orchestration/db/__init__.py

Set repo path before initializing db so that we can the correct db url.
tested locally
cc:

[xy] Set repo path before initializing db.

---

scripts/run_app.sh

Fix mount path.
to be tested on cloud
cc:

[xy] Fix mount path.

---

mage_ai/data_integrations/sources/constants.py
mage_integrations/mage_integrations/sources/intercom/README.md
mage_integrations/mage_integrations/sources/intercom/__init__.py
mage_integrations/mage_integrations/sources/intercom/client.py
mage_integrations/mage_integrations/sources/intercom/schema.py
mage_integrations/mage_integrations/sources/intercom/schemas/admins.json
mage_integrations/mage_integrations/sources/intercom/schemas/companies.json
mage_integrations/mage_integrations/sources/intercom/schemas/company_attributes.json
mage_integrations/mage_integrations/sources/intercom/schemas/company_segments.json
mage_integrations/mage_integrations/sources/intercom/schemas/contact_attributes.json
mage_integrations/mage_integrations/sources/intercom/schemas/contacts.json
mage_integrations/mage_integrations/sources/intercom/schemas/conversation_parts.json
mage_integrations/mage_integrations/sources/intercom/schemas/conversations.json
mage_integrations/mage_integrations/sources/intercom/schemas/segments.json
mage_integrations/mage_integrations/sources/intercom/schemas/tags.json
mage_integrations/mage_integrations/sources/intercom/schemas/teams.json
mage_integrations/mage_integrations/sources/intercom/streams.py
mage_integrations/mage_integrations/sources/intercom/templates/config.json
mage_integrations/mage_integrations/sources/intercom/transform.py

Add intercom source.
TODO: support bookmark
tested locally
cc:

[xy] Add intercom source.

---

mage_integrations/mage_integrations/sources/intercom/client.py

Fix intercom source import. Remove backoff decorators.
tested locally
cc:

[xy] Fix intercom source import.

---

mage_ai/data_preparation/repo_manager.py

Fix mage data location priority.
tested locally
cc:

[xy] Fix mage data location priority.

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx

Hide partition key setting when the partition key is not configurable.
tested locally
cc:

[dy] Hide partition key setting

---

docs/tutorials/dbt/quick_start.md
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/ContextMenu/index.tsx
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/FileEditor/utils.ts
mage_ai/frontend/components/FileSelectorPopup/index.style.tsx
mage_ai/frontend/components/FileSelectorPopup/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/oracle/components/LabelWithValueClicker.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/utils/models/dbt.ts

- Allow user to create new dbt model through the UI in the pipeline editor.
- Clicking on dbt sql file with an existing code block in the pipeline will scroll to it.
- If a user clicks on a dbt sql file that does not exist in the current pipeline, user can add it to the pipeline.
Adding new dbt model:
Add dbt model to pipeline from sql file:
cc:
@wangxiaoyou1993 @MageKai

[jk] Create new dbt model without requiring an existing SQL file

---

SUMMARY.md

[jk] Update docs to include Google Sheets and Intercom data source

---

docs/deploy/terraform/GCP.md
mage_ai/data_preparation/templates/data_loaders/api.py
mage_ai/data_preparation/templates/data_loaders/azure_blob_storage.py
mage_ai/data_preparation/templates/data_loaders/bigquery.py
mage_ai/data_preparation/templates/data_loaders/default.jinja
mage_ai/data_preparation/templates/data_loaders/file.py
mage_ai/data_preparation/templates/data_loaders/google_cloud_storage.py
mage_ai/data_preparation/templates/data_loaders/postgres.py
mage_ai/data_preparation/templates/data_loaders/redshift.py
mage_ai/data_preparation/templates/data_loaders/s3.py
mage_ai/data_preparation/templates/data_loaders/snowflake.py
mage_ai/data_preparation/templates/sensors/default.py
mage_ai/orchestration/run_status_checker.py
mage_ai/tests/data_preparation/test_templates.py
scripts/server/test.sh
templates/docker/Dockerfile

[td] Make sensor work with once intervals

---

scripts/deploy/terraform/gcp/main.tf

Enable secret manager api in gcp terraform.
tested locally
cc:

[xy] Enable secret manager api in gcp terraform.

---

scripts/deploy/terraform/gcp/main.tf

Add example for mounting secrets to google cloud run.
tested locally 
cc:

[xy] Add example for mounting secrets to google cloud run.

---

mage_ai/server/utils/output_display.py
mage_ai/server/websocket.py

Not pass repo_config when executing code.
temp fix for variable path.
tested locally
cc:

[xy] Not pass repo_config when executing code.

---

docs/deploy/terraform/GCP.md
mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx
templates/docker/Dockerfile

[td] Improve GCP docs

---

docs/deploy/terraform/AWS.md
mage_ai/data_preparation/models/block/dbt/utils/__init__.py

[td] Interpolate env var in DBT profiles when opening non-DBT connection

---

mage_ai/data_preparation/repo_manager.py
mage_ai/server/utils/output_display.py
mage_ai/server/websocket.py

Fix variables dir from repo_config.
Priority:
1. 'variables_dir' from config_dict
2. os.getenv(MAGE_DATA_DIR_ENV_VAR)
3. repo_config.get('variables_dir')
4. 'variables_dir' from repo_config file
tested locally
cc:

[xy] Fix variables dir from repo_config.

---

docs/deploy/ci_cd/README.md
docs/deploy/terraform/AWS.md
templates/github_actions/build_and_deploy_to_aws_ecs.yml

[td] Improved AWS CI/CD template

---

scripts/deploy/terraform/gcp/main.tf
scripts/deploy/terraform/gcp/variables.tf

* Set min instance count to 1 for gcp.
* Increase memory for mage deployed on GCP.
tested locally
cc:

[xy] Set min instance count to 1 for gcp.

---

mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx

- See title.
- Tested locally and confirmed new logs automatically appear at 5s intervals.

[jk] Auto-refresh logs every 5 seconds

---

mage_ai/data_preparation/models/pipelines/integration_pipeline.py
mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/index.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

Show data preview for all selected streams.
TODO: fix line height spacing in data table when there are multiple streams

[dy] Fix source preview for multiple streams

---

mage_integrations/README.md
mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/__init__.py

[td] Update Salesforce tap

---

mage_ai/frontend/components/PipelineDetail/FileTabs/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/index.style.tsx
mage_ai/frontend/components/PipelineLayout/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Moved file editor tabs to subheader in Pipeline Editor in order to allow scrolling of file tabs and better visibility into open files.

[jk] Revised file editor tabs

---

SUMMARY.md
mage_ai/frontend/components/IntegrationPipeline/index.tsx

- Update docs.mage.ai with CI/CD page.
- Checked gitbook preview.

[jk] Update docs summary with CI/CD doc

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/index.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/interfaces/DataProviderType.ts
mage_ai/frontend/interfaces/IntegrationSourceType.ts

- See title.
Setting for Postgres source:
Setting for non-Postgres source:

[jk] Add log-based replication method for Postgres sources

---

mage_integrations/README.md
mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/bigquery/utils.py
mage_integrations/mage_integrations/destinations/sql/utils.py
mage_integrations/mage_integrations/sources/base.py
mage_integrations/requirements.txt

[td] Fix BigQuery ARRAY and JSON fields

---

mage_integrations/mage_integrations/connections/bigquery/__init__.py
mage_integrations/mage_integrations/connections/sql/base.py
mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/sources/base.py

[td] Add more logging to SQL source and destinations

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/index.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/shared/Table/index.style.tsx
mage_ai/frontend/components/shared/Table/index.tsx

- Add summary table of stream settings when there are multiple streams.
- Add key properties description.

[jk] Add streams summary

---

mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/oracle/components/Tooltip/TooltipWrapper.tsx
mage_ai/frontend/oracle/components/Tooltip/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_ai/frontend/utils/date.ts

- Allows user to quickly run a pipeline simply by clicking a button. This creates an `@once` schedule trigger and runs it immediately.

[jk] Run pipeline once button

---

mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_integrations/mage_integrations/destinations/base.py

[td] Parse record before validating

---

mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

- Renamed "Run pipeline once" button to "Run sync now"  and moved it to the Triggers page.
cc:

[jk] Move sync button to Triggers page

---

mage_ai/data_preparation/logging/logger_manager_factory.py
mage_ai/data_preparation/variable_manager.py

Not require boto3 and botocore when starting the server.
tested locally
cc:

[xy] Not require boto3 and botocore

---

mage_integrations/mage_integrations/destinations/base.py

[td] Improved parsing of nested objects for data integrations

---

Dockerfile
dev.Dockerfile
mage_integrations/requirements.txt

- Use custom fork of singer python so we can upgrade jsonschema package

[td] Data integrations uses custom singer python

---

scripts/deploy/terraform/gcp/db.tf
scripts/deploy/terraform/gcp/main.tf
scripts/deploy/terraform/gcp/variables.tf

Add postgres to gcp terraform.
tested locally
cc:

[xy] Add postgres to gcp terraform.

---

mage_ai/orchestration/db/__init__.py
mage_ai/orchestration/db/process.py

Create new session when creating a subprocess.
tested locally
cc:

[xy] Create new session when creating a subprocess.

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/components/Logs/Detail/index.tsx

- Parse json log messages.
- Add newlines in error messages.
- Hide unique conflict method setting when no unique constraints selected.
View parsed json log msg
Hide unique conflict method
Before newlines in error:
After newlines in error (added wherever there's a `\n`):

[jk] Json log parsing

---

.github/workflows/publish_docker_image.yml

Cache docker image build.
* https://docs.docker.com/build/building/cache/backends/gha/
* https://docs.docker.com/engine/reference/commandline/buildx_build/#cache-from
tested in github actions
cc:

[xy] Cache docker image build.

---

mage_ai/orchestration/db/process.py

Dispose engine before creating subprocess.
https://stackoverflow.com/questions/41279157/connection-problems-with-sqlalchemy-and-multiple-processes
tested locally
cc:

[xy] Dispose engine before creating subprocess.

---

mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/Logs/Detail/index.tsx
mage_ai/frontend/components/Logs/Toolbar/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx

- Fix type error in logs index page.
- Fix block type filters for integration pipeline logs (previously did not include blocks by stream).

[jk] Bugfix logs

---

Dockerfile
dev.Dockerfile

Not cache mage integrations installation
tested locally
cc:

[xy] Not cache mage integrations install.

---

mage_integrations/mage_integrations/sources/intercom/streams.py

Fix intercom comparison
testing locally
cc:

[xy] Fix intercom comparison

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/templates/testable.jinja
mage_ai/tests/data_preparation/test_templates.py

Allow integration pipelines to run with tests.
tested locally
cc:

[dy] Fix tests for integration pipelines

---

mage_ai/frontend/components/IntegrationPipeline/index.tsx

Change order of requests so that schema loads first.
tested locally
cc:

[dy] Change order of requests

---

docs/deploy/terraform/GCP.md
docs/guides/dbt/serve_docs.md

[dy] Add documentation for dbt docs

---

docs/guides/dbt/serve_docs.md

[dy] Update dbt docs

---

.github/workflows/publish_docker_image.yml

Reverts mage-ai/mage-ai#1432 before figuring out the caching issue.

Revert "[xy] Cache docker image build."

---

mage_ai/data_preparation/models/block/__init__.py

[dy] Add pipeline_uuid and block_uuid to global_vars

---

templates/github_actions/build_and_deploy_to_gcp_cloud_run.yml

As title.
tested with another repo

[dy] Add step to deploy to docs service

---

mage_ai/io/base.py
mage_ai/io/bigquery.py
mage_ai/shared/utils.py

Add alter table method to bigquery.
tested locally
cc:

[xy] Add alter table method to bigquery.

---

mage_ai/shared/utils.py

Fix float type conversion.
tested locally
cc:

[xy] Fix float type conversion.

---

docs/deploy/terraform/AWS.md
docs/deploy/terraform/Azure.md
docs/deploy/terraform/GCP.md
docs/deploy/terraform/README.md
mage_integrations/mage_integrations/sources/salesforce/README.md

[td] Update Terraform docs with new links

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/interfaces/IntegrationSourceType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/constants.py
mage_integrations/mage_integrations/sources/base.py
mage_integrations/mage_integrations/sources/catalog.py
mage_integrations/mage_integrations/sources/messages.py

[td] Disable column type check for streams

---

mage_ai/data_preparation/models/block/r/__init__.py

Fix r block exporter.
tested locally
cc:

[xy] Fix r block exporter.

---

mage_integrations/mage_integrations/sources/postgresql/__init__.py
mage_integrations/mage_integrations/sources/redshift/utils.py
mage_integrations/mage_integrations/sources/sql/base.py
mage_integrations/mage_integrations/sources/sql/utils.py

[td] Postgres source cast to timestamp when using bookmark

---

mage_ai/server/api/orchestration.py

Pass in logger to `create_block_runs` method.
tested locally
cc:

[dy] Pass in logger

---

mage_ai/server/api/orchestration.py

Didn't see that the PipelineScheduler was already imported in my previous PR.
cc:

[dy] Fix imports

---

mage_ai/orchestration/pipeline_scheduler.py

[td] Only update state when pipeline run has no block runs

---

mage_ai/data_integrations/logger/utils.py

Include data integration original timestamp in logs.
tested locally
cc:

[xy] Include data integration original timestamp in logs.

---

mage_integrations/mage_integrations/sources/constants.py
mage_integrations/mage_integrations/sources/postgresql/__init__.py
mage_integrations/mage_integrations/sources/sql/base.py

Fix UUID column type comparison.
tested locally
cc:

[xy] Fix UUID column type comparison.

---

mage_ai/data_preparation/templates/template.py

Fix template path in windows.
tested in windows
cc:

[xy] Fix template path in windows.

---

mage_ai/orchestration/pipeline_scheduler.py

Refresh pipeline run before scheduling so that it doesn't use session cached status.
tested locally
cc:

[xy] Refresh pipeline run before scheduling.

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx

- Indicate when a pipeline run is being canceled.

[jk] Show different run status when canceling pipeline

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/index.tsx

- Add column to "Streams summary" table that shows the number of columns selected out of total column count.

[jk] Columns selected summary

---

mage_ai/data_preparation/models/block/__init__.py
mage_integrations/mage_integrations/sources/salesforce/__init__.py
mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/__init__.py
mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/sync.py

Some improvements on salesforce source logging
* Improve logging for salesforce source
* Fix metrics counter for rows synced
tested locally
cc:

[xy] Improve salesforce source logging.

---

mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/sql/utils.py

Fix inserting json column into postgres.
tested locally
cc:

[xy] Fix inserting json column into postgres.

---

mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/orchestration/db/models.py
mage_ai/orchestration/metrics/pipeline_run.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/server/api/logs.py
mage_ai/server/api/orchestration.py
mage_ai/server/api/projects.py

[td] Data integration metrics

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/index.tsx

[jk] Hide stream summary until stream is selected

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
mage_ai/orchestration/execution_process_manager.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/server/api/orchestration.py

Add button and logic to retry incomplete blocks from the block runs page.
tested locally

[dy] Add button to retry failed blocks

---

mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/bigquery/utils.py
mage_integrations/mage_integrations/destinations/postgresql/__init__.py
mage_integrations/mage_integrations/destinations/postgresql/utils.py
mage_integrations/mage_integrations/destinations/sql/utils.py

[td] Improve support for JSONB in Postgres

---

mage_ai/frontend/interfaces/PipelineScheduleType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_ai/orchestration/db/models.py
mage_ai/server/api/orchestration.py

[jk] Show recent pipeline run status on Triggers page

---

mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

- When a pipeline schedule has interval `@once` and its latest pipeline run is finished, the pipeline schedule status is updated to `inactive`.

[jk] Update trigger status to inactive after run completion

---

mage_ai/frontend/components/IntegrationPipeline/SelectStreams/index.tsx

[jk] Make stream search case insensitive

---

mage_ai/data_integrations/logger/utils.py
mage_ai/data_preparation/models/pipelines/integration_pipeline.py
mage_integrations/mage_integrations/connections/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/bigquery/README.md
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/bigquery/templates/config.json

Small updates from stress testing Chargebee and BigQuery.
Removed `table` and added `location` to the BigQuery destination config.
tested locally

[dy] Update for Chargebee and BigQuery

---

mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.style.ts

[jk] Show scrollbar for button tabs

---

docs/deploy/terraform/AWS/terraform_apply_policy.json
docs/deploy/terraform/AWS/terraform_destroy_policy.json

Add new iam permissions for setting up rds.
tested locally
cc:

[xy] Add new iam permissions for setting up rds.

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx

[jk] Update condition for enabling partition keys for columns

---

mage_integrations/mage_integrations/destinations/base.py

[td] Don’t parse row if row is None

---

docs/deploy/terraform/GCP.md

Update the doc to set up HTTPs on GCP.
n/a
cc:

[xy] Update the doc to set up HTTPs on GCP.

---

mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/sources/chargebee/schemas/common/payment_sources.json

Use `TO_JSON` for JSON types. Also updated schema for one of the streams.
tested locally

[dy] Fix chargebee streams

---

mage_ai/cli/main.py
mage_ai/data_preparation/variable_manager.py
mage_ai/server/server.py
mage_ai/server/websocket.py

Fix global variable get and set. Use variables_dir to initialize VariableManager.
tested locally
cc:

[xy] Fix global variable get and set

---

mage_ai/data_preparation/templates/pipeline_execution/emr_bootstrap.sh

Add boto3 to emr_bootstrap.sh
tested creating emr cluster with this bootstrap script
cc:

[xy] Add boto3 to emr_bootstrap.sh

---

mage_ai/orchestration/db/models.py

Rollback transaction when it fails to commit.
tested locally
cc:

[xy] Rollback transaction when it fails to commit.

---

mage_ai/services/aws/emr/config.py

Set Ec2SubnetId when creating emr cluster.
tested locally
cc:

[xy] Set Ec2SubnetId when creating emr cluster.

---

mage_integrations/mage_integrations/destinations/sql/base.py

Fix sql data destination.
tested locally
cc:

[xy] Fix sql data destination.

---

mage_ai/data_integrations/logger/utils.py
mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/constants.py
mage_integrations/mage_integrations/destinations/mysql/__init__.py
mage_integrations/mage_integrations/destinations/postgresql/__init__.py
mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/destinations/sql/utils.py

Automatically add _mage_created_at and _mage_updated_at columns in destination table.
Tested locally
cc:

[xy] Add _mage_created_at and _mage_updated_at columns.

---

mage_integrations/mage_integrations/destinations/mysql/__init__.py
mage_integrations/mage_integrations/destinations/mysql/utils.py
mage_integrations/mage_integrations/destinations/sql/base.py

[td] Update MySQL destination columns

---

docs/data_integrations/README.md

[td] Add API as a source to the docs

---

mage_integrations/mage_integrations/sources/redshift/__init__.py
mage_integrations/mage_integrations/sources/sql/base.py

Only use bookmarks that are in bookmark_properties.
tested locally
cc:

[xy] Only use bookmarks that are in bookmark_properties.

---

mage_ai/data_preparation/storage/local_storage.py

Catch read json exception.
tested locally
cc:

[xy] Catch read json exception.

---

mage_ai/server/server.py

Fix more db session errors.
tested locally
cc:

[xy] Fix more db session errors.

---

mage_ai/data_integrations/sources/constants.py
mage_ai/server/api/logs.py
mage_integrations/mage_integrations/connections/google_analytics/__init__.py
mage_integrations/mage_integrations/sources/google_analytics/README.md
mage_integrations/mage_integrations/sources/google_analytics/__init__.py
mage_integrations/mage_integrations/sources/google_analytics/templates/config.json

Add google analytics source.
tested locally
cc:

[xy] Add google analytics source.

---

mage_ai/orchestration/db/__init__.py

Explicitly catch pending rollback error.
tested locally
cc:

[xy] Explicitly catch pending rollback error.

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/index.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/oracle/components/Panel/index.tsx
mage_ai/frontend/oracle/components/Tooltip/TooltipWrapper.tsx
mage_ai/frontend/oracle/components/Tooltip/index.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx
mage_ai/frontend/stories/oracle/components/Panel.stories.tsx

- Schema settings and config specific to individual features can be applied to all streams (or streams with the same feature).
Applying replication method and unique conflict method to all streams:
Applying schema settings for a specific feature to all streams (if the other stream has that feature):
Column header tooltip for new "All features" column:
cc:
@MageKai

[jk] Improved streams config for multiple streams

---

mage_ai/server/api/orchestration.py

Fix db session error for pipeline runs get endpoint.
tested locally
cc:

[xy] Fix db session error for pipeline runs get endpoint.

---

mage_integrations/mage_integrations/destinations/delta_lake/base.py
mage_integrations/mage_integrations/destinations/delta_lake/schema.py
mage_integrations/mage_integrations/sources/bigquery/__init__.py
mage_integrations/mage_integrations/sources/mysql/__init__.py

[td] Wrap columns in quotes when querying source

---

mage_ai/orchestration/db/process.py
mage_ai/server/scheduler_manager.py

* Not create additional session for scheduler
* Always close db connection.
tested locally
cc:

[xy] More fixes on postgres db

---

mage_ai/cluster_manager/gcp/cloud_run_service_manager.py

Create service using existing service as a template.
tested locally
cc:

[dy] Update service creation

---

mage_ai/data_integrations/logger/utils.py
mage_ai/data_integrations/utils/config.py
mage_ai/data_preparation/models/block/integration/__init__.py

Fix pagination for fetching data from source. Using offset in each subbatch query can cause issues since bookmark property's value could change between block runs.
* Update the state of source every time before executing the source block. 
tested locally
cc:

[xy] Fix pagination for fetching data from source.

---

mage_ai/cluster_manager/gcp/cloud_run_service_manager.py

Fix hopefully the final gcp bug so that services can be created.
tested locally
cc:

[dy] Fix gcp bug

---

Dockerfile
mage_ai/server/constants.py

[td] Explicit pip install of mage-ai version

---

mage_integrations/mage_integrations/destinations/bigquery/__init__.py

[td] Update TO_JSON appearing twice for BigQuery

---

.gitignore
mage_integrations/mage_integrations/destinations/snowflake/__init__.py

[td] Better escaping for newline characters

---

mage_ai/data_integrations/sources/constants.py
mage_ai/server/constants.py
mage_integrations/mage_integrations/sources/amazon_s3/README.md
mage_integrations/mage_integrations/sources/amazon_s3/__init__.py
mage_integrations/mage_integrations/sources/amazon_s3/templates/config.json
setup.py

[td] Add more sources

---

mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/server/constants.py
setup.py

[td] 0.7.40

---

mage_integrations/mage_integrations/destinations/snowflake/__init__.py

Add alter command for snowflake.
tested locally
cc:

[xy] Add alter command for snowflake.

---

mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/utils.py
mage_integrations/mage_integrations/destinations/sql/utils.py

* Fix column identifier for Snowflake destination
* Fix snowflake array
tested locally
cc:

[xy] More snowflake fixes

---

mage_ai/server/api/orchestration.py

Pass in variables to `initialize_states_and_runs`.
tested locally
cc:

[dy] Pass in variables

---

mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/sql/utils.py
mage_integrations/mage_integrations/sources/mysql/__init__.py

* Use backtick to escape mysql source column.
* Escape unique constraints in snowflake destination.
tested locally
cc:

[xy] Fix mysql source and snowflake unique constraints

---

mage_ai/data_preparation/models/block/integration/__init__.py
mage_ai/orchestration/pipeline_scheduler.py

Not set limit in last block run.
tested locally
cc:

[xy] Not set limit in last block run.

---

mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx

[jk] Remove gap between code blocks

---

docs/mint.json
docs/tutorials/etl/complete-project.mdx
docs/tutorials/load-api-data.mdx
docs/tutorials/train-model.mdx
docs/tutorials/train/complete-project.mdx

[td] Update links in docs

---

docs/getting-started/setup.mdx

Add commands to setup doc to create a postgresql docker container and connect to it.
tested locally

[dy] Add script to run postgres locally in docker

---

mage_ai/data_preparation/models/block/__init__.py

Provide better error message for circular reference detected.
Original error message
New error message
tested locally
cc:

[xy] Provide better error message for circular reference detected.

---

mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/server/constants.py
setup.py

- Improve better front-end parsing errors

[td] 0.7.42

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/executors/executor_factory.py
mage_ai/data_preparation/executors/gcp_cloud_run_block_executor.py
mage_ai/data_preparation/models/constants.py
mage_ai/data_preparation/repo_manager.py
mage_ai/services/gcp/cloud_run/cloud_run.py
mage_ai/services/gcp/cloud_run/config.py
requirements.txt
scripts/run_app.sh

Add gcp cloud run executor.
How to configure: set executor type to `gcp_cloud_run` in block conifg and add `executor_config`
```
executor_type: gcp_cloud_run
executor_config:
path_to_credentials_json_file: "..."
```
tested on gcp
cc:

[xy] Add gcp cloud run executor.

---

mage_ai/data_preparation/executors/gcp_cloud_run_block_executor.py

Fix gcp executor cmd
tested locally
cc:

[xy] Fix gcp executor cmd

---

mage_ai/frontend/components/ContextMenu/index.tsx

[jk] Fix duplicate click addEventListener

---

mage_ai/services/hightouch/config.py
mage_ai/services/hightouch/constants.py
mage_ai/services/hightouch/hightouch.py

Add hightouch client.
Example code:
```
from mage_ai.services.hightouch.hightouch import HightouchClient
client = HightouchClient(config=dict(api_key='api_key'))
syncs = client.list_syncs()
sync_id = syncs['data'][0]['id']
client.sync_and_poll(sync_id)
```
Example output:
```
Polling Hightouch Sync [id]. Current status: querying. 0% completed.
Polling Hightouch Sync [id]. Current status: success. 100% completed.
Sync request status: success. Polling complete
```
tested locally
cc:

[xy] Add hightouch client.

---

mage_ai/server/api/orchestration.py

Sort block runs by created_at.
tested locally
cc:

[xy] Sort block runs by created_at.

---

mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/server/constants.py
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
setup.py

- BigQuery: Improve MERGE matching when column values are NULL
- BigQuery: when transaction fails because of concurrent update, recreate table
cc:

[td] 0.7.43

---

mage_ai/frontend/components/ErrorPopup/index.style.tsx
mage_ai/frontend/components/ErrorPopup/index.tsx
mage_ai/frontend/interfaces/FileType.ts
mage_ai/frontend/oracle/elements/Link/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Update error message popup to make it less verbose and a bit less daunting.
- Added link to open pipeline `metadata.yaml` config file.
cc:
@tommydangerous @wangxiaoyou1993

[jk] Update error message popup

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/errors.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/errors/base.py
mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/orchestration/db/models.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/shared/array.py
mage_integrations/README.md

[td] Dynamic blocks

---

mage_ai/server/constants.py
setup.py

[td] 0.7.45

---

docs/mint.json
docs/production/observability/alerting-teams.mdx
mage_ai/data_preparation/templates/repo/metadata.yaml
mage_ai/orchestration/notification/config.py
mage_ai/orchestration/notification/sender.py
mage_ai/services/teams/config.py
mage_ai/services/teams/teams.py
mage_ai/tests/orchestration/notification/constants.py
mage_ai/tests/orchestration/notification/test_config.py
mage_ai/tests/orchestration/notification/test_sender.py

Revert "Revert "Feature/added teams webhook""

---

mage_ai/server/constants.py
setup.py

- Alerting via Microsoft Teams

[td] 0.7.46

---

mage_ai/frontend/utils/models/pipelineRun.ts

[td] Handle no block runs on sync page

---

mage_ai/data_integrations/utils/config.py

Fix getting catalog dict by stream id
tested locally
cc:

[xy] Fix getting catalog dict by stream id

---

mage_ai/orchestration/errors.py
mage_ai/orchestration/notification/sender.py
mage_ai/orchestration/pipeline_scheduler.py

[td] When memory usage is 95% or more, stop pipeline runs

---

mage_ai/server/constants.py
setup.py

- Log heartbeat
- Log CPU and memory
- If memory usage >= 95%, stop pipeline runs

[td] 0.7.47

---

mage_integrations/README.md
mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/bigquery/utils.py

[td] De-dupe rows for BigQuery before constructing queries

---

mage_integrations/mage_integrations/destinations/bigquery/utils.py

[td] Only remove duplicates if unique constraint

---

setup.py

Add kubernetes to setup.py
tested locally
cc:

[dy] Add kubernetes

---

mage_ai/server/constants.py
setup.py

Includes kubernetes as a dependency.
cc:

[dy] Bump to 0.7.48

---

mage_ai/data_integrations/logger/utils.py
mage_ai/data_integrations/utils/scheduler.py
mage_ai/data_preparation/models/block/integration/__init__.py
mage_ai/data_preparation/models/pipelines/integration_pipeline.py
mage_ai/data_preparation/models/pipelines/utils.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/server/constants.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py
mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/bigquery/utils.py
setup.py

- Remove heartbeat
- Data integrations will read and write to disk to optimize memory usage

[td] 0.7.48

---

mage_ai/server/constants.py
setup.py

- Remove heartbeat
- Data integrations will read and write to disk to optimize memory usage

[td] 0.7.49

---

mage_ai/orchestration/pipeline_scheduler.py
mage_ai/server/constants.py
setup.py

[td] 0.7.50

---

mage_integrations/mage_integrations/destinations/base.py

[td] Read lines and process records in batches

---

mage_ai/data_preparation/models/block/integration/__init__.py
mage_ai/server/constants.py
mage_integrations/mage_integrations/sources/chargebee/streams/base.py
setup.py

- Constantly display logs from source process

[td] 0.7.51

---

mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/delta_lake_s3/__init__.py

[td] Fix delta lake region issues

---

mage_integrations/mage_integrations/destinations/bigquery/README.md
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/bigquery/templates/config.json
mage_integrations/mage_integrations/destinations/bigquery/utils.py

[td] Automatically update column types in bigquery

---

mage_integrations/mage_integrations/destinations/base.py

[td] Fix tags reference

---

mage_ai/data_integrations/logger/utils.py
mage_ai/orchestration/pipeline_scheduler.py
mage_integrations/mage_integrations/destinations/base.py

[td] Improve log message

---

docs/developing-in-the-cloud/cloud-dev-environments/cloud-run.mdx
docs/mint.json

[dy] Update mint.json

---

docs/developing-in-the-cloud/cloud-dev-environments/kubernetes.mdx
docs/developing-in-the-cloud/cloud-dev-environments/overview.mdx
docs/mint.json
mage_ai/server/constants.py
setup.py

Bump to 0.7.52 to include kubernetes multi dev change to pass mage connection url environment variable.
tested locally
cc:

[dy] Bump version to 0.7.52

---

mage_ai/server/constants.py
setup.py

Support GKE connection to CloudSQL.
cc:

[dy] Bump to 0.7.53

---

docs/developing-in-the-cloud/cloud-dev-environments/kubernetes.mdx

[dy] Add table to docs

---

docs/developing-in-the-cloud/cloud-dev-environments/kubernetes.mdx

[dy] One more docs update

---

mage_ai/orchestration/db/__init__.py

Update connection url logic to not use `connect_args` for cloud sql.
cc:

[dy] Remove connect args

---

mage_ai/server/constants.py
setup.py

Bump to 0.7.55 to include a small cloud sql fix.
cc:

[dy] Bump 0.7.55

---

docs/production/observability/alerting-teams.mdx

Fix doc for alerting-teams.
tested locally
cc:

[xy] Fix doc for alerting-teams.

---

docs/mint.json
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

[td] Add Amplitude public API key to docs

---

mage_ai/orchestration/db/models.py
mage_ai/server/constants.py
setup.py

- Fix front-end API to not fetch if block UUID is undefined
- Update logging for nested files

[td] 0.7.56

---

docs/mint.json

[td] Update docs meta image

---

mage_ai/data_integrations/logger/utils.py
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/models/block/integration/__init__.py
mage_ai/data_preparation/models/block/r/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/shared/stream.py
mage_ai/orchestration/pipeline_scheduler.py

Add tags to logs.
* block execution
* integration block execution
* dbt block execution
tested locally

[xy] Add tags to logs.

---

mage_ai/frontend/api/index.ts
mage_ai/frontend/api/utils/use.ts
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/server/api/orchestration.py
mage_ai/server/constants.py
setup.py

- Only require token when trigger is API type

[td] 0.7.57

---

mage_integrations/mage_integrations/sources/postgresql/__init__.py

Fix logical replication for postgres.
* Fetch columns directly from the table since Relation is not always there
* Write flush_lsn back to db
* Verify whether message's lsn is larger than start lsn
tested locally
cc:

[xy] Fix logical replication for postgres.

---

mage_integrations/mage_integrations/sources/base.py

Reduce unnecessary logs for writing final record.
tested locally
cc:

[xy] Reduce unnecessary logs for writing final record.

---

docs/data-integrations/sources/postgresql.mdx
mage_integrations/mage_integrations/sources/postgresql/README.md
mage_integrations/mage_integrations/sources/postgresql/__init__.py
mage_integrations/mage_integrations/sources/postgresql/templates/config.json

Make replication slot name configurable and update the doc.
tested locally
cc:

[xy] Make replication slot name configurable.

---

mage_ai/frontend/components/DependencyGraph/constants.ts
mage_ai/frontend/components/DependencyGraph/index.style.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx

- Allow user to add dependencies in Pipeline Editor dependency graph by dragging from a block to a another block.
- Allow user to remove dependencies by clicking on an edge (line connecting nodes) and clicking on the `X` icon.
- User adds downstream dependency by clicking on a block's port (the white circle) and dragging the arrow onto another block.

[jk] Drag and drop dependency graph

---

mage_ai/data_preparation/executors/block_executor.py

Not run tests for integration transformer since we don't save the variable. Running tests caused errors.
tested locally
cc:

[xy] Not run tests for integration transformer.

---

docs/guides/streaming-pipeline.mdx
docs/production/deploying-to-cloud/digitalocean/setup.mdx
docs/production/deploying-to-cloud/using-terraform.mdx

Add doc for deploying Mage to DigitalOcean
n/a
cc:

[xy] Add doc for deploying Mage to DigitalOcean

---

docs/mint.json

Add digitalocean doc to mint json.
n/a
cc:

[xy] Add digitalocean doc to mint json.

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
mage_ai/frontend/utils/models/block.ts
mage_ai/server/api/blocks.py
mage_ai/server/constants.py
setup.py

- Improve UI to always show more actions
- Improve dynamic block tests
- Add more UI elements for dynamic blocks

[td] 0.7.58

---

mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx

[jk] Fix z-index dropdown issues

---

mage_ai/orchestration/pipeline_scheduler.py

Fix the tags for heartbeat logs and metrics calculation logs.
tested locally
cc:

[xy] Fix the tags for some logs.

---

mage_ai/data_preparation/models/block/integration/__init__.py

Throw subprocess exception so it doesn't silently fail.
tested locally
cc:

[xy] Throw subprocess exception.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/utils/models/output.ts
mage_ai/server/constants.py
mage_ai/server/utils/output_display.py
mage_integrations/mage_integrations/sources/sql/base.py
setup.py

- Allow all SQL columns to be used as a bookmark
- Run tests when running block in notebook
No tests
Successful tests
Failed tests

[td] 0.7.60

---

docs/design/data-loading.mdx
mage_ai/io/google_cloud_storage.py

Add doc for googlecloudstorage.
tested locally
cc:

[xy] Add doc for googlecloudstorage.

---

mage_integrations/mage_integrations/destinations/postgresql/utils.py

[td] Escape slash double quotes with double slash

---

mage_ai/orchestration/db/__init__.py

Retry failed db query.
tested locally
cc:

[xy] Retry failed db query.

---

mage_ai/server/scheduler_manager.py
mage_ai/server/server.py

Improve scheduler stability. Use tornado PeriodicCallback to check scheduler status and restart from failure: https://www.tornadoweb.org/en/stable/ioloop.html#tornado.ioloop.PeriodicCallback
tested locally
cc:

[xy] Improve scheduler stability.

---

mage_integrations/mage_integrations/destinations/postgresql/utils.py

[td] Escape single quotes for JSON array in PostgreSQL

---

mage_ai/autocomplete/utils.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/file.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/storage/base_storage.py
mage_ai/data_preparation/storage/local_storage.py
mage_ai/data_preparation/storage/s3_storage.py
mage_ai/data_preparation/variable_manager.py
mage_ai/server/api/autocomplete_items.py
mage_ai/server/api/data_providers.py
mage_ai/server/api/projects.py
mage_ai/server/api/widgets.py
mage_ai/server/server.py
requirements.txt

Improve API perf using asyncio to reduce blocking requests. Blocking requests could cause healthcheck requests timeout and app crash on cloud.
Endpoints updated to be async
* GET a list of pipelines: `/api/pipelines`
* GET pipeline by uuid: `/api/pipeline/[uuid]`
* GET `/api/autocomplete_items`
* GET `/api/data_providers`
* GET `/api/pipelines/[uuid]/widgets`
* PUT `/api/pipelines/[uuid]?update_content=true`
TODO
tested locally
cc:

[xy] Improve API perf using asyncio.

---

mage_ai/io/base.py
mage_ai/server/constants.py
mage_ai/shared/parsers.py
mage_integrations/mage_integrations/sources/bigquery/README.md
mage_integrations/mage_integrations/sources/mysql/README.md
mage_integrations/mage_integrations/sources/postgresql/README.md
mage_integrations/mage_integrations/utils/parsers.py
setup.py

- Improve data integration docs
- Update IO

[td] 0.7.61

---

mage_ai/shared/parsers.py
mage_integrations/mage_integrations/sources/messages.py
mage_integrations/mage_integrations/utils/parsers.py

*  Log message json serializtion error.
* Fix json serialization for date. The class of datetime object's isoformat is `builtin_function_or_method`.
tested locally
cc:

[xy] Fix message serialization for datetime

---

mage_ai/orchestration/db/models.py

* Retry failed db query in scheduler: `active_schedules` and `active_runs`
tested locally
cc:

[xy] Improve scheduler stability

---

mage_ai/services/aws/ecs/ecs.py

Wait for ECS task completion in ECS executor to fix duplicate ECS tasks issue.
tested locally
cc:

[xy] Wait for ECS task completion.

---

mage_integrations/mage_integrations/sources/freshdesk/tap_freshdesk/__init__.py
mage_integrations/mage_integrations/sources/freshdesk/tap_freshdesk/schemas/conversations.json
mage_integrations/mage_integrations/sources/freshdesk/tap_freshdesk/schemas/tickets.json

[td] Sync conversations attachments

---

mage_ai/data_preparation/models/block/__init__.py

Get outputs regardless of status.
tested locally
cc:

[xy] Get outputs regardless of status.

---

docs/getting-started/setup.mdx
docs/production/ci-cd.mdx
mage_integrations/README.md

[td] Update docs for Docker settings

---

docs/data-integrations/overview.mdx
mage_ai/data_integrations/destinations/constants.py
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/constants.py
mage_integrations/mage_integrations/connections/postgresql/README.md
mage_integrations/mage_integrations/connections/trino/__init__.py
mage_integrations/mage_integrations/connections/trino/connection_wrapper.py
mage_integrations/mage_integrations/destinations/postgresql/__init__.py
mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/destinations/sql/utils.py
mage_integrations/mage_integrations/destinations/trino/README.md
mage_integrations/mage_integrations/destinations/trino/__init__.py
mage_integrations/mage_integrations/destinations/trino/connectors/postgresql.py
mage_integrations/mage_integrations/destinations/trino/templates/config.json
mage_integrations/mage_integrations/destinations/trino/utils.py
mage_integrations/requirements.txt
setup.py

- Added destination Trino with support for PostgreSQL catalog

[td] 0.7.64

---

mage_ai/data_integrations/sources/constants.py
mage_integrations/mage_integrations/sources/azure_blob_storage/README.md
mage_integrations/mage_integrations/sources/azure_blob_storage/__init__.py
mage_integrations/mage_integrations/sources/azure_blob_storage/templates/config.json
mage_integrations/requirements.txt

Add Azure Blob Storage source.
tested locally
cc:

[xy] Add Azure Blob Storage source.

---

mage_integrations/mage_integrations/sources/base.py
mage_integrations/mage_integrations/sources/postgresql/__init__.py
mage_integrations/mage_integrations/sources/sql/base.py

Use full table sync for intial sync of logical replication.
tested locally
cc:

[xy] Use full table sync for intial sync of logical replication.

---

docs/data-integrations/overview.mdx

[td] Add Zendesk to docs

---

mage_integrations/mage_integrations/sources/sql/base.py

Fix count records in postgres source.
tested locally
cc:

[xy] Fix count records in postgres source.

---

docs/data-integrations/overview.mdx
mage_integrations/mage_integrations/sources/azure_blob_storage/README.md

Update doc for azure blob storage.
n/a
cc:

[xy] Update doc for azure blob storage.

---

mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runs.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runtime.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/monitors/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx

Fix url params include_content and include_outputs
tested locally
cc:

[xy] Fix url params include_content and include_outputs

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/FileEditor/utils.ts
mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/components/PipelineLayout/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/oracle/elements/Text/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runs.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runtime.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/monitors/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx

- Delete block file
- Show error message if block file path doesn’t exist but is still in the pipeline
- Drag block files and drop them into pipeline to add them to pipeline

[td] Improve pipeline block errors and file browser UI

---

mage_ai/server/constants.py
setup.py

- Delete block file
- Show error message if block file path doesn’t exist but is still in the pipeline
- Drag block files and drop them into pipeline to add them to pipeline

[td] 0.7.65

---

templates/gitlab_cicd/aws.gitlab-ci.yml

Add gitlab aws template
Required variables in `Settings > CI/CD` Variables
* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY
* AWS_DEFAULT_REGION
tested with a test repo
cc:

[xy] Add gitlab aws template

---

docs/production/deploying-to-cloud/gcp/setup.mdx

[td] Fix GCP resources link

---

mage_ai/services/stitch/config.py
mage_ai/services/stitch/constants.py
mage_ai/services/stitch/stitch.py

Add stitch client.
Sample code
```
from mage_ai.services.stitch.stitch import StitchClient
client= StitchClient(config=dict(access_token=access_token))
client.start_replication_job(source_id)
```
testing locally
cc:

[xy] Add stitch client.

---

docs/integrations/stitch.mdx

Add stitch doc.
tested locally
cc:

[xy] Add stitch doc.

---

docs/guides/data-integration-pipeline.mdx
docs/integrations/stitch.mdx
docs/mint.json

[td] Show stitch docs

---

mage_ai/orchestration/pipeline_scheduler.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

Not send notification on pipeline run success to reduce spams.
tested locally
unit test
cc:

[xy] Not send notification on pipeline run success.

---

mage_ai/data_integrations/utils/config.py
mage_ai/data_preparation/models/block/integration/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/pipelines/integration_pipeline.py
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/ErrorPopup/index.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/constants.py
mage_ai/tests/data_preparation/models/test_pipeline.py
setup.py

- Re-use data integration source blocks
- Re-use data integration destination blocks
- Support dragging and dropping a file onto a data integration pipeline

[td] 0.7.66

---

docs/integrations/stitch.mdx
mage_ai/services/stitch/constants.py
mage_ai/services/stitch/stitch.py

Poll status for stitch replication job.
* Poll status for extraction job
* Poll status for load jobs (for each stream)
tested locally
cc:

[xy] Poll status for stitch replication job.

---

mage_ai/server/constants.py
setup.py

[td] 0.7.67

---

mage_ai/data_integrations/utils/config.py

[td] 0.7.67 retry

---

mage_ai/orchestration/pipeline_scheduler.py
mage_ai/server/constants.py
setup.py

Don’t divide by 0 if application cannot get CPU or memory from system.
This fixes issue https://github.com/mage-ai/mage-ai/issues/1756

[td] 0.7.68

---

mage_ai/services/stitch/constants.py
mage_ai/services/stitch/stitch.py

Fetch stitch loads with pagination.
tested locally
cc:

[xy] Fetch stitch loads with pagination.

---

mage_ai/frontend/components/RuntimeVariables/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

Fixes this issue: https://github.com/mage-ai/mage-ai/issues/1760

[td] Fix trigger variables to show all

---

docs/production/ci-cd/local-cloud/github-actions.mdx
docs/production/ci-cd/local-cloud/gitlab-ci-cd.mdx
docs/production/deploying-to-cloud/gcp/setup.mdx

[td] Improve GCP secrets docs

---

mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/server/constants.py
mage_ai/services/stitch/stitch.py
setup.py

- Press enter to save block name
- Fix: https://github.com/mage-ai/mage-ai/issues/1760
- Fix: https://github.com/mage-ai/mage-ai/issues/1756
- Log Stitch sync job completion percentage
```
Polling Stitch load status for source 104567: 42.86% (3/7). Completed streams: ['...']. Running streams: ['...'].
```

[td] 0.7.69

---

mage_ai/orchestration/pipeline_scheduler.py
mage_integrations/mage_integrations/sources/amplitude/__init__.py

Amplitude sources are failing.
tested locally
cc:

[dy] Small fix

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/utils.py

Improve performance for saving block outputs
* Not save null data
* Consolidate multiple micro message into one message.
This reduced the time for updating the test pipeline from ~2.2s to ~700ms, and reduced the time of loading the test pipeline from ~1.7s to ~600ms
tested locally
original messages
consolidated message
cc:

[xy] Improve performance for saving block outputs

---

mage_ai/orchestration/execution_process_manager.py

Not kill process group when cancelling block run processes.
tested locally
cc:

[xy] Not kill process group.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/constants.py
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/interfaces/FileType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/api/blocks.py
mage_ai/server/constants.py
mage_ai/services/stitch/stitch.py
setup.py

- Automatically complete Stitch load job after N seconds
- Delete blocks other than python language

[td] 0.7.70

---

mage_ai/frontend/components/ErrorPopup/index.style.tsx
mage_ai/frontend/components/ErrorPopup/index.tsx

[jk] Add traceback to error message

---

mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/interfaces/FileType.ts
mage_ai/server/constants.py
mage_ai/server/websocket_server.py
mage_ai/utils/code.py
setup.py

- Edit files from non-standard folders (e.g. utils)
- Automatically reload all imported modules

[td] 0.7.71

---

mage_ai/frontend/components/IntegrationPipeline/SelectStreams/index.tsx
mage_ai/frontend/components/shared/Table/index.style.tsx
mage_ai/frontend/components/shared/Table/index.tsx

- Allow user to select all streams from integration source by clicking single checkbox.
- We show a warning when more than 50 streams are selected because the app takes a long time to load and render when many streams are selected. To be optimized in separate PR.
cc:
@wangxiaoyou1993  @dy46

[jk] Select all streams

---

mage_integrations/mage_integrations/sources/amazon_s3/README.md

[xy] Update s3 doc.

---

mage_ai/server/constants.py
setup.py

- Bump to 0.7.72
- Includes feature for allowing user to select all streams at once.

[jk] Bump to version 0.7.72

---

mage_integrations/mage_integrations/sources/amazon_s3/__init__.py

Not discover duplicate catalog entries.
tested locally
cc:

[xy] Not discover duplicate catalog entries.

---

mage_ai/data_preparation/templates/repo/metadata.yaml
mage_ai/orchestration/notification/config.py
mage_ai/orchestration/notification/sender.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/tests/orchestration/notification/constants.py
mage_ai/tests/orchestration/notification/test_sender.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

Update notification config so that the users can configure when the alerts are sent. Current options are `trigger_failure`, `trigger_success`, and `trigger_passed_sla`. By default, we will add `trigger_failure` and `trigger_passed_sla`.
tested locally

[dy] Update notification config

---

mage_integrations/mage_integrations/sources/postgresql/__init__.py

Support update in logical replication.
tested locally
cc:

[xy] Support update in logical replication.

---

mage_ai/services/stitch/stitch.py

[td] Read Stitch logs to check which streams have syncs

---

mage_integrations/mage_integrations/destinations/constants.py
mage_integrations/mage_integrations/sources/base.py
mage_integrations/mage_integrations/sources/postgresql/__init__.py

* Handle delete message from postgres logical replication.
* Add `_mage_deleted_at` column
* Fix `lsn` bookmark
tested locally
cc:

[xy] Handle delete message from postgres logical replication.

---

docs/production/observability/alerting-email.mdx
docs/production/observability/alerting-slack.mdx
docs/production/observability/alerting-teams.mdx

Update docs for the `alert_on` section.
docs
cc:

[dy] Update notification config docs

---

docs/community/contributing.mdx

Change url to updated Roadmap 2023 Q1
Changes link
Tested url to correct path

Updated roadmap link

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/interfaces/PipelineRunType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/orchestration/db/models.py
mage_ai/server/api/orchestration.py

- Remove individual requests for pipeline schedules.
**Before** (note the numbers in the Networks tab which indicates individual requests for pipeline schedules):
**After** (not nearly as many requests):

[jk] Pipeline schedule fetching

---

mage_ai/frontend/components/ErrorPopup/index.tsx
mage_ai/frontend/components/PipelineLayout/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx

[jk] Allow pressing escape key to close error message

---

scripts/run_app.sh

Install dependencies when starting app in docker.
tested locally
cc:

[xy] Install dependencies when starting app in docker.

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/templates/pipeline_execution/spark_script.jinja
mage_ai/server/utils/output_display.py

Pass in `global_vars` to the test functions.
tested locally

[dy] Add global vars to test functions

---

docs/getting-started/kernels.mdx
docs/getting-started/setup.mdx
docs/guides/integrate-mage-airflow.mdx
docs/guides/streaming-pipeline.mdx
docs/integrations/spark-pyspark.mdx
docs/introduction/overview.mdx
docs/production/ci-cd/local-cloud/repository-setup.mdx
docs/production/deploying-to-cloud/digitalocean/setup.mdx
docs/tutorials/quick_start/setup.md

Update the doc to start mage app with docker command.
https://github.com/mage-ai/mage-ai/pull/1798
n/a
cc:

[xy] Update the doc to start mage app with docker command.

---

mage_ai/orchestration/db/__init__.py
mage_ai/orchestration/db/constants.py
mage_ai/orchestration/db/models.py
mage_ai/orchestration/pipeline_scheduler.py

Retry failed db calls in scheduler.
tested locally
cc:

[xy] Retry failed db calls in scheduler.

---

docs/integrations/metaplane.mdx
docs/mint.json

[td] Add docs for metaplane

---

docs/mint.json
docs/production/ci-cd/local-cloud/buildkite.mdx

[td] Buildkite CI/CD templates

---

templates/cicd/buildkite/deploy-ecs.sh
templates/cicd/buildkite/pipeline.yml

[td] Add Buildkite template files

---

mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/constants.py
mage_ai/services/metaplane/metaplane.py
setup.py

- Improve Metaplane service
- Manually name dbt block for running multiple models

[td] 0.7.77

---

mage_integrations/mage_integrations/destinations/mysql/utils.py

This change was causing issues in MySQL destinations.
tested locally

[dy] Revert BIGINT change

---

mage_integrations/mage_integrations/tests/sources/sql/test_base.py
mage_integrations/mage_integrations/tests/sources/test_base.py

[jk] Add unit tests for sources sql base file

---

mage_integrations/mage_integrations/sources/paystack/streams/base.py

Forgot to commit my change to split the logs in the paystack source.
log changes
cc:

[dy] Update log lengths

---

mage_integrations/mage_integrations/sources/postmark/tap_postmark/cleaners.py
mage_integrations/requirements.txt

[td] Fix MutableMapping imports

---

mage_integrations/mage_integrations/sources/base.py
mage_integrations/mage_integrations/sources/postmark/__init__.py
mage_integrations/mage_integrations/sources/postmark/tap_postmark/sync.py

[td] Fix Postmark source

---

mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_integrations/mage_integrations/sources/postmark/templates/config.json

[td] When clicking apply in schema table, update pipeline metadata

---

mage_integrations/mage_integrations/destinations/sql/constants.py

[td] Add more words to the SQL reserved words list

---

mage_ai/server/constants.py
setup.py

* Add Paystack source
* Various fixes
* https://github.com/mage-ai/mage-ai/pull/1834
* https://github.com/mage-ai/mage-ai/pull/1836
* https://github.com/mage-ai/mage-ai/pull/1837
* https://github.com/mage-ai/mage-ai/pull/1838
bump version
cc:

[dy] Bump to 0.7.78

---

mage_integrations/mage_integrations/tests/sources/postgresql/test_postgresql.py
mage_integrations/mage_integrations/tests/sources/sql/test_base.py

[jk] Add unit test for postgres source

---

mage_integrations/mage_integrations/connections/trino/__init__.py
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/trino/README.md
mage_integrations/mage_integrations/destinations/trino/__init__.py
mage_integrations/mage_integrations/destinations/trino/connectors/base.py

Add base trino connector. SQL syntax: https://trino.io/docs/current/sql.html
Add example config for Iceberg connector.
tested with Iceberg connector
cc:

[xy] Add base trino connector.

---

docs/guides/r-blocks.mdx
mage_ai/data_preparation/models/block/r/__init__.py
mage_ai/data_preparation/models/block/r/templates/data_exporter.jinja
mage_ai/data_preparation/models/block/r/templates/data_loader.jinja
mage_ai/data_preparation/models/block/r/templates/transformer.jinja

Support global vars in R blocks.
The variables can be accessed via `global_vars['key']` like `global_vars['execution_date']`.
tested locally
cc:

[xy] Support global vars in R blocks.

---

docs/developing-in-the-cloud/cloud-dev-environments/kubernetes.mdx
mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/frontend/components/Manage/ConfigureInstance.tsx
mage_ai/frontend/pages/manage/index.tsx
mage_ai/server/api/clusters.py

Allow users to add custom config for their mage container in kubernetes.
tested on gke

[dy] Add config for environment variables

---

docs/data-integrations/overview.mdx

Add paystack to integration overview docs
cc:

[dy] Add paystack

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/streaming/sources/base.py
mage_ai/streaming/sources/kinesis.py
mage_ai/streaming/sources/source_factory.py

* Support reading from multiple shards
* Support checkpoint
tested locally
cc:

[xy] Support reading from multiple shards and checkpoint for Kinesis

---

mage_ai/cluster_manager/kubernetes/workload_manager.py

Update location of the `serviceAccountName` field.
tested locally
cc:

[dy] Update location for `serviceAccountName`

---

mage_ai/frontend/components/PipelineDetail/Syncs/SyncRowDetail/index.tsx
mage_ai/orchestration/execution_process_manager.py
mage_ai/orchestration/metrics/pipeline_run.py
mage_ai/orchestration/pipeline_scheduler.py
mage_integrations/mage_integrations/destinations/sql/constants.py
mage_integrations/mage_integrations/destinations/sql/utils.py
mage_integrations/mage_integrations/sources/base.py

[td] Improve data integration error parsing

---

mage_integrations/mage_integrations/tests/sources/bigquery/test_bigquery.py

[jk] Add unit test for bigquery source

---

mage_integrations/mage_integrations/tests/sources/mysql/test_mysql.py

[jk] Add unit test for mysql source

---

mage_ai/server/constants.py
mage_ai/shared/utils.py
setup.py

[td] 0.7.79

---

mage_ai/server/constants.py
setup.py

[td] 0.7.81

---

kube/mage-pod.yaml

Add kube yaml to deploy mage to k8s pod.
tested locally
cc:

[xy] Add kube yaml to deploy mage to k8s pod.

---

docs/getting-started/setup.mdx
docs/production/configuring-production-settings/compute-resource.mdx

Update doc for running in k8s cluster.
n/a
cc:

[xy] Update doc for running in k8s cluster.

---

mage_ai/server/constants.py
setup.py

[td] 0.7.83

---

mage_integrations/mage_integrations/sources/facebook_ads/README.md
mage_integrations/mage_integrations/sources/facebook_ads/__init__.py
mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/__init__.py
mage_integrations/mage_integrations/sources/hubspot/__init__.py
mage_integrations/mage_integrations/sources/hubspot/tap_hubspot/__init__.py
mage_integrations/mage_integrations/sources/hubspot/tap_hubspot/constants.py

[td] Improve automatic stream settings

---

mage_integrations/mage_integrations/sources/hubspot/tap_hubspot/__init__.py
mage_integrations/mage_integrations/sources/linkedin_ads/README.md
mage_integrations/mage_integrations/sources/outreach/templates/config.json

[td] Improve HubSpot config template

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/variable_manager.py
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/server.py
mage_ai/tests/data_preparation/models/test_pipeline.py

Update location of global variables to be stored in the `metadata.yaml` file of the pipeline. This way, a user can update the values through code in addition to through the UI.
tested locally

[dy] Modify global variables in code

---

docs/about/releases.mdx
mage_ai/frontend/components/shared/Header/index.tsx

[td] Improve download Mage button link

---

docs/development/troubleshooting.mdx
docs/mint.json

[td] Troubleshooting docs

---

Dockerfile
dev.Dockerfile
mage_integrations/mage_integrations/connections/mssql/__init__.py
mage_integrations/mage_integrations/sources/mssql/README.md
mage_integrations/mage_integrations/sources/mssql/__init__.py
mage_integrations/mage_integrations/sources/mssql/templates/config.json
mage_integrations/mage_integrations/sources/sql/base.py
mage_integrations/requirements.txt

Add microsoft sql server source.
tested locally
cc:

[xy] Add microsoft sql server source.

---

mage_integrations/mage_integrations/sources/sql/base.py

Include UNIQUE column into unique constraints.
https://www.sqlshack.com/commonly-used-sql-server-constraints-not-null-unique-primary-key/
tested locally
cc:

[xy] Include UNIQUE column into unique constraints.

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/variable_manager.py
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/server.py
mage_ai/tests/data_preparation/models/test_pipeline.py

Reverts mage-ai/mage-ai#1861
Bug
```
I make a POST request to http://xx.xx.xx.xx/api/pipelines/linkedin_ads/variables with
{"variable":{"name":"test","value":1}}
and the response is
{"variables": []}
status code 200
```
cc: @dy46

Revert "[dy] Modify global variables in code"

---

docs/data-integrations/overview.mdx
mage_ai/data_integrations/sources/constants.py

Add Microsoft SQL Server to UI.
tested locally
cc:

[xy] Add Microsoft SQL Server to UI.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.7.84.
Changes included
* https://github.com/mage-ai/mage-ai/pull/1867
* https://github.com/mage-ai/mage-ai/pull/1868
* https://github.com/mage-ai/mage-ai/pull/1870
* https://github.com/mage-ai/mage-ai/pull/1871
* https://github.com/mage-ai/mage-ai/pull/1873
* https://github.com/mage-ai/mage-ai/pull/1876
* https://github.com/mage-ai/mage-ai/pull/1877
n/a
cc:

[xy] Bump version to 0.7.84.

---

mage_ai/server/api/backfills.py

Parse backfill datetime strings in API.
tested locally
cc:

[xy] Parse backfill datetime strings in API.

---

docs/design/core-abstractions.mdx
docs/mint.json
docs/orchestration/backfills/guides.mdx
docs/orchestration/backfills/overview.mdx

[td] Backfill docs

---

mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/destinations/trino/connectors/base.py

Enforce unique constraints for Trino when inserting rows.
tested locally
cc:

[xy] Enforce unique constraints for Trino when inserting rows.

---

.github/workflows/build_and_test.yml
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/mysql.py
mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/data_preparation/models/block/sql/redshift.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/io/redshift.py
mage_ai/io/utils.py
mage_ai/io/utils/sql.py
mage_ai/shared/utils.py
mage_integrations/requirements.txt
requirements.txt

[td] dbt Redshift support

---

mage_integrations/mage_integrations/destinations/trino/connectors/base.py
mage_integrations/mage_integrations/sources/sql/base.py

* Fix merge command for trino destination.
* Enable using datetime columns as bookmark columns.
tested locally
cc:

[xy] Fix trino merge cmd and allow using datetime as bookmarks

---

mage_integrations/mage_integrations/sources/sql/utils.py
mage_integrations/mage_integrations/utils/parsers.py

Fix json serialization for uuid column.
tested locally
cc:

[xy] Fix json serialization for uuid column.

---

mage_integrations/mage_integrations/sources/bigquery/__init__.py

Made several minor changes to the code:
* Added type hints to the function, properties and class definition.
* Refined the way the query variable is updated to use the += operator instead of reassigning a new value to the variable.
* Changed the list(map(lambda column: f'{column}', columns)) to a list comprehension [f'{column}' for column in columns]
CI
cc:

Minor code refinements for the BigQuery source

---

mage_integrations/mage_integrations/destinations/trino/connectors/base.py

Reduce batch size to 500 for Trino destination. Will limit the query text length to 1MB in a future PR.
tested locally
cc:

[xy] Reduce batch size to 500 for Trino destination

---

mage_ai/server/constants.py
setup.py

- SQL blocks can run raw SQL
- Name tables created from SQL blocks
- dbt Redshift support
- Fix bugs related to dbt and Python blocks

[td] 0.7.85

---

mage_ai/io/bigquery.py
mage_ai/io/export_utils.py
mage_ai/io/redshift.py
mage_ai/io/snowflake.py
mage_ai/io/sql.py
mage_ai/server/constants.py
setup.py

[td] 0.7.86

---

mage_integrations/mage_integrations/tests/destinations/test_base.py
mage_integrations/mage_integrations/tests/sources/test_base.py

- Add unit tests for integration destinations `base.py` file.

[jk] Unit tests destinations base

---

docs/introduction/overview.mdx

[td] Add Docker pulls to docs

---

mage_integrations/mage_integrations/sources/linkedin_ads/tap_linkedin_ads/sync.py
mage_integrations/mage_integrations/sources/linkedin_ads/templates/config.json

[td] Improve bookmark logic for LinkedIn Ads

---

mage_ai/data_preparation/models/block/sql/bigquery.py

Fix missing import in bigquery sql block.
tested locally
cc:

[xy] Fix missing import in bigquery sql block.

---

mage_integrations/mage_integrations/sources/sql/base.py

Fix quote in bigquery order_by_columns.
tested locally
cc:

[xy] Fix quote in bigquery order_by_columns.

---

mage_ai/server/constants.py
setup.py

- Improve BigQuery destination
- Improve Outreach source
- Support loading data from file directories

[td] 0.7.87

---

mage_ai/orchestration/db/__init__.py

Fix sqlalchemy connect error.
tested locally
cc:

[xy] Fix sqlalchemy connect error.

---

mage_integrations/mage_integrations/sources/mssql/__init__.py

Fix date comparison for mssql.
tested the sql command locally
cc:

[xy] Fix date comparison for mssql.

---

docs/data-integrations/overview.mdx
mage_ai/data_integrations/destinations/constants.py
mage_integrations/mage_integrations/destinations/mssql/README.md
mage_integrations/mage_integrations/destinations/mssql/__init__.py
mage_integrations/mage_integrations/destinations/mssql/templates/config.json
mage_integrations/mage_integrations/destinations/mssql/utils.py
mage_integrations/mage_integrations/sources/mssql/__init__.py

Add MSSQL destination.
tested locally
cc:

[xy] Add MSSQL destination.

---

docs/development/secrets/GCP.mdx
docs/mint.json

[td] Add docs for GCP dev

---

dev.Dockerfile

No need to install jupyterlab in dev dockerfile.
tested locally
cc:

[xy] Not install jupyterlab in dev dockerfile.

---

mage_ai/tests/api/operations/base.py
mage_ai/tests/api/operations/test_sessions.py
mage_ai/tests/api/operations/test_users.py
mage_ai/tests/factory.py
requirements.txt

[td] Add tests for sessions API

---

mage_ai/cli/main.py
mage_ai/server/server.py
scripts/start.sh

Small update on cli and start script.
* Can't set the tornado to listen on localhost. Otherwise, the port forwarding doesn't work for docker.
* Move the print statement back to server.py
tested locally
cc:

[xy] Small update on cli and start script.

---

mage_integrations/mage_integrations/sources/mssql/__init__.py
mage_integrations/mage_integrations/sources/sql/base.py
mage_integrations/mage_integrations/sources/sql/utils.py

Fix datetime conversion for MSSQL. Truncate the datetime string to 3 digits.
tested locally
cc:

[xy] Fix datetime conversion for MSSQL

---

mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/trino/README.md
mage_integrations/mage_integrations/destinations/trino/connectors/base.py
mage_integrations/mage_integrations/destinations/trino/templates/config.json

Make query_max_length configurable for Trino destination.
tested locally
cc:

[xy] Make query_max_length configurable for Trino destination.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/server/utils/output_display.py
mage_ai/server/websocket_server.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_collinear_columns.py
mage_ai/tests/data_cleaner/transformer_actions/test_column.py
mage_ai/tests/data_cleaner/transformer_actions/test_row.py
mage_ai/tests/data_preparation/models/test_block.py
mage_ai/tests/data_preparation/models/test_variable.py
mage_ai/tests/data_preparation/test_variable_manager.py

Disable automatic output analysis to speed up the execution of the block.
tested locally
cc: @johnson-mage could you disable the column header if there's no analyses data?
cc:

[xy] Disable automatic output analysis.

---

mage_ai/data_preparation/models/block/dbt/__init__.py

Throw exception on dbt compilation error.
tested locally
cc:

[xy] Throw exception on dbt compilation error.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/models/file.py

[td] Use a single dbt source file

---

mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/server/constants.py
setup.py

- Save button on file editor
- Raise error in pipeline run when dbt has a compilation error
- Use 1 dbt `sources.yml` file for a single dbt project

[td] 0.7.88

---

docs/guides/triggering-pipelines.mdx
docs/guides/triggers/events/aws.mdx
docs/guides/triggers/events/overview.mdx
docs/mint.json

[td] Guide for creating event trigger for AWS

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/variable_manager.py
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/server.py
mage_ai/tests/data_preparation/models/test_pipeline.py

Reverts mage-ai/mage-ai#1880
Fixes the response issue. The variables were getting updated correctly, but the server response was constructed incorrectly.
tested locally

Revert "Revert "[dy] Modify global variables in code""

---

mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx
mage_ai/frontend/components/Sidekick/GlobalVariables/index.style.ts
mage_ai/frontend/components/Sidekick/GlobalVariables/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/server/server.py

Some UI changes to allow users to edit their global variables through the UI. The UX is a bit clunky, but I didn't have time to improve it. I'm going to leave this PR up for now, but we can change the UX if wanted.
tested locally
cc:

[dy] Edit global variable through UI

---

mage_ai/data_preparation/logging/__init__.py
mage_ai/data_preparation/logging/gcs_logger_manager.py
mage_ai/data_preparation/logging/logger_manager_factory.py
mage_ai/data_preparation/logging/s3_logger_manager.py

Support writing logs to google cloud storage. Implementation is similar to how we write logs to s3. Will update docs in a separate PR.
tested locally

[dy] Add google cloud storage logs

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/data_preparation/variable_manager.py
mage_ai/orchestration/db/models.py

Fixes this bug: https://github.com/mage-ai/mage-ai/issues/1943

[td] Fix dynamic block key error bug

---

mage_ai/io/mysql.py
mage_ai/io/postgres.py

[td] Fix datatype empty for SQL blocks

---

mage_ai/api/middleware.py
mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/1947
- https://github.com/mage-ai/mage-ai/pull/1945
- Remove non-existent decoded token in middleware

[td] 0.7.90

---

docs/production/observability/logging.mdx

[dy] Update code block

---

mage_ai/services/k8s/job_manager.py
mage_ai/tests/services/k8s/test_job_manager.py
mage_ai/tests/streaming/sinks/test_kinesis.py
mage_ai/tests/streaming/sources/test_kinesis.py

Add more unit tests.
* Kinesis source
* Kinesis sink
* K8s JobManager
unit tests
cc:

[xy] Add more unit tests.

---

mage_integrations/mage_integrations/sources/mssql/__init__.py
mage_integrations/mage_integrations/sources/sql/base.py

Not compare None bookmark value.
tested locally
cc:

[xy] Not compare None bookmark value.

---

kube/app.yaml
mage_ai/data_preparation/executors/ecs_block_executor.py
mage_ai/data_preparation/executors/gcp_cloud_run_block_executor.py
mage_ai/data_preparation/executors/k8s_block_executor.py
mage_ai/services/k8s/constants.py
mage_ai/services/k8s/job_manager.py
mage_ai/tests/services/k8s/test_job_manager.py

Improve k8s executor and job manager.
* Get k8s namespace and pod name from environment variable
* Improve logging for k8s job_manager
* Fix arg names for k8s, ecs, gcp_cloud_run executors
tested locally
cc:

[xy] Improve k8s executor and job manager.

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/io/snowflake.py
mage_ai/server/constants.py
setup.py

- Fix BigQuery dbt and data loader
- Fix Snowflake dbt and data loader

[td] 0.7.91

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx

[jk] Allow multiple parition keys for delta lake destination

---

mage_ai/data_preparation/models/utils.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/storage/utils.py
mage_ai/io/export_utils.py
mage_ai/io/mysql.py
mage_ai/io/postgres.py
mage_ai/tests/data_preparation/models/test_block.py
requirements.txt

- Solution: manually serialize and deserialize columns
- https://github.com/apache/arrow/issues/33928
- https://github.com/apache/arrow/pull/14547
Need `pyarrow` 12.0.0 or else when trying to convert a list of dicts, this error happens:
```
ArrowTypeError: Could not convert {'hey': 1} with type dict: was not a sequence or recognized null for conversion to list type
```

[td] Improve serializing dicts and list of dicts

---

mage_ai/server/constants.py
setup.py

- Better serialization and deserialization of data between blocks (specifically dictionaries and lists)

[td] 0.7.92

---

docs/integrations/databricks.mdx
docs/mint.json
integrations/databricks/Dockerfile
mage_ai/data_preparation/models/constants.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/storage/base_storage.py
mage_ai/data_preparation/storage/local_storage.py
mage_ai/data_preparation/storage/s3_storage.py
mage_ai/data_preparation/variable_manager.py
mage_ai/server/kernels.py
mage_ai/server/utils/output_display.py
mage_ai/server/websocket_server.py
mage_ai/services/aws/s3/s3.py
mage_ai/tests/services/aws/s3/test_s3.py

Integrate with Databricks. Support running pyspark code in remote Databricks cluster.
TODOs
tested locally
unit tests
cc:

[xy] Integrate with Databricks.

---

docs/mint.json

Add rabbitmq doc to menu.
n/a
cc:

[xy] Add rabbitmq doc to menu.

---

mage_integrations/mage_integrations/destinations/sql/utils.py
mage_integrations/mage_integrations/destinations/trino/README.md
mage_integrations/mage_integrations/destinations/trino/__init__.py
mage_integrations/mage_integrations/destinations/trino/connectors/base.py
mage_integrations/mage_integrations/destinations/trino/connectors/deltalake.py
mage_integrations/mage_integrations/destinations/trino/templates/config.json

Support deltalake in trino destination
tested locally
cc:

[xy] Support deltalake in trino destination

---

docs/guides/streaming/streaming-pipeline-rabbitmq.mdx

[td] Fix RabbitMQ docs

---

mage_integrations/mage_integrations/sources/outreach/__init__.py
mage_integrations/mage_integrations/sources/outreach/tap_outreach/discover.py
mage_integrations/mage_integrations/sources/outreach/tap_outreach/sync.py

Improve outreach source
* Fix bookmark comparison
* Improve logging
tested locally
cc:

[xy] Improve outreach source

---

mage_integrations/mage_integrations/destinations/snowflake/README.md
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/templates/config.json

[td] Disable using double quotes in Snowflake data integration

---

mage_ai/data_preparation/models/utils.py
mage_ai/server/constants.py
setup.py

- Improve serialization of empty lists and dicts

[td] 0.7.93

---

mage_ai/io/bigquery.py
mage_ai/server/constants.py
setup.py

- Fill NULL values for columns that are an array type in BigQuery

[td] 0.7.94

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/shared/io.py
mage_ai/tests/data_preparation/models/test_pipeline.py
mage_ai/tests/shared/test_io.py

Add guardrails on pipeline update.
* Not write empty pipeline metadata
* Safely write files
tested locally
unit tests
cc:

[xy] Add guardrails on pipeline update.

---

mage_ai/server/constants.py
setup.py

Includes support for trino in dbt.
cc:

[dy] Bump to 0.7.96

---

mage_ai/io/trino.py
mage_ai/server/constants.py
setup.py

Update `trino.py` code for trino 0.318.0
cc:

[dy] Bump 0.7.98

---

docs/guides/streaming/streaming-pipeline-rabbitmq.mdx

Removed host url (used to test)
cc:

nit: removing ec2 host url

---

mage_ai/data_integrations/utils/config.py

The block settings could have an empty catalog dict.
tested locally
cc:

[xy] Fix fetching catalog.

---

mage_integrations/mage_integrations/sources/hubspot/__init__.py
mage_integrations/mage_integrations/sources/hubspot/tap_hubspot/__init__.py

Improve logging for hubspot source.
tested locally
cc:

[xy] Improve logging for hubspot source.

---

docs/integrations/databricks.mdx
integrations/databricks/Dockerfile
mage_ai/data_preparation/models/block/__init__.py
mage_ai/server/websocket_server.py

Fix databricks pipeline execution
* Automatically initialize spark session if it doesn't
tested locally
cc:

[xy] Fix databricks pipeline execution

---

mage_ai/data_preparation/decorators.py
mage_ai/data_preparation/templates/custom/python/default.jinja
mage_ai/data_preparation/templates/template.py

Add code template for custom block.
tested locally
cc:

[xy] Add code template for custom block.

---

mage_ai/data_preparation/models/block/__init__.py

Fix block output dataframe shape.
tested locally
cc:

[xy] Fix block output dataframe shape.

---

mage_ai/cli/main.py
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/executors/gcp_cloud_run_block_executor.py
mage_ai/data_preparation/executors/k8s_block_executor.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/services/k8s/job_manager.py
mage_ai/tests/services/k8s/test_job_manager.py
scripts/run_app.sh

Run data integration blocks in separate k8s pods
tested locally
cc:

[xy] Run data integration blocks in separate k8s pods

---

mage_integrations/mage_integrations/sources/front/streams/analytics.py

Fix Front date comparison.
tested locally
cc:

[xy] Front date comparison.

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/executors/k8s_block_executor.py
mage_ai/services/k8s/job_manager.py
scripts/run_app.sh

K8s job error handling.
tested locally
cc:

[xy] K8s job error handling.

---

docs/data-integrations/overview.mdx
mage_ai/data_integrations/destinations/constants.py
mage_integrations/mage_integrations/destinations/postgresql/utils.py
mage_integrations/mage_integrations/destinations/redshift/README.md
mage_integrations/mage_integrations/destinations/redshift/__init__.py
mage_integrations/mage_integrations/destinations/redshift/utils.py

Add Redshift destination.
We currently don't support MERGE command since it's still in preview: https://docs.amazonaws.cn/en_us/redshift/latest/dg/r_MERGE.html
tested locally
cc:

[xy] Add Redshift destination.

---

docs/guides/blocks/custom-blocks.mdx
docs/mint.json
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx

[jk] Update docs for custom blocks

---

docs/guides/blocks/custom-blocks.mdx

- See title.
- https://docs.mage.ai/guides/blocks/custom-blocks
- Confirmed fix in readme preview.

[jk] Fix formatting in Custom blocks readme

---

mage_integrations/mage_integrations/destinations/redshift/__init__.py
mage_integrations/mage_integrations/destinations/redshift/utils.py

Fix redshift destination text type.
ref: https://stackoverflow.com/questions/30919389/redshift-equivalent-of-text-data-type
tested locally
cc:

[xy] Fix redshift destination text type.

---

.github/workflows/build_and_test.yml
mage_ai/server/utils/output_display.py
mage_ai/tests/data_cleaner/statistics/test_calculator.py
requirements.txt

Bump up pandas version. Pandas version 1.5.x is supported in python 3.8+
tested locally
unit tests
cc:

[xy] Bump up pandas version.

---

mage_ai/services/k8s/job_manager.py
mage_ai/tests/services/k8s/test_job_manager.py

Pass k8s container env variables to job pod.
tested locally
cc:

[xy] Pass k8s container env variables to job pod.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.7.100
* https://github.com/mage-ai/mage-ai/pull/2000
* https://github.com/mage-ai/mage-ai/pull/1996
* https://github.com/mage-ai/mage-ai/pull/2009
n/a
cc:

[xy] Bump version to 0.7.100

---

mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/__init__.py

Batch fetch records for Facebook Ads streams
* AdCreative
* Leads
tested locally
cc:

[xy] Batch fetch records for Facebook Ads streams

---

mage_ai/data_preparation/templates/data_loaders/streaming/kafka.yaml
mage_ai/streaming/sources/kafka.py
mage_ai/tests/data_preparation/test_templates.py
mage_ai/tests/streaming/sources/test_kafka.py

Support SASL config in kafka streaming source.
tested locally
unit test
cc:

[xy] Support SASL config in kafka streaming source.

---

mage_ai/data_preparation/models/utils.py

Fix datetime serialization issue.
tested locally
cc:

[xy] Fix datetime serialization issue.

---

docs/development/secrets/secrets.mdx
mage_ai/frontend/components/Sidekick/GlobalVariables/Secrets.tsx
mage_ai/orchestration/db/__init__.py
mage_ai/shared/environments.py

Add docs and messaging for accessing mage secrets in code block. Also changed sqlalchemy to only log in dev.
tested locally

[dy] Access secrets in code

---

mage_ai/data_integrations/utils/config.py

[dy] Update interpolation code

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/storage/local_storage.py
mage_ai/server/server.py
mage_ai/server/utils/output_display.py
mage_ai/shared/parsers.py
mage_ai/tests/data_preparation/models/test_variable.py

Provide sample output for large json object.
tested locally
cc:

[xy] Provide sample output for large json object.

---

mage_ai/services/k8s/job_manager.py
mage_ai/tests/services/k8s/test_job_manager.py

Pass mage server image to k8s job pod.
tested locally
unit test
cc:

[xy] Pass mage server image to k8s job pod.

---

mage_ai/api/views.py

[td] Fix file uploads

---

mage_ai/server/constants.py
setup.py

[td] 0.7.102

---

mage_ai/server/constants.py
setup.py

[td] 0.7.103

---

docs/mint.json
docs/production/authentication/overview.mdx

[td] User authentication docs

---

mage_integrations/mage_integrations/sources/couchbase/README.md
mage_integrations/mage_integrations/sources/couchbase/__init__.py
mage_integrations/mage_integrations/tests/sources/couchbase/test_couchbase.py

Update couchbase to handle more unstructured data.
tested locally

[dy] Update couchbase

---

mage_ai/server/constants.py
setup.py

- User login, management, authentication, roles, permissions

[td] 0.8.0

---

mage_ai/data_preparation/repo_manager.py
mage_ai/orchestration/job_manager.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/orchestration/queue/celery_queue.py
mage_ai/orchestration/queue/config.py
mage_ai/orchestration/queue/process_queue.py
mage_ai/orchestration/queue/queue.py
mage_ai/orchestration/queue/queue_factory.py
mage_ai/tests/orchestration/queue/test_process_queue.py
mage_ai/tests/orchestration/test_job_manager.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

Add queue for scheduler.
* Add queue interface
* Add ProcessQueue implementation and CeleryQueue scheduler
* Add JobManager class to handle block run job and pipeline run job
Default queue size is 20.
The queue size can be configured in project's metadata.yaml
```
queue_config:
queue_type: 'process'
concurrency: 100
```
tested locally
tested with unit tests
cc:

[xy] Add queue for scheduler.

---

mage_ai/data_preparation/models/variable.py

Fix delete json variable.
tested locally
cc:

[xy] Fix delete json variable.

---

mage_integrations/mage_integrations/destinations/bigquery/utils.py

Fix more emoji code.
tested locally
cc:

[xy] Fix more emoji code.

---

mage_ai/server/constants.py
mage_ai/server/server.py
setup.py

[td] 0.8.01

---

docs/production/authentication/overview.mdx

[td] Update overview.mdx

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/storage/s3_storage.py
mage_ai/server/websocket_server.py
mage_ai/shared/utils.py

Support pyspark in local env.
tested locally
cc:

[xy] Support pyspark in local env.

---

requirements.txt

Add jwt to requirements.txt
CI
cc:

[xy] Add jwt to requirements.txt

---

mage_ai/server/constants.py
setup.py

Bump version to 0.8.2
* https://github.com/mage-ai/mage-ai/pull/2043
* https://github.com/mage-ai/mage-ai/pull/2042
* https://github.com/mage-ai/mage-ai/pull/2044
* https://github.com/mage-ai/mage-ai/pull/2013
CI
cc:

[xy] Bump version to 0.8.2

---

mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/frontend/api/utils/fetcher.ts
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/ErrorPopup/index.style.tsx
mage_ai/frontend/components/ErrorPopup/index.tsx
mage_ai/frontend/components/FileBrowser/NewFile/index.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/FileEditor/utils.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/utils/models/dbt.ts
mage_ai/server/constants.py
mage_ai/server/server.py
setup.py

- Fix deleting files in nested folders
- Drag and drop dbt models from file browser
- Right click folder to create new file
- Don’t error in the UI if there is no ref detected from the dbt model

[td] 0.8.3

---

mage_ai/data_preparation/models/pipeline.py

Not fallback to empty pipeline when failing to reading pipeline …
tested locally
cc:

[xy] Not fallback to empty pipeline when failing to reading pipeline yaml

---

requirements.txt

[xy] Bump dask version.

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx

- When multiple runs were being canceled, the status for other runs was being updated to "canceling" even though those runs weren't being canceled.

[jk] Show canceling status only for pipeline run being canceled

---

mage_ai/tests/data_cleaner/test_column_type_detector.py
mage_ai/tests/data_cleaner/transformer_actions/test_column.py
requirements.txt

[xy] Bump numpy version.

---

mage_ai/frontend/utils/cookies/constants.ts
mage_ai/server/constants.py
setup.py

- Enable cookies for cloud domains

[td] 0.8.4

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx

- Fix issue with Retry pipeline run button popup being cutoff.
Before:
After:

[jk] Make retry run popup fully visible

---

mage_ai/data_preparation/storage/local_storage.py

Ignore delete errors.
tested locally
cc:

[xy] Ignore delete errors.

---

docs/production/deploying-to-cloud/aws/setup.mdx

Add doc for deploying Mage to EKS cluster.
preview locally
cc:

[xy] Add doc for deploying Mage to EKS cluster.

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2059

[td] 0.8.5

---

mage_ai/frontend/components/Terminal/index.tsx

[jk] Add alert with details on how to allow clipboard paste in insecure contexts

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/utils/output_display.py
mage_ai/server/websocket_server.py

- Play button: compiles SQL and runs it in the target.
- Drop down menu: Run model
- After creating model, use run results to get table name to query the model for sample preview results.

[td] Run dbt model and create table option in notebook

---

mage_ai/tests/services/datadog/test_datadog.py

[dy] Add datadog unit tests

---

mage_ai/api/presenters/OutputPresenter.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/io/postgres.py

- dbt block can now run model instead in addition to compile and preview
- Fix copy csv to Postgres when column has null values
- Fix dynamic block run output in UI
- Fix dynamic block having a child that is a dynamic block

[td] 0.8.6

---

mage_ai/frontend/components/PipelineDetail/Syncs/SyncRowDetail/index.tsx

[jk] Fix NaN being display for runtime value on Syncs page

---

mage_integrations/mage_integrations/destinations/redshift/templates/config.json

Add redshift destination template.
tested locally
cc:

[xy] Add redshift destination template.

---

mage_ai/cli/main.py
mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/templates/repo/metadata.yaml
mage_ai/data_preparation/variable_manager.py
mage_ai/shared/dates.py

Add command to delete cached variables.
Will add a cron job to run this command after the new version is published.
tested locally with `python mage_ai/cli/main.py clean-cached-variables default_repo`
cc:

[xy] Add command to delete cached variables.

---

mage_ai/orchestration/metrics/pipeline_run.py
mage_integrations/mage_integrations/destinations/delta_lake/base.py
mage_integrations/mage_integrations/destinations/delta_lake_s3/__init__.py

Fix row syncing count. Destination row count numbers are logged in different records. So we need to add them up.
tested locally
cc:

[xy] Fix row syncing count.

---

mage_ai/server/constants.py
setup.py

- Bump to v0.8.7
- https://github.com/mage-ai/mage-ai/pull/2076
- https://github.com/mage-ai/mage-ai/pull/2063
- https://github.com/mage-ai/mage-ai/pull/2069

[jk] Bump to v0.8.7

---

mage_ai/api/resources/AutocompleteItemResource.py
mage_ai/api/resources/BackfillResource.py
mage_ai/api/resources/BlockResource.py
mage_ai/api/resources/BlockRunResource.py
mage_ai/api/resources/ClusterResource.py
mage_ai/api/resources/DataProviderResource.py
mage_ai/api/resources/DatabaseResource.py
mage_ai/api/resources/EventRuleResource.py
mage_ai/api/resources/FileContentResource.py
mage_ai/api/resources/FileResource.py
mage_ai/api/resources/IntegrationDestinationResource.py
mage_ai/api/resources/IntegrationSourceResource.py
mage_ai/api/resources/IntegrationSourceStreamResource.py
mage_ai/api/resources/KernelResource.py
mage_ai/api/resources/LogResource.py
mage_ai/api/resources/MonitorStatResource.py
mage_ai/api/resources/OutputResource.py
mage_ai/api/resources/PipelineResource.py
mage_ai/api/resources/PipelineRunResource.py
mage_ai/api/resources/PipelineScheduleResource.py
mage_ai/api/resources/ProjectResource.py
mage_ai/api/resources/SecretResource.py
mage_ai/api/resources/SessionResource.py
mage_ai/api/resources/UserResource.py
mage_ai/api/resources/VariableResource.py
mage_ai/api/resources/WidgetResource.py
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/DependencyGraph/GraphNode.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/io/bigquery.py

[td] Add safe_db_query to all API resources

---

mage_ai/server/constants.py

- https://github.com/mage-ai/mage-ai/pull/2073
- https://github.com/mage-ai/mage-ai/pull/2078

[td] 0.8.8

---

docs/about/changelog.mdx

[td] Add about/changelog for Bing results

---

mage_ai/api/policies/FilePolicy.py
mage_ai/api/presenters/FilePresenter.py
mage_ai/api/resources/FileResource.py
mage_ai/data_preparation/models/file.py
mage_ai/frontend/api/utils/response.ts
mage_ai/frontend/components/ErrorPopup/index.tsx
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/FileBrowser/NewFile/index.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/FileUploader/index.tsx

- Upload files and create new files in the root project directory
- Delete any file from file browser
- Rename any file from file browser

[td] Delete and rename files from any directory

---

mage_ai/api/resources/PipelineResource.py
mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/FileEditor/utils.ts
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/utils/string.ts
mage_ai/shared/strings.py

Don’t create upstream block SQL table unless dbt block references it.

[td] Only create upstream source if its used

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2085
- https://github.com/mage-ai/mage-ai/pull/2086

[td] 0.8.10

---

mage_ai/frontend/components/Terminal/index.tsx

- See title.
https://user-images.githubusercontent.com/78053898/221713029-f1557230-cf79-477b-a0d4-6164eac0624d.mp4

[jk] Handle multi-line pasting into Terminal

---

mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

When a previous block has output, adding a new block can sometimes stop showing that output.
This PR fixes that.

[td] Fix block output missing when adding new block

---

mage_ai/api/resources/BlockResource.py

[td] Delete nested files

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2090
- https://github.com/mage-ai/mage-ai/pull/2091

[td] 0.8.11

---

docs/mint.json

[dy] Update mint json

---

mage_ai/orchestration/pipeline_scheduler.py

Update data sync to happen in `pipeline_scheduler.start` so that it works for all pipeline types.
tested locally
cc:

[dy] Update sync data location

---

mage_ai/orchestration/db/models.py
mage_ai/orchestration/pipeline_scheduler.py

Fix scheduler crash.
tested locally
cc:

[xy] Fix scheduler crash.

---

docs/about/releases.mdx

added recent release v0.8.11 notes
cc:

[tc] update release page

---

mage_ai/server/server.py

[dy] Add settings routes

---

mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/oracle/elements/Headline/index.tsx

[jk] Show spinner when loading sources and destinations

---

mage_ai/data_preparation/templates/data_loaders/streaming/kafka.yaml
mage_ai/streaming/sources/kafka.py
mage_ai/tests/data_preparation/test_templates.py
mage_ai/tests/streaming/sources/test_kafka.py
requirements.txt

Support protobuf message in Kafka source.
tested locally
unit tests
cc:

[xy] Support protobuf message in Kafka source.

---

mage_ai/api/resources/SyncResource.py
mage_ai/frontend/pages/settings/workspace/sync_data.tsx

Pass in sync type in frontend
tested locally
cc:

[dy] Update sync type

---

mage_integrations/mage_integrations/destinations/postgresql/__init__.py

Use TEXT for string type in pg destination
tested locally
cc:

[xy] Use TEXT for string type in pg destination

---

mage_ai/data_preparation/models/block/__init__.py

Not import data_cleaner lib when not used.
tested locally
cc:

[xy] Not import data_cleaner lib when not used.

---

mage_ai/data_preparation/executors/pipeline_executor.py
mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/streaming/sources/kafka.py

Improve logging for streaming pipeline.
tested locally
cc:

[xy] Improve logging for streaming pipeline.

---

mage_ai/server/constants.py
setup.py

* Add git sync: https://github.com/mage-ai/mage-ai/pull/2088
cc:

[dy] Bump 0.8.12

---

docs/design/data-pipeline-management.mdx

Add doc for limiting the concurrency.
n/a
cc:

[xy] Add doc for limiting the concurrency.

---

mage_ai/api/policies/BackfillPolicy.py
mage_ai/frontend/components/Backfills/Detail/index.tsx
mage_ai/frontend/components/Backfills/Edit/index.tsx
mage_ai/frontend/components/Backfills/Table/index.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/ErrorPopup/index.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/components/PipelineLayout/index.tsx
mage_ai/frontend/components/ScheduleLayout/index.tsx
mage_ai/frontend/components/Sidekick/GlobalVariables/Secrets.tsx
mage_ai/frontend/components/Sidekick/GlobalVariables/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/Triggers/Table.tsx
mage_ai/frontend/interfaces/ErrorsType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/backfills/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/frontend/utils/session.ts

- Update pages throughout app for Viewer access, which included hiding or disabling buttons as needed.
- Added error messaging to different areas of app so error popup appears when viewer tries to do a create/update/delete request.
- Checked every page throughout app.
- Sample page with unauthorized access error popup:

[jk] Viewer UI access

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/utils/string.ts
mage_ai/io/export_utils.py
mage_ai/io/postgres.py
mage_ai/server/websocket_server.py

[td] Fix Postgres Python to SQL JSON

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2115

[td] 0.8.13

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/interfaces/BlockType.ts

- Preview positional arguments for data passed from upstream blocks on custom blocks.

[jk] Custom block preview arguments

---

docs/guides/streaming/destinations/kafka.mdx
docs/guides/streaming/overview.mdx
docs/mint.json
mage_ai/data_preparation/templates/data_exporters/streaming/kafka.yaml
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/streaming/constants.py
mage_ai/streaming/sinks/kafka.py
mage_ai/streaming/sinks/sink_factory.py

Add Kafka sink to streaming pipeline
tested locally
cc:

[xy] Add Kafka sink to streaming pipeline

---

mage_ai/server/constants.py
setup.py

Bump version to 0.8.14
* https://github.com/mage-ai/mage-ai/pull/2119
* https://github.com/mage-ai/mage-ai/pull/2120
* https://github.com/mage-ai/mage-ai/pull/2121
n/a
cc:

[xy] Bump version to 0.8.14

---

mage_ai/orchestration/pipeline_scheduler.py

Catch metrics calculation error to avoid silent failure.
tested locally
cc:

[xy] Catch metrics error.

---

docs/guides/schedule-pipelines.mdx
docs/guides/triggering-pipelines.mdx

Update documentation for trigger settings.
only docs changes
cc:

[dy] Update trigger documentation

---

mage_ai/api/resources/PipelineResource.py
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx

- Add button to cancel all running pipeline runs for a pipeline.

[jk] Cancel all running pipeline runs

---

mage_ai/api/resources/BlockResource.py

- Fix issues deleting dbt block files

[td] Fix delete dbt block file

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/2126
* https://github.com/mage-ai/mage-ai/pull/2117
* https://github.com/mage-ai/mage-ai/pull/2102
cc:

[dy] Bump version to 0.8.15

---

mage_ai/api/middleware.py
mage_ai/server/constants.py
setup.py

[td] 0.8.17

---

mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/utils.py
mage_integrations/mage_integrations/destinations/sql/utils.py

Fix snowflake alter table command.
https://stephenallwright.com/snowflake-add-multiple-columns/
tested locally
cc:

[xy] Fix snowflake alter table command.

---

mage_ai/io/postgres.py

Not convert str to json when uploading dataframe.
tested locally
cc:

[xy] Not convert str to json when uploading dataframe.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/utils.py

Use the upstream dynamic block’s block metadata as the downstream child block’s kwargs.

[td] Add metadata from dynamic blocks

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2142

[td] 0.8.18

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/server/constants.py
setup.py

- Fix block output with tables

[td] 0.8.19

---

docs/production/deploying-to-cloud/aws/setup.mdx

Fixes a broken link in the docs
Docs

Fix broken link in docs

---

Dockerfile
dev.Dockerfile

change `apt-get` to `apt -y`
tested with `docker-compose build`
cc:

[dy] Update dockerfile

---

docs/about/releases.mdx

added release v0.8.15 link
cc:

[tc] changelog update

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/Sidekick/GlobalVariables/index.tsx

- Update the Variables tab with more instruction for SQL and R variables.
- Improve SQL/R block upstream block interpolation helper hints.
Variables tab:
SQL block helper hint:
R block helper hint:

[jk] Improve variable explanation

---

mage_ai/api/policies/SyncPolicy.py

Add allow actions to sync policy.
tested locally
cc:

[dy] Add permissions to sync policy

---

mage_ai/server/constants.py
setup.py

Bug fix for sync policy: https://github.com/mage-ai/mage-ai/pull/2154
cc:

[dy] Bump to 0.8.21

---

docs/guides/streaming/destinations/kafka.mdx
docs/guides/streaming/sources/kafka.mdx
mage_ai/streaming/sinks/kafka.py
mage_ai/streaming/sources/kafka.py

Improve kafka source and sink.
* Set api_version in producer and consumer
* Allow passing raw value to transformer
tested locally
cc:

[xy] Improve kafka source and sink.

---

docs/developing-in-the-cloud/setting-up-git.mdx
docs/development/versioning/file-versions.mdx
docs/mint.json
mage_ai/data_preparation/models/file.py

[td] Fix max number of file versions

---

mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2149
- https://github.com/mage-ai/mage-ai/pull/2158
- https://github.com/mage-ai/mage-ai/pull/2157

[td] 0.8.22

---

docs/production/deploying-to-cloud/azure/setup.mdx
docs/production/deploying-to-cloud/gcp/setup.mdx

[td] Update Azure deployment docs

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx

[jk] Hide custom add new block button in streaming pipelines

---

mage_ai/api/presenters/WidgetPresenter.py

Add has_callback to widget presenter.
local
cc:

[dy] Add has_callback to widget

---

docs/community/contributing.mdx
docs/production/deploying-to-cloud/azure/setup.mdx

- Azure diagram
- Mount `z` option

[td] Update Azure docs with diagram

---

mage_ai/data_preparation/models/variable.py

Catch variable write error.
tested locally
cc:

[xy] Catch variable write error.

---

mage_ai/shared/io.py

Catch error when deleting temp metadata.yaml
tested locally
cc:

[xy] Catch error when deleting temp metadata.yaml

---

mage_ai/data_preparation/models/file.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/FileVersions/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Track pipeline metadata.yaml changes
- Restore pipelines to previous versions

[td] Pipeline versioning

---

integrations/spark/Dockerfile

Add Dockerfile for spark env.
tested locally
cc:

[xy] Add Dockerfile for spark env.
