mage-ai/mage-ai

mage_integrations/mage_integrations/sources/sql/base.py

Decode mysql source bytes.
Issue: https://github.com/mage-ai/mage-ai/issues/2164
tested locally
cc:

[xy] Decode mysql source bytes.

---

mage_ai/orchestration/pipeline_scheduler.py

Refresh block run data in scheduler to clear cache in session.
tested locally
cc:

[xy] Refresh block run data in scheduler.

---

mage_integrations/mage_integrations/sources/front/schemas.py
mage_integrations/mage_integrations/sources/front/schemas/channels.json
mage_integrations/mage_integrations/sources/front/schemas/conversations.json
mage_integrations/mage_integrations/sources/front/schemas/custom_fields.json
mage_integrations/mage_integrations/sources/front/schemas/events.json
mage_integrations/mage_integrations/sources/front/schemas/rules.json
mage_integrations/mage_integrations/sources/front/streams/channels.py
mage_integrations/mage_integrations/sources/front/streams/conversations.py
mage_integrations/mage_integrations/sources/front/streams/custom_fields.py
mage_integrations/mage_integrations/sources/front/streams/events.py
mage_integrations/mage_integrations/sources/front/streams/rules.py

Add more front streams.
tested streams
cc:

[xy] Add more front streams.

---

mage_ai/data_preparation/sync/git_sync.py

Overwrite origin url with the user's remote_repo_link if it already exists.
tested locally

[dy] Overwrite origin url

---

mage_ai/data_preparation/sync/git_sync.py

Revert "[dy] Overwrite origin url"

---

mage_ai/data_preparation/models/utils.py
mage_ai/data_preparation/models/variable.py

Fix pipeline execution.
Pipeline execution got stuck due to dask memory calculation.
tested locally
cc:

[xy] Fix pipeline execution.

---

mage_ai/api/middleware.py
mage_ai/orchestration/db/models.py

Fix oauth db query.
tested locally
cc:

[xy] Fix oauth db query.

---

mage_ai/utils/code.py

Library reload error could cause block execution being stuck
tested locally
cc:

[xy] Catch library reload error.

---

mage_ai/io/mysql.py

Update enforce limit command for mysql 5.7
MySQL 5.7 doesn't support WITH syntax
tested locally
cc:

[xy] Update enforce limit command for mysql 5.7

---

mage_ai/server/constants.py
setup.py

Bump version to 0.8.23
* https://github.com/mage-ai/mage-ai/pull/2162
* https://github.com/mage-ai/mage-ai/pull/2167
* https://github.com/mage-ai/mage-ai/pull/2169
* https://github.com/mage-ai/mage-ai/pull/2168
* https://github.com/mage-ai/mage-ai/pull/2161
* https://github.com/mage-ai/mage-ai/pull/2123
* https://github.com/mage-ai/mage-ai/pull/2173
* https://github.com/mage-ai/mage-ai/pull/2170
* https://github.com/mage-ai/mage-ai/pull/2171
* https://github.com/mage-ai/mage-ai/pull/2175
* https://github.com/mage-ai/mage-ai/pull/2172
* https://github.com/mage-ai/mage-ai/pull/2176
* https://github.com/mage-ai/mage-ai/pull/2178
* https://github.com/mage-ai/mage-ai/pull/2179
* https://github.com/mage-ai/mage-ai/pull/2181
* https://github.com/mage-ai/mage-ai/pull/2184
* …

[xy] Bump version to 0.8.23

---

docs/integrations/spark-pyspark.mdx
mage_ai/data_preparation/models/block/__init__.py
mage_ai/server/utils/output_display.py

Write doc for running PySpark code with Spark cluster in Kubernetes.
tested locally
cc:

[xy] Write doc for running PySpark code with Spark cluster in Kubernetes.

---

mage_ai/data_preparation/sync/git_sync.py

Revert "Revert "[dy] Overwrite origin url""

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2187
- https://github.com/mage-ai/mage-ai/pull/2180
N/A

[jk] Bump to v0.8.24

---

docs/design/blocks.mdx
docs/design/blocks/extension.mdx
docs/development/testing/great-expectations.mdx
docs/integrations/great-expectations.mdx
docs/mint.json

[td] Add docs for extension blocks and GX

---

docs/mint.json
docs/production/deploying-to-cloud/using-helm.mdx

Add doc for Helm deployment.
n/a
cc:

[xy] Add doc for Helm deployment.

---

docs/about/releases.mdx

[tc] update changelog

---

docs/developing-in-the-cloud/setting-up-git.mdx
mage_ai/api/resources/GitBranchResource.py
mage_ai/api/resources/SyncResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/sync/git_sync.py
mage_ai/frontend/components/VersionControl/GitActions.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/pages/settings/workspace/sync_data.tsx

Fix bugs found in bug bash.
tested locally
cc:

[dy] Fix git integration bugs

---

mage_ai/frontend/components/CodeBlock/index.tsx

- Stop code block sticky headers once block ends instead of remaining visible until the next block is reached.

[jk] Stop sticky header at end of current block

---

mage_ai/api/presenters/PipelinePresenter.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/oracle/elements/Inputs/InputModal.tsx
mage_ai/frontend/oracle/elements/Inputs/TextArea.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/tests/data_preparation/models/test_pipeline.py

- Add description to pipeline model.
- Edit pipeline description in UI.

[jk] Add pipeline description

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2203
- https://github.com/mage-ai/mage-ai/pull/2201
- https://github.com/mage-ai/mage-ai/pull/2202
- https://github.com/mage-ai/mage-ai/pull/2198
- https://github.com/mage-ai/mage-ai/pull/2196
- Great Expectations
- https://github.com/mage-ai/mage-ai/pull/2183

[td] 0.8.25

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/frontend/components/settings/Dashboard/constants.ts
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/frontend/pages/settings/workspace/sync-data.tsx
mage_ai/tests/data_preparation/models/block/test_sql.py
mage_ai/tests/data_preparation/models/test_block.py

- Users can write raw SQL blocks and only include the `INSERT` statement. `CREATE TABLE` statement isn’t required anymore.
- Allow using semi-colons in quotes in a single SQL statement.
- Make it more apparent of the dangers of running a git sync

[td] SQL block disable create table

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2205
- https://github.com/mage-ai/mage-ai/pull/2193
- https://github.com/mage-ai/mage-ai/pull/2208

[td] 0.8.26

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/variable.py

Improve local spark pipeline
* Allow executing python pipelines in spark environment
* Fetch spark dataframe variables when fetching outputs
tested locally in mage spark image.
cc:

[xy] Improve local spark pipeline

---

mage_ai/io/postgres.py
mage_ai/server/server.py
mage_ai/shared/utils.py

Find available local port for ssh tunneling.
tested locally
cc:

[xy] Find available local port for ssh tunneling.

---

mage_ai/data_preparation/templates/sensors/s3.py
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/DataSourceType.ts

Update S3 sensor template and allow users to select it from the Mage UI.
tested locally
cc:

[dy] Add s3 sensor template

---

mage_integrations/mage_integrations/destinations/bigquery/__init__.py

Add check for size of query since that can potentially exceed the limit.
tested locally

[dy] Update Bigquery query conditions

---

docs/guides/sql-blocks.mdx
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/utils/shared.py

- Support only writing SELECT statements

[td] Support writing SELECT statements only

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py

Add tags to the streaming pipeline error logging.
tested locally
cc:

[xy] Add tags to the streaming pipeline error logging.

---

mage_ai/data_preparation/shared/secrets.py
mage_ai/data_preparation/templates/sensors/bigquery.py
mage_ai/data_preparation/templates/sensors/mysql.py
mage_ai/data_preparation/templates/sensors/postgres.py
mage_ai/data_preparation/templates/sensors/redshift.py
mage_ai/data_preparation/templates/sensors/s3.py
mage_ai/data_preparation/templates/sensors/snowflake.py
mage_ai/frontend/interfaces/DataSourceType.ts

Add sensor templates for SQL databases
tested locally

[dy] Add sensor templates for sql databases

---

mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx

[jk] Fix type error when getting data source menu items

---

mage_ai/server/constants.py
setup.py

Bump version to 0.8.27
* https://github.com/mage-ai/mage-ai/pull/2206
* https://github.com/mage-ai/mage-ai/pull/2211
* https://github.com/mage-ai/mage-ai/pull/2212
* https://github.com/mage-ai/mage-ai/pull/2213
* https://github.com/mage-ai/mage-ai/pull/2215
* https://github.com/mage-ai/mage-ai/pull/2214
* https://github.com/mage-ai/mage-ai/pull/2220
* https://github.com/mage-ai/mage-ai/pull/2221
* https://github.com/mage-ai/mage-ai/pull/2219
* https://github.com/mage-ai/mage-ai/pull/2218
* https://github.com/mage-ai/mage-ai/commit/762fdfe0617e1959753bd2f5346d5aeead8ac2b1
* https://github.com/mage-ai/mage-ai/pull/2223
* https://github.com/mage-ai/mage-ai/pull/2225
n/a
cc:

[xy] Bump version to 0.8.27

---

mage_ai/api/resources/SecretResource.py
mage_ai/data_preparation/shared/secrets.py

Only fetch valid secrets on the Secret index endpoint.
tested locally
cc:

[dy] Only fetch valid secrets

---

mage_ai/frontend/components/PipelineDetail/index.tsx

[jk] Disable run block shortcut for streaming pipelines

---

mage_ai/data_preparation/models/utils.py
mage_ai/data_preparation/models/variable.py
mage_ai/tests/data_preparation/models/test_variable.py

Cast column types when reading dataframe.
* int64
* float64
* Int64
tested locally
added unit test
cc:

[xy] Cast column types when reading dataframe.

---

docs/integrations/spark-pyspark.mdx

Add doc for standalone spark cluster.
n/a
cc:

[xy] Add doc for standalone spark cluster.

---

mage_ai/api/resources/SecretResource.py
mage_ai/data_preparation/shared/secrets.py

Reverts mage-ai/mage-ai#2228
This PR causes another circular import error:
cc: @dy46

Revert "[dy] Only fetch valid secrets"

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/streaming/sources/base.py
mage_ai/streaming/sources/kafka.py

Add async handler to streaming source.
tested locally with kafka source
cc:

[xy] Add async handler to streaming source.

---

mage_integrations/mage_integrations/sources/commercetools/__init__.py
mage_integrations/mage_integrations/sources/commercetools/schemas.py
mage_integrations/mage_integrations/sources/commercetools/schemas/customers.json
mage_integrations/mage_integrations/sources/commercetools/schemas/inventory.json
mage_integrations/mage_integrations/sources/commercetools/schemas/orders.json
mage_integrations/mage_integrations/sources/commercetools/streams/inventory.py

Add inventory stream to Commercetools source.
tested locally
cc:

[xy] Add inventory stream to Commercetools source.

---

docs/development/dependencies/requirements.mdx

[tc] Update python package image

---

docs/development/dependencies/custom-files.mdx

[tc] python code image change

---

docs/guides/sql-blocks.mdx

[tc] update images for doc

---

mage_ai/api/resources/DatabaseResource.py
mage_ai/data_integrations/utils/scheduler.py
mage_ai/orchestration/db/models/base.py
mage_ai/orchestration/pipeline_scheduler.py

Fix db model caching issue.
* Clear cache before API call
* Clear cache before scheduling
tested locally
cc:

[xy] Fix db model caching issue.

---

mage_integrations/mage_integrations/destinations/mysql/__init__.py

Support alter table command in MySQL.
tested locally
cc:

[xy] Support alter table command in MySQL.

---

mage_ai/orchestration/db/models/schedules.py

Fix timezone issue for pipeline schedule execution date. Set the timezone to utc when get current_execution_date.
tested locally
cc:

[xy] Fix timezone issue for pipeline schedule execution date.

---

mage_ai/orchestration/queue/process_queue.py

When killing pipeline run from the same process, update the job status before killing the process.
tested locally
cc:

[xy] Fix killing pipeline run from the same process.

---

mage_integrations/mage_integrations/destinations/mysql/__init__.py
mage_integrations/mage_integrations/destinations/mysql/utils.py

Fix alter table command for mysql.
tested locally
cc:

[xy] Fix alter table command for mysql.

---

mage_integrations/mage_integrations/destinations/mysql/README.md
mage_integrations/mage_integrations/destinations/mysql/__init__.py
mage_integrations/mage_integrations/destinations/mysql/templates/config.json
mage_integrations/mage_integrations/destinations/mysql/utils.py
mage_integrations/mage_integrations/destinations/sql/utils.py
mage_integrations/mage_integrations/destinations/utils.py

Support case sensitive columns in MySQL.
tested locally
cc:

[xy] Support case sensitive columns in MySQL.

---

mage_ai/orchestration/pipeline_scheduler.py

Pass event variable to kwargs.
tested locally
cc:

[xy] Pass event variable to kwargs.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.8.29
* https://github.com/mage-ai/mage-ai/pull/2258
* https://github.com/mage-ai/mage-ai/pull/2259
* https://github.com/mage-ai/mage-ai/pull/2255
* https://github.com/mage-ai/mage-ai/pull/2261
* https://github.com/mage-ai/mage-ai/pull/2262
* https://github.com/mage-ai/mage-ai/pull/2263
* https://github.com/mage-ai/mage-ai/pull/2265
* https://github.com/mage-ai/mage-ai/pull/2264
* https://github.com/mage-ai/mage-ai/pull/2266
n/a
cc:

[xy] Bump version to 0.8.29

---

mage_ai/shared/security.py

Whitelist more env vars.
tested locally
cc:

[xy] Whitelist more env vars.

---

mage_ai/api/presenters/SyncPresenter.py
mage_ai/api/resources/SyncResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/sync/__init__.py
mage_ai/data_preparation/sync/git_sync.py
mage_ai/frontend/components/VersionControl/GitActions.tsx
mage_ai/frontend/interfaces/SyncType.ts
mage_ai/frontend/pages/settings/workspace/sync-data.tsx

Add a section to the git configuration to save git settings. The fields are username, email, ssh public key, and ssh private key. The ssh keys are saved as encrypted Mage secrets. If the ssh keys are ever deleted/removed, then we will recreate the id_rsa and id_rsa.pub files with the values stored in the secrets. 
tested on local docker
cc: @wangxiaoyou1993 for backend

[dy] Save git settings

---

mage_ai/api/policies/GitBranchPolicy.py
mage_ai/api/policies/SyncPolicy.py

Add list and detail to allow read policy.
tested locally
cc:

[dy] Update sync policy

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/2268
* https://github.com/mage-ai/mage-ai/pull/2269
* https://github.com/mage-ai/mage-ai/pull/2270
* https://github.com/mage-ai/mage-ai/pull/2278
tested locally
cc:

[dy] Bump to 0.8.30

---

mage_ai/data_integrations/destinations/constants.py
mage_integrations/mage_integrations/destinations/amazon_s3/README.md
mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py
mage_integrations/mage_integrations/destinations/amazon_s3/templates/config.json

Add S3 destination to data integration pipeline.
Supported file types
* parquet
* csv
tested locally
cc:

[xy] Add S3 destination to data integration pipeline.

---

mage_integrations/mage_integrations/destinations/mysql/utils.py
mage_integrations/mage_integrations/sources/sql/base.py

Map decimal to number for mysql source.
tested locally
cc:

[xy] Map decimal to number for mysql source.

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/data_preparation/logging/logger.py
mage_ai/data_preparation/models/block/__init__.py

Pass logger to transformer for streaming pipeline.
Example usage:
```
@transformer
def transform(messages: List[Dict], *args, **kwargs):
try:
raise Exception('test')
except Exception as err:
kwargs['logger'].error('Test exception', error=err)
return messages
```
tested locally
cc:

[xy] Pass logger to transformer.

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2291
- https://github.com/mage-ai/mage-ai/pull/2290
- https://github.com/mage-ai/mage-ai/pull/2289
- https://github.com/mage-ai/mage-ai/pull/2288
- https://github.com/mage-ai/mage-ai/pull/2285
- https://github.com/mage-ai/mage-ai/pull/2284
- https://github.com/mage-ai/mage-ai/pull/2283
- https://github.com/mage-ai/mage-ai/pull/2282
- https://github.com/mage-ai/mage-ai/pull/2277

[td] 0.8.31

---

mage_ai/api/policies/GitBranchPolicy.py
mage_ai/api/presenters/GitBranchPresenter.py

update git branch permissions
tested locally
cc:

[dy] Update permissions

---

mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/variable_manager.py

Use clean name for variable dir path.
Fix the variable path on windows.
tested locally on windows
cc:

[xy] Use clean name for variable dir path.

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/2286
* https://github.com/mage-ai/mage-ai/pull/2293
* https://github.com/mage-ai/mage-ai/pull/2294
cc:

[dy] Bump to 0.8.32

---

docs/community/contributing.mdx
docs/contributing/backend/overview.mdx
docs/contributing/frontend/overview.mdx
docs/mint.json
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/io/postgres.py

- Don’t limit raw SQL query; allow all rows to be retrieved
- Support SQL blocks passing data to downstream SQL blocks with different data providers
- Raise an exception if a raw SQL block is trying to interpolate an upstream raw SQL block from a different data provider
- Fix date serialization from 1 block to another

[td] Support SQL block interoperability between different providers

---

mage_integrations/mage_integrations/destinations/bigquery/utils.py
mage_integrations/mage_integrations/sources/hubspot/tap_hubspot/__init__.py

Fix array of int type in bigquery destination
tested locally
cc:

[xy] Fix array of int type in bigquery destination

---

mage_ai/api/presenters/PipelinePresenter.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/oracle/components/PopupMenu/PopupMenuContainer.tsx
mage_ai/frontend/oracle/components/PopupMenu/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/utils/date.ts
mage_ai/tests/data_preparation/models/test_pipeline.py

- Show message modal if user has a stale pipeline open or tries to save a stale pipeline (e.g. multiple tabs with same pipeline open in the editor and makes changes in one).

[jk] Prevent editing stale pipelines

---

mage_ai/data_preparation/git/__init__.py
mage_ai/frontend/interfaces/SyncType.ts
mage_ai/frontend/pages/settings/workspace/sync-data.tsx

As title. Also added a label description for the local repo path field in the Git settings page.
tested locally
cc:

[dy] Create local git path if it doesn't exist

---

mage_ai/data_integrations/sources/constants.py
mage_ai/data_preparation/templates/template.py
mage_integrations/mage_integrations/sources/snowflake/README.md
mage_integrations/mage_integrations/sources/snowflake/__init__.py
mage_integrations/mage_integrations/sources/snowflake/templates/config.json
mage_integrations/mage_integrations/sources/sql/base.py

Add Snowflake source to date integration pipeline.
tested locally
cc:

[xy] Add Snowflake source.

---

mage_ai/data_preparation/models/block/integration/__init__.py

Fix index out of range error in data integration transformer.
tested locally
cc:

[xy] Fix index out of range error in data integration transformer.

---

docs/design/blocks/sensor.mdx

[tc] adding sensor image

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2302
- https://github.com/mage-ai/mage-ai/pull/2300
- https://github.com/mage-ai/mage-ai/pull/2298
- https://github.com/mage-ai/mage-ai/pull/2297
- https://github.com/mage-ai/mage-ai/pull/2304
- https://github.com/mage-ai/mage-ai/pull/2305
- https://github.com/mage-ai/mage-ai/pull/2306
- https://github.com/mage-ai/mage-ai/pull/2310
N/A

[jk] Bump to v0.8.34

---

docs/contributing/backend/api/pipeline-runs.mdx
docs/contributing/backend/api/pipeline-schedules.mdx
docs/mint.json

[td] API docs round 3

---

mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/oracle/styles/themes/dark.ts

[td] Add helper for CRON syntax

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/constants.ts
mage_ai/frontend/components/CodeBlock/index.tsx

- Manually input dbt block profile to allow variable interpolation
- Show dbt logs when running compile and preview

[td] Improve dbt block UI

---

mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
mage_ai/frontend/oracle/elements/Inputs/Select.tsx
mage_ai/server/execution_manager.py

When a dbt model runs and if it’s configured to use a schema with a suffix, Mage will now take that into account when fetching a sample of the model at the end of the block run.

[td] Support dbt staging

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2317
- https://github.com/mage-ai/mage-ai/pull/2316
- https://github.com/mage-ai/mage-ai/pull/2314
- https://github.com/mage-ai/mage-ai/pull/2313

[td] 0.8.35

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2319

[td] 0.8.36

---

mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/server/execution_manager.py
mage_ai/server/utils/output_display.py

- Chart blocks weren’t loading their data properly
- Fix raw SQL block trying to export upstream python block

[td] Fix chart blocks loading data

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2325
- https://github.com/mage-ai/mage-ai/pull/2323

[td] 0.8.37

---

mage_integrations/mage_integrations/destinations/bigquery/utils.py

Remove emoji code before writing to BigQuery
tested locally
cc:

[xy] Remove emoji code before writing to BigQuery

---

mage_ai/settings/__init__.py

Set default verbosity level to info.
tested locally
cc:

[xy] Set default verbosity level to info.

---

mage_integrations/mage_integrations/sources/postgresql/README.md
mage_integrations/mage_integrations/sources/postgresql/__init__.py
mage_integrations/mage_integrations/sources/postgresql/templates/config.json
mage_integrations/mage_integrations/tests/sources/test_base.py

Allow customizing the publication name for logical replication.
tested locally
cc:

[xy] Allow customizing the publication name for logical replication.

---

docs/getting-started/setup.mdx

[tc] added image to setup page

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2335
- https://github.com/mage-ai/mage-ai/pull/2329
- https://github.com/mage-ai/mage-ai/pull/2331
- https://github.com/mage-ai/mage-ai/pull/2330
- https://github.com/mage-ai/mage-ai/pull/2321
- https://github.com/mage-ai/mage-ai/pull/2327
- https://github.com/mage-ai/mage-ai/pull/2315

[td] 0.8.38

---

mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/Terminal/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/terminal/index.tsx
mage_ai/server/server.py
mage_ai/server/terminal_server.py

Use named terminals instead of creating a unique terminal every time Mage connects to the terminal websocket.
tested locally
cc:

[dy] Use named terminals

---

mage_ai/io/mssql.py
mage_ai/io/mysql.py
mage_ai/io/postgres.py
mage_ai/io/sql.py
mage_ai/io/trino.py

Fix inserting array to Postgres.
tested locally
cc:

[xy] Fix inserting array to Postgres.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.8.39
* https://github.com/mage-ai/mage-ai/pull/2337
* https://github.com/mage-ai/mage-ai/pull/2332
* https://github.com/mage-ai/mage-ai/pull/2339
n/a
cc:

[xy] Bump version to 0.8.39

---

mage_integrations/mage_integrations/connections/google_search_console/__init__.py
mage_integrations/mage_integrations/sources/google_search_console/README.md
mage_integrations/mage_integrations/sources/google_search_console/__init__.py
mage_integrations/mage_integrations/sources/google_search_console/templates/config.json

Support email in google_search_console config.
cc:

[xy] Support email in google_search_console config.

---

mage_ai/data_preparation/models/pipeline.py

This was occurring due to race conditions:

[td] Check test file before reading and deleting

---

mage_ai/server/terminal_server.py

[dy] Update shell command check

---

mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

Autosave every 10 seconds instead of 5.

[td] Increase autosave interval from 5 to 10 seconds

---

docs/development/environment-variables.mdx
docs/production/data-sync/git.mdx

Update formatting for docs in my previous PR.
cc:

[dy] Update formatting

---

mage_ai/server/constants.py
setup.py

Bump to version 0.8.41.
Includes the following changes:
* https://github.com/mage-ai/mage-ai/pull/2345
* https://github.com/mage-ai/mage-ai/pull/2347
* https://github.com/mage-ai/mage-ai/pull/2351
cc:

[dy] Bump to 0.8.41

---

docs/tutorials/load-api-data.mdx

[td] Update ETL tutorial with easier transformer

---

mage_ai/frontend/components/Terminal/index.tsx

Support copy and pasting multiple commands at once.
tested locally
cc: @johnson-mage I changed some of the command checks, and I don't know how it might affect some edge cases that I haven't tested. Just wanted to check with you to see if you see anything that could break something.

[dy] Update terminal to support multi cmds

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/Dashboard/index.style.tsx
mage_ai/frontend/components/Sidekick/index.style.ts
mage_ai/frontend/components/Sidekick/index.tsx

- Sticky sidekick vertical navigation

[td] Improve vertical navigation fixed scrolling

---

mage_ai/frontend/components/PipelineLayout/index.tsx
mage_ai/frontend/components/Sidekick/index.style.ts
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

[td] Improve sidekick vertical navigation

---

mage_ai/data_preparation/git/__init__.py

Default to os.getcwd() if it's empty or empty string.
cc:

[dy] Add another default for repo path

---

Dockerfile
dev.Dockerfile

Added google-ads lib to Dockerfile
cc:

modified dockerfile to ensure google-ads library

---

mage_ai/io/bigquery.py
mage_ai/io/redshift.py
mage_ai/io/snowflake.py
mage_ai/io/sql.py
mage_ai/io/trino.py

Cleaned up the code related to a duplicated import statement for pandas in a few IO related classes.
CI
cc:
@dy46 @wangxiaoyou1993 @tommydangerous

[hw] Remove a redundant import statement for pandas

---

mage_ai/server/constants.py
setup.py

Includes:
- https://github.com/mage-ai/mage-ai/pull/2353
- https://github.com/mage-ai/mage-ai/pull/2356
- https://github.com/mage-ai/mage-ai/pull/2358
- https://github.com/mage-ai/mage-ai/pull/2359
- https://github.com/mage-ai/mage-ai/pull/2360
- https://github.com/mage-ai/mage-ai/pull/2363
- https://github.com/mage-ai/mage-ai/pull/2364
- https://github.com/mage-ai/mage-ai/pull/2365
- https://github.com/mage-ai/mage-ai/pull/2361
- https://github.com/mage-ai/mage-ai/pull/2367
N/A

[jk] Bump to v0.8.42

---

docs/guides/triggers/configure-triggers-in-code.mdx
docs/mint.json
mage_ai/api/resources/PipelineResource.py
mage_ai/data_preparation/models/file.py
mage_ai/data_preparation/models/triggers/__init__.py
mage_ai/orchestration/backfills/service.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/orchestration/run_status_checker.py
mage_ai/server/api/triggers.py
mage_ai/tests/orchestration/db/test_models.py

Support trigger in `triggers.yaml` in pipeline folder.
Example:
```
triggers:
- name: test_example_trigger
schedule_type: time
schedule_interval: "@daily"
start_time: 2023-01-01
status: active
```
tested locally
cc:

[xy] Support trigger in code

---

mage_ai/frontend/components/CodeBlock/index.tsx

Update `useEffect` dependencies list.
cc:

[dy] Fix callback UI issue

---

.gitignore
scripts/dev.sh
scripts/init.sh

Reverts mage-ai/mage-ai#2366
Revert this PR since it causes this error
@thinkabovelimit Could you update the script to be the one below?
```
docker_version=$(docker version --format '{{.Server.Version}}')
if [[ "$docker_version" == 2*.* ]]; then
HOST=$HOST \
PORT=$PORT \
PROJECT=$PROJECT_NAME \
MANAGE_INSTANCE=$MANAGE_INSTANCE \
docker compose -f docker-compose.yml up
else
HOST=$HOST \
PORT=$PORT \
PROJECT=$PROJECT_NAME \
MANAGE_INSTANCE=$MANAGE_INSTANCE \
docker-compose -f docker-compose.yml up
fi
```

Revert "init file update to support docker latest versions"

---

docs/mint.json

Fix mint.json
ref: https://mintlify.com/docs/api-playground/overview
CI
cc:

[xy] Fix mint.json

---

mage_ai/io/postgres.py

Use parameterized query to insert data into postgres. This solves the quotes issue in string.
https://www.psycopg.org/docs/cursor.html#cursor.executemany
tested locally
cc:

[xy] Use parameterized query to insert data into postgres.

---

mage_ai/api/resources/IntegrationSourceResource.py
mage_ai/data_preparation/executors/ecs_block_executor.py
mage_ai/data_preparation/executors/k8s_block_executor.py
mage_ai/services/k8s/config.py
mage_ai/services/k8s/job_manager.py

Allow customizing k8s executor resource.
tested locally
cc:

[xy] Allow customizing k8s executor resource.

---

docs/about/releases.mdx

[tc] update changelog links

---

mage_ai/orchestration/db/models/schedules.py

Fix timezone in pipeline run execution date.
tested locally
cc:

[xy] Fix timezone in pipeline run execution date.

---

mage_ai/data_preparation/models/pipeline.py

Raise exception when loading empty config.
n/a
cc:

[xy] Raise exception when loading empty config.

---

mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/storage/local_storage.py
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Fix errors when trying to delete analysis
- Don’t hide block when clicking in the dependency tree
- Show view pipeline button when viewing a file

[td] Fix error when trying to delete analysis

---

mage_ai/io/postgres.py

Fix serializing the list of dictionary and NaT.
tested exporting this dataframe
```
df = pd.DataFrame(
[
[1, "123f'cdscdspel3pe'.fds432", '2023-01-01', [2, 3], ['1', '2'], [dict(a=1)], '[{"a": 1}]'],
[2, "23335", '2023-03-01', [1, 2, 3, 4], np.NaN,  [dict(b=1)], '{"a": 1}'],
[3, "1111", np.NaN, [1, 2, 3, 4, 5], None, [], '{"a": 1}'],
],
columns=['col1', 'create', 'col3', 'col4', 'col5', 'col6', 'col7'],
)
df['col3'] = pd.to_datetime(df['col3'])
```
cc:

[xy] More fixes for postgres exporter.

---

mage_integrations/mage_integrations/destinations/redshift/__init__.py

Handle unique constraints in Redshift destination.
tested locally
cc:

[xy] Handle unique constraints in Redshift destination.

---

mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/server/constants.py
setup.py

- dbt block input to downstream Python block in pipeline run is a list of 1 dictionary
- Sidekick on triggers pages has a header that needs to be removed
- https://github.com/mage-ai/mage-ai/pull/2389
- https://github.com/mage-ai/mage-ai/pull/2387
- https://github.com/mage-ai/mage-ai/pull/2386
- https://github.com/mage-ai/mage-ai/pull/2385

[td] 0.8.45

---

.flake8

Including a `.flake8` file in the repository to improve developers who use integrated development environments (IDEs) like PyCharm or VSCode or Vim experiences. This provide real-time feedback on coding style and potential errors as developers write code, making it easier to catch issues early on in the development process.
Local
cc:

add flake8 configuration

---

docs/development/testing/unit-tests.mdx
docs/mint.json
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/shared/constants.py
mage_ai/shared/environments.py

Add doc for writing unit tests.
n/a
cc:

[xy] Add doc for writing unit tests.

---

mage_ai/data_preparation/models/variable.py

Write spark dataframe to parquet instead of csv.
tested locally
cc:

[xy] Write spark dataframe to parquet instead of csv.

---

mage_ai/settings/__init__.py

Fix REQUIRE_USER_AUTHENTICATION value.
tested locally
cc:

[xy] Fix REQUIRE_USER_AUTHENTICATION value.

---

mage_ai/cli/main.py
mage_ai/server/scheduler_manager.py

Update sentry integration to output errors from pipeline scheduler and mage run command.
tested locally
cc:

[dy] Update sentry integration

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2403
- https://github.com/mage-ai/mage-ai/pull/2401
- https://github.com/mage-ai/mage-ai/pull/2402
- https://github.com/mage-ai/mage-ai/pull/2395
- https://github.com/mage-ai/mage-ai/pull/2368
- https://github.com/mage-ai/mage-ai/pull/2397
- https://github.com/mage-ai/mage-ai/pull/2396

[td] 0.8.47

---

mage_integrations/mage_integrations/sources/chargebee/state.py

State can be empty when previewing data, so add check for that.
tested locally
cc:

[dy] Update chargebee load sample data

---

mage_ai/data_preparation/git/__init__.py

Import git only when the `Git` feature is used.
tested locally
cc:

[dy] Import git when needed

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/io/snowflake.py
mage_ai/server/utils/output_display.py
mage_ai/server/websocket_server.py

Add default limit and limit override to sql blocks. Similar to DBT blocks, but DBT blocks won't have a default limit.
tested locally
cc:

[dy] Add limit to sql blocks

---

mage_ai/data_preparation/models/file.py
mage_ai/frontend/components/CodeBlock/constants.ts
mage_ai/frontend/components/CodeEditor/autocomplete/functions.ts
mage_ai/frontend/components/CodeEditor/autocomplete/importLibraries.ts
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/FileEditor/utils.ts
mage_ai/frontend/components/FileSelectorPopup/index.tsx
mage_ai/frontend/components/FileUploader/index.tsx
mage_ai/frontend/components/FileVersions/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/utils/models/dbt.ts
mage_ai/frontend/utils/string.ts

- Update front-end to use `path.sep` to support Windows

[td] Update all slashes to path.sep

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2405
- https://github.com/mage-ai/mage-ai/pull/2406
- https://github.com/mage-ai/mage-ai/pull/2407
- https://github.com/mage-ai/mage-ai/pull/2408
- https://github.com/mage-ai/mage-ai/pull/2400
- https://github.com/mage-ai/mage-ai/pull/2409
- https://github.com/mage-ai/mage-ai/pull/2410

[td] 0.8.48

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/CodeBlock/HiddenBlock/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/package.json
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/yarn.lock

Drag and drop blocks to reorder them in the pipeline.
https://user-images.githubusercontent.com/1066980/232201799-d7ddd7b4-f2f4-4c40-98c9-6b536a69f141.mov

[td] Drag and drop to re-order blocks

---

mage_ai/api/resources/DataProviderResource.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/templates/repo/io_config.yaml
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/interfaces/DataProviderType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Hide ClickHouse schema
- Fix drag and drop issues

[td] Hide clickhouse schema

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/io/sql.py

- Automatically add catalog to Trino query

[td] Update Trino query

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2414
- https://github.com/mage-ai/mage-ai/pull/2413
- https://github.com/mage-ai/mage-ai/pull/2412

[td] 0.8.49

---

docs/development/blocks/sql/trino.mdx
docs/guides/sql-blocks.mdx
docs/mint.json

[td] Docs for Trino SQL blocks

---

mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/data_preparation/models/block/sql/clickhouse.py
mage_ai/data_preparation/models/block/sql/mssql.py
mage_ai/data_preparation/models/block/sql/mysql.py
mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/data_preparation/models/block/sql/redshift.py
mage_ai/data_preparation/models/block/sql/snowflake.py
mage_ai/data_preparation/models/block/sql/trino.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/templates/repo/io_config.yaml
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/io/bigquery.py
mage_ai/io/config.py
mage_ai/io/postgres.py
mage_ai/io/redshift.py
mage_ai/io/snowflake.py
mage_ai/io/sql.py
mage_ai/io/trino.py

- Only export upstream blocks if current block using raw SQL and its using the variable
- Update SQL io to use io_config.yaml database and schema by default

[td] Improve SQL blocks

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2419
- https://github.com/mage-ai/mage-ai/pull/2417

[td] 0.8.50

---

mage_ai/api/policies/BlockTemplatePolicy.py
mage_ai/api/presenters/BlockTemplatePresenter.py
mage_ai/api/resources/BlockTemplateResource.py
mage_ai/data_preparation/templates/constants.py
mage_ai/data_preparation/templates/data_exporters/default.jinja
mage_ai/data_preparation/templates/data_exporters/deltalake/azure_blob_storage.py
mage_ai/data_preparation/templates/data_exporters/deltalake/default.jinja
mage_ai/data_preparation/templates/data_exporters/deltalake/gcs.py
mage_ai/data_preparation/templates/data_exporters/deltalake/s3.py
mage_ai/data_preparation/templates/data_loaders/deltalake/azure_blob_storage.py
mage_ai/data_preparation/templates/data_loaders/deltalake/default.jinja
mage_ai/data_preparation/templates/data_loaders/deltalake/gcs.py
mage_ai/data_preparation/templates/data_loaders/deltalake/s3.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/BlockTemplateType.ts
mage_ai/tests/data_preparation/test_templates.py

[td] Add data loader and data exporter templates for Delta Lake

---

mage_ai/server/constants.py
setup.py

Revert "[td] 0.8.51"

---

docs/guides/streaming/destinations/dummy.mdx
docs/guides/streaming/overview.mdx
docs/guides/streaming/sources/amazon-sqs.mdx
docs/mint.json
mage_ai/data_preparation/templates/data_exporters/streaming/dummy.yaml
mage_ai/data_preparation/templates/data_loaders/streaming/amazon_sqs.yaml
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/frontend/interfaces/DataSourceType.ts
mage_ai/streaming/constants.py
mage_ai/streaming/sinks/base.py
mage_ai/streaming/sinks/dummy.py
mage_ai/streaming/sinks/sink_factory.py
mage_ai/streaming/sources/amazon_sqs.py
mage_ai/streaming/sources/kafka.py
mage_ai/streaming/sources/shared.py
mage_ai/streaming/sources/source_factory.py
mage_ai/tests/streaming/sinks/test_dummy.py
mage_ai/tests/streaming/sources/test_amazon_sqs.py

Add amazon sqs streaming source and dummy sink.
tested locally
added unit tests
cc:

[xy] Add sqs streaming source and dummy sink.

---

docs/dbt/overview.mdx
mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
requirements.txt

[td] Add ldap3 as a requirement

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2427
- https://github.com/mage-ai/mage-ai/pull/2426
- https://github.com/mage-ai/mage-ai/pull/2422

[td] 0.8.51

---

mage_ai/frontend/components/PipelineLayout/index.tsx
mage_ai/frontend/components/Sidekick/Navigation/constants.ts
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/utils/routing.ts

- Fix double scrollbar in data tab
- Preserve file path params when clicking sidekick navigation

[td] Fix double scrollbar in data tab

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/utils/models/log.ts

Update logging parsing logic as it was excluding some logs. I updated the logging in the block executor to be more consistent as well.
tested locally
cc: @johnson-mage can you take a look? and see if it conflicts with your log changes?

[dy] Update logging

---

mage_ai/data_preparation/git/__init__.py
mage_ai/frontend/components/VersionControl/GitActions.tsx

Update git actions error message to use the `stderr` of the command.
tested locally
cc:

[dy] Update git actions error message

---

docs/production/observability/sentry.mdx

Update formatting of Sentry documentation.
cc:

[dy] Update sentry doc

---

docs/integrations/databases/ClickHouse.mdx
docs/mint.json

For the newly added ClickHouse database connector, the user guide document is missing, which has been added.
CI
cc:

[hw] Add the document for ClickHouse

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2439
- https://github.com/mage-ai/mage-ai/pull/2431
- https://github.com/mage-ai/mage-ai/pull/2433
- https://github.com/mage-ai/mage-ai/pull/2432
- https://github.com/mage-ai/mage-ai/pull/2430

[td] 0.8.52

---

mage_ai/shared/security.py

Fix whitelist values in output.
tested locally
cc:

[xy] Fix whitelist values in output.

---

mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/services/k8s/config.py

Fix dbt "run all model" bug.
tested locally
cc:

[xy] Fix dbt all model bug.

---

mage_ai/data_preparation/shared/utils.py

Change `ModuleNotFoundError` to `ImportError` to catch more cases.
tested locally
cc:

[dy] Change to ImportError

---

scripts/run_app.sh

Allow override ulimit -n.
tested locally
cc:

[xy] Allow override ulimit -n.

---

mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

[jk] Add pagination to Triggers and Block Runs pages

---

mage_ai/io/postgres.py

Fix column type detection for list of dictionary. Exclude empty lists when detecting column type.
tested locally
cc:

[xy] Fix column type detection for list of dictionary.

---

mage_ai/data_preparation/executors/block_executor.py

Add try/catch to on success callback as well.
tested locally
cc:

[dy] Update on success callback

---

mage_ai/api/policies/BlockPolicy.py
mage_ai/api/presenters/PipelinePresenter.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/constants.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/DependencyGraph/GraphNode.tsx
mage_ai/frontend/components/DependencyGraph/index.style.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/oracle/components/Badge/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/utils/models/block.ts
mage_ai/orchestration/pipeline_scheduler.py

- Support dynamic child block from multiple branches with dynamic blocks if all but 1 dynamic branch reduces

[td] Fix dynamic block child descendants

---

docs/guides/streaming/sources/amazon-sqs.mdx
mage_ai/data_preparation/templates/data_loaders/streaming/amazon_sqs.yaml
mage_ai/streaming/sources/amazon_sqs.py

Allow deleting sqs message manually.
tested locally
cc:

[xy] Allow deleting sqs message manually.

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/PipelineDetail/Extensions/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

[td] Fix UI bug for GX

---

mage_ai/io/trino.py

This error can occur right after creating a table and trying to immediately fetch data from it.
```
TrinoExternalError(type=EXTERNAL, name=HIVE_PATH_ALREADY_EXISTS, message="Target directory for table 'etl_tmp.dev_chengxuan_api_to_table_python_generate_df1_v1' already exists: s3a://scratch/default/etl_tmp.db/dev_chengxuan_api_to_table_python_generate_df1_v1", query_id=20230420_002515_03976_ijew4)
```
We’ll try 3 times and wait a second in between each try.

[td] Mitigate Trino race condition

---

mage_ai/frontend/components/CodeBlock/index.tsx

Remove variables from dependency list.
tested locally
cc:

[dy] Update useEffect

---

mage_ai/api/presenters/KernelPresenter.py
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/interfaces/KernelType.ts
mage_ai/frontend/oracle/components/PopupMenu/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/storage/localStorage.ts

Add warning for kernel if it unexpectedly restarts. Also, add some memory and cpu metrics for the kernel. 
tested for python3 kernel. will also test for other kernels

[dy] Add kernel warning

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/orchestration/db/models/schedules.py

Allow running multiple executors for streaming pipeline.
tested locally
cc:

[xy] Allow running multiple executors for streaming pipeline.

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2470
- https://github.com/mage-ai/mage-ai/pull/2460
- https://github.com/mage-ai/mage-ai/pull/2467
- https://github.com/mage-ai/mage-ai/pull/2466
- https://github.com/mage-ai/mage-ai/pull/2454
- https://github.com/mage-ai/mage-ai/pull/2465

[td] 0.8.54

---

mage_ai/api/presenters/PipelinePresenter.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/tests/data_preparation/models/test_pipeline.py

Add pipeline executor count to API.
tested locally
cc:

[xy] Add pipeline executor count to API.

---

docs/data-integrations/destinations/add-new-destination.mdx

Add documentation for adding a new destination.
n/a
cc:

[xy] Add documentation for adding a new destination.

---

mage_ai/data_preparation/templates/repo/io_config.yaml
mage_ai/io/bigquery.py
mage_ai/io/config.py

Support configuring location of BigQuery client.

[td] Add location to BigQuery IO

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2478
- https://github.com/mage-ai/mage-ai/pull/2477
- https://github.com/mage-ai/mage-ai/pull/2475
- https://github.com/mage-ai/mage-ai/pull/2474
- https://github.com/mage-ai/mage-ai/pull/2472

[td] 0.8.55

---

mage_ai/server/constants.py
setup.py

[jk] Bump to v0.8.56

---

README.md
docs/introduction/overview.mdx

[jk] Update quick start doc to reflect change in Docker port

---

docs/developing-in-the-cloud/setting-up-git.mdx
mage_ai/api/presenters/GitBranchPresenter.py
mage_ai/api/resources/GitBranchResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/shared/secrets.py
mage_ai/data_preparation/sync/__init__.py

Small update to git secret management. Also add docs for Gitlab
tested locally
cc:

[dy] Update git secret management

---

docs/community/contributing.mdx

[tc] added image

---

mage_ai/cli/main.py

Fix mage run command. Set repo_path before intializing the DB so that we can get correct db_connection_url.
tested locally
cc:

[xy] Fix mage run command.

---

setup.py

Bump version to 0.8.57.
* https://github.com/mage-ai/mage-ai/pull/2487
* https://github.com/mage-ai/mage-ai/pull/2486
* https://github.com/mage-ai/mage-ai/pull/2484
n/a
cc:

[xy] Bump version to 0.8.57.

---

mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx

Update pyspark cluster selection.
tested locally
cc:

[dy] Add useMemo

---

mage_ai/frontend/components/FileBrowser/Folder.tsx

[td] Add folder lines in file browser

---

mage_ai/frontend/components/Sessions/SignForm/index.tsx
mage_ai/frontend/pages/_app.tsx

Automatically redirect users to the sign in page if they are signed in but can’t load anything.

Automatically redirect users to the sign in page

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2503
- https://github.com/mage-ai/mage-ai/pull/2502
- https://github.com/mage-ai/mage-ai/pull/2501
- https://github.com/mage-ai/mage-ai/pull/2476
- https://github.com/mage-ai/mage-ai/pull/2499
- https://github.com/mage-ai/mage-ai/pull/2498
- https://github.com/mage-ai/mage-ai/pull/2468
- https://github.com/mage-ai/mage-ai/pull/2421
- https://github.com/mage-ai/mage-ai/pull/2494
- https://github.com/mage-ai/mage-ai/pull/2493

[td] 0.8.58

---

docs/production/data-sync/git.mdx
mage_ai/data_preparation/git/__init__.py

Some users have run into a `dubious ownership` error when trying to use git. In order to bypass the error, I added the local repository as a global safe directory.
tested locally
cc:

[dy] Dubious ownership error

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2508
- https://github.com/mage-ai/mage-ai/pull/2510
- https://github.com/mage-ai/mage-ai/pull/2507
- https://github.com/mage-ai/mage-ai/pull/2506
- https://github.com/mage-ai/mage-ai/pull/2512

[jk] Bump to v0.8.60

---

mage_ai/data_preparation/models/block/utils.py

Fix dynamic block input variables.
tested locally
cc:

[xy] Fix dynamic block input variables.

---

mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py
mage_integrations/mage_integrations/sources/amazon_s3/README.md
mage_integrations/mage_integrations/sources/amazon_s3/__init__.py
mage_integrations/mage_integrations/sources/amazon_s3/templates/config.json

Support assuming IAM role to access S3 bucket.
tested locally
cc:

[xy] Support authenticating s3 with role arn.

---

mage_ai/frontend/components/CodeBlock/index.tsx

Remove useEffect and add to `useState` default.
tested locally

[dy] Remove useEffect

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2515
- https://github.com/mage-ai/mage-ai/pull/2516
- https://github.com/mage-ai/mage-ai/pull/2511
- https://github.com/mage-ai/mage-ai/pull/2517

[jk] Bump to v0.8.61

---

docs/guides/streaming/sources/kafka.mdx
mage_ai/streaming/sources/kafka.py
mage_ai/streaming/sources/shared.py
requirements.txt
setup.py

Support deserializing avro format in kafka streaming source.
tested locally
cc:

[xy] Support deserializing avro format.

---

mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2519
- https://github.com/mage-ai/mage-ai/pull/2521

[td] 0.8.62

---

docs/development/environment-variables.mdx
mage_ai/orchestration/notification/sender.py
mage_ai/settings/__init__.py

Allow configuring public host in emails instead of using hardcoded localhost url.
tested locally
cc:

[xy] Allow configuring public host in emails.

---

mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/templates/repo/metadata.yaml
mage_ai/data_preparation/variable_manager.py

Not set default retention period for variables.
tested locally
cc:

[xy] Not set default retention period for variables.

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2530
- https://github.com/mage-ai/mage-ai/pull/2518
- https://github.com/mage-ai/mage-ai/pull/2529
- https://github.com/mage-ai/mage-ai/pull/2527

[td] 0.8.63

---

docs/development/testing/great-expectations.mdx
mage_ai/data_preparation/models/block/extension/block.py
mage_ai/data_preparation/models/block/extension/great_expectations.py

Use JSON to define expectations.
```
expectations_json = [
{
"expectation_type": "expect_table_row_count_to_be_between",
"kwargs": {
"min_value": 1000,
"max_value": 10000
}
},
{
"expectation_type": "expect_column_values_to_not_be_null",
"kwargs": {
"column": "user ID",
"result_format": "BASIC"
}
}
]
@extension('great_expectations', expectations=expectations_json)
def validate(validator, *args, **kwargs):
pass
```

[td] Use JSON for GX suite

---

mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx

[td] Right click menu for pipelines list page

---

docs/guides/streaming/sources/amazon-sqs.mdx
mage_ai/data_preparation/templates/data_loaders/streaming/amazon_sqs.yaml
mage_ai/streaming/sources/amazon_sqs.py

Fix typo in sqs source.
tested locally
cc:

[xy] Fix typo in sqs source.

---

mage_ai/data_preparation/templates/repo/io_config.yaml
mage_ai/io/config.py
mage_ai/io/snowflake.py
mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2536
- https://github.com/mage-ai/mage-ai/pull/2514
- https://github.com/mage-ai/mage-ai/pull/2533
- https://github.com/mage-ai/mage-ai/pull/2534
- https://github.com/mage-ai/mage-ai/pull/2532

[td] 0.8.64

---

docs/mint.json
docs/tutorials/load-api-data.mdx
mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/server/constants.py
setup.py

- Fix PG DB names
- Update ETL pipeline tutorial

[td] 0.8.65

---

requirements.txt

[jk] Lock ipython version

---

mage_ai/data_preparation/logging/logger_manager.py

Update max log file size.
tested locally
cc:

[xy] Update max log file size.

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2541
- https://github.com/mage-ai/mage-ai/pull/2542
- https://github.com/mage-ai/mage-ai/pull/2543
- https://github.com/mage-ai/mage-ai/pull/2545

[jk] Bump to v0.8.66

---

docs/guides/blocks/custom-blocks.mdx
docs/guides/blocks/markdown.mdx
docs/guides/triggers/events/aws.mdx
docs/mint.json

- See title.
- https://docs.mage.ai/guides/blocks/markdown-blocks

[jk] Update docs for markdown blocks

---

docs/contributing/statistics/overview.mdx
docs/mint.json
docs/tutorials/setup-dbt.mdx
mage_ai/api/resources/EventRuleResource.py
mage_ai/frontend/api/utils/AuthToken.ts
mage_ai/frontend/components/ChartBlock/index.style.tsx
mage_ai/frontend/components/Sessions/SignForm/index.tsx
mage_ai/frontend/components/charts/BarChartHorizontal.tsx
mage_ai/frontend/components/charts/BarChartVertical.tsx
mage_ai/frontend/pages/_app.tsx
mage_ai/frontend/pages/sign-in.tsx
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/server/server.py
mage_ai/server/subscriber.py
mage_ai/server/websocket_server.py

- On startup, sleep for 3 seconds before trying to create user
- EventRulesResource AWS permissions error
- Batch pipeline callback trigger data integration pipeline error
- Bar chart shows too many X-axis ticks

[td] Fix bugs 4

---

mage_ai/server/constants.py
setup.py

- On startup, sleep for 3 seconds before trying to create user
- EventRulesResource AWS permissions error
- Batch pipeline callback trigger data integration pipeline error
- Bar chart shows too many X-axis ticks

[td] 0.8.67

---

mage_ai/io/postgres.py

Use COPY command as default cmd in io Postgres to improve performance.
tested locally
cc:

[xy] Use COPY command as default cmd in io Postgres.

---

mage_integrations/mage_integrations/sources/intercom/README.md
mage_integrations/mage_integrations/sources/intercom/__init__.py
mage_integrations/mage_integrations/sources/intercom/streams.py
mage_integrations/mage_integrations/sources/intercom/templates/config.json

Support bookmark in intercom source.
tested locally
cc:

[xy] Support bookmark in intercom source.

---

mage_ai/services/k8s/config.py
mage_ai/services/k8s/job_manager.py

Allow adding custom k8s resource limits and requests.
Configure GPU resource:
* https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/
* https://medium.com/spectro-cloud/gpu-in-kubernetes-land-6978c089b3b7
tested locally
cc:

[xy] Support configuring GPU resource in k8s executor

---

docs/production/data-sync/git.mdx

[dy] Add HTTPS to git docs

---

mage_ai/server/constants.py
setup.py

[td] Undo 0.8.68 to 0.8.67

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2491
- https://github.com/mage-ai/mage-ai/pull/2555
- https://github.com/mage-ai/mage-ai/pull/2554
- https://github.com/mage-ai/mage-ai/pull/2553
- https://github.com/mage-ai/mage-ai/pull/2551
- https://github.com/mage-ai/mage-ai/pull/2552
- https://github.com/mage-ai/mage-ai/pull/2535

[td] 0.8.68

---

mage_ai/data_preparation/models/file.py

Fix file write encoding.
tested on windows
cc:

[xy] Fix file write encoding.

---

mage_ai/api/policies/UserPolicy.py
mage_ai/frontend/components/users/edit/Form/constants.ts
mage_ai/frontend/components/users/edit/Form/index.tsx
mage_ai/frontend/interfaces/UserType.ts
mage_ai/frontend/pages/settings/account/profile.tsx
mage_ai/frontend/pages/settings/workspace/users/index.tsx
mage_ai/orchestration/db/models/oauth.py

- Owners can make other users owners.
- Owners can edit other users' emails.
- Users can edit their emails.
- Sort users list.
- Clicking on the same user in the users table will close the "Edit user" side panel.
Make other users owners:
Update email:
Email validation:

[jk] Update owner abilities

---

mage_ai/api/resources/PipelineRunResource.py
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/orchestration/triggers/api.py

- Fixed issue when retrying individual pipeline runs (Using `Retry run` button) with API triggers.
- Locally using sqlite metadata db and also postgres metadata db

[jk] Bugfix retry individual pipeline runs

---

mage_ai/orchestration/backfills/service.py
mage_ai/server/constants.py
setup.py

- Fix backfill using months and years
- https://github.com/mage-ai/mage-ai/pull/2561
- https://github.com/mage-ai/mage-ai/pull/2559
- https://github.com/mage-ai/mage-ai/pull/2558

[td] 0.8.69

---

mage_ai/frontend/components/Sidekick/Charts/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx

- Explain how to add a chart when there are no charts
- Fix z-index on dividers

[td] Improve UI

---

docs/about/releases.mdx

[tc] Update releases.mdx

---

mage_ai/api/resources/GitBranchResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/preferences.py

Use `git switch` to switch brances, and add a default for auth type.
tested locally
cc:

[dy] Update git 

---

docs/contributing/statistics/overview.mdx
mage_ai/data_preparation/repo_manager.py
mage_ai/usage_statistics/logger.py

- Include version when sending usage statistics
- Create `metadata.yaml` file if it doesn’t exist

[td] Include version when sending usage statistics

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/2567
* https://github.com/mage-ai/mage-ai/pull/2568
cc:

[dy] Bump to 0.8.70

---

mage_ai/streaming/sources/google_cloud_pubsub.py

When the credential JSON file is presented, it needs to be used to when creating the Publisher client.
CI
cc:

[hw] Fix a potential authentication issue for the PubSub publisher client

---

mage_ai/frontend/components/CodeBlock/CommandButtons/AddChartMenu.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/Sidekick/constants.ts
mage_ai/frontend/components/Sidekick/index.tsx

- Certain actions (e.g. running block, creating charts) were causing errors when ran on transformer blocks in integration pipelines, so they were removed.

[jk] Hide certain integration pipeline transformer block actions

---

mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/storage/base_storage.py
mage_ai/data_preparation/storage/local_storage.py
mage_ai/data_preparation/storage/s3_storage.py
mage_ai/server/utils/output_display.py
requirements.txt

Support polars dataframe in block output.
tested locally
cc:

[xy] Support polars dataframe in block output.

---

mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py

- Support model configuration `schema` and `alias`

[td] Support dbt alias and schema model config

---

mage_ai/data_preparation/templates/repo/io_config.yaml
mage_integrations/mage_integrations/destinations/mssql/__init__.py
mage_integrations/mage_integrations/destinations/mssql/utils.py

Improvements on MSSQL destination
* Support alter command
* Support MERGE command with multiple unique columns (use AND to connect the columns)
* Add MSSQL config fields to `io_config.yaml`
tested locally
cc:

[xy] Improvements on MSSQL destination

---

mage_ai/server/websocket_server.py

Fix streaming pipeline cancellation. Send the websocket message if pipeline_uuid exists.
tested locally
cc:

[xy] Fix streaming pipeline cancellation.

---

mage_ai/server/api/blocks.py
mage_ai/server/server.py

Remove pipeline and block execute endpoints. These two endpoints are unused.
We execute block/pipeline via websocket requests.
tested locally
cc:

[xy] Remove pipeline and block execute endpoints.

---

setup.py

Fix the version of google-cloud-run package.
match the version with requirements.txt
cc:

[xy] Fix the version of google-cloud-run package.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.8.71
* https://github.com/mage-ai/mage-ai/pull/2571
* https://github.com/mage-ai/mage-ai/pull/2574
* https://github.com/mage-ai/mage-ai/pull/2573
* https://github.com/mage-ai/mage-ai/pull/2575
* https://github.com/mage-ai/mage-ai/pull/2566
* https://github.com/mage-ai/mage-ai/pull/2572
* https://github.com/mage-ai/mage-ai/pull/2578
* https://github.com/mage-ai/mage-ai/pull/2576
* https://github.com/mage-ai/mage-ai/pull/2579
* https://github.com/mage-ai/mage-ai/pull/2582
* https://github.com/mage-ai/mage-ai/pull/2580
* https://github.com/mage-ai/mage-ai/pull/2583
* https://github.com/mage-ai/mage-ai/pull/2581
* https://github.com/mage-ai/mage-ai/pull/2584
n/a
cc:

[xy] Bump version to 0.8.71

---

mage_ai/frontend/components/Terminal/index.tsx
mage_ai/server/terminal_server.py

Update terminal authentication to happen on message.
tested locally
cc:

[dy] Fix terminal user authentication

---

mage_ai/orchestration/pipeline_scheduler.py

If jobs with QUEUED status are not in queue, re-enqueue them.
tested locally
cc:

[xy] Reenqueue stale queued jobs.

---

mage_ai/services/k8s/job_manager.py
mage_ai/tests/services/k8s/test_job_manager.py

Pass in `imagePullSecrets` to the k8s job.
tested on local k8s
cc:

[dy] Pass image pull secrets

---

mage_integrations/mage_integrations/connections/mysql/__init__.py
mage_integrations/mage_integrations/destinations/mysql/README.md

Support using sshtunnel for MySQL source with private key content
tested locally
cc:

[xy] Use sshtunnel with private key content

---

mage_ai/orchestration/db/__init__.py

Catch sqlalchemy.exc.InternalError and roll back trasaction.
tested locally
cc:

[xy] Catch sqlalchemy.exc.InternalError.

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2577
- https://github.com/mage-ai/mage-ai/pull/2586
- https://github.com/mage-ai/mage-ai/pull/2588
- https://github.com/mage-ai/mage-ai/pull/2587
- https://github.com/mage-ai/mage-ai/pull/2589
- https://github.com/mage-ai/mage-ai/pull/2590
- https://github.com/mage-ai/mage-ai/pull/2591

[jk] Bump to v0.8.72

---

mage_ai/api/presenters/SyncPresenter.py
mage_ai/api/resources/SyncResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/preferences.py
mage_ai/data_preparation/shared/secrets.py

Fix git environment variables for https authentication.
tested locally
cc:

[dy] Fix git environment variables

---

mage_ai/api/presenters/SyncPresenter.py
mage_ai/api/resources/SyncResource.py
mage_ai/data_preparation/preferences.py

Update how we save the repo_path if the user leaves it empty.
tested locally
cc:

[dy] Save cwd as repo path if empty

---

mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/components/PipelineDetailPage/utils.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

[jk] Use pipeline uuid from url if pipeline is undefined

---

mage_ai/frontend/components/Terminal/index.tsx
mage_ai/server/terminal_server.py

Update terminal to send 2 commands and specify `on_message` method.
local
cc:

[dy] Update terminal

---

mage_ai/server/server.py
mage_integrations/mage_integrations/destinations/mssql/utils.py

* Add triggers page to backend route
* Support multiple keys in MSSQL destination
tested locally
cc:

[xy] Some bug fixes

---

mage_ai/api/policies/PipelineRunPolicy.py
mage_ai/frontend/components/Backfills/Detail/index.tsx
mage_ai/frontend/components/Backfills/Edit/index.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/interfaces/PipelineRunType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/backfills/[...slug].tsx
mage_ai/orchestration/pipeline_scheduler.py

[jk] Display pipeline run retries and errors on Backfills details page

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2593
- https://github.com/mage-ai/mage-ai/pull/2594
- https://github.com/mage-ai/mage-ai/pull/2595
- https://github.com/mage-ai/mage-ai/pull/2597
- https://github.com/mage-ai/mage-ai/pull/2596
- https://github.com/mage-ai/mage-ai/pull/2598
- https://github.com/mage-ai/mage-ai/pull/2600

[jk] Bump to v0.8.73

---

mage_ai/api/policies/BlockPolicy.py

Add query arguments to policy.
cc:

[dy] Fix query for block

---

docs/tutorials/setup-dbt.mdx

Some steps given in the dbt tutorial were out-of-date, and were updated based on the latest Mage UI.
Manually checked with the latest Mage UI.
cc:

[hw] Update the dbt orchestration tutorial based on latest Mage UI

---

mage_integrations/mage_integrations/connections/sql/base.py

Limit the size of query string in stacktrace to avoid overloading db
tested locally
cc:

[xy] Limit the size of query string in stacktrace.

---

mage_ai/frontend/components/CodeBlock/index.tsx

- Fix `limit` property in dbt block PUT request payload.

[jk] Fix dbt block payload request

---

mage_ai/server/websocket_server.py

Update valid to default to `not REQUIRE_USER_AUTHENTICATION`.
tested locally
cc:

[dy] Update websocket logic

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2604
- https://github.com/mage-ai/mage-ai/pull/2606
- https://github.com/mage-ai/mage-ai/pull/2607
- https://github.com/mage-ai/mage-ai/pull/2610
- https://github.com/mage-ai/mage-ai/pull/2611
- https://github.com/mage-ai/mage-ai/pull/2613

[jk] Bump to v0.8.74

---

mage_ai/server/constants.py
mage_ai/server/websocket_server.py
setup.py

For some reason this change didn't seem to get included in 0.8.74.
* https://github.com/mage-ai/mage-ai/pull/2613
local
cc:

[dy] 0.8.75

---

mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/server/terminal_server.py

Update `pip install` terminal message.
tested locally
cc:

[dy] Fix pip install

---

mage_ai/services/gcp/cloud_run/cloud_run.py

Remove startup_probe in gcp cloud run to fix error
tested on gcp
cc:

[xy] Remove startup_probe in gcp cloud run.

---

docs/orchestration/pipeline-runs/retrying-block-runs.mdx
mage_ai/api/resources/PipelineRunResource.py
mage_ai/data_preparation/models/pipelines/integration_pipeline.py
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/shared/array.py

- If a block is selected in an integration pipeline to retry block runs, only the block runs for the selected block's stream will be ran (e.g. if there are multiple streams).

[jk] Retry from selected block in integration pipeline

---

mage_ai/frontend/components/Backfills/Detail/index.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/Orchestration/CreateSchedule/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/Sidekick/GlobalVariables/index.tsx
mage_ai/frontend/components/Sidekick/Header.tsx
mage_ai/frontend/components/Sidekick/Navigation/constants.ts
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/interfaces/PipelineVariableType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/backfills/[...slug].tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

- Reduce number of API requests made when refocusing browser.
- Fix global variables count in Sidekick header.
- Local

[jk] Reduce API requests

---

mage_ai/data_preparation/models/block/__init__.py

Pass block configuration to kwargs. It can be accessed via `kwargs['configuration']`
tested locally
cc:

[xy] Pass block configuration to kwargs.

---

docs/integrations/databases/MicrosoftSQLServer.mdx
docs/mint.json

Add doc for Microsoft SQL Server.
n/a
cc:

[xy] Add doc for Microsoft SQL Server.

---

mage_ai/data_preparation/executors/ecs_block_executor.py
mage_ai/data_preparation/executors/gcp_cloud_run_block_executor.py

Fix run command for AWS and GCP job runs.
tested on gcp and aws
cc:

[xy] Fix run command for aws and gcp job runs.

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2481
- https://github.com/mage-ai/mage-ai/pull/2618
- https://github.com/mage-ai/mage-ai/pull/2620
- https://github.com/mage-ai/mage-ai/pull/2621
- https://github.com/mage-ai/mage-ai/pull/2614
- https://github.com/mage-ai/mage-ai/pull/2622
- https://github.com/mage-ai/mage-ai/pull/2624
- https://github.com/mage-ai/mage-ai/pull/2623
- https://github.com/mage-ai/mage-ai/pull/2627
- https://github.com/mage-ai/mage-ai/pull/2626

[jk] Bump to v0.8.76

---

Dockerfile
dev.Dockerfile

Install renv in Dockerfile.
tested locally
cc:

[xy] Install renv in Dockerfile.

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Mitigate code block re-renders in Pipeline Editor.
- Hide parent blocks link in Code Block header on small Main Container widths in Pipeline Editor.
- Local

[jk] Pipeline editor improvements

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/shared/retry.py

Support automatic retry for block execution
tested locally
cc:

[xy] Support automatic retry for block execution

---

mage_ai/api/resources/PipelineResource.py
mage_ai/frontend/api/utils/response.ts
mage_ai/frontend/components/ErrorPopup/index.tsx
mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/interfaces/ErrorsType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/pipelines/index.tsx

- If `Too many open files` occurs while fetching pipelines, error popup with link to docs on how to resolve will appear on the Pipelines Dashboard.

[jk] Display error popup with link to docs for too many open files err

---

mage_ai/api/policies/BlockOutputPolicy.py
mage_ai/api/policies/SchedulerPolicy.py
mage_ai/api/policies/StatusPolicy.py
mage_ai/api/presenters/BlockOutputPresenter.py
mage_ai/api/presenters/SchedulerPresenter.py
mage_ai/api/presenters/StatusPresenter.py
mage_ai/api/resources/BlockOutputResource.py
mage_ai/api/resources/PipelineResource.py
mage_ai/api/resources/SchedulerResource.py
mage_ai/api/resources/StatusResource.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/datasets/Export/index.tsx
mage_ai/frontend/pages/_app.tsx
mage_ai/frontend/pages/index.tsx
mage_ai/frontend/pages/manage/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/api/blocks.py
mage_ai/server/server.py

Removed and migrated some additional server endpoints. I didn't migrate the analyses endpoint yet because the frontend is not easily migrated. I'll do it in a separate PR.
tested locally
cc:

[dy] Remove/migrate insecure endpoints

---

mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/data_preparation/models/block/sql/utils/shared.py

…lock.
* Fix using different schemas between upstream block and current block
* Do not compare postgres schema to decide whether to cache data
tested locally
cc:

[xy] Improvements on Postgres SQL block

---

mage_ai/server/constants.py
setup.py

Bump version to 0.8.78.
* https://github.com/mage-ai/mage-ai/pull/2639
* https://github.com/mage-ai/mage-ai/pull/2641
* https://github.com/mage-ai/mage-ai/pull/2616
* https://github.com/mage-ai/mage-ai/pull/2637
* https://github.com/mage-ai/mage-ai/pull/2642
* https://github.com/mage-ai/mage-ai/pull/2605
* https://github.com/mage-ai/mage-ai/pull/2643
n/a
cc:

[xy] Bump version to 0.8.78.

---

docs/integrations/databases/MongoDB.mdx
docs/mint.json

[xy] Add doc for MongoDB.

---

docs/guides/streaming/overview.mdx
docs/integrations/databases/MongoDB.mdx
docs/mint.json

Add doc for configuring streaming pipeline executor type
n/a
cc:

[xy] Add doc for configuring streaming pipeline executor type

---

mage_ai/data_preparation/models/block/__init__.py

Include parent block uuid in callback block kwargs.
tested locally
cc:

[xy] Include parent block uuid in callback block kwargs.

---

docs/integrations/polars.mdx
docs/mint.json

Add doc for Polars integration.
n/a
cc:

[xy] Add doc for Polars integration.

---

mage_ai/api/policies/StatusPolicy.py
mage_ai/server/constants.py
setup.py

- Fix status policy to allow public access or else user auth is broken
- https://github.com/mage-ai/mage-ai/pull/2649
- https://github.com/mage-ai/mage-ai/pull/2655
- https://github.com/mage-ai/mage-ai/pull/2656

[td] 0.8.79

---

mage_ai/usage_statistics/logger.py

```
mage-ai-server-1  | {
mage-ai-server-1  |   "environment": "dev",
mage-ai-server-1  |   "platform": "Linux-5.15.49-linuxkit-aarch64-with-glibc2.31",
mage-ai-server-1  |   "project_uuid": "dangerous",
mage-ai-server-1  |   "version": "0.8.79",
mage-ai-server-1  |   "action": "impression",
mage-ai-server-1  |   "object": "project"
mage-ai-server-1  | }
```

[td] Log environment variable in usage statistics

---

mage_ai/services/gcp/cloud_run/cloud_run.py
mage_ai/services/gcp/cloud_run/config.py

Delete cloud run job after it's completed.
tested on gcp cloud run
cc:

[xy] Delete cloud run job after it's completed.

---

mage_ai/orchestration/notification/sender.py
mage_ai/tests/orchestration/notification/test_sender.py

Include trigger URL in slack alert.
tested locally
updated unit test
cc:

[xy] Include trigger URL in slack alert.

---

mage_integrations/mage_integrations/destinations/postgresql/utils.py

Use timestamptz as data type in postgres destination.
tested locally
cc:

[xy] Use timestamptz as data type in postgres destination.

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py

Support complex (tree-structure) streaming pipeline
```
source -> transformer1 -> sink2
-> transformer2 -> sink2
-> transformer3 -> sink3
```
tested locally with pipeline
cc:

[xy] Support complex streaming pipeline

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2660
- https://github.com/mage-ai/mage-ai/pull/2661
- https://github.com/mage-ai/mage-ai/pull/2662
- https://github.com/mage-ai/mage-ai/pull/2663
- https://github.com/mage-ai/mage-ai/pull/2659
- https://github.com/mage-ai/mage-ai/pull/2665
- https://github.com/mage-ai/mage-ai/pull/2667
- https://github.com/mage-ai/mage-ai/pull/2668

[td] 0.8.80

---

mage_ai/data_preparation/models/utils.py
mage_ai/data_preparation/models/variable.py

Speed up writing dataframe to disk.
tested locally
It reduced the time of writing a dataframe with 2 million rows from 90s to 16s.
cc:

[xy] Speed up writing dataframe to disk.

---

mage_integrations/mage_integrations/destinations/bigquery/__init__.py

Remove call to use pandas to_json method, and just create the json with the values.
tested locally
cc:

[dy] Remove dataframe

---

docs/production/data-sync/git.mdx
mage_ai/api/presenters/SyncPresenter.py
mage_ai/api/resources/GitBranchResource.py
mage_ai/api/resources/SyncResource.py
mage_ai/data_preparation/preferences.py
mage_ai/data_preparation/sync/__init__.py
mage_ai/data_preparation/sync/git_sync.py
mage_ai/frontend/interfaces/SyncType.ts
mage_ai/frontend/pages/settings/workspace/sync-data.tsx
mage_ai/orchestration/db/models/oauth.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/tests/api/operations/test_syncs.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

This PR fixes git sync and also updates how we save git settings for users in the backend.
tested locally and unit test
cc:

[dy] Fix git sync

---

docs/development/blocks/callbacks/overview.mdx
mage_ai/api/policies/BasePolicy.py
mage_ai/api/presenters/BasePresenter.py
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/templates/callbacks/base.jinja
mage_ai/data_preparation/templates/callbacks/orchestration/triggers/default.jinja
mage_ai/data_preparation/templates/repo/.gitignore
mage_ai/frontend/components/Backfills/Edit/index.tsx
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/charts/LineSeries.tsx
mage_ai/frontend/components/users/edit/Form/index.tsx
mage_ai/frontend/oracle/elements/Inputs/Select.tsx
mage_ai/tests/data_preparation/models/test_block.py

When initializing new repo, create a .gitignore file.

[td] Automtically create gitignore when initializing project

---

mage_ai/server/constants.py
setup.py

- Pass parent block’s output and variables to its callback blocks
- Fix missing input field and select field descriptions
- Automatically create files in Mage project that are required in Git repository setup (e.g. .gitignore)
- https://github.com/mage-ai/mage-ai/pull/2671
- https://github.com/mage-ai/mage-ai/pull/2676
- https://github.com/mage-ai/mage-ai/pull/2651
- https://github.com/mage-ai/mage-ai/pull/2670

[td] 0.8.81

---

mage_ai/data_preparation/models/variable.py

When using polars to write complex data structure, pandas fails to read.
Verify reading dataframe after write. Fallback to use pandas to write the dataframe.
tested locally
cc:

[xy] Verify reading dataframe after write

---

mage_ai/frontend/components/FileBrowser/NewFile/index.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/Files/index.tsx

- Create
- Rename
- Move
- Delete

[td] Add all file operations

---

mage_ai/data_preparation/models/pipelines/integration_pipeline.py
mage_integrations/mage_integrations/sources/postgresql/__init__.py
mage_integrations/mage_integrations/sources/sql/base.py

Close ssh tunnel connection after testing connection.
Fix showing error messages for integration pipeline testing and sample.
tested locally
cc:

[xy] Fix MySQL ssh tunnel

---

mage_ai/server/constants.py
setup.py

Bump version to include frontend build
cc:

[dy] Bump to 0.8.82

---

mage_ai/server/constants.py
setup.py

Bump version to 0.8.83.
* https://github.com/mage-ai/mage-ai/pull/2599
* https://github.com/mage-ai/mage-ai/pull/2675
* https://github.com/mage-ai/mage-ai/pull/2684
n/a
cc:

[xy] Bump version to 0.8.83.

---

mage_integrations/mage_integrations/sources/sql/base.py

Fix close connection.
tested locally
cc:

[xy] Fix close connection.

---

mage_ai/api/middleware.py
mage_ai/api/utils.py
mage_ai/tests/api/test_utils.py

This adds support for unnamed cookies in the Cookie header
Untested. Relying on CI.

Handle unnamed cookies

---

docs/development/project/setup.mdx
mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/templates/repo/.gitignore

Support dbt_project.yml custom project names and custom profile names that are different than the dbt folder name.

[td] Support dbt projects with different names

---

mage_ai/data_preparation/git/__init__.py

The git clone command would cause the entire app to hang if the host wasn't added to known hosts. I updated the git clone command to run as a separate process, so it won't block the entire app if it's stuck. Also updated it to work with the timeout.
tested locally
cc:

[dy] Fix git branch page load issue

---

mage_ai/frontend/components/Dashboard/index.style.tsx

[td] Don’t expand vertical navigation unless hovering for 300ms

---

mage_ai/frontend/components/users/edit/Form/index.tsx

Fix profile update for editors and viewers.
tested locally
cc:

[dy] Fix profile update

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2688
- https://github.com/mage-ai/mage-ai/pull/2689
- https://github.com/mage-ai/mage-ai/pull/2687
- https://github.com/mage-ai/mage-ai/pull/2693
- https://github.com/mage-ai/mage-ai/pull/2694
- https://github.com/mage-ai/mage-ai/pull/2696
- https://github.com/mage-ai/mage-ai/pull/2695
- https://github.com/mage-ai/mage-ai/pull/2697
- https://github.com/mage-ai/mage-ai/pull/2691
- https://github.com/mage-ai/mage-ai/pull/2654
- https://github.com/mage-ai/mage-ai/pull/2699

[td] 0.8.84

---

docs/guides/triggers/configure-triggers-in-code.mdx
mage_ai/data_preparation/models/triggers/__init__.py
mage_ai/orchestration/pipeline_scheduler.py

Configure environments in triggers.
tested locally
cc:

[xy] Configure environments in triggers.

---

mage_ai/data_preparation/models/utils.py

Convert numpy ndarray to list if column type is list.
Issue: https://github.com/mage-ai/mage-ai/issues/2706
tested locally
cc:

[xy] Convert numpy ndarray to list if column type is list.

---

docs/design/blocks/dynamic-blocks.mdx
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/data_preparation/models/block/sql/clickhouse.py
mage_ai/data_preparation/models/block/sql/druid.py
mage_ai/data_preparation/models/block/sql/mssql.py
mage_ai/data_preparation/models/block/sql/mysql.py
mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/data_preparation/models/block/sql/redshift.py
mage_ai/data_preparation/models/block/sql/snowflake.py
mage_ai/data_preparation/models/block/sql/trino.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/data_preparation/models/block/utils.py

- Support using dynamic child blocks for SQL blocks

[td] Dynamic SQL blocks

---

mage_ai/data_preparation/models/block/constants.py
mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/constants.ts
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileSelectorPopup/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/interfaces/BlockType.ts

[td] Allow user to configure block to run dbt snapshot

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2703
- https://github.com/mage-ai/mage-ai/pull/2698
- https://github.com/mage-ai/mage-ai/pull/2709
- https://github.com/mage-ai/mage-ai/pull/2710
- https://github.com/mage-ai/mage-ai/pull/2714
- https://github.com/mage-ai/mage-ai/pull/2664
- https://github.com/mage-ai/mage-ai/pull/2713
- https://github.com/mage-ai/mage-ai/pull/2715
- https://github.com/mage-ai/mage-ai/pull/2716
- https://github.com/mage-ai/mage-ai/pull/2717
- https://github.com/mage-ai/mage-ai/pull/2719
- https://github.com/mage-ai/mage-ai/pull/2718

[jk] Bump to v0.8.85

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2724
- https://github.com/mage-ai/mage-ai/pull/2726

[jk] Bump to v0.8.86

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py

Fix streaming pipeline kwargs.
github issue: https://github.com/mage-ai/mage-ai/issues/2730
tested locally
cc:

[xy] Fix streaming pipeline kwargs.

---

mage_ai/data_preparation/git/__init__.py

Create known hosts if it doesn't exist.
tested locally
cc:

[dy] Create known hosts if doesn't exist

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/2723
* https://github.com/mage-ai/mage-ai/pull/2734
* https://github.com/mage-ai/mage-ai/pull/2735
* https://github.com/mage-ai/mage-ai/pull/2736
cc:

[dy] Bump to 0.8.87

---

mage_ai/orchestration/db/models/schedules.py

Do not create trigger when db query fails.
tested locally
cc:

[xy] Do not create trigger when db query fails.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/utils/models/blockRun.ts

When there are multiple downstream replica blocks, this PR will fix those blocks not getting queued.

[td] Fix replica blocks not starting

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2738
- https://github.com/mage-ai/mage-ai/pull/2739

[td] 0.8.88

---

mage_ai/frontend/components/Logs/Table/index.tsx

[jk] Fix block uuid formatting for log

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py

Interpolate variables in streaming configs.
Github issue: https://github.com/mage-ai/mage-ai/issues/2732
tested locally
cc:

[xy] Interpolate variables in streaming configs.

---

mage_ai/api/policies/WidgetPolicy.py

- Update WidgetPolicy to allow editing and creating widgets without authorization errors.
- Local

[jk] Widget policy update

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/templates/sensors/bigquery.py
mage_ai/data_preparation/templates/sensors/default.py
mage_ai/data_preparation/templates/sensors/mysql.py
mage_ai/data_preparation/templates/sensors/postgres.py
mage_ai/data_preparation/templates/sensors/redshift.py
mage_ai/data_preparation/templates/sensors/s3.py
mage_ai/data_preparation/templates/sensors/snowflake.py
mage_ai/tests/data_preparation/models/test_block.py

Update sensor block to accept positional arguments.
tested locally
cc:

[dy] Update sensor block

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2712
- https://github.com/mage-ai/mage-ai/pull/2743
- https://github.com/mage-ai/mage-ai/pull/2745
- https://github.com/mage-ai/mage-ai/pull/2744
- https://github.com/mage-ai/mage-ai/pull/2725
- https://github.com/mage-ai/mage-ai/pull/2747
- https://github.com/mage-ai/mage-ai/pull/2748
- https://github.com/mage-ai/mage-ai/pull/2750

[jk] Bump to v0.8.89

---

mage_integrations/mage_integrations/destinations/snowflake/__init__.py

Fix merge command for Snowflake destination.
Error
```
SQL compilation error:
syntax error line 3 at position 26 unexpected ','..
```
tested locally
cc:

[xy] Fix merge command for Snowflake destination.

---

mage_ai/data_preparation/models/block/dbt/__init__.py

Always delete the temporary dbt profiles dir to prevent file browser performance degrade.
tested locally
cc:

[xy] Always delete the temporary dbt profiles dir.

---

mage_ai/api/utils.py
mage_ai/tests/api/test_utils.py

Pass in entity and entity_id to parent functions.
local and unit testing
cc:

[dy] Fix user auth policy permissions

---

mage_ai/server/constants.py
setup.py

Bump version to 0.8.90
* https://github.com/mage-ai/mage-ai/pull/2753
* https://github.com/mage-ai/mage-ai/pull/2760
* https://github.com/mage-ai/mage-ai/pull/2759
* https://github.com/mage-ai/mage-ai/pull/2762
* https://github.com/mage-ai/mage-ai/pull/2763
* https://github.com/mage-ai/mage-ai/pull/2764
* https://github.com/mage-ai/mage-ai/pull/2765
n/a
cc:

[xy] Bump version to 0.8.90

---

docs/getting-started/setup.mdx
docs/production/configuring-production-settings/overview.mdx
docs/production/databases/default.mdx

Some issues with the rendered MDX document format have been fixed.
Manually tested with VSCode MarkDown viewer.
cc:

[hw] Fix some minor MDX formatting issues

---

mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileBrowser/utils.ts

- Delete any file under the dbt directory; don’t check if the file is a dbt block or not

[td] Delete any file under dbt directory

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/file.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py

Support using dynamic blocks with replica blocks.

[td] Fix dynamic replica blocks

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/2769
* https://github.com/mage-ai/mage-ai/pull/2771
* https://github.com/mage-ai/mage-ai/pull/2768
version bump
cc:

[dy] Bump 0.8.91

---

docs/contributing/backend/overview.mdx

Provide the procedure on how to run unit tests for Mage backend server with a live docker container.
Manually tested the given procedure locally.
cc:

[hw] Add instructions on how to run unit tests with a docker instance

---

docs/getting-started/setup.mdx
docs/introduction/overview.mdx

Make a few minor updates in the user docs to be more consistent.
CI
cc:

[hw] Update the example project names to be consistent

---

docs/development/blocks/conditionals/overview.mdx
docs/mint.json
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/constants.py

Update conditional blocks PR.
tested locally

[dy] Address comments

---

docs/development/environment-variables.mdx
docs/guides/triggers/configure-triggers-in-code.mdx
docs/integrations/spark-pyspark.mdx
mage_ai/data_preparation/models/block/__init__.py
mage_ai/shared/environments.py

* Fix pyspark doc
* Add doc for environment variable
* Remove redundant print statements of spark session
tested locally
cc:

[xy] Some fixes

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2755
- https://github.com/mage-ai/mage-ai/pull/2757
- https://github.com/mage-ai/mage-ai/pull/2775
- https://github.com/mage-ai/mage-ai/pull/2780
- https://github.com/mage-ai/mage-ai/pull/2782
- https://github.com/mage-ai/mage-ai/pull/2784
- https://github.com/mage-ai/mage-ai/pull/2761

[jk] Bump to v0.8.92

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/components/PipelineDetail/AddonBlocks/AddonBlock.tsx

Fix conditional block inputs to get from the parent block.
tested locally

[dy] Fix conditional block inputs

---

docs/development/blocks/conditionals/overview.mdx
mage_ai/server/constants.py
setup.py

Bump to 0.8.93
* https://github.com/mage-ai/mage-ai/pull/2790
version bump
cc:

[dy] Bump 0.8.93

---

docs/integrations/spark-pyspark.mdx

Update pyspark documents for pipeline-level custom `spark_config`
CI
cc:

[hw] Add document for spark sessions with pipeline-level configs

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2797

[jk] Bump to v0.8.94

---

docs/guides/streaming/overview.mdx
docs/mint.json

Update streaming doc to include MongoDB.
n/a
cc:

[xy] Update streaming doc to include MongoDB.

---

mage_ai/data_preparation/models/block/__init__.py

[td] Fix renaming block

---

requirements.txt
setup.py

update azure-eventhub to newest version to fix uamqp error when building mage
tested locally
cc:

[dy] Bump azure-eventhub package

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/mssql.py
mage_ai/io/mssql.py

Fix MSSQL sql block schema. `Schema` was not properly set when checking table existence. Use `dbo` as the default schema if no schema is set.
tested locally
cc:

[xy] Fix MSSQL sql block schema.

---

docs/contributing/backend/overview.mdx
docs/data-integrations/destinations/add-new-destination.mdx
docs/data-integrations/sources/add-new-source.mdx
mage_integrations/mage_integrations/tests/sources/api/test_api.py

Update doc for contributing to mage integrations module.
n/a
cc:

[xy] Update doc for contributing to mage integrations module.

---

mage_ai/tests/data_cleaner/statistics/test_calculator.py
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/utils.py

Use TIMESTAMP_TZ as column type for snowflake datetime column.
tested locally
cc:

[xy] Use TIMESTAMP_TZ as column type for snowflake datetime column.

---

mage_ai/data_preparation/shared/utils.py
mage_ai/shared/hash.py
mage_ai/tests/shared/test_hash.py

Add json value macro.
Example usage: `"{{ json_value(aws_secret_var('test_secret_key_value'), 'k1') }}"`
tested locally
added unit tests
cc:

[xy] Add json value macro.

---

mage_ai/api/policies/BasePolicy.py
mage_ai/api/policies/FileContentPolicy.py
mage_ai/api/policies/FileVersionPolicy.py
mage_ai/tests/api/operations/test_sessions.py

Fix user auth when disable notebook edits is enabled.
tested locally
cc:

[dy] Fix user auth with disable edits

---

mage_ai/api/policies/BasePolicy.py
mage_ai/api/resources/WorkspaceResource.py
mage_ai/frontend/components/workspaces/ConfigureWorkspace.tsx
mage_ai/frontend/components/workspaces/Dashboard/constants.ts
mage_ai/frontend/components/workspaces/Dashboard/index.tsx
mage_ai/server/terminal_server.py
mage_ai/server/websocket_server.py

Workspace usability changes.
tested locally
cc:

[dy] Initial workspace changes

---

mage_ai/api/resources/WorkspaceResource.py
mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/2828
* https://github.com/mage-ai/mage-ai/pull/2826
* https://github.com/mage-ai/mage-ai/pull/2825
* https://github.com/mage-ai/mage-ai/pull/2824
* https://github.com/mage-ai/mage-ai/pull/2823
* https://github.com/mage-ai/mage-ai/pull/2819
* https://github.com/mage-ai/mage-ai/pull/2817
* https://github.com/mage-ai/mage-ai/pull/2816
* https://github.com/mage-ai/mage-ai/pull/2814
* https://github.com/mage-ai/mage-ai/pull/2813
* https://github.com/mage-ai/mage-ai/pull/2808
* https://github.com/mage-ai/mage-ai/pull/2807
* https://github.com/mage-ai/mage-ai/pull/2805
version bump
cc:

[dy] Bump 0.8.96

---

mage_ai/data_preparation/models/block/__init__.py

Fix test spark dataframe. Pass the spark session to variable manager.
tested locally
cc:

[xy] Fix test spark dataframe.

---

docs/development/environment-variables.mdx
docs/production/authentication/overview.mdx
mage_ai/api/operations/base.py
mage_ai/api/resources/SessionResource.py
mage_ai/api/resources/UserResource.py
mage_ai/orchestration/db/models/oauth.py
mage_ai/server/server.py
mage_ai/settings/__init__.py

Update default LDAP user access from editor to no access. I also added an environment variable so that the default access can be customized.
tested locally
cc:

[dy] Update default ldap user

---

mage_ai/server/constants.py
setup.py

Bump to 0.8.97
* https://github.com/mage-ai/mage-ai/pull/2831
* https://github.com/mage-ai/mage-ai/pull/2833
* https://github.com/mage-ai/mage-ai/pull/2835
* https://github.com/mage-ai/mage-ai/pull/2836
* https://github.com/mage-ai/mage-ai/pull/2837
cc:

[dy] Bump 0.8.97

---

mage_integrations/mage_integrations/destinations/bigquery/README.md
mage_integrations/mage_integrations/destinations/google_cloud_storage/README.md
mage_integrations/mage_integrations/destinations/google_cloud_storage/__init__.py
mage_integrations/mage_integrations/sources/bigquery/README.md

Allow authenticating with google cloud storage using instance service account.
Updated docs
tested on GCP
cc:

[xy] Allow authenticating with google cloud storage using service account

---

README.md
mage_ai/api/resources/GitBranchResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/git/api.py
mage_ai/frontend/components/VersionControl/Remote/index.tsx
mage_ai/server/server.py

- Push to remote
- Pull from remote

[td] Use GitHub OAuth token to push and pull

---

mage_ai/api/resources/GitBranchResource.py
mage_ai/api/resources/PullRequestResource.py
mage_ai/data_preparation/git/api.py
mage_ai/data_preparation/sync/__init__.py
mage_ai/frontend/components/VersionControl/Commit/index.tsx
mage_ai/frontend/components/VersionControl/constants.ts
mage_ai/frontend/components/VersionControl/index.tsx

- Don’t auto create a remote using git
- Save default values for future use

[td] Fix version control

---

docs/mint.json
docs/production/data-sync/github.mdx
mage_ai/api/policies/GitBranchPolicy.py
mage_ai/api/resources/GitBranchResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/git/api.py
mage_ai/frontend/components/VersionControl/Branches/index.tsx
mage_ai/frontend/components/VersionControl/Commit/index.tsx
mage_ai/frontend/components/VersionControl/Remote/index.tsx
mage_ai/frontend/components/VersionControl/index.tsx

[td] Add documentation for using GitHub authentication

[td] Add documentation for using GitHub authentication

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2844
- https://github.com/mage-ai/mage-ai/pull/2839
- https://github.com/mage-ai/mage-ai/pull/2770
- https://github.com/mage-ai/mage-ai/pull/2842
- https://github.com/mage-ai/mage-ai/pull/2843

[td] 0.8.98

---

docs/production/data-sync/github.mdx

[td] Add images to version control docs

---

mage_ai/data_preparation/repo_manager.py

Return default project type if there's an error fetching it.
tested locally
cc:

[dy] Fix project type error

---

mage_ai/data_preparation/models/block/sql/__init__.py

Throw exception in bigquery sql block.
tested locally
cc:

[xy] Throw exception in bigquery sql block.

---

docs/development/environment-variables.mdx
docs/production/data-sync/git.mdx
mage_ai/api/presenters/SyncPresenter.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/preferences.py
mage_ai/data_preparation/sync/__init__.py
mage_ai/data_preparation/sync/git_sync.py
mage_ai/frontend/interfaces/SyncType.ts
mage_ai/frontend/pages/settings/workspace/sync-data.tsx
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/server/server.py

[dy] Add option to sync on start up

---

mage_ai/api/resources/WorkspaceResource.py
mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/frontend/pages/manage/index.tsx
mage_ai/server/api/clusters.py

Update dashboard for kubernetes
tested locally
cc:

[dy] Workspace improvements

---

docs/development/environment-variables.mdx
docs/production/authentication/microsoft.mdx
mage_ai/api/resources/OauthResource.py
mage_ai/settings/__init__.py

Docs for enabling active directory sign in for Mage.
docs
cc:

[dy] Active directory docs

---

docs/mint.json
docs/production/authentication/microsoft.mdx

Add microsoft docs to mint.json
cc:

[dy] Add to mint json file

---

mage_ai/api/resources/OauthResource.py

[dy] Update encoding

---

mage_ai/api/resources/PipelineResource.py

Fix trigger count
tested locally
cc:

[dy] Fix trigger count

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/2853
* https://github.com/mage-ai/mage-ai/pull/2854
* https://github.com/mage-ai/mage-ai/pull/2855
* https://github.com/mage-ai/mage-ai/pull/2856
* https://github.com/mage-ai/mage-ai/pull/2863
* https://github.com/mage-ai/mage-ai/pull/2865
* https://github.com/mage-ai/mage-ai/pull/2870
* https://github.com/mage-ai/mage-ai/pull/2818
* https://github.com/mage-ai/mage-ai/pull/2874
version bump
cc:

[dy] Bump version

---

mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/repo_manager.py
mage_ai/frontend/components/Sidekick/GlobalVariables/Secrets.tsx

fix a couple of bugs
* copy text for secrets was incorrect
* git sync asyncio issue
tested locally
cc:

[dy] Small bug fixes

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/2875
version bump
cc:

[dy] Bump 0.8.100

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/2879
* https://github.com/mage-ai/mage-ai/pull/2880
cc:

[dy] 0.8.101

---

mage_ai/data_preparation/git/__init__.py

Revert previous git change.
tested locally
cc:

[dy] Update git behavior

---

mage_ai/io/clickhouse.py
mage_ai/shared/utils.py

When using ClickHouse in Data Exporter, target table was not created. 
Manually tested with a local development environment.
cc:

[hw] Support automatic table creation for ClickHouse Data Exporter

---

mage_ai/api/resources/OauthResource.py
mage_ai/frontend/components/Sessions/SignForm/index.tsx

Fix active directory redirect url construction.
tested locally
cc:

[dy] Fix active directory

---

mage_ai/server/constants.py
setup.py

Bump version to 0.8.102
* https://github.com/mage-ai/mage-ai/pull/2885
* https://github.com/mage-ai/mage-ai/pull/2887
* https://github.com/mage-ai/mage-ai/pull/2871
* https://github.com/mage-ai/mage-ai/pull/2890
* https://github.com/mage-ai/mage-ai/pull/2891
n/a
cc:

[xy] Bump version to 0.8.102

---

mage_ai/api/policies/GitCustomBranchPolicy.py
mage_ai/api/presenters/GitCustomBranchPresenter.py
mage_ai/api/resources/GitBranchResource.py
mage_ai/api/resources/GitCustomBranchResource.py
mage_ai/api/resources/OauthResource.py
mage_ai/authentication/oauth2.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/sync/git_sync.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/VersionControl/Branches/index.tsx
mage_ai/frontend/components/VersionControl/Commit/index.tsx
mage_ai/frontend/components/VersionControl/GitActions.tsx
mage_ai/frontend/components/VersionControl/GitFiles/index.tsx
mage_ai/frontend/components/VersionControl/Remote/index.tsx
mage_ai/frontend/components/VersionControl/index.tsx
mage_ai/frontend/components/shared/Header/index.tsx

Don’t automatically run git init on version control app unless clicking a button.

[td] Disable auto git init

---

docs/data-integrations/configuration.mdx
docs/data-integrations/destinations/overview.mdx
docs/data-integrations/overview.mdx
docs/data-integrations/sources/overview.mdx
docs/mint.json
mage_ai/data_preparation/models/block/integration/__init__.py
mage_ai/orchestration/pipeline_scheduler.py

Interpolate the current pipeline’s name or UUID in data integration pipelines.

[td] Interpolate pipeline name and UUID in data integration pipelines

---

docs/dbt/snapshots.mdx
docs/mint.json
mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts

- Add a dbt block that can run any generic command

[td] Add dbt generic command block

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2898
- https://github.com/mage-ai/mage-ai/pull/2895
- https://github.com/mage-ai/mage-ai/pull/2894

[td] 0.8.103

---

mage_ai/frontend/components/shared/Header/index.tsx

If branch name is greater than 21 characters, show ellipsis.

[td] Shorten branch name in the header

---

mage_ai/io/mysql.py
mage_integrations/mage_integrations/connections/sql/base.py
mage_integrations/mage_integrations/destinations/mysql/__init__.py
mage_integrations/mage_integrations/destinations/mysql/utils.py
mage_integrations/mage_integrations/sources/mysql/__init__.py
mage_integrations/mage_integrations/sources/sql/base.py

* Fix io MySQL inserting datetime
* Fix MySQL destination inserting DOUBLE
* Fix MySQL source comparing datetime column
* Use backtick to wrap column name in MySQL
tested locally
cc:

[xy] Fix MySQL column comparison and insert for datetime and double

---

mage_ai/server/websocket_server.py

- Replace hard-to-read dark blue font in code block output with much more legible yellow font.
Before:
After:

[jk] Improve code output font color

---

mage_integrations/mage_integrations/sources/mongodb/README.md
mage_integrations/mage_integrations/sources/mongodb/tap_mongodb/__init__.py

added authSource and authMechanism options for MongoDB tap
modified MongodDB tap README
lint
cc:

added authSource and authMechanism options for MongoDB tap

---

mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
mage_ai/frontend/components/Dashboard/utils.ts
mage_ai/frontend/components/PipelineRun/shared/utils.ts
mage_ai/frontend/components/shared/AddButton/index.tsx
mage_ai/frontend/components/shared/Table/Toolbar/constants.ts
mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
mage_ai/frontend/pages/index.tsx
mage_ai/frontend/pages/overview/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/orchestration/db/models/schedules.py

- For projects without any pipeline runs (i.e. new projects), redirect homepage to `/pipelines` page instead of `/overview` page.
- Add `New pipeline` button to `/overview` page.
- Handle "pipeline does not exist" error when fetching pipeline runs and pipeline run stats.
- Local

[jk] Overview page improvements

---

mage_ai/server/server.py

[jk] Add overview route

---

mage_ai/data_preparation/executors/ecs_block_executor.py
mage_ai/services/aws/ecs/ecs.py

Check ECS task status after running the task.
testing on ECS
cc:

[xy] Check ECS task status.

---

mage_ai/frontend/components/users/edit/Workspaces/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/settings/index.tsx

- Show error popup if error occurs when updating pipeline settings.

[jk] Display error on pipeline settings page

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx

Change the color of a custom block from the UI.

[td] Change the color of a block from the block UI

---

mage_ai/api/policies/PipelineRunPolicy.py
mage_ai/frontend/components/PipelineRun/Widget/index.tsx
mage_ai/frontend/pages/overview/index.tsx

- Update PipelineRunPolicy to include `pipeline_type` in `LIST` reads.
- Display pipeline run failure count in widget.

[jk] Overview fetch pipeline runs

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2773
- https://github.com/mage-ai/mage-ai/pull/2892
- https://github.com/mage-ai/mage-ai/pull/2884
- https://github.com/mage-ai/mage-ai/pull/2906
- https://github.com/mage-ai/mage-ai/pull/2909
- https://github.com/mage-ai/mage-ai/pull/2910
- https://github.com/mage-ai/mage-ai/pull/2911
- https://github.com/mage-ai/mage-ai/pull/2912
- https://github.com/mage-ai/mage-ai/pull/2901
- https://github.com/mage-ai/mage-ai/pull/2913
- https://github.com/mage-ai/mage-ai/pull/2920
- https://github.com/mage-ai/mage-ai/pull/2919
- https://github.com/mage-ai/mage-ai/pull/2921
- https://github.com/mage-ai/mage-ai/pull/2922
- https://github.com/mage-ai/mage-ai/pull/2924
- https://github.com/mage-ai/mage-ai/pull/2925
- https://github.com/mage-ai/mage-ai/pull/2926 …

[td] 0.8.104

---

mage_ai/data_preparation/executors/executor_factory.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/Settings/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/ExecutorType.ts
mage_ai/frontend/interfaces/PipelineType.ts

- Edit pipeline executor type
- Edit block executor type
- Use interpolation for executor type

[td] Edit pipeline and block executor type and interpolate

---

mage_ai/api/presenters/PipelinePresenter.py
mage_ai/api/resources/BlockResource.py
mage_ai/cache/block.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/components/PipelineDetail/Settings/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/settings/index.tsx
mage_ai/tests/data_preparation/models/test_pipeline.py

- Edit retry config for pipeline from the UI
- Edit retry config for block from the UI

[td] Edit pipeline and block retry config from the UI

---

mage_ai/cache/block.py
mage_ai/data_preparation/models/pipeline.py

Fix None cache key. Catch pipeline load_metadata error when initializing the cache.
tested locally
cc:

[xy] Fix None cache key.

---

mage_ai/io/trino.py

Fix inserting datetime column into trino. The io trino was inserting the Timestamp type into trino directly in value string, which caused errors.
Use the `executemany` method to insert multiple rows into Trino and handle data types correctly.
tested inserting int, str, datetime, dict and list into trino
cc:

[xy] Fix inserting datetime column into trino.

---

mage_ai/io/mssql.py

This PR fixes issue #2829.
Tested in local Mage setup with source as the [Titanic CSV](https://github.com/datasciencedojo/datasets/blob/master/titanic.csv) and destination as a table in SQL Server 2022.
CC: @gmestdacOLV @wangxiaoyou1993

Fix - Quotation marks added around strings for no apparent reason (2829)

---

mage_ai/orchestration/pipeline_scheduler.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

Change where we send the notification for pipeline run failure.
tested locally

[dy] Update where pipeline_run status is set

---

docs/guides/triggers/configure-triggers-in-code.mdx
mage_ai/api/policies/PipelineTriggerPolicy.py
mage_ai/api/presenters/PipelineTriggerPresenter.py
mage_ai/api/resources/PipelineTriggerResource.py
mage_ai/cache/block.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/triggers/__init__.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/Triggers/Table.tsx
mage_ai/frontend/interfaces/PipelineTriggerType.ts
mage_ai/frontend/oracle/elements/Circle.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_ai/server/server.py

Save trigger from UI to pipeline’s trigger.yaml file.

[td] Save trigger from UI to code

---

mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx

Edit the following from sidekick block settings
- Block name
- Block color

[td] Edit block name and color from block settings

---

mage_ai/api/policies/WorkspacePolicy.py
mage_ai/api/resources/PipelineScheduleResource.py
mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/frontend/components/users/edit/Form/index.tsx
mage_ai/frontend/components/users/edit/Workspaces/index.tsx
mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
mage_ai/frontend/components/workspaces/Dashboard/constants.ts
mage_ai/frontend/interfaces/UserType.ts
mage_ai/frontend/oracle/elements/Button/index.tsx
mage_ai/frontend/pages/manage/users/[user]/index.tsx
mage_ai/frontend/pages/settings/account/profile.tsx
mage_ai/frontend/pages/settings/workspace/users/index.tsx
mage_ai/frontend/utils/session.ts
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/orchestration/triggers/api.py
mage_ai/server/server.py
mage_ai/tests/orchestration/db/test_models.py

Fix bugs found in workspace bug bash: https://www.notion.so/mageai/Workspace-Bug-Bash-b30a8735554d4a6190f2cef6459994ef
tested locally
cc:

[dy] Workspace bug bash

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2933
- https://github.com/mage-ai/mage-ai/pull/2935
- https://github.com/mage-ai/mage-ai/pull/2937
- https://github.com/mage-ai/mage-ai/pull/2939
- https://github.com/mage-ai/mage-ai/pull/2941
- https://github.com/mage-ai/mage-ai/pull/2940
- https://github.com/mage-ai/mage-ai/pull/2897
- https://github.com/mage-ai/mage-ai/pull/2938
- https://github.com/mage-ai/mage-ai/pull/2942
- https://github.com/mage-ai/mage-ai/pull/2943
- https://github.com/mage-ai/mage-ai/pull/2944
- https://github.com/mage-ai/mage-ai/pull/2934
- https://github.com/mage-ai/mage-ai/pull/2949
- https://github.com/mage-ai/mage-ai/pull/2950
- https://github.com/mage-ai/mage-ai/pull/2951

[td] 0.9.0

---

mage_integrations/mage_integrations/destinations/postgresql/__init__.py

Escape reserved column name in postgres destination.
Error:
```
Exception: 2023-07-11T08:34:40 Error while executing query: syntax error at or near "create"
LINE 1: ...st_v2__test_export (col_num BIGINT, col_str TEXT, create TIM...
```
tested locally
cc:

[xy] Escape reserved column name in postgres destination.

---

mage_ai/orchestration/metrics/pipeline_run.py

Fix data integration metrics calculation.
tested locally
cc:

[xy] Fix data integration metrics calculation.

---

mage_ai/api/resources/WorkspaceResource.py
mage_ai/cluster_manager/aws/ecs_task_manager.py
mage_ai/services/aws/ecs/config.py
mage_ai/services/aws/ecs/ecs.py

* use network configuration from original service
* use cpu/memory from main task
tested on AWS ECS
cc:

[dy] ECS dev updates

---

docs/dbt/overview.mdx
docs/introduction/overview.mdx
docs/mint.json
docs/tutorials/examples.mdx

Via [this thread](https://mageai.slack.com/archives/C0548LJTD2S/p1688613568529069?thread_ts=1688053416.108069&cid=C0548LJTD2S), we'd like a place to share a curated list of community examples for implementation or solving problems. This PR does just that.
I'm open to adjusting formatting here, not sure if I'm happy with using titles as headers 🤔 
Locally, Mintlify:
cc:

[mp] collection of community examples

---

mage_ai/data_preparation/models/utils.py
mage_ai/data_preparation/models/variable.py

Improve variable serialization and deserialization. Only apply serialization and deserialization when the dataframe has list/dict columns. Remove unnecessary dataframe row level loop through and reduce memory consumption. Fix kernel crash due to out of memory.
tested locally
cc:

[xy] Improve variable serialization and deserialization.

---

mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/postgresql/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/sources/sql/base.py

Wrap Postgres schema with quote in creation command.
tested locally
cc:

[xy] Wrap Postgres schema with quote in creation command.

---

mage_ai/services/k8s/job_manager.py

Cath k8s job deletion error.
tested locally
cc:

[xy] Cath k8s job deletion error.

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/mssql.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/io/mssql.py
mage_ai/io/sql.py

I updated the serialization of mssql objects to be more like postgres. Objects will only be converted to json if the data type is a dictionary or list.
tested locally

[dy] Update serialization for mssql

---

docs/design/core-abstractions.mdx

Document the project file structure and the `mage_data` folder.
Locally, mintlify.

[mp] document project folder structure and `mage_data` folder.

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2970
- https://github.com/mage-ai/mage-ai/pull/2969
- https://github.com/mage-ai/mage-ai/pull/2968
- https://github.com/mage-ai/mage-ai/pull/2964
- https://github.com/mage-ai/mage-ai/pull/2958
- https://github.com/mage-ai/mage-ai/pull/2915
- https://github.com/mage-ai/mage-ai/pull/2965
- https://github.com/mage-ai/mage-ai/pull/2961
- https://github.com/mage-ai/mage-ai/pull/2960
- https://github.com/mage-ai/mage-ai/pull/2959
- https://github.com/mage-ai/mage-ai/pull/2957
- https://github.com/mage-ai/mage-ai/pull/2947
- https://github.com/mage-ai/mage-ai/pull/2954
- https://github.com/mage-ai/mage-ai/pull/2953

[td] 0.9.1

---

mage_ai/frontend/.eslintrc.js

[td] Add react-hooks/exhaustive-deps as an error for ESLint

---

mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/orchestration/queue/process_queue.py

Add docstring to some files.
n/a
cc:

[xy] Add docstring to some files.

---

mage_ai/frontend/components/Triggers/Edit/index.tsx

Cannot edit any fields without all fields resetting.

[td] Fix trigger edit

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/2974
- https://github.com/mage-ai/mage-ai/pull/2976
- https://github.com/mage-ai/mage-ai/pull/2978

[td] 0.9.2

---

mage_ai/streaming/sinks/amazon_s3.py

Add timer to upload data to s3 on timeout  in streaming pipeline.
tested locally
cc:

[xy] Add timer to upload data to s3 on timeout in streaming pipeline.

---

mage_integrations/mage_integrations/sources/postgresql/__init__.py

Escape schema in Postgres source in data integration pipeline
tested locally
cc:

[xy] Escape postgres source schema.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.3
* https://github.com/mage-ai/mage-ai/pull/2975
* https://github.com/mage-ai/mage-ai/pull/2936
* https://github.com/mage-ai/mage-ai/pull/2980
* https://github.com/mage-ai/mage-ai/pull/2981
* https://github.com/mage-ai/mage-ai/pull/2982
* https://github.com/mage-ai/mage-ai/pull/2984
* https://github.com/mage-ai/mage-ai/pull/2987
n/a
cc:

[xy] Bump version to 0.9.3

---

mage_ai/data_preparation/models/triggers/__init__.py
mage_ai/io/s3.py
mage_ai/shared/constants.py

* [Validate env values in trigger config.](https://github.com/mage-ai/mage-ai/commit/5faeba267391cbea85d3686733d7b932915884b5)
* [Use AWS session token in io.s3.](https://github.com/mage-ai/mage-ai/commit/93473a38ca6498e6a005bd5296c5f9e5dc16ed82)
tested locally
cc:

[xy] Some fixes and improvements

---

docs/production/configuring-production-settings/secrets.mdx
mage_ai/data_preparation/shared/utils.py
mage_ai/services/azure/key_vault/key_vault.py

Add azure_secret_var syntax.
`"{{ azure_secret_var('secret_name') }}"`
tested locally
cc:

[xy] Add azure_secret_var syntax.

---

mage_ai/frontend/components/PipelineRun/MetricsSummary/index.tsx

Fix overview crashing due to undefined error.
tested locally
cc:

[dy] Fix overview crashing

---

mage_ai/services/azure/container_instance/container_instance.py
mage_ai/services/azure/key_vault/key_vault.py
setup.py

* Add missing azure package to setup.py
* Delete azure container group after running the job
* Check valid AZURE_KEY_VAULT_URL environment variable before getting Azure secret
tested locally
cc:

[xy] Some fixes for Azure deployment

---

mage_ai/ai/constants.py
mage_ai/ai/gen_doc_for_pipeline.py
mage_ai/ai/generator.py
mage_ai/ai/llm_pipeline_wizard.py
mage_ai/api/policies/LlmPolicy.py
mage_ai/api/presenters/LlmPresenter.py
mage_ai/api/resources/LlmResource.py

Add API for LLM use cases.
tested locally
cc: @matrixstone

[xy] Add API for LLM use cases.

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/2990
* https://github.com/mage-ai/mage-ai/pull/2993
* https://github.com/mage-ai/mage-ai/pull/2994
* https://github.com/mage-ai/mage-ai/pull/2995
* https://github.com/mage-ai/mage-ai/pull/2996
* https://github.com/mage-ai/mage-ai/pull/3001
* https://github.com/mage-ai/mage-ai/pull/3002
* https://github.com/mage-ai/mage-ai/pull/3003
cc:

[dy] Bump to 0.9.4

---

mage_integrations/requirements.txt

https://github.com/pymssql/pymssql/issues/826
tested locally

[dy] Temporary pymssql fix

---

mage_integrations/requirements.txt

Revert "[dy] Temporary pymssql fix"

---

.github/workflows/build_and_test.yml
mage_integrations/requirements.txt

[dy] Temporary pymssql fix v2

---

mage_ai/api/presenters/GitCustomBranchPresenter.py
mage_ai/api/resources/GitBranchResource.py
mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
mage_ai/frontend/components/VersionControl/index.tsx
mage_ai/frontend/components/shared/Header/index.tsx

The header is fetching a branch and getting too many files; it slows the entire app.

[td] Don’t try to fetch all the modified and unstaged files when fetching current branch in the header

---

mage_ai/data_integrations/utils/scheduler.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/metrics/pipeline_run.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/orchestration/queue/config.py
mage_ai/orchestration/queue/process_queue.py
mage_ai/orchestration/utils/distributed_lock.py
mage_ai/settings/__init__.py
requirements.txt

Improve pipeline scheduler and support distributed process queue
* Configure REDIS_URL env variable
* Use Redis to coordinate the job scheduling
* Use Redis to implement distributed lock
tested locally
cc:

[xy] Improve pipeline scheduler and support distributed process queue

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/3026
- https://github.com/mage-ai/mage-ai/pull/3024
- https://github.com/mage-ai/mage-ai/pull/3020
- https://github.com/mage-ai/mage-ai/pull/3000
- https://github.com/mage-ai/mage-ai/pull/3011
- https://github.com/mage-ai/mage-ai/pull/3013
- https://github.com/mage-ai/mage-ai/pull/3015

[td] 0.9.5

---

mage_ai/frontend/interfaces/ErrorsType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Fix issue: Error message would appear but immediately close when running into an error viewing and selecting streams.

[jk] Persist error message popup when selecting stream

---

mage_ai/data_integrations/utils/scheduler.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/metrics/pipeline_run.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/orchestration/queue/config.py
mage_ai/orchestration/queue/process_queue.py
mage_ai/orchestration/utils/distributed_lock.py
mage_ai/settings/__init__.py
requirements.txt

Reverts mage-ai/mage-ai#3026
* Fix duplicate integration block run issue

Revert "Revert "[xy] Improve pipeline scheduler and support distributed process queue""

---

mage_ai/io/bigquery.py

Specify oauth2 scopes in Google BigQuery client to enable pulling from tables imported via Google Drive.
- [Scopes reference](https://developers.google.com/identity/protocols/oauth2/scopes)
- [dbt article](https://docs.getdbt.com/faqs/troubleshooting/access-gdrive-credential) with solution
- [Similar solution](https://stackoverflow.com/questions/53320537/creating-google-api-credentials-from-service-account-with-scope-and-delegated-a)
This closes https://github.com/mage-ai/mage-ai/issues/3022
Locally with Mage Client.

[mp] add google oauth2 scopes to bigquery client

---

mage_ai/orchestration/notification/sender.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/shared/dates.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

Fix SLA alert triggering as soon as the pipeline run starts even if it didn't miss SLA.
local testing and unit test
cc:

[dy] Fix SLA bug

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/orchestration/queue/process_queue.py
mage_ai/orchestration/utils/distributed_lock.py
mage_ai/services/redis/redis.py

Catch redis initialization error and fix logging.
tested locally
cc:

[xy] Catch redis error and fix logging.

---

mage_ai/api/resources/RoleResource.py

Fix roles query.
tested locally
cc:

[dy] Fix roles query by entity bug

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3028
* https://github.com/mage-ai/mage-ai/pull/3023
* https://github.com/mage-ai/mage-ai/pull/3034
* https://github.com/mage-ai/mage-ai/pull/3036
* https://github.com/mage-ai/mage-ai/pull/3038
* https://github.com/mage-ai/mage-ai/pull/3039
* https://github.com/mage-ai/mage-ai/pull/3041
* https://github.com/mage-ai/mage-ai/pull/3035
* https://github.com/mage-ai/mage-ai/pull/3021
* https://github.com/mage-ai/mage-ai/pull/3047
* https://github.com/mage-ai/mage-ai/pull/3049
n/a
cc:

[xy] Bump version to 0.9.6

---

.github/release.yml

Update our releases auto-formatting to correspond to new labels :)

Update `releases.yml` to account for new tags: `feature` & `enhancement`

---

mage_ai/api/policies/LlmPolicy.py
mage_ai/api/presenters/GitCustomBranchPresenter.py
mage_ai/api/resources/GitBranchResource.py
mage_ai/data_preparation/git/__init__.py

Added a 10 second timeout for fetching untracked and staged files. The modified files call is a bit trickier to add a timeout for, but I think the main issue is the untracked files anyway.
tested locally
cc:

[dy] Add timeout for fetching files for git

---

mage_ai/ai/gen_doc_for_pipeline.py
mage_ai/ai/generator.py
mage_ai/ai/llm_pipeline_wizard.py
mage_ai/api/resources/LlmResource.py

Make LLM endpoint async
tested locally
cc:

[xy] Make LLM endpoint async

---

mage_ai/api/policies/PipelineTriggerPolicy.py
mage_ai/api/resources/CustomTemplateResource.py
mage_ai/data_preparation/models/custom_templates/custom_pipeline_template.py
mage_ai/frontend/components/CustomTemplates/PipelineTemplateDetail/constants.ts
mage_ai/frontend/components/CustomTemplates/PipelineTemplateDetail/index.tsx

- Created class for custom pipeline template
- Fix lint and type errors in build jobs so that accident master merge is not broken

[td] Created custom pipeline template class and fix build issues

---

mage_ai/api/presenters/CustomTemplatePresenter.py
mage_ai/data_preparation/models/custom_templates/custom_pipeline_template.py
mage_ai/frontend/components/CustomTemplates/BrowseTemplates/index.style.tsx
mage_ai/frontend/components/CustomTemplates/BrowseTemplates/index.tsx
mage_ai/frontend/components/CustomTemplates/PipelineTemplateDetail/constants.ts
mage_ai/frontend/components/CustomTemplates/PipelineTemplateDetail/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/interfaces/CustomTemplateType.ts

Add tree graph to detail page.

[td] Added tree to pipeline template detail page

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/3050
- https://github.com/mage-ai/mage-ai/pull/3052
- https://github.com/mage-ai/mage-ai/pull/3051
- https://github.com/mage-ai/mage-ai/pull/3043
- https://github.com/mage-ai/mage-ai/pull/3055
- https://github.com/mage-ai/mage-ai/pull/3042
- https://github.com/mage-ai/mage-ai/pull/3058
- https://github.com/mage-ai/mage-ai/pull/3059
- https://github.com/mage-ai/mage-ai/pull/3064

[td] 0.9.7

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/3068
- https://github.com/mage-ai/mage-ai/pull/3067

[td] 0.9.8

---

docs/production/deploying-to-cloud/architecture.mdx

Add doc for scale web server and schedulers.
n/a
cc:

[xy] Add doc for scale web server and schedulers.

---

mage_ai/api/policies/SearchResultPolicy.py
mage_ai/api/presenters/SearchResultPresenter.py
mage_ai/api/resources/BlockResource.py
mage_ai/api/resources/CustomTemplateResource.py
mage_ai/api/resources/FileContentResource.py
mage_ai/api/resources/FileResource.py
mage_ai/api/resources/SearchResultResource.py
mage_ai/cache/base.py
mage_ai/cache/block_action_object/__init__.py
mage_ai/cache/block_action_object/constants.py
mage_ai/cache/constants.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/custom_templates/custom_block_template.py
mage_ai/data_preparation/models/file.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/FileBrowser/NewFile/index.tsx
mage_ai/frontend/components/FileBrowser/NewFolder/index.tsx
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/server/server.py
mage_ai/services/search/block_action_objects.py
mage_ai/services/search/constants.py
requirements.txt
setup.py

- Created cache object to store Mage templates, custom block templates, and block files
- Added Search Results API endpoint to retrieve block action objects based on user search query

[td] Created cache for block action objects and search service

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/package.json
mage_ai/frontend/yarn.lock

Render text/html output types.
tested locally with pygwalker
cc:

[dy] Render text/html from block output

---

mage_ai/ai/llm_pipeline_wizard.py
mage_ai/data_preparation/models/custom_templates/utils.py

Fix NoneType error from custom templates.
tested locally
cc:

[xy] Fix NoneType error from custom templates.

---

mage_ai/api/policies/BlockPolicy.py
mage_ai/api/resources/BlockResource.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CustomTemplates/BrowseTemplates/constants.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.style.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/BlockActionObjectType.ts
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/SearchResultType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

[td] Add new block flow 2.0

---

docs/mint.json

[td] Fix CI/CD docs in left navigation

---

mage_ai/shared/parsers.py
mage_ai/tests/shared/test_parsers.py

Support nested sampling on output.
unit test
tested locally
cc:

[xy] Support nested sampling on output.

---

docs/api-reference/oauth-access-tokens/overview.mdx
docs/api-reference/oauth-access-tokens/read-oauth-access-tokens.mdx
docs/mint.json
mage_ai/api/policies/OauthAccessTokenPolicy.py
mage_ai/api/presenters/OauthAccessTokenPresenter.py
mage_ai/api/resources/OauthAccessTokenResource.py

- Fetch active/expired access tokens for a user or all users

[td] Add API endpoint for fetching OAuth access tokens

---

mage_ai/data_preparation/executors/k8s_pipeline_executor.py

Fix command for running streaming pipeline in k8s executor.
tested locally
cc:

[xy] Fix command for running streaming pipeline in k8s executor.

---

mage_ai/api/policies/SearchResultPolicy.py
mage_ai/api/presenters/BlockTemplatePresenter.py
mage_ai/api/resources/BlockResource.py
mage_ai/api/resources/SearchResultResource.py
mage_ai/data_preparation/templates/constants.py
mage_ai/data_preparation/templates/template.py
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.style.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/BlockTemplateType.ts
mage_ai/frontend/oracle/elements/KeyboardTextGroup.tsx
mage_ai/frontend/utils/hooks/keyboardShortcuts/constants.ts

[td] Add new block flow 2.0 bug bash

---

mage_ai/api/resources/VariableResource.py

[jk] Clean up code in VariableResource method

---

mage_ai/data_integrations/destinations/constants.py
mage_integrations/mage_integrations/destinations/mongodb/README.md
mage_integrations/mage_integrations/destinations/mongodb/__init__.py
mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/sinks.py
mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/target.py
mage_integrations/mage_integrations/destinations/mongodb/templates/config.json

Adding mongoDB as destination for data integration pipelines
Tested with postgreSQL source on MongoDB destination
Both FULL_TABLE and INCREMENTAL were tested, sync example:
MongoDB data example:
MongoDB document example:
Array example:
Object example:
PostgreSQL schema:
cc:

adding mongodb as destination ( data integration )

---

mage_ai/ai/llm_pipeline_wizard.py

Update response format for generate_block_with_description.
Example response:
tested locally
cc:

[xy] Update response format for generate_block_with_description.

---

mage_ai/ai/llm_pipeline_wizard.py
mage_ai/api/policies/PipelinePolicy.py
mage_ai/api/resources/PipelineResource.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/interfaces/LLMType.ts
mage_ai/shared/array.py

- Document block
- Document pipeline and all blocks

[td] Generate documentation using AI

---

mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx

[td] Add text on buttons when adding new blocks

---

mage_ai/api/policies/ProjectPolicy.py
mage_ai/api/presenters/ProjectPresenter.py
mage_ai/api/resources/ProjectResource.py
mage_ai/data_preparation/models/project/__init__.py
mage_ai/data_preparation/models/project/constants.py
mage_ai/data_preparation/repo_manager.py
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/usage_statistics/constants.py
mage_ai/usage_statistics/logger.py

- Turn on or off features
- Log usage stats for features

[td] Feature flags

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/3005
- https://github.com/mage-ai/mage-ai/pull/3029
- https://github.com/mage-ai/mage-ai/pull/3074
- https://github.com/mage-ai/mage-ai/pull/3077
- https://github.com/mage-ai/mage-ai/pull/3070
- https://github.com/mage-ai/mage-ai/pull/3076
- https://github.com/mage-ai/mage-ai/pull/3080
- https://github.com/mage-ai/mage-ai/pull/3083
- https://github.com/mage-ai/mage-ai/pull/3079
- https://github.com/mage-ai/mage-ai/pull/3081
- https://github.com/mage-ai/mage-ai/pull/3086
- https://github.com/mage-ai/mage-ai/pull/3087
- https://github.com/mage-ai/mage-ai/pull/3089
- https://github.com/mage-ai/mage-ai/pull/3090
- https://github.com/mage-ai/mage-ai/pull/3092
- https://github.com/mage-ai/mage-ai/pull/3093
- https://github.com/mage-ai/mage-ai/pull/3094 …

[td] 0.9.9

---

docs/mint.json

[td] Add API docs for getting OAuth access tokens.

---

mage_ai/data_preparation/models/triggers/__init__.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py

- Schedule pipeline runs and start it based on landing times

[td] Pipeline landing times

---

docs/design/data-loading.mdx

Adds OracleDB config to data loader docs.

[mp] add oracledb source to data loader docs

---

docs/design/core-abstractions.mdx
docs/pipelines/pipeline-tagging.mdx

Docs that walkthrough the basics of pipeline tagging, re: [this Story](https://airtable.com/applEuqJsK4zF5yJK/tbl5bIlFkk2KhCpL4/viwmMwX4PDtsuaQ7W/recq50Kp0Hg6uPNQV?blocks=show&bip=full).
Mintlify
cc:

[mp] pipeline tagging documentation

---

Dockerfile
dev.Dockerfile
mage_ai/data_preparation/models/pipelines/integration_pipeline.py
mage_ai/io/mssql.py
mage_ai/shared/security.py
mage_integrations/requirements.txt
scripts/dev.sh

Install pymssql 2.2.7 but force it to use a certain verison of Cython. This should fix the build issue while also using the same version of pymssql that was working for us before.
tested build locally and the mssql data integration

[dy] Fix pymssql dependency

---

mage_ai/api/presenters/PipelinePresenter.py
mage_ai/api/resources/PipelineRunResource.py
mage_ai/api/resources/ProjectResource.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/project/__init__.py
mage_ai/orchestration/backfills/service.py
mage_ai/orchestration/concurrency.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/tests/data_preparation/models/test_pipeline.py
mage_ai/usage_statistics/constants.py
mage_ai/usage_statistics/logger.py

Support pipeline level concurrency.
```yaml
concurrency_config:
block_run_limit: 1
pipeline_run_limit: 1
```
tested locally
cc:

[xy] Support pipeline level concurrency.

---

mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx

[jk] Fix positioning of nested flyout menu 4 levels deep

---

mage_ai/orchestration/db/models/schedules.py

Address comments from: https://github.com/mage-ai/mage-ai/pull/3109

[td] Address PR comments for landing times

---

mage_ai/server/websocket_server.py

Update format of docstring to match other comments
cc:

[dy] Update docstring

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.style.tsx
mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
mage_ai/frontend/components/Sidekick/index.style.ts
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/oracle/components/Badge/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx

- Make `Updated at` column font size more consistent with font size of rest of Pipelines table.
- Improve styling of "Execute pipeline" buttons in Pipeline Editor for streaming pipelines.
- Remove gap at bottom of dependency graph in Pipeline Editor Sidekick.
- Improve formatting and hide code block header items on smaller widths.
- Local

[jk] Misc UI improvements

---

mage_ai/api/policies/GlobalDataProductPolicy.py
mage_ai/api/presenters/GlobalDataProductPresenter.py
mage_ai/api/resources/GlobalDataProductResource.py
mage_ai/data_preparation/models/global_data_product.py

A global data product will represent a block or a pipeline as a single unit that can be used in any pipeline.

[td] Create model and API endpoint for global data products

---

mage_ai/api/presenters/GlobalDataProductPresenter.py
mage_ai/api/resources/GlobalDataProductResource.py
mage_ai/data_cleaner/transformer_actions/helpers.py
mage_ai/data_preparation/models/global_data_product.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/CustomTemplates/TemplateDetail/index.style.tsx
mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
mage_ai/frontend/components/GlobalDataProductDetail/index.tsx
mage_ai/frontend/components/GlobalDataProducts/index.tsx
mage_ai/frontend/interfaces/GlobalDataProductType.ts
mage_ai/frontend/pages/global-data-products/[...slug].tsx
mage_ai/frontend/pages/global-data-products/index.tsx
mage_ai/io/postgres.py
mage_ai/io/trino.py
mage_ai/server/server.py
mage_ai/shared/hash.py

[td] Global data product list and detail page

---

docs/production/observability/logging.mdx
mage_ai/data_cleaner/transformer_actions/helpers.py
mage_ai/data_preparation/logging/s3_logger_manager.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/models/global_data_product.py
mage_ai/io/postgres.py
mage_ai/services/aws/s3/s3.py
mage_ai/tests/orchestration/db/test_models.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/utils.py

Allow custom endpoint_url in s3 logger.
```yaml
logging_config:
type: s3
level: INFO
destination_config:
bucket: <bucket name>
prefix: <prefix path>
aws_access_key_id: <(optional) AWS access key ID>
aws_secret_access_key: <(optional) AWS secret access key>
endpoint_url: <(optional) custom endpoint url>
```
tested locally
cc:

[xy] Allow custom endpoint_url in s3 logger.

---

mage_ai/cli/main.py
mage_ai/data_preparation/logging/__init__.py
mage_ai/data_preparation/logging/gcs_logger_manager.py
mage_ai/data_preparation/logging/logger_manager.py
mage_ai/data_preparation/logging/s3_logger_manager.py
mage_ai/data_preparation/repo_manager.py
mage_ai/tests/base_test.py
mage_ai/tests/data_preparation/logging/test_logger_manager.py

Delete logs after log retention period.
Example logging config:
```
logging_config:
retention_period: '15d'
```
Example usage:
```
mage clean-old-logs k8s_project
```
tested locally
unit tests
cc:

[xy] Delete logs after log retention period.

---

mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/frontend/pages/settings/workspace/users/index.tsx
mage_ai/orchestration/triggers/api.py
mage_ai/server/server.py

For sql blocks, we try to interpolate the query even if there are no interpolated variables in the block. I added a regex to check if there is the `{{ df_X }}` syntax in the query before trying to interpolate variables.
I also removed the git sync from api triggers because it can potentially cause issues.
tested locally

[dy] Only try to interpolate variables if they are in the query

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3111
* https://github.com/mage-ai/mage-ai/pull/3109
* https://github.com/mage-ai/mage-ai/pull/3032
* https://github.com/mage-ai/mage-ai/pull/3019
* https://github.com/mage-ai/mage-ai/pull/3072
* https://github.com/mage-ai/mage-ai/pull/3114
* https://github.com/mage-ai/mage-ai/pull/3112
* https://github.com/mage-ai/mage-ai/pull/3119
* https://github.com/mage-ai/mage-ai/pull/3115
* https://github.com/mage-ai/mage-ai/pull/3120
* https://github.com/mage-ai/mage-ai/pull/3118
* https://github.com/mage-ai/mage-ai/pull/3125
* https://github.com/mage-ai/mage-ai/pull/3128
* https://github.com/mage-ai/mage-ai/pull/3129
* https://github.com/mage-ai/mage-ai/pull/3130
* https://github.com/mage-ai/mage-ai/pull/3110
* https://github.com/mage-ai/mage-ai/pull/3131 …

[xy] Bump version to 0.9.10.

---

docs/design/data-pipeline-management.mdx
docs/production/configuring-production-settings/compute-resource.mdx
docs/production/observability/logging.mdx

* Add doc for pipeline level concurrency.
* Add doc for customizing k8s executor config.
* Add doc for log retention period.
n/a
cc:

[xy] Add docs for new features

---

docs/development/troubleshooting.mdx

Provide brief documentation for [this error](https://mageai.slack.com/archives/C03HTTWFEKE/p1690818264305139), as suggested by one of our users. Also added the term "frequently asked questions" to troubleshooting to help with search.
Mintlify local
cc:

[mp] document `invalidtoken` error

---

mage_integrations/mage_integrations/destinations/mongodb/__init__.py
mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/target.py

Adding test connection to MongoDB destination
Added new process function
Updated logs on Target file
Tested on a local mage instance
Successful test connection:
DB not found connection:
Timed out connection ( wrong connection url):
cc:

Adding test connection to MongoDB destination

---

mage_ai/frontend/components/Logs/Table/index.tsx
mage_ai/frontend/components/Logs/Toolbar/index.tsx
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/frontend/oracle/elements/Divider/index.tsx
mage_ai/frontend/oracle/elements/Inputs/ToggleSwitch.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/frontend/storage/constants.ts

- Add setting on logs page for automatically scrolling to newest log on bottom of logs table.
- Add button for scrolling to bottom of logs table.

[jk] Auto-scroll to newest logs

---

MANIFEST.in
mage_ai/server/server.py

Needed for supporting a prefix in the Mage url.
cc:

[dy] Include frontend_dist_base_path_template in package

---

docs/development/troubleshooting.mdx

Add a common question about rendering Mage locally to documentation.

[mp] add documentation on local hosting w/ different port

---

mage_ai/server/server.py
mage_ai/tests/server/test_server.py

The frontend_dist folder was not being created properly.
tested locally and on k8s
cc:

[dy] Fix base path frontend_dist creation

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/shared/utils.py
mage_ai/orchestration/db/utils.py
mage_ai/tests/data_preparation/test_repo_manager.py

Fixes https://mageai.slack.com/archives/C03HTTWFEKE/p1690993959608629
This PR does a couple of things:
1. Removes `pipeline.py` dependency on `db_connection`.
2. Initializes all the `RepoConfig` variables so that if there is an issue rendering the yaml file, it doesn't cause the entire app to crash.
3. Populate project_uuid directly from the `metadata.yaml` file instead of through the RepoConfig.
tested locally

[dy] Fix circular dependency and repo config issues

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/tests/data_preparation/models/block/test_sql.py

Support drop table command in raw sql.
tested locally
unit tests
cc:

[xy] Support drop table command in raw sql.

---

.gitignore

Add `frontend_dist_base_path` to Mage gitignore
cc:

[dy] Update gitignore

---

docs/production/deploying-to-cloud/aws-without-terraform.mdx

Updates Docker templates to point at most recent version in github. Fixes broken markdown formatting for a few tables.
Mintlify!

[mp] fix table formatting and update template

---

mage_ai/streaming/sinks/amazon_s3.py

Remove streaming pipeline s3 sink timer error.
tested locally
cc:

[xy] Remove streaming s3 sink timer error.

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3134
* https://github.com/mage-ai/mage-ai/pull/3148
* https://github.com/mage-ai/mage-ai/pull/3103
* https://github.com/mage-ai/mage-ai/pull/2772
* https://github.com/mage-ai/mage-ai/pull/3101
* https://github.com/mage-ai/mage-ai/pull/3150
* https://github.com/mage-ai/mage-ai/pull/3151
* https://github.com/mage-ai/mage-ai/pull/3156
* https://github.com/mage-ai/mage-ai/pull/3163
* https://github.com/mage-ai/mage-ai/pull/3164
* https://github.com/mage-ai/mage-ai/pull/3159
* https://github.com/mage-ai/mage-ai/pull/3075
* https://github.com/mage-ai/mage-ai/pull/3141
* https://github.com/mage-ai/mage-ai/pull/3170
* https://github.com/mage-ai/mage-ai/pull/3171
* https://github.com/mage-ai/mage-ai/pull/3178
* https://github.com/mage-ai/mage-ai/pull/3174 …

[xy] Bump version to 0.9.11

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/server/websocket_server.py

Support replica blocks for new block execution method. Also changed the except message to sound less like an error.
tested locally
cc:

[dy] Fix error logging for replica blocks

---

mage_integrations/mage_integrations/destinations/clickhouse/__init__.py

Adding State file location to clickhouse destination
Tested on a local mage instance:
cc:

Added clickhouse state file location

---

mage_ai/ai/constants.py
mage_ai/ai/generator.py
mage_ai/ai/generator_cmds.py
mage_ai/ai/llm_pipeline_wizard.py

Generate comment for each function inside the code.
The newly generated comment will be added as a doc string beneath function definition.
Also it can merge into existing doc string if there is error.
Current issues are (1) the output code is not well formatted (2) # comment misses
Command to run the code:
`python mage_ai/ai/generator_cmds.py generate-comment-for-block code_file`
code_file is the file contains the code to generate comment for.
Reviewer:

[xh]Generate comment for code

---

mage_ai/data_preparation/models/block/extension/block.py
mage_ai/data_preparation/models/block/global_data_product/__init__.py
mage_ai/data_preparation/models/global_data_product/__init__.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/triggers/global_data_product.py
mage_ai/orchestration/triggers/utils.py
mage_ai/tests/data_preparation/models/block/test_global_data_product.py
mage_ai/tests/data_preparation/models/test_global_data_product.py
mage_ai/tests/orchestration/triggers/test_global_data_product.py
mage_ai/tests/orchestration/triggers/test_utils.py

- GDP class
- GDP block
- GDP trigger
- Trigger utils

[td] Add unit tests for all global data product classes, methods, and functions

---

mage_ai/server/constants.py
setup.py

Primarily bug fixes
*  https://github.com/mage-ai/mage-ai/pull/3200
* https://github.com/mage-ai/mage-ai/pull/3201
* https://github.com/mage-ai/mage-ai/pull/3203
* https://github.com/mage-ai/mage-ai/pull/3205
cc:

[dy] Bump to 0.9.12

---

mage_ai/data_preparation/models/block/dbt/utils/__init__.py

Support the following config in dbt SQL model:
```
{{ config(database='some-project-id') }}
```

[td] Support dbt model config option for database

---

mage_ai/api/resources/GlobalDataProductResource.py
mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
mage_ai/frontend/components/GlobalDataProductDetail/index.tsx
mage_ai/frontend/components/GlobalDataProducts/index.tsx
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/pages/global-data-products/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/frontend/pages/templates.tsx

Show GDP in the UI:
- Right click pipeline row on pipeline list page
- Show GDP as a nav link in dashboard

[td] Add global data products to the UI

---

mage_ai/frontend/components/Dashboard/utils.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/oracle/icons/custom/StreamingPipeline.tsx

[td] Add custom block template for streaming pipeline

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Add new pull request template.
n/a
cc:

[xy] Add new pull request template.

---

mage_ai/streaming/constants.py
mage_ai/streaming/sources/kafka.py

Adds a configurable `timeout_ms` parameter to kafka streaming pipelines

[mp] add custom timeout to kafka streams

---

mage_ai/io/redshift.py
mage_ai/io/utils.py

Update format value so that it escapes the resulting string.
tested locally

[dy] Update redshift format value

---

mage_ai/server/server.py
mage_ai/tests/server/test_server.py

I updated where the `frontend_dist_base_path` folder is created because it's possible that Mage won't have permission to edit the folder where the Mage package is installed. I chose to use the `get_variables_dir()` directory since I wasn't really sure where else to put it.
I also changed the `print` statements in the `server.py` file to `logger.info` since the print statements don't show up in server logs outside of the dev environment.
- [] I have made corresponding changes to the documentation

[dy] Update where the `frontend_dist_base_path` is created

---

mage_ai/api/resources/SearchResultResource.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/global_data_product/__init__.py
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/orchestration/triggers/global_data_product.py
mage_ai/orchestration/triggers/utils.py
mage_ai/server/server.py

Fix bugs reported in the bug bash doc: https://www.notion.so/mageai/Bug-Bash-Global-data-products-9734c15d4db249ea869d36c90867a4b7?pvs=4
cc:

[td] Bug bash for global data products

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/3208
- https://github.com/mage-ai/mage-ai/pull/3206
- https://github.com/mage-ai/mage-ai/pull/3209
- https://github.com/mage-ai/mage-ai/pull/3210
- https://github.com/mage-ai/mage-ai/pull/3199
- https://github.com/mage-ai/mage-ai/pull/3213
- https://github.com/mage-ai/mage-ai/pull/3216
- https://github.com/mage-ai/mage-ai/pull/3211
- https://github.com/mage-ai/mage-ai/pull/3220
- https://github.com/mage-ai/mage-ai/pull/3219
- https://github.com/mage-ai/mage-ai/pull/3221
- https://github.com/mage-ai/mage-ai/pull/3222
- https://github.com/mage-ai/mage-ai/pull/3204
- https://github.com/mage-ai/mage-ai/pull/3225
- https://github.com/mage-ai/mage-ai/pull/3196
- https://github.com/mage-ai/mage-ai/pull/3226
- https://github.com/mage-ai/mage-ai/pull/3194 …

[td] 0.9.13

---

mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
mage_ai/frontend/oracle/elements/Text/index.tsx

- Make minor styling and formatting updates to the BlockRuns table so it's styling is consistent with the PipelineRuns table.

[jk] Update block runs table

---

Dockerfile
dev.Dockerfile

Resolves: #3248
Groupes and Reorders Docker Statements for better build performance
- lower number of layers (smaller build)
- often changing things last

Docker: Optimize build by reordering and grouping some statements

---

Dockerfile
dev.Dockerfile

Reverts mage-ai/mage-ai#3258 due to version not found issues.

Revert "Docker: Optimize build by reordering and grouping some statements"

---

mage_ai/api/presenters/BlockRunPresenter.py
mage_ai/api/resources/BlockRunResource.py

The `pipeline_schedule_name` property was not being returned correctly by the server. I updated the `BlockRunResource` to include it in the response.

[dy] Fix trigger not showing up in block run view

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.14.
* https://github.com/mage-ai/mage-ai/pull/3214
* https://github.com/mage-ai/mage-ai/pull/3253
* https://github.com/mage-ai/mage-ai/pull/3254
* https://github.com/mage-ai/mage-ai/pull/3236
* https://github.com/mage-ai/mage-ai/pull/3256
* https://github.com/mage-ai/mage-ai/pull/3257
* https://github.com/mage-ai/mage-ai/pull/3169
* https://github.com/mage-ai/mage-ai/pull/3265
* https://github.com/mage-ai/mage-ai/pull/3268
* https://github.com/mage-ai/mage-ai/pull/3264
* https://github.com/mage-ai/mage-ai/pull/3243
* https://github.com/mage-ai/mage-ai/pull/3245
* https://github.com/mage-ai/mage-ai/pull/3273
* https://github.com/mage-ai/mage-ai/pull/3274
* https://github.com/mage-ai/mage-ai/pull/3276
N/A
cc:

[xy] Bump version to 0.9.14.

---

docs/integrations/databases/MicrosoftSQLServer.mdx
mage_ai/data_preparation/templates/constants.py
mage_ai/data_preparation/templates/data_exporters/mssql.py
mage_ai/data_preparation/templates/data_loaders/mssql.py
mage_ai/io/mssql.py

Add block templates for MSSQL. It includes the block template for data loader and data exporter.
This PR also fixes an issue of inserting nan to MSSQL.
cc:

[xy] Add block templates for MSSQL.

---

docs/guides/schedule-pipelines.mdx
docs/mint.json
mage_ai/frontend/components/Triggers/Edit/index.tsx

[td] Add docs for landing times

---

mage_integrations/mage_integrations/destinations/clickhouse/README.md
mage_integrations/mage_integrations/destinations/clickhouse/target_clickhouse/sinks.py
mage_integrations/mage_integrations/destinations/clickhouse/target_clickhouse/target.py
mage_integrations/mage_integrations/destinations/clickhouse/templates/config.json

Updated Clickhouse destination version
Added table_name to configuration
Perfomance improvements
Tested using local mage version
Full table test:
Incremental tests:
cc:

Updated clickhouse destination

---

docs/mint.json
docs/orchestration/global-data-products/overview.mdx

[td] Add global data product docs

---

docs/api-reference/pipeline-schedules/overview.mdx
docs/api-reference/pipeline-schedules/read-pipeline-schedules.mdx
docs/mint.json

[td] Add tags to pipeline schedule API docs

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3294
* https://github.com/mage-ai/mage-ai/pull/3300
* https://github.com/mage-ai/mage-ai/pull/3302
* https://github.com/mage-ai/mage-ai/pull/3279
* https://github.com/mage-ai/mage-ai/pull/3283
* https://github.com/mage-ai/mage-ai/pull/3285
* https://github.com/mage-ai/mage-ai/pull/3286
* https://github.com/mage-ai/mage-ai/pull/3234
cc:

[dy] Bump 0.9.15

---

docs/custom-templates/overview.mdx
docs/guides/streaming-pipeline.mdx
docs/guides/streaming/streaming-pipeline-rabbitmq.mdx
docs/mint.json

[td] Docs for custom templates

---

docs/developing-in-the-cloud/setting-up-git.mdx
docs/mint.json
docs/production/data-sync/github.mdx

[td] Docs and videos for version control

---

requirements.txt
setup.py

Added oracledb lib to mage-ai requirements.txt
Tested mage-ai build
cc:

Adding oracledb lib to mage-ai

---

mage_ai/tests/data_preparation/executors/test_pipeline_executor.py

Comment out flaky test of pipeline execution. Will fix the test later. https://github.com/mage-ai/mage-ai/actions/runs/5929313969/job/16076730729
cc:

[xy] Comment out flaky test of pipeline execution

---

docs/integrations/databricks.mdx

Fixed one broken link for a section title, added a sequence number for a section, and changed raw URL with the linked web page title.
cc:

[hw] Update the user docs for Databricks with some refinements

---

mage_integrations/mage_integrations/sources/google_ads/__init__.py

Added test_connection to google ads source integration
Tested on a local mage instance
- 
cc:

Added test connection to google_ads source

---

mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/salesforce/__init__.py
mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/target.py

Removed `is_sandbox` config
Tested on a local mage instance
cc:

Removed unused config in Salesforce destination

---

docs/contributing/code-of-conduct.mdx
docs/contributing/testing.mdx
docs/mint.json

This PR adds a code of conduct borrowed from the [Contributor Covenant](https://www.contributor-covenant.org/), a widely adopted framework for guiding contributions to Open Source communities. 
cc:

[mp] contributor covenant

---

mage_ai/data_preparation/shared/secrets.py
mage_ai/tests/data_preparation/shared/test_secrets.py

* Add safe_db_query to some secrets methods
* Update how we fetch secrets for `get_secret_value` to handle legacy secrets better

[dy] Fix secrets bugs

---

docs/contributing/code-of-conduct.mdx

Correct typo in code of conduct

[mp] code of conduct hotfix

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.16
* https://github.com/mage-ai/mage-ai/pull/3246
* https://github.com/mage-ai/mage-ai/pull/3310
* https://github.com/mage-ai/mage-ai/pull/3289
* https://github.com/mage-ai/mage-ai/pull/3311
* https://github.com/mage-ai/mage-ai/pull/3315
* https://github.com/mage-ai/mage-ai/pull/3313
* https://github.com/mage-ai/mage-ai/pull/3317
* https://github.com/mage-ai/mage-ai/pull/3316
* https://github.com/mage-ai/mage-ai/pull/3319
* https://github.com/mage-ai/mage-ai/pull/3280
* https://github.com/mage-ai/mage-ai/pull/3322
* https://github.com/mage-ai/mage-ai/pull/3301
* https://github.com/mage-ai/mage-ai/pull/3287
* https://github.com/mage-ai/mage-ai/pull/3325
* https://github.com/mage-ai/mage-ai/pull/3326
* https://github.com/mage-ai/mage-ai/pull/3309
* …

[xy] Bump version to 0.9.16

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/data_preparation/models/block/sql/clickhouse.py
mage_ai/data_preparation/models/block/sql/mssql.py
mage_ai/data_preparation/models/block/sql/mysql.py
mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/data_preparation/models/block/sql/redshift.py
mage_ai/data_preparation/models/block/sql/snowflake.py
mage_ai/data_preparation/models/block/sql/spark.py
mage_ai/data_preparation/models/block/sql/trino.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/data_preparation/models/pipeline.py

Use `{{ variables('...') }}` in the dbt profiles.yml file.
cc:

[td] Interpolate variables in dbt profiles.yml

---

mage_ai/api/presenters/PipelineRunPresenter.py

Add `started_at` to the pipeline run policy.
cc:

[dy] Add started_at to pipeline run policy

---

Dockerfile
dev.Dockerfile

Resolves: #3248
Variant of closed: #3258 
Groupes and Reorders Docker Statements for better build performance
- lower number of layers (smaller build)
- often changing things last
cc: @dy46 I have only removed the version pinning. It works for me.

Docker: Optimize build by reordering and grouping some statements v2

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/components/shared/Table/index.tsx

- Add tooltips to columns in "Features" table used for integration pipelines. This is to help users understand what the columns are used for and make it more visible to users (there are already explanations below the Features table that users might not be aware of).
Unique column:
Bookmark column:
Key prop column:

[jk] Integration pipeline column explanations

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/dbt/__init__.py
mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts

Disable dbt blocks automatically running dbt tests.
cc:

[td] Disable automatic dbt tests

---

mage_ai/ai/constants.py
mage_ai/api/resources/PipelineResource.py
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
mage_ai/frontend/interfaces/LLMType.ts

Add inline comments to a block.
cc:

[td] Add inline comments for a block using AI

---

mage_ai/data_preparation/models/block/integration/__init__.py

Fix data integration pipeline column renaming in transformer block.
When using the clean_column_name transformer action to rename columns, we also need to rename the column names in 
unique_constraints and key_properties
Before this PR, the sync failed with the error
After this PR, the sync succeeded
cc:

[xy] Fix data integration pipeline column renaming in transformer block.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.17
* https://github.com/mage-ai/mage-ai/pull/3327
* https://github.com/mage-ai/mage-ai/pull/3337
* https://github.com/mage-ai/mage-ai/pull/3335
* https://github.com/mage-ai/mage-ai/pull/3342
* https://github.com/mage-ai/mage-ai/pull/3334
* https://github.com/mage-ai/mage-ai/pull/3338
* https://github.com/mage-ai/mage-ai/pull/3252
* https://github.com/mage-ai/mage-ai/pull/3345
* https://github.com/mage-ai/mage-ai/pull/3346
* https://github.com/mage-ai/mage-ai/pull/3347
* https://github.com/mage-ai/mage-ai/pull/3341
* https://github.com/mage-ai/mage-ai/pull/3348
* https://github.com/mage-ai/mage-ai/pull/3329
* https://github.com/mage-ai/mage-ai/pull/3320
* https://github.com/mage-ai/mage-ai/pull/3353
* https://github.com/mage-ai/mage-ai/pull/3355
* …

[xy] Bump version to 0.9.17

---

mage_ai/api/resources/FileContentResource.py

Update FileContentResource to ensure that all files in a project can be opened properly.
cc:

[dy] Fix FileContentResource file path check

---

mage_ai/server/constants.py
setup.py

Bug fix: https://github.com/mage-ai/mage-ai/pull/3363
cc:

[dy] Bump 0.9.18

---

mage_ai/api/policies/PipelinePolicy.py
mage_ai/api/resources/PipelineResource.py
mage_ai/frontend/components/AI/ControlPanel/index.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/Dashboard/utils.tsx
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/interfaces/LLMType.ts
mage_ai/frontend/pages/overview/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx

[td] Generate pipeline using AI

---

docs/guides/ai/overview.mdx
docs/mint.json

[td] Add docs for using AI

---

mage_ai/api/middleware.py
mage_ai/server/api/v1.py
mage_ai/server/server.py

Update `api/status` endpoint to bypass oauth check. There was an existing way to bypass oauth for certain endpoints, but it doesn't seem safe since it just checks if any element of the path equals a certain string. I added a new `RequestHandler` that can be configured to bypass oauth checks for a specified resource.

[dy] Update api/status endpoint

---

mage_ai/data_preparation/executors/k8s_pipeline_executor.py

Allow using k8s executor config for streaming pipeline.
cc:

[xy] Allow using k8s executor config for streaming pipeline.

---

mage_integrations/mage_integrations/connections/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/README.md
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/templates/config.json
mage_integrations/mage_integrations/sources/snowflake/README.md
mage_integrations/mage_integrations/sources/snowflake/__init__.py
mage_integrations/mage_integrations/sources/snowflake/templates/config.json

Add role to snowflake data integration pipeline.
cc:

[xy] Add role to snowflake data integration pipeline.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.19.
* https://github.com/mage-ai/mage-ai/pull/3365
* https://github.com/mage-ai/mage-ai/pull/3366
* https://github.com/mage-ai/mage-ai/pull/3352
* https://github.com/mage-ai/mage-ai/pull/3369
* https://github.com/mage-ai/mage-ai/pull/3371
* https://github.com/mage-ai/mage-ai/pull/3372
* https://github.com/mage-ai/mage-ai/pull/3374
* https://github.com/mage-ai/mage-ai/pull/3376
* https://github.com/mage-ai/mage-ai/pull/3377
N/A
N/A
cc:

[xy] Bump version to 0.9.19.

---

mage_ai/api/policies/BlockRunPolicy.py
mage_ai/api/resources/BlockRunResource.py
mage_ai/frontend/components/ActionForm/index.tsx
mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/Logs/Table/index.tsx
mage_ai/frontend/components/Logs/Toolbar/index.tsx
mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineRun/MetricsSummary/index.tsx
mage_ai/frontend/components/PipelineRun/Widget/index.tsx
mage_ai/frontend/components/RecommendationsWindow/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/datasets/overview/utils.tsx
mage_ai/frontend/components/shared/Table/constants.ts
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/interfaces/BlockRunType.ts
mage_ai/frontend/oracle/components/Panel/index.tsx
mage_ai/frontend/oracle/components/Table/BaseTable.tsx
mage_ai/frontend/pages/manage/users/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/monitors/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx

- Add sorting to all block runs page for an individual pipeline.
- Add sorting to block runs page for an individual pipeline run.
- Block run table columns supported for sorting: `Status`, `Block`, and `Completed at`
Block runs for a pipeline run:
Block runs for a pipeline (with multiple pages):
GET `http://localhost:6789/api/block_runs?pipeline_uuid=demo_pipeline&_limit=30&_offset=0&order_by=block_uuid%20desc`
Response:
```
{
"block_runs": [
{
"block_uuid": "withered_dust",
"completed_at": "2023-05-31T07:13:20.295828",
"created_at": "2023-05-31T07:12:49",
"id": 4230,
"pipeline_run_id": 1531,
"status": "completed",
"updated_at": "2023-05-31T07:13:20",
"pipeline_schedule_id": 437,
"pipeline_schedule_name": "green dawn"
},
{
"block_uuid": "withered_dust",
"completed_at": …
```

[jk] Add sorting to Block Runs table

---

mage_ai/data_preparation/decorators.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/presenters/charts/data_sources/base.py
mage_ai/presenters/charts/data_sources/block.py
mage_ai/presenters/charts/data_sources/chart_code.py
mage_ai/presenters/charts/data_sources/constants.py
mage_ai/shared/strings.py

- Abstract class for creating a data source for a chart
- Chart data source from a pipeline block
cc:

[td] Add chart data source base and for block

---

mage_ai/api/policies/BasePolicy.py
mage_ai/api/policies/BlockLayoutItemPolicy.py
mage_ai/api/presenters/BlockLayoutItemPresenter.py
mage_ai/api/resources/BlockLayoutItemResource.py
mage_ai/api/resources/PageBlockLayoutResource.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/presenters/charts/data_sources/chart_code.py
mage_ai/tests/data_preparation/models/test_pipeline.py

- Get the underlying data of a block layout chart
cc:

[td] Block layout item API

---

mage_integrations/mage_integrations/destinations/mongodb/README.md
mage_integrations/mage_integrations/destinations/mongodb/__init__.py
mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/sinks.py
mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/target.py
mage_integrations/mage_integrations/destinations/mongodb/templates/config.json

Fixed mongodb destination error after INCREMENTAL pipeline run
Added RECORD pre-processing
Added table_name option on destination config
1.  **User reported not being able to modify data types on MongoDB destination**
Solution:
MongoDB sink was modified to support a preprocessing function on each record
This function checks each data type with the given schema, if a data type does not correspond to the given schema, the function will try to do a simple python type conversion. If failed, pipeline will break and user will be notified.
2. **User reported a ERROR message after doing a INCREMENTAL run**
Solution:
The error was being caused by the `state_path` not being defined on MongoDB `__init__.py ` file
State path was added
3. **User reported not being able to overwrite destination table …

Fixes on MongoDB destination (Data integration)

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3354
* https://github.com/mage-ai/mage-ai/pull/3356
* https://github.com/mage-ai/mage-ai/pull/3375
* https://github.com/mage-ai/mage-ai/pull/3370
* https://github.com/mage-ai/mage-ai/pull/3387
* https://github.com/mage-ai/mage-ai/pull/3389
* https://github.com/mage-ai/mage-ai/pull/3386
* https://github.com/mage-ai/mage-ai/pull/3262
* https://github.com/mage-ai/mage-ai/pull/3393
* https://github.com/mage-ai/mage-ai/pull/3394
* https://github.com/mage-ai/mage-ai/pull/3388
N/A
N/A
cc:

[xy] Bump version to 0.9.20

---

mage_ai/data_preparation/git/__init__.py
mage_ai/frontend/components/VersionControl/GitFiles/index.tsx

When doing a commit from the `version-control` page, the files have already been staged, so there's no need to add them again.
cc:

[dy] Fix git commit from version control

---

docs/data-integrations/configuration.mdx
docs/dbt/variable-interpolation.mdx
docs/development/variables/environment-variables.mdx
docs/development/variables/referencing-variables.mdx
docs/development/variables/secrets.mdx
docs/getting-started/setup.mdx
docs/mint.json
docs/orchestration/triggers/configure-triggers-in-code.mdx
docs/production/deploying-to-cloud/architecture.mdx

- Add doc for interpolating variables
- Organize other variables docs

[mp] add docs for interpolating variables and split from other variables docs

---

mage_ai/api/policies/GitCustomBranchPolicy.py
mage_ai/api/resources/GitBranchResource.py
mage_ai/api/resources/GitCustomBranchResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/git/api.py
mage_ai/data_preparation/sync/__init__.py
mage_ai/data_preparation/sync/git_sync.py
mage_ai/frontend/components/VersionControl/Remote/index.tsx
mage_ai/frontend/components/VersionControl/constants.ts

Add fetch and reset hard to version control app. There's currently no way to do a git fetch or hard reset through the version control UI, so I'm adding that here.
cc:

[dy] Add fetch and reset to version control app

---

Dockerfile
docs/production/configuring-production-settings/compute-resource.mdx
mage_ai/data_preparation/executors/ecs_pipeline_executor.py
mage_ai/data_preparation/executors/executor_factory.py
mage_ai/data_preparation/executors/k8s_pipeline_executor.py
mage_ai/data_preparation/executors/pipeline_executor.py
mage_ai/orchestration/pipeline_scheduler.py

Support ECS pipeline executor
Example pipeline metadata.yaml
```yaml
blocks
- ...
- ...
executor_type: ecs
run_pipeline_in_one_process: true
name: example_pipeline
...
```
cc:

[xy] Support ECS pipeline executor

---

mage_ai/server/constants.py
setup.py

Changes included
* https://github.com/mage-ai/mage-ai/pull/3397
* https://github.com/mage-ai/mage-ai/pull/3396
* https://github.com/mage-ai/mage-ai/pull/3406
* https://github.com/mage-ai/mage-ai/pull/3403
* https://github.com/mage-ai/mage-ai/pull/3385
* https://github.com/mage-ai/mage-ai/pull/3405
* https://github.com/mage-ai/mage-ai/pull/3395
* https://github.com/mage-ai/mage-ai/pull/3407
* https://github.com/mage-ai/mage-ai/pull/3419
* https://github.com/mage-ai/mage-ai/pull/3417
* https://github.com/mage-ai/mage-ai/pull/3399
* https://github.com/mage-ai/mage-ai/pull/3409
* https://github.com/mage-ai/mage-ai/pull/3418
* https://github.com/mage-ai/mage-ai/pull/3423
* https://github.com/mage-ai/mage-ai/pull/3422
N/A
N/A
cc:

[xy] Bump version to 0.9.21

---

mage_ai/api/presenters/BlockLayoutItemPresenter.py
mage_ai/api/resources/BlockLayoutItemResource.py
mage_ai/api/resources/PageBlockLayoutResource.py
mage_ai/data_cleaner/analysis/charts.py
mage_ai/data_preparation/decorators.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/models/widget/charts.py
mage_ai/data_preparation/models/widget/utils.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.style.tsx
mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
mage_ai/frontend/components/BlockLayout/BlockLayoutItemDetail/index.tsx
mage_ai/frontend/components/BlockLayout/ChartConfigurations.tsx
mage_ai/frontend/components/BlockLayout/index.tsx
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/GlobalDataProductDetail/index.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/interfaces/BlockLayoutItemType.ts
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/frontend/interfaces/PageBlockLayoutType.ts
mage_ai/frontend/oracle/components/FlyoutMenu/FlyoutMenuWrapper.tsx
mage_ai/frontend/pages/block-layout.tsx
mage_ai/presenters/charts/data_sources/block.py
mage_ai/shared/strings.py

Add custom charts to an application and display the charts.
cc:

[td] Block layout app

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/logging/logger.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/models/triggers/__init__.py
mage_ai/server/utils/output_display.py

Pass mage block logger through block `kwargs` and also redirect stderr to the `StreamToLogger` object. Some logs will get logged to stderr by default such as the `loguru` module.

[dy] Support custom logging level

---

mage_ai/data_preparation/executors/gcp_cloud_run_block_executor.py
mage_ai/data_preparation/models/variable.py
mage_ai/services/gcp/cloud_run/cloud_run.py

Fix command on GCP cloud run. When there's json value included in the command, the json value was splited by empty space. This PR fixes this issue.
After the fix
Before the fix
cc:

[xy] Fix command on GCP cloud run.

---

mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.style.tsx
mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
mage_ai/frontend/components/BlockLayout/index.tsx

Drag and drop the block layout items to re-arrange them.
cc:

[td] Drag and drop block layout

---

mage_ai/api/policies/GitBranchPolicy.py
mage_ai/api/presenters/GitBranchPresenter.py
mage_ai/api/presenters/GitCustomBranchPresenter.py
mage_ai/api/resources/GitBranchResource.py
mage_ai/api/resources/GitCustomBranchResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/preferences.py
mage_ai/data_preparation/sync/git_sync.py
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/pages/settings/workspace/sync-data.tsx

Fix git sync and git integration issues. There are several different git workflows now, so making any git change can potentially affect them differently. We will need to consolidate these workflows at some point.
It is also not a super smooth experience going from one workflow to another.
cc:

[dy] Fix git sync issues

---

mage_ai/api/resources/BlockLayoutItemResource.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/frontend/components/BlockLayout/index.tsx
mage_ai/frontend/interfaces/BlockLayoutItemType.ts
mage_ai/presenters/charts/data_sources/block_runs.py
mage_ai/presenters/charts/data_sources/pipeline_runs.py
mage_ai/presenters/charts/data_sources/pipeline_schedules.py
mage_ai/presenters/charts/data_sources/pipelines.py

Get data from these sources:
1. Pipelines
2. Triggers
3. Pipeline runs
4. Block runs
cc:

[td] Add more data sources for block layout content

---

docs/production/configuring-production-settings/compute-resource.mdx
mage_ai/data_preparation/executors/executor_factory.py
mage_ai/data_preparation/models/constants.py
mage_ai/services/aws/ecs/config.py

* [Support local_python_force executor type.](https://github.com/mage-ai/mage-ai/commit/bf056a3e2b8afedaf22efd715d5732680d5ee48a)
* [Support configure ECS executor launch type.](https://github.com/mage-ai/mage-ai/commit/74c777bc3260564424802d9360ffa9a2dc44ee20)
cc:

[xy] Some improvements on executors

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/logging/logger.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/server/utils/output_display.py

Revert "[dy] Support custom logging level"

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3429
* https://github.com/mage-ai/mage-ai/pull/3378
* https://github.com/mage-ai/mage-ai/pull/3418
* https://github.com/mage-ai/mage-ai/pull/3417
* https://github.com/mage-ai/mage-ai/pull/3424
* https://github.com/mage-ai/mage-ai/pull/3437
* https://github.com/mage-ai/mage-ai/pull/3438
* https://github.com/mage-ai/mage-ai/pull/3439
* https://github.com/mage-ai/mage-ai/pull/3436
* https://github.com/mage-ai/mage-ai/pull/3444
* https://github.com/mage-ai/mage-ai/pull/3445
* https://github.com/mage-ai/mage-ai/pull/3448
* https://github.com/mage-ai/mage-ai/pull/3440
* https://github.com/mage-ai/mage-ai/pull/3447
* https://github.com/mage-ai/mage-ai/pull/3452
docker/github action changes:
* https://github.com/mage-ai/mage-ai/pull/3441
* …

[dy] Bump to 0.9.22

---

README.md
mage_ai/api/resources/BlockLayoutItemResource.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/frontend/components/BlockLayout/index.tsx
mage_ai/frontend/components/PipelineDetailPage/constants.ts
mage_ai/frontend/components/PipelineDetailPage/utils.ts
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/components/charts/BarChartHorizontal.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/frontend/interfaces/PageBlockLayoutType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/dashboard.tsx
mage_ai/presenters/block_layout/page.py
mage_ai/presenters/charts/data_sources/block_runs.py
mage_ai/presenters/charts/data_sources/pipeline_runs.py
mage_ai/presenters/charts/data_sources/pipeline_schedules.py
mage_ai/presenters/charts/data_sources/pipelines.py

- Add block layout app to pipeline detail dashboard
https://github.com/mage-ai/mage-ai/assets/1066980/85085c2c-9e31-4202-a0f7-b0159096403d
https://github.com/mage-ai/mage-ai/assets/1066980/0e0dbecb-37a6-4bdf-96c3-d06a2184bb07
cc:
Uploading CleanShot 2023-09-07 at 17.17.39.mp4…

[td] Pipeline detail dashboard

---

mage_ai/frontend/components/settings/workspace/Preferences.tsx

- Obfuscate OpenAI api key in project settings when it has been saved.

[jk] Hide OpenAI api key

---

docs/streaming/destinations/postgres.mdx
mage_ai/streaming/sinks/postgres.py
mage_ai/streaming/sources/amazon_sqs.py
mage_ai/tests/streaming/sinks/test_postgres.py

* [Add additional health check message.](https://github.com/mage-ai/mage-ai/commit/8fb9a999cf0ad84403494dbf36f3397194a92921)
* [Support unique constraints for postgres sink.](https://github.com/mage-ai/mage-ai/commit/c9e0482774400a5e8f50dbb1720780e0c9736ba7)
cc:

[xy] Some improvements for streaming pipeline

---

mage_ai/frontend/components/PipelineDetailPage/utils.ts

Comment out dashboard in navigation bar.
N/A
N/A
cc:

[xy] Comment out dashboard in navigation bar.

---

mage_ai/frontend/components/BlockLayout/index.tsx
mage_ai/frontend/components/Dashboard/constants.ts
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/pages/overview/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/dashboard.tsx

Add block layout charts to overview page.
cc:

[td] Add block layout to overview

---

mage_ai/cli/main.py

Run git sync on mage run if `sync_on_start` is enabled.
cc:

[dy] Run git sync on mage run

---

mage_ai/cluster_manager/aws/emr_cluster_manager.py
mage_ai/data_preparation/executors/pyspark_pipeline_executor.py
mage_ai/data_preparation/repo_manager.py
mage_ai/services/aws/emr/config.py
mage_ai/services/aws/emr/launcher.py
mage_ai/services/aws/emr/resource_manager.py

Allow creating EMR with custom bootstrap script.
cc:

[xy] Allow creating EMR with custom bootstrap script.

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3450
* https://github.com/mage-ai/mage-ai/pull/3455
* https://github.com/mage-ai/mage-ai/pull/3451
* https://github.com/mage-ai/mage-ai/pull/3457
* https://github.com/mage-ai/mage-ai/pull/3458
* https://github.com/mage-ai/mage-ai/pull/3400
* https://github.com/mage-ai/mage-ai/pull/3460
* https://github.com/mage-ai/mage-ai/pull/3464
* https://github.com/mage-ai/mage-ai/pull/3466
* https://github.com/mage-ai/mage-ai/pull/3468
* https://github.com/mage-ai/mage-ai/pull/3456
* https://github.com/mage-ai/mage-ai/pull/3462
* https://github.com/mage-ai/mage-ai/pull/3472
* https://github.com/mage-ai/mage-ai/pull/3465
* https://github.com/mage-ai/mage-ai/pull/3449
* https://github.com/mage-ai/mage-ai/pull/3433
* https://github.com/mage-ai/mage-ai/pull/3446 …

[xy] Bump version to 0.9.23

---

mage_ai/cluster_manager/kubernetes/workload_manager.py

For debugging purposes, it would be useful to throw an exception if the ingress is not updated properly when provided.
cc:

[dy] Throw exception for ingress

---

docs/production/databases/default.mdx

Simple PR to fix the connection string, per https://github.com/mage-ai/mage-ai/compare/master...matt/connection-string-hotfix?quick_pull=1

Correct connection string

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3484
* https://github.com/mage-ai/mage-ai/pull/3492
cc:

[dy] Bump to 0.9.24

---

docs/mint.json
docs/visualizations/dashboards.mdx

Added docs for charts: http://localhost:3001/visualizations/dashboards

[td] Add docs for visualizations

---

setup.py

Added the elasticsearch library to setup file
Added the elasticsearch library to setup file
This library was missing for setup

Added the elasticsearch library to setup file

---

mage_ai/frontend/components/VersionControl/Branches/index.tsx
mage_ai/orchestration/db/migrations/env.py

Only allow switching to local branches in version control app. This still allows users to merge, rebase, and pull from remote branches.
cc:

[dy] Only allow switching to local branches

---

mage_ai/server/terminal_server.py

Ensure that the cwd is in the current project folder, and that the path exists. If either of those conditions are not true, use the default path.
cc:

[dy] Add checks for cwd in websocket server

---

mage_ai/api/resources/BlockLayoutItemResource.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/widget/charts.py
mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
mage_ai/frontend/components/BlockLayout/index.tsx
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/PipelineDetailPage/utils.ts
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/presenters/charts/data_sources/block_runs.py
mage_ai/presenters/charts/data_sources/constants.py
mage_ai/presenters/charts/data_sources/pipeline_runs.py
mage_ai/presenters/charts/data_sources/pipeline_schedules.py
mage_ai/presenters/charts/data_sources/pipelines.py
mage_ai/usage_statistics/constants.py
mage_ai/usage_statistics/logger.py
mage_ai/usage_statistics/utils.py

[td] Bug bash charts 2.0

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/logging/logger.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/models/block/integration/__init__.py
mage_ai/server/utils/output_display.py

This PR is a modification of https://github.com/mage-ai/mage-ai/pull/3428. The previous PR would cause integration pipelines to not run properly. This PR updates the block code so that integration blocks don't redirect stderr.

[dy] Support custom logging level v2

---

mage_ai/api/resources/BlockResource.py
mage_ai/api/resources/CustomTemplateResource.py
mage_ai/api/resources/PipelineResource.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/components/CustomTemplates/PipelineTemplateDetail/index.tsx
mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
mage_ai/frontend/components/DependencyGraph/BlockNode/utils.ts
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/usage_statistics/constants.py
mage_ai/usage_statistics/logger.py

- Log block create
- Log pipeline create
- Log custom template create
cc:

[td] Add usage statistics for creating blocks, pipelines, and custom templates

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3503
* https://github.com/mage-ai/mage-ai/pull/3481
* https://github.com/mage-ai/mage-ai/pull/3505
* https://github.com/mage-ai/mage-ai/pull/3501
* https://github.com/mage-ai/mage-ai/pull/3507
* https://github.com/mage-ai/mage-ai/pull/3495
* https://github.com/mage-ai/mage-ai/pull/3508
* https://github.com/mage-ai/mage-ai/pull/3473
* https://github.com/mage-ai/mage-ai/pull/3509
* https://github.com/mage-ai/mage-ai/pull/3510
* https://github.com/mage-ai/mage-ai/pull/3463
* https://github.com/mage-ai/mage-ai/pull/3513
* https://github.com/mage-ai/mage-ai/pull/3514
* https://github.com/mage-ai/mage-ai/pull/3520
* https://github.com/mage-ai/mage-ai/pull/3528
N/A
N/A
cc:

[xy] Bump version to 0.9.25

---

mage_ai/api/policies/BlockPolicy.py
mage_ai/api/presenters/BlockPresenter.py
mage_ai/api/presenters/PipelinePresenter.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/constants.py
mage_ai/data_preparation/models/pipeline.py

Create `catalog.json` file for pipeline blocks. This is required for unifying standard and data integration pipelines.
cc:

[td] Update block catalog via API

---

mage_ai/api/resources/OauthResource.py
mage_ai/data_preparation/git/api.py
mage_ai/tests/data_preparation/git/test_api.py

There were two different methods for fetching access tokens, so I consolidated them. This should fix github authentication for new users.
cc:

[dy] Fix git authentication issue

---

.circleci/config.yml
.github/workflows/build_and_test.yml
mage_ai/frontend/.eslintrc.js
mage_ai/frontend/.storybook/main.js
mage_ai/frontend/package.json
mage_ai/frontend/yarn.lock

- There was an issue running Storybook so needed to upgrade some packages in order to resolve it.
- Successfully rebuilt Docker image/containers and ran Storybook without any issues (previous error no longer appeared).

[jk] Upgrade Storybook

---

integrations/spark/Dockerfile

Update Mage spark dockerfile.
close: https://github.com/mage-ai/mage-ai/issues/3536
cc:

[xy] Update Mage spark dockerfile.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.26
* https://github.com/mage-ai/mage-ai/pull/3430
* https://github.com/mage-ai/mage-ai/pull/3519
* https://github.com/mage-ai/mage-ai/pull/3531
* https://github.com/mage-ai/mage-ai/pull/3404
* https://github.com/mage-ai/mage-ai/pull/3534
* https://github.com/mage-ai/mage-ai/pull/3487
* https://github.com/mage-ai/mage-ai/pull/3525
* https://github.com/mage-ai/mage-ai/pull/3532
* https://github.com/mage-ai/mage-ai/pull/3498
* https://github.com/mage-ai/mage-ai/pull/3530
* https://github.com/mage-ai/mage-ai/pull/3522
* https://github.com/mage-ai/mage-ai/pull/3521
* https://github.com/mage-ai/mage-ai/pull/3537
* https://github.com/mage-ai/mage-ai/pull/3539
* https://github.com/mage-ai/mage-ai/pull/3542
* https://github.com/mage-ai/mage-ai/pull/3543
* …

[xy] Bump version to 0.9.26

---

mage_ai/frontend/oracle/components/Banner/index.style.ts
mage_ai/frontend/oracle/components/Banner/index.tsx
mage_ai/frontend/oracle/styles/units/borders.ts
mage_ai/frontend/pages/_app.tsx
mage_ai/frontend/storage/constants.ts

- Add persistent warning message on demo site that tells users not to enter private credentials in the app. Users can hide the warning banner.

[jk] Display warning on demo site to prevent users from entering private credentials.

---

docs/development/project/local-timezone.mdx
docs/mint.json

- See title.
Locally via `mintlify dev`

[jk] Add doc for local timezone setting

---

mage_ai/api/resources/BlockRunResource.py
mage_ai/api/resources/SearchResultResource.py
mage_ai/data_integrations/utils/scheduler.py
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/data_integration/mixins.py
mage_ai/data_preparation/models/block/data_integration/utils.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/tests/data_preparation/executors/test_block_executor.py

- Create a set of block runs for each stream
- Create a set of block runs for each batch in a stream
cc:

[td] Fan out source block runs

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/usage_statistics/logger.py

- Run batches in a stream sequentially
- Log landing time enabled
cc:

[td] Run batches in a single stream sequentially

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.27
* https://github.com/mage-ai/mage-ai/pull/3550
* https://github.com/mage-ai/mage-ai/pull/3545
* https://github.com/mage-ai/mage-ai/pull/3557
* https://github.com/mage-ai/mage-ai/pull/3559
* https://github.com/mage-ai/mage-ai/pull/3554
* https://github.com/mage-ai/mage-ai/pull/3541
* https://github.com/mage-ai/mage-ai/pull/3561
* https://github.com/mage-ai/mage-ai/pull/3562
* https://github.com/mage-ai/mage-ai/pull/3563
* https://github.com/mage-ai/mage-ai/pull/3560
* https://github.com/mage-ai/mage-ai/pull/3568
* https://github.com/mage-ai/mage-ai/pull/3572
* https://github.com/mage-ai/mage-ai/pull/3558
* https://github.com/mage-ai/mage-ai/pull/3570
* https://github.com/mage-ai/mage-ai/pull/3553
* https://github.com/mage-ai/mage-ai/pull/3576
* …

[xy] Bump version to 0.9.27

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/block.py

Fix variables interpolation in dbt target.
cc:

[xy] Fix variables interpolation in dbt target.

---

mage_ai/data_preparation/models/block/dbt/block.py

DBT seed command needs `--vars` so it can interpolate.

[td] Fixed dbt seed requiring variables

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/data_integration/utils.py

Destination blocks weren’t merging the upstream catalogs if the upstream block isn’t a source block.
cc:

[td] Fix getting catalog from upstream for destination

---

mage_ai/api/resources/BlockResource.py
mage_ai/data_integrations/utils/settings.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/templates/data_integrations/utils.py
mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/utils/models/block.ts
mage_ai/server/api/integration_sources.py

Render a different UI for data integration blocks.
cc:

[td] Data integration block UI

---

mage_ai/data_preparation/models/variable.py

Fix writing dataframe to s3 storage. The column types file wasn't using the storage class to write and read. Thus, it caused errors when fetching the block output dataframe.
Fix writing dataframe to s3 storage.
cc:

[xy] Fix writing dataframe to s3 storage.

---

mage_ai/data_preparation/models/errors.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/utils.py

Check yaml serialization before writing to global variables.
cc:

[dy] Check yaml serialization before writing variable

---

mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/storage/gcs_storage.py
mage_ai/data_preparation/variable_manager.py
mage_ai/shared/constants.py
mage_ai/shared/urls.py
mage_ai/tests/data_preparation/storage/test_gcs_storage.py

This MR enables using Google Cloud Storage as a variables storage (block outputs) the same way as S3 can be used.
cc:

WIP: Feat/gcs storage

---

mage_ai/api/presenters/SyncPresenter.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/sync/__init__.py
mage_ai/data_preparation/sync/git_sync.py
mage_ai/frontend/interfaces/SyncType.ts
mage_ai/frontend/pages/settings/workspace/sync-data.tsx

Sync one level of git submodules when performing git sync. Users will need to check the `Include submodules` button to enable this feature. I'll also update the documentation
cc:

[dy] Sync git submodules

---

docs/design/data-pipeline-management.mdx
docs/integrations/spark-pyspark.mdx
mage_ai/data_preparation/models/variable.py

Update docs for variable storage and emr config.
preview docs locally
cc:

[xy] Update docs for variable storage and emr config.

---

mage_ai/shared/utils.py

Fix https://github.com/mage-ai/mage-ai/issues/3566

Support TIMESTAMP in redshift convert

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3497
* https://github.com/mage-ai/mage-ai/pull/3578
* https://github.com/mage-ai/mage-ai/pull/3579
* https://github.com/mage-ai/mage-ai/pull/3574
* https://github.com/mage-ai/mage-ai/pull/3580
* https://github.com/mage-ai/mage-ai/pull/3584
* https://github.com/mage-ai/mage-ai/pull/3585
* https://github.com/mage-ai/mage-ai/pull/3586
* https://github.com/mage-ai/mage-ai/pull/3587
* https://github.com/mage-ai/mage-ai/pull/3588
* https://github.com/mage-ai/mage-ai/pull/3590
* https://github.com/mage-ai/mage-ai/pull/3555
* https://github.com/mage-ai/mage-ai/pull/3581
* https://github.com/mage-ai/mage-ai/pull/3358
* https://github.com/mage-ai/mage-ai/pull/3596
* https://github.com/mage-ai/mage-ai/pull/3595
* https://github.com/mage-ai/mage-ai/pull/3592 …

[xy] Bump version to 0.9.28

---

mage_ai/frontend/components/BlockLayout/index.tsx

Ethan Brown:
"I am noticing a couple things with the new charts dashboard. The first thing is when trying to rename a new chart on the dashboard. See video for behavior.
The second thing is just general performance. I imagine it will improve in future updates but sometimes it will take a several minutes to load the dashboard. I have 4 charts on it right now."

[td] Fix charts when trying to change name

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/3619

[td] 0.9.29

---

README.md
docs/guides/tips-and-tricks.mdx

Simple PR to add a few tips & tricks to our page

[mp] Update tips & tricks page
