mage-ai/mage-ai

mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/package.json
mage_ai/frontend/yarn.lock

- Build error when running `yarn export_prod` or `yarn build` locally, though the build was successful in the CI/CD process:
```
TypeError: Cannot read properties of undefined (reading 'tf')
at getColorsForBlockType
at Array.reduce
at getBlockColorHexCodeMapping
at 44425
at __webpack_require__
at 55283
at __webpack_require__ 
at /mage/repos/mage-ai/mage_ai/frontend/.next/server/pages/pipelines/[pipeline]/monitors/block-runs.js:60:92
at __webpack_require__.a {
type: 'TypeError'
}
```
- Upgrade Nextjs minor version
- Successfully created Nextjs build locally without error.

[jk] Fix nextjs local build type error

---

mage_ai/streaming/sources/amazon_sqs.py
mage_ai/streaming/sources/base.py

Add healthcheck to sqs streaming source.
* Run consumer thread and health check thread separately
* Automatically terminate the consumer thread if health check fails.
cc:

[xy] Add healthcheck to sqs streaming source.

---

mage_integrations/mage_integrations/sources/postgresql/__init__.py

Create lsn and _mage_deleted_at in initial log_based sync.
Close: https://github.com/mage-ai/mage-ai/issues/3344
Before this PR, those two columns are not created in the first sync.
cc:

[xy] Create lsn and _mage_deleted_at in initial log_based sync.

---

mage_ai/orchestration/db/__init__.py

Encountered the following exception when adding a specific schema to a PostgreSQL connection URL:
```
mage-ai-server-1  | The above exception was the direct cause of the following exception:
mage-ai-server-1  | 
mage-ai-server-1  | Traceback (most recent call last):
mage-ai-server-1  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
mage-ai-server-1  |     self.run()
mage-ai-server-1  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
mage-ai-server-1  |     self._target(*self._args, **self._kwargs)
mage-ai-server-1  |   File "/home/src/mage_ai/orchestration/db/process.py", line 15, in start_session_and_run
mage-ai-server-1  |     results = target(*args)
mage-ai-server-1  |   File …
```

[hw] Change the default search path to the schema given in the connection URL for PostgreSQL

---

mage_ai/data_preparation/models/block/dbt/utils/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/tests/data_preparation/models/test_global_data_product.py
mage_ai/tests/data_preparation/models/test_pipeline.py
mage_ai/tests/orchestration/triggers/test_global_data_product.py
mage_ai/tests/orchestration/triggers/test_utils.py

This PR adds validation to a pipeline to ensure that blocks with duplicate uuids are not added to the same pipeline. The validation happens when loading the pipeline as well as adding a block to a pipeline.
If a pipeline already has blocks with duplicate uuids, they should see an error when opening the pipeline instead of the entire server crashing, like in this github issue: https://github.com/mage-ai/mage-ai/issues/2997.
cc:

[dy] Raise exception if a pipeline has duplicate block uuids

---

dev.Dockerfile

Nodesource does not support setup scripts anymore. The installation is straight forward.
In addition I have
- updated to Nodejs 20, as its the current version and Nodejs 17 is EOL.
- removed npm as its already included in nodejs package
Ran dev.Dockerfile using scripts/dev.sh and checked whether localhost:3000 still works.
cc: @dy46

Docker: Installation Method of Node using setup_17.x is no longer supported

---

docs/orchestration/triggers/configure-triggers-in-code.mdx
mage_ai/api/resources/PipelineResource.py
mage_ai/api/resources/PipelineScheduleResource.py
mage_ai/data_preparation/models/triggers/__init__.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/tests/api/operations/test_pipeline_schedules.py

- The saved triggers in code (i.e. the `triggers.yaml` files) were not getting updated when users interacted with the UI (e.g. starting or pausing pipeline schedules). This PR automatically updates the `triggers.yaml` files when user makes changes through the UI to the pipeline schedules that are saved as code.
- In addition to starting/pausing an individual trigger, users can also start or pause a pipeline, which can change the `status` of multiple triggers at once and require the `triggers.yaml` config file to be updated for multiple triggers.
- When deleting a trigger saved as code, also remove that trigger from the `triggers.yaml` file. Otherwise, the trigger will keep getting recreated since it is still saved as code.
- Added unit test
- Tested through UI and confirmed changes in …

[jk] Auto-update triggers in code when making changes in UI

---

mage_ai/data_integrations/utils/scheduler.py

If a user does not specify a Destination block for a Data integration pipeline run, it will receive this log message:
In order to make it easier to understand that 1 Source and 1 Destination block are necessary, a None check was added to the Destination Block type, and a exception message explaining what happened:
Tested on a Local mage instance
- 
cc:

Feat: Added Missing destination block warning

---

mage_ai/data_preparation/models/block/__init__.py

Fix creating subfolder when renaming block.
The subfolder was created with a wrong path (relative path, missing the `/` at the beginning). This PR fixes it.
Before the fix, it failed
After the fix, it successfully renames the block
cc:

[xy] Fix creating subfolder when renaming block.

---

mage_integrations/mage_integrations/destinations/bigquery/README.md
mage_integrations/mage_integrations/destinations/mssql/README.md
mage_integrations/mage_integrations/destinations/mysql/README.md
mage_integrations/mage_integrations/destinations/postgresql/README.md
mage_integrations/mage_integrations/destinations/snowflake/README.md
mage_integrations/mage_integrations/destinations/sql/base.py

When running SQL Destinations in Data Integration Pipelines, a user may experience a permission error.
This is caused by the Destination user not having schema creation auth.
To fix this issue, a disable schema creation was added on SQL Base class.
Tested on a local mage instance, using API -> PostgreSQL destination.
**With** schema creation:
**Without** schema creation:
cc:

Added disable schema creation config

---

mage_integrations/mage_integrations/destinations/postgresql/__init__.py
mage_integrations/mage_integrations/destinations/sql/utils.py

Add `key_properties` argument to `build_create_table_command` so that the primary key constraint can be added to the destinations. Right now, I only added support for Postgresql. For other data warehouses, the command may be slightly different.

[dy] Add support for key properties for postgresql destination

---

.pre-commit-config.yaml
mage_integrations/mage_integrations/sources/commercetools/schemas/orders.json
mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/adcreative.json
mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights.json
mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights_age_and_gender.json
mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights_country.json
mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights_dma.json
mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights_platform_and_device.json
mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights_region.json
mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/shared/targeting.json
mage_integrations/mage_integrations/sources/outreach/tap_outreach/schemas/mailboxes.json
mage_integrations/mage_integrations/sources/outreach/tap_outreach/schemas/mailings.json
mage_integrations/mage_integrations/sources/outreach/tap_outreach/schemas/teams.json
mage_integrations/mage_integrations/sources/stripe/schemas/shared/charge.json
mage_integrations/mage_integrations/sources/zendesk/tap_zendesk/schemas/tickets.json

The pre-commit hook `check-yaml` does not support multiple documents in a single file separated by `---`. I have added the `--unsafe` option to support this. No files had to be fixed.
Added the pre-commit hook `check-json` to also check json files. Found a couple of json files, which had issues by having duplicated keys. Those I have also fixed.
cc: @wangxiaoyou1993 @dy46

Fix+Optimize pre-commit hook check-yaml and add check-json

---

.github/workflows/build_and_test.yml

Often new commits are pushed without running the pre-commit hooks. The "Build-and-Test" Github action workflow only runs linting but not all pre-commit hooks. I have changed it to use the pre-commit definition for both local development and the github action workflow.
Also the Github Action Workflow will first lint and then build, which will reduce the number of unneeded builds.
cc: @wangxiaoyou1993, @dy46

Full Code Quality Check in Github Action Workflow "Build and Test"

---

mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.style.tsx
mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
mage_ai/frontend/components/BlockLayout/LayoutDivider/index.style.tsx
mage_ai/frontend/components/BlockLayout/LayoutDivider/index.tsx
mage_ai/frontend/components/BlockLayout/index.tsx

Add block layout items in between columns and in between rows
cc:

[td] Add block layout item in between others

---

.github/workflows/build_and_test.yml

Currently the workflow doesnt run against any files. This change adds the changed files to the pre-commit command.

Fix Check Code Quality Workflow

---

.github/workflows/lint_docker_image.yml
Dockerfile
dev.Dockerfile

Resolves: #3249, #3250
Adds some basic Docker image linting using hadolint. The workflow will only run, if a Dockerfile is changed and is very lightweight.
Corrects warnings from hadolint:
- Missing quotes
- No consecutive `RUN` statements
- No pipefail configured
Ignores warnings from hadolint:
- Not using root
- Missing specific package versions for apt, pip and node
Additional changes:
- Added specific python image. Currently 3.10 is 3.10-bookworm (Debian 12), but this might change in the future.
mssql does not yet officially support Debian 12 (apt sources list only available for Debian 11), but is working somehow. Therefore pinning the debian version makes it a bit more stable.
- Removed the `PIP` argument, as I couldn't find any use case for it.
cc: @dy46, @wangxiaoyou1993

Docker: Lint Image and some best practices

---

mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx

- The `status` query param was being included in the blocks runs request, but it should only have been included in the pipeline runs request.
- Local

[jk] Remove unnecessary query from block runs request

---

mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/orchestration/db/setup.py

Fix aws secrets manager dependency issue in `db/setup.py`. The `secrets_manager` module only needs to be imported if the environment variable is set.
cc:

[dy] Fix aws secrets manager dependency issue

---

mage_integrations/mage_integrations/sources/bigquery/__init__.py
mage_integrations/mage_integrations/sources/sql/utils.py

Fix comparing bookmark value for timestamp col in BigQuery.
cc:

[xy] Fix comparing bookmark value for timestamp col in BigQuery.

---

docs/development/variables/block-variables.mdx
docs/mint.json
mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/PipelineVariableType.ts
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Update the `Block settings` section of the Sidekick so that users can add or update block variables stored on an individual block's configuration.
- Fix redirect when clicking `Add callback` from block "More actions" dropdown.

[jk] Add and update block variables through UI

---

.github/workflows/build_and_test.yml
mage_ai/frontend/pages/settings/workspace/sync-data.tsx
requirements.txt

Bump version of GitPython to fix this issue: https://github.com/gitpython-developers/GitPython/issues/1566
Also, update the logic of showing git sync operations to be a little more clear.
cc:

[dy] Fix git issues

---

mage_ai/orchestration/db/models/schedules.py
mage_ai/tests/orchestration/db/models/test_schedules.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

Compare start_time and execution_date in should_schedule. If current_execution_date is before start_time, don't schedule it.
After the fix, it doesn't schedule the pipeline run immediately after I start the trigger.
Before the fix, it schedules the pipeline run with execution date before the start time.
cc:

[xy] Compare start_time and execution_date in should_schedule.

---

mage_ai/services/aws/emr/config.py
mage_ai/services/aws/emr/emr.py

Support auto scaling for EMR cluster.
Example config
```yaml
emr_config:
master_instance_type: 'r5.4xlarge'
slave_instance_type: 'r5.4xlarge'
scaling_policy:
unit_type: 'Instances'    # 'InstanceFleetUnits'|'Instances'|'VCPU'
minimum_capacity_units: 1
maximum_capacity_units: 4
maximum_on_demand_capacity_units: 4
maximum_core_capacity_units: 3
```
cc:

[xy] Support auto scaling for EMR cluster.

---

mage_ai/api/policies/OauthPolicy.py
mage_ai/api/resources/OauthResource.py
mage_ai/authentication/oauth/utils.py
mage_ai/frontend/components/VersionControl/Remote/index.tsx

Added some changes to support github auth in multiple workspaces using the same database. When creating the github `Oauth2Application`, the project uuid will be added to the client_id to differentiate it among workspaces. Also, when we query access tokens for an application, we also need to take the Mage user into account.
cc:

[dy] Support github auth for different workspaces

---

mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx

- When the pipelines list was initially rendered, a default row sorting was causing issues with the correct pipeline being selected. If the pipelines fetched from the server wer already sorted by `pipeline_uuid` (which is not always the case), there wouldn't be issues with the correct pipeline being selected, but if the pipelines were not already sorted, this would cause a bug to occur where the selected pipeline does not match the correct pipeline that an action (e.g. rename, edit description) is meant to be performed on.
Before: The pipeline action is not performed on the correct selected pipeline:
After: The pipeline action performed on the selected pipeline is fixed because the pipeline row ordering is consistent with the order of pipelines returned from the server (for testing …

[jk] Fix initial ordering of pipeline rows

---

mage_ai/cli/main.py
mage_ai/data_preparation/preferences.py
mage_ai/data_preparation/sync/__init__.py

Add `GIT_SYNC_ON_EXECUTOR_START` environment variable. This will tell mage to run a git sync on the `mage run` command before executing the block or pipeline.

[dy] Add git sync on executor start env var

---

mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx

- Hide the `Execute pipeline` action item from the "Run" menu dropdown on the Pipeline Editor page for non-streaming pipelines.
- Context: We used to show the "Pipeline execution" section (see screenshot below for what it looks like) in the Sidekick of the Pipeline Editor for all pipeline types (integration, standard, and streaming) and allow users to execute the pipeline directly from the Pipeline Editor, but this caused inconsistencies and issues from executing the pipeline there and running a pipeline by creating a trigger (e.g. clicking the `Run @once` button on the Triggers list page). As a result, we started only showing the Pipeline execution for streaming pipelines since it is still needed for streaming pipelines specifically.
- In this PR, we are removing the `Execute pipeline` …

[jk] Only show Execute pipeline action for streaming pipelines

---

mage_ai/api/resources/ProjectResource.py
mage_ai/data_preparation/models/project/constants.py
mage_ai/frontend/components/Backfills/Detail/index.tsx
mage_ai/frontend/components/Backfills/Edit/index.tsx
mage_ai/frontend/components/Backfills/Table/index.tsx
mage_ai/frontend/components/Logs/Table/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/PipelineRun/Widget/index.tsx
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/Triggers/Table.tsx
mage_ai/frontend/components/Triggers/utils.ts
mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/frontend/components/settings/workspace/utils.ts
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/frontend/oracle/components/Calendar/index.tsx
mage_ai/frontend/oracle/components/Calendar/utils.ts
mage_ai/frontend/pages/overview/index.tsx
mage_ai/frontend/pages/pipeline-runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/backfills/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/frontend/pages/triggers/index.tsx
mage_ai/frontend/storage/constants.ts
mage_ai/frontend/utils/date.ts
mage_ai/frontend/utils/models/log.ts

- Add project setting for displaying datetimes in local timezone. The timezone conversions are all done on the frontend. Dates are still stored in config files and the metadata db in UTC time.
- Certain pages (namely a pipeline's "Monitor" page) and components (e.g. the pipeline run completed vertical bar chart on the "Overview" page) are still in UTC time since those dates are parsed from the UTC datetimes on the backend. Will require a separate PR to convert these dates in the graphs to the local timezone.
The dates are in local time (they have a timezone offset):

[jk] Local timezone setting

---

mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx

- Display dates in local timezone on Block Runs page.

[jk] Use local time on Block runs page

---

mage_integrations/mage_integrations/sources/oracledb/__init__.py

Swtich from `user_tab_columns` table to `all_tab_columns` to read all the table user has access to instead of user owned tables only.
Tested locally with pipeline and in oracle sqlplus
cc:

[xh]Update oracle discovery table

---

mage_ai/frontend/components/Backfills/Table/index.tsx
mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/Triggers/Table.tsx
mage_ai/frontend/components/shared/Table/constants.ts
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/frontend/utils/date.ts
mage_integrations/mage_integrations/tests/sources/api/test_api.py

- Show timezone (e.g. `America/Los Angeles`) when hovering over tooltip in date column headers and local timezone setting is enabled.
- Hovering over the dates in the tables also displays the datetimes in UTC, which allows users to check what the UTC date would be even if they have the local timezone setting enabled.
- Confirmed tooltips display timezone and UTC dates on various pages with tables (e.g. pipelines, triggers, pipeline runs, block runs, and backfills)
Examples:

[jk] Show timezone in column header tooltip when displaying local time

---

mage_integrations/mage_integrations/tests/sources/api/test_api.py
requirements.txt

Polar newest version (0.19.3) seems to alter the behavior of the `read_excel` function, used in Data Integrations API Source. Locking to 0.19.2 resolves this issue
cc:

Locking Polars version to 0.19.2

---

docs/visualizations/dashboards.mdx
mage_ai/api/resources/BlockLayoutItemResource.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/models/widget/constants.py
mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
mage_ai/frontend/components/BlockLayout/index.tsx
mage_ai/frontend/interfaces/BlockLayoutItemType.ts
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/frontend/pages/pipelines/index.tsx

Create a custom render logic for chart block. You can render HTML, JPEG, PNG, etc.
cc:

[td] Support custom render function in charts

---

mage_ai/api/presenters/KernelPresenter.py

Fix zmq context destroy issue.
This warning shows when the zmq context is deleted while the channel is still running: https://github.com/jupyter/jupyter_client/blob/main/jupyter_client/client.py#L119-L121
If the ZMQ context is not destroy successfully, it could cause memory leak.

[xy] Fix zmq context destroy issue.

---

mage_ai/data_preparation/executors/pyspark_block_executor.py
mage_ai/data_preparation/executors/pyspark_pipeline_executor.py
mage_ai/services/aws/emr/resource_manager.py
mage_integrations/mage_integrations/destinations/delta_lake_s3/__init__.py

Resolves #3515 
Used `posixpath.join` instead of `os.path.join` in all cases to force posix like join using forward slash for `s3://` paths.

Fix: S3 path is joined using os.path.join -> Error non posix systems

---

mage_ai/tests/api/operations/test_sessions.py

Fix: timestamp out of range on windows

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/tests/data_preparation/models/block/sql/utils/test_shared.py

If you wrote this:
```
SELECT *
FROM {{ df_1 }} AS a
```
Mage automatically adds an alias on top of the user defined alias.
This fix will only automatically add the alias if an alias isn’t defined.
cc:

[td] Fix raw SQL alias

---

.pre-commit-config.yaml
mage_integrations/requirements.txt
requirements.txt

Resolves #3524
- `snowflake-connector-python`
the production Dockerfile also installs mage-ai after mage-integrations, effectively sets whatever version of the package is 
needed for mage-ai. If there weren't any error until now, then it should be fine to downgrade.
- `pytz`
Typically upgrading pytz doesn't change anything. Most packages just define a minimum version anyway
cc:

Fix: Dependency mismatch between mage_ai and mage_integrations

---

docs/streaming/destinations/kafka.mdx
docs/streaming/sources/kafka.mdx
mage_ai/streaming/sinks/kafka.py
mage_ai/streaming/sources/kafka.py
mage_ai/tests/streaming/sources/test_kafka.py

Support multiple kafka topics in kafka source
Example config
```
connector_type: kafka
bootstrap_server: "kafka:9093"
consumer_group: unique_consumer_group
include_metadata: true
topics: ['test', 'test2']
```
This PR also moves the key to the metadata. Example record
```python
{
"data":{
"title":"test_title",
"director":"Bennett Miller",
"year":"2011",
"rating":0.9114357818630547
},
"metadata":{
"key": None,
"partition": 0,
"offset": 18759,
"time": 1695061975118,
"topic": "test"
}
}
```
cc:

[xy] Support multiple kafka topics in kafka source

---

mage_ai/data_preparation/models/block/sql/utils/shared.py

This PR fixes 2 issues related to schema/table name parsing when creating the upstream block table.
The first issue is that when the `data_provider` was the same for the current block and the upstream block, the schema name was being taken from the upstream block even if the `data_provider_profile` was different. 
The second issue is that the table_name from the upstream block can potentially be `database_name.table_name`, and the `table_name_parts` function was not accounting for that and just using the entire string as the table name.

[dy] Fix how table name is parsed for sql blocks

---

mage_ai/server/server.py

When using a base path, an url with trailing slash results in 404 as the path for routing in server.py becomes empty string and not single slash. This can be confusing.
```bash
MAGE_BASE_PATH=mage ./scripts/dev.sh dummy_project
```
- http://localhost:6789/mage - works
- http://localhost:6789/mage/ - does not work
```bash
MAGE_BASE_PATH=mage ./scripts/dev.sh dummy_project
```
- http://localhost:6789/mage - works
- http://localhost:6789/mage/ - also works

Support trailing slash when base path set

---

mage_ai/data_cleaner/column_types/column_type_detector.py
mage_ai/data_cleaner/shared/utils.py
mage_ai/data_preparation/models/widget/utils.py
mage_ai/tests/data_cleaner/statistics/test_calculator.py
mage_ai/tests/data_cleaner/transformer_actions/test_column.py
mage_ai/tests/data_cleaner/transformer_actions/test_custom_actions.py
mage_ai/tests/data_cleaner/transformer_actions/test_row.py

Resolves #3516 
made sure `np.int64` is used

Fix: dtype int is not always casted as int64

---

.pre-commit-config.yaml
mage_ai/cluster_manager/aws/emr_cluster_manager.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/models/variable.py
mage_ai/io/io_config.py
mage_ai/orchestration/db/__init__.py
mage_ai/server/docs_server.py
mage_ai/server/server.py
mage_ai/settings/repo.py
mage_ai/tests/base_test.py
mage_ai/tests/data_preparation/models/test_block.py
mage_ai/tests/data_preparation/models/test_file.py
mage_ai/tests/data_preparation/models/test_pipeline.py
mage_ai/tests/data_preparation/test_repo_manager.py
mage_integrations/mage_integrations/tests/sources/test_base.py
scripts/install_other_dependencies.py

Resolves #3518
replaced many instances. There are probably more.
WHen using paths as names (e.g. uuids for blocks) this should probably be handled more strict. e.g. always use forward slash in these cases. Also rather use posixpath instead of manually doing some concatenating of strings to form a path.
Fixed gitconfig for windows users. Running unittest on windows will not destroy the .gitconfig anymore.

Fix: paths include posix like forward slash in many instances, which will not work on non-posix systems

---

mage_ai/data_preparation/models/block/dbt/utils/__init__.py

Can’t overwrite runtime variables for dbt blocks.
cc:

[td] Fix overwriting runtime variables for dbt block

---

mage_ai/server/server.py

Previous [PR 3530](https://github.com/mage-ai/mage-ai/pull/3530) changed root path to r'/?' from r'/' .
After that I found an `if ... else` code block that used to handle the root path as a special case.
With the mentioned change the special case is not needed, the condition in the `if` never evaluates to `True`, and hence is obsolete.
Removing for cleaner code.
```bash
MAGE_BASE_PATH=mage ./scripts/dev.sh dummy_project
```
- http://localhost:6789/mage - works
- http://localhost:6789/mage/ - works
```bash
./scripts/dev.sh dummy_project
```
- http://localhost:6789 - works
- http://localhost:6789/ - works
cc:
@dy46

Removing obsolete code, handle root path

---

mage_ai/data_preparation/models/block/utils.py

Not concat pandas dataframes when not reducing dynamic blocks.
Code in still_leaf block
```python
@transformer
def transform(data, *args, **kwargs):
result = []
print(data)
for d in data:
result.append(pd.DataFrame.from_dict(d))
return result
```
Before the fix, the list of dataframes get concatenate automatically in the data exporter block.
With the fix, the data exporter block gets the list of dataframes as input. 
cc:

[xy] Not concat pandas dataframes when not reducing dynamic blocks.

---

mage_ai/frontend/components/CustomTemplates/BrowseTemplates/index.tsx

- Update wording for empty pipeline template state since there is no button in the UI for creating a new pipeline template directly from the pipeline templates page.

[jk] Update wording for empty pipeline template state

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/tests/data_preparation/models/test_block.py

- Reorder a block's `upstream_blocks` based on the pipeline's block order when reordering the blocks in the pipeline.
- Users can reorder blocks in a pipeline by dragging them before or after another block in the Pipeline Editor. Now when reordering the blocks, this will also automatically update the upstream blocks order for a block based on the pipeline's block order.

[jk] Reorder upstream blocks

---

mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/Triggers/Table.tsx
mage_ai/frontend/components/Triggers/utils.ts
mage_ai/frontend/utils/date.ts

- The cron expressions for triggers with custom interval schedules are still being used to schedule pipeline runs in UTC time, even though a user may have enabled the `display_local_timezone` setting. This caused some confusion since a user may enter a cron expression like `0 10 * * 1-5` (human readable: "At 10:00 AM, Monday through Friday") and expect their pipeline to run based on local time. However, the pipeline would run at 10 AM UTC.
- The local timezone setting displays dates in local time all on the frontend, so in order to make the cron expressions match up with local time, this PR converts the local cron expression to a UTC cron expression in the background and continues to store the cron expressions in the database the same as before, but now users don't need to do any time …

[jk] Support local timezone for cron expressions

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/templates/main/metadata.yaml
mage_ai/data_preparation/templates/repo/metadata.yaml

Prioritize using remote_variables_dir for variable manager.
```yaml
variables_dir: /home/src/mage_data
remote_variables_dir: s3://mage-feature-sets/mage_variables/
```
The block output variables are stored in s3 bucket. Other local data (cache, secret key, local database) are stored in local variables_dir.
cc:

[xy] Prioritize using remote_variables_dir for variable manager.

---

mage_ai/api/middleware.py

So I was creating and updating sessions using the API. I noticed that while response bodies would contain error details, the actual HTTP status_code would still be OK 200. For easier error handling for adopters, I desired to see actual 401 'token expired' http responses.
Error responses should therefore use the correct status_code according to `api/errors.py` which can be done in the existing api middleware class.
1. I updated the code in this PR, at every point where an API http response is set to error, the corresponding status_code is also set on the response.
2. I set the `MAGE_ACCESS_TOKEN_EXPIRY_TIME` environment variable to a very short value (120) to trigger token expiration
3. I attempted API calls with the expired session token in the header. 
4. I observed the response …

fix: have api middlware set status codes if api key or oauth token error

---

mage_ai/api/policies/BlockPolicy.py
mage_ai/api/resources/BlockResource.py
mage_ai/api/resources/BlockRunResource.py
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
mage_ai/frontend/components/DependencyGraph/BlockNode/utils.ts
mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
mage_ai/frontend/interfaces/BlockRunType.ts
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py

- If stream is not parallel, sequentially run a stream and then run the next one after its done.
- Show all dynamic blocks
cc:

[td] If run in parallel is not on, sequentially run streams

---

mage_ai/shared/config.py

Allow users to customize the ECS config. The `load_extra_config` method is only used in the ECSConfig class right now.

[dy] Customize ecs config

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/orchestration/db/__init__.py
mage_ai/orchestration/db/models/utils.py
mage_ai/orchestration/db/utils.py
mage_ai/tests/orchestration/db/test_utils.py

Fixes https://github.com/mage-ai/mage-ai/issues/3307. The `urllib.parse` function doesn't work for some cases, so I wrote a custom function to parse the db connection url.
cc:

[dy] Fix postgres db connection url parsing

---

docs/design/data-loading.mdx
mage_ai/data_preparation/templates/constants.py
mage_ai/data_preparation/templates/data_exporters/duckdb.py
mage_ai/data_preparation/templates/data_loaders/duckdb.py
mage_ai/io/duckdb.py

This PR includes
- Add DuckDB loader and exporter
- Convert array type into text in duckdb
Loader template and loaded data:
Loader template and exported data:
Write Int array, String array, Json in duckdb
cc:

[xh] Add DuckDB loader and exporter

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx

- Make some minor changes to improve UX for bookmark values in data integration pipelines.
- Update explanations.
- Default to making the bookmark property values visible. 
- If user tries to save an empty bookmark value, it will be saved as `null` instead of an empty string. An empty string can cause syncing issues.
Update descriptions:

[jk] Bookmark values minor improvements

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/server/utils/output_display.py

The logger was not getting passed in as a keyword argument properly when executing upstream blocks from the notebook. This PR changes the execution code to include a logger as a keyword argument for the upstream blocks.
Also, pass in the logger win `block.run_tests`.

[dy] Fix passing in logger for alternative block execution methods

---

mage_ai/data_integrations/utils/scheduler.py
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/data_integration/mixins.py
mage_ai/data_preparation/models/block/data_integration/schema.py
mage_ai/data_preparation/models/block/data_integration/utils.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/frontend/components/Logs/Table/index.tsx
mage_ai/server/websocket_server.py
mage_ai/shared/environments.py

- Use Python and decorators to dynamically build destination blocks.
- Control what upstream blocks pass its output data or catalog to destination block as inputs for the decorated functions
```python
import json
@data_integration_destination
def destination(input_only, _, _sp, **kwargs):
return input_only
@data_integration_config
def config(*args, **kwargs):
return dict(
database='dangerous',
host='host.docker.internal',
password='postgres',
port=5432,
schema='mage_destination_blocks',
username='postgres',
)
@data_integration_catalog
def catalog(_, tup, source_postgresql, **kwargs):
d, c = source_postgresql
print([sd['stream'] for sd in c['streams']])
print(len(d))
for da in d:
print(da['columns'], len(da['rows']))
api_data, api_data_catalog = tup
columns_by_type = {}
for col, …
```

[td] Support Python destination blocks

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/data_integration/mixins.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/data_preparation/models/pipeline.py

Update the block directory name that is under the pipeline directory.
This block directory contains the catalog.json. For example:
pipelines/[pipeline_uuid]/[block_uuid]/catalog.json
- Interpolate upstream block output in YAML files
- Add parsing logic to extract value from variables in YAMLfiles
```yaml
config:
database: dangerous
host: host.docker.internal
password: "{{ variables('PASSWORD_WTF') }}"
port: 5432
schema: mage
username: postgres
source: >
{{ variables(
'SOURCE_WTF',
'lambda x: x.split(",")[1]'
) }}
```
```yaml
config:
database: dangerous
host: host.docker.internal
password: "{{ variables('PASSWORD_WTF') }}"
port: 5432
schema: mage
username: postgres
source: >
{{ block_output('divine_glitter', 'lambda x: x[1]') }}
```
cc:

[td] Renaming block will move the catalog.json and all other files

---

mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/bigquery/utils.py
mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/destinations/sql/utils.py
mage_integrations/mage_integrations/tests/destinations/test_base.py

Speed up bigquery destination in data integration pipeline.
* Only run schema creation command, table creation and alter commands for the first subbatch in destination
* Allow maximum batch size to be configured via `maximum_batch_size_mb` key in destination config
* Remove redundant records loop through in bigquery destination when `use_batch_load` is true
* Speed up exporting datetime column to BigQuery by converting records to dataframe and use `pd.to_datetime` to convert datetime column
* User PARQUET format for most of the cases
* Use CSV format when there're json columns: https://stackoverflow.com/questions/76983677/json-format-not-supported-when-using-load-table-from-dataframe-bigquery
* Use load_table_from_json when there's ARRAY type since REPEATED mode is not supported in CSV …

[xy] Speed up bigquery destination in data integration pipeline.

---

mage_ai/ai/generator.py
mage_ai/ai/generator_cmds.py
mage_ai/ai/llm_pipeline_wizard.py

This PR does several refactoring:
(1) Replace several `async_llm_inferene` functions with generic `__async_llm_call`. All those `async_llm_inferene` just passes different params and prompt template. They are duplicating same langchain call to LLM. Instead, I now pass different params within a dict. So generic `__async_llm_call` function can be reused.
(2) Rename function following the API function name. So they are consistent.
Run the command before the refactor and after the refactor. Record the result in the `Refactor code evaluation` tab in https://docs.google.com/spreadsheets/d/1vp0UB6EqM3vnY4f0hYV0nB36X7ngiRIVZZU4FFcybH0/edit#gid=975603530
cc:

[xh] Refactor: use generic function to call LLM avoid code duplication

---

mage_ai/frontend/components/shared/Table/index.style.tsx
mage_ai/frontend/pages/pipelines/index.tsx

- Fix bug that caused issues with selected pipeline rows when clearing the search query input.
Before (multiple pipeline rows appear "selected", even though only 1 row should be allowed to be selected):
After (bug no longer appears):

[jk] Fix updating of pipelineRowsSorted when clearing search query

---

mage_ai/services/aws/emr/config.py

Allow configuring core instance count for EMR cluster
```yaml
emr_config:
master_instance_type: 'r5.4xlarge'
master_spark_properties:
spark.driver.memory: 400M
spark.executor.cores: '8'
slave_instance_count: 2
slave_instance_type: 'r5.4xlarge'
slave_spark_properties:
spark.driver.memory: 400M
spark.executor.cores: '8'
```
cc:

[xy] Allow configuring EMR cluster spark properties

---

mage_ai/api/resources/PipelineResource.py
mage_ai/frontend/components/PipelineDetailPage/constants.ts
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/components/shared/Table/Toolbar/constants.ts
mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/orchestration/db/models/schedules.py

- Retry all of a pipeline's incomplete block runs from the UI. This includes all block runs that do not have `completed` status.
- Users may not want to create a new pipeline run when retrying failed pipeline runs, so this allows users to keep the same pipeline runs but still retry the failed block runs without having to individually go into each pipeline run to do so.
Retry all incomplete block runs even if the pipeline runs are across diff pages (the failed blocks intentionally had an exception for testing purposes):
Retry all incomplete block runs (successfully completes):
"Retry all incomplete block runs" option from Actions menu in a pipeline's Pipeline Runs page:
Confirm dialogue before proceeding:

[jk] Bulk retry incomplete block runs

---

mage_ai/api/resources/BlockResource.py
mage_ai/api/resources/PipelineResource.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/constants.py
mage_ai/data_preparation/models/pipeline.py

FIx a bug in 0.9.28. `ModuleNotFoundError: No module named 'dbt.flags'`
This PR updates it to lazy import dbt block and library
cc:

[xy] Lazy import dbt block and library

---

mage_integrations/mage_integrations/sources/stripe/__init__.py

Removed the kwargs decorator (double asterisks) from the `params` argument sent to `StripeObject._request` in the `new_list` method that overrides Stripe's `ListObject.list` method. This was causing an "invalid keyword argument 'limit'" when running the Mage Stripe source ingestion block.
Spot tested locally (since this is a minor change [two characters] and there is no current tests for `mage_integrations.sources.stripe`.
Steps to reproduce test:
1. Open python in a terminal
2. Copy and paste imports, `new_list` definition, and `ListObject.list = new_list` statements into terminal
3. Make a list call to a Stripe endpoint like `stripe.Customer.list(api_key="<insert_api_key>", limit=100)`
4. Call should return successfully
cc:
@wangxiaoyou1993, @dy46, @johnson-mage, @tommydangerous

Fix invalid keyword argument error when requesting a list from Stripe

---

mage_ai/io/snowflake.py

Fix snowflake output column names. The snowflake block output uses column names `col_0`, `col_1`, etc. when table name is not specified, which causes many issues. This PR fixes it by fetching the column names from the cursor description.
Reference: https://stackoverflow.com/a/69589670
python block
sql block
cc:

[xy] Fix snowflake output column names.

---

mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx

- Allow `Created at` and `Started at` columns to be sorted on Block Runs table. Previously, only the `Status`, `Block`, and `Completed at` columns were sortable.

[jk] Add sortable block run columns

---

mage_ai/frontend/components/PipelineRun/MetricsSummary/index.tsx
mage_ai/frontend/components/PipelineRun/Widget/index.tsx
mage_ai/frontend/components/PipelineRun/shared/constants.ts
mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/frontend/pages/overview/index.tsx

- Even with the `display_local_timezone` setting enabled, the metrics on the Overview page are still calculated based on pipeline run creation dates in UTC time. This PR adds tooltips to the Overview page to make it clear that the metrics and pipeline run counts are still based on UTC time.
- Disable inputting OpenAI API key on mage demo app (demo.mage.ai).

[jk] Clarify components based on UTC time in Overview page

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/data_preparation/models/pipeline.py

Support interpolating pipeline variables in streaming configs.
Also pass the global vars to transformer kwargs,
cc:

[xy] Support interpolating pipeline variables in streaming configs.

---

mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py
mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/delta_lake/base.py
mage_integrations/mage_integrations/destinations/google_cloud_storage/__init__.py

`export_batch_data` wasn’t updated everywhere to accept the `tags` keyword argument.
Failing in S3 destination.

[td] Fix export_batch_data not accepting tags as a kwarg

---

mage_ai/data_preparation/shared/secrets.py
mage_ai/orchestration/db/models/secrets.py
mage_ai/tests/data_preparation/shared/test_secrets.py

In case there is extra whitespace in the key or uuid files for some reason, we should be able to still retrieve the secrets.
cc:

[dy] Handle secret key and uuid whitespace

---

mage_ai/data_preparation/models/block/__init__.py

The output of a block was not normalized to an pandas.DataFrame and wasn't checked whether this df is empty. Which caused errors in upstream blocks, which output wasn't already an df.
I have normalized the output and made sure only non empty df are materialized.
cc: @wangxiaoyou1993 @tommydangerous

Fix materializing upstream outputs for dbt

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/shared/Table/Toolbar/constants.tsx
mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
mage_ai/frontend/interfaces/PipelineRunType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

- Add `Started at` column to Pipeline Runs table.
- Add search input for searching pipeline run variables on Pipeline Runs page for individual pipelines.
"Started at" column included in Pipeline Runs table:
Searching for substring in key or value in pipeline runs' variables:

[jk] Pipeline runs table (for individual pipelines) updates

---

mage_ai/api/resources/BlockResource.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dynamic.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/variable_manager.py
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/Logs/Detail/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

No matter how levels down a dynamic child is, reduce the results.
cc:

[td] Reduce dynamic child block at any level

---

mage_integrations/mage_integrations/destinations/oracledb/__init__.py
mage_integrations/mage_integrations/destinations/postgresql/__init__.py
mage_integrations/mage_integrations/destinations/redshift/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/sources/oracledb/__init__.py
mage_integrations/mage_integrations/sources/postgresql/__init__.py

Fix memory leak in data integration pipelines.
For SQL sources and destinations, close all the connections that weren't closed.
Test data integration pipelines with the following source and destination locally
cc:

[xy] Fix memory leak in data integration pipelines.

---

docs/orchestration/triggers/configure-triggers-in-code.mdx
docs/orchestration/triggers/schedule-pipelines.mdx
mage_ai/data_preparation/models/triggers/__init__.py
mage_ai/frontend/interfaces/PipelineScheduleType.ts
mage_ai/orchestration/airflow.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/tests/orchestration/db/models/test_schedules.py

User request.
Add `@always_on` schedule interval for scheduled triggers. Always on schedules will trigger the new pipeline run as soon as the latest pipeline run is completed. Basically, it should always have 1 pipeline run in progress at all times.
I also replaced schedule interval strings with constants in this PR.
cc:

[dy] Add always on schedule interval

---

mage_ai/streaming/sources/kafka.py

Addition of SASL_PLAINTEXT security protocol support for Apache Kafka Streaming block.
Motivation: Required SASL_PLAINTEXT connectivity to Apache Kafka
Dependencies: None
K8s Deployment on AWS
Instructions:
* Requires Bitnami Helm Apache Kafka Helm Chart deployed on K8s cluster
* MageAI configuration using K8s yaml files (can provide separately)

Apache Kafka - SASL_PLAINTEXT

---

mage_ai/orchestration/db/__init__.py

Change `search_path` for a role in a database instead of for the entire database. 
cc:

[dy] Update search_path command

---

mage_ai/data_preparation/models/block/dbt/block.py
mage_ai/data_preparation/models/block/dbt/block_sql.py
mage_ai/data_preparation/models/pipeline.py

Fix auto generating `mage_sources.yml` for dbt upstream blocks.
The `mage_sources.yml` wasn't auto generated after adding a python block as upstream.
cc:

[xy] Fix auto generating mage_sources.yml for dbt upstream blocks

---

mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/pages/pipelines/index.tsx

- Remove the pipeline statuses `retry` and `retry_incomplete_block_runs` from the pipeline filters.
- Fix ordering of sorted pipeline rows when applying filters.
- Fix cutoff pipeline context menu.
Before (pipeline groupings were sometimes incorrect):
After (fixed pipeline groupings):
Reposition context menu at bottom of page:

[jk] Pipelines list fixes

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/streaming/sinks/kafka.py
mage_ai/streaming/sources/kafka.py

Support Kafka SASL_SSL SCRAM-SHA-512 authentication and add an option to use cafile. 
Ref: https://stackoverflow.com/questions/57290708/setting-python-kafkaproducer-sasl-mechanism-property
```yaml
security_protocol: "SASL_SSL"
sasl_config:
mechanism: "SCRAM-SHA-512"
username: username
password: password
ssl_config:
cafile: "pemfilename.pem"
```
cc:

[xy] Support Kafka SASL_SSL SCRAM-SHA-512 authentication.

---

mage_ai/data_preparation/models/block/sql/druid.py
mage_ai/data_preparation/models/block/sql/utils/shared.py

Throw exception in sql blocks if there is a jinja variable in the sql block that is not passed in when interpolating the variables. 
Fixes issue https://github.com/mage-ai/mage-ai/issues/3288
cc:

[dy] Throw exception if a variable is not defined in jinja for sql blocks

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx

Don’t show images from output with empty data.
Fixes:
cc:

[td] Don’t show empty images

---

mage_ai/services/aws/ecs/config.py

Made a simple change that makes any ECS task executor automatically inherit the tags configured in the task definition. Previously there was no way of doing that, or define tags for the executors in general.
cc:

Propagate tags of ECS task definition to task executors

---

mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx

- Include `event_variables` in variables search for pipeline runs page for individual pipelines. Previously, the search only included the `variables` property of pipeline runs.
- locally

[jk] Also search pipeline run event_variables

---

mage_ai/frontend/components/BlockLayout/index.tsx

Made text changes to the empty state message of the dashboard. Fixed a typo and simplified message.
Fixed typo and tense:
- _Old:_ "Get started with a recommended set OF freely define your own." 
- _New:_ "Start with a recommended set OR freely define your own."
Simplified first sentence
- Made more distinct from H1
Simple text change, reviewed in code.

Fixed typo and simplified text for empty dashboard

---

mage_ai/api/policies/BlockPolicy.py
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx

- Show `YAML` in "Language" row of ConfigureBlock modal when adding new yaml block (it wasn't appearing in streaming pipeline data loader/exporter blocks or DBT yaml blocks).
- Update block policy for creating/deleting blocks.
Missing language in modal:
Block policy errors when creating and deleting blocks:

[jk] YAML block language display

---

mage_ai/api/policies/RolePermissionPolicy.py
mage_ai/api/presenters/PermissionPresenter.py
mage_ai/api/presenters/RolePermissionPresenter.py
mage_ai/api/presenters/RolePresenter.py
mage_ai/api/resources/RolePermissionResource.py
mage_ai/authentication/permissions/constants.py
mage_ai/orchestration/db/migrations/README.md
mage_ai/orchestration/db/models/oauth.py

~~Add an association table for roles and permissions so that permissions can belong to many roles~~
- ~~role_id~~
- ~~permission_id~~
- ~~user_id~~
- ~~Add new association on Role~~
- `~~role_permissions = relationship('Permission', secondary='role_permission', back_populates='roles')~~`
- ~~Permission~~
- `~~roles = relationship('Role', secondary='role_permission', back_populates='role_permissions')~~`
- ~~Read~~
- ~~role_id~~
- ~~permission_id~~
- ~~user_id~~
- ~~id~~
- ~~created_at~~
- ~~updated_at~~
- ~~Create~~
- ~~Write~~
- ~~role_id~~
- ~~permission_id~~
- ~~user_id~~
- ~~Delete~~
- ~~Roles~~
- ~~Add `role_permissions`~~
- ~~Permissions~~
- ~~Add `roles`~~
cc:

[td] Add role permissions API

---

mage_ai/data_preparation/sync/git_sync.py
mage_ai/tests/data_preparation/sync/test_git_sync.py

In a previous PR, I made a change to preserve the `.preferences.yaml` file between git sync operations. However, it's possible that the file won't exist in some cases, so this PR adds a check for that.
cc:

[dy] Fix git config preserve when .preferences.yaml file doesn't exist

---

mage_ai/api/policies/InteractionPolicy.py

Fixes bug when trying to create interaction. The UUID is the file path and name.
cc:

[td] Allow writing of interaction UUID on create

---

docs/integrations/databases/MicrosoftSQLServer.mdx
mage_ai/io/druid.py
mage_ai/io/mssql.py
mage_ai/io/postgres.py
mage_ai/io/sql.py

Speed up io mssql export method.
pyodbc library is slow on bulk inserting rows.
Tested using pyodbc + fast_executemany=True option, the performance didn't improve a lot.
Tested using sqlalchemy + fast_executemany=True + df.to_sql, the performance drastically improved.
Original time (pyodbc): 120s
Use sqlalchemy engine (fast_executemany=True) + df.to_sql: 20s
cc:

[xy] Speed up io mssql export method

---

mage_ai/orchestration/db/models/oauth.py

Only create the first 4 permissions by default since the other permission access is for when requiring user permissions.
cc:

[td] Only create 4 default permissions

---

mage_ai/frontend/oracle/components/Markdown/index.tsx
mage_ai/frontend/package.json
mage_ai/frontend/yarn.lock

Previously, Mage's markdown blocks only supported images via this format:
```
```
This PR supports `<img>` elements with custom sizes in Markdown blocks ([Airtable Task](https://airtable.com/applEuqJsK4zF5yJK/tbl5bIlFkk2KhCpL4/viwCmaGgcnwD9IqOM/recMUKSfAtQMaj4Rj?blocks=hide)) by providing `width` and `height` attributes like so:
```
```
We achieved this support by using the [`rehype-raw`](https://github.com/rehypejs/rehype-raw) plugin, which supports HTML embedded inside markdown. You can see the `react-markdown` doc about using this plugin [here](https://www.npmjs.com/package/react-markdown#appendix-a-html-in-markdown).
> [rehype-raw](https://github.com/rehypejs/rehype-raw) can handle the raw embedded HTML strings by parsing them into standard hast nodes (element, text, etc). This is a …

[ac] Add rehype-raw plugin to Markdown

---

mage_integrations/mage_integrations/sources/mysql/__init__.py

Fix MySQL source int comparison.
Close: https://github.com/mage-ai/mage-ai/issues/3228
Reference
* https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html
cc:

[xy] Fix MySQL source int comparison.

---

mage_ai/api/policies/BackfillPolicy.py

- Backfills were not appearing in `/pipelines/[pipeline_uuid]/backfills` page due to policy issue.
- Confirmed backfills appear in table on `/pipelines/[pipeline_uuid]/backfills` page.

[jk] Update Backfill policy

---

mage_ai/api/middleware.py
mage_ai/api/policies/StatusPolicy.py
mage_ai/api/presenters/StatusPresenter.py
mage_ai/api/resources/StatusResource.py
mage_ai/server/api/base.py
mage_ai/server/api/v1.py
mage_ai/server/server.py

Added a `with_activity_details` format to return activity details for the server. This will be used to determine if a workspace should terminated based on user configured settings.

[dy] Add activity to status endpoint when requested

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_ai/presenters/pages/loaders/pipeline_schedules.py

```
File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 34, in retry_func
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 512, in __execute_with_retry
return self._execute(
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 976, in _execute
self.block.run_tests(
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2259, in run_tests
test_function(*outputs)
TypeError: test_output() missing 1 required positional argument: 'output'
@test
def test_output(output, *args) -> None:
"""
Template code for testing the output of the block.
"""
assert …
```

[td] Fix block tests not getting output

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/DataTable/index.tsx

- App was crashing if there were empty strings in the column headers when rendering the DataTable component.
- Prevent table rendering if there are empty string column headers.
- Show warning in block output letting user know they should check their column headers for empty strings.

[jk] Check for empty column headers

---

docs/guides/blocks/markdown-blocks.mdx

This PR updates the [Mage Markdown blocks documentation](https://docs.mage.ai/guides/blocks/markdown-blocks) with the new `<img>` syntax support added in #3692.
cc: @johnson-mage @wangxiaoyou1993

[ac] Update Markdown blocks documentation with image support

---

mage_ai/streaming/sources/google_cloud_pubsub.py

i implement streaming pipeline using pubsub  but can't read the attributes from the pubsub message,
so i  set the attributes from pubsub message to dict when passing to handler
reference : https://cloud.google.com/python/docs/reference/pubsub/latest/google.cloud.pubsub_v1.subscriber.message.Message
cc:
@wangxiaoyou1993 @tommydangerous @dy46 @johnson-mage

Set attributes from pubsub message to handler dict

---

mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/tests/data_preparation/models/block/sql/utils/test_shared.py

Fix extracting update statement from sql.
When the UPDATE command uses alias for the table, the UPDATE statement wasn't extracted properly.
cc:

[xy] Fix extracting update statement from sql.

---

mage_ai/data_preparation/models/triggers/__init__.py
mage_ai/frontend/interfaces/PipelineScheduleType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

- Display error popup if trigger in code has syntax error for cron expression. Note that this checks if the cron syntax is invalid, not if the `triggers.yaml` config file has proper yaml syntax. For example, `schedule_interval: */15 * * * *` may not be parsed correctly as yaml because `*/15 * * * *` requires quotes around it.

[jk] Cron expression syntax err display for triggers in code

---

mage_ai/frontend/components/Backfills/Table/index.tsx
mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/Triggers/Table.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/frontend/utils/date.ts

Previously, when you hovered over a datetime in a table, we would display a tooltip with the corresponding UTC time:
This PR updates the tooltip to instead show the amount of time that has elapsed between the datetime and now based on the following logic ([Airtable Task](https://airtable.com/applEuqJsK4zF5yJK/tbl5bIlFkk2KhCpL4/viwCmaGgcnwD9IqOM/recUepW8SZxtgaFn3?blocks=hide)):
* If elapsed time >= 1 year, display `X year(s) ago`
* If elapsed time >= 1 month, display `X month(s) ago`
* If elapsed time >= 1 day, display `X day(s) ago`
* If elapsed time >= 1 hr, display `X hr(s) Y min(s) ago`
* If elapsed time < 1 hr, display `X min(s) ago`
Note that the current implementation always rounds down. If 11 months and 27 days have passed, we show `11 months ago`. In this case, Kai and I decided …

[ac] Display elapsed time on datetime hover rather than UTC time

---

mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.style.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx

- If there were too many items in the flyout menu, it would extend beyond the view of the window and make scrolling it an unideal UX. This issue was apparent in the standard pipeline editor for data integration sources and destinations when adding a new block.
- This PR sets a height on the long list of items in the flyout menu and makes it scrollable, and also repositions the flyout submenu so the items are within view.
Before (excessively long menu):
After:

[jk] Flyout menu overflow

---

mage_ai/api/policies/mixins/user_permissions.py
mage_ai/authentication/permissions/constants.py
mage_ai/frontend/components/Permissions/PermissionDetail.tsx
mage_ai/frontend/components/Roles/RoleDetail.tsx
mage_ai/frontend/components/users/UserDetail.tsx
mage_ai/tests/api/endpoints/test_variables.py
mage_ai/tests/api/policies/permissions/mixins.py
mage_ai/tests/api/policies/permissions/test_base_policy_with_permissions.py
mage_ai/tests/api/policies/permissions/test_permissions_with_entity_id.py

If a permission has an entity ID, then use the permissions only on that entity.
cc:

[td] Validate permissions for specific entity IDs

---

mage_ai/data_preparation/templates/data_integrations/utils.py
mage_ai/shared/strings.py
mage_integrations/mage_integrations/sources/twitter_ads/__init__.py

1. Couchbase (python, yaml) - 'NoneType' object has no attribute 'items'
2. Datadog (python, yaml) - float() argument must be a string or a real number, not 'dict'
3. Google ads (python, yaml) - float() argument must be a string or a real number, not 'list'
4. Sftp (python, yaml) - float() argument must be a string or a real number, not 'list'
5. Twitter ads (python, yaml) - 'NoneType' object has no attribute 'items'
Except for Couchbase (libssl issue), other sources can be correctly loaded with the fix.
cc:

[xy] Fix loading data integration sources.

---

mage_ai/data_preparation/models/block/dbt/block_sql.py
mage_ai/data_preparation/models/block/dbt/dbt_cli.py
mage_ai/data_preparation/shared/secrets.py
mage_ai/tests/data_preparation/models/block/dbt/test_block_sql.py

Fix adding dbt block with mage_secret_var.
When using syntax `{{mage_secret_var('secret_var_name')}}` in the profiles.yml, Mage throws exception on adding new dbt block.
> Hi
> We recently attempted to upgrade from 0.9.8 to 0.9.34 (big gap as there was an connection string issue preventing us updating) and we now get an error when attempting to add DBT models to a pipeline: Runtime Error Could not run dbt existing DBT pipelines continue to run. From the stack trace the error is:
> dbt.exceptions.DbtProfileError: Runtime Error
>   Compilation Error
>     Could not render {{mage_secret_var('insights-db-database')}}: 'mage_secret_var' is undefined
> mage_secret_var is working when pipelines are executed, it's only adding a new DBT block that is causing this.
> 
This PR fixes this issue by …

[xy] Fix adding dbt block with mage_secret_var.

---

mage_ai/orchestration/pipeline_scheduler.py

When setting the `remote_variables_dir` to a s3 bucket, the pipeline scheduler fails to schedule data integration pipeline due to the error below
This PR excludes the block objects from the process args so that they don't need to be pickled when enqueueing the job.
cc:

[xy] Fix botocore library pickle error in pipeline scheduler.

---

mage_integrations/mage_integrations/sources/postgresql/__init__.py

The method is `close_connection` but the code is invoking `close`.

[td] Incorrect method call on PostgreSQL close connection

---

mage_integrations/mage_integrations/connections/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/bigquery/README.md
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/sources/bigquery/README.md
mage_integrations/mage_integrations/sources/bigquery/__init__.py

Allow specifying credentials info in bigquery source and dest.
Example source config
```
credentials_info:
type: service_account
project_id: project-id
private_key_id: 123456789abcdefg
private_key: |
-----BEGIN PRIVATE KEY-----
keydata
-----END PRIVATE KEY-----
client_email: test@projet-id.iam.gserviceaccount.com
client_id: "123456789"
auth_uri: https://accounts.google.com/o/oauth2/auth
token_uri: https://oauth2.googleapis.com/token
auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
client_x509_cert_ur": url
dataset: test_dataset
```
cc:

[xy] Allow specifying credentials info in bigquery source and dest.

---

mage_ai/api/policies/BlockPolicy.py

- Fix block policy issue preventing "Pipelines using this block" from being listed in block's settings.
- Locally

[jk] Update block policy

---

mage_ai/api/policies/BasePolicy.py
mage_ai/settings/__init__.py
mage_ai/tests/api/policies/test_base_policy.py

the `DISABLE_NOTEBOOK_EDIT_ACCESS` variable was not working properly if user authentication was not enabled.
cc:

[dy] Fix DISABLE_NOTEBOOK_EDIT_ACCESS variable

---

mage_ai/data_preparation/storage/gcs_storage.py
mage_ai/tests/data_preparation/storage/test_gcs_storage.py

This MR fixes Google Cloud Storage listdir so it to doesn't list all path objects recursively (it list only depth 1).
This bug impacts running pipelines with multiple blocks with GCS as its block storage.

[BUG] GCS listdir so it doesnt go recursively listing objects

---

mage_ai/api/resources/GitBranchResource.py
mage_ai/api/resources/GitCustomBranchResource.py

Hide `mage-repo` remote in the version control app, and throw exception if a user tries to create the `mage-repo` remote.
cc:

[dy] Hide mage-repo remote

---

mage_ai/frontend/components/Backfills/Detail/index.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/shared/Table/constants.ts
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx

This PR addresses the following user feedback:
>  I often want to view the "Run details" tab for multiple runs, and clicking each individual run's row is cumbersome. Would love to be able to just use the UP or DOWN arrow to iterate through them quickly to find the run that I'm after.
When you're on a page with a pipeline runs table and rows are selectable, you can click on a row to select it. Once a row is selected, you can use the keyboard up arrow (↑) to navigate to the previous run and the keyboard down arrow (↓) to go to next run in the table on the current page. 
* If the first run is selected and you click the ↑ arrow, we loop to the last run in the table on the current page.
* If the last run is selected and you click the ↓ arrow, we loop to the first run in the table on the …

[ac] Add up/down arrow keyboard shortcut for navigating b/w pipeline runs

---

mage_integrations/mage_integrations/destinations/redshift/utils.py

Extend the column type mapping for the Redshift data integration destination by adding support for the [TIMESTAMPTZ](https://docs.aws.amazon.com/redshift/latest/dg/r_Datetime_types.html#r_Datetime_types-timestamptz) type.
Created a new Redshift cluster and a new data integration pipeline that retrieves data from an external API and stores the records in Redshift.
Following statement was executed (extracted from logs)
```sql
CREATE TABLE IF NOT EXISTS mage.api (id VARCHAR(255), last_updated TIMESTAMPTZ, _mage_created_at TIMESTAMPTZ, _mage_updated_at TIMESTAMPTZ, CONSTRAINT uniquemage_api_id UNIQUE (id))
```
Screenshot of the generated table schema and exported content

Redshift: Use TIMESTAMPTZ column type for datetimes

---

mage_ai/io/mssql.py
mage_ai/io/mysql.py
mage_ai/io/postgres.py
mage_ai/io/trino.py

Fix exception of exporting dataframe to Postgres when one column's type is numpy.ndarray
```
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type json
DETAIL:  Token "'" is invalid.
CONTEXT:  JSON data, line 1: ['...
COPY exam_diag, line 1, column malformations: "['aaaaaa' 'bbbbbbb']"
```
Serialize np.ndarray before exporting to postgres, mysql, mssql and trino
cc:

[xy] Serialize np.ndarray before exporting to postgres.

---

docs/integrations/databases/Redshift.mdx
mage_integrations/mage_integrations/destinations/redshift/__init__.py

* Update Redshift doc to clarify how to specify host for Redshift Serverless
* Fix Redshift Servereless destination in data integration pipeline
Close: https://github.com/mage-ai/mage-ai/issues/2754
```yaml
database: dev
host: workgroup.account.region.redshift-serverless.amazonaws.com
password: password
port: 5439
region: us-west-2
schema: public
user: username
```
cc:

[xy] Support Redshift Serverless 

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/package.json
mage_ai/frontend/utils/date.ts
mage_ai/frontend/yarn.lock

This PR adds a new `Execution Time` column in the Pipeline runs table, which displays how long it took each of the pipelines to run ([Airtable](https://airtable.com/applEuqJsK4zF5yJK/tbl5bIlFkk2KhCpL4/viwCmaGgcnwD9IqOM/rec7be6rwQDozAkU9?blocks=hide)).
The execution times are displayed in the first matching time format:
* If execution time ≥ 1 week, display `> 1 week`
* If execution time ≥ 1 day, display in the `d,HH:mm:ss.SS` format (e.g. `2d,12:04:35.12`)
* If execution time < 1 day, display in the `HH:mm:ss.SS` format (e.g. `12:04:35.12`)
When you hover over an execution time, the tooltip displays the execution time in a very specific, human-readable format and could include years / months / weeks / days / hours / minutes / seconds / milliseconds depending on the duration. We use the …

[ac] Add total execution time to Pipeline Runs table

---

mage_ai/orchestration/notification/sender.py
mage_ai/services/slack/slack.py
mage_ai/tests/orchestration/notification/test_sender.py

This PR improves the Slack Notification layout using Slack API Blocks.
I've created a standard "example" project (mage init + mage start) with a Slack connection.
I also supplied an example formated Slack message to the project metadata, as follows:
```yaml
alert_on:
- trigger_failure
- trigger_passed_sla
message_templates:
failure:
title: ":x:  Failed to execute pipeline {pipeline_uuid}"
details: >
*Execution time*: {execution_time}\n
*Pipeline URL*: {pipeline_run_url}\n
*Trigger name*: {pipeline_schedule_name}\n
slack_config:
webhook_url: "{{ env_var('SLACK_WEBHOOK_URL') }}"
```
Then I created a pipeline that raises a `ValueError` on purpose to trigger the Slack notification on failure.
The Slack notification output:
Note: I've added `title` as a variable to be used …

Improved Slack notification design

---

mage_ai/cli/main.py

When project's metadata.yaml file uses the `mage_secret_var` syntax, the job using k8s executor fails to execute due to exception:
```
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/repo_manager.py", line 70, in __init__
config_file = Template(f.read()).render(
File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 46, in top-level template code
File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py", line 118, in func_with_rollback
File …
```

[xy] Initialize db_connection session before interpolating repo config.

---

mage_ai/frontend/components/ServerTimeDropdown/ServerTimeButton.tsx
mage_ai/frontend/components/ServerTimeDropdown/index.style.tsx
mage_ai/frontend/components/ServerTimeDropdown/index.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx

Previously, we would show the current time button in the top right of the app header with a dark background by default (#3785):
This PR makes a slight style adjustment such that the button has a transparent background by default. When you hover over the button OR if the dropdown menu is open, the button displays a dark background. This was a design request by Kai!
https://github.com/mage-ai/mage-ai/assets/8130751/2bee93b3-da72-49e4-9152-8625264af4b4
cc:
@johnson-mage

[ac] Make current time button transparent by default

---

mage_ai/frontend/components/Backfills/Detail/index.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/shared/Table/constants.ts
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx

PR #3815 introduced a bug where other keyboard shortcuts (e.g. `cmd+R` to refresh the page or `opt+cmd+I` to open the browser console) and text input abilities (e.g. `Search pipeline run variables` on the Pipeline Runs page) were disabled. This was the result of the `event.preventDefault(...)` in the `registerOnKeyDown(...)` function, which disables key press actions as well. 
The original intent of using `event.preventDefault(...)` was to prevent the default auto-scrolling behavior in response to the pressing the up/down arrow keys:
https://github.com/mage-ai/mage-ai/assets/8130751/5acbd501-ade0-4f18-a0de-6b8daed2d6f1
This PR fixes this bug! The table nav behavior is now as follows:
* When no row is selected, pressing the up/down arrow keys will trigger the default auto-scrolling …

[ac] Fix disabled keyboard shortcuts due to Pipeline Runs table keyboard nav

---

Dockerfile

Fix libodbc conflicts in Dockerfile.
Resolve the conflicts between libodbc1 (from msodbcsql18) library and libodbc2 library (from freetds-bin)
Error: https://github.com/mage-ai/mage-ai/actions/runs/6635841565/job/18027399703
cc:

[xy] Fix libodbc conflicts in Dockerfile.

---

mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
mage_ai/frontend/components/Sidekick/GlobalVariables/Secrets.tsx
mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx
mage_ai/frontend/components/Sidekick/GlobalVariables/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/context/shared/utils.ts

There was a bug on the Pipeline Runs page where after clicking the "Execute Pipeline" or "Cancel Pipeline" button, you could no longer save a code block via the `cmd + s` shortcut ([Airtable task](https://airtable.com/applEuqJsK4zF5yJK/tbl5bIlFkk2KhCpL4/viwCmaGgcnwD9IqOM/recdr4j0pXLg8tAFc?blocks=hide)). It would instead bring up the default system file save dialog:
https://github.com/mage-ai/mage-ai/assets/8130751/5aafe36b-4825-4734-9033-094aa5a2f526
The issue was that in `SidekickContainerStyle`, we disabled keyboard shortcuts in `onFocus` but the `onBlur` event was never triggered when the sidekick focus was lost. This is a result of a `div` not being a focusable element by default. This PR fixes this issue!
**Pipeline Execution** …

[ac] Fix save block functionality after pipeline execution

---

dev.Dockerfile

Similar with the fix for production Dockerfile https://github.com/mage-ai/mage-ai/pull/3840, this PR fixes the libodbc conflicts for dev Dockerfile.
cc:

[xy] Fix libodbc conflicts in dev.Dockerfile.

---

mage_ai/api/policies/BasePolicy.py
mage_ai/tests/api/policies/test_base_policy.py

Before, if a user was a owner, the `authorize_query` check would automatically return true. We need to perform the policy checks if `DISABLE_NOTEBOOK_EDIT_ACCESS` is enabled, so I changed the condition to check for that environment variable.
cc:

[dy] Update authorize_query check

---

mage_ai/frontend/components/FileBrowser/index.tsx

Moved the menu up whenever it overflows off the screen. Also moved it a bit to the right, for good measure.
Resolves #3800.
- Before
- After

[Fix] Reposition file browser context menu

---

mage_ai/frontend/components/ServerTimeDropdown/ServerTimeButton.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx

Kai and I were chatting about how the shared app header had inconsistent styling (e.g. button sizing, item placements):
So we came up with a couple minor styling improvements!
* Re-ordered the items on the right side of the app header: Github actions button, current time display, version display, version update button, Live Chat button
* Standardized the Github actions button, current time display, and version display to be 12px Fira codemonospace 
* Standardized the version update button and Live Chat button to be 14px Roboto
* Made the button styling more minimalistic + cleaner and shortened the version update button text
* Hovering over the Github actions button shows the full branch name
* Hovering over the version update button shows a more descriptive action: "Update version to …

[ac] Improve app header styling

---

mage_ai/api/policies/BlockPolicy.py
mage_ai/api/resources/BlockResource.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/Extensions/constants.ts
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Add block "Detach" feature, which lets user duplicate a block and remove any associations with other pipelines (would require to choose a new, unique block name). Feature is visible for blocks with shared pipelines.
- Supported for python, sql, R, and data integration YAML blocks (not supported for dbt blocks).
With add-on blocks (conditional and callback) and upstrea/downstream dependencies:
Dep graph before detaching `custom_sql_block2_c2`:
Dep graph after detaching `custom_sql_block2_c2` (replaced with `custom_sql_block2_c2_copy`):

[jk] Detach block from shared pipelines

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/context/shared/utils.ts

In the Pipeline Runs table, you can click on a row to **highlight** it and open the sidekick with run details. You can also click on a row's checkbox (on the far left) to **select/deselect** it for performing actions on one or more rows. Previously, clicking on a row's checkbox both selected/deselected and highlighted the row.
This PR makes a few updates to how we highlight/select rows:
* When you click on a row's checkbox, we no longer highlight the row and only select/deselect it. We've also made a broader change to prevent a table row from being highlighted if the user clicked on an interactive element (e.g. `a`, `button`, `input`) in the row.
* We also add a new keyboard shortcut for selecting rows. If you hold the meta key (`Cmd` on Mac or `Ctrl` on Windows) and click on an …

[ac] Add `ctrl/cmd + click` keyboard shortcut for selecting pipeline run rows

---

mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx

Previously, the file browser context menu would be partially hidden in scenarios where the file browser area was too small to fit the full menu. This was because overflow was hidden in the file browser aside:
https://github.com/mage-ai/mage-ai/assets/8130751/91073d14-39f7-4688-ad97-5e4ca81990c5
This PR fixes this bug and makes sure that the file browser context menu is always fully visible within the viewport ([Airtable Task Pt. 1](https://airtable.com/applEuqJsK4zF5yJK/tbl5bIlFkk2KhCpL4/viwCmaGgcnwD9IqOM/recrnz90jwBp3lxJJ?blocks=hide)). The fix makes use of [React Portals](https://react.dev/reference/react-dom/createPortal) to render the context menu into a DOM node that exists outside the DOM hierarchy of the parent component, which has `overflow: hidden`.
Note: This is a one-off fix …

[ac] Make sure file browser context menu is always fully visible in the viewport when open

---

docs/integrations/observability/alerting-email.mdx
docs/integrations/observability/alerting-slack.mdx
mage_ai/orchestration/notification/sender.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/tests/orchestration/notification/test_sender.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

Close: https://github.com/mage-ai/mage-ai/issues/3802
When a pipeline fail due to Fail to initialize block runs, send the failure message to notification channels.
This PR also add the support to include the error message in notifications.
The error message includes the failed block uuids if there're any.
Custom template
Default template
Error message with failed block runs:
cc:

[xy] Send notification on block run intialization failure.

---

mage_ai/services/k8s/job_manager.py

Use `read_namespaced_job` instead of `read_namespaced_job_status` when getting k8s job status.
I check the response of `read_namespaced_job` and `read_namespaced_job_status` methods. The responses are the same. `read_namespaced_job` doesn't require the extra permissions of `jobs/status` resource.
Close: https://github.com/mage-ai/mage-ai/issues/3810
cc:

[xy] Use read_namespaced_job instead of read_namespaced_job_status.

---

mage_integrations/mage_integrations/sources/api/__init__.py

Support 'text/csv' response type in API source.
This PR also fixes converting dataframe to the list of records in API integration source.
The sync succeeded.
cc:

[xy] Support 'text/csv' response type in API source

---

docs/design/core-abstractions.mdx

Used the following doc for reference: https://docs.mage.ai/design/blocks
The documentation had incorrect number of block types and their names. Correcting the same via this change.
- [Check] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [Check] I have performed a self-review of my own code
cc:

[Documentation] Add correct types of blocks in core-abstractions.mdx

---

mage_ai/api/resources/PipelineResource.py

- When users switch the `python` kernel to `pyspark` and an error occurs, the pipeline `type` should not update from `python` to `pyspark`, but should revert back to `python`. This PR reverts the pipeline type when trying to update the kernel and an error occurs.
Before (pipeline type is updated):
After (pipeline type is reverted back to its original type):

[jk] Revert pipeline type when error occurs switching type

---

mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/CodeEditor/utils.ts

A user was running into an issue where the Code Editor was displaying the light theme on the initial load but not in subsequent refreshes:
This seems to be caused by either the Monaco theme failing to load OR the component mounting before the theme loaded. This PR attempts to fix this issue by moving the theme definition call into the `handleEditorWillMount` function, which is called before the editor is mounted. In the off chance that the Monaco custom theme doesn't load properly, we fallback to Monaco's default dark theme (`vs-dark`).

[ac] Fix Monaco editor theme

---

mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/context/shared/utils.ts

This PR adds the same keyboard shortcuts as Jupyter notebooks for inserting new scratchpad cells:
* If a block is selected and the user presses `a`, a new scratchpad cell is inserted above the selected block.
* If a block is selected and the user presses `b`, a new scratchpad cell is inserted below the selected block.
* If no block is selected or the user is typing in an input / text area, the `a` and `b` keyboard shortcuts do nothing.

[ac] Add keyboard shortcuts for inserting new scratchpad cell

---

mage_ai/data_preparation/models/block/integration/__init__.py

Fix pipeline LIST API performance.
Pipeline LIST API was slow on the Pipeline list page.
```
GET /api/pipelines?include_schedules=1
```
The slow performance is due to the bug in the data integration block `to_dict` method. When the data integration block calls `super().to_dict`, it didn't specify the keyword argument name in the method, which causes the `include_outputs` to be set to `True` and the block fetches the unnecessary output data.
This PR fixes this issue.
cc:

[xy] Fix pipeline LIST API performance.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.43.
I forgot to update to server/constants.py in the previous version bump [PR](https://github.com/mage-ai/mage-ai/pull/3913). and the same version can't be re-uploaded to pypi ([error](https://github.com/mage-ai/mage-ai/actions/runs/6778884913)).
Thus, just update the the version to 0.9.43.
N/A
N/A
cc:

[xy] Bump version to 0.9.43.

---

mage_ai/frontend/components/Backfills/Table/index.tsx

This PR adds colour code for pipeline backfills.

[Feat] Add colour code for pipeline backfills

---

mage_ai/orchestration/triggers/utils.py

- There was an infinite loop when triggering a pipeline via code if the pipeline run failed and the `check_status` setting was enabled and the `error_on_failure` setting was disabled. This PR causes the loop to end.
Before (infinite loop, had to cancel pipeline run to stop it):
After (pipeline run completed after triggered pipeline run failed):

[jk] Break while loop when not raising error on failure for pipeline triggered by code

---

mage_ai/data_preparation/models/block/global_data_product/__init__.py
mage_ai/orchestration/triggers/global_data_product.py
mage_ai/tests/orchestration/triggers/test_global_data_product.py

Instead of running global data products by directly running it on the webserver process, we create the pipeline schedule, pipeline run, and just turn the pipeline schedule active. This way, the scheduler will pick up the pipeline run and scheduler it in the scheduler process, so the unnecessary logs won't show up in the block output.

[dy] Update how global data products are run

---

mage_ai/frontend/components/Backfills/Table/index.tsx
mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
mage_ai/frontend/components/Triggers/Table.tsx
mage_ai/frontend/components/shared/Table/constants.ts

- The run status colors were not uniform across tables, so this PR makes them consistent. "Run status" is a catch-all term which includes backfill statuses, block run statuses, and pipeline run statuses. These status colors match the bar colors in the pipeline run chart in the project "Overview" page.
The status colors used are the following:
1. cancelled - yellow
2. completed - green
3. failed - red
4. inactive or N/A - grey
5. initial - white
6. running - blue
Triggers page:
Backfills page:
Block runs page:

[jk] Consistent run status colors across tables

---

mage_ai/cli/main.py
mage_ai/server/server.py
mage_ai/shared/constants.py

Allow getting instance type from environment variable so that we can simplify the configuration for web server and scheduler in helm chart: https://github.com/mage-ai/helm-charts/pull/28
The web server and scheduler are set correctly with the env vars.
cc:

[xy] Allow getting instance type from environment variable.

---

mage_ai/data_preparation/models/block/dbt/block_yaml.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/tests/data_preparation/models/block/dbt/test_block_yaml.py

A dbt block with a generic command with 2 upstream blocks and the following content:
```
--select models/example/"{{ variables('model1') }}".sql models/example/"{{ block_output(parse=lambda arr, _variables: arr[0][0]['model2']) }}".sql
--vars '{"test1": "{{ env_var("ENV") }}", "test2": "{{ variables('model1') }}", "test3": "{{ block_output(parse=lambda arr, _variables: arr[1]) }}", "test4": "{{ block_output('pastel_portal', parse=lambda arr, _variables: arr[2]) }}"}'
```
Produces this command:
```
dbt run \
--select models/example/my_first_dbt_model.sql models/example/my_second_dbt_model.sql \
--vars {"foo": 1, "model1": "my_first_dbt_model", "env": "dev", "execution_date": "2023-11-09T11:34:47.251412", "interval_start_datetime": "2023-11-09T11:34:47.251412", "event": {}, "configuration": …
```

[td] Interpolate variables and upstream block output in dbt commands

---

mage_ai/services/aws/ecs/config.py
mage_ai/tests/services/aws/ecs/test_config.py

Close: https://github.com/mage-ai/mage-ai/issues/3939
Support override assignPublicIp and enableExecuteCommand in EcsConfig
Example config
```yaml
ecs_config:
assign_public_ip: false
enable_execute_command: true
```
cc:

[xy] Support override assignPublicIp and enableExecuteCommand in EcsConfig

---

mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/tests/sources/api/test_api.py

Close: https://github.com/mage-ai/mage-ai/issues/3954
Clean the column correctly instead of just using the lower case when using batch load to export to Snowflake.
config
```yaml
...
disable_double_quotes: true
use_batch_load: true
```
The sync succeeded with the fix.
cc:

[xy] Clean column name when using batch load in Snowflake destination.

---

mage_ai/io/duckdb.py
requirements.txt
setup.py

Update duckdb version from 0.8.1 to 0.9.1
According to [the release notes](https://duckdb.org/2023/09/26/announcing-duckdb-090.html#breaking-sql-changes) there is 1 major breaking change, but we don't seem to be using structs anywhere in our code for now. We may need to let users know that we're bumping the version though in case it affects them.
cc:

[dy] Update duckdb version

---

mage_ai/api/resources/BackfillResource.py
mage_ai/frontend/components/Backfills/Detail/index.tsx
mage_ai/frontend/components/Backfills/Edit/index.tsx
mage_ai/frontend/components/Sidekick/utils.ts
mage_ai/frontend/components/Triggers/OverwriteVariables/index.tsx
mage_ai/frontend/components/Triggers/RunPipelinePopup/index.style.ts
mage_ai/frontend/components/Triggers/RunPipelinePopup/index.tsx
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_ai/frontend/utils/hash.ts

- Allow backfill variables to be updated via API requests. Resolves Github issue https://github.com/mage-ai/mage-ai/issues/3928.
- Add ability to overwrite runtime variables for pipeline runs created by backfills from the UI. The `Overwrite runtime variables` toggle must be enabled or the default pipeline variables will be used.
- Tested updating backfill variables through PUT requests using Insomnia.
- Updated backfill variables in the UI and confirmed the existing variables were overwritten when running the pipeline with the backfills.
Update backfill variables in UI:
Remove overwritten backfill variables in UI (e.g. if user had updated a backfill's variables but decides they no longer want to overwrite the pipeline's variables):
cc:

[jk] Update backfill variables

---

docs/guides/ai/ai-client.mdx

I noticed the code reference link is broken in the doc:
This PR is to fix it.
cc:
@wangxiaoyou1993 @dy46

[xh]Fix doc link reference

---

mage_integrations/mage_integrations/destinations/snowflake/__init__.py

Close: https://github.com/mage-ai/mage-ai/issues/3958
Serialize Snowflake dataframe dict column to json if column type is STRING.
Fix exception: 
cc:

[xy] Serialize Snowflake dataframe dict column to json if column type is string

---

.github/pull_request_template.md
mage_ai/frontend/components/Triggers/Edit/index.tsx

- It may be unclear how to add or edit runtime variables when editing a pipeline trigger, so this PR always shows the `Overwrite global variables` setting in the Trigger Edit page but disables it if the pipeline has no global variables and displays a link to add pipeline variables.
"Runtime variables" setting (bottom right) when there are no pipeline variables:
Previously, the "Runtime variables" section was empty if there were no pipeline variables:

[jk] Always show "Overwrite global variables" setting when editing a trigger 

---

docs/streaming/destinations/kafka.mdx
docs/streaming/sources/kafka.mdx
mage_ai/data_preparation/templates/data_exporters/streaming/kafka.yaml
mage_ai/data_preparation/templates/data_loaders/streaming/kafka.yaml
mage_ai/tests/data_preparation/test_templates.py

Added kafka api_version to the data loader and data exporter templates, updated the docs to incorporate this accordingly.
- [ Yes ] Made changes to data preparation test accordingly
- [ N/A ] Test B
- [ Yes ] I have made corresponding changes to the documentation
cc:

Add kafka api_version to the data loader and data exporter templates

---

mage_ai/orchestration/concurrency.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/orchestration/triggers/utils.py
mage_ai/server/api/triggers.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

Add new config options to `ConcurrencyConfig`:
* `pipeline_run_limit_all_triggers`: set the maximum number of pipeline runs for a single pipeline
* `on_pipeline_run_limit_reached`: set behavior for pipeline runs when the pipeline run limit is reached. if set to "skip", the scheduler will cancel the current run when the limit is reached.
I had to update the scheduling logic in `schedule_all` to handle the new configuration option to loop through schedules grouped by pipeline.

[dy] Add pipeline run limit for a pipeline

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/templates/callbacks/base.jinja
mage_ai/shared/hash.py
mage_ai/tests/data_preparation/executors/test_block_executor.py

Add error information to failure callback as a keyword argument. I also changed the fallback logic for the callbacks because it was catching all `TypeError` exceptions even if it was occurring inside the callback block.
cc:

[dy] Add exception failure message in callbacks

---

mage_ai/frontend/components/PipelineRun/MetricsSummary/index.style.ts
mage_ai/frontend/components/PipelineRun/MetricsSummary/index.tsx
mage_ai/frontend/components/charts/BarStack.tsx
mage_ai/frontend/components/charts/utils/label.ts
mage_ai/frontend/components/shared/Grid/Col.tsx
mage_ai/frontend/components/shared/Grid/Row.tsx
mage_ai/frontend/pages/overview/index.tsx

- The formatting was off for very large pipeline run counts in the project overview dashboard, so this PR fixes it.
Responsive pipeline run metrics component:

[jk] Fix project dashboard overview count formatting

---

mage_ai/api/policies/RolePolicy.py
mage_ai/api/resources/UserResource.py

When updating any user profile information from the user profile page, the roles were getting deleted when `role_ids` was not being passed into the payload. This PR updates the logic in the `UserResource` to not delete all the roles when `role_ids` is not passed in.
cc:

[dy] Fix roles getting overwritten when updating profile

---

README.md

Create a single source of truth for quickstart info.
I modeled this after [Astro's README](https://github.com/withastro/astro/blob/main/README.md#install), which provides info on installation, but links out to their documentation for quickstarts/tutorials.

[mp] point `README` quickstart to docs

---

mage_ai/api/resources/BlockResource.py
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/DependencyGraph/utils.ts

Data integration pipelines weren’t being handled when viewing their block runs in the tree.
The block run UUID wasn’t being mapped to the original block UUIDs and the upstream and downstream blocks weren’t being re-assigned to handle suffix UUIDs containing colons and indexes.

[td] Fix tree for data integration pipeline

---

requirements.txt

Add pyarrow-hotfix to requirements.txt
Close: https://github.com/mage-ai/mage-ai/issues/3988
cc:

[xy] Add pyarrow-hotfix to requirements.txt

---

mage_ai/orchestration/queue/process_queue.py
mage_ai/tests/orchestration/queue/test_process_queue.py

Enhance the `has_job` check in ProcessQueue method. It's reported by user that some block runs are stuck in queued status. I suspect it's some random issue of enqueueing or dequeueing the job.
Thus when checking the job existence, we also check whether the queue is empty to make sure the job is in queue or not. 
cc:

[xy] Re-enqueue the job if queue is empty.

---

mage_ai/tests/api/endpoints/test_workspaces.py

As title. The workspace test is flaky in the github CI for some reason, so disabling for now.
cc:

[dy] Disable flaky workspace test

---

mage_ai/tests/api/operations/test_base.py
mage_ai/tests/api/operations/test_users.py

Add additional unit test to validate that admin users can access the user attributes when fetching list of users.
cc:

[td] Add unit test to test user list response for admins

---

mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx

If the current kernel is not PySpark, don’t show the status in the notebook header for SSH tunneling.
cc:

[td] Don’t show SSH tunnel option unless kernel is PySpark

---

mage_ai/api/operations/base.py
mage_ai/api/resources/GlobalHookResource.py
mage_ai/data_preparation/models/global_hooks/constants.py
mage_ai/data_preparation/models/global_hooks/models.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/tests/api/operations/test_operations_with_hooks.py

- Add a special operation `UPDATE_ANYWHERE` so that when a block is updated via the Pipeline endpoint, the hook with that operation also runs.
- If operation is `UPDATE_ANYWHERE`, the hook will run in 2 place:
- When updating a block from the block API endpoint
- When updating a block from the pipeline API endpoint
cc:

[td] Add hook operation for running when block is updated in a pipeline

---

mage_ai/services/k8s/job_manager.py
mage_ai/tests/services/k8s/test_job_manager.py

Pass env_from to k8s job pod.
Close: https://github.com/mage-ai/mage-ai/issues/3975
cc:

[xy] Pass envFrom to job pod.

---

docs/development/blocks/data_loaders/templates.mdx

- [ Yes ] Tested by opening the docs locally [Screenshot attached]
cc:

[sm] Added data loader templates for Druid and Pinot in the doc

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
mage_ai/frontend/oracle/components/Tooltip/TooltipWrapper.tsx

- If a data integration pipeline had multiple streams and a user tried applying a feature as a bookmark to all streams, the bookmark property may not get applied to the other streams if the other stream did NOT have that particular feature as a "valid replication key" in its metadata, which could be confusing to users wondering if the "Apply to all streams" feature was working properly. This PR adds a section in the schema settings to clarify valid replication keys and how it affects applying a feature as a bookmark to all streams. The "Valid replication keys" section will only be displayed if the integration pipeline has multiple streams and at least 1 bookmark property is selected.
- Bugfix: Fixed tooltip positioning in data integration pipeline schema table.
The `All streams` column …

[jk] Clarification when applying bookmark to all streams

---

mage_ai/data_preparation/models/global_hooks/constants.py
mage_ai/data_preparation/models/global_hooks/models.py
mage_ai/data_preparation/models/global_hooks/utils.py
mage_ai/tests/api/operations/test_operations_with_hooks.py
mage_ai/tests/data_preparation/models/global_hooks/test_hook.py
mage_ai/tests/data_preparation/models/global_hooks/test_utils.py
mage_ai/tests/shared/mixins.py

- For restricted resource types, remove the input and output data
- Add tests for restricted resource types
- Uncomment API operation tests for using hooks
cc:

[td] Enable API operation tests with hooks and add more

---

mage_ai/data_preparation/executors/pipeline_executor.py
mage_ai/data_preparation/models/block/__init__.py

* Allow using block configuration when run_pipeline_in_one_process is true
* Update block run status and start time in pipeline executor.
cc:

[xy] Allow using block configuration when run_pipeline_in_one_process is true

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx

- If the valid replication keys for a stream's schema in a data integration pipeline is empty, any of the stream's features/columns can be bookmark properties. This allows other stream's columns to be marked as bookmark properties when using the "apply bookmark to all streams" feature. Previously, no column for another stream would be applied as a bookmark property when using the "apply to all streams" feature if the other stream's `valid_replication_keys` list was empty, so this PR fixes that.
Applying bookmark to all streams when the other streams have an empty `valid_replication_keys` list: 
Updated description for "Valid replication keys" (not empty list):
Updated description for "Valid replication keys" (empty list):

[jk] Update logic for valid replication keys in integration pipelines

---

mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
mage_ai/frontend/components/PipelineDetailPage/utils.ts

- Backfills is only supported for standard/python pipelines, so this PR hides the Backfills section from the left vertical navigation in other pipeline types (i.e. streaming and integration pipelines).
Standard pipeline nav (Backfills visible):
Streaming pipeline nav (Backfills hidden):
Integration pipeline nav (Backfills hidden):

[jk] Only show Backfills in vertical nav for standard (python) pipelines

---

mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

Clicking a file in the file browser from the notebook opens the file to be edited.
The URL will include the file path.
The notebook page suppose to update the component state to be the value of the file path in the URL. However, the hook that supposes to update that internal state was not being triggered.
Solution is to add the query object as a dependency to the `useEffect` that is setting the state.
cc:

[td] Fix files not being selected in notebook

---

mage_ai/frontend/components/Backfills/Detail/index.tsx
mage_ai/frontend/components/Backfills/Table/index.tsx
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/tests/factory.py
mage_ai/tests/orchestration/db/models/test_schedules.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

- The backfill status was not updating to `running` when the backfill's pipeline runs were running, or `failed` after at least 1 of the backfill's pipeline runs failed, or `completed` when the backfill initially failed but successfully completed upon retrying. This PR updates the backfill statuses accordingly.
Failed backfill does not update status (you have to cancel the backfill to retry again):
Successful backfill retry does not update status:
Successful backfill:
Failed backfill:
Successful backfill retry:

[jk] Update backfill statuses

---

mage_ai/data_preparation/models/global_hooks/models.py
mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
mage_ai/frontend/interfaces/GlobalHookType.ts

Add a setting to run hook’s pipeline asynchronously.
cc:

Add asynchronous to global hooks run

---

mage_ai/frontend/components/CodeBlock/utils.ts

You can reduce the output of any dynamic child block no matter the depth; however, the UI didn’t allow for that.
cc:

[td] Reduce block at any level UI

---

docs/mint.json
docs/streaming/destinations/rabbitmq.mdx
mage_ai/data_preparation/templates/data_exporters/streaming/rabbitmq.yaml
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/streaming/constants.py
mage_ai/streaming/sinks/rabbitmq.py
mage_ai/streaming/sinks/sink_factory.py
mage_ai/tests/streaming/sinks/test_rabbitmq.py

Add RabbitMQ as streaming data sink
- [ Yes ] Tested by running locally
- [ Yes ] Added RabbitMQ streaming sink test
- [ Yes ] I have added unit tests that prove my fix is effective or that my feature works
- [ Yes ] I have commented my code, particularly in hard-to-understand areas
- [ Yes ] I have made corresponding changes to the documentation
- [ Yes ] If new documentation has been added, relative paths have been added to the appropriate section of `docs/mint.json`
cc:

[sm] Add RabbitMQ as streaming data sink

---

mage_ai/data_integrations/sources/constants.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailOverview.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/IntegrationSourceType.ts
mage_integrations/mage_integrations/sources/catalog.py
mage_integrations/mage_integrations/sources/sql/base.py
mage_integrations/mage_integrations/sources/sql/constants.py
mage_integrations/mage_integrations/sources/sql/utils.py

For SQL sources, change the operator used when comparing new records to the bookmark property value.
cc:

[td] Support different operators when comparing bookmark properties

---

mage_ai/data_preparation/models/block/sql/utils/shared.py

Support interpolating environment variables in SQL blocks using the following syntax:
```sql
SELECT 
'{{ env_var("ENV") }}' AS test
, '{{ variables("test") }}' AS test2
, {{ test }} AS test3
```
cc:

[td] Support interpolating environment variables in SQL blocks

---

mage_ai/frontend/components/Triggers/utils.ts
mage_ai/frontend/utils/date.ts

The problem existed due to the use of `.toISOSString()` when formatting the selected date, which will add time zone offset. Fixed using (the already exists) `moment`.
- Before
- After

[Fix] Backfill's date-picker date value mismatch

---

mage_ai/api/policies/OauthPolicy.py
mage_ai/tests/api/policies/test_oauth_policy.py

An error was occurring on AWS for a user.
Need to gracefully access dictionaries.
cc:

[td] Gracefully access dictionaries in the Oauth Policy

---

mage_ai/services/k8s/job_manager.py
mage_ai/tests/services/k8s/test_job_manager.py

Pass tolerations from main pod to job pod.
**Before the change:**
* main pod 
* job pod
**After the change:**
* job pod
cc:

[xy] Pass tolerations to job pod.

---

mage_ai/data_preparation/models/block/utils.py
mage_ai/data_preparation/models/pipelines/integration_pipeline.py
mage_ai/tests/data_preparation/models/test_block.py

Loading sample data from integration pipelines was not working when the data integration block in batch pipelines feature was enabled. This PR updates the load sample data logic for integration pipelines  so that the sample data can be properly fetched.
cc:

[dy] Fix load sample data for integration pipelines

---

docs/_snippets/whats-a-block.mdx
docs/data-integrations/destinations/overview.mdx
docs/data-integrations/sources/overview.mdx
docs/getting-started/setup.mdx
docs/guides/community-examples.mdx
docs/mint.json

This PR adds a user's guide on ETL to our community support, cleans up a few things in the `mint.json`, and adds a verbose description of "what is a block" to our guide.

[mp] add user guide and update tutorial to explain blocks

---

mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailSchemaProperties.tsx
mage_ai/frontend/components/DataIntegrationModal/StreamSchemaPropertiesEditor/index.tsx
mage_ai/frontend/components/DataIntegrationModal/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/DataSourceType.ts
mage_ai/frontend/interfaces/IntegrationSourceType.ts

- Data integration data exporter blocks in standard pipelines with certain destination types (i.e. `amazon_s3`, `google_cloud_storage`, and `kafka`) don't support unique constraints or key properties on columns, so it could be confusing to users having those settings there in the schema configuration. This PR hides those settings if the destination type does not support it.
- Clean up `Schema properties` tab in data integration block configuration modal: "Partition key" setting should be under "Options", and `uuid` was missing from the "Column types". The "Bookmark property" bulk edit option only appears when the stream's replication method is set to "Incremental".
All the screenshots below are from data exporter data integration destination blocks in a standard pipeline.
MySQL …

[jk] Hide "Unique" and "Key" columns for certain data integration destination blocks

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeEditor/index.style.tsx
mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/FileVersions/index.tsx

- Add some top padding to the Code Editor for individual files.
cc:
@MageKai

[jk] Add top padding to file code editor

---

mage_ai/data_preparation/preferences.py
mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/sync/__init__.py
mage_ai/server/server.py
mage_ai/settings/repo.py

For git settings and workspace settings, I'm changing Mage to default to the environment variable values if they exist. These values are saved to project config, but I think it makes more sense to default to the env var value since those are specifically set by the user when configuring their mage projects.
cc:

[dy] Default to using environment variables for git and workspace settings

---

mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/tests/orchestration/db/models/test_schedules.py

Remove itertools.groupby because it wasn't behaving how I expected. This was causing bugs when scheduling triggers.

[dy] Remove itertools groupby

---

mage_ai/api/resources/BlockResource.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
mage_ai/frontend/components/PipelineRun/shared/buildTableSidekick.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.style.ts
mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx

Dynamic child blocks can have additional upstream dependencies at runtime.
```yaml
blocks:
- all_upstream_blocks_executed: true
color: teal
configuration: {}
downstream_blocks:
- dynamic_block_normal
- dynamic_block_with_children_with_dynamic_upstream
executor_config: null
executor_type: local_python
has_callback: false
language: python
name: data for dynamic blocks
retry_config: null
status: executed
timeout: null
type: custom
upstream_blocks: []
uuid: data_for_dynamic_blocks
- all_upstream_blocks_executed: true
color: null
configuration:
dynamic: true
downstream_blocks:
- dynamic_child_with_dynamic_upstream
executor_config: null
executor_type: local_python
has_callback: false
language: python
name: dynamic block with children with dynamic upstream
retry_config: null
status: updated …
```

[td] Add upstream block dependencies for dynamic child blocks at runtime

---

docs/integrations/databases/Chroma.mdx
mage_ai/io/chroma.py

* Remove unnecessary print statements
* Add params `id_column` and `metadata_column` to export method
cc:

[xy] Improve the interface for Chroma class.

---

docs/development/project/local-timezone.mdx
mage_ai/frontend/components/Backfills/Detail/index.tsx
mage_ai/frontend/components/Backfills/Table/index.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/PipelineDetail/Syncs/SyncRow/index.tsx
mage_ai/frontend/components/PipelineDetail/Syncs/SyncRowDetail/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/ServerTimeDropdown/index.style.tsx
mage_ai/frontend/components/ServerTimeDropdown/index.tsx
mage_ai/frontend/components/Triggers/utils.ts
mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/frontend/components/settings/workspace/utils.ts
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/storage/constants.ts
mage_ai/frontend/storage/serverTime.ts

- Previously, toggling the local time setting from the header would only change between displaying the current time as UTC or the local timezone. This PR updates this "Display local timezone" toggle in the header so that it actually updates the app's local timezone setting, which displays datetimes in various pages as the local timezone or in UTC. This setting can also be found under the project settings as "Display local timezone".
- Fixes the datetimes in the Syncs page to also display local timezone for the datetimes accordingly. This page was previously not accounted for when adding the local timezone project setting.

[jk] Update local timezone project setting from header

---

mage_ai/frontend/components/Triggers/OverwriteVariables/index.tsx
mage_ai/frontend/components/Triggers/RunPipelinePopup/index.tsx
mage_ai/frontend/oracle/components/Accordion/AccordionPanel.tsx

Overriding variables wasn’t showing up.
cc:

[td] Fix runtime variables not showing when creating new trigger

---

mage_ai/data_preparation/executors/pipeline_executor.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py

Fix executing conditional blocks with pipeline executor.
When running conditional blocks in pipeline executor (run_pipeline_in_one_process: true), the pipeline execution could get stuck because it doesn't update the downstream block status of the failed conditional block. This PR fixes this issue.
cc:

[xy] Fix executing conditional blocks with pipeline executor.

---

docs/guides/blocks/detach-blocks.mdx
docs/mint.json

- See title.
- Tested in mintlify development mode:

[jk] Add docs for detaching blocks

---

mage_ai/data_integrations/utils/scheduler.py
mage_ai/orchestration/metrics/pipeline_run.py
mage_ai/orchestration/pipeline_scheduler.py

When running integration pipelines, the `calculate_metrics` function was being run before the pipeline run started, after every block run, and after the pipeline run was completed. The `calculate_metrics` was calculating pipeline run metrics and block run metrics every time it was called, so if there were a large number of block runs, calculating metrics could take a long time. 
I changed a couple of things to optimize this operation:
1. instead of calculating the metrics for all block runs after each block run was completed, we instead only calculate the metrics for the block run that completed. 
2. instead of calculating every metric when `calculate_metrics` was called, I created separate functions for calculating block run metrics and pipeline run metrics so pipeline run metrics will …

[dy] Optimize calculate metrics for integration pipelines

---

mage_integrations/mage_integrations/destinations/salesforce/README.md
mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/sinks.py

Users reported not being able to execute the `upsert` action while using Salesforce destination.
This was being caused by the current Salesforce Destination target not allowing for a external ID to be selected.
Istead, the target would only use the default `Id` column. For future reference, please refer to salesforce docs [here](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/bulk_api_2_0_upsert.htm?q=upsert)
To fix this, a new optional config named `external_id_name` was added. If it is not provided, the default `Id` strategy is used.
Also added better explanation to the `allow_failures` setting inside README.MD
Tested using API Source block -> Salesforce Destination using `Upsert` action
cc:

Fixed Salesforce Destination Upsert action

---

mage_ai/data_preparation/logging/gcs_logger_manager.py
mage_ai/data_preparation/logging/logger_manager.py
mage_ai/data_preparation/logging/s3_logger_manager.py
mage_ai/services/k8s/job_manager.py

When using external cloud storage for blocks that use the k8s executor, the logs for the block were not getting uploaded correctly. This was happening because the logs were getting written to the destination twice, so the logs in the 1st write were getting overwritten. This PR will try to fetch logs from the destination first and append the new logs to the existing logs if they exist.
Before:
After:

[dy] Fix external cloud storage logs for k8s blocks

---

mage_ai/api/presenters/DownloadPresenter.py

- Fix DownloadPolicy error preventing downloading pipeline zip files when using app as non-owner role.
- Related to https://github.com/mage-ai/mage-ai/pull/3813
- Tested pipeline downloads were working.
Before (policy error):

[jk] Update DownloadPolicy to allow downloading pipeline zip files

---

docs/mint.json
docs/streaming/destinations/activemq.mdx
mage_ai/data_preparation/templates/data_exporters/streaming/activemq.yaml
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/streaming/constants.py
mage_ai/streaming/sinks/activemq.py
mage_ai/streaming/sinks/sink_factory.py
mage_ai/tests/streaming/sinks/test_activemq.py

Add ActiveMQ as streaming data sink
cc:

[sm] Add ActiveMQ as streaming data sink

---

mage_ai/api/policies/BlockPolicy.py
mage_ai/api/resources/BlockResource.py
mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx

The block runs page was loading very slowly when there are a large number of block runs, for example in an integration pipeline with many streams/batches. The block runs page was attempting to render every single block run in the dependency graph which would cause the page to hang or load slowly. This PR updates the dependency graph to only try to render every block run if there fewer than a set number of block runs.
cc:

[dy] Fix block runs page when there are a large number of block runs

---

mage_ai/api/presenters/WorkspacePresenter.py
mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/cluster_manager/workspace/kubernetes.py
mage_ai/frontend/interfaces/WorkspaceType.ts
mage_ai/frontend/pages/manage/index.tsx
mage_ai/tests/cluster_manager/kubernetes/test_workload_manager.py

For kubernetes workspaces, if the workspace config has an `ingress_name`, then we will try to get the url to access the workspace when fetching the workspace. Also, remove the service from the ingress when deleting the workspace.
cc:

[dy] Update url logic for workspace manager

---

mage_ai/io/postgres.py
mage_integrations/mage_integrations/destinations/sql/base.py

Some users may be manually adding double quotes for tables that have capitalized letters. We will account for this by removing double quotes in cases where they are not needed or we are already adding them.

[dy] Remove double quotes for postgres

---

mage_ai/frontend/components/DependencyGraph/utils.ts

- The upstream blocks in a pipeline were getting sorted automatically, affecting the order of the upstream blocks despite its order in the pipeline's `metadata.yaml` file. The order of the upstream blocks can be important, so this PR fixes the auto-sorting bug so that the upstream block order will be based on its order in the pipeline `metadata.yaml` file.
Before (the upstream block order for block `natural_familiar` should be the order that the blocks appear in the pipeline in this scenario, but the upstream block order is based on alphabetical name order):
After (upstream block ordering can be changed and ordering reflects order in pipeline):
Is consistent with order in metadata.yaml:
```
upstream_blocks:
- knightly_music
- spirited_merchant
- cold_phoenix
uuid: natural_familiar
```
cc:

[jk] Fix block sorting bug

---

mage_ai/data_preparation/templates/custom/python/default.jinja

- Remove `data` from the arguments in the custom block template to avoid confusion since users might think an upstream block is required (it is not required for custom blocks).

[jk] Update custom block template

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/global_hooks/models.py

When trying to persist a block run,
```
sqlalchemy.exc.StatementError: (builtins.TypeError) Object of type Py4JJavaError is not JSON serializable
[SQL: UPDATE block_run SET updated_at=CURRENT_TIMESTAMP, status=?, metrics=? WHERE block_run.id = ?]
[parameters: [{'metrics': {'__error_details': {'error': Py4JJavaError('An error occurred while calling o84.parquet.
', JavaObject id=o85)}}, 'status': <BlockRunStatus.FAILED: 'failed'>, 'block_run_id': 1395}]]
```
Cannot save arbitrary error details in the database
cc:

[td] Don’t save error details in the block run DB

---

mage_ai/frontend/components/Logs/Toolbar/constants.ts
mage_ai/frontend/components/Logs/Toolbar/index.tsx
mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
mage_ai/frontend/oracle/components/ToggleMenu/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/frontend/utils/routing.ts

If applying a filter on the Pipelines Dashboard while on a later page and the total number of filtered pipelines is too few to require the current page number, no pipelines will be visible (see "Before" gif below for example). This PR resets the query `_offset` after applying a pipeline filter to make sure any applicable pipelines will be visible.
Before (pipelines hidden until you click on a previous page):
After (page resets):

[jk] Reset page after applying pipeline filters

---

mage_ai/data_preparation/models/block/dbt/block_sql.py
mage_ai/data_preparation/models/block/dbt/profiles.py
mage_ai/data_preparation/models/block/platform/mixins.py
mage_ai/tests/data_preparation/models/block/dbt/test_dbt_adapter.py
mage_ai/tests/data_preparation/models/block/dbt/test_profiles.py

Don’t raise an error when adding a dbt file and the profile can’t be parsed.
cc:

[td] Don’t raise errors when adding dbt files

---

docs/integrations/databases/Qdrant.mdx
docs/mint.json
mage_ai/data_preparation/templates/constants.py
mage_ai/data_preparation/templates/data_exporters/qdrant.py
mage_ai/data_preparation/templates/data_loaders/qdrant.py
mage_ai/data_preparation/templates/repo/io_config.yaml
mage_ai/io/base.py
mage_ai/io/config.py
mage_ai/io/qdrant.py
requirements.txt
setup.py

- Add new data loader template and explorter template for Qdrant.
- Add io/qdrant.py script to support the load and exporter function.
Mage UI Loader:
Exporter, number of reords written by exporter:
With auto generation vector list to query:
cc:

[xh]Qdrant integration for data loader and exporter

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/data_preparation/templates/data_loaders/streaming/nats.yaml
mage_ai/streaming/sources/nats_js.py

https://github.com/mage-ai/mage-ai/issues/4122 implementation, a configurable nats jetstream subscription method, that support for PULL and PUSH consumer type with queue group options.
New Configuration:
- consumer_type: define what the type of consumer you want, available types: PULL and PUSH, the default is PULL.
- use_queue_group: this is the configuration for a PUSH consumer. If set to True, it allows the consumer to use a queue group.
- tested locally by creating NATS streaming pipeline with new configuration.
cc:
@mfreeman451 @wangxiaoyou1993

[Enhancement] Add queue_subscription support for nats jetstream streaming source

---

setup.py

`qdrant-client` requires `importlib-metadata` with Python >= 3.8.
Mage is set to require Python >= 3.7.
```
> [linux/amd64 7/9] RUN   tag=$(tail -n 1 /tmp/constants.py) &&   VERSION=$(echo "$tag" | tr -d "'") &&   pip3 install --no-cache-dir "mage-ai[all]==$VERSION" &&   rm /tmp/constants.py:
83.32   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
83.32     state = resolution.resolve(requirements, max_rounds=max_rounds)
83.32   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
83.32     failure_causes = self._attempt_to_pin_criterion(name)
83.32   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 227, in _attempt_to_pin_criterion
83.32 …
```

[td] Remove qdrant-client

---

mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/Files/index.tsx

Files were not opening when you click them when on `/files` page.
cc:

[td] Fix files page not opening files

---

docs/streaming/destinations/rabbitmq.mdx
docs/streaming/sources/rabbitmq.mdx
mage_ai/streaming/sinks/rabbitmq.py
mage_ai/streaming/sources/rabbitmq.py

This PR adds a new setting to both sink and source RabbitMQ blocks
Now users can specify whether they want to use the standard `amqp` or `amqps` protocol
cc:

Added url protocol option to rabbitmq streaming

---

mage_ai/frontend/components/FileBrowser/FileHeaderMenu/index.style.ts
mage_ai/frontend/components/FileBrowser/FileHeaderMenu/index.tsx
mage_ai/frontend/components/FileBrowser/Folder/index.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/FileEditor/Header/index.tsx
mage_ai/frontend/components/Files/index.tsx
mage_ai/frontend/components/Files/useFileComponents.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/constants.ts
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/interfaces/FileType.ts
mage_ai/frontend/pages/manage/files/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/storage/files.ts

- Add file header menu to FileBrowser component to view of hide hidden files/folders.
cc:

[jk] View or hide hidden files in file browser

---

mage_ai/api/resources/ProjectResource.py

Import error when installing Mage via pip without dbt installed.

[td] Don’t import any dbt files until needed

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts

Optionally disable running a query at the end of executing raw SQL.
Some commands (e.g. `UNLOAD` in Redshift) don’t return data. Trying to fetch sample data after these commands will throw an error in Mage:
```python
None object is not iterable
```
cc:

[td] Disable sample query when using raw SQL

---

mage_ai/io/mongodb.py

Fixes:
```
File "/usr/local/lib/python3.10/site-packages/mage_ai/io/mongodb.py", line 83, in export
if not data:
File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 1527, in __nonzero__
raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

[td] Fix dataframe validation

---

mage_integrations/mage_integrations/sources/dynamodb/README.md
mage_integrations/mage_integrations/sources/dynamodb/__init__.py

The amazon_s3 integration source has code in the constructor that lets you use a `role_arn` instead of static `aws_access_key_id` and `aws_secret_access_key`, but currently the dynamoDB source does not have this. This MR basically copies the code over from amazon_s3 with one change (passing 'dynamodb' to the `session.client` call instead of 's3')
The motivation for this is that we are trying really hard to keep static AWS credentials out of our production environment, since they are difficult to manage and keep track of. It is also AWS best practice to use IAM Roles: https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#bp-workloads-use-roles
* Ran code locally
* The Docker container mounts my `~/.aws` directory, so I added a temporary profile in my `~/.aws/config` file …

Added role_arn as an optional config for AWS DynamoDB source

---

mage_ai/api/resources/PipelineResource.py
mage_ai/data_preparation/models/block/__init__.py

This PR fixes two issues
* Catch pipeline initialization errors when loading pipeline list page
* Save block statistics.json in correct execution partition folder so that the file doesn't have conflicts when running multiple triggers.
cc:

[xy] Save statistics.json in correct execution partition folder.

---

mage_ai/cache/pipeline.py
mage_ai/cache/tag.py
mage_ai/cache/utils.py
mage_ai/frontend/components/Dashboard/index.tsx

Filtering by type was throwing an error because of how we stored pipelines in the cache. We now add the repo path to the key.
cc:

[td] Fix the way we store pipelines by type in the cache

---

mage_ai/frontend/components/Triggers/utils.ts

- When UTC dates were being used in the app ("Display local timezone" setting NOT enabled), the "Start date and time" for a new trigger should default to the current datetime in UTC time, but the start date (YYYY-MM-DD) was defaulting to the current local date, so it could appear to be 1 day off depending on the timezone difference. This PR fixes that.
Before (Current datetime was `2024-01-03 18:42 PST` / `2024-01-04 02:42 UTC`, but UTC start time was defaulting to `2024-01-03` instead of `2024-01-04`):
After (Current datetime was `2024-01-03 18:40 PST` / `2024-01-04 02:40 UTC`, and UTC start time correctly defaults to `2024-01-04`):

[jk] Use utc date for trigger start date

---

mage_ai/frontend/components/FileBrowser/Folder/index.tsx
mage_ai/frontend/components/FileBrowser/Folder/requestIdleCallbackPolyfill.ts

`requestIdleCallback` is not supported on Safari.
That function is used to defer rendering of elements in the File browser.
cc:

[td] Fix requestIdleCallback not supported on Safari

---

mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/Triggers/utils.ts

- Fixes issue related to https://github.com/mage-ai/mage-ai/pull/4283 where sometimes, the start date for triggers or start/end dates for backfills would be off 1 day if they were already set and then changed in the edit pages due to an issue with timezone conversions.
- Tested various start/end datetimes for triggers/backfills and confirmed that the datetimes displayed were consistent with the datetimes in the Edit pages.

[jk] Display correct default start datetime when editing trigger/backfill

---

mage_ai/orchestration/db/__init__.py
mage_ai/server/server.py

Resolves https://github.com/mage-ai/mage-ai/issues/4217. We will only run the `ALTER ROLE ...` command when the web server is started, so that it isn't executing multiple times when multiple pipelines are started in executor pods/tasks.

[dy] Only set the schema in the DB when the server is started

---

mage_ai/io/postgres.py

Resolves https://github.com/mage-ai/mage-ai/issues/3929. Like the issue suggests, psycopg2 does not accept keyword arguments in the `.execute` method, so this PR changes the postgres io class to pass in the query variables as a dictionary when they exist.
cc:

[dy] Pass in query_vars as a dict

---

mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/orchestration/pipeline_scheduler_project_platform.py

Wrap block run initialization logic with lock so that no duplicate block runs are created for data integration pipeline when there're multiple servers running
Run a data integration pipeline, no duplicate block runs are created anymore
Original:
With the fix:
cc:

[xy] Wrap block run initialization logic with lock.

---

mage_ai/io/bigquery.py

Escape bigquery project name in sql block.
Close: https://github.com/mage-ai/mage-ai/issues/4182
Wrap the project name with backtick
cc:

[xy] Escape bigquery project name in sql block.

---

mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/orchestration/pipeline_scheduler_project_platform.py

Try preventing creating duplicate pipeline runs in scheduler.
Before creating the pipeline run, double check whether there's an existing pipeline run with same execution date, pipeline schedule id and pipeline uuid.
cc:

[xy] Try preventing creating duplicate pipeline runs in scheduler.

---

mage_ai/frontend/components/FileEditor/utils.ts
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/utils/hooks/keyboardShortcuts/useGlobalKeyboardShortcuts.tsx

Dragging from file browser added the block type folder name in front of it.
cc:

[td] Fix dragging and dropping file in browser

---

mage_ai/data_preparation/models/block/data_integration/mixins.py

```
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py in execute_block(self, block_run_outputs_cache, build_block_output_stdout, custom_code, execution_partition, from_notebook, global_vars, input_args, logger, logging_tags, input_from_output, runtime_arguments, dynamic_block_index, dynamic_block_indexes, dynamic_upstream_block_uuids, run_settings, data_integration_runtime_settings, execution_partition_previous, **kwargs)
1270             if from_notebook and self.is_data_integration():
1271                 input_vars, kwargs_vars, upstream_block_uuids = \
-> 1272                     self.fetch_input_variables_and_catalog(
1273                         input_args,
1274 …
```

[td] Fix incremental sync bug with missing arg

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/utils.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/storage/base_storage.py
mage_ai/data_preparation/storage/gcs_storage.py
mage_ai/data_preparation/storage/local_storage.py
mage_ai/data_preparation/storage/s3_storage.py
mage_ai/data_preparation/variable_manager.py
mage_ai/tests/data_preparation/models/test_block.py
mage_ai/tests/data_preparation/models/test_variable.py
requirements.txt

Resolves https://github.com/mage-ai/mage-ai/issues/4102.
In order to serialize a polars dataframe, we have to write some metadata about the output variable so that we can determine whether or not to use polars or pandas when serializing. This PR adds a `type.json` file to the variable directory that currently just stores the type of the variable which will be used when reading the output data. If there is no file, we will fallback to the previous logic.

[dy] Support serialize Polars dataframe

---

mage_ai/data_preparation/models/project/__init__.py
mage_ai/settings/repo.py
mage_ai/tests/data_preparation/models/test_project.py

When using `mage_secret_var` in project metadata.yaml and starting the Mage server, there's an infinite loop that prevents
the server from starting.
The infinite loop: get_secret_value calls Project(), Project() calls get_repo_config(), get_repo_config() calls get_secret_value.
To fix this issue, I change the `repo_config` to be lazy initialized in Project model.
There's another issue of calling `get_variables_dir`. This method throws undefined variable error. Thus, I change this method to only render the `variables_dir` value in the project metadata.yaml instead of rendering the whole file.
cc:

[xy] Fix interpolating mage secret in project metadata.yaml

---

mage_integrations/mage_integrations/destinations/amazon_s3/README.md
mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py

Added support for IAM role-based authentication for AWS S3 Destination integration by copying the implementation from AWS S3 Source integration.
Since both Source and Destination integrations share a lot of similar code, I would suggest minimising repetition by creating a base class that both integrations inherit from.
Related to #2516.
cc:

AWS S3 Destination: Added support for IAM role-based authentication.

---

mage_ai/api/resources/PipelineRunResource.py

Speed up pipeline run count query. `/api/pipeline_runs?_limit=0&api_key=` (A user reported this request takes 2mins with a lot of pipeline runs)
* No need to order the results if limit is 0
* No need to fetch additional results if limit is 0
cc:

[xy] Speed up pipeline run count query.

---

mage_ai/data_preparation/executors/ecs_block_executor.py
mage_ai/services/aws/ecs/config.py
mage_ai/services/aws/ecs/ecs.py

ECS executor command was split by empty space. When data integration block's command has parameter like `--template-runtime-configuration '{"destination_table": "table_name", "index": 0, "is_last_block_run": false, "selected_streams": ["stream_name"]}'`, it splits the json into multiple args, which causes the ECS task execution to fail.
Thus, fix this issue by passing a list of args directly to ECS run_task method.
cc:

[xy] Fix executing data integration block with ecs executor

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
mage_ai/shared/retry.py
mage_ai/tests/data_preparation/executors/test_block_executor.py

Add retry attempts to kwargs for block function and callback functions.
cc:

[td] Add retry info in callbacks and function that’s being retried

---

mage_ai/data_preparation/models/block/content.py

This use to work but it stopped because a change.
```
{{ variable_name }}
```
This code change fixes it.

[td] Fix SQL blocks

---

mage_ai/services/search/block_action_objects.py

- Prevent `max() arg is an empty sequence` error when searching for blocks.
- TODO (in separate PR): Include block files when searching for blocks, since they are currently not appearing in the search results.
Before:
After:
cc:

[jk] Prevent error when searching for blocks

---

mage_ai/frontend/pages/_app.tsx

Don’t disable command center if user authentication is not required.

[td] Enable command center when user auth not required

---

mage_ai/frontend/components/CommandCenter/constants.tsx

- It was a bit confusing what exactly to enter when modifying the command center keyboard shortcut, so this PR improves the wording, provides a link to get key codes, and fixes the example shortcut.

[jk] Improve command center shortcut wording and example

---

mage_ai/cache/block_action_object/__init__.py

- The block search in the Pipeline Editor wasn't searching for block files due to an issue with the `block_action_objects_mapping` cache. This PR fixes this.
cc:

[jk] Fix bug when searching for block files

---

mage_ai/api/resources/PipelineResource.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/pages/pipelines/index.tsx

- The pipelines might not load on the Pipelines Dashboard if 1 of the pipelines has a block with an invalid block type, but the error (`'NoneType' object is not callable`) wasn't very explicit and could be difficult to troubleshoot not knowing which pipeline had the issue.
- The pipeline with an invalid configuration will still be displayed in the UI, but have an `invalid` pipeline type. When users click on that pipeline, they can see the error causing the pipeline to load. If it's due to an invalid block type error, the error will be more descriptive now.

[jk] Make block type error more descriptive

---

mage_ai/frontend/components/Triggers/utils.ts

- The cron expression wasn't being displayed properly in the UI when setting it to midnight local time (with `display_local_timezone` setting enabled). This PR fixes it.
- Addresses github issue https://github.com/mage-ai/mage-ai/issues/4266
Before: Setting the cron expression to 12 AM local time has the correct "Next run date", but the cron expression isn't displayed correctly.
After - The cron expression displayed in the UI is consistent with what was entered.

[jk] Fix cron expression conversion when using local midnight time

---

mage_integrations/mage_integrations/sources/freshdesk/tap_freshdesk/schemas/tickets.json

`custom_fields` was removed from freshdesk tickets.json schema in a latter PR
After inserting it back into the tickets.json file, no issue was found.
Since no issue was found, this PR adds `custom_fields` field back into tickets.json schema
Tested using a freshdesk test account, in a Freshdesk -> PostgreSQL pipeline 
State is not being handled correctly, rendering incremental sync inoperable as of now
cc:

Added 'custom_fields' to freshdesk source

---

docs/integrations/databases/BigQuery.mdx
mage_ai/io/bigquery.py

Support overwriting column types in BigQuery.
`overwite_types` param is added to `export` method as an optional param.
Supported column types: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#TableFieldSchema.FIELDS.type
cc:

[xy] Support overwriting column types in BigQuery.

---

mage_ai/api/resources/WidgetResource.py

Fix exception when creating widget: `Widget object has no attribute 'write_async'`
Close: https://github.com/mage-ai/mage-ai/issues/4364
The bug was introduced in version 0.9.55 https://github.com/mage-ai/mage-ai/pull/4193
cc:

[xy] Fix creating widget.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dynamic/utils.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/CodeBlock/CodeOutput/MultiOutput.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/useCodeOutput.tsx
mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
mage_ai/frontend/components/PipelineDetail/utils.ts
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/KernelOutputType.ts
mage_ai/server/utils/output_display.py
mage_ai/server/websocket_server.py
mage_ai/shared/custom_logger.py

- Fix dynamic child blocks input and output data
- Show dynamic block outputs in notebook
- Show dynamic child block outputs in notebook
https://github.com/mage-ai/mage-ai/assets/1066980/d2328ae7-009c-4a5e-96ce-ebe38f4a338a
https://github.com/mage-ai/mage-ai/assets/1066980/7be11881-6496-425f-94b6-59398c1ce6d9
cc:

[td] Show multiple outputs and fix downstream dynamic child block inputs and outputs

---

mage_ai/server/terminal_server.py
mage_ai/server/websockets/terminal/server.py
mage_ai/server/websockets/terminal/utils.py

Remove extraneous terminal subclasses and the color commands because it freezes the apps installed via pip.
cc:

[td] Remove terminal colors because the commands freeze pip installed Mage

---

mage_ai/api/policies/ProjectPolicy.py
mage_ai/api/resources/ProjectResource.py
mage_ai/command_center/applications/constants.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/pipelines/seed.py
mage_ai/data_preparation/models/project/__init__.py
mage_ai/data_preparation/models/project/constants.py
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/frontend/pages/overview/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/frontend/utils/models/project/useProject.ts
mage_ai/orchestration/db/constants.py
mage_ai/orchestration/db/functions.py
mage_ai/orchestration/monitor/monitor_stats.py
mage_ai/usage_statistics/constants.py
mage_ai/usage_statistics/logger.py

- Stop making multiple calls for a single endpoint (Overview page calls monitor stats twice or more)
- Don’t select all columns, only select the ones needed
- Perform as much formatting logic as possible in the database
cc:

[td] Speed up monitor stats and reduce calls on overview

---

requirements.txt

Remove `couchbase` from requirements.txt so Docker can build: https://github.com/mage-ai/mage-ai/actions/runs/7616491146/job/20743366010

[td] Remove Couchbase from the dev requirements

---

mage_integrations/mage_integrations/destinations/clickhouse/__init__.py
mage_integrations/mage_integrations/destinations/clickhouse/target_clickhouse/sinks.py

This PR removes Draft7 validation from Clickhouse destination.
The issue seems to be caused by Draft7 expecting record datetime data to be valid RFC3339, but the Clickhouse engine not allowing the specified date-time string record to be inserted. ( preliminary tests seems to replicate the same behaviour on simple DateTime64 columns as well )
To quickly allow users to use MySQL -> Clickhouse Pipelines, this PR removes the Draft7 validation and guarantees datetime.datetime insertion on Clickhouse DB.
Also, when updating tables, the singer-sdk would point to a `load_method` variable that currently was not supported, the APPEND_ONLY method was selected as of now.
Tested using MySQL -> Clickhouse DB
cc:

Removing Draft7 validation from Clickhouse destination

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/tests/data_preparation/executors/test_block_executor.py
mage_ai/tests/data_preparation/executors/test_pipeline_executor.py

There was a bug introduced in version 0.9.59 that the `global_vars['context']` is not passed across blocks because the `global_vars` is copied before execute method.
This PR fixes this issue.
Also comment out `asyncio.run(UsageStatisticLogger().block_run_ended(self.block_run))` in BlockExecutor since it throws error when running PipelineExecutor
cc:

[xy] Fix global_vars context in pipeline executor.

---

docs/streaming/sources/kafka.mdx
mage_ai/streaming/sources/kafka.py
mage_ai/tests/streaming/sources/test_kafka.py

This PR contemplates three issues (#4069 #4114 #4040)
Kafka source will now allow for offset configuration along with 
partition settings.
These offsets being:
1. Beginning
2. End
3. Int
4. Timestamp
This allows users to set specific positions inside a topic to consume data
offset handling corresponds to #4114 and #4069
in #4069 user requested a similar behaviour to the auto_offset_reset python function
The specified function in the issue seems to be from Spark.
With that, the whole content of the issue is solved inside Offset Handling, but this 
setting was added to prevent future issues
Added max_partition_fetch_bytes settings along with auto_offset_reset.
this corresponds to #4040
Tested using a local kafka broker and Dummy sink.
For this test, 10 messages were written with a producer, …

Added kafka streaming source offset and partition options

---

mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/tests/destinations/snowflake/test_snowflake.py

Fix writing to Snowflake with mixed int and str types. 
```
, "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/sql/base.py\", line 383, in main
destination.process(sys.stdin.buffer)
", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 364, in process
errors=traceback.format_stack(),
"], "message": "Traceback (most recent call last):
File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 359, in process
self._process(input_buffer)
File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 516, in _process
self.__process_batch_set(
File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 585, in …
```

[xy] Fix writing to Snowflake with mixed int and str types

---

docs/guides/blocks/reorder-blocks.mdx
docs/mint.json

- See title. Doc will be located at https://docs.mage.ai/guides/blocks/reorder-blocks.
- Checked doc in dev environment:
cc:

[jk] Add doc for reordering blocks

---

mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/components/DataIntegrationModal/constants.ts
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/IntegrationPipeline/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Fix bug due to incorrectly named prop passed into `PipelineDetail` and `Sidekick` components for fetching files.
- Confirmed error no longer appears locally when clicking the `View and select streams` button in an integration pipeline and confirming a selected stream.

[jk] Fix pipeline detail prop passed for fetching files

---

mage_ai/frontend/components/CommandCenter/index.style.tsx

- The AddNewBlock menu was disappearing when hovering the mouse cursor about halfway down the window due to a z-index issue with the hidden command center. This PR fixes this so the menu no longer disappears unexpectedly.
Before (AddNewBlock menu disappears suddenly):
After (AddNewBlock menu no longer disappears unexpectedly):

[jk] Prevent add block menu from disappearing

---

mage_integrations/mage_integrations/destinations/postgresql/__init__.py

Properly cleaning column names for existing columns when altering table in postgresql destination mage_integrations.
1. Create data_loader block that returns any uppercase column name DataFrame e.g. `[{"ID": 1,},]`
2. Create data_exporter integration destination block (PostgreSQL). Set option `lower_case: false`
3. Run pipeline. This will create a new table, columns and data. Correctly.
4. Run this pipeline again. As a result the following will happen:
- Without this PR, runner will raise exception: `Error while executing query: column "ID" of relation ... already exists ... Query string: ALTER TABLE "schemaname"."tablename" ADD COLUMN "ID" BIGINT ...`
- With this PR, repeated integration runs are performed correctly.

Fix alter table column names cleaning (postgresql integration exporter)

---

mage_ai/io/postgres.py

When a user doesn't have permission to create a schema, the CREATE SCHEMA IF NOT EXISTS... fails even if the schema already exists.
https://mageai.slack.com/archives/C03HTTWFEKE/p1705108869898959
I swapped out the `CREATE SCHEMA IF NOT EXISTS... ` statement for one that queries the schema catalog and only CREATES the schema if it doesn't exist.  
You can reproduce it by creating a new unprivileged user that only has INSERT on the target table.  
cc:

fix: handle unprivileged user for postgres

---

mage_integrations/mage_integrations/sources/salesforce/README.md
mage_integrations/mage_integrations/sources/salesforce/__init__.py
mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/__init__.py
mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/credentials.py

This PR fixes OAuth connection inside Salesforce Source
These problems originated by a timer set on the login method inside SalesforceOAuth connection. This timer would break the 10 seconds rule for Test Connection and block discover time.
Also, the Login URL was modified to match Salesforce Destination connection, and support specific domains instead of the usual login/test param.
Finally, the `__finally_clean_up()` method was removed from the discover phase. This method would only delivery such information outside of the main pipelines logs, and the standard logs from pipeline output already deliver the exact number of requests versus the max cap. This should allow for less discovery time.
Tested using a Salesforce Source account and a PostgreSQL DB as destination.
( Account stream …

Fixed Oauth connection on Salesforce Source

---

mage_ai/frontend/components/ComputeManagement/index.tsx
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/Files/index.style.tsx
mage_ai/frontend/components/PipelineLayout/index.tsx
mage_ai/frontend/components/ScheduleLayout/index.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/components/TripleLayout/useTripleLayout.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Fix the following bugs:
1. The vertical scrollbar in the before panel (e.g. file browser or trigger detail panel) was not able to be clicked for vertical scrolling (though you could still scroll by using a laptop trackpad or mouse wheel).
2. The before panel width would jump to a smaller width when resizing initially.
Before (vertical scrollbar can't be clicked):
After (vertical scrollbar CAN be clicked):
Before (jumping before panel width):
After (Files page - before panel does not jump):
- Also made sure before panel doesn't jump when resizing on Pipeline Editor, Trigger Detail, Backfill Detail, Pipeline Monitor, Version Control, and Compute Management pages.

[jk] Fix unclickable vertical scrollbar and jumping before panel

---

mage_ai/orchestration/db/models/schedules.py

Optimize some schedule queries. Some queries were pulling all pipeline runs for a schedule when they just needed to get a count which could be very inefficient when there are a lot of runs.

[dy] Optimize pipeline schedule queries

---

mage_ai/api/presenters/PipelinePresenter.py
mage_ai/cache/utils.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/PipelineDetail/utils.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/tests/cache/example_pipeline.json
mage_ai/tests/cache/pipeline_details_mapping_template
mage_ai/tests/cache/test_pipeline_cache.py
mage_ai/tests/data_preparation/models/test_pipeline.py

- The `updated_at` attribute in the Pipeline model was causing git merge conflicts since that value was changing too frequently. In order to display a pipeline's "Updated at" property in the UI or when a pipeline was last saved, we get the modified time of the pipeline's `metadata.yaml` config file.
- If an existing pipeline already has an `updated_at` property in its `metadata.yaml` config file, it will be removed when the pipeline is next saved. The last modified time of the pipeline's config file will still be used for its `updated_at` value in the pipeline response.
Pipeline's "Updated at" values still visible in the Pipelines Dashboard:
Pipeline "Last saved at" date (in the footer on the right) uses pipeline config file's last modified time:

[jk] Remove pipeline's updated_at attribute

---

mage_ai/frontend/components/Files/useFileComponents.tsx

Only show open files that have the correct repo_path prefix. This should reduce the number of file not found errors that occur when opening the file viewer.
cc:

[dy] Only show files with correct prefix

---

docs/streaming/destinations/google-cloud-storage.mdx

Instead of S3, it should be Google Cloud Storage, as this page is referencing Google Cloud Storage
cc:

Wrong cloud storage reference

---

mage_ai/data_preparation/models/triggers/__init__.py
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/interfaces/PipelineScheduleType.ts
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/orchestration/pipeline_scheduler_project_platform.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

Allow users to select what the time out status is for a pipeline schedule. By default, the runs will be set to status failed.
cc:

[dy] Select status for pipeline runs that time out

---

docs/integrations/databases/MotherDuck.mdx
docs/mint.json

Add documentation for using DuckDB to connect to MotherDuck from Mage. This is intentionally a separate page in our documentation— that's what the MotherDuck team requested.
`mintlify dev`

[mp] MotherDuck Docs

---

mage_ai/api/policies/WorkspacePolicy.py
mage_ai/api/resources/WorkspaceResource.py
mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/cluster_manager/manage.py
mage_ai/cluster_manager/workspace/kubernetes.py
mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
mage_ai/frontend/components/workspaces/ConfigureWorkspace/constants.ts
mage_ai/frontend/interfaces/WorkspaceType.ts
mage_ai/frontend/pages/manage/index.tsx
mage_ai/frontend/storage/workspaces.ts
mage_ai/server/server.py

Resolves https://github.com/mage-ai/mage-ai/issues/4451.
Added a filter on the workspaces dashboard to fetch workspaces in all namespaces. In the future, maybe we can add more granular filtering, but right now it's either the default namespace or all workspaces.
cc:

[dy] Create and view workspaces in different namespaces

---

mage_ai/cli/main.py

Fix running dynamic blocks with k8s executor. Pass block_run_id to BlockExecutor init method.
Close: https://github.com/mage-ai/mage-ai/issues/4464
cc:

[xy] Fix running dynamic blocks with k8s executor.

---

mage_ai/api/policies/WidgetPolicy.py
mage_ai/cache/block.py
mage_ai/frontend/components/ChartBlock/index.tsx

- There was a WidgetPolicy error when trying to update a chart block name, so this PR fixes the policy issue.
- Also add a check to avoid `AttributeError: 'list' object has no attribute 'get'` when building the pipeline_count_mapping for the files in the file browser. This might happen when updating a chart block name.
- Confirmed the following policy error no longer appears when updating the chart name:

[jk] Widget policy update

---

mage_ai/cache/block.py

Catch exception of building cache key for block cache so that the block cache can be built successfully.
The error was
cc:

[xy] Catch exception of building cache key for block cache.

---

docs/developer-ux/file-browser.mdx

- See title.
- Tested locally:

[jk] Add docs for used/unused block files in file browser

---

mage_ai/orchestration/monitor/monitor_stats.py

Use utc time as the default time for monitor_stats so that it can show latest pipeline runs when container is using a different timezone
cc:

[xy] Use utc time as the default time for monitor_stats.

---

mage_ai/api/resources/SearchResultResource.py
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/FileEditor/utils.ts
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/FileType.ts

There is currently no easy way to reuse callback and conditional blocks through the UI. This PR allows the user to reuse callback and conditional blocks with 2 different methods:
1. On the Pipeline Editor page, [drag and drop](https://docs.mage.ai/developer-ux/code-editor#adding-blocks-made-easy) a conditional/callback block from the file browser onto the Notebook.
2. On the Pipeline Editor page, [search](https://docs.mage.ai/developer-ux/code-editor#adding-blocks-made-easy) for the name of the callback/conditional block and click the search result to add it to the pipeline (it will automatically be added in the Sidekick under the "Add-on blocks" tab.
Adding callback and conditional blocks via drag and drop:
Adding callback and conditional blocks via block search:

[jk] Reuse callback and conditional blocks

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/server/utils/output_display.py

Show pandas datetime in iso format in notebook.
Doc: https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.to_json.html
before the fix
with the fix
cc:

[xy] Show pandas datetime in iso format in notebook.

---

mage_integrations/mage_integrations/sources/google_ads/tap_google_ads/streams.py

In a specific type of stream, Google Ads Source Catalog sets a column type as a  string, whereas Mage frontend require a python list ( array ) to filter each result.
Because of this, Schema properties cant be modified while using Batch pipelines ( see linked issue for a real example ). This PR aims to fix this and allow Schema Properties to be modified.
Tested using a local mage instance and a developer google ads account
cc:

Fix Google Ads Catalog to Data Integration Block

---

mage_ai/frontend/api/utils/useDelayFetch.ts
mage_ai/frontend/utils/models/customDesign/useCustomDesign.ts

- The custom design header logo wasn't loading, so this PR fixes it.
- Addresses https://github.com/mage-ai/mage-ai/issues/4570

[jk] Load custom design logo

---

mage_ai/orchestration/db/alembic.ini
mage_ai/orchestration/db/database_manager.py
mage_ai/orchestration/db/migrations/env.py
mage_ai/tests/base_test.py

I noticed that some server logs were not showing up in certain situations. After looking into it, it was happening when the alembic migrations were being run on the main server process. The `env.py` file was overriding the configuration of the root logger which causes most server logs to get hidden. This PR adjusts the `database_manager.run_migrations` methods to tell `env.py` to not configure the loggers, and to manually configure the `alembic` and `sqlalchemy.engine` loggers instead.

[dy] Adjust alembic logger initialization

---

mage_ai/data_preparation/repo_manager.py

Set max width for yaml file to inf to prevent long lines getting wrapped in the yaml file
Ref: https://stackoverflow.com/questions/42170709/prevent-long-lines-getting-wrapped-in-ruamel-yaml
-  Remove the project_uuid from the project metadata.yaml
- Add the following config to project metadata.yaml
```
alert_on:
- trigger_failure
- trigger_passed_sla
slack_config:
webhook_url: "{{ env_var('MAGE_SLACK_WEBHOOK_URL') if env != 'dev' else mage_secret_var('SLACK_ETL_MONITORING') }}"
teams_config:
webhook_url: "{{ env_var('MAGE_TEAMS_WEBHOOK_URL') }}"
```
- Restart the server
- Before the fix, the long line get wrapped and the following error is thrown
- After the fix, the format of the yaml doesn't change and the server can start successfully.
cc:

[xy] Set max width for yaml file to inf.

---

mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/shared/hash.py
mage_ai/tests/shared/test_hash.py

Resolves issue: https://github.com/mage-ai/mage-ai/issues/4526.
We will dig into the `ingress.status.load_balancer` field to get the ingress host if there is no host in the http rules. This can happen if the ingress is updated dynamically by something like AWS LB controller.
cc:

[dy] Show the load balancer ingress host if there is no host in the ingress rules

---

mage_integrations/mage_integrations/sources/google_sheets/README.md
mage_integrations/mage_integrations/sources/google_sheets/__init__.py
mage_integrations/mage_integrations/sources/google_sheets/templates/config.json

Support filtering google sheets by sheet names to reduce google sheets API calls
This PR also fixes the logging
```yaml
path_to_credentials_json_file: /path/to/credentials.json
spreadsheet_id: abcdefg
selected_sheet_names:
- sheet1
- sheet2
- sheet3
```
only specified sheets are selected
cc:

[xy] Support filtering google sheets by sheet names

---

mage_ai/io/clickhouse.py
mage_ai/io/mysql.py
mage_ai/io/sql.py
mage_ai/io/trino.py

Support exporting to mysql with selected columns.
Close: https://github.com/mage-ai/mage-ai/issues/4482
cc:

[xy] Support exporting to mysql with selected columns.

---

docs/design/data-loading.mdx
mage_ai/io/google_cloud_storage.py
mage_ai/io/s3.py

Support exporting files to S3 and GCS.
Close: https://github.com/mage-ai/mage-ai/issues/4339
```python
bucket_name = 'test-bucket'
object_key = 'test_file_copy.csv'
S3.with_config(ConfigFileLoader(config_path, config_profile)).export(
'/home/src/test_file.csv',
bucket_name,
object_key,
)
```
```python
bucket_name = 'test-bucket'
object_key = 'test_file_copy.csv'
GoogleCloudStorage.with_config(ConfigFileLoader(config_path, config_profile)).export(
'/home/src/test_file.csv',
bucket_name,
object_key,
)
```
cc:

[xy] Support exporting files to S3 and GCS.

---

mage_ai/api/resources/SyncResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/preferences.py

Filter out access token from error message when using HTTPS connection. It doesn't seem to consistently get included in the logs (seems to be dependent on the URL format), so trying a change to catch errors and remove the token from the error message.
cc:

[dy] Filter out sensitive config

---

mage_ai/orchestration/pipeline_scheduler.py
mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/tests/orchestration/test_pipeline_scheduler_project_platform.py

This PR combines the pipeline_scheduler_original and pipeline_scheduler_project_platform in one scheduler.
To separate the code logic for single project and project platform, this PR uses the generator method for different scenarios to generate the pipeline with active_schedules.
* gen_pipeline_with_schedules_single_project
* gen_pipeline_with_schedules_project_platform
The core logic of scheduling is same for both scenarios.
This PR still keeps the logic inside `pipeline_scheduler_original.py` to better view the code changes and update the `pipeline_scheduler.py` to only import `pipeline_scheduler_original`. Will delete the other `pipeline_scheduler_project_platform` file completely after the scheduler is proved to be running fine.
cc:

[xy] Combine schedulers.

---

mage_ai/api/resources/LogResource.py
mage_ai/data_preparation/logging/logger_manager.py
mage_ai/data_preparation/models/file.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/db/models/schedules_project_platform.py
mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/tests/orchestration/db/models/test_schedules.py

Separate scheduler logs and pipeline logs to avoid "stale file handle error".
When the scheduler and executor use the same file for logging, it could cause stale handle error since we use RotatingFileHandle.
This PR fixes it by separating the logging files.
cc:

[xy] Separate scheduler logs and pipeline logs.

---

mage_ai/api/resources/PipelineResource.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/tests/data_preparation/models/test_pipeline.py

[jk] Update tag and block cache when cloning pipeline

---

mage_ai/api/resources/PipelineResource.py
mage_ai/frontend/oracle/components/ToggleMenu/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx

Fix the following bugs:
- Pipeline search does not work properly when there is a "Type" filter applied.
- Searching for pipeline from page > 1 does not show any results because they are on page 1. 
- Clicking "Defaults" in pipeline filters does not clear search input.
- Applying pipeline filter sets items per page to 20 instead of 30 (the default items per page).
- Items per page was getting reset to the default 30 amount when applying pipeline filter defaults (items per page should be preserved instead since it is not related to filter defaults).
- Confirmed all bugs mentioned above were fixed locally.

[jk] Various bugfixes for pipeline search and filter

---

mage_ai/io/base.py
mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py
mage_integrations/mage_integrations/destinations/google_cloud_storage/__init__.py

Upgrade of pyarrow package causes the datetime to be written in nanoseconds in S3 and GCS.
This PR updates it to use milliseconds in parquet by default so that there're no problems creating Redshift/BigQuery tables from S3/GCS.
cc:

[xy] Use milliseconds in parquet by default.

---

mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/target.py
mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/target.py

Some random inputs can be written inside a source output file, this can cause some destinations ( mainly singer-sdk based ones) to break. This PR aims to allow these destinations to ignore such inputs.
Now, the destination will check whether the given line starts with a '{' ( meaning it is a possible valid json-L) and validating this Json by running json.loads function
To efectivly test this scenario, i've modified an output file and inserted both random strings and numbers on lines.
Example:
In order that the output file would not be overwritten, i've tested these changes by running the direct destination command inside Mage server Docker.
cc:

Fixed random input inside singer destinations

---

mage_ai/frontend/components/ComputeManagement/index.tsx
mage_ai/frontend/components/PipelineLayout/index.tsx
mage_ai/frontend/components/PipelineRun/shared/buildTableSidekick.tsx
mage_ai/frontend/components/RuntimeVariables/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/components/VersionControl/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

Fix the following bugs:
- There is an extra scrollbar (unstyled) in the Pipeline Editor when vertically scrolling the page.
- Double scrollbar in Sidekick on Triggers/Trigger detail/Pipeline runs page for a pipeline.
- Incomplete height of after DraggableStyle on Compute Management page (visible on hover).
- Confirmed UI issues were fixed locally.

[jk] Fix double scrollbars and draggable height

---

mage_ai/frontend/components/VersionControl/Branches/index.tsx
mage_ai/frontend/components/VersionControl/index.tsx

Fix the following bugs:
- Clicking `<- Remote & Auth` button on Version Control page while on Branches tab redirected to blank tab.
- When initially loading the Version Control page, the two column widths in the before panel did not take up the entire width of the before panel (some blank space was visible).
Addresses github issue https://github.com/mage-ai/mage-ai/issues/4538
Before:
After:

[jk] UI bugfixes on Version Control page

---

mage_ai/orchestration/db/database_manager.py

Add DB locking for postgres and mysql. Mage doesn't work properly with mysql yet, but I added it in case we support it in the future. Each instance of mage will attempt to acquire the lock for 30 seconds after starting, and if it cannot acquire it an error will be thrown.
The code for this is based off of airflow's db locking implementation.

[dy] Add DB locking

---

mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
mage_ai/frontend/components/BlockLayout/index.tsx
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/GlobalDataProductDetail/index.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/pages/overview/index.tsx

Fix the following bugs on the Overview Dashboard:
- Remove the vertical line on the Overview page, Dashboard tab (addresses github issue https://github.com/mage-ai/mage-ai/issues/4652).
- Infinite spinner when creating new chart in project overview dashboard and no data source selected
- Unnecessary extra right padding after before panel when creating/editing a chart
- Before panel draggable border extending into subheader in create/edit chart view
- Unclickable bottom add chart divider line
- Chart name not getting updated on subsequent charts being edited/created after creating/updating an initial chart
Fixed positioning of before draggable border on Global Data Products detail page (similar to bug on Overview dashboard Edit Chart view). Screenshot of the bug below:
UX improvement:
- …

[jk] Bugfixes for Overview Dashboard

---

mage_ai/frontend/pages/index.tsx

- There was a delay in redirecting to the login page from the home page when user authentication was enabled and user went to the homepage. This PR avoids the unnecessary redirect to the `/pipelines`, `/overview`, or `/manage` page and immediately redirects to the `/sign-in` page if user authentication is enabled and the user is not logged in.
- Tested locally in development and also on frontend production build.
- Tested with user authentication enabled and also disabled.
Before (Pipelines dashboard is briefly visible if user was not logged in):
After (User is immediately redirected to login page):

[jk] Redirect to login page immediately

---

mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/AddChartMenu.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/oracle/components/LabelWithValueClicker.tsx
mage_ai/frontend/utils/string.ts

- Clean up chart block default name (was excessively long with timestamp).
- Fix chart width when selecting between half and full width (wasn't re-rendering).
- On very small chart block widths, decrease chart block name width with ellipsis (user can hover to view chart block name in tooltip).
Before (long chart block name / no re-render when selecting half width / no shorted name on very small widths):
After (includes chart block polish):

[jk] Clean up chart block widths in Pipeline Editor

---

mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Fix this bug: Pressing keyboard's "Enter" key on "Save" button for ConfigureBlock popup for new block caused "Block already exists" error since 2 POST requests were being made, one for the button click action and one for the keyboard shortcut event.
- This PR prevents the keyboard shortcut event for a duplicate POST request when the user presses "Enter" while focused on the `Save and...` (i.e. "replace"/"update"/"add") or `Cancel` buttons.
- Tested locally on Chrome, Firefox, and Safari browsers

[jk] Bugfix for save block shortcut

---

mage_integrations/mage_integrations/destinations/postgresql/__init__.py
mage_integrations/mage_integrations/destinations/sql/utils.py

PostgreSQL destination failed when building ALTER TABLE SQL commands. That happened because recently added `ALLOW_RESERVED_WORDS` setting was not being called withing build_alt_commands method.
This PR corrects the `ALLOW_RESERVED_WORDS` setting.
Tested using a PostgreSQL Source and Destination.
A table was modified to force  build_alt_commands method.
cc:

Fixed postgreSQL reserved words

---

mage_integrations/mage_integrations/connections/mysql/__init__.py
mage_integrations/mage_integrations/destinations/mysql/README.md
mage_integrations/mage_integrations/destinations/mysql/__init__.py
mage_integrations/mage_integrations/sources/mysql/README.md
mage_integrations/mage_integrations/sources/mysql/__init__.py
mage_integrations/mage_integrations/tests/destinations/mysql/test_mysql.py

Support extra connection arguments in mysql source and destination.
Close: https://github.com/mage-ai/mage-ai/issues/4579
cc:

[xy] Support extra connection arguments in mysql source and destination.

---

mage_ai/frontend/components/CodeBlock/index.tsx

- Fixes bug where replica block content in Pipeline Editor was not staying synced with the most up-to-date code of the replicated block when minimizing the replica block.
Before (replica block content reverts to stale content after minimizing):
After (replica block content stays up-to-date):

[jk] Sync block contents for replica block when minimizing

---

mage_ai/frontend/utils/models/block.ts

- Fixes this issue: There was an error (screenshot below) causing the app to crash when user was viewing the "Schema properties" of a data stream for an integration block in a standard pipeline. This was due to an unexpected column type (a non-array value received).
- Tested locally. Was able to recreate error and confirmed it no longer appeared.

[jk] Fix "filter is not a function" type error in schema props

---

mage_integrations/mage_integrations/destinations/elasticsearch/__init__.py
mage_integrations/mage_integrations/destinations/elasticsearch/target_elasticsearch/sinks.py
mage_integrations/mage_integrations/destinations/sink.py

Fix a couple of issues with the Elasticsearch destination:
* Test connection will fail if the `properties` field doesn't exist, so adding a safe get there.
* The `logger.debug` command was causing an error when using the `metadata_fields` config value.

[dy] Fix elasticsearch destination

---

mage_ai/data_preparation/models/block/dynamic/variables.py

Fix list index out of range for dynamic blocks.
When setting both regular block and dynamic block as upstream blocks, dynamic child block throws the "list index out of range" error upon execution
```
Error
File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
return self._execute(
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
result = self.block.execute_sync(
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1315, in …
```

[xy] Fix list index out of range for dynamic blocks.

---

mage_integrations/mage_integrations/sources/salesforce/__init__.py
mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/credentials.py

* Set default domain to login for salesforce source.
* Fix unboundlocalerror when it fails to connect
cc:

[xy] Set default domain for salesforce source

---

mage_ai/data_preparation/models/block/__init__.py

- If there are too many dynamic block children, it can cause significant slowdowns on the Pipeline Editor page when trying to render the block outputs. This PR limits the output displayed for dynamic blocks.

[jk] Limit block output for dynamic blocks in UI

---

mage_integrations/mage_integrations/destinations/elasticsearch/target_elasticsearch/target.py
mage_integrations/mage_integrations/destinations/target.py

Handle JSON decode errors when parsing the input file for the elasticsearch destination. This logic is similar to the default file parsing logic in the `Destination` class. However, the Elasticsearch destination has its custom sink and target class, so we can't easily use the existing logic.
cc:

[dy] Handle JSON reading errors for elasticsearch

---

mage_ai/api/policies/BackfillPolicy.py

- Fix backfill policy error when updating "Max concurrent runs" setting for backfill.
Confirmed the error below no longer appears when saving backfill with "Max concurrent runs" input filled:

[jk] Update backfill policy to allow update on settings

---

mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/db/models/schedules_project_platform.py
mage_ai/tests/orchestration/db/models/test_schedules.py

Runs for schedules that used cron intervals were calculating the interval variables, so I'm adding that here.
cc:

[dy] Add interval variables for cron based schedules

---

mage_integrations/mage_integrations/destinations/elasticsearch/target_elasticsearch/target.py

`.warning` doesn't exist on the mage_integrations logger, so changing it to `.info`.
cc:

[dy] Fix logging for elasticsearch destination

---

mage_integrations/requirements.txt

The mageai integration uses [Pyarrow version 14.0.1](https://github.com/mage-ai/mage-ai/blob/ed6ade4ddab27e847baadd0f96bd58e13bfcbb42/mage_integrations/requirements.txt#L26) and [Snowflake connector 3.4.0](https://github.com/mage-ai/mage-ai/blob/ed6ade4ddab27e847baadd0f96bd58e13bfcbb42/mage_integrations/requirements.txt#L37). But snowflake 3.4.0 restricts pyarrow>=10.0.1,<10.1.0. This requires building multiple pyarrow versions when using custom pyarrow build.
[This issue](https://github.com/snowflakedb/snowflake-connector-python/issues/1566) addresses the strict pyarrow version dependency by snowflake. The fix is [released](https://github.com/snowflakedb/snowflake-connector-python/issues/1566#issuecomment-1810831158) in snowflake version 3.5.0. So, we are upgrading to Snowflake Connector …

Pyarrow version conflicts from Snowflake connector

---

mage_ai/orchestration/pipeline_scheduler_original.py

Catch sync schedules exception to prevent scheduler being stopped due to one invalid trigger config.
cc:

[xy] Catch sync schedules exception.

---

mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
mage_ai/frontend/components/BlockLayout/index.tsx
mage_ai/frontend/components/DataTable/index.tsx

- Address issues mentioned in this github issue https://github.com/mage-ai/mage-ai/issues/4691
- Add error messaging when loading block layout item.
Confirmed the following bugs no longer appeared:

[jk] Fix buggy pipeline dashboard

---

mage_ai/orchestration/notification/sender.py
mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/services/slack/slack.py

Add error details to the message. I only add the latest error message if there are multiple errors because there could potentially be a lot of blocks that error.

[dy] Add error stack trace to the message for pipeline run failure

---

docs/api-reference/backfills/overview.mdx
docs/api-reference/backfills/update-backfill.mdx
mage_ai/frontend/components/Backfills/Detail/index.tsx
mage_ai/frontend/components/Backfills/Edit/index.tsx
mage_ai/frontend/components/Backfills/Table/index.tsx
mage_ai/frontend/components/Triggers/Table.tsx
mage_ai/frontend/components/shared/Table/useDeleteConfirmDialogue.tsx
mage_ai/frontend/interfaces/BackfillType.ts
mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/backfills/index.tsx

- Add delete button to backfills table that allows user to delete backfills individually.
- Prevent user from setting a backfill interval unit value less  than 1, which could cause issues loading the backfills.

[jk] Delete backfills

---

docs/integrations/databases/MicrosoftSQLServer.mdx
mage_ai/io/mssql.py
mage_ai/io/sql.py

Add additional logic for exporting data to MSSQL with `unique_conflict_method=UPDATE` and `unique_constraints` set. In order to update records directly, I'm using the `method` parameter of the `to_sql` method. The resulting query will look like this:
```
MERGE [dbo].[test_update] AS t
USING (VALUES
(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
) s([passengerid], [survived], [pclass], [_name], [sex], [age], [sibsp], [parch], [ticket], [fare], [cabin], [embarked], [new_col])
ON s.[passengerid] = t.[passengerid]
WHEN NOT MATCHED THEN
INSERT ([passengerid], [survived], [pclass], [_name], [sex], [age], [sibsp], [parch], [ticket], [fare], [cabin], [embarked], [new_col])
VALUES (s.[passengerid], s.[survived], s.[pclass], s.[_name], s.[sex], s.[age], s.[sibsp], s.[parch], s.[ticket], s.[fare], …
```

[dy] Add unique_conflict_method for mssql

---

mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- In the Pipeline Editor, users weren't able to open a file by clicking on it in the File Browser, which should open it in an Arcane Library popup window. This PR fixes this.
Before (file wont open until you enable Command Center):
After (file does open even before enabling Command Center):

[jk] Allow file to be opened in Pipeline Editor without Command Center enabled

---

mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/index.tsx
mage_ai/frontend/components/RuntimeVariables/index.style.tsx
mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.style.ts
mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

- Make horizontal scrollbar visible when there are many streams in the Integration Pipeline edit page (may not be intuitive to users that they can scroll horizontally to view more streams).
- There was an unnecessary unstyled scrollbar (see screenshot below) in the Runtime Variables section of a pipeline's Trigger page, so this PR removes it and styles the scrollbar for condensed Sidekick widths.
Horizontal scrollbar beneath stream button tabs:
No unnecessary scrollbar:

[jk] Scrollbar polish

---

mage_ai/frontend/components/ApplicationManager/index.style.tsx
mage_ai/frontend/components/CommandCenter/index.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- The bottom 20px of a page was unclickable (e.g. horizontal scrollbars at the page bottom could not be clicked on) due to the height of the hidden dock used for managing applications causing a z-index issue. This PR decreases the dock height so bottom elements can be interacted with.
- Also fix some spacing and scrollbar issues in the Sidekick on the Pipeline Editor page.
Bottom horizontal scrollbars can be clicked (previously, could not interact with them):

[jk] Bugfix dock overlay

---

mage_integrations/mage_integrations/destinations/redshift/__init__.py

Remove Redshift stl insert query.
Close: https://github.com/mage-ai/mage-ai/issues/4663
cc:

[xy] Remove Redshift stl insert query.

---

mage_ai/frontend/components/Interactions/InteractionSettings.tsx
mage_ai/frontend/components/PipelineInteractions/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- There was a client error when user tried to add a permission in the interactions settings before the interactions were done loading. This PR prevents the error but also adds a load state for the interactions settings so that users are not able to prematurely create interactions or permissions before the existing interactions are loaded, which could result in overwriting existing interactions/permissions.
- Decrease fetch delay for interactions from 6 seconds to 3 seconds.
Pipeline with no interactions (zero state):
Pipeline with existing interactions:

[jk] Avoid client error when making request before interactions are done loading

---

mage_integrations/README.md
mage_integrations/mage_integrations/destinations/trino/README.md
mage_integrations/mage_integrations/destinations/trino/connectors/base.py
mage_integrations/mage_integrations/destinations/trino/templates/config.json

Mage version
0.9.65
Describe the bug
Trino delta lake setup with glue metastore unable to delete underlying data from storage when temp tables are dropped. It happens because when property 'with location' is used to create tables, they are considered as external tables. So when these tables are dropped, it drops the meta information but does not delete underlying data. Which means when next time the pipeline runs, it already finds the data sitting in the location specified and raises error about using system.register_table() function.
To reproduce
Setup trino delta lake connector with glue metastore
Provide a location parameter in the trino configuration
Run a integration pipeline once (It should succeed since this is the first time and temp table does not exist)
Run the integration …

Trino temp table location fix - Fixes issue https://github.com/mage-ai/mage-ai/issues/4738

---

.gitignore
mage_integrations/mage_integrations/sources/stripe/__init__.py

Issue with None being passed to singer bookmarks utilities when it expects a dict in-stead
Local machine
- [ x] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [x ] I have performed a self-review of my own code
cc:

bug fix with stripe sync

---

mage_integrations/mage_integrations/destinations/snowflake/__init__.py

Fix alter Snowflake table with lower_case=false
It falis to match the column name with existing column name when lower_case=false
cc:

[xy] Fix alter Snowflake table with lower_case=false

---

mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx

- Update block runs column indexes and mapping used for block run sorting (since the block runs table columns had been rearranged).
- Locally
cc:

[jk] Fix block run sorting

---

mage_ai/frontend/components/Logs/Detail/index.tsx

- There was an issue when expanding a log message that displayed an incorrectly formatted log message similar to this:
```
{
"type": "pre",
"key": null,
"ref": null,
"props": {
"children": "some_string_value"
},
"_owner": null
}
```
The expanded log message should only contain the contents of this object's `props.children` value. This PR adds a check to render these contents only instead of including this entire object.
cc:

[jk] Add check to avoid rendering of invalid JSX element

---

docs/design/data-pipeline-management.mdx
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/storage/gcs_storage.py
mage_ai/data_preparation/storage/local_storage.py
mage_ai/data_preparation/storage/s3_storage.py
mage_ai/data_preparation/variable_manager.py
mage_ai/services/aws/s3/s3.py

- If a user's block returned a list of many values (versus a list of a list with many values), it could cause significant slowdowns in the browser when loading the pipeline because a block output file is created for each value in the output list. For example, a block returning a list of 1000 items creates 1000 output files, which takes a long time to read so many files and resulting in an unintended large pipeline response.
- This PR limits the number of output files' contents included in the pipeline response to 10 files (previously all output files' contents were included).
- Tested using the same block that returned a list with 20k items
Before (took ~34 seconds to load the pipeline/page):
After (took <1 second to load the pipeline/page):

[jk] Limit number of block output files read and included in pipeline response

---

mage_ai/frontend/components/CodeEditor/index.style.tsx

- Context menu of code block editor was difficult to read so this PR improves its visibility.
- Tested on Chrome, Firefox, and Safari
Before:
After:
cc:

[jk] Increase visibility of code block context menu

---

mage_ai/io/bigquery.py

Fix exporting dataframe to bigquery.
When dataframe contains column that has None value. The data type is detected as `dtype('O')` when calling Bigquery client's load_table_from_dataframe method, and thus throw the following warning and set wrong schema in bigquery table.
```
/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_pandas_helpers.py:533: UserWarning: Pyarrow could not determine the type of columns: xxx.
```
This PR fixes the issue by replacing the None values with np.NaN values before exporting.
cc:

[xy] Fix exporting dataframe to bigquery.

---

mage_ai/io/oracledb.py

Following up on this issue: https://github.com/mage-ai/mage-ai/issues/4654 to add oracle thick mode support in standard pipeline.
Mage UI to create standard pipeline and successfully load data:
cc:

[xh] Oracle add thick mode support in standard pipeline

---

mage_ai/orchestration/db/__init__.py

Only show sql logs in debug environment. Users setting `ENV=dev` get the excessive sql logs, which could be annoying.
cc:

[xy] Only show sql logs in debug environment.

---

mage_ai/data_preparation/executors/k8s_block_executor.py
mage_ai/data_preparation/executors/k8s_pipeline_executor.py
mage_ai/services/k8s/job_manager.py

Close: https://github.com/mage-ai/mage-ai/issues/4488
Support dynamic namespace in k8s executor by interpolating vars in the namespace
https://docs.mage.ai/development/variables/overview
cc:

[xy] Interpolate global vars in k8s executor namespace

---

docs/mint.json
docs/streaming/sources/mongodb.mdx
mage_ai/streaming/sources/mongodb.py

- Added an additional configuration option to the MongoDB streaming source to enable full_document options available on the pymongo.Collection.watch() method.
- Added documentation for the MongoDB streaming source, which was previously missing.
Existing unit tests pass, no significant changes to tests needed.
cc:

[enhancement] mongodb stream full_document config option

---

mage_ai/frontend/components/Sessions/SignForm/index.tsx
mage_ai/frontend/pages/index.tsx

When the oauth flow is started, the /oauth and /sign-in routes will be accessed and the user may not be logged in. Thus, we should ignore the auth checks that we do in the `pages/index.tsx` file.

[dy] Fix SSO sign in for frontend build

---

mage_ai/api/resources/PipelineRunResource.py
mage_ai/frontend/components/Triggers/Detail/index.tsx

The `/pipeline_runs` query seems to be fetching cached data which is fine in most cases, but if there is a running pipeline run, the status of the pipeline run can sometimes get stuck. I'm added a check to expire a pipeline run in the session if it is in progress, so that the status can be properly updated in future queries.

[dy] Expire certain pipeline runs

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/integration/__init__.py
mage_ai/frontend/components/CodeBlockV2/Output/index.tsx

- Prevent table rendering error when columns and rows undefined.
- Fix error (`DestinationBlock.update() got an unexpected kwarg 'detach'`) when trying to rename a destination block in an integration pipeline.
- Include block pipelines in data integration pipeline destination block (previously wasn't included, which was causing the "Renaming this block will affect X pipelines. The renamed block may need to be re-added to the shared pipeline(s)." warning to not appear when renaming the destination block specifically).
- Tested locally and confirmed errors no longer appear
cc:

[jk] Bugfixes - table render / rename destination block

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/orchestration/db/models/schedules.py

When getting `pipeline_tags` for pipeline runs, we are initializing the entire pipeline which can sometimes take a long time. This PR changes the `pipeline_tags` property to fetch the tags from the pipeline config directly.

[dy] Load pipeline tags from config

---

mage_ai/api/resources/BlockLayoutItemResource.py
mage_ai/api/resources/BlockResource.py
mage_ai/api/resources/CacheItemResource.py
mage_ai/api/resources/PageBlockLayoutResource.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/block_factory.py
mage_ai/data_preparation/models/block/dbt/block.py
mage_ai/data_preparation/models/block/global_data_product/__init__.py
mage_ai/data_preparation/models/block/platform/mixins.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/shared/path_fixer.py
mage_ai/tests/data_preparation/models/block/dbt/test_block.py
mage_ai/tests/data_preparation/models/block/dbt/test_block_sql.py
mage_ai/tests/data_preparation/models/block/dbt/test_block_yaml.py
mage_ai/tests/data_preparation/models/test_block.py
mage_ai/tests/settings/models/test_configuration_option.py

Improve the performance of loading dbt blocks.
* Move Block.block_class_from_type to BlockFactory to resolve circular dependency instead of putting import statement in class method. If the import statement is inside the class method, it will indeed get executed every time the method is called. This can lead to performance overhead, especially if the method is called frequently.
* Update the `add_absolute_path` to take care of the case of old dbt block so that it doesn't always need to do direcotry scan.
cc:

[xy] Improve the performance of loading dbt blocks.

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlockV2/constants.ts
mage_ai/frontend/components/CodeBlockV2/dbt/Configuration/index.tsx
mage_ai/frontend/components/CodeBlockV2/dbt/useCodeBlockProps.tsx
mage_ai/frontend/components/CodeBlockV2/useCodeBlockComponents.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx

- The Pipeline Editor page was making a `configuration_options` request for each dbt block in the pipeline upon initial load (e.g. 50 dbt blocks would make 50 requests). This PR mitigates the number of requests made by making a single `configuration_options` request upon initial load.
Load pipeline with dbt blocks (2 sql and 1 yaml):
cc:

[jk] Avoid N dbt config option requests for N blocks on Pipeline Editor

---

mage_ai/services/spark/spark.py

Raise ImportError when spark is not supported since Spark API is only catching ImportError: https://github.com/mage-ai/mage-ai/blob/master/mage_ai/services/spark/api/base.py#L51
cc:

[xy] Raise ImportError when spark is not supported.

---

docs/integrations/observability/alerting-discord.mdx
docs/integrations/observability/alerting-email.mdx
docs/integrations/observability/alerting-slack.mdx
docs/integrations/observability/alerting-telegram.mdx
mage_ai/api/monitors/BaseMonitor.py
mage_ai/orchestration/notification/sender.py
mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/services/slack/slack.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

The slack notifications were not being sent out properly when the stack trace was included in the error message. I also think it's a good idea to include the stack trace as an additional parameter `stacktrace` instead of including it with the existing `error` parameter. I also truncate the error message if it has too many lines in case the clients can't handle it.

[dy] Fix slack notifications with stacktrace

---

mage_ai/streaming/sources/base.py
mage_ai/streaming/sources/kafka.py

Test kafka connection when intiializing the consumer.
Close: https://github.com/mage-ai/mage-ai/issues/4803
cc:

[xy] Test kafka connection when initializing the consumer.

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlockV2/dbt/Configuration/index.tsx
mage_ai/frontend/components/CodeBlockV2/dbt/constants.tsx
mage_ai/frontend/components/CodeBlockV2/useCodeBlockComponents.tsx
mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
mage_ai/frontend/tests/base.ts
mage_ai/frontend/tsconfig.json
mage_ai/frontend/utils/array.ts

- Allow dbt command in dbt v2 code block to be configurable.
- Remove duplicate "targets" appearing in select dropdown in dbt v1 code block header
- Since dbt blocks are the only block type using the v2 code block, remove the `Code block v2` project setting and only use `Dbt v2` project setting to avoid confusion. Otherwise, users may not know how to switch between dbt code block v1 and v2.
- Update typescript configuration (tsconfig.json) from es5 to es6 (typescript errors were appearing for correct es6 syntax).
- Rebuilt frontend production build without issues
- dbt command input added to dbt yaml block config:
cc:

[jk] Configure dbt v2 yaml block and other dbt code block improvements

---

docs/development/observability/logging.mdx
mage_ai/data_preparation/logging/gcs_logger_manager.py

Make path_to_credential optional in GCS logger.
Close: https://github.com/mage-ai/mage-ai/issues/4829
cc:

[xy] Make path_to_credential optional in GCS logger.

---

mage_ai/data_preparation/storage/gcs_storage.py

Fix writing polars dataframe to gcs storage.
Close: https://github.com/mage-ai/mage-ai/issues/4100
cc:

[xy] Fix writing polars dataframe to gcs storage.

---

mage_ai/cache/tag.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/pages/pipelines/index.tsx

- Remove pipeline tag from filter dropdown on Pipelines Dashboard if that tag is no longer used by any pipelines.
- Update tag cache when removing tags from a pipeline (previously the tag cache was not getting updated in this scenario).
Tag is removed from pipeline filters after the only pipeline using it is deleted:
The pipelines dashboard reflects a pipeline's updated tags after removing one of its tags:

[jk] Bugfix pipeline tag cache

---

mage_ai/data_preparation/templates/constants.py
mage_ai/io/export_utils.py
mage_ai/io/oracledb.py
mage_ai/io/sql.py

This PR add export function to oracle io, so data can be exported to oracle destination
Mage UI
UI select Oracle DB exporter:
Oracle DB destination code:
Oracle DB exported table (1) including newly created table (2) also tested with new rows added:
Oracle DB exported table with datetime type:
cc:

[xh]Oracledb add export

---

mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Remove `block_uuid` query param when selecting/deselecting block in Pipeline Editor. The `block_uuid` query param is used to automatically select and focus a block when redirecting to the Pipeline Editor page, but if it's not removed when selecting other blocks, there can be issues with unexpected refocusing of the block with the uuid in the query param. This PR fixes this issue.

[jk] Clear block_uuid query param when selecting new block

---

mage_integrations/mage_integrations/destinations/clickhouse/target_clickhouse/target.py
mage_integrations/mage_integrations/destinations/elasticsearch/target_elasticsearch/sinks.py
mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/target.py
mage_integrations/mage_integrations/destinations/opensearch/target_opensearch/target.py
mage_integrations/mage_integrations/destinations/sink.py

Some targets did not properly catch JSON parsing issues, so updating those targets to handle that.
cc:

[dy] Catch JSON decode errors in mage targets

---

mage_ai/frontend/components/Terminal/index.tsx
mage_ai/frontend/components/Terminal/useTerminal/index.tsx

- The blue font in the terminal was hard to read, so this PR replaces the blue font with the more legible cyan font.
- Limit the terminal output in the UI to 2500 lines. Including more starts to hurt app performance, at least in development mode (e.g. typing in the terminal becomes very laggy to the point of being basically unusable).
Before (the "notice" text has blue font):
After (the "notice" text has cyan font):
cc:

[jk] Replace blue font with cyan in terminal

---

mage_ai/data_preparation/models/block/__init__.py

- Fix `Block object has no attribute 'get_block'` error when detaching block.

[jk] Replace Block reference with BlockFactory

---

mage_ai/orchestration/job_manager.py
mage_ai/orchestration/queue/celery_queue.py
mage_ai/orchestration/queue/process_queue.py
mage_ai/orchestration/queue/queue.py
mage_ai/server/scheduler_manager.py
mage_ai/tests/orchestration/queue/test_process_queue.py

Kill all jobs on scheduler crash so that the scheduler can successfully restart.
cc:

[xy] Kill all jobs on scheduler crash.

---

mage_ai/data_preparation/models/variable.py

Fix spark dataframe read error.
Do not write json file in spark data directory to avoid read error
```
java.lang.RuntimeException: file:/home/src/mage_data/.../output_0/type.json is not a Parquet file. 
Expected magic number at tail, but found [109, 101, 34, 125]
```
cc:

[xy] Fix spark dataframe read error.

---

mage_ai/frontend/pages/pipeline-runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

- The filters toggles on the `/pipeline-runs` and `/pipelines/[pipeline_uuid]/triggers` were being reset unexpectedly due to the filter component getting re-rendered with stale data every time a certain resource was being fetched. This PR fixes this issue.
Before (filters periodically reset):
After (filter state persists):
cc:

[jk] Fix filters from being reset when items fetched

---

.github/workflows/build_and_test.yml
mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/templates/repo/metadata.yaml
mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/frontend/tests/base.ts

- Remove usage stats modal.
- Locally

[jk] Usage stats modal

---

mage_ai/orchestration/queue/process_queue.py
mage_ai/server/scheduler_manager.py

Fix dangling process when reloading webserver.
When tornado server is reloaded, in addition to stop the scheduler, we should also kill the running jobs so that there're no duplicate jobs running.
cc:

[xy] Fix dangling process when reloading webserver.

---

mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/frontend/playwright.config.ts
mage_ai/frontend/tests/base.ts
mage_ai/frontend/tests/functionality.spec.ts
mage_ai/frontend/tests/pipeline_runs.spec.ts
mage_ai/frontend/tests/utils.ts

This PR creates e2e test which runs the `default_repo`'s `example_pipeline` once to ensure pipelines could run smoothly.
- Tests pass on github.

[edw] e2e: ensure example pipeline runs smoothly

---

mage_ai/data_preparation/shared/utils.py
mage_ai/frontend/components/users/UserDetail.tsx
mage_ai/frontend/pages/settings/workspace/users/index.tsx
mage_ai/orchestration/db/models/oauth.py
mage_ai/server/server.py
mage_ai/settings/server.py
mage_ai/tests/orchestration/db/models/test_oauth.py
mage_ai/tests/server/test_server.py

In some cases, the same project name can be used for multiple workspaces, so the permissions will be added to the same role. This PR changes the role name to use the project uuid instead. I originally used the project name to create the default roles for readability, but it has some limitations.
cc:

[dy] Use project uuid for workspace default permissions

---

mage_ai/data_preparation/models/utils.py
mage_ai/data_preparation/models/variable.py

In issue https://github.com/mage-ai/mage-ai/issues/4682, the `__write_parquet` method is failing when there is a mix of string and integer values in a column. If we just cast the column to string, then the `__write_parquet` method should work properly.
@wangxiaoyou1993 let me know if this makes sense. I'm not sure what the best solution is here.
cc:

[dy] Cast ambiguous columns to strings

---

.github/pull_request_template.md
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/FileHeaderMenuItem.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/storage/constants.ts

- Add "View" menu item in Pipeline Editor for hiding block output after block is executed, which can avoid rendering excessive block output

[jk] Block output view option

---

mage_ai/orchestration/pipeline_scheduler_original.py

Refresh block run statuses before fetching crashed block runs.
This prevents block runs keep being restarted  (especially when there're a lot of dynamic child blocks)
cc:

[xy] Refresh block run statuses before fetching crashed block runs.

---

mage_ai/frontend/api/utils/useDelayFetch.ts
mage_ai/frontend/components/Applications/PortalTerminal/index.tsx
mage_ai/frontend/components/Files/useFileComponents.tsx

- There were unnecessary `files` requests being made when calling the `useFileComponents` hook, specifically when not using the ArcaneLibrary component specifically. If the ArcaneLibrary component wasn't being used, then we could reduce the number of `files` requests being made. This PR implements this fix.
- Confirmed `/api/files?pattern=%2F.csv%24%7C.json%24%7C.md%24%7C.py%24%7C.r%24%7C.sh%24%7C.sql%24%7C.txt%24%7C.yaml%24%7C.yml%24%2F&flatten=true&exclude_pattern=/__init__.py|metadata.yaml|interactions.yaml|.DS_Store/&exclude_dir_pattern=/compiled|__pycache__` request was only being made when opening the Arcane Library and not in other pages using the FileBrowser component.
cc:

[jk] Only make specific files request with ArcaneLibrary

---

mage_ai/data_preparation/templates/data_exporters/mysql.py
mage_ai/io/base.py
mage_ai/io/bigquery.py
mage_ai/io/mysql.py
mage_ai/io/snowflake.py

Add ability to use upsert in MySQL, BigQuery, and Snowflake IO classes. The implementation is based on the destinations in the mage_integrations module, but modified slightly to work with the IO classes.
cc:

[dy] Add upsert to MySQL, BQ, and Snowflake

---

mage_ai/data_preparation/models/block/data_integration/mixins.py
mage_ai/orchestration/db/models/schedules.py

Scheduler checks in a loop whether a block is an integration block. This instantiates Project object in each call which is quite slow and adds considerably, esp. when many blocks are in the pipeline.
The change caches the pipeline project outside of the loop. The method now takes the cached object as an optional parameter and avoids lookups.
Tested in my local project.
cc:

Caching pipeline_project outside of loop to avoid multple lookups

---

mage_ai/frontend/pages/index.tsx

- There was an unnecessary pipeline_runs request from the `mage_ai/frontend/pages/index.tsx` file being made on most pages specifically when using the frontend production build. That pipeline_runs request was to check if the user's project had at least 1 pipeline run, and if it did not, it could mean that it was a new project and would redirect users to the Pipelines Dashboard (instead of the Overview page). Since the request could potentially affect app performance, it was removed in order to maximize app performance.
- As a result, the root page of the app no longer redirects to the Pipelines dashboard for new projects (where there are no pipeline runs yet), just the Overview dashboard, which should not affect the user experience significantly.
- Built frontend production build locally …

[jk] Remove pipeline_runs request appearing on different pages

---

mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/utils/models/project/useProject.ts

- If the project's header breadcrumbs were not visible, it could be indicative of an issue with the project's `metadata.yaml` configuration file. However, there wasn't any visibility into this error, so this PR displays the error in a popup and also shows `Error loading project configuration` in the header.
- May help identify issues related to this github issue: https://github.com/mage-ai/mage-ai/issues/4880
- Tested with an invalid project metadata.yaml config file:
- Tested on both single project and multi-project platform.
cc:

[jk] Add visibility into project config loading errors

---

mage_ai/frontend/components/ServerTimeDropdown/index.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/pages/sign-in.tsx

- Certain components in the Header were visible or actions able to be performed on the Sign In page, which would not work due to the user not being signed in. This PR hides these actions/components in the Header to avoid confusion.
- Confirmed when user is not logged in, they cannot go to project settings from the Sign-in page UI, launch the command center, or adjust timezone settings.

[jk] Hide header actions on sign-in page

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/data_preparation/models/block/extension/utils.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/server/websocket_server.py

Support alerts and limited retries in streaming pipeline.
Close: https://github.com/mage-ai/mage-ai/issues/4840
Close: https://github.com/mage-ai/mage-ai/issues/4842
When retry_config is set in streaming pipeline's metadata.yaml at pipeline level, only retry the streaming pipeline with limited times and send alerts when pipeline fails.
retry config
retry logs
alerts
cc:

[xy] Support alerts and limited retries in streaming pipeline.

---

mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler_original.py

Currently, if one pipeline's metadata.yaml is invalid, the whole scheduler gets crashed.
Catch pipeline error in scheduler to avoid scheduler crash.
cc:

[xy] Catch pipeline error in scheduler.

---

mage_ai/data_preparation/models/block/dynamic/child.py
mage_ai/data_preparation/models/block/dynamic/variables.py

Fix dynamic block with great expectation block.
* Don't run great expectation block in the DynamicChildController class
* When running great expectation block in dynamic child block, don't pass the entire output
Close: https://github.com/mage-ai/mage-ai/issues/4770
cc:

[xy] Fix dynamic block with great expectation block.

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.style.tsx
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/utils/string.ts

- Using a number as the first character of a block name could cause confusion because the block uuid replaces the number with `letter_n`. For example, if a block was named `1example_block`, its block uuid would be `letter_1example_block`. In order to make the block naming consistent with the block uuids, this PR does not allow numbers to be used as the first character of a block name in the UI. If the user enters a number as the first char, the "Save" button gets disabled and warning appears.

[jk] Disallow numbers as first character of block names

---

mage_ai/api/resources/PipelineScheduleResource.py
mage_ai/data_preparation/models/triggers/__init__.py

- Renamed triggers saved in code (i.e. saved in `triggers.yaml` file) would update the pipeline schedule in the db, but not the trigger in the trigger config file, resulting in the original trigger being recreated. This PR fixes this so the trigger saved in code is not duplicated.
- Addresses github issue https://github.com/mage-ai/mage-ai/issues/4862
cc:

[jk] Prevent renamed triggers in code from being duplicated

---

mage_ai/frontend/components/Triggers/Table.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_ai/frontend/pages/triggers/index.tsx

- Improve Triggers table column order.
- Fix `Description` column widths for very long descriptions.
- Fix typo for "Sort runs by" text on project-wide Triggers page (these are triggers, not runs).
- Change "N/A" to a simple "-" in `Latest status` column for improved differentiation from status text.
- Show spinner on project-wide Triggers page when pipeline schedules are loading (table previously showed "No triggers available" text when pipeline schedules were loading).
- Confirmed fixes locally
Old Triggers table column order:
Updated Triggers table column order:
cc:

[jk] Triggers table UI fixes

---

mage_ai/data_preparation/executors/k8s_block_executor.py
mage_ai/data_preparation/executors/k8s_pipeline_executor.py

Support interpolating trigger name in k8s job name by using `{trigger_name}` in the k8s executor config's `job_name_prefix` field.
Close: https://github.com/mage-ai/mage-ai/issues/4910
cc:

[xy] Support interpolating trigger name in k8s job name.

---

mage_integrations/mage_integrations/destinations/base.py

Check type key in anyOf array objects.
Close: https://github.com/mage-ai/mage-ai/issues/4903
The MongoDB source has this schema: https://github.com/mage-ai/mage-ai/blob/master/mage_integrations/mage_integrations/sources/mongodb/tap_mongodb/sync_strategies/common.py#L259
`list_schema = {"type": "array", "items": {"anyOf": [{}]}}`
cc:

[xy] Check type key in anyOf array objects.

---

mage_ai/orchestration/pipeline_scheduler_original.py

Only send failure notification when pipeline run status is failed.
When pipeline time out and the timeout_status is CANCELLED, don't send the failure notification.
Close: https://github.com/mage-ai/mage-ai/issues/4945
cc:

[xy] Only send failure notification when pipeline run status is failed.

---

.gitignore
mage_integrations/mage_integrations/destinations/sql/utils.py
mage_integrations/mage_integrations/destinations/trino/connectors/deltalake.py
mage_integrations/mage_integrations/destinations/trino/connectors/iceberg.py

Issue 1 - Iceberg connector did not work with Array type fields. The issue was fixed for delta lake last month by @wangxiaoyou1993 but iceberg was still pending.
Issue 2 - Single quotes in text were not being handled by the connector causing issues with Insert commands. This PR fixes that issue
Issue 3 - Code repetition which is an anti pattern. There was no difference at all between delta lake and iceberg code so simply reusing the delta lake class makes it easy to maintain and debug.
Issue 4 - Delta lake and Iceberg default item type set as string for array fields. Fixes issue - [4895](https://github.com/mage-ai/mage-ai/issues/4895)
Test locally.
- [X ] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [ X] I have performed a self-review of my own code
- [ …

Trino iceberg and delta lake array issues fix along with issue 4895 and other improvements

---

mage_ai/server/api/downloads.py

Fix downloading xlsx file.
Got the error when downloading xlsx
```
Error fetching file filename.xlsx.
'utf-8' codec can't decode byte 0x8f in position 22: invalid start byte
```
Update the file open mode to `rb` for xlsx file to fix the issue
cc:

[xy] Fix downloading xlsx file.

---

mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
mage_ai/frontend/components/DependencyGraph/BlockNode/utils.ts
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/DependencyGraph/utils.ts

- There was a "Layout Error: TypeError: Cannot read properties of null (reading 'p')" preventing the dependency tree in the Pipeline Editor from rendering when block dependencies were added in certain scenarios (e.g. downstream connection added to a block two levels down in a block grouping within a grouping)
- Example of what could cause the dependency tree rendering issue (among other combinations):
- Confirmed dep tree would render properly even with downstream connections that previously prevented the dep tree from rendering, such as:
cc:

[jk] Bugfix - Dependency tree layout

---

mage_ai/api/policies/BackfillPolicy.py
mage_ai/api/presenters/BackfillPresenter.py
mage_ai/frontend/components/Backfills/Detail/index.tsx
mage_ai/frontend/components/Backfills/Table/index.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/interfaces/BackfillType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/backfills/index.tsx
mage_ai/orchestration/db/models/schedules.py

- Prevent user from being able to edit backfill once backfill has started. It can be confusing if the user edits a backfill's interval type/units after a backfill has started, since it would not affect the number of associated pipeline runs created.
- Add status count (i.e. `Ready`, `Running`, `Cancelled`, `Completed`, and `Failed`) columns for all statuses.
- Rearrange columns to better display most relevant data.
Before:
After:
cc:

[jk] Backfills table improvements

---

mage_integrations/mage_integrations/sources/postgresql/__init__.py

Improve the performance of Postgres source metadata query.
The original query uses the complex views, which could be very slow (even timeout) for large database.
- Reduce the time from 25ms to 8ms for local database.
- For large database, reduce the time from 100s to 0.2s.
cc:

[xy] Improve the performance of Postgres source metadata query.

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py

Fix logging tags for streaming pipeline run. Include pipeline_run_id in the tags so that the logs can show in the pipeline run logs page.
cc:

[xy] Fix logging tags for streaming pipeline run.

---

mage_ai/orchestration/notification/sender.py

Catch notification send exceptions so that notification send exception doesn't break scheduler.
When there're notification exceptions, the running block run process is not killed properly. https://github.com/mage-ai/mage-ai/blob/master/mage_ai/orchestration/pipeline_scheduler_original.py#L327-L353
This PR fixes that issue.
cc:

[xy] Catch notification send exceptions.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py

Use executor type from pipeline level when block level executor_type is not set
Close: https://github.com/mage-ai/mage-ai/issues/4965
cc:

[xy] Use executor type from pipeline level when block level executor is not set

---

docs/production/configuring-production-settings/compute-resource.mdx
mage_ai/services/aws/ecs/ecs.py

ECS executor configs have a setting `wait_timeout`  that tells the executor how long to wait for the task to complete before retrying. The `mage_ai.services.aws.ecs.run_task` function has been updated to check if this value is set to -1. If so, it will skip waiting for the task to complete.
_There was no test coverage for wait functionality to update for this change. Existing tests for ECS config remain unaffected._
cc:

[Enhancement] Optionally Disable Wait Timeout in ECS Config

---

mage_ai/frontend/components/Files/useFileComponents.tsx
mage_ai/frontend/components/PipelineDetail/FileTabs/Tab.tsx

- When clicking `Cancel` in the confirmation dialogue for closing an unsaved, modified file in the File Editor, user would expect the unsaved file to remain open so they could save it, but the file was closing instead, causing unsaved changes to be lost. This PR fixes this so that clicking `Cancel` behaves as expected.
- Addresses github issue https://github.com/mage-ai/mage-ai/issues/4882
- Also fix blocked "Close" button tooltip in file tab.
Before (clicking cancel closes the file without allowing user to save changes):
After (clicking cancel keeps the file open as expected):

[jk] Cancel unsaved modified file dialogue

---

mage_ai/data_preparation/models/block/__init__.py

Close: https://github.com/mage-ai/mage-ai/issues/4966
cc:

[xy] Always set logger in different blocks separately.

---

mage_ai/services/k8s/config.py
mage_ai/services/k8s/utils.py
mage_ai/tests/services/k8s/test_job_manager.py

Fix parsing affinity config in k8s config.
Close: https://github.com/mage-ai/mage-ai/issues/4874
```
service_account_name: mageai
pod:
tolerations:
- key: "key2"
operator: "Equal"
value: "value2"
effect: "NoSchedule"
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: kubernetes.io/os
operator: In
values:
- windows
```
The pod is created with the correct spec
cc:

[xy] Fix k8s affinity parsing.

---

mage_ai/frontend/components/MultiColumnController/index.style.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/FileHeaderMenuItem.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/StatusFooter/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/storage/constants.ts

- Add `Disable autosave` option to "File" header menu in Pipeline Editor to turn off pipeline autosave, which automatically saves the pipeline if there are changes detected every 10 seconds. This could potentially mitigate issues with stale pipelines autosaving and overwriting newer data if there are multiple tabs of the same pipeline open in the Pipeline Editor.
- Locally
cc:

[jk] Allow disabling pipeline autosave

---

mage_ai/orchestration/job_manager.py

Delay initializing the queue.
Fix this error when installing Mage via pip
```
raise RuntimeError('''
RuntimeError:
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.
This probably means that you are not using fork to start your
child processes and you have forgotten to use the proper idiom
in the main module:
if __name__ == '__main__':
freeze_support()
...
The "freeze_support()" line can be omitted if the program
is not going to be frozen to produce an executable.
To fix this issue, refer to the "Safe importing of main module"
section in https://docs.python.org/3/library/multiprocessing.html
```
cc:

[xy] Delay initializing the queue.

---

mage_ai/io/bigquery.py

Fix None Bigquery database error.
```
BadRequest: 400 Invalid project ID 'None'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
```
This is an error introduced in version 0.9.69 https://github.com/mage-ai/mage-ai/pull/4769
cc:

[xy] Fix None Bigquery database error.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/tests/data_preparation/models/block/sql/utils/test_shared.py

Fix extracting table name from INSERT statement in SQL block.
* When using env variable in the SQL block, the table name is not extracted correctly.
* When using `INSERT IGNORE INTO` syntax in MySQL SQL block, the table name is not extracted correctly.
* When putting multiple spaces between INSERT and INTO, the table name is not extracted correctly.
```sql
INSERT IGNORE INTO {{ env_var("default_fact_schema") }}.test_table(
columnA,
columnB
)
SELECT
columnA,
columnB
FROM {{ env_var("default_stage_schema") }}.stage_table as s;
```
cc:

[xy] Fix extracting table name from INSERT statement in SQL block.

---

requirements.txt

given the bleow requirements.txt in a mage project:
> mage-ai[mysql]
> dlt
it bails with:
> ERROR: Cannot install -r requirements.txt (line 2), None, dlt==0.4.9 and mage-ai because these package versions have conflicting dependencies.
>The conflict is caused by:
>    mage-ai 0.9.70 depends on pytz==2022.2
>    great-expectations 0.18.12 depends on pytz>=2021.3
>    dlt 0.4.9 depends on pytz>=2022.6
>    mage-ai 0.9.70 depends on pytz==2022.2
>    great-expectations 0.18.12 depends on pytz>=2021.3
>...
>    dlt 0.2.7 depends on pytz>=2022.6
>    mage-ai 0.9.70 depends on pytz==2022.2
>    great-expectations 0.18.12 depends on pytz>=2021.3
>
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve …

relax pytz version requirements

---

mage_ai/cli/main.py

Not show locals in CLI exception.
When there's an exception connecting to database, the password might be shown in the exception's local values. This PR 
fixes that.
Reference: https://typer.tiangolo.com/tutorial/exceptions/#disable-local-variables-for-security
cc:

[xy] Not show locals in CLI exception.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/data_integration/mixins.py

Catch yaml interpolation error in Pipeline API.
Close: https://github.com/mage-ai/mage-ai/issues/4998
cc:

[xy] Catch yaml interpolation error.

---

mage_ai/io/redshift.py

Not run insert query for empty dataframe in Redshift io export method.
Running insert query without value causes errors.
cc:

[xy] Not run insert query for empty dataframe.

---

mage_ai/api/resources/GitBranchResource.py
mage_ai/data_preparation/git/api.py
mage_ai/frontend/components/VersionControl/Remote/index.tsx
mage_ai/frontend/components/VersionControl/constants.ts
mage_ai/frontend/components/VersionControl/index.tsx

Being able to prune the remote is useful when we want to delete references to deleted branches. This PR adds the ability to select a "prune" option when performing a fetch operation.
cc:

[dy] Add prune option for fetch

---

docs/mint.json
docs/streaming/destinations/oracledb.mdx
mage_ai/data_preparation/templates/data_exporters/streaming/oracledb.yaml
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/streaming/sinks/oracledb.py
mage_ai/streaming/sinks/sink_factory.py
mage_ai/tests/streaming/sinks/test_oracledb.py

Follow this issue request: https://github.com/mage-ai/mage-ai/issues/4666 to create oracle destination for streaming pipeline.
Mage UI:
Created streaming pipeline with source: RabbitMQ, transformer and OracleDB destination.
UI to select OracleDB destination
Successfully exported data into Oracle:
cc:

[xh]Create streaming oracle destination

---

mage_ai/authentication/providers/oidc.py

OIDC auth ignores user_roles , this pr fixes reported bug #4898 
- [ x] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [ x] I have performed a self-review of my own code
cc:

Add support for user_roles when using OIDC auth

---

docs/about/roadmap.mdx

- Fix parsing of Roadmap doc.
Doc page renders correctly:
cc:
@thomaschung408

[jk] Fix syntax for iframe in Roadmap doc

---

mage_ai/frontend/components/FileUploader/index.tsx
mage_ai/frontend/components/PipelineDetail/UploadPipeline/index.tsx
mage_ai/frontend/oracle/elements/Inputs/MultiFileInput.tsx

- Zip files were not visible or disabled in certain browsers / on Windows when using the pipeline zip importer, so this PR fixes that.
Before (zip file disabled in file uploader):
After (zip file can be selected):

[jk] Allow files to be selected for pipeline zip import

---

docs/production/configuring-production-settings/compute-resource.mdx
mage_ai/services/k8s/config.py
mage_ai/services/k8s/job_manager.py
mage_ai/tests/services/k8s/test_job_manager.py

Simple pass parameters to V1JobSpec in JobManager.create_job_object
cc:

Add configuration parameters to V1JobSpec in k8s executor

---

mage_ai/autocomplete/utils.py
mage_ai/server/websocket_server.py
mage_ai/utils/code.py

In our local development, utility code changes are not effective automatically when working with the editor.
Instead kernel restart or manual importlib.reload helps.
In a slack chat I learnt from @tommydangerous, this is not the intended way.
[https://app.slack.com/client/T03GK6PEQP6/C03HTTWFEKE/1713014196.350109](https://app.slack.com/client/T03GK6PEQP6/C03HTTWFEKE/1713014196.350109)
I looked at the code that was referenced by Tommy and applied a few changes. This seems to work in our local dev env.
Changes:
- look for root project name, helps w multiprojects
- run importlib.reload in kernel via client
- [] Not tested in other bigger, cloud, etc systems.
Also could not reproduce original issue on demo.mage.ai
cc:

Reload libraries when running blocks from edit pipeline

---

docs/design/data-pipeline-management.mdx
mage_ai/orchestration/concurrency.py
mage_ai/settings/server.py

Support configuring concurrency config via env vars.
* `CONCURRENCY_CONFIG_BLOCK_RUN_LIMIT` and `CONCURRENCY_CONFIG_PIPELINE_RUN_LIMIT`
Close: https://github.com/mage-ai/mage-ai/issues/4997
cc:

[xy] Support configuring concurrency config via env vars.

---

mage_ai/frontend/components/Sidekick/GlobalVariables/Secrets.tsx
mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx

- Long secret and variable names in the Sidekick of the Pipeline Editor were getting cut off with no way to read them if the clipboard was blocked. This PR makes the variable/secret names fully visible, also adding tooltips, even if there is no access to the browser's clipboard.
- Addresses https://github.com/mage-ai/mage-ai/issues/5066
Before:
After:
cc:

[jk] Improve visibility of variable/secret names

---

requirements.txt

```
#20 377.6   Downloading psycopg2_binary-2.9.3-cp310-cp310-manylinux_2_24_aarch64.whl (3.4 MB)
#20 377.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 17.8 MB/s eta 0:00:00
#20 378.0 Collecting terminaltables==3.1.10
#20 378.0   Downloading terminaltables-3.1.10-py2.py3-none-any.whl (15 kB)
#20 378.6 Collecting google-cloud-storage==2.5.0
#20 378.6   Downloading google_cloud_storage-2.5.0-py2.py3-none-any.whl (106 kB)
#20 378.6      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.0/107.0 kB 18.6 MB/s eta 0:00:00
#20 378.8 Collecting google-analytics-data==0.14.2
#20 378.9   Downloading google_analytics_data-0.14.2-py2.py3-none-any.whl (108 kB)
#20 378.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.2/108.2 kB 18.9 MB/s eta 0:00:00
#20 379.6 Collecting …
```

[td] Upgrade deltalake because of Docker image build error

---

mage_ai/frontend/components/Backfills/Edit/index.tsx

- When editing a backfill, if user entered a value for "Max concurrent runs" but then deleted it and didn't enter anything else, there would be a `ValueError: invalid literal for int() with base 10: ''` error with the scheduler, causing the backfill to be stuck in the `initial` status. This PR fixes this.
- Locally
cc:

[jk] Fix max concurrent runs value for backfill

---

mage_ai/server/utils/output_display.py

Problem:
Runtime crashes occurred due to improper escaping of backslashes in raw string patterns used in code blocks, exemplified by:
```
foo = re.match(r'[A-Z]+(\d+)', segments[2])
```
This resulted in errors such as:
```
server-1  | KeyError: '\\d'
```
The root cause was traced back to insufficient backslash escaping in the escaped_code variable during dynamic string operations.
- Enhanced Backslash Escaping: Updated the escaping mechanism to ensure correct handling of backslashes in dynamically evaluated strings. This change doubles backslashes in escaped_code, preventing runtime errors during regex operations. The adjustment specifically affects the __interpolate_code_content method, where re.sub() is utilized for string replacements.
- Reproduce the Error: Before applying the …

Escaping Backslashes when interpolating code content

---

docs/integrations/observability/alerting-discord.mdx
docs/integrations/observability/alerting-email.mdx
docs/integrations/observability/alerting-slack.mdx
docs/integrations/observability/alerting-telegram.mdx
mage_ai/orchestration/notification/sender.py

1) Motivation: It is helpful to be able to interpolate `PipelineSchedule.description` attribute in notification messages
2) Problem: Currently there is no way to interpolate `PipelineSchedule.description` attribute
3) Solution: Include a `pipeline_schedule_description` var that interpolates from `PipelineSchedule.description`
Locally Ran `scripts/dev.sh` with the following notification config in project metadata.yaml (send notifications to slack)
```yaml
alert_on:
- trigger_success
- trigger_failure
- trigger_passed_sla
slack_config:
<<YOUR_SLACK_URL>>
message_templates:
success:
details: |
> Run Status: `Success ✅`
> Environment: `{{ env_var('ENV') }}`
> Pipeline UUID: `{pipeline_uuid}`
> Pipeline Schedule ID: `{pipeline_schedule_id}`
> Pipeline Schedule Name: …
```

Add pipeline_schedule_description variable to notification sender

---

mage_ai/data_preparation/models/block/__init__.py

In multi-project the get_repo_path() in the settings lib returns the active project repo path.
This makes it hard to read config files using generic code.
Having the repo path in kwargs makes it easy to use that in blocks.
Having it in os.environ local to python subprocesses, allows libraries to access this. This works with local executors. A different solution may be appropriate for spark and cloud executors.
Tested in our local multi-project codebase.
cc:

Added repo_path to block kwargs and os.environ, improves multi-project feature

---

mage_ai/api/resources/WorkspaceResource.py

Fix delete workspace. `self.current_user` is not defined in the resource class.
cc:

[xy] Fix delete workspace.

---

mage_ai/data_preparation/templates/repo/transformers/fill_in_missing_values.py

https://github.com/mage-ai/mage-ai/issues/5140
Fixed variable name `median_age` to `median_value`. Chief complaint was that the old `median_age` variable was used for iterations on all columns and not just the `Age` column. Renamed variable for clarity.
cc:

Updated Variable Name for Cohesion

---

mage_ai/data_preparation/templates/repo/transformers/fill_in_missing_values.py
mage_ai/services/telegram/telegram.py

Close: https://github.com/mage-ai/mage-ai/issues/4877
Whitespace in front of the content messages. Used code provided by the issue reporter to fix.
cc:
@csharplus @wangxiaoyou1993

Remove leading whitespace from Telegram notification message (Issue #4877)

---

mage_ai/io/base.py

Fix auto_clean_name param. Return the original column name when the param is set to False
cc:

[xy] Fix auto_clean_name param.

---

mage_ai/orchestration/db/models/schedules.py

Close: https://github.com/mage-ai/mage-ai/issues/5157
When comparing the token in trigger config with the database object
* If the existing trigger database object's token is None, create the token with uuid.uuid4().hex
* If the token in the trigger config is not None and it's not same with the trigger database object's token, update the db object's token
cc:

[xy] Fix api trigger token comparison.

---

mage_ai/io/snowflake.py

The key should be `network_timeout` not `timeout`
https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-connect#managing-connection-timeouts

[td] Update Snowflake timeout to network_timeout

---

mage_ai/frontend/package.json

- There was a Next build error related to lodash types:
```
./node_modules/@types/lodash/common/object.d.ts:1026:46
Type error: '?' expected.
1024 |     type GetFieldTypeOfArrayLikeByKey<T extends unknown[], K> =
1025 |         K extends number ? T[K]
> 1026 |         : K extends `${infer N extends number}` ? T[N]
|                                              ^
1027 |         : K extends keyof T ? T[K] : undefined;
1028 | 
1029 |     type GetFieldTypeOfStringByKey<T extends string, K> =
```
- This PR specifies versions for `@types/lodash` and `@types/lodash-es` to avoid the type error during the frontend build.
- Created successful build locally without the lodash type error.
cc:

[jk] Add specific lodash dependency version

---

.github/workflows/build_and_test.yml
mage_ai/io/bigquery.py
mage_ai/tests/io/create_table/test_bigquery.py

https://github.com/mage-ai/mage-ai/issues/5197
- Added a `create_dataset` parameter to the BigQuery `export` method to allow users to create a dataset if desired.
- Previously, the `__write_table` method always attempted to create a dataset.
- Now, dataset creation is controlled by the `create_dataset` parameter, which defaults to `False`.
cc: 
@jx2lee

Add create_dataset parameter to Bigquery #5197

---

mage_ai/server/server.py

Close: https://github.com/mage-ai/mage-ai/issues/4558
Update the file content API implementation to take the whole subpath as the argument.
When web server proxy automatically decode the url, the file content API throws error. This PR fixes that.
cc:

[xy] Update the file content API implementation.

---

mage_ai/frontend/components/CommandCenter/ItemRow/constants.tsx
mage_ai/frontend/components/CommandCenter/ItemRow/index.tsx

- Default the command center `item` variable to an object with default values to avoid type errors causing the app to crash.
- Local
cc:
@matrixstone

[jk] Default command center item

---

mage_ai/frontend/oracle/elements/Head/index.tsx

- The Mage website icon (`favicon.ico`) wasn't loading properly (e.g. in the browser tab), so this PR fixes the base path issue associated with it.
Before (note the lack of Mage icon in the browser tab):
After:
cc:

[jk] Include base path when loading favicon

---

mage_ai/api/presenters/PipelinePresenter.py
mage_ai/cache/utils.py
mage_ai/frontend/components/PipelineDetail/utils.ts
mage_ai/frontend/pages/pipelines/index.tsx

- Add ways for user to go back to RAG pipeline canvas page after creating RAG pipeline (e.g. if they navigate away from the canvas back to the main dashboard).
- To go to the v2 canvas, users can do one of the following from the Pipelines Dashboard:
1. Double-click a RAG pipeline (double-clicking a non-RAG pipeline will still go to the Pipeline Editor).
2. Right-click a RAG pipeline and select "Open pipeline" from the context menu.
cc:
@MageKai

[jk] V2 Canvas entry points

---

mage_ai/frontend/api/cleaner/utils/token.ts
mage_ai/frontend/api/utils/AuthToken.ts
mage_ai/frontend/api/utils/token.ts
mage_ai/frontend/components/Sessions/SignForm/index.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/mana/themes/utils.ts
mage_ai/frontend/oracle/styles/themes/utils.ts
mage_ai/frontend/package.json
mage_ai/frontend/pages/_app.tsx
mage_ai/frontend/pages/_document.tsx
mage_ai/frontend/utils/cookies/constants.ts
mage_ai/frontend/utils/cookies/utils.ts
mage_ai/frontend/utils/session.ts
mage_ai/frontend/yarn.lock

- Store oauth cookie based on base path so if user has multiple clusters open on the same domain but different base paths, they can be logged into all of them at the same time.
- Remove second argument from the `Cookies.get` method call, since it only requires 1 argument.
- Set `SameSite` and `Secure` attributes on oauth_token cookie.
- Note that there may still be some conflicting behavior due to shared local storage, for example if user is logged in as admin role in one cluster and viewer role in another cluster (to be resolved in separate PR).
- Tested logging into multiple clusters with different base paths at the same time (was not logged out of one after logging into the other as happened previously):

[jk] Cookie session updates

---

mage_ai/ai/openai_client.py
requirements.txt
setup.py

OpenAI API got upgrade with version >= 1.0.0. [Guide](https://github.com/openai/openai-python/discussions/742). This PR changes the API call and enforce openAI version to bigger than 1.0.0.
1. Tested with Mage AI command line functions:
- `generate-block-with-description`
- `generate-pipeline-documentation`
- `generate-block-with-description`
- `generate-pipeline-with-description`
- `generate-comment-for-block`
2. unit test run `python -m unittest mage_ai/tests/ai/test_ai_functions.py`
3. Tested in Mage UI
cc:

[xh]Update openai version to >= 1.0.0

---

mage_ai/orchestration/pipeline_scheduler_original.py

Only run memory usage failure check when executor type is local python.
When using external executor, the memory usage inside the scheduler isn't related to the pipeline execution.
cc:

[xy] Only run memory usage failure check when executor type is local python

---

mage_ai/data_preparation/models/block/dynamic/counter.py
mage_ai/data_preparation/models/block/dynamic/data.py
mage_ai/data_preparation/models/block/dynamic/factory.py
mage_ai/data_preparation/models/block/dynamic/variables.py
mage_ai/data_preparation/models/block/settings/dynamic/constants.py
mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/presenters/blocks/graph.py
mage_ai/tests/data_preparation/models/block/dynamic/test_variables.py

- When checking to see whether a dynamic child block should start running, if upstream dynamic child block has 0 outputs, proceed forward
- Handle division by 0 when upstream output data is 0 or empty
- Fix block run tree display of lines to downstream blocks that don’t actually exist
- Fix reduce output
```
server-1          | ERROR:dynamic1/56/20240731T015248/e_1:{"block_run_id": 285, "block_uuid": "e:1", "pipeline_run_id": 126, "pipeline_schedule_id": 56, "pipeline_uuid": "dynamic1", "hostname": "f9506d1fddb0", "block_type": "data_exporter", "level": "EXCEPTION", "message": "Failed to execute block e", "timestamp": 1722395949.415388, "uuid": "1687f4418a1e42aabeaf375236ed915b", "error": ["Traceback (most recent call last):\n  File …
```

[td] Fix blocks waiting and when fetching upstream w/ no output

---

mage_ai/frontend/utils/cookies/constants.ts
mage_ai/frontend/utils/environment.ts

- The `secure` cookie property was causing login issues if the user was running Mage not on localhost and not with `https`. This PR updates the condition that was setting the `secure` property to `true`. Previously, it checked if the `NODE_ENV` environment variable was `production`, but the FE production build could still have a "production" `NODE_ENV` environment variable set while still using the `http` protocol.
- Tested locally in Chrome, Safari, and Firefox.
cc:

[jk] Update condition for cookie secure property

---

mage_ai/server/server.py

Fix dbt block delete request with nginx. When dbt block with the nested path and run Mage in nginx, the block can't be deleted because nginx automatically decode the URL. This PR fixes this issue.
cc:

[xy] Fix dbt block delete request with nginx.

---

docs/design/blocks/transformer-blocks.mdx
docs/guides/blocks/transformer-blocks.mdx
mage_ai/data_cleaner/transformer_actions/column.py
mage_ai/tests/data_cleaner/transformer_actions/test_trim_transformer.py

This PR adds a new `trim` reformat action to the Python transformer block, which removes leading and trailing whitespace from specified text columns. My motivation for this PR is to start contributing to the Mage project!
No additional dependencies are required for this change.
cc: @wangxiaoyou1993 @johnson-mage

Add trim reformat action to transformer block

---

requirements.txt

DuckDB Version 0.9.2 is old and causing conflicts with MotherDuck.
This commit updates the Version to 1.0.0 which resolves the compatibility issue.
DuckDB 1.0.0 introduces some [new features](https://duckdb.org/2024/06/03/announcing-duckdb-100.html) and is currently the stable version of DuckDB.
We use this package in production at MotherDuck.

enhancement: bump duckdb to 1.0.0

---

mage_ai/data_preparation/templates/data_exporters/streaming/generic_python.py

Resolve the following error message encountered when `Execute pipeline` after adding a Data Exporter for a streaming pipeline:
```
[test_0001] [KafkaSource] Test connection successfully.
Pipeline test_0001 execution failed with error:
File "/usr/local/lib/python3.10/site-packages/mage_ai/server/websocket_server.py", line 118, in run_pipeline
pipeline.execute_sync(
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipeline.py", line 807, in execute_sync
StreamingPipelineExecutor(self).execute(
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/streaming_pipeline_executor.py", line 136, in execute
raise e
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/streaming_pipel …
```

[hw] Fix a missing import issue with data types in a template for Data Exporters

---

mage_ai/streaming/sources/kafka.py

Hostname validation was not working properly for SASL_SSL security protocol. Always connector was validating the hostname against the SSL, added a logic to disable this validation as well.
This issue was reported by multiple people.
This is associated with the bug, https://github.com/mage-ai/mage-ai/issues/5031
Yes. 
cc:
@wangxiaoyou1993  @tommydangerous

SASL_SSL kafka Host Name Validation

---

mage_ai/streaming/sources/kafka.py

When setting up SASL, all SSL settings needs to be passed through as well.
cc:

Pass all SSL settings through for SASL_SSL

---

mage_ai/frontend/components/Triggers/Edit/TriggerInteractions.tsx

- The "Frequency" row for custom frequency triggers in the trigger edit "Review" tab were appearing as `Ustom` instead of `Custom`. This PR fixes this.
- Addresses item `#2`in https://github.com/mage-ai/mage-ai/issues/5376
cc:

[jk] Fix typo for custom frequency in trigger review

---

docs/guides/streaming-pipeline.mdx

Followed the existing user guide for testing Kafka streaming, and encountered some issues, e.g., 
```
% docker-compose up
zsh: command not found: docker-compose
```
and
```
% docker compose up
WARN[0000] /Users/hw/workspace/kafka-docker/docker-compose.yml: `version` is obsolete 
[+] Running 0/1
⠦ zookeeper Pulling                                                                                                                                      1.7s 
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/wurstmeister/zookeeper:3.4.6 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at …
```

[hw] Update the user guide for Kafka streaming with latest changes based on testing

---

README_dev.md

On Mac, when running the following command:
```
pip install $(python -c "import toml; print(' '.join(toml.load('pyproject.toml')['tool']['poetry']['group']['dev']['dependencies'].keys()))" | tr '\n' ' ')
```
The `python` executable could be pointing to that of the system installed version, and leads to the following error:
```
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'toml'
ERROR: You must give at least one requirement to install (see "pip help install")
```
Using the command with `python3` in the updated document would work.
cc:

Update the development document to resolve one issue encountered

---

mage_ai/tests/data_preparation/models/block/dbt/test_profiles.py
mage_ai/tests/data_preparation/sync/test_git_sync.py
mage_ai/tests/settings/test_platform.py

In Python 3.12, the following two methods are fully deprecated and would lead to unit test failures:
```
assertEquals
assertNotEquals
```
e.g.,
```
ERROR: test_interpolate_clean (tests.data_preparation.models.block.dbt.test_profiles.ProfilesTest.test_interpolate_clean)
Test the Profiles Interface by
----------------------------------------------------------------------
File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/async_case.py", line 90, in _callTestMethod
if self._callMaybeAsync(method) is not None:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/async_case.py", line 117, in _callMaybeAsync
return …
```

Update unit tests to use the methods compatible with Python 3.12

---

mage_ai/tests/orchestration/queue/test_process_queue.py
mage_ai/tests/streaming/sinks/test_generic_io.py

When running on Python 3.12, a few unit tests failed. These tests have been updated to run without issues on Python 3.12.
```
ERROR: test_has_job (tests.orchestration.queue.test_process_queue.ProcessQueueTests.test_has_job)
----------------------------------------------------------------------
File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/mock.py", line 1393, in patched
return func(*newargs, **newkeywargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hw/workspace/dev/mage-ai/mage_ai/tests/orchestration/queue/test_process_queue.py", line 49, in test_has_job
self.queue.enqueue('block_run_1', run_block)
File "/Users/hw/workspace/dev/mage-ai/mage_ai/orchestration/queue/process_queue.py", line 121, …
```

Update a few unit tests that failed on Python 3.12

---

mage_ai/data_preparation/git/utils.py

Based on this documentation from Bitbucket, there is a difference between Bitbucket and the other providers like Github in using auth-token
> The literal string x-token-auth as a substitute for username is required.
So I changed a little bit code in function build_authenticated_remote_url‎ to customize for bitbucket only.
I don't want to change too much in the other function because it should be isolated for only this function, the other functions are the same with the other providers
- Tested this code by updating code directly in lib file: /usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/git/utils.py and it worked
cc:

#5417 Fix bug: Can't use git with Bitbucket

---

mage_ai/streaming/sources/kafka.py
mage_integrations/mage_integrations/destinations/kafka/__init__.py

Resolve the following unit test failure issue when running with Python 3.12:
```
ERROR: tests.streaming.sources.test_kafka (unittest.loader._FailedTest.tests.streaming.sources.test_kafka)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.streaming.sources.test_kafka
File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
module = self._get_module_from_name(name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
__import__(name)
File …
```

Fix kafka module related unit test failure issues in Python 3.12

---

mage_ai/services/k8s/config.py
mage_ai/services/k8s/job_manager.py

This PR introduces the ability to customize the Kubernetes scheduler options when using the Kubernetes Executor. It allows users to specify scheduler configurations directly, enhancing flexibility and control over pod scheduling behavior in Kubernetes environments.
Mentioned in [this issue](https://github.com/mage-ai/mage-ai/issues/5411)

Add support to scheduler name on k8s executor

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.74
* Initialize google cloud storage source by @TalaatHasanin in https://github.com/mage-ai/mage-ai/pull/5334
* Add support to scheduler name on k8s executor by @messerzen in https://github.com/mage-ai/mage-ai/pull/5412
* Airtable Integration by @TalaatHasanin in https://github.com/mage-ai/mage-ai/pull/5404
* Add trim reformat action to transformer block by @cristopheridlc in https://github.com/mage-ai/mage-ai/pull/5321
* Enable polars dataframe by @TalaatHasanin in https://github.com/mage-ai/mage-ai/pull/5348
* [jk] Update condition for cookie secure property by @johnson-mage in https://github.com/mage-ai/mage-ai/pull/5327
* [xy] Fix NoneType in trigger settings. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5329
* [xy] Fix dbt block delete request …

[xy] Bump version to 0.9.74

---

mage_ai/ai/openai_client.py

Pass OpenAI API key to library
Tested in Mage UI when ENV openai key is not set. AI generated function still functionable.

[xh]Pass OpenAI API key to OpenAI Library

---

mage_integrations/requirements.txt

Updated Facebook Ads SDK to version 20.0.2
No changes on the source tap code were made to support this version. 
Tested on local Mage run with the updated SDK and no bugs/issues were detected.
#5384 
cc:

Updated Facebook Ads SDK to 20.0.2

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/tests/data_preparation/models/test_block.py

When the block_type value is `None`, the following code would throw exception:
```
>> block_type + 's'
File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
However, the following code works fine:
```
>> f'{block_type}s'
'Nones'
```
It was showing as “BlockType.###s” earlier for valid block_types, due to the behavior change of StrEnum in Python 3.11+. It was changed to `block_type +'s'` to pass existing unit tests. With the later StrEnum change, this work-around was not needed anymore. 
```
(.venv) mage-ai % python3 -m unittest mage_ai.tests.data_preparation.models.test_block.BlockTest
WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!
WARNING:traitlets:Message …
```

[hw] Avoid throwing exceptions when `block_type` is None

---

mage_ai/frontend/components/Logs/Detail/index.tsx
mage_ai/frontend/interfaces/LogType.ts

- The FE app was crashing due an error in the error log format when viewing the Log Details for an error log. This PR fixes the error.
Before (this error would appear and crash the app):
After (error log loads without issues):
cc:

[jk] Fix error detail log parsing

---

mage_ai/frontend/components/CodeBlock/CodeOutput/TableOutput.tsx
mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/PipelineDetail/utils.ts

- Fix formatting of nested tables inside of rows for block outputs in Pipeline Editor. Previously, JSON objects would be rendered as nested tables inside the cells of tables for the block output, but the formatting was broken and the nested tables could not scroll or view the contents easily. This PR renders the JSON objects simply as formatted strings.
Before:
After:
cc:

[jk] Render json objects in block outputs as string instead of nested table

---

mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx

- See title.
`ID` column added to Block Runs Table on `/pipelines/[pipeline_uuid]/runs/[pipeline_run_id]` and `/pipelines/[pipeline_uuid]/runs?tab=block_runs` pages:
cc:

[jk] Display ID in block runs table

---

mage_integrations/mage_integrations/sources/google_cloud_storage/__init__.py
mage_integrations/requirements.txt

- This pr includes adding `chardet` (a python library to get file encoding) to pass the sile encoding to `read_csv()` pandas method
- Also added chardet and pyairtable to `requirements.txt`
Fix #5446 
cc:

Fix encoding in GCS Integration

---

docs/streaming/destinations/elasticsearch.mdx
mage_ai/data_preparation/templates/data_exporters/streaming/elasticsearch.yaml
mage_ai/streaming/sinks/elasticsearch.py

Adds support for the  bulk operations with [Data streams](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html) as they require this as they are Append-only indexes
https://elasticsearch-py.readthedocs.io/en/v8.15.1/helpers.html#bulk-helpers

[enhancement] Elasticsearch support of _op_type for bulk operations

---

mage_ai/shared/enum.py
mage_ai/tests/api/endpoints/test_blocks.py
mage_ai/tests/api/endpoints/test_configuration_options.py
mage_ai/tests/api/endpoints/test_configuration_options_project_platform.py
mage_ai/tests/api/endpoints/test_custom_designs.py
mage_ai/tests/api/endpoints/test_custom_designs_project_platform.py
mage_ai/tests/api/endpoints/test_dbt_blocks.py
mage_ai/tests/api/endpoints/test_file_contents.py
mage_ai/tests/api/endpoints/test_file_contents_with_project_platform.py
mage_ai/tests/api/endpoints/test_pipelines.py
mage_ai/tests/api/endpoints/test_pipelines_with_project_platform.py

There is a built-in type IntEnum in Python 3.8 - 3.10, thus no need to create a new class.
cc:

[hw] Use the built-in IntEnum instead of creating a new class

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/tests/data_preparation/test_variable_manager_project_platform.py

The root cause of some flaky unit tests was found: [the cached reading of YAML file](https://github.com/mage-ai/mage-ai/blob/master/mage_ai/cache/mem_lru.py) could not detect file changes if two changes are too close together (e.g., calling set_global_variable twice in a row as done in unit tests). This issue was explained in more detail in: https://stackoverflow.com/questions/19059877/python-os-path-getmtime-time-not-changing.
It could be an issue with Mage system overall, i.e., whenever pipeline state changes are too close to each other, the cached version of the pipeline YAML file in memory would be stale, and could lead to data loss due to wrong overwrites, e.g., the earlier set value is over-written.
I've tried the time delay value of `0.0001` and `0.0002`, which didn't work. The …

Add time delay to avoid getting the same file timestamp for multiple changes

---

mage_ai/services/teams/config.py
mage_ai/services/teams/teams.py
mage_ai/tests/orchestration/notification/test_config.py

Fixes https://github.com/mage-ai/mage-ai/issues/5507
This change introduces support for multiple Microsoft Teams webhook URLs within the notification configuration. The previous structure allowed for a single webhook URL, as follows:
```yaml
alert_on:
- trigger_failure
- trigger_success
teams_config:
webhook_url: URL 1
```
The updated structure enables the configuration of multiple webhook URLs:
```
alert_on:
- trigger_failure
- trigger_success
teams_config:
webhook_url: 
- URL 1
- URL 2
```
This enhancement allows users to send notifications to multiple Teams channels simultaneously, providing greater flexibility in notification management.
Additionally, the new implementation retains compatibility with the existing configuration model. This …

Add support to multiples webhook endpoints for Microsoft Teams notification service

---

mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/__init__.py
mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/__init__.py

For Issue #5409 
When configuring the Salesforce Source in a batch pipeline the 'start_date' is being converted before it is passed through - even though it is correctly entered in the config. 
The root cause looks like it is with how yaml.safe_load parses the date string and returns to the frontend. Opted to change the SalesForce data integration to handle both formats to reduce impact. Updated to `strptime_to_utc` as `strptime` is [deprecated](https://github.com/singer-io/singer-python/blob/master/singer/utils.py#L30C8-L30C18)  
Once this bug was resolved, there was an initial error with the sync because the `raw_state` was not set. Updated to default the raw_state
Verified the integration using the SalesForce data integration within a batch pipeline locally. Confirmed loading data from …

[Bug] Updated SalesForce source to handle multiple date formats

---

mage_ai/io/postgres.py

This fix allows  all valid psycopg2 connection parameters as keyword arguments. Previously, only a limited set of parameters were passed to connect(), restricting customization options like `sslmode` and `keepalives`. The fix now allows users to specify any connection parameter, which is then properly passed to `connect()`, enhancing flexibility in PostgreSQL connections.
fixes #5442
Manually tested and confirmed output. Did not see existing test for the class.
Open to writing test if requested.
```python
from mage_ai.io.postgres import Postgres
credentials = {
'dbname': 'postgres',
'user': 'postgres',
'password': 'postgres',
'host': 'localhost',
'port': '5432',
'sslmode': 'disable'
}
with Postgres(dbname = credentials['dbname'],
user = credentials['user'],
password = …
```

Fix unable to pass extra parameters to psycopg2 in Postgres connector

---

docs/_snippets/contribution-process.mdx
docs/contributing/development-environment.mdx
docs/extensibility/env-config/pipeline.mdx
docs/extensibility/env-config/project.mdx
docs/mint.json

- Add docs for overriding project/pipeline configurations based on environment.
- Tested locally.
cc:

[jk] Environment-specific config override docs

---

mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/orchestration/pipeline_scheduler_project_platform.py
mage_ai/usage_statistics/logger.py

Move help improve_mage check outside of asyncio.run so that scheduler isn't stuck in asyncio.run
Close: https://github.com/mage-ai/mage-ai/issues/5621

[xy] Move help improve_mage check outside of asyncio.run

---

mage_ai/api/policies/PipelineSchedulePolicy.py
mage_ai/api/presenters/PipelineSchedulePresenter.py
mage_ai/api/resources/PipelineScheduleResource.py
mage_ai/settings/server.py

Support hiding and rotating API trigger token.
* It can be enabled with env var `HIDE_API_TRIGGER_TOKEN=true`
* Once it's enabled, any API calls to pipeline schedule API won't return the token in response. API trigger token won't be shown in the UI
* API trigger token will only be returned once on PipelineSchedule UPDATE request with `"rotate_token": true" in the paylod
* How to rotate token
```
PUT /api/pipeline_schedules/[pipeline_schedule_id]
{
"pipeline_schedule": {
"rotate_token": true
}
}
```

[xy] Support hiding and rotating API trigger token.

---

mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/orchestration/pipeline_scheduler_project_platform.py
mage_ai/orchestration/utils/distributed_lock.py

Support configuring Redis default timeout. 
* Set `REDIS_LOCK_DEFAULT_TIMEOUT` env var to number of seconds for the lock timeout
Close: https://github.com/mage-ai/mage-ai/issues/5619
cc:

[xy] Support configuring redis default timeout

---

.github/workflows/build_and_test.yml
mage_integrations/mage_integrations/tests/sources/couchbase/test_couchbase.py
mage_integrations/setup.py
setup.py

Remove the support for `Python 3.8`, as it has been officially deprecated, as listed in https://devguide.python.org/versions/
cc:

Drop the support for Python 3.8 as it is EOL officially

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/mssql.py

This PR fix the disable query preprocessing for MSSQL SQL block for the bug: https://github.com/mage-ai/mage-ai/issues/5633. The bug ticket reports `DROP TABLE` command for MSSQL SQL block with `disable query preprocessing` enable. I reproduce the issue and fix with code chagne.
Local Mage UI
Reproduce the issue with drop table command failure:
Test with the code change, drop command success and table got deleted.
cc:

[xh]Fix disable query preprocessing

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/utils/shared.py

Pass execution_partition to interpolate content method. so that we can interpolate the `block_output` with correct execution_partition.
https://docs.mage.ai/guides/blocks/sql-blocks#upstream-block-output
Close: https://github.com/mage-ai/mage-ai/issues/5660
cc:

[xy] Pass execution_partition to interpolate content method.

---

.github/workflows/build_and_test.yml

Resolve the following error encountered in the GitHub build:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
cc:

[hw] Update a deprecated git action version

---

mage_ai/io/mysql.py

Fix MySQL error.
```
MySQL initialized
└─ Opening connection to MySQL database...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File /usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py:401, in execute_sql_code(block, query, dynamic_block_index, dynamic_upstream_block_uuids, execution_partition, from_notebook, global_vars, config_file_loader, configuration)
398 elif DataSource.MYSQL.value == data_provider:
399     from mage_ai.io.mysql import MySQL
--> 401     with MySQL.with_config(config_file_loader) as loader:
402         mysql.create_upstream_block_tables(
403             loader,
404             block,
405 …
```

[xy] Fix MySQL error.

---

mage_integrations/mage_integrations/connections/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/kafka/__init__.py
mage_integrations/mage_integrations/sources/mssql/__init__.py
mage_integrations/mage_integrations/sources/oracledb/__init__.py

Fix arguments in some data integration sources/destinations.
```
self.export_batch_data(
File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/sql/base.py\", line 98, in export_batch_data
self.build_connection().execute(create_schema_commands, commit=True)
File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 56, in execute
data = self.execute_with_connection(
TypeError: BigQuery.execute_with_connection() got an unexpected keyword argument 'log_exception'
", "caller": "BigQuery", "level": "EXCEPTION", "timestamp": 1742261508, "uuid": "f1c811e7d8084a95b243ff3a7b2c8cd0", "type": "LOG"}
```
```
Exception: 2025-03-14T16:14:01 MSSQL process failed with error MSSQL._limit_query_string() got an unexpected keyword argument …
```

[xy] Fix arguments in some data integration sources/destinations.

---

mage_integrations/requirements.txt
requirements.txt

Meta is deprecating all their API-versions prior to v21.0 on Tuesday, May 6, 2025. [https://developers.facebook.com/docs/marketing-api/marketing-api-changelog#available-marketing-api-versions](url)
Bumping Facebook Ads SDK to version 22.0.2
No changes on the source tap code were made to support this version.
Tested on local Mage run with the updated SDK and no bugs/issues were detected.
cc:

Bumping facebook_ads version

---

docs/guides/data-sync/version-control-guide.mdx

This PR adds GitLab documentation to the version control doc
Tested in the mintlify dev env.
cc:
@johnson-mage

[cf] add gitlab to version control docs

---

mage_integrations/mage_integrations/sources/facebook_ads/tests/test_facebook_invalid_attribution_window.py
mage_integrations/mage_integrations/sources/facebook_ads/tests/unittests/test_attribute_error_retry.py
mage_integrations/mage_integrations/sources/facebook_ads/tests/unittests/test_attribution_window.py
mage_integrations/mage_integrations/sources/facebook_ads/tests/unittests/test_request_timeout.py
mage_integrations/mage_integrations/sources/facebook_ads/tests/unittests/test_retry_logic.py
mage_integrations/mage_integrations/sources/facebook_ads/tests/unittests/test_sync_batches_retry.py
mage_integrations/mage_integrations/sources/linkedin_ads/tests/unittests/test_account_number.py
mage_integrations/mage_integrations/sources/linkedin_ads/tests/unittests/test_adCampaignGroup_4XX.py
mage_integrations/mage_integrations/sources/linkedin_ads/tests/unittests/test_exception_handling.py
mage_integrations/mage_integrations/sources/linkedin_ads/tests/unittests/test_fetch_access_token.py
mage_integrations/mage_integrations/sources/linkedin_ads/tests/unittests/test_timeout.py
mage_integrations/mage_integrations/sources/mongodb/tests/test_mongodb_datatype.py

This PR migrates from `unittest.assertEquals` to `unittest.assertEqual` which is deprecated from Python2.7:
```python
DeprecationWarning: Please use assertEqual instead.
```
Run tests.
cc:

Migrate to unittest.assertEqual

---

docs/docs.json

This adds the additional mage pro only docs to the Mage Pro docs page
The was tested in the mintlify dev env.
cc:
https://github.com/user-attachments/assets/3aa32e86-95d0-436c-92c7-56ab375961cf
@johnson-mage

adding more docs to mage pro

---

mage_ai/io/postgres.py
mage_ai/tests/io/create_table/test_postgresql.py

This PR fixes the issue #5803 which is about incorrect encoding when exporting `text[]` columns with non-ASCII characters to Postgres
- Navigate to the relevant directory `cd mage_ai/tests/io/create_table/`
- Run the test `python3 -m unittest discover -s . --failfast`
- I also ran all the other tests and they passed as well:
- Navigate back to the root of the repo
- Run `python3 -m unittest discover -s mage_ai/ --failfast`
cc:

Add ensure_ascii=False to JSON serialization for better Unicode handling. Fixes issue #5803

---

docs/docs.json
docs/observability/alerting/alerting-zendesk.mdx

This pull request adds documentation for integrating Zendesk as an alerting destination in Mage, allowing users to create Zendesk tickets from pipeline events. The main changes are the addition of a new Zendesk alerting guide and updating the documentation index to include this new page.
**Zendesk alerting documentation:**
* Added a new guide `alerting-zendesk.mdx` that explains how to configure Mage to send alerts to Zendesk, including setup steps, configuration examples, and template customization options.
* The guide covers both standard and Mage Pro features, such as advanced variable interpolation in ticket templates.
**Documentation index update:**
* Updated `docs.json` to include the new Zendesk alerting documentation in the sidebar navigation.
cc:

[xy] Add zendesk doc.

---

mage_ai/data_preparation/storage/local_storage.py

Close: https://github.com/mage-ai/mage-ai/issues/5859
This pull request introduces a small but important improvement to the `read_polars_parquet` method in `local_storage.py`, enhancing its robustness when reading Parquet files with Polars.
Error handling improvement:
* Updated `read_polars_parquet` to first attempt reading with `use_pyarrow=True`, and if an exception occurs, fallback to a standard read. This makes the method more resilient to different Parquet file formats or environments.
cc:

[xy] Not set use_pyarrow=True as fallback for reading polars.
