mage-ai/mage-ai

mage_ai/orchestration/db/__init__.py

This reverts commit 9d5cb6116d84e150a7233f4be38e6ad533dafe78.
Accidentally pushed this commit to master.
cc:

Revert "[dy] Update search_path command"

---

docs/production/data-sync/git-sync.mdx
mage_ai/data_preparation/preferences.py

Add environment variable to configure the `sync_submodules` setting for git sync.
cc:

[dy] Add sync submodules environment variable

---

mage_ai/api/presenters/BlockTemplatePresenter.py
mage_ai/data_preparation/models/block/data_integration/utils.py
mage_ai/data_preparation/templates/data_integrations/utils.py
mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.tsx
mage_ai/frontend/components/DataIntegrationModal/Credentials/index.tsx
mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailOverview.tsx
mage_ai/frontend/components/DataIntegrationModal/StreamsOverview/index.tsx
mage_ai/frontend/components/DataIntegrationModal/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/utils.ts
mage_ai/frontend/interfaces/BlockTemplateType.ts
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

Completed bugs here: https://www.notion.so/mageai/Bug-bash-Great-unification-of-pipelines-460c2d9a536d455387f5919cae6838b7?pvs=4
cc:

[td] Fix bugs from bug bash

---

mage_ai/api/operations/constants.py
mage_ai/api/policies/PipelinePolicy.py
mage_ai/api/presenters/PipelinePresenter.py
mage_ai/api/resources/PipelineResource.py
mage_ai/authentication/operation_history/constants.py
mage_ai/authentication/operation_history/models.py
mage_ai/authentication/operation_history/utils.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/project/constants.py
mage_ai/data_preparation/storage/base_storage.py
mage_ai/data_preparation/storage/gcs_storage.py
mage_ai/data_preparation/storage/local_storage.py
mage_ai/data_preparation/storage/s3_storage.py
mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/frontend/storage/pipelines.ts
mage_ai/shared/io.py

[td] Show recently viewed pipelines

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/data_integration/mixins.py
mage_ai/data_preparation/templates/utils.py
mage_ai/presenters/interactions/constants.py
mage_ai/presenters/interactions/models.py
mage_ai/presenters/interactions/utils.py

Create class for interactions (we won’t call them block interactions because these interactions can be associated to other entities beyond blocks).
cc:

[td] Create Interaction class and other models

---

mage_ai/api/policies/InteractionPolicy.py
mage_ai/api/presenters/InteractionPresenter.py
mage_ai/api/resources/InteractionResource.py
mage_ai/presenters/interactions/models.py

API endpoints for CRUD operations on the interactions resource. Attributes that are readable and writable are the variables and layout attributes.
cc:

[td] Add API for interactions

---

mage_ai/data_preparation/models/pipelines/constants.py
mage_ai/data_preparation/models/pipelines/interactions.py
mage_ai/presenters/interactions/models.py

Add class to CRUD interactions related to a pipeline’s blocks.
cc:

[td] Created class to handle interactions for pipelines

---

mage_ai/api/policies/PipelineInteractionPolicy.py
mage_ai/api/presenters/PipelineInteractionPresenter.py
mage_ai/api/resources/PipelineInteractionResource.py

Add API endpoint to support adding and removing interactions for a block in that pipeline.
cc:

[td] Add CRUD API endpoint for interactions in a pipeline

---

mage_ai/server/websocket_server.py

Initialize db connection session for scratchpads if it hasn't been initialized already.

[dy] Initialize db connection session

---

docs/guides/dbt/developing-dbt-in-mage.mdx

[mp] dbt hotfix

---

mage_ai/data_preparation/models/pipelines/interactions.py
mage_ai/frontend/components/Breadcrumbs/index.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/DataIntegrationModal/index.tsx
mage_ai/frontend/components/Interactions/InteractionSettings.tsx
mage_ai/frontend/components/PipelineInteractions/index.style.tsx
mage_ai/frontend/components/PipelineInteractions/index.tsx
mage_ai/frontend/components/PipelineLayout/index.tsx
mage_ai/frontend/components/Sidekick/Header.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

Show interactions in notebook.

[td] Add interactions app to sidekick

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3589
* https://github.com/mage-ai/mage-ai/pull/3622
* https://github.com/mage-ai/mage-ai/pull/3621
* https://github.com/mage-ai/mage-ai/pull/3623
* https://github.com/mage-ai/mage-ai/pull/3591
* https://github.com/mage-ai/mage-ai/pull/3627
* https://github.com/mage-ai/mage-ai/pull/3626
* https://github.com/mage-ai/mage-ai/pull/3617
* https://github.com/mage-ai/mage-ai/pull/3629
* https://github.com/mage-ai/mage-ai/pull/3632
* https://github.com/mage-ai/mage-ai/pull/3633
* https://github.com/mage-ai/mage-ai/pull/3634
* https://github.com/mage-ai/mage-ai/pull/3635
* https://github.com/mage-ai/mage-ai/pull/3636
* https://github.com/mage-ai/mage-ai/pull/3637
* https://github.com/mage-ai/mage-ai/pull/3638
* https://github.com/mage-ai/mage-ai/pull/3641 …

[xy] Bump version to 0.9.30

---

mage_ai/frontend/oracle/components/Table/SimpleDataTable.tsx
mage_ai/frontend/stories/components/charts/BarGraphHorizontal.stories.tsx
mage_ai/frontend/stories/components/charts/BoxPlotHorizontal.stories.tsx
mage_ai/frontend/stories/components/charts/Histogram.stories.tsx
mage_ai/frontend/stories/components/charts/PieChart.stories.tsx
mage_ai/frontend/stories/oracle/components/Accordion.stories.tsx
mage_ai/frontend/stories/oracle/components/Badge.stories.tsx
mage_ai/frontend/stories/oracle/components/Breadcrumbs.stories.tsx
mage_ai/frontend/stories/oracle/components/Chip.stories.tsx
mage_ai/frontend/stories/oracle/components/Menu.stories.tsx
mage_ai/frontend/stories/oracle/components/Panel.stories.tsx
mage_ai/frontend/stories/oracle/components/ProgressBar.stories.tsx
mage_ai/frontend/stories/oracle/components/RowDataTable.stories.tsx
mage_ai/frontend/stories/oracle/components/SimpleDataTable.stories.tsx
mage_ai/frontend/stories/oracle/components/Spinner.stories.tsx
mage_ai/frontend/stories/oracle/components/Tabs.stories.tsx
mage_ai/frontend/stories/oracle/elements/Button/Button.stories.tsx
mage_ai/frontend/stories/oracle/elements/Button/ButtonGroup.stories.tsx
mage_ai/frontend/stories/oracle/elements/Checkbox.stories.tsx
mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
mage_ai/frontend/stories/oracle/elements/Inputs/Select.stories.tsx
mage_ai/frontend/stories/oracle/elements/Inputs/TextInput.stories.tsx
mage_ai/frontend/stories/oracle/elements/Link.stories.tsx
mage_ai/frontend/stories/oracle/elements/Text.stories.tsx

- Update deprecated Storybook type.
- Clean up `SimpleDataTable` story.
- Locally on Storybook

[jk] Storybook cleanup

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/constants.ts
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/Interactions/BlockInteractionController.tsx
mage_ai/frontend/components/Interactions/InteractionLayoutContainer/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/PipelineDetail/utils.ts
mage_ai/frontend/components/PipelineInteractions/index.style.tsx
mage_ai/frontend/components/PipelineInteractions/index.tsx
mage_ai/frontend/components/Sidekick/Header.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.style.ts
mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
mage_ai/frontend/oracle/styles/themes/dark.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/utils/output_display.py

[td] Show the interactions rendered in the code block

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/Interactions/BlockInteractionController.tsx
mage_ai/frontend/components/Interactions/InteractionDisplay.tsx
mage_ai/frontend/components/Interactions/InteractionLayoutContainer/LayoutItem.tsx
mage_ai/frontend/components/Interactions/InteractionLayoutContainer/index.tsx
mage_ai/frontend/components/Interactions/InteractionSettings.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/server/utils/output_display.py
mage_ai/server/websocket_server.py

Use variables from the interactions when running a block in the notebook.
cc:

[td] Use variables from interactions when running block

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/Interactions/BlockInteractionController.tsx
mage_ai/frontend/components/Interactions/InteractionDisplay.tsx
mage_ai/frontend/components/Interactions/InteractionLayoutContainer/LayoutItem.tsx
mage_ai/frontend/components/Interactions/InteractionLayoutContainer/index.tsx
mage_ai/frontend/components/Interactions/InteractionSettings.tsx
mage_ai/frontend/components/Interactions/index.style.tsx
mage_ai/frontend/components/PipelineInteractions/PermissionRow/index.tsx
mage_ai/frontend/components/PipelineInteractions/index.tsx
mage_ai/frontend/interfaces/InteractionType.ts
mage_ai/presenters/interactions/constants.py
mage_ai/presenters/interactions/models.py

[td] Improve helper hints for interactions

---

mage_ai/api/policies/PipelinePolicy.py
mage_ai/api/presenters/PipelineInteractionPresenter.py
mage_ai/frontend/components/Interactions/InteractionDisplay.tsx

[td] Fix API policies for pipeline interactions

---

mage_ai/presenters/pages/constants.py
mage_ai/presenters/pages/models/base.py
mage_ai/presenters/pages/models/pipeline_schedules.py

Create base models to store data about pages and components the clients use.
cc:

[td] Create page models to help client determine what components to show

---

mage_ai/api/policies/ClientPagePolicy.py
mage_ai/api/presenters/ClientPagePresenter.py
mage_ai/api/resources/ClientPageResource.py
mage_ai/presenters/pages/constants.py
mage_ai/presenters/pages/models/base.py
mage_ai/presenters/pages/models/client_pages/pipeline_schedules.py
mage_ai/presenters/pages/models/client_pages/pipelines.py
mage_ai/presenters/pages/models/constants.py
mage_ai/presenters/pages/models/page_components/pipeline_schedules.py
mage_ai/presenters/pages/models/pipeline_schedules.py

Add API endpoints for client pages.
```
{
"client_pages": [
{
"category": null,
"components": [
{
"category": "button",
"components": [],
"disabled": false,
"operation": "create",
"parent": null,
"resource": "pipeline_schedule",
"uuid": "create_with_interactions_component",
"version": 1
}
],
"disabled": false,
"operation": "create",
"parent": null,
"resource": "pipeline_schedule",
"uuid": "pipeline_schedule:create",
"version": 1
},
{
"category": null,
"components": [],
"disabled": false,
"operation": "list",
"parent": null,
"resource": "pipeline_schedule",
"uuid": "pipeline_schedule:list",
"version": 1
},
{
"category": null,
"components": [],
"disabled": false,
"operation": "detail",
"parent": null,
"resource": "pipeline",
"uuid": "pipeline:detail",
"version": 1
},
{
"category": null, …
```

[td] Client pages API

---

mage_ai/api/operations/base.py

[td] Add await to authorize in base operation

---

mage_ai/api/policies/ClientPagePolicy.py
mage_ai/api/policies/PipelineSchedulePolicy.py
mage_ai/api/presenters/ClientPagePresenter.py
mage_ai/api/resources/ClientPageResource.py
mage_ai/presenters/pages/loaders/base.py
mage_ai/presenters/pages/loaders/pipeline_schedules.py
mage_ai/presenters/pages/loaders/pipelines.py
mage_ai/presenters/pages/loaders/utils.py
mage_ai/presenters/pages/models/base.py
mage_ai/presenters/pages/models/client_pages/pipeline_schedules.py
mage_ai/presenters/pages/models/page_components/pipeline_schedules.py

Load other models in the same API call so that the client pages and page components can use those models to validate.

[td] Added query params to client pages API

---

mage_ai/api/policies/ClientPagePolicy.py
mage_ai/api/presenters/BasePresenter.py
mage_ai/api/presenters/ClientPagePresenter.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
mage_ai/frontend/interfaces/ClientPageType.ts
mage_ai/frontend/interfaces/PageComponentType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_ai/presenters/pages/models/base.py
mage_ai/presenters/pages/models/client_pages/pipeline_schedules.py
mage_ai/presenters/pages/models/constants.py
mage_ai/presenters/pages/models/page_components/pipeline_schedules.py
mage_ai/shared/hash.py

[td] Update page models

---

docs/streaming/overview.mdx

Added Google Cloud PubSub link for sources
cc:

[tc] Update overview.mdx

---

mage_ai/api/operations/base.py
mage_ai/api/parsers/RoleParser.py
mage_ai/api/parsers/UserParser.py
mage_ai/api/policies/PermissionPolicy.py
mage_ai/api/policies/RolePolicy.py
mage_ai/api/policies/UserRolePolicy.py
mage_ai/api/presenters/BasePresenter.py
mage_ai/api/presenters/PermissionPresenter.py
mage_ai/api/presenters/RolePresenter.py
mage_ai/api/presenters/UserPresenter.py
mage_ai/api/presenters/UserRolePresenter.py
mage_ai/api/resources/BaseResource.py
mage_ai/api/resources/DatabaseResource.py
mage_ai/api/resources/PermissionResource.py
mage_ai/api/resources/RoleResource.py
mage_ai/api/resources/UserRoleResource.py
mage_ai/authentication/permissions/constants.py
mage_ai/orchestration/db/models/base.py
mage_ai/orchestration/db/models/oauth.py

- Roles
- `name`: any custom name
- Has many permissions
- Permissions
- `entity_id`: add permissions to a specific resource
- `entity_name`
- Majority of `entity_name`s will map to an existing API resource.
- This will make it easy for policies to automatically select the correct permissions from a user’s roles and validate against it.
- A lot (see below)
- `entity_type`: entity subtypes (e.g. pipeline type)
- `access`
- [operation] List
- [operation] Create
- [operation] Detail
- This operation can double as being the operation to view a page, component, or use a feature
- [operation] Update
- [operation] Delete
- [action on attributes] Read
- [action on attributes] Write
- [action on attributes] Query
- `options`
- This can store the query parameters this permission grants access to
- …

[td] Update auth models and constants

---

mage_ai/orchestration/pipeline_scheduler.py

Add None check for blocks in the `__update_block_run_statuses` method.
cc:

[dy] Add None for block check

---

mage_integrations/mage_integrations/sources/twitter_ads/tap_twitter_ads/__init__.py
mage_integrations/mage_integrations/sources/twitter_ads/tap_twitter_ads/discover.py
mage_integrations/mage_integrations/sources/twitter_ads/tap_twitter_ads/schema.py
mage_integrations/mage_integrations/sources/twitter_ads/tap_twitter_ads/streams.py
mage_integrations/mage_integrations/sources/twitter_ads/tap_twitter_ads/sync.py

Fixed Twitter Ads imports for Twitter-ads Source in Data Integration Pipelines
cc:

Fixed twitter ads imports

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3679
* https://github.com/mage-ai/mage-ai/pull/3682
* https://github.com/mage-ai/mage-ai/pull/3684
* https://github.com/mage-ai/mage-ai/pull/3683
* https://github.com/mage-ai/mage-ai/pull/3686
* https://github.com/mage-ai/mage-ai/pull/3651
* https://github.com/mage-ai/mage-ai/pull/3677
* https://github.com/mage-ai/mage-ai/pull/3630
* https://github.com/mage-ai/mage-ai/pull/3690
* https://github.com/mage-ai/mage-ai/pull/3688
* https://github.com/mage-ai/mage-ai/pull/3607
* https://github.com/mage-ai/mage-ai/pull/3693
* https://github.com/mage-ai/mage-ai/pull/3694
version bump
cc:

[dy] Bump 0.9.32

---

docs/guides/blocks/sql-blocks.mdx
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/tests/data_preparation/models/block/sql/utils/test_shared.py

Support UPDATE command in raw sql command.
cc:

[xy] Support UPDATE command in raw sql command.

---

.pre-commit-config.yaml
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/ErrorPopup/index.tsx
mage_ai/frontend/components/Interactions/BlockInteractionController.tsx
mage_ai/frontend/components/Interactions/InteractionDisplay.tsx
mage_ai/frontend/components/Interactions/InteractionLayoutContainer/index.tsx
mage_ai/frontend/components/Interactions/InteractionSettings.tsx
mage_ai/frontend/components/PipelineInteractions/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/interfaces/InteractionType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_ai/frontend/utils/models/interaction.ts
mage_ai/orchestration/db/models/schedules.py
mage_ai/presenters/interactions/constants.py
mage_ai/tests/api/operations/test_pipeline_schedules.py
mage_ai/tests/factory.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

https://www.notion.so/mageai/Bug-Bash-No-code-pipeline-block-interactions-d3b1425efeb94dfdb62511308f524b8e?pvs=4
cc:

[td] Bug bash interactions

---

mage_ai/api/policies/SessionPolicy.py
mage_ai/api/policies/StatusPolicy.py
mage_ai/api/policies/mixins/user_permissions.py

[td] Update session and status resource to allow with permissions

---

mage_ai/api/presenters/UserPresenter.py
mage_ai/frontend/components/settings/Dashboard/index.tsx
mage_ai/frontend/components/shared/index.style.tsx
mage_ai/frontend/components/users/edit/Form/index.tsx
mage_ai/frontend/interfaces/UserType.ts
mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
mage_ai/frontend/pages/settings/workspace/users/[...slug].tsx
mage_ai/frontend/pages/settings/workspace/users/index.tsx
mage_ai/orchestration/db/models/oauth.py

[td] User edit and detail view

---

mage_ai/api/policies/PermissionPolicy.py
mage_ai/api/presenters/PermissionPresenter.py
mage_ai/api/presenters/UserPresenter.py
mage_ai/frontend/components/Roles/RoleDetail.tsx
mage_ai/frontend/interfaces/PermissionType.ts
mage_ai/frontend/interfaces/RoleType.ts
mage_ai/frontend/pages/settings/workspace/roles/[...slug].tsx
mage_ai/frontend/pages/settings/workspace/roles/index.tsx
mage_ai/frontend/pages/settings/workspace/users/[...slug].tsx
mage_ai/frontend/utils/models/user.ts

[td] Roles detail page

---

mage_ai/frontend/api/index.ts
mage_ai/frontend/components/Roles/RoleDetail.tsx
mage_ai/frontend/components/settings/Dashboard/constants.tsx
mage_ai/frontend/interfaces/PermissionType.ts
mage_ai/frontend/pages/settings/workspace/permissions/index.tsx
mage_ai/frontend/pages/settings/workspace/roles/index.tsx
mage_ai/frontend/utils/models/permission.ts

[td] Permissions list page

---

mage_ai/api/policies/RolePermissionPolicy.py
mage_ai/api/policies/RolePolicy.py
mage_ai/api/presenters/RolePresenter.py
mage_ai/api/presenters/StatusPresenter.py
mage_ai/api/resources/DatabaseResource.py
mage_ai/api/resources/PermissionResource.py
mage_ai/api/resources/RolePermissionResource.py
mage_ai/api/resources/RoleResource.py
mage_ai/api/resources/StatusResource.py
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/Roles/RoleDetail.tsx
mage_ai/frontend/components/settings/Dashboard/constants.tsx
mage_ai/frontend/components/settings/Dashboard/index.tsx
mage_ai/frontend/pages/_app.tsx
mage_ai/frontend/pages/settings/workspace/roles/[...slug].tsx
mage_ai/frontend/pages/settings/workspace/roles/index.tsx
mage_ai/frontend/utils/session.ts

[td] Add permissions and users to role

---

mage_ai/data_preparation/shared/secrets.py
mage_ai/services/aws/__init__.py

Add `suppress_warning` kwarg to the `get_secret_value` methods, so that the warning logs are not displayed in some situations. Also reformat the `aws/__init__.py` file.
cc:

[dy] Suppress secret logs for aws secrets

---

mage_ai/data_integrations/destinations/constants.py
mage_integrations/mage_integrations/destinations/opensearch/README.md
mage_integrations/mage_integrations/destinations/opensearch/__init__.py
mage_integrations/mage_integrations/destinations/opensearch/target_opensearch/common.py
mage_integrations/mage_integrations/destinations/opensearch/target_opensearch/sinks.py
mage_integrations/mage_integrations/destinations/opensearch/target_opensearch/target.py
mage_integrations/mage_integrations/destinations/opensearch/templates/config.json
mage_integrations/requirements.txt

Added a modified version of target-elasticsearch to support Opensearch Destination in Data Integrations Pipeline
Tested using PostgreSQL -> Local OpenSearch cluster 
Logs From opensearch destination in FULL TABLE sync:
Opensearch search result example:
Formatted search result:
```json
{
"took": 1,
"timed_out": false,
"_shards": {
"total": 1,
"successful": 1,
"skipped": 0,
"failed": 0
},
"hits": {
"total": {
"value": 3,
"relation": "eq"
},
"max_score": 1.0,
"hits": [
{
"_index": "ecs-account-2023.10.10",
"_id": "2tcYGYsBxExjeDBDHvgT",
"_score": 1.0,
"_source": {
"id": "0016e00003KhVWsAAN",
"isdeleted": false,
"masterrecordid": null,
"name": "Burlington Textiles Corp of America",
"type": "Customer - Direct",
"parentid": null,
"billingstreet": "525 S. Lexington Ave",
"billingcity": …
```

Added Opensearch Destination

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/templates/repo/metadata.yaml
mage_ai/services/spark/config.py
mage_ai/services/spark/spark.py

Support using custom spark session.
Spark config
```yaml
spark_config:
use_custom_session: true
custom_session_var_name: 'spark'
```
cc:

[xy] Support using custom spark session.

---

mage_ai/api/resources/RoleResource.py
mage_ai/frontend/components/Roles/RoleDetail.tsx
mage_ai/orchestration/db/models/schedules.py

- Can’t start backfills
- Can’t create triggers
cc:

[td] Remove the requirement for schedule type

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/3697
- https://github.com/mage-ai/mage-ai/pull/3687
- https://github.com/mage-ai/mage-ai/pull/3700
- https://github.com/mage-ai/mage-ai/pull/3689
- https://github.com/mage-ai/mage-ai/pull/3692
- https://github.com/mage-ai/mage-ai/pull/3705
- https://github.com/mage-ai/mage-ai/pull/3706
- https://github.com/mage-ai/mage-ai/pull/3707
- https://github.com/mage-ai/mage-ai/pull/3709
- https://github.com/mage-ai/mage-ai/pull/3710
- https://github.com/mage-ai/mage-ai/pull/3711
- https://github.com/mage-ai/mage-ai/pull/3712
- https://github.com/mage-ai/mage-ai/pull/3713
- https://github.com/mage-ai/mage-ai/pull/3703
- https://github.com/mage-ai/mage-ai/pull/3704
- https://github.com/mage-ai/mage-ai/pull/3719
- https://github.com/mage-ai/mage-ai/pull/3723 …

[td] 0.9.33

---

mage_ai/api/policies/PermissionPolicy.py
mage_ai/api/presenters/PermissionPresenter.py
mage_ai/api/resources/PermissionResource.py
mage_ai/api/resources/RoleResource.py
mage_ai/frontend/components/Permissions/PermissionDetail.tsx
mage_ai/frontend/components/Roles/RoleDetail.tsx
mage_ai/frontend/pages/settings/workspace/permissions/[...slug].tsx
mage_ai/orchestration/db/models/oauth.py
mage_ai/orchestration/db/models/schedules.py

- Show roles
- Add roles
- Show users with this permission
cc:

[td] Add roles and users on permissions detail page

---

mage_ai/api/operations/base.py
mage_ai/api/policies/mixins/user_permissions.py
mage_ai/frontend/components/Permissions/PermissionDetail.tsx
mage_ai/frontend/pages/settings/workspace/permissions/index.tsx

[td] Fix permissions list

---

mage_ai/api/policies/BasePolicy.py
mage_ai/server/constants.py
setup.py

- Fix mixins missing
- Add override permissions

[td] 0.9.34

---

mage_ai/frontend/components/Permissions/PermissionDetail.tsx
mage_ai/frontend/components/Roles/RoleDetail.tsx
mage_ai/frontend/components/users/UserDetail.tsx

Make it harder to uncheck a box on the user management tables.

[td] Make it less easy to uncheck a role, permission, etc in a table

---

mage_ai/api/middleware.py
mage_ai/api/resources/StatusResource.py
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/Triggers/utils.ts
mage_ai/orchestration/triggers/utils.py
mage_ai/server/api/triggers.py
mage_ai/server/server.py
mage_ai/shared/requests.py

Add a new endpoint `api/pipeline_schedules/{id}/api_trigger` that takes the token in the request header instead of in the url path.
New api trigger page:

[dy] Update api trigger request

---

docs/mint.json

Add GC PubSub to `mint.json`

---

mage_ai/api/policies/BasePolicy.py
mage_ai/api/policies/BlockPolicy.py
mage_ai/api/policies/PipelineSchedulePolicy.py
mage_ai/api/policies/SeedPolicy.py
mage_ai/api/policies/mixins/user_permissions.py
mage_ai/api/presenters/BasePresenter.py
mage_ai/api/presenters/SeedPresenter.py
mage_ai/api/presenters/UserPresenter.py
mage_ai/api/resources/RoleResource.py
mage_ai/api/resources/SeedResource.py
mage_ai/api/resources/UserResource.py
mage_ai/api/resources/shared/collective_loaders.py
mage_ai/api/utils.py
mage_ai/authentication/permissions/seed.py
mage_ai/authentication/permissions/seed_script.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/pages/settings/workspace/permissions/index.tsx
mage_ai/frontend/pages/settings/workspace/roles/index.tsx
mage_ai/orchestration/db/models/oauth.py
mage_ai/settings/__init__.py

Create permissions and roles based off existing API policies.
cc:

[td] Seed permissions based off policies

---

mage_ai/orchestration/db/models/oauth.py

[td] Fix fetching roles new for User

---

mage_ai/api/mixins/result_set.py
mage_ai/api/operations/base.py
mage_ai/api/policies/BasePolicy.py
mage_ai/api/policies/mixins/user_permissions.py
mage_ai/api/presenters/UserPresenter.py
mage_ai/api/resources/UserResource.py
mage_ai/authentication/oauth/utils.py
mage_ai/frontend/components/users/UserDetail.tsx
mage_ai/orchestration/db/__init__.py
mage_ai/orchestration/db/cache.py
mage_ai/orchestration/db/models/oauth.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/server/server.py

- Drastically speed up permissions checking by using previously granted permissions to authorize repeated checks
- Add optional ability to cache results from SQL session within a single API operation
cc:

[td] Speed up API

---

mage_ai/api/resources/BaseResource.py
mage_ai/api/resources/DatabaseResource.py
mage_ai/tests/api/resources/test_base_resource.py
mage_ai/tests/api/resources/test_database_resource.py
mage_ai/tests/api/resources/test_generic_resource.py
mage_ai/tests/api/resources/test_resource.py

- Add unit tests for `Resource`
- Add unit tests for `BaseResource`
- Add unit tests for `GenericResource`
- Add unit tests for `DatabaseResource`

[td] Test API base resource classes

---

.pre-commit-config.yaml
mage_ai/tests/api/mixins.py
mage_ai/tests/api/presenters/test_base_presenter.py
mage_ai/tests/api/presenters/test_mixins.py
mage_ai/tests/api/resources/test_database_resource.py
mage_ai/tests/api/utils.py

- Test all public methods for `BasePresenter`
cc:

[td] Unit test BasePresenter

---

mage_ai/api/policies/BasePolicy.py
mage_ai/tests/api/policies/test_base_policy.py

Add tests for `BasePolicy`
cc:

[td] Add unit tests for BasePolicy

---

mage_ai/api/policies/BasePolicy.py
mage_ai/authentication/permissions/constants.py
mage_ai/tests/api/policies/permissions/test_base_policy_with_permissions.py

- Test every permission access
cc:

[td] Test BasePolicy with permissions

---

mage_ai/api/policies/mixins/user_permissions.py
mage_ai/authentication/permissions/constants.py
mage_ai/tests/api/policies/permissions/test_base_policy_with_permissions.py

[td] Add more test cases for permissions

---

docs/design/blocks/conditionals.mdx
docs/guides/tips-and-tricks.mdx

Add conditionals video to tips & tricks and standardize capitalization. Tested locally

[mp] Add conditionals video

---

docs/integrations/spark-pyspark.mdx
mage_integrations/mage_integrations/sources/mssql/README.md
mage_integrations/mage_integrations/sources/mysql/README.md
mage_integrations/mage_integrations/sources/oracledb/README.md
mage_integrations/mage_integrations/sources/postgresql/README.md
mage_integrations/mage_integrations/sources/redshift/README.md
mage_integrations/mage_integrations/sources/snowflake/README.md

Update docs for Spark pipelines and data integration sources
Previewed locally
cc:

[xy] Update docs for Spark pipelines and data integration sources

---

mage_ai/api/policies/WorkspacePolicy.py
mage_ai/api/presenters/WorkspacePresenter.py
mage_ai/api/resources/ClusterResource.py
mage_ai/api/resources/StatusResource.py
mage_ai/api/resources/WorkspaceResource.py
mage_ai/cluster_manager/config.py
mage_ai/cluster_manager/constants.py
mage_ai/cluster_manager/errors.py
mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/cluster_manager/manage.py
mage_ai/data_preparation/repo_manager.py
mage_ai/frontend/pages/manage/index.tsx
mage_ai/server/api/clusters.py
mage_ai/server/server.py

* Add auto termination check in main project, will check every minute
* Add functionality to start and stop kubernetes workspaces
* Pass in workspace config to configure auto termination settings
* Refactor existing workspace code
config:
```
termination_policy:
enable_auto_termination: true
max_idle_seconds: 600
```
TODO:
* Add unit tests
* Add frontend (will do in a separate PR)

[dy] Update workspace resource for auto termination

---

mage_ai/api/views.py
mage_ai/tests/api/test_views.py

Test all permutations of using API views.

[td] Test API views

---

mage_ai/api/operations/base.py
mage_ai/api/policies/RolePolicy.py
mage_ai/api/presenters/PipelineTriggerPresenter.py
mage_ai/api/resources/DatabaseResource.py
mage_ai/api/resources/PermissionResource.py
mage_ai/api/resources/PipelineRunResource.py
mage_ai/api/resources/PipelineScheduleResource.py
mage_ai/api/resources/RoleResource.py
mage_ai/api/resources/StatusResource.py
mage_ai/tests/api/endpoints/mixins.py
mage_ai/tests/api/endpoints/test_permissions.py
mage_ai/tests/api/endpoints/test_pipeline_schedules.py
mage_ai/tests/api/endpoints/test_pipeline_triggers.py
mage_ai/tests/api/endpoints/test_projects.py
mage_ai/tests/api/endpoints/test_role_permissions.py
mage_ai/tests/api/endpoints/test_roles.py
mage_ai/tests/api/endpoints/test_schedulers.py
mage_ai/tests/api/endpoints/test_secrets.py
mage_ai/tests/api/endpoints/test_statuses.py
mage_ai/tests/api/endpoints/test_user_roles.py
mage_ai/tests/api/endpoints/test_variables.py
mage_ai/tests/base_test.py

[td] Test more API endpoints

---

mage_ai/api/policies/SparkApplicationPolicy.py
mage_ai/api/presenters/SparkApplicationPresenter.py
mage_ai/api/resources/SparkApplicationResource.py
mage_ai/services/spark/api/base.py
mage_ai/services/spark/api/local.py
mage_ai/services/spark/api/test.py
mage_ai/services/spark/models.py

[td] Spark UI API endpoints

---

Dockerfile
dev.Dockerfile
mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/bigquery/README.md
mage_integrations/mage_integrations/destinations/bigquery/templates/config.json
mage_integrations/mage_integrations/destinations/snowflake/README.md
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/templates/config.json
mage_integrations/mage_integrations/sources/bigquery/README.md

**1. Convert schema name to uppercase when disable_double_quotes.**
When using the lower case as the schema name and set `disable_double_quotes` to True, it fails to sync data to Snowflake.
Exceptions
* The alter table command tried to add duplicate columns
* When use_batch_load is true, it tried to insert the table name with lower case.
**2. This PR also updates the default config value of `use_batch_load` to true for BigQuery and Snowflake destinations.**
**3. This PR fixes the libcryto issue**
close: https://github.com/mage-ai/mage-ai/issues/3755
```
raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
```
* https://community.snowflake.com/s/article/Python-Connector-fails-to-connect-with-Lib …

[xy] Convert schema name to uppercase when disable_double_quotes.

---

mage_ai/frontend/components/ComputeManagement/ConnectionSettings.tsx
mage_ai/frontend/components/ComputeManagement/ResourceManagement.tsx
mage_ai/frontend/components/ComputeManagement/index.tsx
mage_ai/frontend/components/ComputeManagement/shared/KeyValueConfigurationSection.tsx
mage_ai/frontend/interfaces/ProjectType.ts

Configure resources for Spark.

[td] Resources view for compute management

---

docs/data-integrations/batch-pipelines.mdx
docs/mint.json
mage_ai/data_preparation/models/block/data_integration/mixins.py
mage_ai/data_preparation/templates/data_integrations/sources/base.py
mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/components/CodeBlock/BlockExtras/index.tsx
mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DataIntegrationModal/Credentials/InputsTable.tsx
mage_ai/frontend/components/DataIntegrationModal/Credentials/index.tsx
mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailOverview.tsx
mage_ai/frontend/components/DataIntegrationModal/StreamOverviewEditor.tsx
mage_ai/frontend/components/DataIntegrationModal/StreamSettingsEditorTable.tsx
mage_ai/frontend/components/DataIntegrationModal/StreamsOverview/index.tsx
mage_ai/frontend/components/DataIntegrationModal/constants.ts
mage_ai/frontend/components/DataIntegrationModal/index.style.tsx
mage_ai/frontend/components/DataIntegrationModal/index.tsx
mage_ai/frontend/components/PipelineDetail/AddonBlocks/AddonBlock.tsx
mage_ai/frontend/components/PipelineDetail/Extensions/constants.ts
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/utils/models/block.ts

[td] Document and fix bugs for data integration blocks

---

docs/data-integrations/batch-pipelines.mdx

[td] Add missing docs

---

docs/data-integrations/batch-pipelines.mdx
docs/interactions/overview.mdx
docs/mint.json
mage_ai/frontend/components/Interactions/InteractionDisplay.tsx
mage_ai/frontend/components/PipelineInteractions/index.tsx
mage_ai/frontend/oracle/components/Accordion/AccordionPanel.tsx
mage_ai/frontend/oracle/components/Accordion/index.tsx

[td] Add docs and fixes for interactions

---

docs/authentication/permissions/overview.mdx
docs/authentication/permissions/permissions.mdx
docs/authentication/permissions/roles.mdx
docs/interactions/overview.mdx
docs/mint.json
mage_ai/api/policies/SessionPolicy.py
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/Permissions/PermissionDetail.tsx
mage_ai/frontend/components/Roles/RoleDetail.tsx
mage_ai/frontend/components/settings/Dashboard/index.tsx
mage_ai/frontend/components/shared/Header/index.tsx

[td] Add docs for permissions and show avatar

---

mage_ai/server/constants.py
setup.py

[td] 0.9.35

---

docs/dbt/overview.mdx
requirements.txt
setup.py

Added and tested dbt-dremio support.
cc:

[dy] Add dbt-dremio dependency

---

mage_ai/cluster_manager/config.py
mage_ai/cluster_manager/manage.py

Fix default for WorkspaceConfig. This was originally in a bigger PR, but moving it to this one.
cc:

[dy] Fix WorkspaceConfig default

---

mage_ai/orchestration/db/setup.py
mage_ai/services/aws/__init__.py

Fix circular dependency that occurs when fetching db secrets from secret manager.
cc:

[dy] Fix aws secrets circular dependency

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/3751
- https://github.com/mage-ai/mage-ai/pull/3760
- https://github.com/mage-ai/mage-ai/pull/3784
- https://github.com/mage-ai/mage-ai/pull/3742
- https://github.com/mage-ai/mage-ai/pull/3783
- https://github.com/mage-ai/mage-ai/pull/3786
- https://github.com/mage-ai/mage-ai/pull/3788
- https://github.com/mage-ai/mage-ai/pull/3791

[td] 0.9.36

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/server/api/triggers.py

IndexError error in the upstream block of a dbt block
```
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1278, in execute_block
output = outputs[0]
IndexError: list index out of range
```
NoneType error in `api_trigger` endpoint
```
File \\"/usr/local/lib/python3.10/site-packages/tornado/web.py\\", line 1702, in _execute
result = method(*self.path_args, **self.path_kwargs)
File \\"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\\", line 123, in func_with_rollback
File \\"/usr/local/lib/python3.10/site-packages/mage_ai/server/api/triggers.py\\", line 18, in post
if ScheduleType.API == pipeline_schedule.schedule_type and \\\\
AttributeError: \'NoneType\' object has no attribute …
```

[xy] Two small bug fixes 

---

docs/mint.json

[mp] Fix Grouping on `mint.json`

---

mage_integrations/mage_integrations/destinations/bigquery/README.md
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/mssql/README.md
mage_integrations/mage_integrations/destinations/mssql/__init__.py
mage_integrations/mage_integrations/destinations/mssql/utils.py
mage_integrations/mage_integrations/destinations/mysql/README.md
mage_integrations/mage_integrations/destinations/mysql/__init__.py
mage_integrations/mage_integrations/destinations/oracledb/README.md
mage_integrations/mage_integrations/destinations/oracledb/__init__.py
mage_integrations/mage_integrations/destinations/oracledb/utils.py
mage_integrations/mage_integrations/destinations/postgresql/README.md
mage_integrations/mage_integrations/destinations/postgresql/__init__.py
mage_integrations/mage_integrations/destinations/redshift/README.md
mage_integrations/mage_integrations/destinations/redshift/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/README.md
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/utils.py
mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/destinations/sql/utils.py
mage_integrations/mage_integrations/tests/destinations/bigquery/test_bigquery.py
mage_integrations/mage_integrations/tests/destinations/mssql/test_mssql.py
mage_integrations/mage_integrations/tests/destinations/mysql/test_mysql.py
mage_integrations/mage_integrations/tests/destinations/oracledb/test_oracledb.py
mage_integrations/mage_integrations/tests/destinations/postgresql/test_postgres.py
mage_integrations/mage_integrations/tests/destinations/redshift/test_redshift.py
mage_integrations/mage_integrations/tests/destinations/snowflake/test_snowflake.py

Users have reported not being able to use case sensitive column names on SQL destinations in Data Integration pipelines. ( Slack threads [example-1](https://mageai.slack.com/archives/C03HTTWFEKE/p1696280965183949) and [example-2](https://mageai.slack.com/archives/C03HTTWFEKE/p1695309486767869) )
To fix this, the optinal config `lower_case` was added. If set to `False`, the requested Destination will allow for case sensitive column names when executing all `clean_column_name` functions.
This PR adds this feature to the following destinations:
1. Snowflake
2. PostgreSQL
3. Redshift
4. OracleDB
5. MySQL
6. MSSQL
7. BigQuery
Unittests were created at mage_integrations/tests/destinations folder.
These tests cover build-table enforcing case sensitive queries.
cc:

Case sensitive column names in DI SQL destinations

---

mage_ai/api/presenters/WorkspacePresenter.py
mage_ai/api/resources/WorkspaceResource.py
mage_ai/cluster_manager/config.py
mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/cluster_manager/manage.py
mage_ai/cluster_manager/workspace/base.py
mage_ai/cluster_manager/workspace/cloud_run.py
mage_ai/cluster_manager/workspace/ecs.py
mage_ai/cluster_manager/workspace/kubernetes.py
mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
mage_ai/frontend/oracle/components/Accordion/index.tsx
mage_ai/server/server.py

This PR refactors workspace code into a `Workspace` class to perform workspace related operations. 
There are also some bug fixes in this PR that were found during testing.

[dy] Refactor workspace

---

mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

[td] Refresh page when adding block and split view

---

mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/server/constants.py
setup.py

[td] 0.9.38

---

mage_ai/frontend/components/CodeBlock/index.style.tsx

[td] Fix code block header overflow menu

---

mage_ai/api/policies/UserPolicy.py

[td] Allow admin users to read attributes on users list

---

mage_ai/server/constants.py
setup.py

[td] 0.9.39

---

mage_ai/server/constants.py
setup.py

bug fixes
* https://github.com/mage-ai/mage-ai/pull/3839
* https://github.com/mage-ai/mage-ai/pull/3841
cc:

[dy] Bump 0.9.40

---

mage_ai/orchestration/db/models/schedules.py

[td] Fix dynamic children not running and its downstream

---

mage_ai/api/policies/BlockPolicy.py
mage_ai/api/policies/FileVersionPolicy.py
mage_ai/api/resources/BlockResource.py
mage_ai/api/resources/FileVersionResource.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/DependencyGraph/BlockNode/index.style.tsx
mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
mage_ai/frontend/components/DependencyGraph/BlockNode/utils.ts
mage_ai/frontend/components/DependencyGraph/constants.ts
mage_ai/frontend/components/DependencyGraph/index.style.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/DependencyGraph/utils.ts
mage_ai/frontend/components/FileVersions/index.tsx
mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

[td] Dependency graph tree v2

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/ComputeManagement/SparkGraph/index.tsx
mage_ai/frontend/components/DependencyGraph/BlockNode/index.style.tsx
mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
mage_ai/frontend/components/DependencyGraph/index.style.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/PipelineDetail/ColumnScroller/index.tsx

- Only fetch jobs from local spark app if compute feature enabled
- Fix split view scrolling when resizing window

[td] Only get spark jobs if compute enabled

---

mage_ai/data_preparation/models/project/__init__.py
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/interfaces/KernelType.ts
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

[td] Update header for compute management

---

mage_ai/frontend/utils/samples/adjectives.ts

[mp] remove 'throbbing' as potential adjective for new blocks

---

docs/getting-started/setting-up-git.mdx

This simple PR adds some additional verbiage around Git usage, as requested in [this](https://airtable.com/applEuqJsK4zF5yJK/tbl5bIlFkk2KhCpL4/viw3Q3HphkAoZ0KK1/recjZhIETmrIRt6Et?blocks=hide) ticket.

[mp] Update Git Sync Docs

---

Dockerfile
dev.Dockerfile
mage_integrations/mage_integrations/connections/mssql/__init__.py
mage_integrations/mage_integrations/destinations/mssql/README.md
mage_integrations/mage_integrations/destinations/mssql/__init__.py
mage_integrations/mage_integrations/sources/mssql/README.md
mage_integrations/mage_integrations/sources/mssql/__init__.py
mage_integrations/requirements.txt

Remove pymssql and freetds dependencies to resolve the conflicts between libodbc1 and libodbc2.
Use pyodbc library in mage_integrations module to connect to Microsoft SQL Server.
cc:

[xy] Remove pymssql dependency

---

docs/mint.json
docs/production/developing-in-the-cloud/workspaces/kubernetes.mdx
docs/production/developing-in-the-cloud/workspaces/overview.mdx

Update workspace documentation with new config fields.
cc:

[dy] Update workspace documentation

---

.github/workflows/build_and_test.yml
mage_integrations/requirements.txt
requirements.txt
setup.py

Bump `snowflake-connector-python` to version 3.2.1 to include some recent bug fixes. Also, bump `dbt-snowflake` to 1.4.4.

[dy] Bump snowflake-connector-python version

---

mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/destinations/trino/connectors/base.py
mage_integrations/mage_integrations/tests/destinations/bigquery/test_bigquery.py
mage_integrations/mage_integrations/tests/destinations/mssql/test_mssql.py
mage_integrations/mage_integrations/tests/destinations/mysql/test_mysql.py
mage_integrations/mage_integrations/tests/destinations/oracledb/test_oracledb.py
mage_integrations/mage_integrations/tests/destinations/postgresql/test_postgres.py
mage_integrations/mage_integrations/tests/destinations/redshift/test_redshift.py
mage_integrations/mage_integrations/tests/destinations/snowflake/test_snowflake.py
mage_integrations/mage_integrations/tests/destinations/sql/mixins.py
mage_integrations/mage_integrations/tests/destinations/test_base.py

Improve base DI destination
* Update the base destination class to abstract class
* Move abstract methods up (test_connection, export_batch_data)
* Move class methods down
Add unit tests.
* Add abstract class for base destination tests and require some tests to be written
* Add base tests for SQL destinations
* Implement unit tests for SQL destination
Close: https://github.com/mage-ai/mage-ai/issues/3138
cc:

[xy] Improve base DI destination and add unit tests.

---

docs/data-integrations/overview.mdx
mage_ai/data_integrations/destinations/constants.py
mage_integrations/mage_integrations/destinations/elasticsearch/README.md
mage_integrations/mage_integrations/destinations/elasticsearch/__init__.py
mage_integrations/mage_integrations/destinations/elasticsearch/target_elasticsearch/common.py
mage_integrations/mage_integrations/destinations/elasticsearch/target_elasticsearch/sinks.py
mage_integrations/mage_integrations/destinations/elasticsearch/target_elasticsearch/target.py
mage_integrations/mage_integrations/destinations/elasticsearch/templates/config.json
mage_integrations/requirements.txt

Adding Elasticsearch Destination to Data Integration Pipelines
All tests for this destination were executed using elasticsearch==7.11.0 python version, this allowed to run elasticsearch code without product check.
Fail:
Success:
This destination uses Table Name config as Index name by default, example:
cc:

Added Elasticsearch Destination to Data Integrations

---

docs/data-integrations/overview.mdx
mage_integrations/mage_integrations/destinations/opensearch/README.md
mage_integrations/mage_integrations/destinations/opensearch/__init__.py
mage_integrations/mage_integrations/destinations/opensearch/target_opensearch/sinks.py
mage_integrations/mage_integrations/destinations/opensearch/target_opensearch/target.py
mage_integrations/mage_integrations/destinations/opensearch/templates/config.json

Added connection test to opensearch
Modified index naming to match elasticsearch destination ( using table name by default )
cc:

Added test connection and new index naming

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/3845
* https://github.com/mage-ai/mage-ai/pull/3846
* https://github.com/mage-ai/mage-ai/pull/3847
* https://github.com/mage-ai/mage-ai/pull/3827
* https://github.com/mage-ai/mage-ai/pull/3851
* https://github.com/mage-ai/mage-ai/pull/3852
* https://github.com/mage-ai/mage-ai/pull/3854
* https://github.com/mage-ai/mage-ai/pull/3856
* https://github.com/mage-ai/mage-ai/pull/3834
* https://github.com/mage-ai/mage-ai/pull/3859
* https://github.com/mage-ai/mage-ai/pull/3857
* https://github.com/mage-ai/mage-ai/pull/3819
* https://github.com/mage-ai/mage-ai/pull/3849
* https://github.com/mage-ai/mage-ai/pull/3816
* https://github.com/mage-ai/mage-ai/pull/3843
* https://github.com/mage-ai/mage-ai/pull/3855
* https://github.com/mage-ai/mage-ai/pull/3799 …

[xy] Bump version to 0.9.41.

---

mage_ai/services/email/config.py
mage_ai/services/email/email.py
mage_ai/tests/services/email/test_email.py

Allow sending emails without TLS. When username and password are not configured in email config, don't set TLS and login.
cc:

[xy] Allow sending emails without TLS

---

mage_ai/api/policies/BasePolicy.py

[td] Fix permissions policy for owners

---

mage_ai/services/k8s/config.py
mage_ai/services/k8s/job_manager.py
mage_ai/tests/services/k8s/test_job_manager.py

Add more unit tests to k8s job manager.
- [] Unit tests
cc:

[xy] Add more unit tests to k8s job manager.

---

mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/interfaces/KernelType.ts
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

Reverts mage-ai/mage-ai#3852
The pipeline editor pages keeps making /api/spark_applications requests, which causes many backend errors

Revert "[td] Update header for compute management"

---

mage_ai/api/resources/PipelineResource.py
mage_ai/cache/tag.py
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/pages/pipelines/index.tsx

This PR adds a `No tags` filtering option on the `/pipelines` page.

[jk] Add "No tags" filtering option for pipelines

---

mage_ai/data_preparation/templates/data_loaders/druid.py

The method name is incorrect and says "load_data_from_postgres". Corrected it to "load_data_from_druid". 
- Tested the changes locally.
cc:

[Bugfix] Update druid.py to have correct method name

---

mage_ai/data_preparation/models/project/__init__.py
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/interfaces/KernelType.ts
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

[td] Update header for compute management w/ fixes

---

.github/pull_request_template.md
docs/mint.json

Add DuckDB to mint.json and update PR checklist

[mp] add DuckDB to `mint.json`

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/DependencyGraph/index.style.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/DependencyGraph/utils.ts

Address comments from https://github.com/mage-ai/mage-ai/pull/3886

[td] Address PR comments on Tree v2 PR

---

.github/workflows/build_and_test.yml
mage_ai/ai/llm_pipeline_wizard.py
mage_ai/tests/ai/test_ai_functions.py
requirements.txt
setup.py

Add 5 tests for all public methods in llm_pipeline_wizard
`python -m unittest mage_ai/tests/ai/test_ai_functions.py`
cc:

[xh]Add test functions for AI class

---

mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailOverview.tsx
mage_ai/frontend/components/DataIntegrationModal/index.tsx
mage_ai/frontend/utils/models/block.ts
mage_integrations/mage_integrations/sources/sftp/tap_sftp/client.py
mage_integrations/mage_integrations/sources/sftp/tap_sftp/singer_encodings/json_schema.py

This PR fixes some issues with the sftp client. The SFTP schema was returning the type of the field as a string field instead of an array for some fields. The frontend also would just error out when the type was not an array, so I added some additional checks in the frontend as well.
cc:

[dy] Fix sftp client side exception

---

docs/contributing/development-environment.mdx

Minor corrections in doc
- [ N/A ] Test A
- [ N/A ] Test B
cc:

[Doc] Improvements to development environment doc

---

mage_ai/data_preparation/models/block/data_integration/data.py
mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DataIntegrationModal/index.tsx

https://mageai.slack.com/archives/C03HTTWFEKE/p1698908640321099
An upstream block contained a Pandas Timestamp column.
When trying to serialize Timestamp data type to JSON when exporting to BigQuery destination, an error is raised.

[td] Fix JSON serializing Timestamp when exporting to BigQuery

---

mage_ai/data_preparation/models/pipeline.py

Speed up Pipeline UPDATE API. The pipeline update requests become slow when there're a lot of pipelines in the project.
When `update_content=true` is set in the Pipeline PUT request, it updates the block content when the 'content' key is set in block data. The slowness mainly comes from the block action object cache update. It reads and updates the block action object cache file which contains the block data of the whole project.
**Updates in this PR**
* Not update the block content and cache when the block content doesn't change.
* Not initialize the BlockActionObjectCache repeatedly
A future optimization is needed to not store all the block object cache data in one file.
cc:

[xy] Speed up Pipeline UPDATE API.

---

requirements.txt
setup.py

Restrict the version of openai.
The new release of `openai` deprecated many functions which causes the tests to fail
https://github.com/openai/openai-python/discussions/631
```
======================================================================
ERROR: test_async_generate_block_with_description (tests.ai.test_ai_functions.AIFunctionTest)
----------------------------------------------------------------------
File "/home/runner/work/mage-ai/mage-ai/mage_ai/tests/ai/test_ai_functions.py", line 48, in setUp
self.wizard = LLMPipelineWizard()
File "/home/runner/work/mage-ai/mage-ai/mage_ai/ai/llm_pipeline_wizard.py", line 194, in __init__
self.llm = OpenAI(openai_api_key=openai_api_key, temperature=0)
File …
```

[xy] Restrict the version of openai.

---

mage_ai/ai/llm_pipeline_wizard.py
mage_ai/api/presenters/KernelPresenter.py
mage_ai/api/resources/BlockResource.py
setup.py

Bump version to 0.9.42
* https://github.com/mage-ai/mage-ai/pull/3880
* https://github.com/mage-ai/mage-ai/pull/3535
* https://github.com/mage-ai/mage-ai/pull/3881
* https://github.com/mage-ai/mage-ai/pull/3884
* https://github.com/mage-ai/mage-ai/pull/3885
* https://github.com/mage-ai/mage-ai/pull/3887
* https://github.com/mage-ai/mage-ai/pull/3888
* https://github.com/mage-ai/mage-ai/pull/3870
* https://github.com/mage-ai/mage-ai/pull/3882
* https://github.com/mage-ai/mage-ai/pull/3867
* https://github.com/mage-ai/mage-ai/pull/3886
* https://github.com/mage-ai/mage-ai/pull/3892
* https://github.com/mage-ai/mage-ai/pull/3893
* https://github.com/mage-ai/mage-ai/pull/3891
* https://github.com/mage-ai/mage-ai/pull/3897
* https://github.com/mage-ai/mage-ai/pull/3818
* …

[xy] Bump version to 0.9.42

---

mage_ai/server/constants.py

Update version in server constants.py to 0.9.42
N/A
N/A
cc:

[xy] Update version in server constants.py

---

docs/design/blocks/sensor.mdx

- [ N/A ] Test A
- [ N/A ] Test B
cc:

[Doc] Add sensor check frequency in the docs

---

.github/workflows/build_and_test.yml

Remove libkrb5-dev from build_and_test.yml to fix CI failure
cc:

[xy] Remove libkrb5-dev from build_and_test.yml

---

mage_ai/api/resources/PipelineResource.py
mage_ai/cluster_manager/aws/emr_cluster_manager.py
mage_ai/data_preparation/executors/pyspark_block_executor.py
mage_ai/data_preparation/executors/pyspark_pipeline_executor.py
mage_ai/server/active_kernel.py
mage_ai/services/aws/emr/emr.py
mage_ai/services/aws/emr/launcher.py

Support pipeline level EMR config.
The EMR config can be configured in pipeline metadata.yaml file under `executor_config`
Project metadata.yaml
Pipeline metadata.yaml
Before the change, the EMR cluster uses the project level emr_config
With the change, the EMR cluster can use the pipeline level emr_config
cc:

[xy] Support pipeline level emr config.

---

docs/authentication/permissions/overview.mdx
docs/authentication/permissions/permissions.mdx
docs/authentication/permissions/roles.mdx
docs/data-integrations/batch-pipelines.mdx
docs/data-integrations/destinations/overview.mdx
docs/mint.json
docs/production/data-sync/git-sync.mdx

- Updates the definition of `GIT_AUTH_TYPE` to reflect possible values mentioned [here](https://mageai.slack.com/archives/C03GGQTS8CT/p1699291194140329)
- Removes duplicate item in `mint.json`
- Removes icons on secondary-level pages, which is inconsistent with the rest of our docs.

[mp] Update git variable definition, remove misc icons that don't conform to style

---

mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/context/shared/utils.ts

This PR includes the changes from PR #3889, except it fixes the bug where code editors in the Sidekick could sometimes be disabled (see Johnson's comments in that PR). The offending code was this block that was added in `CodeEditor/index.tsx`:
```
editor.onDidBlurEditorWidget(() => {
setTextareaFocused?.(false);
});
```
I've removed that block of code for now to fix the issue. It was never actually needed for my previous PR but I had added it because it seemed like missing code. Now, it's clear that `textareaFocused` has much more dependencies that I initially realized, and changes to it shouldn't be included in this PR 😅
Same procedure as PR #3889! The fixed code editor is shown here:
https://github.com/mage-ai/mage-ai/assets/8130751/3f6dd1af-d173-487a-8c3d-74963cf4c196

[ac]  Add keyboard shortcuts for inserting new scratchpad cell

---

docs/guides/ai/ai-client.mdx
docs/mint.json

Add documentation for (1) how to use hugging face client (2) how to add new client
Previewed mdx
cc:

[xh]Add documentation for (1) how to use hugging face client (2) how to add new client

---

mage_ai/data_preparation/models/block/data_integration/mixins.py
mage_ai/presenters/interactions/utils.py

[td] Make 2nd argument of lambda function optional

---

mage_ai/frontend/components/settings/Dashboard/constants.tsx
mage_ai/frontend/pages/settings/workspace/sync-data.tsx

Update permissions for the git settings page. There are policy checks on the backend for updating the git settings, so we can rely on those instead of gating the settings page in the frontend.
Also, update the error handling on the `sync-data` page.
cc:

[dy] Update git settings permissions

---

mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/frontend/components/workspaces/Dashboard/constants.ts

* Add the base path for the workspace if it exists when getting the workload activity
* Use `patch_namespaced_stateful_set` instead of `patch_namespaced_stateful_set_scale`
* Always show the settings tab in the frontend
cc:

[dy] Misc workspace changes

---

mage_integrations/mage_integrations/destinations/base.py
mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/target.py
mage_integrations/mage_integrations/tests/destinations/mongodb/test_mongodb.py
mage_integrations/mage_integrations/tests/destinations/test_base.py

Not set `export_batch_data` method as abstractmethod.
Add unit test for MongoDB destination.
cc:

[xy] Fix MongoDB destination and add unit test

---

mage_integrations/mage_integrations/destinations/sql/base.py

Close: #3936
Escape the reserved word correctly for the unique constraints columns.
cc:

[xy] Fix sql destination reserved words.

---

mage_ai/frontend/components/CodeBlock/constants.ts
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DataIntegrationModal/index.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/Interactions/BlockInteractionController.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/PipelineInteractions/index.tsx
mage_ai/frontend/utils/array.ts

[td] Fix notebook block ordering for upstream blocks

---

docs/dbt/run-selected-model.mdx

[td] Document how to interpolate data into dbt generic command

---

dev.spark.Dockerfile
docker-compose.yml
mage_ai/data_preparation/models/block/spark/mixins.py
mage_ai/services/spark/utils.py

- Fix dev dockerfile for using Spark
- Is using EMR, fix API calls

[td] Fix Dockerfile and API when using EMR

---

mage_ai/tests/base_test.py
mage_ai/tests/data_preparation/test_repo_manager.py

Failure
https://github.com/mage-ai/mage-ai/actions/runs/6831035158/job/18579926129
Fix secrets dir delete warning.
cc:

[xy] Fix unit tests warnings and errors

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.44.
Management
Editor
Orchestration
Others
N/A
cc:

[xy] Bump version to 0.9.44.

---

mage_ai/data_preparation/templates/repo/io_config.yaml

Minor fix, using Pinot broker configuration instead of Pinot controller port.
- [ Yes ] Tested locally
cc:

[Bugfix] Minor bug fix in Pinot config on io_config.yaml

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/block_sql.py
mage_ai/data_preparation/models/block/dbt/utils.py

Move DBT seed logic to downstream block.
Close: https://github.com/mage-ai/mage-ai/issues/3702
cc:

[xy] Move dbt seed logic to downstream block.

---

docs/guides/tips-and-tricks.mdx

Update tips and tricks page with a few more walkthrough videos

[mp] update tips & tricks

---

mage_ai/api/policies/GitCustomBranchPolicy.py
mage_ai/api/resources/GitBranchResource.py
mage_ai/api/resources/GitCustomBranchResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/git/api.py
mage_ai/frontend/components/VersionControl/Remote/index.tsx
mage_ai/frontend/interfaces/GitBranchType.ts

Some users want to use a personal access token to use the version control instead of authenticating with Github. This PR will change the version control app to use a personal access token if it is provided in the Git settings for the user.
cc:

[dy] Use personal access token if available

---

docs/guides/tips-and-tricks.mdx

[mp] tips/tricks hotfix

---

mage_integrations/mage_integrations/sources/api/__init__.py

Added application/gzip support to API source
Tested using local flask API to a PostgreSQL destination
Snippet used in generating the gzip file:
```python
@app.route("/")
def hello_world():
very_long_content = [{'column1': 1, 'column2': 2}, {'column3': 3, 'column4': 4}]
content = gzip.compress(json.dumps(very_long_content).encode('utf8'), 5)
response = make_response(content)
response.headers['Content-length'] = len(content)
response.headers['Content-Encoding'] = 'gzip'
return response
```
cc:

Added application/gzip support to API source

---

mage_ai/api/presenters/WorkspacePresenter.py
mage_ai/cluster_manager/workspace/base.py
mage_ai/tests/api/endpoints/test_workspaces.py

Workspaces were not getting fetched properly in the user management page. This PR fixes the issue and adds some unit tests for the workspaces resource
cc:

[dy] Fix workspace user management fetching

---

docs/mint.json
docs/production/authentication/google.mdx
docs/production/authentication/okta.mdx

Add docs for setting up okta and google sign in.
cc:

[dy] Add sso docs

---

docs/integrations/observability/prometheus.mdx
docs/mint.json

Add documentation page for Prometheus integration
cc:
@dy46

prometheus: add documentation

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/BlocksInPipeline/index.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/constants.ts
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

Fixes: https://github.com/mage-ai/mage-ai/issues/3947
https://github.com/mage-ai/mage-ai/assets/1066980/fe6b484d-97f9-47cf-a40c-aa4aa8874b92

[td] Handle hidden block positions when split view

---

mage_ai/api/policies/GlobalHookPolicy.py
mage_ai/api/presenters/GlobalHookPresenter.py
mage_ai/api/resources/GlobalHookResource.py
mage_ai/authentication/permissions/constants.py
mage_ai/data_preparation/models/global_hooks/models.py
mage_ai/data_preparation/models/project/__init__.py
mage_ai/data_preparation/models/project/constants.py
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/services/compute/aws/models.py
mage_ai/services/compute/models.py
mage_ai/services/spark/models/applications.py
mage_ai/shared/models.py

Add models to store information about global hooks that can be executed attached to a resource operation.
- GlobalHook
- Hook
cc:

[td] Global hooks backend

---

mage_ai/frontend/api/utils/url.ts
mage_ai/frontend/components/CodeEditor/index.tsx

Adjust the monoco editor vs path based on the base path.

[dy] Fix monoco editor for base path

---

mage_ai/tests/api/endpoints/test_workspaces.py
mage_ai/tests/api/operations/test_syncs.py
mage_integrations/mage_integrations/tests/sources/api/test_api.py

Attempt to fix some flaky tests that were intermittently failing. Will monitor CI results to see if they are resolved.
cc:

[dy] Fix flaky tests

---

mage_integrations/mage_integrations/sources/api/__init__.py

Add better error message for API source to avoid confusion.
Original error message: `"message": "Api process failed with error object of type 'NoneType' has no len()."`
cc:

[xy] Add better error message for API source.

---

mage_ai/api/operations/base.py
mage_ai/api/policies/GlobalHookPolicy.py
mage_ai/api/resources/GlobalHookResource.py
mage_ai/data_preparation/models/global_hooks/models.py
mage_ai/shared/models.py
mage_ai/tests/api/operations/test_operations.py
mage_ai/tests/api/operations/test_operations_with_hooks.py

Add hooks to API base operation.
- Unit test operations when hooks are enabled and present
cc:

[td] Attach global hook to resource operation

---

mage_ai/api/operations/base.py
mage_ai/data_preparation/models/global_hooks/models.py
mage_ai/shared/hash.py
mage_ai/tests/shared/test_hash.py

This reverts commit f5a043ec947f27243f8be32d827fd3477130a15a.
cc:

Revert "fix"

---

mage_ai/data_preparation/models/global_hooks/models.py
mage_ai/orchestration/triggers/api.py
mage_ai/tests/api/operations/test_operations_with_hooks.py
mage_ai/tests/data_preparation/models/global_hooks/test_global_hooks.py
mage_ai/tests/data_preparation/models/global_hooks/test_hook.py
mage_ai/tests/factory.py
mage_ai/tests/shared/mixins.py

Add unit tests for:
- Global hooks model
- Hook model
- API endpoints using hooks
- Pipeline update with block content
cc:

[td] Additional global hook unit tests

---

mage_ai/api/resources/PipelineResource.py
mage_ai/data_preparation/models/global_hooks/models.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/tests/api/operations/test_operations_with_hooks.py
mage_ai/tests/factory.py
mage_ai/tests/shared/mixins.py

Add unit tests for API operations using hooks.
cc:

[td] Add tests for API operations with hooks

---

mage_ai/api/policies/BasePolicy.py
mage_ai/api/policies/GlobalHookPolicy.py
mage_ai/api/presenters/GlobalHookPresenter.py
mage_ai/api/resources/AsyncBaseResource.py
mage_ai/api/resources/GlobalHookResource.py
mage_ai/data_preparation/models/global_hooks/constants.py
mage_ai/data_preparation/models/project/__init__.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
mage_ai/frontend/components/GlobalHooks/GlobalHooksList/index.style.tsx
mage_ai/frontend/components/GlobalHooks/GlobalHooksList/index.tsx
mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
mage_ai/frontend/components/shared/SetupSection/index.tsx
mage_ai/frontend/interfaces/GlobalHookType.ts
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
mage_ai/frontend/oracle/elements/Inputs/Select.tsx
mage_ai/frontend/pages/global-hooks/[...slug].tsx
mage_ai/frontend/pages/global-hooks/index.tsx

Add pages to:
- View list of hooks
- Detail/Edit view of the hook
- Delete action

[td] UI/UX to create and manage global hooks

---

mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx
mage_ai/frontend/pages/global-hooks/index.tsx

Delete global hooks from the UI

[td] Delete hooks

---

docs/integrations/databases/GoogleSheets.mdx

Fixes link based on Thomas' observation
https://mageai.slack.com/archives/C03GGQTS8CT/p1700261160758669?thread_ts=1700244207.348439&cid=C03GGQTS8CT

[mp] correct link

---

docs/mint.json

This PR updates the `metadata` property in `mint.json` to properly display our og image. It also adds a default description and site name for indexing, which should improve how our links are displayed (and help SEO).

[mp] update docs metadata

---

docs/getting-started/setup.mdx

Brief PR to add terminal instructions to the quickstart docs.

[mp] Add terminal instructions on quickstart

---

mage_ai/data_preparation/models/project/__init__.py

[td] Hide global hooks feature flag

---

mage_ai/api/policies/IntegrationSourcePolicy.py
mage_ai/api/presenters/IntegrationSourcePresenter.py
mage_ai/api/presenters/PipelineRunPresenter.py
mage_ai/api/presenters/PipelineSchedulePresenter.py
mage_ai/api/resources/IntegrationSourceResource.py
mage_ai/data_integrations/utils/scheduler.py
mage_ai/data_preparation/models/block/data_integration/utils.py
mage_ai/orchestration/db/models/schedules.py

Create API endpoint for fetching information about the current bookmark value and which pipeline schedule and pipeline run it’s from.
```json
{
"integration_source": {
"name": null,
"partition": "255/20231125T001015",
"pipeline_run": {
"execution_date": "2023-11-25 00:10:15.817107+00:00",
"id": 1042,
"status": "completed"
},
"pipeline_schedule": {
"id": 255,
"name": "golden artifact",
"schedule_interval": "@once",
"schedule_type": "time",
"settings": null,
"variables": null
},
"streams": {
"titanic": {
"record": {
"passengerid": 891,
"survived": null,
"pclass": null,
"name": null,
"sex": null,
"age": null,
"sibsp": null,
"parch": null,
"ticket": null,
"fare": null,
"cabin": null,
"embarked": null,
"_mage_created_at": null,
"_mage_updated_at": null
},
"state": {
"bookmarks": {
"titanic": { …
```

[td] Backend API for getting information about bookmarks

---

mage_ai/frontend/components/Triggers/OverwriteVariables/index.tsx
mage_ai/frontend/components/Triggers/RunPipelinePopup/index.tsx
mage_ai/frontend/oracle/components/Panel/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

Add any runtime variables regardless if it’s in the pipeline.
cc:

[td] Add any runtime variables

---

mage_ai/streaming/sinks/postgres.py

Fixes issue https://github.com/mage-ai/mage-ai/issues/4063
- [ N/A ] Test A
- [ N/A ] Test B
cc:

[sm] Fix postgres streaming sink when there are no messages

---

docs/guides/load-api-data.mdx

Updated text from "Finally, we'll write the transformed data to a locak DuckDB table." -> "Finally, we'll write the transformed data to a local DuckDB table."
There is no testing need, it's just a formatting change.
cc:
No one to comment! 👍

Update load-api-data.mdx to correct misspelling error

---

docs/orchestration/triggers/events/aws.mdx

Correct the orchestration doc related to env variable names
N/A
cc:

[sm] Correct the orchestration doc related to env variable names

---

mage_ai/orchestration/pipeline_scheduler.py

Pipeline scheduler sometimes crashes due to invalid data integration pipeline.
This PR catches the exception to prevent pipeline scheduler crash.
cc:

[xy] Catch execption of empty integration streams in pipeline scheduler.

---

mage_ai/api/presenters/PipelineSchedulePresenter.py

Remove debugging print message.

[td] Remove accidental print statement

---

mage_integrations/mage_integrations/sources/postmark/__init__.py
mage_integrations/mage_integrations/sources/postmark/tap_postmark/postmark.py
mage_integrations/mage_integrations/sources/postmark/tap_postmark/schemas/messages_outbound.json
mage_integrations/mage_integrations/sources/postmark/tap_postmark/streams.py
mage_integrations/mage_integrations/sources/postmark/tap_postmark/sync.py

Include message_events_json in Postmark messages_outbound stream
cc:

[xy] Include message_events_json in Postmark messages_outbound stream

---

docs/production/data-sync/github.mdx

Update Github integration docs to include information about how to connect to GHE.
cc:

[dy] Update Github docs for GHE

---

requirements.txt
setup.py

The previous version got yanked from pypi, so changing it to use a stable version.
cc:

[dy] Update opentelemetry-exporter-prometheus package version

---

docs/data-integrations/destinations/overview.mdx

This PR fixes the description of [data integration destinations](https://docs.mage.ai/data-integrations/destinations/overview) as raised in #4053 
cc:
@mattppal

Fix destinations technical documentation

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.47
Management
Editor
Orchestration
Others
N/A
cc:

[xy] Bump version to 0.9.47

---

setup.py

[xy] Fix chromadb dependency.

---

setup.py

Fix chromadb in all package.
cc:

[xy] Fix chromadb in all package.

---

mage_ai/api/operations/base.py
mage_ai/data_preparation/models/project/__init__.py
mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/server/server.py

- Fix UI spacing
- Add `/global-hooks` route to server
- Show Global hooks in sidebar navigation if enabled
- Hide global hooks feature in project preferences
cc:

[td] Add global hooks route to server

---

mage_ai/frontend/components/Triggers/OverwriteVariables/index.tsx

[td] Remove console log

---

docs/integrations/databases/ClickHouse.mdx

Add data exporter for ClickHouse in mdx file
Related Slack thread: https://mageai.slack.com/archives/C03HTTWFEKE/p1700653736340409
- [ Yes ] tested by running the doc server locally
cc:

[sm] Add data exporter for ClickHouse in mdx file

---

docs/design/data-loading.mdx

The doc had lot of code wrapped in python code block as can be seen in screenshot below:
Post the fix:
Not applicable
cc:

[sm] Doc bugfix in data-loading doc for DuckDB and Snowflake

---

mage_ai/data_integrations/utils/scheduler.py
mage_ai/orchestration/metrics/pipeline_run.py
mage_ai/orchestration/pipeline_scheduler.py

Revert "[dy] Optimize calculate metrics for integration pipelines"

---

mage_ai/api/resources/PipelineResource.py
mage_ai/frontend/pages/pipelines/index.tsx

Pagination wasn’t working when sorting.
cc:

[td] Fix pagination

---

docs/production/deploying-to-cloud/aws/terraform-apply-policy.mdx

Thank you Josh Pachner!
https://mageai.slack.com/archives/C03KW780J2F/p1702072412311739?thread_ts=1702072406.532729&cid=C03KW780J2F

[td] Update terraform-apply-policy.mdx

---

mage_ai/api/resources/LogResource.py
mage_ai/api/resources/PipelineRunResource.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DependencyGraph/utils.ts
mage_ai/frontend/components/Logs/Table/index.tsx
mage_ai/orchestration/db/models/schedules.py
mage_ai/tests/factory.py
mage_ai/tests/orchestration/db/models/test_schedules.py

- Add unit test for PipelineRun
- Fix Logs table to show more of the name
- Fix retry blocks to retry dynamic blocks
cc:

[td] Add tests and improve logs table

---

mage_ai/orchestration/db/models/schedules.py
mage_ai/tests/orchestration/db/models/test_schedules.py

Added additional unit test for global hook when pipeline executing.
cc:

[td] Add more tests for pipeline execute global hook

---

mage_ai/server/constants.py
setup.py

- https://github.com/mage-ai/mage-ai/pull/4138
- https://github.com/mage-ai/mage-ai/pull/4048
- https://github.com/mage-ai/mage-ai/pull/4131
- https://github.com/mage-ai/mage-ai/pull/4130
- https://github.com/mage-ai/mage-ai/pull/4128
- https://github.com/mage-ai/mage-ai/pull/4072
- https://github.com/mage-ai/mage-ai/pull/4126
- https://github.com/mage-ai/mage-ai/pull/4133
- https://github.com/mage-ai/mage-ai/pull/4132
- https://github.com/mage-ai/mage-ai/pull/4144
- https://github.com/mage-ai/mage-ai/pull/4148
- https://github.com/mage-ai/mage-ai/pull/4141
- https://github.com/mage-ai/mage-ai/pull/4058
- https://github.com/mage-ai/mage-ai/pull/4147
- https://github.com/mage-ai/mage-ai/pull/4109
- https://github.com/mage-ai/mage-ai/pull/4152
- https://github.com/mage-ai/mage-ai/pull/4156 …

[td] 0.9.49

---

mage_ai/server/constants.py
setup.py

[td] 0.9.50

---

docs/production/data-sync/git-sync.mdx
mage_ai/data_preparation/preferences.py
mage_ai/settings/__init__.py

Add another environment variable to allow users to set git settings as environment variables and overwrite them through the UI. 
cc:

[dy] Update git settings when environment variables are set

---

mage_ai/api/operations/base.py
mage_ai/data_preparation/models/global_hooks/models.py

Show errors when debug is on.
Fix missing KWARGS.

[td] Fix silent errors from global hooks

---

mage_ai/api/operations/base.py

Add avatar, first name, last name, and username in the user kwargs for hooks.

[td] Add more user information in hooks kwargs

---

docs/mint.json
docs/streaming/sources/rabbitmq.mdx

Added source doc for RabbitMQ
cc:

[sm] Add source doc for RabbitMQ

---

mage_ai/frontend/pages/404.tsx

This PR will add a custom 404 page, which (1) display an error toast telling the user the previous URL doesn't exist, and then redirect them to `/pipelines`.

[edw] Add custom 404 page

---

mage_ai/tests/data_preparation/shared/test_secrets.py

[td] Fix secrets test

---

mage_ai/orchestration/db/models/schedules.py
mage_ai/tests/data_preparation/shared/test_secrets.py
mage_ai/tests/orchestration/db/models/test_schedules.py

Optimize some schedule queries. Some queries were pulling all pipeline runs for a schedule when they just needed to get a count which could cause problems when there are a lot of runs.
Also, fixing a bunch of schedules related tests.
cc:

[dy] Rewrite schedule queries

---

mage_ai/api/policies/CustomDesignPolicy.py
mage_ai/api/presenters/CustomDesignPresenter.py
mage_ai/api/resources/CustomDesignResource.py
mage_ai/authentication/permissions/constants.py
mage_ai/data_preparation/models/project/constants.py
mage_ai/data_preparation/models/project/models.py
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/presenters/design/constants.py
mage_ai/presenters/design/models.py

Add base files for configuring custom designs in the application.
cc:

[td] Add models for custom design framework

---

mage_ai/api/policies/CustomDesignPolicy.py
mage_ai/api/presenters/CustomDesignPresenter.py
mage_ai/api/resources/CustomDesignResource.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/ButtonItems.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/constants.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
mage_ai/frontend/components/shared/Header/index.style.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/CacheItemType.ts
mage_ai/frontend/interfaces/ClientPageType.ts
mage_ai/frontend/interfaces/CustomDesignType.ts
mage_ai/frontend/interfaces/ProjectPlatformType.ts
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/frontend/pages/test.tsx
mage_ai/frontend/utils/models/customDesign/useCustomDesign.ts
mage_ai/presenters/design/models.py
mage_ai/shared/hash.py

https://github.com/mage-ai/mage-ai/assets/1066980/228a944e-1194-4929-bbc3-684b57cf38e7
cc:

[td] Custom design for UI

---

mage_ai/data_preparation/models/block/platform/mixins.py
mage_ai/shared/path_fixer.py

Don’t try to use file source path for backwards compatability.
cc:

[td] Don’t try to use file source if not exist

---

mage_ai/server/constants.py
setup.py

0.9.52 try 2

---

mage_ai/data_preparation/models/block/__init__.py

Missing file raises error for git API endpoint.
cc:
@dy46

[td] Fix missing git module

---

mage_ai/data_preparation/models/block/platform/mixins.py

[td] Don’t construct the project path for dbt yaml files

---

mage_ai/api/policies/GitBranchPolicy.py
mage_ai/api/policies/GitCustomBranchPolicy.py

Add some git actions to the GitBranchPolicy
cc:

[dy] Add actions to GitBranchPolicy

---

docs/production/developing-in-the-cloud/workspaces/overview.mdx
mage_ai/api/presenters/ProjectPresenter.py
mage_ai/api/resources/ProjectResource.py
mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/data_preparation/models/project/__init__.py
mage_ai/data_preparation/repo_manager.py
mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/frontend/pages/manage/index.tsx

Adds initial support for setting default values for workspace creation. There is no validation for the default values, but that will be a follow up to this feature.
cc:

[dy] Add default values for workspace creation

---

mage_ai/cache/dbt/utils.py
mage_ai/settings/models/configuration_option.py

Fix dbt profile interpolation.
cc:

[td] Fix dbt profiles interpolation

---

mage_ai/data_preparation/models/file.py
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/FileBrowser/Folder/index.tsx
mage_ai/frontend/components/FileBrowser/Folder/useFileIcon.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/FileEditor/Controller.tsx
mage_ai/frontend/components/FileEditor/Header/index.tsx
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/FileTabsScroller/index.style.tsx
mage_ai/frontend/components/FileTabsScroller/index.tsx
mage_ai/frontend/components/FileVersions/index.tsx
mage_ai/frontend/components/Files/index.style.tsx
mage_ai/frontend/components/Files/index.tsx
mage_ai/frontend/components/Files/useFileComponents.tsx
mage_ai/frontend/components/Files/utils.ts
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.style.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/FileTabs/Tab.tsx
mage_ai/frontend/components/PipelineDetail/FileTabs/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/components/VersionControl/index.tsx
mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx
mage_ai/frontend/pages/manage/files/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

Refactor file components to be used anywhere without repeating yourself and improved the UI/UX.
cc:

[td] Re-use file browser and editor in notebook

---

mage_ai/api/policies/ProjectPolicy.py
mage_ai/api/presenters/ProjectPresenter.py
mage_ai/api/resources/ProjectResource.py
mage_ai/data_preparation/models/project/__init__.py
mage_ai/frontend/components/platform/Settings/index.tsx
mage_ai/frontend/components/settings/Dashboard/constants.tsx
mage_ai/frontend/components/settings/Dashboard/index.tsx
mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
mage_ai/frontend/interfaces/PlatformType.ts
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/frontend/pages/settings/platform/preferences.tsx
mage_ai/frontend/pages/settings/platform/settings.tsx
mage_ai/frontend/utils/models/customDesign/useCustomDesign.ts
mage_ai/orchestration/db/models/schedules_project_platform.py
mage_ai/settings/platform/__init__.py
mage_ai/tests/data_preparation/models/test_project.py

Configure project platform preferences and settings.
cc:

[td] Configure root project preferences and settings

---

mage_ai/api/policies/GlobalHookPolicy.py
mage_ai/api/resources/GlobalHookResource.py
mage_ai/data_preparation/models/global_hooks/models.py
mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
mage_ai/frontend/components/FileBrowser/Folder/index.tsx
mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
mage_ai/frontend/components/GlobalHooks/GlobalHookDetailPage.tsx
mage_ai/frontend/components/GlobalHooks/GlobalHooksList/index.tsx
mage_ai/frontend/components/GlobalHooks/GlobalHooksPage.tsx
mage_ai/frontend/pages/global-hooks/[...slug].tsx
mage_ai/frontend/pages/global-hooks/index.tsx
mage_ai/frontend/pages/platform/global-hooks/[...slug].tsx
mage_ai/frontend/pages/platform/global-hooks/index.tsx

Configure global hooks for the root project.
cc:

[td] Global hooks for platform

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/components/FileBrowser/Folder/index.tsx
mage_ai/frontend/components/FileBrowser/NewFile/index.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileSelectorPopup/index.tsx
mage_ai/frontend/components/Files/useFileComponents.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/Sidekick/constants.ts
mage_ai/frontend/pages/manage/files/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

Fix several bugs related to new file browser.
cc:

[td] File browser bug bash

---

mage_ai/frontend/components/FileBrowser/Folder/index.tsx

[td] Remove logs

---

test_branch.Dockerfile

Dockerfile to build test branch

[td] Update test branch Dockerfile

---

mage_ai/cache/dbt/cache.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/block_sql.py

Issues when trying to delete a file that is a block from the file browser.
cc:

[td] Fix bug when deleting block from file browser

---

mage_ai/settings/platform/__init__.py
mage_ai/settings/platform/utils.py

Creating a pipeline schedule with multiple projects doesn’t fetch the correct repo path.

[td] Fix pipeline schedule creation and repo name

---

mage_ai/api/policies/GitFilePolicy.py
mage_ai/api/presenters/GitBranchPresenter.py
mage_ai/api/resources/GitBranchResource.py
mage_ai/api/resources/GitFileResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/Dashboard/index.style.tsx
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileEditor/Controller.tsx
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/Files/useFileComponents.tsx
mage_ai/frontend/components/MultiColumnController/index.style.tsx
mage_ai/frontend/components/MultiColumnController/index.tsx
mage_ai/frontend/components/VersionControl/constants.ts
mage_ai/frontend/components/VersionControl/index.tsx
mage_ai/frontend/components/VersionControl/utils.ts
mage_ai/frontend/components/shared/StyledScrollbarContainer/index.tsx
mage_ai/frontend/interfaces/FileType.ts
mage_ai/frontend/interfaces/GitBranchType.ts
mage_ai/frontend/oracle/components/ClickOutside/index.tsx
mage_ai/frontend/styles/globals.css

[td] Bug fixes and minor improvements on version control app

---

mage_ai/version_control/models.py

[td] Add models for version control

---

mage_ai/api/policies/VersionControlBranchPolicy.py
mage_ai/api/policies/VersionControlFilePolicy.py
mage_ai/api/policies/VersionControlProjectPolicy.py
mage_ai/api/policies/VersionControlRemotePolicy.py
mage_ai/api/presenters/VersionControlBranchPresenter.py
mage_ai/api/presenters/VersionControlFilePresenter.py
mage_ai/api/presenters/VersionControlProjectPresenter.py
mage_ai/api/presenters/VersionControlRemotePresenter.py
mage_ai/api/resources/VersionControlBranchResource.py
mage_ai/api/resources/VersionControlFileResource.py
mage_ai/api/resources/VersionControlProjectResource.py
mage_ai/api/resources/VersionControlRemoteResource.py
mage_ai/authentication/permissions/constants.py
mage_ai/version_control/models.py

Add version control APIs for granular git commands that will be used in the command center and also in multi-git repo management.
cc:

[td] Add API for projects

---

mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/orchestration/pipeline_scheduler_project_platform.py
mage_integrations/mage_integrations/utils/parsers.py

Fix syncing MySQL TIME type.
The TIME column type from MySQL wasn't serialized correctly. This PR fixes it.
cc:

[xy] Fix syncing MySQL TIME type

---

mage_ai/data_preparation/models/block/dbt/block_sql.py
mage_ai/frontend/components/Dashboard/index.tsx

Can’t resize dashboard on pipeline detail.
cc:

[td] Fix dashboard resizing

---

mage_ai/data_preparation/models/block/r/__init__.py

Fix escaping quotes for dictionary variaable in r block.
Close: https://github.com/mage-ai/mage-ai/issues/4171
The value is serialized correctly in global_vars
cc:

[xy] Fix escaping quotes in R block.

---

mage_integrations/mage_integrations/sources/google_ads/tap_google_ads/streams.py

Upgraded Google ads version from 14 to 15
Tested on a local mage instance using Google Ads Source -> PostgreSQL destination
cc:

Upgraded Google ads version from 14 to 15

---

mage_integrations/mage_integrations/sources/mssql/__init__.py

…eline.
Wrap mssql table name with double quotes in data integration pipeline.
Close: https://github.com/mage-ai/mage-ai/issues/4286
cc:

[xy] Wrap mssql table name with double quotes in data integration pipeline

---

docs/development/variables/referencing-variables.mdx

Simple PR to fix some broken variables links

[mp] Broken Links

---

.github/workflows/publish_docker_image.yml
Dockerfile

Allow building image with feature branch
Enter the input in "feature branch" to build image with feature branch.
cc:

[xy] Allow building image with feature branch

---

.circleci/config.yml

Allow export frontend circleci job to be run on alpha branch in addition to master
cc:

[dy] Update export frontend to be able to be run on alpha branch

---

mage_ai/api/resources/BlockResource.py
mage_ai/cache/block_action_object/__init__.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/io/base.py
mage_ai/io/bigquery.py
mage_ai/io/clickhouse.py
mage_ai/io/druid.py
mage_ai/io/pinot.py
mage_ai/io/snowflake.py
mage_ai/io/spark.py
mage_ai/io/sql.py

Execute any command without mage preprocessing the command.
https://github.com/mage-ai/mage-ai/assets/1066980/86f37e44-2252-46b0-829c-e7ab89b3b7c2
cc:

[td] Add execute raw SQL without preprocessing to all loaders

---

docs/integrations/databases/BigQuery.mdx
mage_integrations/mage_integrations/destinations/bigquery/README.md
mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/sources/bigquery/README.md

* Add BigQuery permissions to docs.
* Escape BigQuery project name with backtick in the queries
cc:

[xy] Add BigQuery permissions to docs.

---

mage_ai/api/resources/SearchResultResource.py
mage_ai/command_center/blocks/utils.py
mage_ai/command_center/pipelines/factory.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/TripleLayout/useTripleLayout.ts
mage_ai/frontend/oracle/elements/Link/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
mage_ai/frontend/storage/localStorage.ts
mage_ai/frontend/storage/serverTime.ts
mage_ai/frontend/utils/hooks/keyboardShortcuts/useGlobalKeyboardShortcuts.tsx
mage_ai/frontend/utils/models/blockRun.ts
mage_ai/services/search/block_action_objects.py

- Refactor triple layout props to hook
- Improve runs detail page
- Fix buggy editor focusing

[td] Improve UI in several areas

---

mage_ai/cluster_manager/kubernetes/workload_manager.py

Update default image when creating workspace.
cc:

[dy] Use current pod image as the default

---

mage_ai/data_preparation/git/__init__.py

Update how git sync handles submodules. The previous method would get a "bad config" error in certain cases.
cc:

[dy] Fix git submodule sync

---

mage_ai/frontend/components/shared/Header/index.tsx

- Each page was sending an `undefined` 404 request, so this PR removes it.
- Navigated various pages in the app and confirmed no `undefined` requests. Example below.
BEFORE (`undefined` requests in network tab):
AFTER (No `undefined` requests in network tab):
cc:

[jk] Remove undefined request

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx

- Fixes the right panel peaking out
cc:

[td] Fix triple layout after width

---

mage_ai/api/policies/CustomTemplatePolicy.py
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/Triggers/Table.tsx

- Can’t reduce dynamic + dynamic child blocks that have custom upstream blocks

[td] Fix reduce output bug

---

mage_ai/data_preparation/models/block/__init__.py

Fix cannot unpack non-iterable NoneType object
cc:

[xy] Fix cannot unpack non-iterable NoneType object

---

docker-compose.yml
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/block_sql.py
mage_ai/data_preparation/models/block/dbt/block_yaml.py
mage_ai/data_preparation/models/block/platform/mixins.py
mage_ai/frontend/components/CodeBlockV2/Output/index.tsx
mage_ai/frontend/components/FileEditor/utils.ts
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- File editor jumping around
- Renaming blocks

[td] Add small fixes

---

mage_ai/data_preparation/models/block/dbt/block_yaml.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlockV2/dbt/Configuration/index.tsx
mage_ai/frontend/components/CodeBlockV2/dbt/useCodeBlockProps.tsx
mage_ai/frontend/oracle/elements/Circle.tsx
mage_ai/io/bigquery.py

- Manually enter in everything

[td] Add fields to dbt code block 2.0 for manual entry

---

mage_ai/data_preparation/models/block/dbt/block_yaml.py

If users have single project setup, look in the `dbt` folder.

[td] If project can’t be found, look directly in the dbt folder

---

mage_ai/server/constants.py
setup.py

* https://github.com/mage-ai/mage-ai/pull/4249
* https://github.com/mage-ai/mage-ai/pull/4255
* https://github.com/mage-ai/mage-ai/pull/4263
* https://github.com/mage-ai/mage-ai/pull/4264
* https://github.com/mage-ai/mage-ai/pull/4254
* https://github.com/mage-ai/mage-ai/pull/4267
* https://github.com/mage-ai/mage-ai/pull/4268
* https://github.com/mage-ai/mage-ai/pull/4270
* https://github.com/mage-ai/mage-ai/pull/4256
* https://github.com/mage-ai/mage-ai/pull/4271
* https://github.com/mage-ai/mage-ai/pull/4272
* https://github.com/mage-ai/mage-ai/pull/4275
* https://github.com/mage-ai/mage-ai/pull/4277
* https://github.com/mage-ai/mage-ai/pull/4262
* https://github.com/mage-ai/mage-ai/pull/4278
* https://github.com/mage-ai/mage-ai/pull/4282
* https://github.com/mage-ai/mage-ai/pull/4283 …

[xy] Bump version to 0.9.59.

---

docs/getting-started/file-versions.mdx

[jk] Update file versioning doc

---

mage_ai/cache/block.py

- Fixed bugs related to block cache and shared pipelines displayed for blocks in the Pipeline Editor.
- Tested locally to make sure "Shared pipelines" were being displayed properly in block settings and block cache was getting updated correctly when removing or adding a block to a pipeline.
cc:

[jk] Fix caching issues with block cache and shared pipelines

---

docs/mint.json
docs/streaming/destinations/google-cloud-storage.mdx
mage_ai/data_preparation/templates/data_exporters/streaming/google_cloud_storage.yaml
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/streaming/sinks/amazon_s3.py
mage_ai/streaming/sinks/base_object_storage.py
mage_ai/streaming/sinks/google_cloud_storage.py
mage_ai/streaming/sinks/sink_factory.py
mage_ai/tests/streaming/sinks/test_google_cloud_storage.py

Add google cloud storage sink to streaming pipeline.
cc:

[xy] Add google cloud storage sink to streaming pipeline.

---

docs/production/data-sync/github.mdx
mage_ai/api/resources/OauthResource.py

Add docs for setting up bitbucket authentication.
cc:

[dy] Add bitbucket docs

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/tests/data_preparation/executors/test_block_executor.py

Callbacks for dynamic child blocks weren’t getting the correct input data.

[td] Fix callbacks input data from dynamic child blocks

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dynamic/utils.py
mage_ai/data_preparation/models/block/extension/utils.py
mage_ai/data_preparation/models/block/utils.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/shared/parsers.py

- Dynamic child blocks with no other upstream blocks weren’t fetching their input data.
- Tests functions in dynamic child blocks in the notebook will always fail because it also wasn’t fetching the data properly
https://github.com/mage-ai/mage-ai/assets/1066980/9d3f0eff-84f8-44e6-9420-a9eaab579151
cc:

[td] Fix dynamic child block getting input data

---

mage_ai/services/search/block_action_objects.py

[td] Fix block search

---

mage_ai/frontend/components/ApplicationManager/Header/index.tsx
mage_ai/frontend/components/ApplicationManager/index.style.tsx
mage_ai/frontend/components/ApplicationManager/useApplicationManager.tsx
mage_ai/frontend/components/CommandCenter/index.style.tsx
mage_ai/frontend/components/FileEditor/Header/index.tsx
mage_ai/frontend/components/PipelineDetail/StatusFooter/index.tsx
mage_ai/frontend/components/VersionControlFileDiffs/index.tsx
mage_ai/frontend/interfaces/ElementType.ts
mage_ai/frontend/storage/ApplicationManager/cache.ts
mage_ai/frontend/storage/ApplicationManager/constants.ts
mage_ai/frontend/utils/elements.ts
mage_ai/frontend/utils/hooks/keyboardShortcuts/utils.ts
mage_ai/frontend/utils/string.ts
mage_ai/frontend/utils/useDraggableElement.ts
mage_ai/frontend/utils/useResizeElement.ts

https://github.com/mage-ai/mage-ai/assets/1066980/8e20c1c5-691b-475b-8ff9-ca5a15975096

[td] Upgrade app layout behavior

---

mage_ai/data_preparation/preferences.py
mage_ai/server/server.py

Call `.lower()` on the `auth_type` value since we expect the value to be in lowercase.
cc:

[dy] Lowercase auth_type enum

---

mage_ai/cluster_manager/constants.py
mage_ai/cluster_manager/gcp/cloud_run_service_manager.py
mage_ai/cluster_manager/workspace/cloud_run.py

Resolve initialization error when creating cloud run service.
cc:

[dy] Update cloud run workspace

---

docs/design/data-pipeline-management.mdx
docs/development/troubleshooting.mdx

Update doc about caching block output in memory and troubleshooting cloud server restarts.
cc:

[xy] Update doc about caching block output in memory and troubleshooting

---

mage_ai/frontend/components/Terminal/useTerminal/index.tsx

Fix client side exception on terminal page.
cc:

[dy] Fix terminal

---

docs/guides/blocks/sql-blocks.mdx

- Disable SQL preprocessing
- SQL variable interpolation

[td] SQL docs

---

mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/shared/custom_logger.py

[td] custom design docs

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/orchestration/db/models/schedules.py

This fixes bugs with dynamic child blocks not running the conditional properly in the notebook and in the pipeline run.
cc:

[td] Fix dynamic block conditionals in runs and in notebook

---

docs/contributing/development-environment.mdx

Small update to contributor guide

Fix incorrect port

---

mage_ai/data_preparation/executors/pipeline_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dynamic/child.py
mage_ai/data_preparation/models/block/dynamic/utils.py
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/PipelineDetail/utils.ts
mage_ai/frontend/utils/array.ts
mage_ai/presenters/blocks/graph.py
mage_ai/server/utils/output_display.py
mage_ai/tests/data_preparation/models/block/dynamic/test_dynamic_helpers.py

- Fix running tests in notebook when having reduce output
- Fix running tests in pipeline runs when having reduce output
cc:

[td] Fix reduce output block tests

---

mage_ai/server/constants.py
setup.py

Management
Editor
Orchestration
Others
N/A
cc:

[xy] Bump up the version to 0.9.60

---

mage_ai/api/resources/SessionResource.py
mage_ai/authentication/ldap.py

User was getting a stacktrace instead of a formatted error message when the LDAP user was invalid. This should fix the error, and return a human readable message when the user is invalid.
cc:

[dy] Fix LDAP unpacking

---

mage_ai/data_preparation/models/block/dynamic/variables.py
mage_ai/frontend/components/TripleLayout/useTripleLayout.ts

- Fix reduce output from dynamic squared upstream
- Fix triple layout when width prop is present
cc:

[td] Fix reduce output and triple layout saving

---

docs/developer-ux/avatar.mdx
docs/developer-ux/file-browser.mdx
docs/developer-ux/overview.mdx
docs/mint.json
mage_ai/data_preparation/git/api.py
mage_ai/frontend/components/FileVersions/index.tsx
mage_ai/frontend/components/Files/useFileComponents.tsx
mage_ai/frontend/components/users/UserDetail.tsx
mage_ai/frontend/pages/settings/account/profile.tsx
mage_ai/frontend/pages/settings/workspace/users/[...slug].tsx

- File browser was adding odd path
- Enhance file versions to refresh
- Fix git push bug with wrong kwargs

[td] Fix filebrowser bug and git push bug

---

mage_ai/data_preparation/models/block/__init__.py

- Instead of using isoformat, use encode complex encoder
cc:

[td] Fix serializing list and dict when formatting output

---

mage_ai/services/k8s/config.py
mage_ai/services/k8s/job_manager.py
mage_ai/shared/hash.py
mage_ai/tests/services/k8s/test_job_manager.py
mage_ai/tests/shared/test_hash.py

Support affinity and tolerations in k8s_executor_config.
Close: https://github.com/mage-ai/mage-ai/issues/4394
Checked the pod spec. It matches the k8s executor config.
cc:

[xy] Support affinity and tolerations in k8s_executor_config.

---

mage_ai/data_preparation/models/block/dynamic/variables.py

[td] Prevent index out of bounds

---

mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/io/bigquery.py
requirements.txt
setup.py

Fixes https://github.com/mage-ai/mage-ai/issues/4423
https://github.com/mage-ai/mage-ai/assets/1066980/8212c8ae-b771-4650-a626-ccaca4b1068f
https://github.com/mage-ai/mage-ai/assets/1066980/9b70aa4d-7709-4910-b973-13bcea63b9d6
https://github.com/mage-ai/mage-ai/assets/1066980/da77a791-e905-4891-9c70-9a90bbcc0695
cc:

[td] Fix database missing and serializing QueryJob

---

mage_integrations/requirements.txt
requirements.txt

Bump up dependency versions to resolve critical and high security vulnerabilities.
cc:

[xy] Bump up dependency versions to resolve vulnerabilities.

---

mage_integrations/mage_integrations/destinations/bigquery/README.md
mage_integrations/mage_integrations/destinations/snowflake/README.md
mage_integrations/mage_integrations/sources/chargebee/README.md

Update docs for data integration pipelines
cc:

[xy] Update docs for data integration pipelines

---

mage_ai/api/resources/BlockResource.py
mage_ai/command_center/constants.py
mage_ai/data_preparation/models/block/global_data_product/__init__.py
mage_ai/data_preparation/variable_manager.py
mage_ai/orchestration/triggers/global_data_product.py
mage_ai/tests/data_preparation/models/block/test_global_data_product.py
mage_ai/tests/orchestration/triggers/test_global_data_product.py

- Fixed loop
- Fixed potential double run

[td] Fix a few global data product bugs

---

.github/workflows/build_and_test.yml
Dockerfile
dev.Dockerfile
mage_ai/api/resources/DataProviderResource.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/content.py
mage_ai/data_preparation/models/block/dynamic/child.py
mage_ai/data_preparation/models/block/dynamic/utils.py
mage_ai/data_preparation/models/block/dynamic/variables.py
mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/presenters/blocks/graph.py
mage_ai/shared/memory.py
mage_ai/tests/shared/test_files.py
requirements.txt

[td] Fix dynamic blocks OOM round 2

---

mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/io/bigquery.py
requirements.txt

Help users fill in full name for BigQuery tables. If filled in properly, the 404 error doesn’t occur.
https://github.com/mage-ai/mage-ai/assets/1066980/5ba8f3bb-4d4b-4a90-a573-d322143553a5

[td] Improve bigquery name parsing to help fill in full name

---

mage_ai/api/monitors/BaseMonitor.py
mage_ai/api/operations/base.py
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/dynamic/variables.py
mage_ai/server/api/base.py
mage_ai/usage_statistics/constants.py
mage_ai/usage_statistics/logger.py

- Log API errors
- Log application errors
- Log block executor errors

[td] Add error logging

---

mage_integrations/mage_integrations/destinations/bigquery/__init__.py
mage_integrations/mage_integrations/sources/chargebee/__init__.py
mage_integrations/mage_integrations/sources/chargebee/streams/base.py
mage_integrations/mage_integrations/sources/chargebee/streams/comments.py
mage_integrations/mage_integrations/sources/chargebee/streams/coupons.py
mage_integrations/mage_integrations/sources/chargebee/streams/events.py
mage_integrations/mage_integrations/sources/chargebee/streams/subscriptions.py

Fix incremental sync in chargebee source
* Use correct bookmark column
* Add more logging
* Fix clean column name in BigQuery destination
cc:

[xy] Fix incremental sync in chargebee source

---

docs/platform/projects/management.mdx

`# multiverse_project/settings.ymal` is not correct

Fix incorrect spelling

---

mage_ai/data_preparation/models/block/dynamic/child.py

If output data is None, don’t try to count it and just wait.

[td] Don’t count values if is None

---

docs/guides/tips-and-tricks.mdx

Add new tips and tricks videos to docs (Backfills & API Triggers)

[mp] Add new tips & tricks to docs

---

docs/getting-started/setup.mdx

https://mageai.slack.com/archives/C03HTTWFEKE/p1706168410110529

[mp] update windows command for quickstart

---

mage_ai/api/policies/CommandCenterItemPolicy.py

[td] Fix policy issue updating settings

---

mage_ai/frontend/components/CommandCenter/index.tsx
mage_ai/presenters/blocks/graph.py

Fix empty keyboard shortcut configurations.

[td] Fix keyboard shortcuts when its empty array

---

mage_ai/data_preparation/git/__init__.py

Run `git submodules sync -- <submodule>` before updating the submodule.
cc:

[dy] Run submodule sync

---

mage_integrations/mage_integrations/destinations/snowflake/__init__.py

Fixed a issue where empty dictionary fields in a pandas dataframe caused insertion issues in Snowflake destination.
When using Snowflake `write_pandas` method, insertion can fail due to pyarrow engine not being able to define what is the current type inside a empty dictionary
Example:
To solve this, this PR adds a simple check method to verify wether a column value is a empty dict
Tested using a Stripe account and Snowflake destination
cc:

Fixing snowflake write_pandas issue

---

docs/integrations/databases/Weaviate.mdx
docs/mint.json
mage_ai/data_preparation/templates/constants.py
mage_ai/data_preparation/templates/data_exporters/weaviate.py
mage_ai/data_preparation/templates/data_loaders/weaviate.py
mage_ai/data_preparation/templates/repo/io_config.yaml
mage_ai/io/base.py
mage_ai/io/config.py
mage_ai/io/weaviate.py

Weaviate is a vector database: https://weaviate.io/developers/weaviate/quickstart#step-3-connect-to-weaviate
This PR is to add it into Mage with data loader and exprter.
Mage UI:
Loader template and loader result:
Export template and result:
cc:
@dy46

[xh] Weaviate integration with loader and exporter

---

docs/integrations/databases/Algolia.mdx
docs/mint.json
mage_ai/data_preparation/templates/constants.py
mage_ai/data_preparation/templates/data_exporters/algolia.py
mage_ai/data_preparation/templates/data_loaders/algolia.py
mage_ai/data_preparation/templates/repo/io_config.yaml
mage_ai/io/algolia.py
mage_ai/io/base.py
mage_ai/io/config.py

Algolia is a hosted search engine can be used for context searching and vector database: https://www.algolia.com/doc/. It is requested by customer to support it.
Mage UI:
Loader:
Exporter:
- [] I have added unit tests that prove my fix is effective or that my feature works
cc:
@dy46

[xh]Alogia integration

---

docs/streaming/sources/kafka.mdx
mage_ai/streaming/sources/kafka.py

Fix kafka type and doc about offset reset
cc:

[xy] Fix kafka type and doc.

---

mage_ai/data_preparation/decorators.py
mage_ai/data_preparation/models/block/data_integration/mixins.py
mage_ai/data_preparation/models/block/data_integration/utils.py
mage_ai/data_preparation/models/block/dynamic/variables.py
mage_ai/data_preparation/templates/data_integrations/destinations/base.py
mage_ai/data_preparation/templates/data_integrations/sources/base.py
mage_ai/io/postgres.py
mage_ai/io/trino.py
mage_ai/presenters/blocks/graph.py
mage_ai/server/utils/output_display.py

- Add optional query decorators for Python data integration blocks
- Fix some IO bugs
- Fix some UI bugs for dynamic blocks tree

[td] Add query decorator for data integration blocks

---

mage_ai/server/constants.py
setup.py

Management
Editor
Orchestration
Others
N/A
cc:

[xy] Bump up version to 0.9.61

---

mage_ai/orchestration/job_manager.py
mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/orchestration/queue/process_queue.py
mage_ai/orchestration/queue/queue.py
mage_ai/tests/orchestration/queue/test_process_queue.py
mage_ai/tests/orchestration/test_job_manager.py

* Check whether process is alive in scheduler.
* Log process crash in scheduler ProcessQueue
* Log pipeline run cancellation message with tags correctly
This PR doesn't make corresponding change in the project platform scheduler since we're going to combine them very soon.
Create a backfill for a pipeline that loads large data and forces the OOM issue.
cc:

[xy] Scheduler improvements

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/executors/pipeline_executor.py

Fix errors when logging errors in pipeline executor’s block executor.

[td] Fix error logging in pipeline executor

---

mage_ai/frontend/components/Applications/ArcaneLibrary/index.tsx
mage_ai/frontend/components/Files/useFileComponents.tsx
mage_ai/frontend/components/TripleLayout/useTripleLayout.ts

Clicking show file version wasn’t showing the right panel.

[td] When clicking show file versions in arcane library, show right panel

---

mage_ai/frontend/components/charts/BarChartHorizontal.tsx
mage_ai/io/bigquery.py

Don’t error if it doesn’t work.

[td] Catch BigQuery if it fails to fix table names

---

mage_ai/frontend/components/PipelineDetailPage/utils.ts

Always show "edit pipeline" button in vertical navigation. If the user is a viewer, show 'View pipeline' instead.
cc:

[dy] Always show edit pipeline button

---

mage_ai/settings/platform/__init__.py
mage_ai/settings/platform/constants.py
mage_ai/tests/base_test.py
mage_ai/tests/settings/test_platform.py

Fix app slowness due to project platform check.
The `project_platform_activated` is called in a lot of places. Repeatedly checking the os path causes the slowdown of the APP.
Thus, update it to set the flag at the time of server start.
Before fix
After fix
cc:

[xy] Fix app slowness due to project platform check.

---

mage_ai/io/postgres.py

[td] Revert change to PG IO

---

mage_ai/io/redshift.py

Fix io redshift.
* Set default value for overwrite_types to None
* Remove unnecessary print
cc:

[xy] Fix io redshift.

---

mage_ai/settings/platform/constants.py
mage_ai/settings/repo.py
mage_ai/tests/base_test.py

Fix multi project flag. Set the flag after setting repo path so that it gets the correct value for repo path.
cc:

[xy] Fix multi project flag.

---

mage_ai/cluster_manager/config.py
mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/frontend/components/workspaces/ConfigureWorkspace/constants.ts
mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
mage_ai/frontend/components/workspaces/Detail/index.tsx
mage_ai/frontend/components/workspaces/constants.ts

Add PVC retention policy configuration field.
cc:

[dy] Add PVC retention policy

---

docs/mint.json
docs/production/custom-docker-image/non-root-user.mdx

Add doc for running Mage as non root users.
cc:

[xy] Add doc for running Mage as non root users.

---

docs/data-integrations/destinations/overview.mdx

Update doc about maximum batch size.
cc:

[xy] Update doc about maximum batch size.

---

mage_integrations/mage_integrations/destinations/bigquery/__init__.py

Fix Bigquery clean column name in data integration destination
cc:

[xy] Fix Bigquery clean column name.

---

mage_ai/tests/api/endpoints/test_custom_designs.py
mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py

Convert datetime type column for s3 data integration destination.
cc:

[xy] Convert datetime type for s3 data integration destination.

---

mage_ai/server/constants.py
setup.py

Management
Editor
Orchestration
Others
N/A
cc:

[xy] Bump version to 0.9.62.

---

mage_ai/api/resources/BlockResource.py
mage_ai/data_preparation/models/widget/utils.py
mage_ai/data_preparation/variable_manager.py
mage_ai/frontend/pages/overview/index.tsx

[td] Fix some minor bugs

---

mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/io/bigquery.py

fix 
BadRequest: 400 Syntax error: Expected keyword ALL or keyword DISTINCT but got keyword SELECT at [3:140]

[td] Remove table name helper

---

mage_integrations/mage_integrations/connections/mssql/__init__.py

Implemented the code from here pyodbc wiki:
https://github.com/mkleehammer/pyodbc/wiki/Using-an-Output-Converter-function
**Note:** Similar patch is probably needed in mage_ai/io/mssql.py. I had not run into that yet, and had no time to fix that right now. Likely I will run into it soon, though.
Tested in local pipeline w/ mssql source.
Against:
- local postrgesql - ended up as timestamp_tz
- local mssql, ended up as text , this could be fixed by adding support for timestamp_tz in MSSQL as DATETIMEOFFSET
cc:

MSSQL data integration source - add support for DATETIMEOFFSET type

---

mage_integrations/mage_integrations/destinations/redshift/README.md

Update doc for Redshift skip_schema_creation.
N/A
cc:

[xy] Update doc for Redshift skip_schema_creation.

---

docs/production/authentication/microsoft.mdx
docs/production/developing-in-the-cloud/workspaces/kubernetes.mdx

Add documentation for some recent changes.
cc:

[dy] Add docs

---

docs/streaming/sources/kafka.mdx

Update Kafka doc about SASL authentication.
cc:

[xy] Update Kafka doc about SASL authentication.

---

mage_ai/io/mssql.py

Use sqlalchemy.engine.URL to create the connection_url to handle special characters in the password.
cc:

[dy] Update connection url

---

docs/getting-started/runtime-variable.mdx

Add a community solution to the problem of envronment-specific runtime variables in pipelines.
From: https://mageai.slack.com/archives/C03GGQTS8CT/p1706040699648159

pipeline env vars

---

mage_ai/io/config.py
mage_ai/io/duckdb.py
requirements.txt
setup.py

Support MotherDuck.
* Upgrade the duckdb library version from 0.9.1 to 0.9.2
* Update the code to support connecting to MotherDuck with token
cc:

[xy] Support MotherDuck.

---

mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Fix how the stale pipeline message modal is displayed after removing the pipeline's `updated_at` property, since it was temporarily disabled in this [PR](https://github.com/mage-ai/mage-ai/pull/4525).
- We use the [Broadcast Channel API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) in order to detect when multiple tabs of the same pipeline are open. If there are multiple tabs of a pipeline open, we display a warning on any already-open tabs so users are aware that saving changes could overwrite changes from a different tab.
- Tested on Chrome, Safari, and Firefox.

[jk] Update how the stale pipeline message modal is displayed

---

mage_ai/server/constants.py
setup.py

* [xy] Support MotherDuck. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/4533
* [xh] Add Oracle dockerfile to support thick mode by @matrixstone in https://github.com/mage-ai/mage-ai/pull/4421
* [rp] Import functionality for pipeline zips by @johnson-mage in https://github.com/mage-ai/mage-ai/pull/4453
* [jk] Prevent add block menu from disappearing by @johnson-mage in https://github.com/mage-ai/mage-ai/pull/4502
* [td] Fix some minor bugs by @tommydangerous in https://github.com/mage-ai/mage-ai/pull/4505
* [td] Remove table name helper by @tommydangerous in https://github.com/mage-ai/mage-ai/pull/4506
* Fix alter table column names cleaning (postgresql integration exporter) by @arnetkachev in https://github.com/mage-ai/mage-ai/pull/4493
* Fixed Oauth connection on …

[xy] Bump version to 0.9.63

---

docs/guides/pipelines/importing-pipelines.mdx
docs/mint.json

[jk] Add docs for importing pipelines

---

mage_integrations/mage_integrations/connections/google_sheets/__init__.py
mage_integrations/mage_integrations/sources/base.py
mage_integrations/mage_integrations/sources/google_sheets/__init__.py

Improve google sheets source.
* Add backoff retry for the google sheet API calls to mitigate the TooManyRequests error
* Update the logging to use the correct logger
* Only fetch sheet metadata for filtered streams instead of all sheets.
cc:

[xy] Improve google sheets source.

---

docs/_snippets/configure-git-sync.mdx
docs/development/git/configure.mdx
mage_ai/api/resources/GitBranchResource.py
mage_ai/api/resources/SyncResource.py
mage_ai/cli/main.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/sync/git_sync.py
mage_ai/frontend/components/VersionControl/Remote/index.tsx
mage_ai/frontend/pages/settings/workspace/sync-data.tsx
mage_ai/orchestration/utils/git.py
mage_ai/server/server.py

Codecommit requires some additional ssh config to be able to connect to a repository. This PR adds the additional config file if the repository host is codecommit.
cc:

[dy] Add support for AWS codecommit

---

mage_ai/api/presenters/IntegrationSourceStreamPresenter.py
mage_ai/frontend/components/BlockSettings/index.tsx
mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx
mage_integrations/mage_integrations/sources/sftp/tap_sftp/discover.py
mage_integrations/mage_integrations/sources/sftp/tap_sftp/tap.py

The block settings tab was causing the frontend to crash when the variable value was an object, so add `toString`. Also, update the behavior of the SFTP tap discover slightly.
cc:

[dy] Fix frontend crashing issues

---

mage_ai/data_preparation/logging/logger.py
mage_ai/data_preparation/models/block/dbt/constants.py
mage_ai/data_preparation/models/block/dbt/dbt_cli.py
mage_ai/frontend/components/Logs/Table/index.tsx

Update DBT logging to include warn and error logs. They were not getting logged, so some important logs were missing when running DBT blocks.
cc:

[dy] Fix DBT logging

---

mage_integrations/mage_integrations/connections/sql/base.py
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/tests/destinations/snowflake/test_snowflake.py
requirements.txt
setup.py

Create TEMP Snowflake table in data integration destination.
Update the Snowflake sql commands to use one connection so that TEMP table can be used.
Close: https://github.com/mage-ai/mage-ai/issues/4537
This PR also restricts version of `langchain_community` to fix test https://github.com/mage-ai/mage-ai/actions/runs/7895444881/job/21547813402
cc:

[xy] Create TEMP Snowflake table in data integration destination

---

docs/production/deploying-to-cloud/aws/setup.mdx
mage_ai/api/presenters/GitBranchPresenter.py
mage_ai/api/resources/GitBranchResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/frontend/components/VersionControl/Branches/index.tsx
mage_ai/frontend/pages/manage/index.tsx

* Improve UX when refreshing workspaces so that it is clear that the page is actually refreshing.
* Add ability to switch to remote branches.
cc:

[dy] Misc workspace/git improvements

---

mage_ai/server/server.py
mage_ai/tests/server/test_server.py

Fix how user authentication is initialized for subprojects.
cc:

[dy] Update user authentication for subprojects

---

mage_integrations/mage_integrations/sources/postgresql/__init__.py

Match postgres logical replication records with stream name.
Example Relation message:
Example Insert message:
cc:

[xy] Match postgres logical replication records with stream name.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.64
* [Feature] ✨ adding BACKEND support for OpenTelemetry (OTEL) by @mfreeman451 in https://github.com/mage-ai/mage-ai/pull/4476
* Added reserved words settings to PostgreSQL by @Luishfs in https://github.com/mage-ai/mage-ai/pull/4142
* [xy] Use utc time as the default time for monitor_stats. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/4554
* Fix Google Ads Catalog to Data Integration Block by @Luishfs in https://github.com/mage-ai/mage-ai/pull/4565
* [jk] Load custom design logo by @johnson-mage in https://github.com/mage-ai/mage-ai/pull/4574
* [dy] Adjust alembic logger initialization by @dy46 in https://github.com/mage-ai/mage-ai/pull/4552
* [dy] Add support for AWS codecommit by @dy46 in https://github.com/mage-ai/mage-ai/pull/4568
* [dy] Fix …

[xy] Bump version to 0.9.64

---

docs/production/authentication/oidc.mdx
docs/production/data-sync/github.mdx
mage_ai/authentication/providers/gitlab.py

Update docs for the following features
* Version control GitLab authentication 
* Sign in with OIDC
cc:

[dy] Update docs 2/16

---

mage_ai/server/server.py
mage_ai/shared/utils.py

Update the port check to use specified host.
The `localhost` name is not known in a container running on windows.
cc:

[xy] Update the port check to use specified host.

---

mage_ai/shared/utils.py

Set default host when checking port in case it's None
cc:

[xy] Set default host when checking port.

---

mage_ai/api/resources/SyncResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/git/utils.py
mage_ai/data_preparation/preferences.py
mage_ai/data_preparation/sync/git_sync.py

Consolidate duplicated git code from `git/utils.py` and `git/__init__.py`.
- Tested locally by running git operations
cc:

[dy] Refactor duplicate git code

---

mage_ai/frontend/components/ApplicationManager/useApplicationManager.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- Address issue reported in https://github.com/mage-ai/mage-ai/issues/4566 where there were issues opening/minimizing the Arcane Library and Portal Terminal windows when both apps were open.
Before (minimized windows from Command Center do not open):
After (minimized windows can open and re-minimize):

[jk] Fix unclickable minimized windows

---

docs/production/deploying-to-cloud/aws/setup.mdx

Update EKS docs with some workspace specific instructions.
cc:

[dy] Update EKS docs

---

mage_ai/io/mssql.py

Fixing support for timestamp w time zone aka datetimeoffset.
Implemented the code from here pyodbc wiki:
https://github.com/mkleehammer/pyodbc/wiki/Using-an-Output-Converter-function
Note: This has been implemented for integration pipelines in https://github.com/mage-ai/mage-ai/pull/4499
Tested in local pipeline w/ mssql source.
cc:

mage_ai/io MSSQL connection: add support for DATETIMEOFFSET

---

docs/production/authentication/microsoft.mdx

`ACTIVE_DIRECTORY_ROLE_MAPPING` -> `ACTIVE_DIRECTORY_ROLES_MAPPING`
docs fix
cc:

[dy] Fix typo in AD documentation

---

mage_ai/io/mssql.py

Description:
Hello mage team, while reading through the documents, i realised that the spelling for level was incorrect. would like to propose to change the spelling of the word from levl to level. Thank you!

Incorrect spelling for the word level in documentation

---

mage_ai/orchestration/db/__init__.py
mage_ai/orchestration/db/database_manager.py
mage_ai/shared/logger.py

Update the name of the alembic logger that is configured.
cc:

[dy] Fix unit test logging

---

docs/production/data-sync/github.mdx

Update link in GitLab docs.
cc:

[dy] Update docs link

---

requirements.txt

Bump up more versions to resolve vulnerabilities.
jupyter-server is not upgraded due to dependency issue
cc:

[xy] Bump up more versions to resolve vulnerabilities.

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.65
* Luthfir/telegram notification by @luthfir-rahman in https://github.com/mage-ai/mage-ai/pull/4632
* Luthfir/discord notification by @luthfir-rahman in https://github.com/mage-ai/mage-ai/pull/4590
* [xy] Support exporting to mysql with selected columns. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/4605
* [xy] Update the port check to use specified host. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/4606
* [xy] Set default host when checking port. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/4610
* [dy] Refactor duplicate git code by @dy46 in https://github.com/mage-ai/mage-ai/pull/4611
* [jk] Fix unclickable minimized windows by @johnson-mage in https://github.com/mage-ai/mage-ai/pull/4613
* [dy] Attempt to …

[xy] Bump version to 0.9.65

---

docs/contributing/frontend/testing.mdx
mage_ai/frontend/.gitignore
mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/frontend/playwright.config.ci.ts
mage_ai/frontend/playwright.config.ts
mage_ai/frontend/tests/base.ts
mage_ai/frontend/tests/pages.spec.ts
mage_ai/frontend/tests/pipelines.spec.ts
mage_ai/frontend/utils/testing/index.ts

This PR adds a test to make sure all pages from left navigation bar load without error.

[edw] e2e test: load pages no errors

---

mage_ai/server/utils/output_display.py

Try `.fillna('')` for every column and catch the exception if it fails. This should resolve the most critical issue for now.

[dy] Add try/except

---

mage_ai/data_preparation/models/block/dbt/block_sql.py

Add upstream_dbt_blocks method back to DBTBlockSQL.
Close: https://github.com/mage-ai/mage-ai/issues/4645
cc:

[xy] Add upstream_dbt_blocks method back to DBTBlockSQL.

---

mage_ai/frontend/api/utils/useDelayFetch.ts
mage_ai/frontend/components/PipelineInteractions/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

- The pipeline interactions weren't properly loading in the Pipeline Editor, so this PR fixes that.
- Also display errors when creating/updating a pipeline interaction and avoid editing an invalid interaction if a new interaction is created with the same uuid as an existing interaction.
Previously, the block interactions would not load at all:

[jk] Bugfix for pipeline interactions

---

mage_ai/api/resources/OauthResource.py
mage_ai/authentication/oauth/utils.py
mage_ai/tests/authentication/oauth/test_utils.py

Fix access token queries when a user is provided. Instead of adding a user id to the oauth client, I think it makes more sense to add the user id to the oauth access token. Also, added unit tests for the oauth util methods. 
cc:

[dy] Update access token user queries and add tests

---

docs/guides/community-examples.mdx

Added few new sources and links
cc:

[tc] Update community-examples.mdx

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/shared/io.py

Fix pipeline metadata encoding issue.
Close: https://github.com/mage-ai/mage-ai/issues/4716
cc:

[xy] Fix pipeline metadata encoding issue.

---

docs/mint.json
docs/orchestration/pipeline-runs/database-query.mdx
docs/orchestration/triggers/database-query.mdx

Add docs for trigger and pipeline run queries.
Close: https://github.com/mage-ai/mage-ai/issues/4677
cc:

[xy] Add docs for trigger and pipeline run queries.

---

mage_ai/authentication/providers/oidc.py
mage_ai/frontend/pages/oauth.tsx

Display error if the authorization request fails during the Oauth process.
cc:

[dy] Display error on oauth

---

mage_ai/server/server.py

Run status endpoint in scheduler so that user can check scheduler liveness easily.
When setting INSTANCE_TYPE=scheduler
cc:

[xy] Run status endpoint in scheduler.

---

mage_ai/frontend/pages/index.tsx

Reverts https://github.com/mage-ai/mage-ai/pull/4662

[dy] Fix sign in issue

---

mage_ai/server/constants.py
setup.py

* [jk] Delete backfills by @johnson-mage in https://github.com/mage-ai/mage-ai/pull/4726
* [dy] Support AzureDevOps using Entra ID/AD authentication by @dy46 in https://github.com/mage-ai/mage-ai/pull/4721
* [jk] Fix "filter is not a function" type error in schema props by @johnson-mage in https://github.com/mage-ai/mage-ai/pull/4686
* [xy] Fix list index out of range for dynamic blocks. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/4688
* [xy] Set default domain for salesforce source by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/4689
* [dy] Handle JSON reading errors for elasticsearch by @dy46 in https://github.com/mage-ai/mage-ai/pull/4696
* [dy] Add try/except by @dy46 in https://github.com/mage-ai/mage-ai/pull/4683
* [jk] Update backfill policy to …

[xy] Bump version to 0.9.66

---

docs/development/testing/unit-tests.mdx

Add additional documentation to the unit test section about mocking Mage IO classes.

[dy] Add documentation on mocking IO libraries in unit tests

---

mage_ai/data_preparation/git/api.py
mage_ai/data_preparation/git/clients/gitlab.py

One of the import statements for the GitLab client was not correct, and it was not throwing any exception for some reason. I fixed the import and added some error logging.
cc:

[dy] Fix GitLab auth issues

---

mage_ai/data_preparation/decorators.py
mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/data_preparation/templates/data_loaders/streaming/generic_python.py
mage_ai/data_preparation/templates/template.py
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/streaming/sources/base_python.py
mage_ai/streaming/sources/source_factory.py

Support custom python source in Streaming pipeline so that user can write their own streaming source.
Close: https://github.com/mage-ai/mage-ai/issues/4585
Choose the generic source and get the python block with code template
Code template for python source
```python
from mage_ai.streaming.sources.base_python import BasePythonSource
from typing import Callable
if 'streaming_source' not in globals():
from mage_ai.data_preparation.decorators import streaming_source
@streaming_source
class CustomSource(BasePythonSource):
def init_client(self):
"""
Implement the logic of initializing the client.
"""
def batch_read(self, handler: Callable):
"""
Batch read the messages from the source and use handler to process the messages.
"""
while True:
records = []
if len(records) > 0:
handler(records)
``` …

[xy] Support custom python source in Streaming pipeline

---

mage_ai/frontend/pages/index.tsx

Add sign in check to `pages/index.tsx` so that it doesn't redirect first.

[dy] Add sign in check to index.tsx

---

mage_ai/frontend/pages/index.tsx

Check status response instead of checking the cookie because there could be a delay in Mage actually setting the cookie.

[dy] Check status response for REQUIRE_USER_AUTHENTICATION

---

mage_ai/orchestration/job_manager.py

Fix the exception reported on windows
```
File "C:\Program Files\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
exitcode = _main(fd, parent_sentinel)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\multiprocessing\spawn.py", line 130, in _main
self = reduction.pickle.load(from_parent)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\SELECT COAP\mage-ai\mage-ai\mage_ai\server\websocket_server.py", line 17, in <module>
from mage_ai.api.resources.PipelineResource import PipelineResource
File "D:\SELECT COAP\mage-ai\mage-ai\mage_ai\api\resources\PipelineResource.py", line 19, in <module>
from mage_ai.api.resources.BlockResource import BlockResource
File "D:\SELECT COAP\mage-ai\mage-ai\mage_ai\api\resources\BlockResource.py", line 31, in <module>
from …
```

[xy] Catch job manager init error.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/components/PipelineDetail/AddonBlocks/AddonBlock.tsx
mage_ai/frontend/components/PipelineDetail/AddonBlocks/index.tsx
mage_ai/tests/data_preparation/models/test_block.py

Add parent block global vars to the add on block if they don't interfere with the existing add on block global vars.

[dy] Add all parent block variables to the add on block

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.67
* [xy] Support custom python source in Streaming pipeline by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/4763
* [xh] Oracle add thick mode support in standard pipeline by @matrixstone in https://github.com/mage-ai/mage-ai/pull/4701
* [jk] Add check to avoid rendering of invalid JSX element by @johnson-mage in https://github.com/mage-ai/mage-ai/pull/4755
* [dy] Fix GitLab auth issues by @dy46 in https://github.com/mage-ai/mage-ai/pull/4760
* [jk] Increase visibility of code block context menu by @johnson-mage in https://github.com/mage-ai/mage-ai/pull/4768
* [dy] Check status response for REQUIRE_USER_AUTHENTICATION by @dy46 in https://github.com/mage-ai/mage-ai/pull/4782
* [xy] Fix exporting dataframe to bigquery. by @wangxiaoyou1993 in …

[xy] Bump version to 0.9.67

---

mage_ai/settings/backends.py

The cache will throw an exception if it does not find a secret, so we need to catch the exception.
cc:

[dy] Put cache in try/except

---

mage_ai/frontend/components/DataIntegrationModal/Credentials/index.tsx
mage_ai/frontend/components/IntegrationPipeline/SourceConfig.tsx
mage_integrations/requirements.txt

Fix clickhouse destination error. Issue https://github.com/mage-ai/mage-ai/issues/4480
Also made a change to the data integration config fields so that you can delete the existing config in the field without it repopulating the field.
cc:

[dy] Fix clickhouse destination

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/services/spark/spark.py
mage_ai/settings/models/configuration_option.py
mage_ai/shared/files.py

* `/api/pipelines/[pipeline_uuid]/configuration_options?configuration_type=dbt&option_type=projects&resource_type=Block`
* Combine two directory traverse into one
* Skip hidden folder traverse
* Local testing: reduce time from 430ms to 160ms
* `/api/pipelines/[pipeline_uuid]?include_block_pipelines=true&includes_outputs=true`
* Not repeatedly read block cache.
* Local testing: reduce time from 580ms to 300ms
* More efficiently detect whether spark is enabled.
* Local testing: reduce time from 300ms to 200ms
cc:

[xy] Speed up backend requests.

---

mage_ai/api/resources/GitBranchResource.py

Update how we set the `config_overwrite` from the GitBranchResource. We should only set the `config_overwrite` if the user is using an oauth token.
cc:

[dy] Update config_overwrite

---

mage_ai/streaming/sources/mongodb.py

Fix mongodb source typo.
Close: https://github.com/mage-ai/mage-ai/issues/4831
cc:

[xy] Fix mongodb source typo.

---

mage_integrations/mage_integrations/destinations/snowflake/__init__.py
requirements.txt
setup.py

Create snowflake temp table like original table to that they use the same schema.
There could be column type mismatch if the original table is pre-created.
cc:

[xy] Create snowflake temp table like original table.

---

mage_integrations/mage_integrations/sources/oracledb/__init__.py

Issue reported: https://github.com/mage-ai/mage-ai/issues/4596, when customer uses a datetime type as bookmark. The trigger failed with error `ORA-00906: missing left parenthesis.`
I reproduce the issue and figured out the reason is limit_query construction problematic when where clause using datetype. In this PR, I fixed it by introducing dedicated `_build_comparison_statement` function to source/oracledb and convert it with right datetype format and return it as `comparision_value`
Mage UI
cc:

[xh] Oracle fix issue: incremental datetime bookmark fetch fails

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.68
* https://github.com/mage-ai/mage-ai/pull/4789
* https://github.com/mage-ai/mage-ai/pull/4792
* https://github.com/mage-ai/mage-ai/pull/4793
* https://github.com/mage-ai/mage-ai/pull/4794
* https://github.com/mage-ai/mage-ai/pull/4796
* https://github.com/mage-ai/mage-ai/pull/4727
* https://github.com/mage-ai/mage-ai/pull/4788
* https://github.com/mage-ai/mage-ai/pull/4797
* https://github.com/mage-ai/mage-ai/pull/4790
* https://github.com/mage-ai/mage-ai/pull/4800
* https://github.com/mage-ai/mage-ai/pull/4806
* https://github.com/mage-ai/mage-ai/pull/4807
* https://github.com/mage-ai/mage-ai/pull/4812
* https://github.com/mage-ai/mage-ai/pull/4815
* https://github.com/mage-ai/mage-ai/pull/4819
* https://github.com/mage-ai/mage-ai/pull/4822
* …

[xy] Bump version to 0.9.68

---

mage_ai/data_preparation/models/block/__init__.py

- Fix this error when adding a block via block search:
cc:

[jk] Fix block search add block error

---

mage_ai/frontend/components/AutocompleteDropdown/index.tsx
mage_ai/frontend/components/BlockBrowser/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
mage_ai/frontend/components/Tags/TagsAutocompleteInputField/index.tsx
mage_ai/frontend/interfaces/EventPropertiesType.ts
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutWrapper.tsx

- Add tracking for the Mage demo app (demo.mage.ai) for autocomplete search results (e.g. block search in Pipeline Editor and tags in Pipeline Settings).
- Confirmed tracking appeared in Google Analytics.

[jk] Autocomplete search results logging

---

requirements.txt
setup.py

Support latest version of Pydantic 2.6.4
cc:

[td] Update GX and other libraries to support higher versions of Pydantic

---

mage_ai/orchestration/queue/process_queue.py

Support cancelling jobs when using multiple replicas.
Use Redis to coordinate the job cancellation.
Close: https://github.com/mage-ai/mage-ai/issues/4847
cc:

[xy] Support cancelling jobs when using multiple replicas.

---

mage_ai/data_preparation/models/pipeline.py

Fix updating pipeline content with unicode.
Another attempt to fix this ticket: https://github.com/mage-ai/mage-ai/issues/4716
cc:

[xy] Fix updating pipeline content with unicode.

---

mage_integrations/mage_integrations/destinations/snowflake/utils.py

Close: https://github.com/mage-ai/mage-ai/issues/4821
cc:

[xy] Update snowflake destination datetime to use TIMESTAMP type.

---

docs/_snippets/contribution-process.mdx
docs/contributing/documentation/overview.mdx
mage_ai/frontend/components/ServerTimeDropdown/index.tsx
mage_ai/frontend/components/platform/Settings/index.tsx
mage_ai/frontend/components/settings/Dashboard/constants.tsx
mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/oracle/elements/Inputs/ToggleSwitch.tsx
mage_ai/frontend/playwright.config.ci.ts
mage_ai/frontend/playwright.config.ts
mage_ai/frontend/tests/utils.ts

- Display Platform Preferences tab when user authentication is disabled.
- Fix untoggling of "Override all project features" platform setting when enabling it and saving.
- Make "Display local timezone" setting more consistent when changing projects within multi-project platform and when the "Override all project features" setting is enabled.
- Locally

[jk] Multi-project platform project settings updates

---

docs/mint.json
docs/production/data-sync/version-control.mdx

Add some clarification to the version control authentication docs
cc:

[dy] Update version control authentication docs

---

mage_ai/streaming/sources/influxdb.py

Add `measurement` field to influxdb source.
Close: https://github.com/mage-ai/mage-ai/issues/4870
cc:

[xy] Add measurement to influxdb source.

---

mage_ai/data_preparation/templates/data_exporters/oracledb.py

Add template for oracle export
Local Mage UI
cc:

Fix: add template for oracle export

---

docs/design/blocks/dynamic-blocks.mdx

[td] Update dynamic blocks docs

---

docs/production/deploying-to-cloud/secrets/Azure.mdx

Update Azure secret doc about getting secret with Python code.
cc:

[xy] Update Azure secret doc.

---

mage_ai/data_preparation/repo_manager.py
mage_ai/server/server.py

This will prevent watchdog errors if the metadata.yaml file does not exist when starting the server.
cc:

[dy] Create metadata.yaml file if it doesn't exist

---

docs/production/data-sync/version-control.mdx

Update version control documentation with a warning for GitHub authentication.
cc:

[dy] Update version control documentation

---

mage_ai/data_preparation/models/block/sql/__init__.py

The ETL demo pipeline is failing due to a duckdb error and this PR should fix the issue.
cc:

[dy] Fix duckdb sql

---

mage_ai/streaming/sources/kafka.py

[edw] Fix typo in Kafka streaming source

---

docs/about/roadmap.mdx

Removing current link to roadmap until 2024 roadmap is available.
cc:

[tc] Update roadmap.mdx

---

mage_ai/orchestration/utils/resources.py

Skip checking memory in Windows.
Close: https://github.com/mage-ai/mage-ai/issues/4941
cc:

[xy] Skip checking memory in Windows.

---

mage_ai/orchestration/db/models/oauth.py
mage_ai/server/server.py
mage_ai/tests/server/test_server.py

Avoid creating duplicate `admin` user if it already exists. The server will fail to start if it tries to create a duplicate user, so this should help avoid that issue.
cc:

[dy] Avoid creating duplicate admin user

---

mage_ai/api/policies/WorkspacePolicy.py
mage_ai/api/resources/WorkspaceResource.py
mage_ai/cluster_manager/kubernetes/workload_manager.py
mage_ai/cluster_manager/workspace/base.py
mage_ai/cluster_manager/workspace/kubernetes.py
mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
mage_ai/frontend/components/workspaces/Detail/index.tsx
mage_ai/frontend/pages/manage/index.tsx

This PR will allow users to update the workspace settings (environment variables) and update the workspace main container config from the UI. Being able to update the container config will allow users to update the workspace image as well.
cc:

[dy] Add workspace update features

---

mage_ai/shared/parsers.py

Modifying parser to handle pandas._libs.missing.NAType

---

requirements.txt

Update to latest version to fix https://nvd.nist.gov/vuln/detail/CVE-2024-28179 detected by Dependabot.
Also, testing out the contributor flow before making more changes :)

Update jupyter-server-proxy to fix CVE-2024-28179

---

mage_ai/api/resources/GitBranchResource.py
mage_ai/api/resources/GitCustomBranchResource.py
mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/git/api.py
mage_ai/data_preparation/git/utils.py
mage_ai/frontend/components/VersionControl/Branches/index.tsx
mage_ai/frontend/components/VersionControl/Commit/index.tsx
mage_ai/frontend/components/VersionControl/GitActions.tsx
mage_ai/frontend/components/VersionControl/Remote/index.tsx

The git branch related API endpoints were not encoding the branch name, so if the branch name contained a `/` character, the request would fail. This PR encodes all the branch names before making the API requests. Also, it will fetch remote branches in the GitActions view so that a user can switch to a remote branch in that view.
cc:

[dy] Fix some git bugs

---

mage_ai/data_preparation/git/__init__.py
mage_ai/data_preparation/git/utils.py
mage_ai/frontend/pages/settings/workspace/sync-data.tsx

Fix more git issues.
1. Dubious ownership error when initializing git in multi project
2. Fix overwriting git user settings for the git actions modal
cc:

[dy] Fix more git issues

---

mage_ai/orchestration/job_manager.py

Reverts mage-ai/mage-ai#4990
Revert this PR since it causes server reload to fail.

Revert "[xy] Delay initializing the queue."

---

mage_ai/api/policies/PipelinePolicy.py
mage_ai/api/resources/PipelineResource.py
mage_ai/tests/api/resources/test_pipeline_resource.py

Support query pipelines with repo_path.
This can be used to fetch pipelines with sub project path via API.
```
http://localhost:6789/api/pipelines?repo_path=/home/src/multi_project/sub_project2&_limit=30&_offset=0&search=&include_schedules=1&api_key=xxx
```
cc:

[xy] Support query pipelines with repo_path.

---

mage_ai/server/scheduler_manager.py

Another attempt to fix None job manager error: https://github.com/mage-ai/mage-ai/pull/4990
Revert this PR https://github.com/mage-ai/mage-ai/pull/4994
cc:

[xy] Fix None job manager.

---

mage_ai/server/constants.py
setup.py

Bump up version to 0.9.70.
* https://github.com/mage-ai/mage-ai/pull/4929
* https://github.com/mage-ai/mage-ai/pull/4934
* https://github.com/mage-ai/mage-ai/pull/4937
* https://github.com/mage-ai/mage-ai/pull/4926
* https://github.com/mage-ai/mage-ai/pull/4944
* https://github.com/mage-ai/mage-ai/pull/4933
* https://github.com/mage-ai/mage-ai/pull/4947
* https://github.com/mage-ai/mage-ai/pull/4948
* https://github.com/mage-ai/mage-ai/pull/4950
* https://github.com/mage-ai/mage-ai/pull/4949
* https://github.com/mage-ai/mage-ai/pull/4952
* https://github.com/mage-ai/mage-ai/pull/4957
* https://github.com/mage-ai/mage-ai/pull/4928
* https://github.com/mage-ai/mage-ai/pull/4961
* https://github.com/mage-ai/mage-ai/pull/4951
* https://github.com/mage-ai/mage-ai/pull/4942
* …

[xy] Bump up version to 0.9.70.

---

mage_ai/frontend/components/shared/Header/index.tsx

Remove error pop up on sign in page in issue https://github.com/mage-ai/mage-ai/issues/5013.
cc:

[dy] Remove error pop up

---

mage_integrations/requirements.txt
requirements.txt

upgrading deltalake version to add new features ([tableMerger](https://delta-io.github.io/delta-rs/api/delta_table/delta_table_merger/))
- tested locally by running blocks to export deltalake to s3
- tested on mage_integrations using deltalake s3 exporter

upgrade deltalake for tableMerger

---

mage_ai/api/presenters/SyncPresenter.py
mage_ai/api/resources/SeedResource.py
mage_ai/api/resources/SyncResource.py
mage_ai/authentication/permissions/seed.py
mage_ai/data_preparation/git/utils.py
mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx
mage_ai/frontend/interfaces/SyncType.ts
mage_ai/frontend/pages/settings/workspace/roles/index.tsx
mage_ai/frontend/pages/settings/workspace/sync-data.tsx
mage_ai/orchestration/db/__init__.py
mage_ai/tests/base_test.py

The `SeedResource` was causing the entire app to hang while creating the default roles and permissions since it can take a while. I changed it to run in a separate thread so the app won't hang.
This PR also updates the behavior of the ssh keys and access token when they are set in environment variables so that they match the behavior of the other git settings.
cc:

[dy] Fix git and seed issues

---

mage_ai/api/presenters/StatusPresenter.py
mage_ai/api/resources/StatusResource.py
mage_ai/server/scheduler_manager.py

Include server and scheduler process id in status response to debug scheduler issue.
cc:

[xy] Include server and scheduler process id in status response.

---

docs/production/deploying-to-cloud/architecture.mdx

Typo in link description
Not applicable

docs: typo in architecture.mdx

---

docs/orchestration/triggers/schedule-pipelines.mdx
mage_ai/orchestration/db/models/schedules.py
mage_ai/tests/orchestration/test_pipeline_scheduler.py

Add pipeline_run_id to kwargs. It can be accessed via `kwargs['pipeline_run_id']` in code.
Close: https://github.com/mage-ai/mage-ai/issues/5019
cc:

[xy] Add pipeline_run_id to kwargs.

---

mage_ai/data_preparation/models/custom_templates/utils.py
mage_ai/tests/data_preparation/models/custom_templates/test_utils.py

Fix custom template issue on server start.
cc:

[xy] Fix custom template issue on server start.

---

mage_ai/tests/api/operations/base/test_base_with_user_authentication.py
mage_ai/tests/api/operations/base/test_base_with_user_permissions.py

There're flaky unit tests from the following files:
mage_ai/tests/api/operations/base/test_base_with_user_permissions.py
mage_ai/tests/api/operations/base/test_base_with_user_authentication.py
Comment out them first. Will look into the tests later
cc:

[xy] Comment out flaky unit tests

---

mage_ai/api/resources/GitBranchResource.py
mage_ai/data_preparation/git/utils.py

Use the email from the mage user if the email returned from the api is None.
cc:

[dy] Update git email field

---

mage_ai/settings/platform/__init__.py
mage_ai/shared/parsers.py

Fix some circular dependencies related to initializing the DB.
cc:

[dy] Fix circular dependency

---

mage_ai/tests/api/operations/base/test_base.py
mage_integrations/mage_integrations/connections/mssql/__init__.py
mage_integrations/mage_integrations/destinations/mssql/README.md
mage_integrations/mage_integrations/destinations/mssql/__init__.py
mage_integrations/mage_integrations/destinations/mssql/templates/config.json
mage_integrations/mage_integrations/sources/mssql/README.md
mage_integrations/mage_integrations/sources/mssql/__init__.py
mage_integrations/mage_integrations/sources/mssql/templates/config.json
mage_integrations/mage_integrations/tests/destinations/mssql/test_mssql.py
mage_integrations/mage_integrations/tests/destinations/sql/mixins.py

Allow configuring authentication mode in mssql config.
Close: https://github.com/mage-ai/mage-ai/issues/5037
cc:

[xy] Allow configuring authentication mode in mssql config.

---

docs/development/troubleshooting.mdx
docs/integrations/databases/PostgreSQL.mdx
docs/production/configuring-production-settings/compute-resource.mdx

* Postgres doc
* ECS executor
* K8s executor
* Troubleshooting block running status
cc:

[xy] Update some docs

---

mage_ai/frontend/next.config.js
mage_ai/frontend/next_base_path.config.js

[td] Turn off unoptimized images

---

mage_ai/data_preparation/models/block/outputs.py
mage_ai/data_preparation/models/project/__init__.py
mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/variable_manager.py
mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/OutputRenderer.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/TableOutput.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/TextOutput.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/KernelOutputType.ts
mage_ai/frontend/package.json
mage_ai/frontend/yarn.lock
mage_ai/server/kernel_output_parser.py
mage_ai/server/utils/custom_output.py
mage_ai/server/utils/output_display.py
mage_ai/shared/parsers.py
mage_ai/shared/yaml.py

- Fixed parsing of interpolating loaded YAML as Python dictionary
- Fixed rendering no output
- Improved rendering list outputs

[td] Fix IDE outputs

---

mage_ai/api/resources/VersionControlProjectResource.py

[td] Fix git issue

---

mage_ai/api/resources/VersionControlProjectResource.py

Td  fix git2

---

mage_ai/server/websocket_server.py

Fix websocket authentication.
Check whether oauth_token is None before getting the user.
cc:

[xy] Fix websocket authentication.

---

mage_ai/server/utils/execute_custom_code.py
mage_ai/server/utils/output_display.py
mage_ai/server/websocket_server.py

Bulletproof interpolation of dictionary objects.

[td] Fix interpolating dictionaries when adding custom code to ide execution

---

mage_ai/api/resources/ClusterResource.py
mage_ai/cluster_manager/aws/emr_cluster_manager.py
mage_ai/server/utils/output_display.py

Fix switching active kernel. Update repo_path to keyword argument
cc:

[xy] Fix switching active kernel

---

mage_ai/data_preparation/executors/streaming_pipeline_executor.py

Set infinite_retries to True if retry_config is not present
cc:

[xy] Fix retry in streaming pipeline.

---

docs/production/custom-docker-image/non-root-user.mdx

Made corrections to misspelled words. 
"reocmmended" is corrected to "recommended."
"restict" is corrected to "restrict."
Capitalized "Docker" since it's a proper noun.
cc:
@thomaschung408  I don't know anyone else to CC :)

Grammar corrections to doc "Update non-root-user.mdx"

---

.gitignore
mage_ai/data_preparation/models/utils.py
mage_ai/tests/data_preparation/models/test_utils.py

Fix inferring variable types so Polars works when flag is on.

[td] Fix infer variables

---

mage_ai/data/models/manager.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/variable_manager.py

Fic circular dependency of importing from variable_manager file.
cc:

[xy] Fic circular dependency.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/extension/utils.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/variable_manager.py
mage_ai/settings/repo.py
mage_ai/shared/yaml.py

* Speed up pipeline update endpoint by removing unnecessary pipeline file updates
* Consolidate print output for scratchpad block
* Speed up variables write (not call get_variables_dir duplicately)
* Speed up yaml load with CLoader
cc:

[xy] Speed up pipeline update endpoint.

---

mage_ai/shared/outputs.py

[td] Don’t raise error if can’t load

---

mage_ai/api/resources/CustomTemplateResource.py

Fix custom template creation.
cc:

[xy] Fix custom template creation.

---

mage_ai/data_preparation/storage/gcs_storage.py
mage_ai/data_preparation/storage/local_storage.py
mage_ai/data_preparation/storage/s3_storage.py
mage_ai/data_preparation/variable_manager.py
mage_ai/shared/models.py

* Catch exception in variables API
* Let BaseEnum to also inherit from str so that the comparison between an enum value and a string is not always false.
cc:

[xy] Fix variables API and BaseEnum

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/triggers/__init__.py
mage_ai/orchestration/db/models/schedules.py
mage_ai/orchestration/pipeline_scheduler_original.py
mage_ai/shared/config.py

Reduce CPU usage in scheduler by reducing unnecessary yaml parsing
cc:

[xy] Reduce CPU usage in scheduler.

---

mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/components/TripleLayout/index.tsx

[td] Fix after on pipeline dashboard

---

mage_ai/frontend/components/TripleLayout/index.tsx

[td] Fix after panel showing up everywhere

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.71
* [xh]Create streaming oracle destination by @matrixstone in https://github.com/mage-ai/mage-ai/pull/4896
* [xy] Exclude dropped columns from the postgres schema discovery query. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5002
* [xy] Fix None Bigquery database error. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5005
* [xy] Fix extracting table name from INSERT statement in SQL block. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5008
* [xy] Catch yaml interpolation error. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5012
* [xy] Not run insert query for empty dataframe. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5017
* [dy] Fix git and seed issues by @dy46 in …

[xy] Bump version to 0.9.71

---

.github/workflows/publish_to_pypi.yml

Update pypi github action.
* Set the version of the package instead of master branch
* Set verbose to true
* Set skip-existing to true
cc:

[xy] Update pypi github action

---

Dockerfile
dev.Dockerfile

Fix Dockerfile to:
```
pip3 install --no-cache-dir faster-fifo && \
```

[td] Fix Dockerfile to install faster fifo from source

---

mage_ai/api/resources/WorkspaceResource.py
mage_ai/data_preparation/models/block/dynamic/models.py

Fix import statement of Optional type
Add user to verify_project method in WorkspaceResource
cc:

[xy] Fix import and add user to verify_project.

---

docs/production/authentication/overview.mdx
mage_ai/server/server.py
mage_ai/settings/server.py
mage_ai/tests/server/test_server.py

Allow configuring custom owner credentials through environment variables
* DEFAULT_OWNER_EMAIL
* DEFAULT_OWNER_PASSWORD
* DEFAULT_OWNER_USERNAME
cc:

[xy] Allow configuring custom owner credentials.

---

docs/integrations/databases/Algolia.mdx

Added missing backtick in Algolia integration docs page.
- [] The PR is tagged with proper labels (bug, enhancement, feature, documentation)

docs: fix markdown formatting

---

docs/orchestration/backfills/guides.mdx

1. see title
- tested link locally in mintlify dev environment 
cc:

[cf] added link to backfill guide

---

mage_ai/data_preparation/executors/executor_factory.py
mage_ai/data_preparation/models/block/__init__.py

Fix executor type when not specified.
When executor_type is not specified, it should default executor type.
cc:

[xy] Fix executor type when not specified.

---

mage_integrations/mage_integrations/sources/api/__init__.py
requirements.txt

Upgrade polars package version to latest version
Close: https://github.com/mage-ai/mage-ai/issues/5170
Close: https://github.com/mage-ai/mage-ai/issues/5169
cc:

[xy] Upgrade polars package version

---

mage_ai/api/resources/PipelineResource.py
mage_ai/api/resources/ProjectResource.py
mage_ai/cache/mem_lru.py
mage_ai/cache/ttl.py
mage_ai/data_preparation/models/block/platform/mixins.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/project/__init__.py
mage_ai/tests/data_preparation/models/block/dynamic/test_combos.py
mage_ai/tests/data_preparation/models/block/dynamic/test_factory.py
mage_ai/tests/data_preparation/models/test_block.py
mage_ai/tests/data_preparation/test_variable_manager.py
requirements.txt

Speed up Pipeline get and list.
* Add in memory LRU cache for Pipeline read and parsing.
* Optimize the configuration clean path method for dbt block
* Not repeatedly call get_repo_config in Pipeline LIST endpoint. Each get_repo_config takes about 3-4ms in my test.
* Cache project latest version with TTL cache.
cc:

[xy] Speed up Pipeline get and list.

---

mage_ai/autocomplete/utils.py

Speed up autocomplete endpoint with cache.
cc:

[xy] Speed up autocomplete endpoint with cache.

---

mage_ai/api/policies/BrowserItemPolicy.py
mage_ai/api/policies/CodeExecutionPolicy.py
mage_ai/api/presenters/BrowserItemPresenter.py
mage_ai/api/resources/BaseResource.py
mage_ai/api/resources/BrowserItemResource.py
mage_ai/authentication/permissions/constants.py
mage_ai/server/server.py
mage_ai/shared/files.py
mage_ai/system/browser/models.py

[td] Browser items API

---

.github/workflows/build_and_test.yml

- Never finishes running on Windows Server 10 for some reason

[td] Disable playright, never finishes no windows server 3.10

---

mage_ai/data_preparation/decorators.py
mage_ai/data_preparation/executors/streaming_pipeline_executor.py
mage_ai/data_preparation/templates/data_exporters/streaming/generic_python.py
mage_ai/data_preparation/templates/template.py
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
mage_ai/streaming/sinks/base.py
mage_ai/streaming/sinks/base_python.py
mage_ai/streaming/sinks/sink_factory.py

Support custom python sink in Streaming pipeline so that user can write their own streaming sink.
cc:

Support custom python sink in Streaming pipeline

---

mage_ai/data_preparation/executors/k8s_block_executor.py
mage_ai/data_preparation/executors/k8s_pipeline_executor.py
mage_ai/settings/server.py
mage_ai/tests/data_preparation/models/test_pipeline.py

Custom kubernetes config
* Use MAGE_CLUSTER_UUID as the prefix for the job so that there're no duplicate job names when multiple Mage deployments are running in the same cluster
cc:

[xy] Custom kubernetes job prefix

---

mage_ai/data_preparation/models/global_data_product/__init__.py

Fix global data product in single project.
https://github.com/mage-ai/mage-ai/issues/5155
cc:

[xy] Fix global data product in single project.

---

docs/mint.json
docs/orchestration/global-hooks/guides.mdx
docs/orchestration/global-hooks/overview.mdx

Documentation for Global Hooks
Docs appeared as expected in the Mintlify dev env
cc:

[cf] Global Hooks Docs

---

.circleci/config.yml

Try using xlarge instance in circleci export_frontend job.
cc:

[xy] Try using xlarge in circleci.

---

.github/workflows/build_and_test.yml
mage_ai/frontend/pages/_app.tsx

On the first initial load of the overview page, it flickers infinitely.

[td] Revert Next _app back before breaking change

---

docs/production/deploying-to-cloud/secrets/AWS.mdx

This PR updates the current AWS Secrets Manager documentation 
The document was tested and appeared as normal in the mintlify dev env. Pictures Attached.
cc:

[CF] AWS Secrets Manager Docs Update

---

docs/development/observability/logging.mdx
docs/integrations/observability/alerting-discord.mdx
docs/integrations/observability/alerting-email.mdx
docs/integrations/observability/alerting-slack.mdx
docs/integrations/observability/alerting-telegram.mdx

Some small fixes on the docs.
cc:

[xy] Some small fixes on the docs.

---

docs/orchestration/triggers/schedule-pipelines.mdx

This update includes more description about the types of schedules (hourly, daily, weekly, etc.)
This document was tested and appeared as expected in the mintlify dev env. See picture.
cc:
cc @johnson-mage

[cf] Updates to schedules doc

---

mage_ai/server/constants.py
setup.py

Bump version to 0.9.72
* [td] Canvas V2 by @tommydangerous in https://github.com/mage-ai/mage-ai/pull/5193
* Support custom python sink in Streaming pipeline by @lgarcia11 in https://github.com/mage-ai/mage-ai/pull/5174
* [xy] Fix delete/update workspace. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5146
* [td] Fix Dockerfile to install faster fifo from source by @tommydangerous in https://github.com/mage-ai/mage-ai/pull/5152
* [xy] Fix import and add user to verify_project. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5151
* [xy] Fix auto_clean_name param. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5161
* [xy] Bump the version of dbt-sqlserver to 1.7.4 by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5162
* [xy] Fix …

[xy] Bump version to 0.9.72

---

mage_integrations/mage_integrations/sources/api/__init__.py
requirements.txt

Reverts mage-ai/mage-ai#5176
Upgrade of polars causes some version incompatibility when installing Mage via pip. Will need to resolve the issues before upgrading the version.

Revert "[xy] Upgrade polars package version"

---

requirements.txt

Resolve CVE-2024-35225
https://github.com/mage-ai/mage-ai/security/code-scanning/195
cc:

[xy] Resolve CVE-2024-35225

---

mage_ai/api/presenters/BlockPresenter.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frameworks/execution/constants.py
mage_ai/frameworks/execution/models/pipeline/base.py

Add pipeline execution logic for execution framework.
* Set block dependencies based on execution framework and run blocks.
* Copy block configuration from block template if present
cc:

[xy] Pipeline execution for execution framework

---

docs/design/blocks/data-exporter.mdx

This pull request updates the Data Exporter documentation 
The doc is showing as expected in mintlify dev env.
cc:
@johnson-mage

[cf]-data-exporter-docs-update

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/utils/shared.py
mage_ai/data_preparation/models/utils.py

Interpolate the sql profile.
Close: https://github.com/mage-ai/mage-ai/issues/4129
cc:

[xy] Interpolate the sql profile.

---

mage_ai/data_preparation/models/widget/utils.py

Don't force cast type to int or float in dashboard charts
Close: https://github.com/mage-ai/mage-ai/issues/5246
cc:

[xy] Don't force cast type to int or float.

---

docs/streaming/sources/azure-event-hub.mdx

This PR is an update to the Azure Event Hub documentation.
The document is appearing as expected in the mintlify dev env.
cc:
@johnson-mage

[CF]-Azure-Event-Hub-Doc-Update

---

mage_ai/authentication/providers/utils.py
mage_ai/server/server.py

Some fixes for using requests base path.
* fonts path is not set correctly when using base path.
* google authentication redirect url is not set correctly when using request base path
Close: https://github.com/mage-ai/mage-ai/issues/5264
cc:

[xy] Some fixes for using requests base path.

---

mage_ai/frameworks/execution/models/pipeline/base.py

Allow optional block groups in execution framework. Find upstream blocks and downstream blocks recursively.
cc:

[xy] Allow optional block groups.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/dbt/block_sql.py

Fix adding dbt block. Add all upstream dbt blocks when adding a dbt block
cc:

[xy] Add all upstream dbt blocks when adding a dbt block

---

mage_ai/services/k8s/config.py
mage_ai/services/k8s/job_manager.py

Support customizing node selector in k8s config.
cc:

[xy] Support customizing node selector in k8s config.

---

.github/workflows/export_frontend.yml

Add export frontend job in github action
The job is triggered manually
cc:

[xy] Add export frontend job in github action

---

.github/workflows/build_and_test.yml
.github/workflows/export_frontend.yml

[xy] Fix export frontend job

---

.github/workflows/export_frontend.yml

Create PR instead of push directly to master branch for frontend build.
cc:

[xy] Create PR instead of push directly to master branch for frontend build.

---

mage_ai/server/constants.py
requirements.txt
setup.py

* Memory management upgrade: https://www.notion.so/mageai/Memory-management-upgrades-e6c5e6e360ce410094091e00c46e3bb6?pvs=4
* Dynamic blocks 2.0 https://www.notion.so/mageai/Dynamic-Blocks-2-0-d2fc11a4f48148d68b817e9bfb38a732
* [xy] Support getting Azure db conn url from key vault. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5302
* [jk] Workspace monitoring by @johnson-mage in https://github.com/mage-ai/mage-ai/pull/5311
* [td] Fix editor v2 page by @tommydangerous in https://github.com/mage-ai/mage-ai/pull/5222
* [jk] Add specific lodash dependency version by @johnson-mage in https://github.com/mage-ai/mage-ai/pull/5237
* [xy] Don't force cast type to int or float. by @wangxiaoyou1993 in https://github.com/mage-ai/mage-ai/pull/5254
* [xy] Some fixes for using requests …

[xy] Bump version to 0.9.73

---

docs/development/dependencies/requirements.mdx

Documentation for the requirements.txt file were changed for installing python packages
This documentation was tested in the mintlify dev env.
cc:
@johnson-mage 
https://github.com/user-attachments/assets/aa3505f9-6037-416e-95df-e8cab7a61a44

[cf]-requirements-documentation-updates

---

mage_ai/data_preparation/models/triggers/__init__.py

Fix NoneType in trigger settings.
cc:

[xy] Fix NoneType in trigger settings.

---

mage_ai/server/server.py

Fix API for file versions when using Nginx.
cc:

[xy] Fix API for file versions.

---

docs/streaming/sources/activemq.mdx

This is a documentation update to the ActiveMQ streaming source page
Yes, this has been tested in the mintlify dev env.
cc:
@johnson-mage

ActiveMQ update commit

---

mage_ai/cluster_manager/kubernetes/workload_manager.py

Pass main pod labels to workspaces.
cc:

[xy] Pass main pod labels to workspaces.

---

mage_ai/io/base.py
mage_ai/io/google_cloud_storage.py

This include some updates on the export method of the gcs io to enable exporting polars dataframes beside pandas dataframes
Fix #4881 
cc:

Enable polars dataframe

---

docs/production/configuring-production-settings/compute-resource.mdx

Fixed spelling of two words in compute-resources.mdx.
cc:
@johnson-mage

Fix spelling in compute-resource.mdx

---

mage_ai/io/postgres.py

Fix schema creation when schema name is wrapped with double quotes.
cc:

[xy] Fix schema creation when schema name is wrapped with double quotes.

---

docs/production/authentication/microsoft.mdx

Added environment variable configuration `AZURE_HOST` and `MICROSOFT_GRAPH_API_HOST` to docs
Yes this was tested and working in the mintlify dev env.
cc:
@johnson-mage

[CF]-Azure-gove

---

mage_ai/ai/openai_client.py

This PR is to fix issue: https://github.com/mage-ai/mage-ai/issues/5323.
Before accessing the response, it checks the status of response. If it is still error after retries, we throw the error out.
Tested in local Mage UI
cc:

[xh] Add retry logic and throw if open AI API returns error

---

mage_ai/api/presenters/SyncPresenter.py
mage_ai/data_preparation/preferences.py
scripts/dev.sh

[td] Fix Git syncs API error returning sync_on_executor_start

---

docs/production/deploying-to-cloud/aws-without-terraform.mdx

"_Prerequistes_" → "_Prerequisites_"

Fixing spelling error

---

mage_ai/data_preparation/templates/data_loaders/streaming/nats.yaml
mage_ai/streaming/sources/nats_js.py

Allow NATS JS streaming source to authenticate through a credentials file
Performed integration tests on a jwt enabled NATS server
- [ X] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
cc:

Add NATS credentials file authentication

---

mage_ai/data_integrations/sources/constants.py
mage_integrations/mage_integrations/connections/airtable/__init__.py
mage_integrations/mage_integrations/sources/airtable/README.md
mage_integrations/mage_integrations/sources/airtable/__init__.py
mage_integrations/mage_integrations/sources/airtable/templates/config.json
requirements.txt

Airtable Data Integration Source
cc:

Airtable Integration

---

Dockerfile

[xy] Fix Dockerfile.

---

mage_ai/frontend/components/DataTable/index.tsx

- Fix vertical overflow of cells in block output tables.
- Locally
cc:

[jk] Block output table cell overflow

---

docs/design/blocks.mdx

[td] Add block overview

---

docs/streaming/overview.mdx

[td] Add case study to streaming pipelines

---

docs/design/blocks.mdx

[td] Fix blocks doc

---

docs/getting-started/setting-up-git.mdx

Improved a grammatical error in the getting started docs related to using Git in Mage.
No test has been performed, as it is only a grammatical error in the docs.
cc:

Update documentation for Git in Mage in the Getting Started section

---

mage_integrations/mage_integrations/sources/google_cloud_storage/__init__.py

this fix load data in google cloud storage integration
Fix #5455 
cc:

Fix load data in GCS integration

---

docs/production/deploying-to-cloud/aws/setup.mdx

This PR contains a small improvement to the docs related to enabling HTTPS in a load balancer in AWS. 
No test has been performed, as it is only a small update to the docs.
cc:

Update text in documentation about enabling HTTPS in AWS

---

docs/production/configuring-production-settings/compute-resource.mdx

This PR fixes typos in the compute resources documentation
No tests needed.
cc:

Fix typos in compute-resource.mdx

---

mage_ai/io/oracledb.py

```
values = []
for i in range(0, len(df_)): 
values.append(tuple(df_.fillna('').values[i])) 
```
in for loop, pandas's values function is keep being called, so if dataframe is large (many rows), it will take long time to make list of tuples.
Tested it on local development 
cc:

[Oracle DB] Modify inefficient code that converts dataframe to list of tuples

---

docs/streaming/destinations/elasticsearch.mdx
mage_ai/data_preparation/templates/data_exporters/streaming/elasticsearch.yaml
mage_ai/streaming/sinks/elasticsearch.py

Align the doc publishing of records in the same way as its done with the [Standard (batch) mode](https://github.com/mage-ai/mage-ai/blob/8aec8f92ea7f3afa787eca7a4401b1506a9857f1/mage_integrations/mage_integrations/destinations/elasticsearch/target_elasticsearch/sinks.py#L145)
cc:

[enhancement] Elasticsearch - Align the doc publishing with the Standard (batch)

---

docs/integrations/observability/alerting-teams.mdx

Updating the documentation for microsoft teams notification in case [this PR](https://github.com/mage-ai/mage-ai/pull/5508) be merged.
Only with preview mode.
cc:

Update alerting-teams.mdx for multiples webhooks.

---

docs/mint.json

[td] Add GA to docs

---

docs/design/data-loading.mdx
mage_ai/io/base.py

Support for laoding and exporting xls/xlsx file in base IO class
Manually tested. I test to wirte and read different files to Minio using the S3 data loder/exporter. I also ran all existing tests.
I do not understand why test pipeline fails. I have no problem locally and this seems to concern a part of the code that I have not modified

[Enhancement] io/base.py: add Excel support

---

mage_integrations/requirements.txt
requirements.txt

Bump up the `deltalake` module to a later version, as suggested in https://github.com/mage-ai/mage-ai/pull/5504, and fix some build issues due to incompatible module versions.
cc:

[hw] Update deltalake to a recent version `0.20.2`

---

README.md

[td] Update main docs

---

README.md

[td] Update links

---

README.md

[td] Add more spacing breaks

---

README.md

[td] Add links to cards

---

docs/snippets/pro/button.mdx
docs/style.css

[td] Try to remove border bottom on buttons in docs

---

docs/ai/ai-client.mdx

Fixed typo
differnt > different

Typo fix ai-client.mdx

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/templates/data_loaders/streaming/nats.yaml

Address the issue reported in https://github.com/mage-ai/mage-ai/issues/5556.
cc:

[hw] Correct the SSL settings in the nats configuration template

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlockV2/Editor/index.tsx
mage_ai/frontend/components/CodeBlockV2/useCodeBlockComponents.tsx
mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
mage_ai/frontend/components/FileBrowser/Folder/index.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/FileBrowser/utils.ts
mage_ai/frontend/components/FileSelectorPopup/index.tsx
mage_ai/frontend/components/Files/useFileComponents.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/ButtonItems.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetailPage/utils.ts
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/Triggers/utils.ts
mage_ai/frontend/components/settings/workspace/Preferences.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/interfaces/ProjectType.ts
mage_ai/frontend/pages/overview/index.tsx
mage_ai/frontend/tests/base.ts
mage_ai/frontend/tests/pages.spec.ts
mage_ai/frontend/tests/utils.ts

[jk] misc updates

---

docs/data-integrations/batch-pipelines.mdx

Adds an information box to the Data Integrations>Batch Pipelines page detailing the dependency of the `Data integrations in batch pipeline` feature on `Add new block v2`.
This closes #5583
Locally rendered and checked.
cc:

Add information regarding feature dependency to docs

---

mage_ai/server/constants.py
mage_integrations/requirements.txt
requirements.txt
setup.py

Bump up version to 0.9.75
* Airtable Destination by @TalaatHasanin in https://github.com/mage-ai/mage-ai/pull/5454
* [hw] Support Mage in Python 3.11 and 3.12 by @csharplus in https://github.com/mage-ai/mage-ai/pull/5393
* Add postgres client package by @jx2lee in https://github.com/mage-ai/mage-ai/pull/5486
* [enhancement] Update Elasticsearch + verify_certs connection option by @syepes in https://github.com/mage-ai/mage-ai/pull/5462
* [enhancement] adds support of _op_type for bulk operations of destinations by @syepes in https://github.com/mage-ai/mage-ai/pull/5482
* [enhancement] Elasticsearch support of _op_type for bulk operations by @syepes in https://github.com/mage-ai/mage-ai/pull/5471
* Add support to multiples webhook endpoints for Microsoft Teams notification service by …

[xy] Bump up version to 0.9.75

---

docs/mint.json

I deleted the destination redirect json item for streaming sources and destination links not working
All the links are working on mintlify dev env, see photos of some sources
cc:

[cf]-fixed-links-to-streaming-docs

---

mage_integrations/requirements.txt
requirements.txt
setup.py

Address the upgrade request in https://github.com/mage-ai/mage-ai/issues/5525.
cc:

Update the version for the google-ads module

---

docs/mint.json

Added destinations back to redirects for streaming links
Tested in mitlify dev env
- [X
] I have made corresponding changes to the documentation
cc:
@johnson-mage

[cf]-added-destinations-back

---

README.md
docs/introduction/overview.mdx
docs/mint.json
docs/snippets/pro/banner.mdx
docs/snippets/pro/button.mdx
docs/snippets/pro/only.mdx
docs/snippets/variables/urls.mdx

[td] Update docs sign up

---

docs/getting-started/setup.mdx

Added Mage Pro documentation to the getting started page
This was tested in mintlify dev. env.
cc:
@johnson-mage 
New screenshots of UI to follow

Mage Pro getting started documentation

---

docs/development/variables/environment-variables.mdx
docs/getting-started/setup.mdx

This PR updates the documentation for mage pro environment variables and the getting started page.
The documentation is working on mintlify dev env.
cc:

[cf] Mage Pro environment variables and getting started

---

mage_ai/io/mssql.py
mage_ai/io/sql.py

Support passing chunksize and method to mssql export method.
Close: https://github.com/mage-ai/mage-ai/issues/5636
cc:

[xy] Support passing chunksize and method to mssql export method.

---

requirements.txt

Updates dependency version.
Ran locally, connected to MotherDuck successfully.
- [x ] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [x ] I have performed a self-review of my own code

enhancement: Upgrade DuckDB to the latest stable version

---

docs/guides/dbt/overview.mdx
docs/introduction/overview.mdx
docs/mint.json

Some links to dbt related document pages were out-of-date, which has been updated to valid ones.
cc:

[hw] Update a few out-of-date dbt doc links

---

mage_ai/io/mssql.py

Close: https://github.com/mage-ai/mage-ai/issues/5650
cc:

[xy] Support pool_size and max_overflow in mssql connect kwargs.

---

mage_ai/api/resources/SessionResource.py
mage_ai/orchestration/db/__init__.py

Add safe_db_query_async decorator to catch db issues in async methods.
Close: https://github.com/mage-ai/mage-ai/issues/5637
cc:

[xy] Add safe_db_query_async decorator.

---

mage_ai/io/bigquery.py

Auto cast timestamp columns for bigquery exporter.
cc:

[xy] Auto cast timestamp columns for bigquery exporter.

---

mage_ai/api/resources/SyncResource.py
mage_ai/orchestration/db/models/secrets.py

Close: https://github.com/mage-ai/mage-ai/issues/5662
Fetch git secret with repo query so that git credentials can be created per workspace.
cc:

[xy] Fetch git secret with repo query.

---

docs/guides/developer-ux/workspaces.mdx
docs/mint.json

This pull request is for the workspaces documentation 
This documentation appeared as expected in the mintlify dev env.
cc:
@johnson-mage

[cf] workspaces documentation

---

mage_ai/api/resources/PipelineScheduleResource.py
mage_ai/api/resources/PipelineTriggerResource.py

Not save token to triggers.yaml if `HIDE_API_TRIGGER_TOKEN` is true.
cc:

[xy] Not save token to triggers.yaml if HIDE_API_TRIGGER_TOKEN is true.

---

mage_ai/io/bigquery.py

Fix bigquery write with replace policy. Set the job config with schema and write_disposition.
cc:

[xy] Fix bigquery write with replace policy.

---

docs/mint.json

[td] Updated button URL

---

docs/guides/developer-ux/workspaces.mdx

Added Mage Pro only banner to doc
Screenshot from mintlify dev env below 
cc:
@johnson-mage

[cf] workspaces mage pro banner

---

docs/guides/developer-ux/visual-studio-code.mdx
docs/mint.json

VS Code video, written docs will come later
The link in the nav bar and the page are functioning normally in mintlify dev env.
cc:
@johnson-mage

[cf] vscode video commit

---

docs/guides/data-sync/version-control-guide.mdx
docs/guides/developer-ux/visual-studio-code.mdx
docs/mint.json

This is the new version control documentation guide
The page is functioning properly in mintlify dev env.
cc:
@johnson-mage

New version control doc

---

mage_ai/server/api/triggers.py

Only allow api trigger endpoint for API trigger.
cc:

[xy] Only allow api trigger endpoint for API trigger.

---

mage_ai/server/api/triggers.py

Revert "[xy] Only allow api trigger endpoint for API trigger."

---

mage_ai/server/api/triggers.py

Fix the issue mentioned in PR: https://github.com/mage-ai/mage-ai/pull/5706
cc:

[xy] Fix API trigger request authentication.

---

mage_ai/data_integrations/destinations/constants.py
mage_ai/data_integrations/sources/constants.py
mage_integrations/mage_integrations/connections/sql/base.py
mage_integrations/mage_integrations/connections/teradata/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/sql/base.py
mage_integrations/mage_integrations/destinations/teradata/README.md
mage_integrations/mage_integrations/destinations/teradata/__init__.py
mage_integrations/mage_integrations/destinations/teradata/templates/config.json
mage_integrations/mage_integrations/destinations/teradata/utils.py
mage_integrations/mage_integrations/sources/sql/base.py
mage_integrations/mage_integrations/sources/teradata/README.md
mage_integrations/mage_integrations/sources/teradata/__init__.py
mage_integrations/mage_integrations/sources/teradata/templates/config.json
mage_integrations/requirements.txt

Add teradata source and destination to data integration pipeline
* Teradata source
* full table sync + incremental sync
* with and without unique constraints
* Teradata destination
cc:

[xy] Add teradata source and destination to data integration pipeline

---

docs/guides/developer-ux/workspaces.mdx
docs/integrations/compute/databricks.mdx
docs/integrations/databases/Databricks.mdx
docs/mint.json

Add docs for databricks integration.
cc:

[xy] Add docs for databricks integration.

---

docs/integrations/airbyte.mdx

Update airbyte integration docs.
cc:

[xy] Update airbyte integration docs.

---

mage_ai/orchestration/metrics/pipeline_run.py

Fix data integration pipeline run metrics.
Close: https://github.com/mage-ai/mage-ai/issues/5661
cc:

[xy] Fix data integration pipeline run metrics.

---

docs/orchestration/pipeline-runs/retrying-block-runs.mdx

Update doc for retry config.
cc:

[xy] Update doc for retry config.

---

docs/guides/data-sync/version-control-guide.mdx
docs/guides/data-sync/version-control.mdx

Update version control doc.
cc:

[xy] Update version control doc.

---

docs/guides/streaming/sources/oracledb.mdx
docs/mint.json

[xy] Add doc for oracledb CDC.

---

docs/development/git/setting-up-git.mdx

Update doc for version control.
cc:

[xy] Update doc for version control.

---

docs/integrations/compute/spark-pyspark.mdx

[xy] Update pyspark doc.

---

docs/guides/streaming/tutorials/streaming-stateful-store.mdx
docs/mint.json

Add doc for stateful streaming pipeline.
cc:

[xy] Add doc for stateful streaming pipeline.

---

.github/workflows/build_and_test.yml

Comment out tj-actions/changed-files@v36 package in CI.
cc:

[xy] Fix CI

---

mage_ai/usage_statistics/logger.py

Update event logging to use sync method in scheduler
cc:

[xy] Update event logging to use sync method in scheduler

---

mage_integrations/mage_integrations/connections/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/README.md
mage_integrations/mage_integrations/destinations/snowflake/__init__.py
mage_integrations/mage_integrations/destinations/snowflake/templates/config.json
mage_integrations/mage_integrations/sources/snowflake/README.md
mage_integrations/mage_integrations/sources/snowflake/__init__.py
mage_integrations/mage_integrations/sources/snowflake/templates/config.json
mage_integrations/mage_integrations/tests/destinations/snowflake/test_snowflake.py

Support key authentication in snowflake source and destination.
cc:

[xy] Support key authentication in snowflake source and destination.

---

mage_integrations/requirements.txt
requirements.txt
setup.py

Close: https://github.com/mage-ai/mage-ai/issues/5722
* Upgrade package versions for some packages
* Fix version differences between two requierments.txt
* Fix couchbase version for python 3.12
cc:

[xy] Upgrade package versions.

---

.github/workflows/publish_to_pypi.yml

[xy] Fix PyPI github action.

---

.github/workflows/publish_to_pypi.yml

Fix python version in pypi action.
cc:

[xy] Fix python version in pypi action.

---

docs/development/io_config.mdx

Add doc for unified io config.
cc:

[xy] Add doc for unified io config.

---

mage_ai/orchestration/queue/config.py

Enforce int for queue concurrency.
cc:

[xy] Enforce int for queue concurrency.

---

mage_ai/api/resources/GitFileResource.py

Address the security issue reported in https://github.com/mage-ai/mage-ai/issues/5605.
cc:

[hw] Resolve a security issue related to file traversal

---

docs/guides/developer-ux/workspaces.mdx

Made updates to the workspace documentation 
I tested this in the mintlify dev env
cc:

[cf] workspaces update inherit env var commit

---

docs/development/variables/referencing-variables.mdx

Update doc for local file content syntax
cc:

[xy] Update doc for local file content syntax

---

docs/extensibility/pro-api-reference/overview.mdx
docs/mint.json

[xy] Add pro API doc

---

docs/design/data-pipeline-management.mdx

Add doc for global concurrency by block uuid.
cc:

[xy] Add doc for global concurrency by block uuid.

---

mage_ai/streaming/sources/kafka.py
mage_ai/tests/streaming/sources/test_kafka.py

Commit Kafka offset after processing the messages.
Close: https://github.com/mage-ai/mage-ai/issues/5757
cc:

[xy] Commit Kafka offset after processing the messages.

---

docs/data-integrations/sources/custom_source.mdx
docs/mint.json

Add doc for plugging in custom DI source.
cc:

[xy] Add doc for plugging in custom DI source.

---

docs/data-integrations/sources/custom_source.mdx

Add testing method to custom source doc.
cc:

[xy] Add testing method to custom source doc.

---

docs/development/variables/overview.mdx

Address issue reported in: https://github.com/mage-ai/mage-ai/issues/5421
Typo fixed
N/A
cc:
@csharplus

Fixed typo in doc

---

.github/workflows/trivy.yml

Resolve the issue that `trivy.yml` was not running, as discussed in https://github.com/actions/runner-images/issues/11101.
Updated to use the `ubuntu-latest` version, same with that in other `yml` files for github actions.
cc:

[hw] Update the version of ubuntu to the latest to resolve the build issue with `trivy.yml`

---

mage_ai/orchestration/notification/sender.py
mage_ai/tests/orchestration/notification/test_sender.py

Addressed issue reported in https://github.com/mage-ai/mage-ai/issues/5784
cc:
@csharplus @wangxiaoyou1993

Update teams title to resolve issue #5784

---

docs/data-integrations/overview.mdx
docs/data-integrations/sources/quickbooks.mdx
docs/data-integrations/sources/stripe.mdx
docs/data-integrations/sources/xero.mdx
docs/mint.json

Add new data integration sources docs.
cc:

[xy] Add new data integration sources docs.

---

docs/guides/developer-ux/visual-studio-code.mdx
docs/guides/developer-ux/workspaces.mdx

Update doc for workspace and tailscale.
cc:

[xy] Update doc for workspace and tailscale.

---

docs/fiber.js

[td] Remove Fiber.js

---

docs/extensibility/pro-api-reference/deployments/overview.mdx
docs/mint.json

[xy] Add deploy API doc.

---

docs/guides/dbt/developing-dbt-in-mage.mdx
docs/guides/dbt/overview.mdx
docs/integrations/databases/Iceberg.mdx
docs/mint.json

[xy] Add doc for Iceberg.

---

docs/guides/dbt/overview.mdx
docs/production/mage/pro.mdx

[xy] Update dbt and pro docs.

---

docs/guides/tips-and-tricks.mdx

[td] Async guide

---

docs/docs.json

Added some pro features to the new Mage Pro tab
Yes this was working in my mintlify dev env as expected 
cc:
@johnson-mage 
https://github.com/user-attachments/assets/e14c667b-12f9-439a-a314-7e537e5b5fa4

first pro features commit

---

docs/docs.json
docs/integrations/compute/spark-pro.mdx
docs/integrations/databases/Iceberg.mdx

Add pyspark with iceberg doc.
cc:

[xy] Add pyspark with iceberg doc.

---

docs/guides/developer-ux/visual-studio-code.mdx

[xy] Update VSCode doc.

---

docs/production/deploying-to-cloud/secrets/GCP.mdx

[xy] Update GCP secret doc.

---

docs/production/mage/pro.mdx

[xy] Fix typo in the doc.

---

docs/ai/sidekick/index.mdx

[td] Docs on enabling RAG

---

docs/ai/sidekick/index.mdx

[td] AI docs

---

docs/ai/sidekick/index.mdx

[xy] Update AI sidekick doc

---

docs/data-integrations/sources/dynamodb.mdx
docs/docs.json
docs/integrations/databases/Athena.mdx
docs/integrations/databases/S3.mdx

Update docs for AWS services.
cc:

[xy] Update docs for AWS services.

---

docs/docs.json

changed the github link to https://github.com/mage-ai/mage-ai 
Tested in mintlify dev env.
cc:

github link change in navbar

---

docs/docs.json
docs/migrations/airflow-to-mage-pro.mdx
docs/production/mage/pro.mdx

Add airflow migration guide.
cc:

[xy] Add airflow migration guide.

---

docs/guides/data-sync/cicd-workflow.mdx

CICD workflow doc 
Tested in mintlify dev env all links working correctly
cc:
@johnson-mage

[cf] cicd workflow doc commit

---

docs/docs.json
docs/guides/data-sync/git-terminal.mdx

git terminal docs update
tested in mintlify dev env pictures attached
cc:

[cf] git terminal docs update

---

docs/integrations/text-editor.mdx
docs/orchestration/pipeline-runs/retrying-block-runs.mdx

Update pipeline metadata.yaml doc. Add more fields
cc:

[xy] Update pipeline metadata.yaml doc.

---

docs/observability/testing/data-validation.mdx

[td] Update docs

---

docs/docs.json
docs/migrations/dbt-to-mage-pro.mdx

dbt to mage pro migration docs
tested in mintlify dev env
cc:

[cf] dbt to mage pro migration docs

---

docs/guides/blocks/dynamic-blocks-2.mdx

added the "Enabling stream mode" section 
Tested in mintlify dev env.
cc:

[cf] enabling-stream-mode-dynamic-blocks

---

docs/docs.json
docs/migrations/airbyte-to-mage-pro.mdx

Add airbyte to Mage migration doc.
cc:

[xy] Add airbyte to Mage migration doc.

---

docs/pro-architecture/saas.mdx

Added whitelisted ip addresses to the saas architecture doc
Tested in mintlify dev env
cc:

[cf] add whitelisted ip range to saas architecture doc

---

docs/observability/alerting/alerting-discord.mdx
docs/observability/alerting/alerting-email.mdx
docs/observability/alerting/alerting-slack.mdx
docs/observability/alerting/alerting-teams.mdx
docs/observability/alerting/alerting-telegram.mdx

- See title. Additional variables supported for message templates for notifications in Mage Pro.
- Checked Mintlify page
cc:

[jk] Update docs for notification message templates

---

docs/data-integrations/sources/api.mdx

Update doc for API source.
cc:

[xy] Update doc for API source.

---

docs/data-integrations/destinations/redshift.mdx

Improve Redshift destination doc.
cc:

[xy] Improve Redshift destination doc.

---

docs/docs.json
docs/migrations/airbyte-to-mage-pro.mdx
docs/migrations/airflow-to-mage-pro.mdx
docs/migrations/estuary-to-mage-pro.mdx
docs/migrations/fivetran-to-mage-pro.mdx

[xy] Add new migration docs.

---

docs/guides/developer-ux/workspaces.mdx
docs/integrations/databases/PostgreSQL.mdx
docs/production/executors/k8.mdx

This pull request updates documentation for Mage Pro workspaces, PostgreSQL integration, and the Kubernetes executor. The main focus is to clarify environment variable inheritance, enhance Kubernetes executor configuration instructions, and better document Pro-only features for PostgreSQL.
**Environment Variable Inheritance in Workspaces:**
- Major rewrite of the workspace environment variable inheritance section in `workspaces.mdx`:
- Clarifies the use of `INHERIT_ENV_VARS` and introduces `USER_DEFINED_VARS` for both Managed Cloud and Self-hosted Mage Pro.
- Adds support for variable inheritance by pattern (wildcard/regex) and per-workspace environment using `USER_DEFINED_VARS__ENV__{env_value}`.
**Kubernetes Executor Documentation Improvements:**
- Expands and reorganizes the Kubernetes …

[xy] Improve docs.

---

docs/ai/blocks.mdx
docs/docs.json

[td] AI Blocks docs

---

docs/ai/blocks.mdx

Fix AI blocks YouTube embed link

[td] Fix AI blocks YouTube embed link

---

docs/development/troubleshooting.mdx
docs/docs.json
docs/guides/developer-ux/code-editor.mdx

This pull request adds guidance on safe pipeline editing and collaboration practices, and improves the discoverability of troubleshooting documentation. The main changes include new warnings and best practices for editing pipelines, updates to documentation navigation, and a minor metadata addition.
**Documentation improvements:**
* Added a new section in `code-editor.mdx` with warnings about editing the same pipeline in multiple tabs, tips for safe editing, and best practices for team collaboration using Workspace mode.
* Added the `development/troubleshooting` page to the Quickstart group in `docs.json`, making troubleshooting information more accessible in the documentation sidebar.
**Metadata update:**
* Added an `icon: "question"` metadata field to `troubleshooting.mdx` for improved …

[xy] Improve docs for pipeline editing

---

mage_ai/data_preparation/executors/pipeline_executor.py

Fix asyncio in pipeline executor.
This pull request refactors the pipeline execution logic in `pipeline_executor.py` to better support both synchronous and asynchronous contexts. The main change is the introduction of a coroutine for pipeline execution, which improves compatibility with async workflows and prevents errors when running within an existing event loop.
Async execution improvements:
* Refactored the `execute` method to define an internal async function `_execute_task`, which is then executed using either `asyncio.create_task` and `run_until_complete` if an event loop is running, or `asyncio.run` otherwise. This ensures proper handling in both sync and async contexts.
* Changed direct calls to `asyncio.run(self.pipeline.execute(...))` and `asyncio.run(self.__run_blocks(...))` …

[xy] Fix asyncio in pipeline executor.

---

.github/workflows/publish_to_pypi.yml

Update python version in pypi action.
cc:

[xy] Update python version in pypi action.

---

mage_ai/settings/server.py

Set default value of user authentication to True.
cc:

[CVE-2025-2129] Set default value of user authentication to True.

---

mage_ai/data_preparation/models/block/outputs.py

Fix serializing polars dataframe for display.
cc:

[xy] Fix serializing polars dataframe for display.

---

docs/design/blocks/callbacks.mdx
docs/getting-started/setup.mdx
docs/guides/blocks/sql-blocks.mdx
docs/pro-architecture/architecture-overview.mdx
docs/production/authentication/overview.mdx

This pull request updates documentation across several areas to clarify new features, improve technical explanations, and enhance usability. The most significant changes include updates to Mage Pro deployment architectures, user authentication defaults, new callback functionality, dynamic SQL block configuration, and improved onboarding instructions.
**Deployment & Authentication Updates:**
* Expanded the Mage Pro architecture overview to clearly describe the four deployment options (SaaS, Hybrid Cloud, Private Cloud, On-Premises), including their benefits and considerations. This helps teams select the best deployment for their needs.
* Updated authentication documentation to reflect that user authentication is now enabled by default in Mage OSS v0.9.78+ and Mage Pro, with instructions …

[xy] Update multiple docs

---

docs/orchestration/triggers/configure-triggers-in-code.mdx

Update triggers doc to clarify trigger deletion and envs.
cc:

[xy] Update triggers doc to clarify trigger deletion and envs.

---

docs/docs.json
docs/extensibility/pro-api-reference/workspaces/update-workspace.mdx

Add workspace update API doc.
cc:

[xy] Add workspace update API doc.

---

docs/orchestration/triggers/configure-triggers-in-code.mdx

fixed lin to advanced settings
mintlify dev env
cc:
https://github.com/user-attachments/assets/0cac455c-8750-4990-8673-6393063471fd

[cf] fix-advance-settings-link-congigure-triggers-in-code

---

docs/data-integrations/destinations/bigquery.mdx
docs/design/data-loading.mdx
docs/development/io_config.mdx
docs/development/io_config_setup.mdx
docs/docs.json
docs/guides/blocks/sql-blocks.mdx
docs/guides/data-sync/version-control-guide.mdx
docs/integrations/databases/SQLite.mdx

This pull request makes substantial improvements to the Mage documentation, focusing on clarifying and expanding instructions for configuring data integrations, IO Config setup, and version control in Mage Pro. The changes provide more detailed guidance on credential management, introduce advanced features for Mage Pro, and enhance troubleshooting and best practices sections for users. Additionally, new integrations are documented and several UI/UX descriptions are updated for clarity.
* Added detailed instructions and examples for setting up `io_config.yaml`, including variable interpolation and secret management across environment variables, Mage secrets, AWS, Azure, GCP, and files. Expanded best practices and troubleshooting sections for common issues. …

[xy] Improve docs
