mage-ai/mage-ai

mage_ai/__init__.py
mage_ai/server/app.py
mage_ai/server/constants.py

Show UI in iframe after launching server.
tested locally
cc:

[xy] Show UI in iframe.

---

mage_ai/server/data/models.py

Update sample data response.
tested locally
cc:

[xy] Update sample data response.

---

mage_ai/server/app.py
requirements.txt

Enable CORS so that we can access the backend endpoints from the frontend.
tested locally
cc:

[dy] Enable CORS for Flask app

---

mage_ai/frontend/pages/datasets/[slug]/features/index.tsx

- see above
- update styling to be closer to Figma
This PR will not work until Nathaniel's bugfix (#73) is merged as well, since that affects the dataset view used to get to this page.
In addition, the bug where NextJS's router doesn't allow direct paths affects this page too, so accessing /datasets/[id]/features directly does not work and causes an error. If there's a fix please let me know
cc: @johnson-mage @nathaniel-mage

[sp] column view backend integration

---

setup.py

Update setup packages. Install mage_ai as a whole package instead of installing sub packages.
tested locally
cc:

[xy] Update setup packages.

---

MANIFEST.in

Include frontend_dist in package.
tested locally
cc:

[xy] Include frontend_dist in package.

---

mage_ai/server/app.py
mage_ai/server/data/models.py

Support filtering sample data by column
tested locally
cc: @nathaniel-mage

[xy] Filter sample data by column.

---

README.md

Add initial README. Will fill in more content in later PR.
n/a
cc:

[xy] Add initial README

---

mage_ai/__init__.py
mage_ai/server/app.py
mage_ai/server/data/base.py
mage_ai/server/data/models.py

Some refinements on backend app.
* Return feature set in reverse order
* Return head data for sample data
* Disable console messages in Flask server
tested locally
cc:

[xy] Some refinements on backend app.

---

mage_ai/data_cleaner/analysis/calculator.py
mage_ai/data_cleaner/analysis/charts.py
mage_ai/data_cleaner/data_cleaner.py
mage_ai/data_cleaner/shared/logger.py
mage_ai/data_cleaner/shared/utils.py
mage_ai/data_cleaner/statistics/calculator.py
mage_ai/server/app.py

Improve the performance of analysis calculator by reducing the duplicate code of cleaning series.
This PR also updates the feature sets endpoint to only return valid feature sets.
tested locally with a dataframe with 100k rows and 27 columns.
Original time of analysis calculator
After optimization
cc:

[xy] Some improvements on performance

---

mage_ai/server/data/models.py

Reduce the time of fetching 40 feature sets from 4s to 40ms.
* Not load data when initializing feature set class.
tested locally
cc:

[xy] Reduce the time of fetching feature sets.

---

README.md
requirements.txt

Add installation, getting started, usage, and community-building section in docs
Uhh i did not 😳

[fk] update docs

---

mage_ai/frontend/components/ActionForm/actions.ts
mage_ai/frontend/components/ActionForm/constants.ts
mage_ai/frontend/components/ActionForm/index.style.tsx
mage_ai/frontend/components/ActionForm/index.tsx
mage_ai/frontend/components/ActionForm/utils.ts
mage_ai/frontend/interfaces/TransformerActionType.tsx
mage_ai/frontend/oracle/elements/Divider/index.tsx
mage_ai/frontend/oracle/elements/Text/index.tsx
mage_ai/frontend/oracle/icons/BaseIcon.tsx
mage_ai/frontend/oracle/styles/themes/light.ts
mage_ai/frontend/pages/datasets/[slug].tsx
mage_ai/frontend/pages/datasets/index.tsx
requirements.txt
titanic_survival.csv

[td] Add config for forms and component for forms

---

mage_ai/server/data/models.py

Filter suggestions by column name when fetching feature set data with column filter.
tested locally
cc:

[xy] Filter suggestions by column name.

---

mage_ai/frontend/components/ActionForm/actions.ts
mage_ai/frontend/components/ActionForm/constants.ts
mage_ai/frontend/components/ActionForm/index.tsx
mage_ai/frontend/pages/datasets/[slug].tsx
mage_ai/frontend/pages/datasets/[slug]/features/[column].tsx

[td] Add action form for single column

---

mage_ai/frontend/oracle/components/Menu/MenuContainer.tsx
mage_ai/frontend/oracle/components/Menu/index.tsx
mage_ai/frontend/oracle/components/Tabs/index.tsx
mage_ai/frontend/oracle/elements/Link/index.tsx
mage_ai/frontend/pages/datasets/[slug].tsx
mage_ai/frontend/stories/oracle/components/Menu.stories.tsx
mage_ai/frontend/stories/oracle/components/Tabs.stories.tsx

- Added Menu component.
- Added optional `actionEl` prop to Tabs component.
Menu component:
Tabs with action:
cc:

[jk] Oracle Menu component

---

README.md
docs/faq/README.md
docs/tutorials/README.md
docs/tutorials/quick-start.md
mage_ai/frontend/components/ActionForm/actions.ts
mage_ai/frontend/components/ActionForm/constants.ts
mage_ai/frontend/components/ActionForm/index.tsx

[td] Fix line errors and update README

---

mage_ai/frontend/api/utils/url.ts

- See title.
- Local. Need to test in google colab.

[jk] Update host config

---

mage_ai/frontend/components/suggestions/SuggestionsList.tsx
mage_ai/frontend/pages/datasets/[slug].tsx

- fix pipeline ID for PUT request
- remove unnecessary React state
There are still issues with action's state, and the API payload does not automatically refresh, meaning that the actions list is still governed by React state, not from the backend. I'm working on fixing the suggestions component so that the actions list pulls directly from the API payload.

[sp] rework suggestions

---

mage_ai/data_cleaner/statistics/calculator.py
mage_ai/tests/data_cleaner/statistics/test_calculator.py

Add unit tests to stats calculator.
unit test
cc:

[xy] Add unit tests to stats calculator.

---

mage_ai/frontend/oracle/components/Accordion/AccordionPanel.tsx
mage_ai/frontend/oracle/components/Accordion/index.tsx

[td] Fix accordion styles

---

.circleci/config.yml

Change SSH key to fix permissions error.
cc:

[dy] Change fingerprint

---

mage_ai/server/app.py

Remove unnecessary comment.
n/a
cc:

[xy] Remove unnecessary comment.

---

mage_ai/data_cleaner/cleaning_rules/remove_outliers.py
mage_ai/data_cleaner/pipelines/base.py
mage_ai/data_cleaner/statistics/calculator.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_outliers.py

Add remove outliers cleaning rule. Suggest to filter outliers with a upper bound and lower bound.
tested locally
added unit test
cc:

[xy] Add remove outliers cleaning rule.

---

mage_ai/data_cleaner/cleaning_rules/remove_outliers.py
mage_ai/data_cleaner/statistics/calculator.py
mage_ai/server/app.py
mage_ai/server/data/base.py
mage_ai/server/data/models.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_outliers.py
mage_ai/tests/data_cleaner/statistics/test_calculator.py

* Add total value count to statistics.
* Update the title of remove_outliers.
* Only update pipeline metadata when setting feature_set_id
* Set default value of pipeline action to be an empty array
unit tests
cc:

[xy] Some refinements on backend

---

mage_ai/frontend/components/constants.ts
mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
mage_ai/frontend/interfaces/ActionType.ts
mage_ai/frontend/interfaces/FeatureSetType.ts
mage_ai/frontend/interfaces/FeatureType.tsx
mage_ai/frontend/interfaces/SuggestionType.ts
mage_ai/frontend/pages/datasets/[slug]/constants.ts
mage_ai/frontend/pages/datasets/[slug]/index.tsx

- Add various interfaces.
N/A
cc:

[jk] Add feature set interfaces

---

mage_ai/data_cleaner/transformer_actions/utils.py
mage_ai/server/app.py

Auto generate action titles.
tested locally
cc:

[xy] Auto generate action titles.

---

mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/suggestions/SuggestionRow.tsx
mage_ai/frontend/components/suggestions/index.tsx
mage_ai/frontend/interfaces/TransformerActionType.tsx
mage_ai/frontend/utils/models/featureSet.ts

[td] Delete action

---

mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/datasets/overview/utils.ts
mage_ai/frontend/oracle/components/Tabs/index.tsx

[td] Use tab from URL

---

mage_ai/server/data/base.py

Ignore non number folder name.
tested locally
cc:

[xy] Ignore non number folder name.

---

mage_ai/frontend/components/PageBreadcrumbs/index.tsx
mage_ai/frontend/components/suggestions/SuggestionRow.tsx

[td] Fix page breadcrumbs

---

mage_ai/frontend/components/datasets/columns/ColumnDetail.tsx
mage_ai/frontend/components/datasets/columns/ColumnList.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/oracle/components/Layout/index.tsx
mage_ai/frontend/oracle/components/Table/index.style.tsx
mage_ai/frontend/pages/datasets/index.tsx

- Fix table corner clipping
- Add bottom padding to column detail page
- Update "skewed" to "skewness"

[jk] Styling fixes

---

mage_ai/__init__.py
mage_ai/data_cleaner/pipelines/base.py
mage_ai/server/app.py

Support run pipeline with pipeline id.
tested locally
cc:

[xy] Support run pipeline with pipeline id.

---

mage_ai/frontend/components/datasets/columns/ColumnDetail.tsx
mage_ai/frontend/components/datasets/columns/ColumnList.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/pages/datasets/[...slug].tsx

- Make API request for feature set once, and pass `featureSet` to each subpage .
- Local

[jk] Page dataset fetching

---

mage_ai/frontend/components/datasets/FeatureProfiles.tsx
mage_ai/frontend/components/datasets/Insights/Overview.tsx
mage_ai/frontend/components/datasets/columns/ColumnDetail.tsx
mage_ai/frontend/components/datasets/overview/index.tsx

[dy] Fix some bug bash issues

---

mage_ai/data_cleaner/statistics/calculator.py

Return sample outliers in response.
tested locally
outliers
total_invalid_value_count
cc:

[xy] Return sample outliers in response.

---

mage_ai/data_cleaner/analysis/charts.py
mage_ai/data_cleaner/transformer_actions/base.py
mage_ai/frontend/components/ActionForm/index.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/interfaces/ActionPayloadType.ts

[td] Pass in action variables when saving action

---

mage_ai/frontend/api/index.ts
mage_ai/frontend/api/utils/response.ts
mage_ai/frontend/api/utils/url.ts
mage_ai/frontend/components/datasets/columns/ColumnDetail.tsx
mage_ai/frontend/hocs/ClientOnly.tsx
mage_ai/frontend/oracle/components/Breadcrumbs/Breadcrumb.tsx
mage_ai/frontend/oracle/components/Table/SimpleDataTable.tsx
mage_ai/frontend/oracle/elements/Link/index.tsx
mage_ai/frontend/oracle/elements/Text/index.tsx
mage_ai/frontend/tsconfig.json

- Fetch individual column data in Column Detail view for specific suggestions and row data.
- Local
cc:
@tommydangerous @shrey-mage @nathaniel-mage

[jk] Fetch column data

---

mage_ai/frontend/api/utils/use.ts
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/pages/datasets/[...slug].tsx

[td] Use mutate to fetch data after PUT

---

mage_ai/frontend/components/suggestions/SuggestionRow.tsx

[td] Show options if no message

---

mage_ai/data_cleaner/pipelines/base.py

Prioritize removing columns cleaning rules.
n/a
cc:

[xy] Prioritize removing columns cleaning rules.

---

mage_ai/server/data/base.py

Added back in deleted sorting code for getting all datasets
cc:

[sk] Small bug fix after deleted code

---

mage_ai/frontend/components/datasets/Insights/Overview.tsx
mage_ai/frontend/oracle/components/Table/SimpleDataTable.tsx
mage_ai/frontend/oracle/components/Table/index.style.tsx

[td] Remove borders from nested tables

---

mage_ai/frontend/components/charts/HeatMap.tsx
mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
mage_ai/frontend/components/datasets/Insights/Overview.tsx
mage_ai/frontend/components/datasets/columns/ColumnDetail.tsx
mage_ai/frontend/oracle/components/Table/index.style.tsx
mage_ai/frontend/pages/datasets/index.tsx

[td] Add correlations to column detail

---

mage_ai/frontend/components/ActionForm/constants.ts
mage_ai/frontend/components/ActionForm/index.tsx
mage_ai/frontend/components/suggestions/SuggestionRow.tsx
mage_ai/frontend/next.config.js
mage_ai/frontend/oracle/styles/fonts/sizes.ts
mage_ai/frontend/package.json
mage_ai/frontend/yarn.lock

[td] Filter action should allow user to write code

---

mage_ai/data_cleaner/cleaning_rules/clean_column_names.py
mage_ai/data_cleaner/cleaning_rules/impute_values.py
mage_ai/data_cleaner/cleaning_rules/reformat_values.py
mage_ai/data_cleaner/cleaning_rules/remove_columns_with_single_value.py
mage_ai/data_cleaner/cleaning_rules/remove_duplicate_rows.py
mage_ai/data_cleaner/cleaning_rules/remove_outliers.py
mage_ai/tests/data_cleaner/cleaning_rules/test_clean_column_names.py
mage_ai/tests/data_cleaner/cleaning_rules/test_impute_values.py
mage_ai/tests/data_cleaner/cleaning_rules/test_reformat_values.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_columns_with_single_value.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_duplicate_rows.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_outliers.py

Updated the cleaning suggestion messages to fix grammatical errors and be more explanatory & precise. Some of the cleaning suggestion files and unit tests were also reformatted during this update (leading to an unfortunately fairly messy git blame). 
For ease of access I've directly listed all the messages I've updated below:
- **Clean Column Names**: "The following columns have unclean naming conventions: [...]. Cleaning these names to be lowercase and alphanumeric can improve ease of dataset access and reduce security risks."
- **Average Imputation**: "The following columns have null-valued entries and the distribution of remaining values is approximately symmetric: [...]. Fill the null values in each of these columns with their average value."
- **Constant Imputation**: "The following …

[sk] Update cleaning suggestions messages

---

mage_ai/data_cleaner/analysis/calculator.py
mage_ai/data_cleaner/pipelines/base.py
mage_ai/data_cleaner/shared/utils.py
mage_ai/server/data/models.py

* Not calculate histogram for bool type (pandas is_numeric_type method returns true for bool type)
* Catch the exception of each individual column analysis calculation
* Fix the serialization of the sample data datetime column
tested locally
cc:

[xy] Some fixes on analysis calculator

---

mage_ai/frontend/components/ActionForm/actions.ts
mage_ai/frontend/components/ActionForm/index.tsx

[td] Add custom code form

---

mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/server/app.py

[td] Show full stack trace when 500 error

---

requirements.txt

Update package version of numpy and six to fix package error and warning in google colab. 
tested locally
to be tested in google colab after the PR is merged.
cc:

[xy] Update package version of numpy and six.

---

mage_ai/server/data/base.py

Fix dir not exist exception.
tested locally
cc:

[xy] Fix dir not exist exception.

---

mage_ai/frontend/components/ActionForm/index.style.tsx
mage_ai/frontend/components/ActionForm/index.tsx
mage_ai/frontend/components/charts/LineSeries.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/suggestions/SuggestionRow.tsx
mage_ai/frontend/components/suggestions/index.tsx
mage_ai/frontend/oracle/components/Accordion/AccordionPanel.tsx
mage_ai/frontend/oracle/components/FlexContainer.tsx
mage_ai/frontend/yarn.lock

- add scrollbar & update formatting for suggested actions
- add "View Code" button to edit suggested actions
- update state for suggested actions & custom menu accordingly
- fix hydration issue for tabs on dataset overview page

[sp] add editable actions & revamp custom actions

---

mage_ai/frontend/components/datasets/constants.ts
mage_ai/frontend/components/datasets/overview/utils.ts

- Changes the wording of the message: values -> rows, features -> columns
- Updates the formatting to not display e+...
- Refactors code to use the utils functions.
- Update payload keys to use totals instead of average.
cc:
@johnson-mage @dy46

[nt]  dataset metrics formating

---

mage_ai/data_cleaner/analysis/calculator.py

Calculate correlation for bool type.
tested locally
cc:

[xy] Calculate correlation for bool type.

---

mage_ai/frontend/components/charts/LineSeries.tsx
mage_ai/frontend/components/charts/ScatterPlot.tsx
mage_ai/frontend/components/datasets/Insights/Overview.tsx
mage_ai/frontend/package.json
mage_ai/frontend/yarn.lock

Add scatter plot to visualization overview page
tested locally
cc:

[dy] Add scatterplot

---

mage_ai/frontend/components/ActionForm/ActionDropdown/index.tsx
mage_ai/frontend/components/ActionForm/index.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/suggestions/SuggestionRow.tsx
mage_ai/frontend/components/suggestions/index.tsx
mage_ai/frontend/interfaces/FeatureSetType.ts

- The `SuggestionRow` component had a `columns` prop which had inconsistent typing.
- Local
cc:
@shrey-mage please check to make sure this didn't break any of your code

[jk] Suggestions props refactor

---

mage_ai/frontend/components/charts/BarGraphHorizontal.tsx
mage_ai/frontend/components/charts/Histogram.tsx
mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
mage_ai/frontend/components/datasets/Insights/utils/data.ts

* Fix tooltip on histogram
* Fix labels on horizontal bar chart
local test
cc:

[dy] Fix some bugs

---

mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/datasets/overview/utils.ts

- Undo change where Flex was modified
- Improvements to precision of progress bar
Went to localhost and pulled up progress bar.
cc:
@johnson-mage

[nt] Add loose typing and add back proper flex values

---

mage_ai/frontend/components/ActionForm/ActionDropdown/index.tsx
mage_ai/frontend/components/datasets/columns/ColumnDetail.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/interfaces/ActionType.ts
mage_ai/frontend/interfaces/FeatureSetType.ts
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/interfaces/SuggestionType.ts
mage_ai/frontend/interfaces/TransformerActionType.ts

- Integrate new actions performed on individual columns.
- Certain actions (e.g. reformat column name / remove column) need to be refined in terms of redirecting the user after the action is applied and refetching data since the feature id mappings change.

[jk] Column-specific actions

---

mage_ai/server/data/base.py
mage_ai/server/data/models.py

Fix writing to parquet with mixed data types. Convert all data types to the same type in each column.
tested locally
cc:

[xy] Fix writing to parquet with mixed data types.

---

mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
mage_ai/frontend/components/datasets/Insights/Overview.tsx
mage_ai/frontend/components/datasets/overview/index.style.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/oracle/components/Layout/index.tsx
mage_ai/frontend/oracle/components/Table/BaseTable.tsx
mage_ai/frontend/oracle/components/Table/Table.style.tsx
mage_ai/frontend/oracle/components/Table/helpers.tsx

[td] Change layout of dataset slug

---

mage_ai/frontend/oracle/components/Table/BaseTable.tsx

[td] Show boolean and nulls

---

mage_ai/data_cleaner/column_type_detector.py
mage_ai/data_cleaner/shared/utils.py
mage_ai/tests/data_cleaner/test_column_type_detector.py

Updated column type detection to recognize phone numbers that are formatted as integers or floats. To do this, both integers and floats are also checked to see if they fit the criteria of a phone number:
- Value is in $[10^9, 10^{12})$ - the range of expected phone numbers
- Value has no decimal places (its floor is equal to itself)
- Column name contains 'phone'
This involves updates how integers and floats are checked, both as raw types and in string form. In addition, `clean_series` was updated to convert numerical types identified as phone numbers to strings (with truncation of decimal places)
Unit tests were written locally to check for correctness, alongside running the code on sample datasets.
cc:

[sk] Update phone number detection

---

mage_ai/frontend/components/datasets/constants.ts
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/datasets/overview/utils.ts

- Adds a new parameter to the parse (needs column types to get number of columns)
- Handles edge case of 0 rows or cols, but 0 rows is more likely.
Launched on Localhost 
cc:
@johnson-mage

[nt] Add calculations for total cells and calculate percentages

---

mage_ai/server/data/base.py

Fix writing to parquet file again. Not convert NaN value to string.
tested locally
cc:

[xy] Not convert NaN value to string.

---

mage_ai/frontend/components/charts/HeatMap.tsx

[td] Fix heatmap

---

mage_ai/frontend/components/suggestions/index.tsx
mage_ai/frontend/oracle/components/Layout/MultiColumn.style.tsx
mage_ai/frontend/oracle/components/Layout/MultiColumn.tsx

[td] Added padding to multicolumn layout

---

mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/oracle/components/Table/Table.style.tsx

[td] Move action form to the side bar

---

mage_ai/frontend/components/ActionForm/index.style.tsx
mage_ai/frontend/components/datasets/columns/ColumnDetail.tsx
mage_ai/frontend/components/datasets/overview/index.style.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/suggestions/index.tsx
mage_ai/frontend/interfaces/FeatureSetType.ts
mage_ai/frontend/oracle/components/Layout/MultiColumn.style.tsx
mage_ai/frontend/oracle/components/Layout/index.tsx

- Add column-specific suggestions to Column Details page.
- Updated layout of Column Details page to position suggestions on the right side panel.

[jk] Column suggestions

---

mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/oracle/components/Layout/MultiColumn.style.tsx
mage_ai/frontend/oracle/components/Layout/MultiColumn.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx

[td] Improve tabs on dataset overview

---

mage_ai/server/data/models.py

Increase sample size to 200.
tested locally
cc:

[xy] Increase sample size.

---

mage_ai/data_cleaner/cleaning_rules/clean_column_names.py
mage_ai/data_cleaner/cleaning_rules/impute_values.py
mage_ai/data_cleaner/cleaning_rules/reformat_values.py
mage_ai/data_cleaner/cleaning_rules/remove_collinear_columns.py
mage_ai/data_cleaner/cleaning_rules/remove_columns_with_high_empty_rate.py
mage_ai/data_cleaner/cleaning_rules/remove_columns_with_single_value.py
mage_ai/data_cleaner/cleaning_rules/remove_duplicate_rows.py
mage_ai/data_cleaner/cleaning_rules/remove_outliers.py
mage_ai/tests/data_cleaner/cleaning_rules/test_clean_column_names.py
mage_ai/tests/data_cleaner/cleaning_rules/test_impute_values.py
mage_ai/tests/data_cleaner/cleaning_rules/test_reformat_values.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_collinear_columns.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_columns_with_high_empty_rate.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_columns_with_single_value.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_duplicate_rows.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_outliers.py

Changed cleaning suggestion messages to be less verbose so they are easier to read on the front end. Here is an example of the new cleaning suggestion messages:
Changes were tested using the interface as well as unit tests
cc:

[sk] Updated suggestions messages to be less verbose

---

mage_ai/server/data/models.py

Not always write to metadata.
tested locally
cc:

[xy] Not always write to metadata.

---

mage_ai/frontend/api/index.ts
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/suggestions/index.tsx
mage_ai/frontend/oracle/components/Layout/MultiColumn.tsx
mage_ai/frontend/oracle/components/Table/BaseTable.tsx
mage_ai/frontend/oracle/components/Table/index.style.tsx
mage_ai/frontend/pages/datasets/[...slug].tsx
mage_ai/frontend/utils/url.ts
mage_ai/server/app.py
mage_ai/server/data/models.py

[td] Load data for single column

---

mage_ai/frontend/components/datasets/overview/index.tsx

[td] Add back all column charts

---

mage_ai/frontend/components/datasets/columns/ColumnDetail.tsx
mage_ai/frontend/components/datasets/columns/ColumnReports.tsx
mage_ai/frontend/oracle/components/Table/Cell.tsx
mage_ai/frontend/oracle/components/Table/SimpleDataTable.tsx

[jk] Column outliers

---

mage_ai/frontend/components/charts/BarGraphHorizontal.tsx
mage_ai/frontend/components/charts/Histogram.tsx
mage_ai/frontend/components/charts/LineSeries.tsx
mage_ai/frontend/components/charts/ScatterPlot.tsx
mage_ai/frontend/components/charts/utils/label.ts
mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
mage_ai/frontend/components/datasets/Insights/Overview.tsx

Fixed a variety of visualization bugs
* Change text color for axis labels
* Fix number of rows by date chart width issue
* Fix missing lines in line series chart in column analysis page
* Show pie chart for boolean values
tested locally
cc:

[dy] Fix visualization bugs

---

mage_ai/frontend/components/datasets/FeatureProfiles.tsx

- fix rate calculation to use row count instead of column count
- adjust order of features list

[sp] adjust feature profiles calculation and order

---

mage_ai/frontend/components/ActionForm/index.style.tsx
mage_ai/frontend/components/ActionForm/index.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/suggestions/index.tsx

[td] optional shadow

---

mage_ai/data_cleaner/cleaning_rules/remove_outliers.py
mage_ai/data_cleaner/pipelines/base.py
mage_ai/server/data/models.py

Not show duplicate remove outlier suggestions.
tested locally
cc:

[xy] Not show duplicate remove outlier suggestions.

---

mage_ai/frontend/components/ActionForm/actions.ts
mage_ai/frontend/components/ActionForm/index.tsx
mage_ai/frontend/components/ActionForm/utils.ts
mage_ai/frontend/oracle/components/Table/BaseTable.tsx

[td] Add descriptions to all action forms

---

mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/suggestions/SuggestionRow.tsx
mage_ai/frontend/components/suggestions/index.tsx
mage_ai/frontend/oracle/styles/themes/light.ts

[td] Show loading progress

---

mage_ai/server/app.py
mage_ai/server/data/base.py
mage_ai/server/data/models.py

Store versioned snapshots of the feature set response.
Use endpoint `/feature_sets/[id]/versions/[version]` to get snapshots.
tested locally
cc:

[xy] Store versioned snapshots.

---

mage_ai/frontend/components/charts/ScatterPlot.tsx

Fix the scatter plot periodically crashing.
local testing
cc:

[dy] Try fix crashing

---

mage_ai/server/data/base.py

Fix the type of parquet column.
tested locally
cc:

[xy] Fix the type of parquet column.

---

mage_ai/data_cleaner/statistics/calculator.py

Sometimes, stats json serialization failed because np.NaN is in the index. This PR fixes the issue.
tested locally
cc:

[xy] Fix stats json serialization

---

mage_ai/frontend/components/datasets/columns/ColumnReports.tsx
mage_ai/frontend/oracle/components/RowDataTable/index.style.ts
mage_ai/frontend/oracle/components/RowDataTable/index.tsx
mage_ai/frontend/oracle/components/Table/index.style.tsx
mage_ai/frontend/utils/models/featureSet.ts

- Add outliers table to Column Reports tab.
cc:
@nathaniel-mage Please rebase master and check for conflicts.

[jk] Column outliers table

---

mage_ai/data_cleaner/column_type_detector.py
mage_ai/data_cleaner/statistics/calculator.py
mage_ai/tests/data_cleaner/test_column_type_detector.py

Return invalid values in response.
tested locally. unit test

[xy] Return invalid values in response.

---

mage_ai/data_cleaner/pipelines/base.py
mage_ai/server/data/models.py

Not show outliers in stats if outlier removal suggestion was applied.
tested locally
cc:

[xy] Not show outliers if outlier removal suggestion was applied.

---

README.md
mage_ai/__init__.py

Combine cleaning with uuid and path into one method.
tested locally
cc:

[xy] Combine cleaning with uuid and path into one method.

---

mage_ai/frontend/components/PageBreadcrumbs/index.tsx
mage_ai/frontend/components/datasets/overview/index.tsx

- Update breadcrumbs to include column name and allow user to navigate back to dataset view.
cc:

[jk] Add column name to breadcrumbs

---

mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/oracle/components/Table/Cell.tsx
mage_ai/frontend/oracle/components/Table/SimpleDataTable.tsx
mage_ai/frontend/utils/array.ts
mage_ai/frontend/utils/string.ts

- bolds and highlights poor quality metrics in red if above/below the warning threshold
- add modular way to set warnings for `<SimpleDataTable>`
[bad_product_data.csv](https://github.com/mage-ai/mage-ai/files/8857229/bad_product_data.csv)

[sp] add warnings for quality metrics & statistics

---

mage_ai/data_cleaner/statistics/calculator.py

Fix outlier samples, returning actually outliers instead of z-scores.
tested locally
cc:

[xy] Fix outlier samples.

---

mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/oracle/components/Layout/MultiColumn.style.tsx
mage_ai/frontend/utils/usePrevious.ts

[td] Fix table widths

---

mage_ai/frontend/components/DataTable/index.tsx

[td] Stretch column full width

---

mage_ai/server/data/models.py

Catch version write failure.
tested locally
cc:

[xy] Catch version write failure.

---

mage_ai/frontend/components/datasets/columns/ColumnReports.tsx
mage_ai/frontend/utils/models/featureSet.ts

[jk] Add invalid values table

---

mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/charts/BarGraphHorizontal.tsx
mage_ai/frontend/components/charts/Histogram.tsx
mage_ai/frontend/components/charts/PieChart.tsx
mage_ai/frontend/components/datasets/overview/index.tsx

[td] Add charts into column header

---

mage_ai/data_cleaner/analysis/calculator.py
mage_ai/data_cleaner/analysis/charts.py

Reduce the analysis calculator time by optimizing timeseries calculation.
Timeseries calculation was not efficient due to duplicate calculation on buckets splitting and dataframe filtering. This PR changes to batch calculating timeseries charts.
tested locally on a feature set with 10k rows and 2 datetime columns.
Tested 
*  Original time (Use multithread): 4.879s
*  Not use multithread: 4.5s
*  Not convert dateime: 4.1s
*  Not calculate value counts: 3917ms
*  Use mean instead of sum / len: 3895ms
*  Batch calculate timeseries: 1503ms
cc:

[xy] Improve perf by batch calculating timeseries charts.

---

mage_ai/frontend/components/ActionForm/ActionDropdown/index.tsx
mage_ai/frontend/components/ActionForm/ActionMenu/index.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/oracle/components/ClickOutside/index.tsx
mage_ai/frontend/oracle/components/Menu/MenuContainer.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx

[jk] Improve  new action button

---

mage_ai/frontend/components/datasets/Detail/index.tsx
mage_ai/frontend/components/datasets/Export/index.tsx
mage_ai/frontend/oracle/components/PanelOld/PanelRoot.tsx
mage_ai/frontend/oracle/components/PanelOld/index.tsx
mage_ai/frontend/oracle/elements/Headline/index.tsx
mage_ai/frontend/oracle/styles/fonts/sizes.ts
mage_ai/frontend/pages/datasets/[...slug].tsx

[td] Writing export instructions

---

mage_ai/frontend/components/datasets/columns/ColumnReports.tsx
mage_ai/frontend/oracle/components/Table/Cell.tsx
mage_ai/frontend/oracle/components/Table/SimpleDataTable.tsx
mage_ai/frontend/oracle/components/Table/index.style.tsx
mage_ai/frontend/utils/models/featureSet.ts

- Refactor cell and tables for undefined values
- Add progress bar to percentage metrics
- Add more quality metrics to the page.
Went on localhost
cc: @johnson-mage 
Note this has big changes to design as it removes the border from the cells for the datatable.

[nt]  column metric additions

---

mage_ai/frontend/components/datasets/Insights/Overview.tsx

[jk] Fix bug preventing Distribution of Values graph from being displayed

---

mage_ai/frontend/yarn.lock

- See title
n/a
cc:
@shrey-mage

[jk] Update yarn.lock file

---

mage_ai/frontend/components/charts/ScatterPlot.tsx
mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
mage_ai/frontend/components/datasets/overview/index.tsx

* Add text when there are no visualizations
* Scale the scatter plot circle size slightly when there are multiple duplicate points
local testing
cc:

[dy] Final launch changes

---

mage_ai/frontend/components/ActionForm/actions.ts
mage_ai/frontend/components/ActionForm/constants.ts
mage_ai/frontend/components/ActionForm/index.tsx

- Adds a `CODE_EXAMPLE` that users can see to better understand how to use the custom actions.
- Updates the description for row and column custom code actions.
Localhost

[nt] custom actions copy

---

mage_ai/frontend/components/datasets/Detail/index.tsx

[jk] Show message when no suggestions available instead of blank panel

---

mage_ai/frontend/components/suggestions/SuggestionRow.tsx

- "View Code" / edit suggestion button now turns black when action menu is expanded

[sp] add edit suggestion button styling

---

mage_ai/data_cleaner/pipelines/base.py
mage_ai/data_cleaner/statistics/calculator.py

Remove redundant prints.
tested locally
cc:

[xy] Remove redundant prints.

---

mage_ai/frontend/components/charts/ScatterPlot.tsx

I thought this was fixed, but I tried it again on localhost:5000, and it causes the frontend to crash sometimes. Need to figure out why this causes the frontend to crash. This will be a temporary hotfix.
local frontend
cc:

[dy] Don't allow users to select same feature for both axes

---

mage_ai/__init__.py

Rename pipeline_path param.
tested locally
cc:

[xy] Rename pipeline_path param.

---

mage_ai/server/app.py

Add dataset routes.
tested locally
cc:

[xy] Add dataset routes.

---

README.md

[td] Better README

---

mage_ai/frontend/components/datasets/columns/ColumnListSidebar.tsx

[td] Fix vertical alignment sidebar

---

mage_ai/frontend/components/datasets/Detail/index.tsx

[td] Fix no actions

---

mage_ai/frontend/components/datasets/Detail/index.tsx
mage_ai/frontend/components/datasets/columns/ColumnReports.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/datasets/overview/utils.tsx

[td] Fix column type wrapping

---

mage_ai/frontend/components/datasets/columns/ColumnReports.tsx

Mode doesn't have to be a number
local
cc:

[dy] Fix mode

---

mage_ai/frontend/components/datasets/Detail/index.tsx

[jk] Local storage bugfix

---

mage_ai/frontend/oracle/components/Table/index.style.tsx

- Fix corner clipping at bottom of table.

[jk] Fix simple data table corner styling

---

docs/tutorials/README.md
docs/tutorials/data_cleaning.md
docs/tutorials/data_cleaning_workflow.md

[td] Add more README tutorials

---

mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
mage_ai/frontend/components/datasets/Insights/Overview.tsx

[td] Fix charts on column detail

---

setup.py

Bump up version number to v0.0.2.
n/a
cc:

[xy] Bump up version number.

---

MANIFEST.in

Include csv in package.
tested locally
cc:

[xy] Include csv in package.

---

mage_ai/data_cleaner/analysis/charts.py

Fix count filter in scatter plot. Use the actually the sample count instead of SCATTER_PLOT_SAMPLE_COUNT.
tested locally
cc:

[xy] Fix count filter in scatter plot.

---

mage_ai/frontend/components/charts/HeatMap.tsx

[sp] adjust correlation matrix headers

---

README.md

[td] Update borders

---

mage_ai/frontend/components/ActionForm/actions.ts
mage_ai/frontend/components/ActionForm/constants.ts
mage_ai/frontend/components/ActionForm/index.tsx
mage_ai/frontend/components/ActionForm/utils.ts
mage_ai/frontend/components/charts/ScatterPlot.tsx
mage_ai/frontend/components/datasets/Insights/Overview.tsx
mage_ai/frontend/components/datasets/overview/index.tsx

[td] Show all cleaning actions and show columns by default

---

README.md

[td] Update README to use sample datasetes

---

mage_ai/frontend/components/datasets/overview/index.tsx

[sp] add close button for stack trace panel

---

setup.py

[xy] Bump up version.

---

mage_ai/frontend/components/PageBreadcrumbs/index.tsx
mage_ai/frontend/components/datasets/Detail/index.tsx
mage_ai/frontend/components/datasets/Export/index.tsx
mage_ai/frontend/oracle/components/Breadcrumbs/Breadcrumb.tsx
mage_ai/frontend/oracle/elements/Text/index.tsx
mage_ai/frontend/oracle/styles/fonts/sizes.ts

- Clean up breadcrumbs and header on export page

[jk] Breadcrumbs polish

---

mage_ai/data_cleaner/analysis/calculator.py
mage_ai/data_cleaner/analysis/charts.py
mage_ai/data_cleaner/cleaning_rules/clean_column_names.py
mage_ai/data_cleaner/cleaning_rules/impute_values.py
mage_ai/data_cleaner/cleaning_rules/reformat_values.py
mage_ai/data_cleaner/cleaning_rules/remove_collinear_columns.py
mage_ai/data_cleaner/column_types/column_type_detector.py
mage_ai/data_cleaner/column_types/constants.py
mage_ai/data_cleaner/data_cleaner.py
mage_ai/data_cleaner/pipelines/base.py
mage_ai/data_cleaner/shared/utils.py
mage_ai/data_cleaner/statistics/calculator.py
mage_ai/data_cleaner/transformer_actions/column.py
mage_ai/data_cleaner/transformer_actions/constants.py
mage_ai/data_cleaner/transformer_actions/helpers.py
mage_ai/data_cleaner/transformer_actions/row.py
mage_ai/data_cleaner/transformer_actions/udf/addition.py
mage_ai/data_cleaner/transformer_actions/udf/difference.py
mage_ai/tests/data_cleaner/cleaning_rules/test_reformat_values.py
mage_ai/tests/data_cleaner/test_column_type_detector.py
mage_ai/tests/data_cleaner/transformer_actions/test_custom_actions.py

Column type operations (storage of constant values and inference of column types) were refactored to a new `column_types` subpackage to better isolate their logic from the rest of the `data_cleaner` package. 
Additionally, column type constants were replaced with an enum to namespace column type constants, making their use more explicit. Using an enum also makes imports less verbose and easier to manage.
Previous unit tests were refactored and ran to confirm that all supported functions of the data cleaner package are not broken.
cc:

[sk] Refactor Column Types

---

mage_ai/data_cleaner/analysis/calculator.py
mage_ai/data_cleaner/analysis/charts.py

Consolidate calculation for correlation to reduce analysis calculation time.
tested locally
Reduced analysis calculation time from 2523ms to 2198ms
cc:

[xy] Consolidate calculation for correlation.

---

mage_ai/data_cleaner/statistics/calculator.py

Fixed typo in conversion from series to dictionary.
cc:

[sk] Fixed small bug

---

mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/utils/models/featureSet.ts

- Cells are highlighted dark red with white text when they are invalid values.
Localhost
_Checked values from the feature profiles that had red and checked the datatable for inspection.

[nt]  invalid syntax detection

---

README.md

[td] Update README again

---

README.md

[td] Add a break between gif and Slack link

---

setup.py

Bump version to 0.0.4.
n/a
cc:

[xy] Bump version to 0.0.4.

---

README.md

[td] Add more spacing between Slack and gif

---

mage_ai/server/README.md

Update README.md for starting flask app with new port number
n/a
cc:

[xy] Update README for starting flask app with port

---

mage_ai/data_cleaner/column_types/column_type_detector.py
mage_ai/data_cleaner/data_cleaner.py
mage_ai/server/app.py
mage_ai/tests/data_cleaner/test_column_type_detector.py

Reduce duplicate column type calculation.
tested locally
unit tests
cc:

[xy] Reduce duplicate column type calculation.

---

mage_ai/server/app.py

[td] Allow custom host and port when launching

---

docs/contributing/README.md
docs/contributing/jupyter.md
mage_ai/frontend/api/utils/url.ts
mage_ai/server/app.py

[td] Custom ports and hosts when running flask app

---

docs/contributing/jupyter.md
mage_ai/__init__.py

[td] Override host and port of iframe

---

README.md
docs/contributing/jupyter.md

[td] Update README for host and port

---

mage_ai/__init__.py

Print url after launching web server.
tested locally
to be tested on google colab after PR is merged
cc:

[xy] Print url after launching web server.

---

.github/workflows/build_and_test.yml
.github/workflows/test.yml

Add github workflow for unit tests.
CI
cc:

[xy] Add github workflow for unit tests.

---

setup.py

Bump version to 0.0.5.
n/a
cc:

[xy] Bump version to 0.0.5.

---

README.md
docs/contributing/README.md
docs/contributing/jupyter.md
docs/tutorials/assets/quick-start.ipynb

Update sample_datasets path in doc.
n/a
cc:

[xy] Update sample_datasets path in doc.

---

mage_ai/frontend/components/charts/BarGraphHorizontal.tsx

- see above
cc: @johnson-mage @dy46 @MageKai

[sp] remove dark part of bar chart

---

mage_ai/server/app.py

Fixed the unused imports error from #343 
cc:

[sk] Removed unused imports

---

mage_ai/frontend/components/suggestions/SuggestionRow.tsx
mage_ai/frontend/oracle/styles/themes/light.ts

- add new theme color "secondary link, disabled"
- fix rendering of column name when it has been renamed or no longer exists

[sp] fix column names styling in pipeline

---

mage_ai/frontend/components/ActionForm/actions.ts
mage_ai/frontend/interfaces/ActionPayloadType.ts

- See title.
Note that the title for the applied action will appear after this [PR](https://github.com/mage-ai/mage-ai/pull/383) is merged.

[jk] Add remove multidimensional outliers action

---

mage_ai/__init__.py

Connect data with pyspark dataframe. Sample rows and convert to pandas dataframe before processing.
tested on databricks notebook
cc:

[xy] Connect data with pyspark dataframe.

---

mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/DataTable/scrollbarWidth.ts
mage_ai/frontend/components/PageBreadcrumbs/index.tsx
mage_ai/frontend/components/datasets/FeatureProfiles.tsx
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/utils.ts

- The "View all" invalid values redirect link wasn't working properly, so this PR fixes that and maintains the state of the query params.

[jk] Fix invalid values "view all" link redirect

---

mage_ai/frontend/components/datasets/overview/utils.tsx

- Rename "time series" to "datetime" features.

[jk] Rename time series features label

---

mage_ai/__init__.py
mage_ai/data_cleaner/shared/utils.py
mage_ai/data_cleaner/transformer_actions/base.py
mage_ai/data_cleaner/transformer_actions/spark/constants.py
mage_ai/data_cleaner/transformer_actions/spark/transformers.py

Implement spark transformers. The implementation was moved from the data repo to this repo with some modifications.
Supported cleaning functions
The remaining cleaning functions will be added in following PRs.
tested on databricks
Create pipeline locally and sync to cloud. Clean the pyspark dataframe in databricks notebook.
cc:

[xy] Implement spark transformers

---

README.md

[td] Add link to CircleCI build

---

.gitignore
Dockerfile
docker-compose.yml
docs/contributing/README.md
scripts/dev.sh

Add support to run Jupyter, server, and front-end in Docker.
Ran locally
cc:
@dy46

[td] Add Docker

---

docs/contributing/README.md
example.ipynb

Added an example notebook for a quick start once starting the services in docker.
Ran it locally.
cc:
@dy46

[td] Add example notebook for docker jupyter lab

---

docs/contributing/README.md
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/suggestions/index.tsx
mage_ai/frontend/oracle/components/CsvExport.tsx
mage_ai/server/app.py

Download the dataset as a CSV file.
cc:
@johnson-mage @skunichetty

[td] Download dataset

---

README.md

[td] Add emojis

---

README.md

[td] Improve readme

---

README.md

[td] Improve README by adding more emojis + numbers

---

README.md
docs/contributing/README.md
example.ipynb

[td] Simplify readme

---

README.md

[td] Update table of contents

---

README.md
docs/contributing/README.md
docs/tutorials/clean.md

[td] Simplified quick start even more

---

mage_ai/data_cleaner/transformer_actions/base.py

Cache spark execution result to improve perf.
tested on databricks notebook
cc:

[xy] Cache spark execution result.

---

mage_ai/__init__.py
mage_ai/server/app.py
mage_ai/server/constants.py
mage_ai/server/utils/frontend_renderer.py
requirements.txt

Databricks notebook generates the url in this format: `https://{host}/driver-proxy-api/o/{workspaceId}/{clusterId}/{port}/?token=[token]`. For our flask app, we need to append additional path after the base url. This PR updates frontend urls in static files with base_path and token param after launching the flask server in databricks notebook.
This PR also refactored some code in `mage_ai/__init__.py` and move it to `frontend_rendere.py`
TODO: update frontend react to generate url dynamically with base_path and url_params
tested in databricks notebook about frontend url updates.

[xy] Update frontend urls in static files for databricks notebook.

---

mage_ai/data_cleaner/transformer_actions/spark/transformers.py

Some improvements on spark implementation.
* Not implement remove_outlier transformer for now
* Update groupby apply to applyInPandas to remove warnings.
tested in databricks notebook
cc:

[xy] Some improvements on spark implementation

---

mage_ai/frontend/components/CodeEditor/constants.ts
mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/CodeEditor/keyboard_shortcuts/index.tsx
mage_ai/frontend/components/CodeEditor/keyboard_shortcuts/shortcuts.ts
mage_ai/frontend/components/CodeEditor/utils.ts
mage_ai/frontend/package.json
mage_ai/frontend/pages/test.tsx
mage_ai/frontend/yarn.lock

Add a code editor based on VSCode.
cc:
@johnson-mage @dy46

[td] Add code editor on test page

---

mage_ai/__init__.py
mage_ai/data_cleaner/data_cleaner.py
mage_ai/data_cleaner/pipelines/base.py
mage_ai/data_cleaner/statistics/calculator.py

Create preview results for rows removed.
In each suggestion, if there're row removed after applying the action, we'll add a preview_results with removed_row_indices to the suggestion payload.
tested locally

[xy] Create preview results for row removed.

---

Dockerfile

Issue: https://github.com/mage-ai/mage-ai/issues/417
- Built docker image locally with no cache and it works.
- Eliel Godsent tested
- @ChadGueli tested

[td] Explicitly install npm version (credit to Eliel Godsent)

---

mage_ai/data_cleaner/cleaning_rules/base.py
mage_ai/data_cleaner/cleaning_rules/impute_values.py
mage_ai/data_cleaner/cleaning_rules/reformat_values.py
mage_ai/data_cleaner/cleaning_rules/remove_collinear_columns.py
mage_ai/data_cleaner/cleaning_rules/remove_columns_with_high_empty_rate.py
mage_ai/data_cleaner/cleaning_rules/remove_outliers.py
mage_ai/data_cleaner/data_cleaner.py
mage_ai/data_cleaner/pipelines/base.py
mage_ai/server/app.py
mage_ai/server/data/models.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_columns_with_high_empty_rate.py
mage_ai/tests/data_cleaner/cleaning_rules/test_remove_outliers.py

Allow overriding cleaning rule config.
`default_config` is declared in each cleaning rule class. User can override the default config by include the custom config in `cleaning_rule_configs` with the cleaning rule name as the key. Example
```
"cleaning_rule_configs": {
"RemoveOutliers": {
"max_z_score": 2
}
}
```
tested locally and added new unit tests
Before adding custom cleaning rule config, the default max_z_score for RemoveOutliers is 3.
After adding the custom max_z_score for RemoveOutliers, the suggestion changes.
cc:

[xy] Allow overriding cleaning rule config.

---

mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/PageBreadcrumbs/index.tsx
mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
mage_ai/frontend/components/datasets/Insights/Overview.tsx
mage_ai/frontend/components/datasets/overview/constants.ts
mage_ai/frontend/components/datasets/overview/index.tsx
mage_ai/frontend/components/datasets/overview/utils.tsx
mage_ai/frontend/components/utils.ts

- add time series histogram for datetime columns
- change data table column header links to redirect to "Visualizations" tab instead of "Reports" tab

[sp] add visualization for datetime data

---

mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
mage_ai/frontend/components/datasets/overview/utils.tsx

- only display one time series histogram for data table column header & column-specific visualizations
If multiple datetime columns aren't present in a testing dataset, use the below action code to add a distinct distribution:
```python
@transformer_action
def transform(df):
import pandas as pd
import numpy as np
def random_dates(start, end, n=10):
start_u = start.value//10**9
end_u = end.value//10**9
return pd.to_datetime(np.random.randint(start_u, end_u, n), unit='s')
start = pd.to_datetime('2015-01-01')
end = pd.to_datetime('2018-01-01')
df['rand_times'] = random_dates(start, end, len(df))
return df
```
cc: @johnson-mage @wangxiaoyou1993

[sp] fix datetime visualizations

---

mage_ai/data_cleaner/pipelines/base.py

Fix index in preview results to handle the scenario that index has missing numbers.
tested locally
cc:

[xy] Fix index in preview results.

---

setup.py

Bump version to 0.0.6.
n/a
cc:

[xy] Bump version to 0.0.6.

---

mage_ai/data_cleaner/shared/utils.py
mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/repo_management.py
mage_ai/data_preparation/templates/pipeline/metadata.yaml
mage_ai/tests/data_preparation/test_block.py
mage_ai/tests/data_preparation/test_pipeline.py
requirements.txt

Add initial pipeline and block models.
Tech design: https://www.notion.so/mageai/Data-preparation-tool-tech-design-0d3de36d5818454889d10ebe9645ab37
Tested locally
Added unit tests for Block and Pipeline model.
cc: @dy46 @skunichetty

[xy] Add pipeline and block models

---

mage_ai/frontend/interfaces/KernelOutputType.ts
mage_ai/frontend/pages/test.tsx
mage_ai/server/kernel_output_parser.py
mage_ai/server/server.py
mage_ai/server/subscriber.py
mage_ai/server/websocket.py

Track when a block of code is finished running or still in progress.
cc:
@johnson-mage

[td] Track kernel in progress

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/variable_manager.py
mage_ai/server/server.py

Add endpoints for block, pipeline and variables.
Tech design: https://www.notion.so/mageai/Data-preparation-tool-tech-design-0d3de36d5818454889d10ebe9645ab37
Endpoints:
```
GET /pipelines
GET /pipelines/[pipeline_uuid]
POST /pipelines
PUT /pipelines/[pipeline_uuid]
GET /pipelines/[pipeline_uuid]/blocks
GET /pipelines/[pipeline_uuid]/blocks/[block_uuid]
POST /pipelines/[pipeline_uuid]/blocks
PUT /pipelines/[pipeline_uuid]/blocks/[block_uuid]
GET /pipelines/[pipeline_uuid]/variables
```
Detailed request and response payloads are in design doc.
TODOs in following PRs
tested locally
cc:

[xy] Add endpoints for block, pipeline and variables.

---

mage_ai/frontend/components/charts/BoxPlotHorizontal.tsx
mage_ai/frontend/oracle/styles/themes/constants.ts
mage_ai/frontend/oracle/styles/themes/light.ts
mage_ai/frontend/package.json
mage_ai/frontend/stories/components/charts/BarGraphHorizontal.stories.tsx
mage_ai/frontend/stories/components/charts/BoxPlotHorizontal.stories.tsx
mage_ai/frontend/utils/array.ts
mage_ai/frontend/yarn.lock

- see above
Tested "primary", "secondary", and "danger" props. Sample data distribution displays correctly.
One-sided distributions also display correctly.
Added tooltips (cursor looks off in the GIF but it works correctly):

[sp] add box plot

---

mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeEditor/index.style.tsx
mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/CodeEditor/utils.ts
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/interfaces/KernelOutputType.ts
mage_ai/frontend/oracle/styles/themes/dark.ts
mage_ai/frontend/package.json
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/frontend/yarn.lock
mage_ai/server/kernel_output_parser.py

[td] Update editor

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeEditor/index.style.tsx
mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/CodeEditor/utils.ts
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/components/charts/BoxPlotHorizontal.tsx
mage_ai/frontend/pages/_document.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/frontend/storage/localStorage.ts

[td] When moving cursor to bottom, scroll

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/templates/utils.py
mage_ai/server/server.py

Implement init_repo method and add repo templates.
tested locally
cc: @dy46 @skunichetty

[xy] Implement init_repo method.

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/variable_manager.py
mage_ai/server/server.py

Add block output and analysis endpoints.
Tech design: https://www.notion.so/mageai/Data-preparation-tool-tech-design-0d3de36d5818454889d10ebe9645ab37#36709c0c76ab42f789e8be3a400aca5b
tested locally
cc:

[xy] Add block output and analysis endpoint.

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/file.py

Update some endpoint responses
* Include variable_uuid in outputs and analyses endpoints.
* Return relative path for files get endpoint.
tested locally
cc:

[xy] Update some endpoint responses

---

mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeEditor/index.style.tsx
mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/CodeEditor/utils.ts
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.style.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/index.style.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/EventPropertiesType.ts
mage_ai/frontend/oracle/components/FlexContainer.tsx
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/frontend/oracle/elements/Tracking/index.tsx
mage_ai/frontend/oracle/styles/themes/dark.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/frontend/utils/array.ts
mage_ai/frontend/utils/hooks/keyboardShortcuts/constants.ts

[td] Enhance adding block experience

---

mage_ai/command_line.py
mage_ai/server/server.py
setup.py

Add command line commands for initializing repo and starting server.
Currently, the command is set as `mage-ai <command>` instead of `mage <command>` because that keyword seems to be used somewhere already.
tested locally

[dy] Add command line

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/server/server.py
mage_ai/tests/data_preparation/models/test_pipeline.py

Add execute logic for pipelines. Right now, the execution logic will run the blocks in parallel when possible.
unit tests
cc:

[dy] Add execution logic for pipelines

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py

This PR includes the following changes:
* Only return dirs when fetching pipelines.
* Throw exception when creating duplicate block uuid
* Implement the method to update block dependencies.
tested locally
Create duplicate block uuid
Update block dependencies
cc:

[xy] Update some endpoints

---

docker-compose.yml

[td] Use local image when running docker compose

---

mage_ai/data_preparation/variable_manager.py
mage_ai/server/server.py

Return stack trace for 500 error.
This PR also fixes the error for fetching variables.
tested locally
cc:

[xy] Return stacktrace for 500 error

---

mage_ai/data_preparation/models/block.py
mage_ai/tests/data_preparation/models/test_block.py
mage_ai/tests/data_preparation/models/test_pipeline.py

Add logic to execute block code.
unit tests

[dy] Add block execution logic

---

mage_ai/data_loader/bigquery.py
mage_ai/data_preparation/templates/data_loaders/bigquery.py
mage_ai/data_preparation/templates/data_loaders/file.py
mage_ai/data_preparation/templates/data_loaders/postgres.py
mage_ai/data_preparation/templates/data_loaders/redshift.py
mage_ai/data_preparation/templates/data_loaders/s3.py
requirements.txt

Added data loader + template for Google BigQuery. To add this functionality, two new dependencies were added:
- `google-cloud-bigquery` - Google client for interfacing with BigQuery
- `db-dtypes` - Library required by BigQuery client to write loaded data to a Pandas data frame.
Testing was performed by connecting to a Google BigQuery data warehouse and querying data from it into a data frame using multiple different construction strategies
cc:

[sk] Added data loader + template for Google BigQuery 

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeEditor/constants.ts
mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/KernelOutputType.ts
mage_ai/frontend/oracle/components/Spinner/index.tsx
mage_ai/frontend/oracle/styles/fonts/sizes.ts
mage_ai/frontend/oracle/styles/themes/constants.ts
mage_ai/frontend/oracle/styles/themes/dark.ts
mage_ai/frontend/utils/constants.ts
mage_ai/server/kernel_output_parser.py
mage_ai/server/server.py
mage_ai/server/websocket.py

[td] Send websocket message with msg_id and uuid

---

mage_ai/__init__.py
mage_ai/command_line.py

Add pipeline execution from python method and command line 
tested locally

[dy] Add other execution methods

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/file.py
mage_ai/server/server.py

* Update block execute to use POST request
* Update files GET to return files in dictionary.
tested locally
cc: @shrey-mage

[xy] Update some endpoints.

---

mage_ai/data_preparation/models/block.py
mage_ai/server/server.py
mage_ai/tests/data_preparation/models/test_block.py

This PR has the following changes
*. Verify output variable dtypes
* Return block outputs in execution reponse
* Analyze dataframe after executing block
tested locally.
updated unit tests.
cc: @dy46

[xy] Analyze dataframe after executing block

---

docker-compose.yml
mage_ai/frontend/scripts/install_and_run.sh

[td] Install node modules everytime docker-compose up

---

mage_ai/data_loader/snowflake.py
mage_ai/data_preparation/templates/data_loaders/snowflake.py
requirements.txt

Added data loader and template for loading data frames from Snowflake connections.
Some notable changes:
- Added new dependency: `snowflake-connector-python==2.7.9`
- Downgraded `pyarrow` from 8.0.0 to 6.0.0 to resolve conflict with `snowflake-connector-python`
- While connections to Snowflake could be opened with `pyarrow==8.0.0`, the connection crashed upon attempting to load a query into a pandas data frame. Downgrading based on warnings fixed this issue and data frames are now correctly loaded.
Data loader was tested by connecting to Snowflake and running test queries.

[sk] Added data loader + template for Snowflake connections

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/server/server.py
mage_ai/tests/data_preparation/models/test_block.py
mage_ai/tests/data_preparation/models/test_pipeline.py

This PR includes the following fixes/updates on endpoints
* Delete unused requirements.txt in pipeline folder
* If outputs of a block is None, set it to an empty list to fix output verification
* Fix pipeline execute endpoint pattern
tested locally
cc:

[xy] Some fixes on endpoints

---

docker-compose.yml
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/KernelOutputType.ts
mage_ai/frontend/interfaces/KernelType.ts
mage_ai/frontend/oracle/components/Spinner/index.tsx
mage_ai/frontend/oracle/elements/Circle.tsx
mage_ai/frontend/oracle/elements/KeyboardTextGroup.tsx
mage_ai/frontend/oracle/styles/themes/constants.ts
mage_ai/frontend/oracle/styles/themes/dark.ts
mage_ai/frontend/scripts/install_and_run.sh
mage_ai/server/kernel_output_parser.py
mage_ai/server/server.py

[td] Queue blocks

---

mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.style.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/oracle/styles/themes/constants.ts
mage_ai/frontend/oracle/styles/themes/dark.ts

[td] Fix clicking on a block and highlighting it

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/oracle/elements/Circle.tsx
mage_ai/frontend/oracle/styles/themes/dark.ts

[td] Show whether block has been ran

---

mage_ai/frontend/api/index.ts
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/utils/string.ts
mage_ai/server/server.py

[td] CRUD block

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/variable.py

Implement block name update method.
tested locally
cc:

[xy] Implement block name update method.

---

mage_ai/data_preparation/models/file.py

Tree generation for frontend filesystem. Example payload: 
Tests were performed locally to make sure that the correct tree structure is generated
cc:

[sk] Updated directory tree generation

---

mage_ai/data_preparation/models/pipeline.py

Fix file not found error.
tested locally
cc:

[xy] Fix file not found error.

---

mage_ai/data_preparation/models/pipeline.py

Not change order when updating block uuid.
tested locally
cc:

[xy] Not change order when updating block uuid.

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/file.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/server/server.py
mage_ai/tests/data_preparation/models/test_pipeline.py

This PR add or update the following endpoints
* Add block delete endpoints.
* Allow getting or updating all block content in a pipeline via one API call
Tested locally
cc:

[xy] Add block delete endpoints.

---

mage_ai/frontend/api/cleaner/index.ts
mage_ai/frontend/api/index.ts
mage_ai/frontend/api/utils/response.ts
mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.style.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/index.style.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/context/Kernel.tsx
mage_ai/frontend/context/Pipeline.tsx
mage_ai/frontend/interfaces/LinkType.ts
mage_ai/frontend/oracle/components/FlexContainer.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.style.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutWrapper.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Created dropdown menus for file and commands

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/context/Block.tsx
mage_ai/frontend/context/Kernel.tsx
mage_ai/frontend/context/Pipeline.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Use context for pipeline slug

---

mage_ai/server/server.py

Include content in response by default.
tested locally
cc:

[xy] Include content in response by default.

---

mage_ai/frontend/api/index.ts
mage_ai/frontend/api/utils/use.ts
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/context/Pipeline.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Save and get all pipeline content

---

mage_ai/frontend/api/index.ts
mage_ai/frontend/api/utils/use.ts
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Delete block

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/context/Block.tsx
mage_ai/frontend/context/Kernel.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Show save status

---

mage_ai/server/server.py

Fix json serialization in response.
tested locally

[xy] Fix json serialization in response.

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Save all outputs in 1 API call

---

mage_ai/frontend/components/PipelineDetail/index.tsx

[td] Added autosave

---

mage_ai/data_preparation/models/block.py

Throw error when renaming duplicate name.
tested locally
cc:

[xy] Throw error when renaming duplicate name.

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/server/utils/output_display.py
mage_ai/server/websocket.py

[td] Show table when output is dataframe

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/server/server.py

Support creating a block with a priority
tested locally
cc:

[xy] Support creating a block with a priority

---

mage_ai/frontend/components/FileTree/index.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/frontend/utils/events.ts

[td] Don’t re-render file tree unnecessarily

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeEditor/index.style.tsx
mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/oracle/components/Tooltip/TooltipWrapper.tsx

[td] Made various tweaks

---

mage_ai/data_preparation/models/pipeline.py

Fix updating block dependencies.
tested locally
cc:

[xy] Fix updating block dependencies.

---

mage_ai/frontend/api/index.ts
mage_ai/frontend/api/utils/url.ts
mage_ai/frontend/api/utils/use.ts
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/Sidekick/index.style.ts
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/components/charts/BarGraphHorizontal.tsx
mage_ai/frontend/components/charts/PieChart.tsx
mage_ai/frontend/components/datasets/overview/utils.tsx
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/frontend/oracle/elements/Text/index.tsx
mage_ai/frontend/oracle/icons/index.tsx
mage_ai/frontend/oracle/styles/mixins.ts
mage_ai/frontend/oracle/styles/scrollbars.ts
mage_ai/frontend/oracle/styles/themes/light.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx

- Display data table in Data tab.
- Update styling of table to match dark theme.
- Use query params to redirect to specific tab.
- Optimize rendering of data table (resizing right panel is laggy on Data tab).
cc:
@tommydangerous @shrey-mage

[jk] Integrate Data tab in Sidekick

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/server/utils/output_display.py

[td] Improve code editor and output rendering

---

mage_ai/server/utils/output_display.py

[td] Fix display output

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/PipelineDetail/index.style.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/oracle/styles/scrollbars.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/frontend/styles/theme.ts
mage_ai/server/utils/output_display.py

[td] If block is not selected, disable scrolling datatable

---

mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/Sidekick/index.style.ts
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[jk] Sidekick dependency tree integration

---

mage_ai/frontend/components/DependencyGraph/constants.ts
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/Sidekick/constants.ts
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/oracle/elements/Text/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

- See title.
- Also added minor dependency tree node polish.

[jk] Use query params for Sidekick views

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DependencyGraph/GraphNode.tsx
mage_ai/frontend/components/DependencyGraph/index.style.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/DependencyGraph/utils.ts
mage_ai/frontend/components/Sidekick/index.style.ts
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/context/Block.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/frontend/utils/array.ts

[td] Edit downstream blocks

---

mage_ai/server/kernel_output_parser.py
mage_ai/server/websocket.py

Return error traceback in websocket message.
tested locally

[dy] Return error traceback

---

mage_ai/data_preparation/models/block.py
mage_ai/frontend/api/utils/response.ts
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/DependencyGraph/GraphNode.tsx
mage_ai/frontend/components/DependencyGraph/constants.ts
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/DependencyGraph/utils.ts
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/oracle/elements/KeyboardText.tsx
mage_ai/frontend/oracle/elements/Text/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/frontend/utils/string.ts
mage_ai/server/server.py
mage_ai/server/websocket.py

[td] Show data loader outputs

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/variable_manager.py

Delete old outputs when saving outputs of scratchpad.
tested locally
original outputs
after updating
cc:

[xy] Delete old outputs when saving outputs.

---

mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/variable_manager.py
mage_ai/tests/data_preparation/test_variable_manager.py

Some updates on variables.
* Throw exception when setting a variable in a non-existent pipeline
* Add a method to get variable of a block
tested locally
cc:

[xy] Some updates on variables.

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/FileTree/index.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/context/Block.tsx
mage_ai/frontend/context/Kernel.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/KernelType.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Remove context

---

mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Resize table

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Update sidekick whenever execution done

---

mage_ai/frontend/api/index.ts
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/oracle/styles/themes/dark.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx

- Allow user to execute entire pipeline.
- Display error messages if request fails.
Successful request:
Errors:

[jk] Execute pipeline

---

mage_ai/frontend/components/Sidekick/index.tsx

[jk] Only show execute pipeline button on Tree view

---

mage_ai/data_preparation/models/block.py
mage_ai/tests/data_preparation/models/test_block.py

Add some additional error messaging
unit tests/ local

[dy] Add error messaging for block execute

---

mage_ai/frontend/components/BlockCharts/index.tsx
mage_ai/frontend/components/Sidekick/constants.ts
mage_ai/frontend/components/charts/HeatMap.tsx
mage_ai/frontend/components/charts/Histogram.tsx

- make charts take up full width of sidekick panel
- update histogram & heat map for dark theme coloring
- add padding to correlation matrix panel
cc: @johnson-mage @tommydangerous @dy46

[sp] update sidekick graphs & chart styling

---

mage_ai/frontend/components/DependencyGraph/GraphNode.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/oracle/styles/themes/light.ts
mage_ai/frontend/stories/components/DependencyGraph.stories.tsx

- Show green checkmark for executed blocks in dependency graph.
- Display nodes top to bottom.

[jk] Dependency tree polish

---

mage_ai/data_preparation/templates/transformers/default.py
mage_ai/tests/data_preparation/test_templates.py

Template for transformers is updated to mention adding parameters in the case that this function has multiple parent blocks. This will let users know that they need to define multiple parameters in the case there are multiple parent blocks providing input.
Unit tests were updated to confirm that the correct template was added, alongside local testing with UI.
cc:

[sk] Updated transformer template to mention adding parameters

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeEditor/index.tsx

[td] Fix round 1 of bugs

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/server/websocket.py

* Update error message of deleting block
* Fix `No module named 'utils'` when installing the library
tested locally
cc:

[xy] Two small fixes

---

mage_ai/frontend/api/utils/response.ts
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Bug fixes v2

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/frontend/storage/localStorage.ts

[td] Show execution state

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/constants.py

Set status as failed when the block encounters an error.
local
cc:

[dy] Add failed status

---

mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

- Center depgraph and move error messages to Sidekick.
cc:

[jk] Bugfixes dependency graph round 1

---

mage_ai/frontend/components/FileTree/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/index.style.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx

[td] Bug polish round 3

---

mage_ai/frontend/components/DependencyGraph/GraphNode.tsx
mage_ai/frontend/components/DependencyGraph/index.style.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/oracle/elements/Circle.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Show node loader when running

---

mage_ai/data_preparation/models/block.py
mage_ai/server/websocket.py

Return stdout in a separate message for block execution so that it can be rendered in the frontend code output.
cc: @wangxiaoyou1993 @skunichetty

[dy] Show stdout of block execution

---

mage_ai/io/base.py
mage_ai/io/bigquery.py
mage_ai/io/file.py
mage_ai/io/postgres.py
mage_ai/io/redshift.py
mage_ai/io/s3.py
mage_ai/io/snowflake.py
mage_ai/shared/logger.py

Data loading and exporting now has the option to print verbose output on the exact commands being executed at any point. This verbose output is disabled by default but can be enabled by specifying `verbose=True` when constructing any IO handler.
Example with Postgres
Local tests were performed to check that the printing behavior works as expected.
cc:

[sk] Added option to print status of IO procedures

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py

There was a pipeline execution error because it was trying to await a null task. Also, updated some error messages to also include block uuid.
tested locally

[dy] Fix pipeline execution error

---

mage_ai/server/utils/output_display.py

Sample data in custom output. Otherwise, the kernel will time out for large dataset.
tested locally

[xy] Sample data in custom output.

---

mage_ai/frontend/components/FileTree/index.tsx
mage_ai/frontend/components/FileTree/utils.ts
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/oracle/elements/Link/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[sp] double click block file to add to pipeline

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/variable_manager.py

* Not always override variables.
* Not return empty variable names.
tested locally
cc:

[xy] Two fixes on variables

---

docker-compose.yml

Restart the server_kernel container on failure.
Ref: https://docs.docker.com/config/containers/start-containers-automatically/#:~:text=Docker%20provides%20restart%20policies%20to,process%20managers%20to%20start%20containers.
tested locally
cc:

[xy] Restart the server_kernel container on failure.

---

mage_ai/data_preparation/models/variable.py
mage_ai/tests/data_preparation/models/test_variable.py

Speed up loading data when there's large dataframe. Store sample_data.parquet along with data.parquet to speed up data loading.
tested locally
before optimization
after optimization: 
cc:

[xy] Speed up loading data.

---

mage_ai/frontend/components/FileTree/constants.ts
mage_ai/frontend/components/FileTree/utils.ts
mage_ai/frontend/interfaces/FileType.ts
mage_ai/frontend/stories/components/panels/FileTree.stories.tsx

- see above
- everything still works

[sp] clean up file tree utils

---

mage_ai/frontend/components/FileTree/index.tsx
mage_ai/frontend/components/FileTree/utils.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Open new pipeline by double clicking

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/DataTable/index.tsx

[td] Fix showing cell values as objects

---

mage_ai/data_preparation/decorators.py

Add comments for decorators file for clarification.
n/a
cc:

[xy] Add comments for decorators file.

---

mage_ai/frontend/components/PipelineDetail/index.tsx

[td] Disable adding block when typing in field to update UUID

---

mage_ai/data_preparation/models/block.py
mage_ai/server/server.py

Update block delete endpoints.
* Update block delete endpoint to `/api/blocks/<block_type_and_uuid_encoded>`
* Delete file of scratchpad block when post to pipeline block delete endpoint
tested locally
cc:

[xy] Update block delete endpoints.

---

mage_ai/frontend/components/DependencyGraph/GraphNode.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/oracle/components/FlexContainer.tsx

[jk] Dependency graph node failed status

---

.gitignore
mage_ai/command_line.py
mage_ai/server/constants.py
mage_ai/server/server.py
requirements.txt
setup.py

Update setup to install correct version of jupyter client and update the message when the server is started.
cc: @wangxiaoyou1993 @skunichetty

[dy] Update setup and server start message

---

mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[jk] Dependency graph update after codeblock execution

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

- see above
cc: @johnson-mage @tommydangerous @wangxiaoyou1993 @dy46

[sp] edit pipeline name functionality

---

mage_ai/frontend/api/index.ts
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

- add `deleteBlockFile` function for future usage in file browser, code block menu, etc
- update API library to support `useDelete` for single resources
cc: @dy46 @johnson-mage @tommydangerous

[sp] "delete block file" integration

---

mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/index.style.tsx
mage_ai/frontend/oracle/elements/Circle.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Save file

---

mage_ai/data_preparation/models/pipeline.py

Save pipeline name on update.
tested locally
cc:

[xy] Save pipeline name on update.

---

mage_ai/data_preparation/models/file.py

File tree now hides `.git`.
Tested locally
cc:

[sk] Hide .git folder

---

mage_ai/data_preparation/models/file.py

Hide .DS_Store files from the file tree
Changes tested locally
cc:

[sk] Hide .DS_Store files

---

mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/interfaces/FileType.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Fix content not saving

---

mage_ai/data_cleaner/README.md
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/interfaces/FileType.ts

[td] Support editing YAML files

---

mage_ai/data_preparation/models/block.py

Catch dataframe analyze exception so that it doesn't interrupt dataframe calculation.
tested locally
cc:

[xy] Catch dataframe analyze exception.

---

mage_ai/frontend/components/BlockCharts/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx

[td] Control enter to execute block

---

mage_ai/server/server.py

Add route for additional static files
tested locally
cc:

[dy] Add fonts route

---

mage_ai/data_preparation/models/pipeline.py

Only return valid pipelines.
tested locally
cc: @dy46

[xy] Only return valid pipelines.

---

mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/datasets/FeatureProfiles/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

- fix pipeline text field focus bug by removing double conditional render
cc: @johnson-mage @wangxiaoyou1993 @dy46 @tommydangerous

[sp] fix rename pipeline text field focus

---

mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

- see above
cc: @johnson-mage @dy46 @tommydangerous

[sp] refresh file browser after creating pipeline

---

mage_ai/server/utils/output_display.py

[td] Multiline expressions with (), {}, and []

---

setup.py

Bump version to v0.1.0
n/a
cc:

[xy] Bump version to v0.1.0

---

docker-compose.yml
docs/contributing/README.md
docs/contributing/data_cleaner/README.md
mage_ai/command_line.py
mage_ai/server/server.py
mage_ai/server/utils/output_display.py
scripts/dev.sh
scripts/init.sh
scripts/run.sh
scripts/start.sh

[td] Add support for different host and ports

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/interfaces/KernelOutputType.ts

- asynchronous print output is now combined appropriately when rendered
cc: @tommydangerous @skunichetty @dy46 @johnson-mage

[sp] fix async print output

---

mage_ai/server/utils/output_display.py
setup.py

[td] Bump version to 0.1.1

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx
scripts/test.sh
setup.py

[td] Fix shift enter keyboard shortcut

---

mage_ai/server/utils/output_display.py

[td] Limit number of columns that are returned

---

mage_ai/command_line.py
mage_ai/data_preparation/repo_manager.py

Add sys path when starting server and running pipeline so that we can use the custom python scripts in project path.
tested locally
cc:

[xy] Add sys path when starting server and running pipeline

---

mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/FileTree/index.tsx
mage_ai/frontend/components/FileTree/utils.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx

- users can now re-add an existing block back to a pipeline via the file editor
cc: @johnson-mage @tommydangerous @dy46

[sp] implement "add block to current pipeline"

---

mage_ai/frontend/pages/pipelines/[...slug].tsx

[sp] refresh file browser when deleting scratchpad

---

mage_ai/data_cleaner/transformer_actions/utils.py
mage_ai/data_preparation/templates/transformers/transformer_action_fmt.jinja
mage_ai/tests/data_preparation/test_templates.py

Fixed some template generation bugs.
- Data frame not included in template
- Building action variables fails due to bad column types argument
cc:
@johnson-mage

[sk] Bug fixes for transformer action template generation

---

README.md

When you have to install, everytime you copy the commend you have to remove the dollar sign, i remove them so is more comfortable and easier
Well is a readme change i just had to render it
cc:

more comfortable installing from docs

---

mage_ai/server/server.py
scripts/start.sh

* try other ports if the initial port is not available.
* add `--service-ports` to the docker command which seems to fix localhost connection issue.
tested locally

[dy] Fix start up issues

---

setup.py

[td] Bump version 0.1.3

---

mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/DataSourceType.ts
mage_ai/frontend/interfaces/KeyboardShortcutType.ts
mage_ai/frontend/oracle/components/FlyoutMenu/FlyoutMenuWrapper.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

- Allow user to select data source type so that data loader template is generated in new data loader code block.
cc:

[jk] Data loader templates UI

---

mage_ai/data_preparation/templates/data_exporters/bigquery.py
mage_ai/data_preparation/templates/data_exporters/file.py
mage_ai/data_preparation/templates/data_exporters/postgres.py
mage_ai/data_preparation/templates/data_exporters/redshift.py
mage_ai/data_preparation/templates/data_exporters/s3.py
mage_ai/data_preparation/templates/data_exporters/snowflake.py
mage_ai/data_preparation/templates/data_loaders/bigquery.py
mage_ai/data_preparation/templates/data_loaders/file.py
mage_ai/data_preparation/templates/data_loaders/postgres.py
mage_ai/data_preparation/templates/data_loaders/redshift.py
mage_ai/data_preparation/templates/data_loaders/s3.py
mage_ai/data_preparation/templates/data_loaders/snowflake.py
mage_ai/io/file.py
mage_ai/tests/data_preparation/test_templates.py

Made two main modifications:
- For file IO, dropped configuration settings in favor of reading filepath
- For other IO methods, updated comments to refer to configuration settings in `io_config.yaml`
Unit tests updated to check newest templates are loaded correctly

[sk] Updated data IO templates for ease of use

---

mage_ai/command_line.py
mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/templates/repo/metadata.yaml
mage_ai/data_preparation/variable_manager.py
requirements.txt

This makes some changes to the library so that it can run in Airlfow
* Update dependencies to resolve conflicts
* Not update block status when running pipeline with command
* Allow specifying the variables path to resolve write permission issue.
Code for creating a BashOperator
```
from airflow import DAG
from airflow.operators.bash_operator import BashOperator
from datetime import datetime
from shared_utils.dag import DEFAULT_ARGS, DEFAULT_SETTINGS
from shared_utils.hash import merge_dict
import os
ABSOLUTE_PATH = os.path.abspath(os.path.dirname(__file__))
pipeline_path = os.path.join(ABSOLUTE_PATH, 'pipelines', 'pipeline_test')
dag = DAG(
'test_mage_pipeline',
default_args=merge_dict(DEFAULT_ARGS, {
'start_date': datetime(2022, 7, 14),
}),
description='Test running mage pipeline.', …
```

[xy] Support Airflow integration

---

mage_ai/tests/data_cleaner/cleaning_rules/test_remove_collinear_columns.py
mage_ai/tests/data_preparation/models/test_block.py

Fixed some unit tests associated with collinearity suggestions.
cc:

[sk] Fix collinearity suggestions unit tests

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/ContextMenu/index.tsx
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

- build generic right click context menu for use throughout data prep tool
- add context menu to the file browser (currently, the only action supported is deleting block files)
- display error popup box if user tries to delete a block file with dependencies 

[sp] add right click context menu

---

docs/production/airflow.md
mage_ai/__init__.py

Add doc for integrating with Airflow.
n/a
cc:

[xy] Add doc for integrating with Airflow.

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/constants.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/widget.py
mage_ai/server/api/base.py
mage_ai/server/api/widgets.py
mage_ai/server/server.py
mage_ai/tests/data_preparation/models/test_pipeline.py
scripts/server/test.sh

[td] Add widgets API

---

mage_ai/frontend/components/PipelineDetail/index.tsx

[td] Autosave when pasting content in block

---

mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/interfaces/DataSourceType.ts

[jk] Add generic data source option for data loader

---

mage_ai/data_preparation/models/block.py

Forgot to remove this method call.
tested locally
cc:

[dy] Fix run upstream

---

mage_ai/__init__.py
mage_ai/command_line.py

Fix no module error when using custom scripts from the project
tested in Airflow
cc:

[xy] Fix no module error when using custom scripts from the project

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx

- add expand/collapse carets for code blocks & code output
cc: @johnson-mage @tommydangerous @dy46

[sp] make blocks collapsible

---

Dockerfile

Update docker file to support spark kernel.
tested locally
cc:

[xy] Update docker file to support spark kernel.

---

mage_ai/data_cleaner/data_cleaner.py
mage_ai/data_cleaner/pipelines/base.py
mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.style.tsx
mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/interfaces/KernelOutputType.ts
mage_ai/server/websocket.py
mage_ai/shared/logger.py

Update pipeline to be executed asynchronously in a separate thread. Also added an initial display for the pipeline execution output.
tested locally

[dy] Add async pipeline execution

---

mage_ai/frontend/components/Sidekick/index.tsx

Move execute pipeline button under the dependency tree.
cc:

[dy] Change order of tree sidekick

---

docs/production/prefect.md

Add docs on how to use Prefect with Mage. Followed format of the Airflow docs.
tested locally by running the prefect flows 

[dy] Add prefect docs

---

mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.style.tsx
mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/oracle/styles/scrollbars.ts
mage_ai/frontend/oracle/styles/themes/dark.ts

- Make scrollbar lighter color to make it more visible.
- Only show file browser scrollbar on hover.

[jk]  Scrollbar styling

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/Sidekick/Charts/index.tsx
mage_ai/server/websocket.py

[td] Add chart default settings for histogram

---

docs/contributing/README.md
docs/contributing/charts/how_to_add.md
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/models/widget/constants.py
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/charts/PieChart.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/oracle/elements/Spacing/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/server/api/widgets.py

[td] Add docs for adding new chart

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/server/utils/output_display.py

Display number of rows and columns in the dataframe output.

[dy] Show number of rows and columns in df

---

mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/Sidekick/Charts/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/server/websocket.py

[td] Run chart blocks when changing settings

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/server/websocket.py

[td] Fix updating widget upstream

---

docs/contributing/charts/how_to_add.md
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/models/widget/constants.py
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.style.tsx
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/charts/BarGraphHorizontal.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/ChartBlockType.ts

[td] Adding bar charts

---

mage_ai/data_preparation/models/block.py

Don't check block status when running a pipeline.
tested locally

[dy] Run all blocks

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/utils.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/frontend/storage/localStorage.ts

- remove background on "Expand output" caret
- make "Expand output" text clickable in addition to caret
- persist collapsed blocks on page reload

[sp] update collapsible blocks

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/DataTable/index.tsx

[td] Fix double table index output

---

docs/contributing/charts/how_to_add.md
mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/models/widget/constants.py
mage_ai/data_preparation/models/widget/utils.py
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/server/utils/output_display.py
mage_ai/server/websocket.py

[td] Add chart type table

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/ChartBlock/index.style.tsx
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/Sidekick/Charts/index.tsx
mage_ai/frontend/components/shared/Grid/Col.tsx
mage_ai/frontend/components/shared/Grid/Row.tsx
mage_ai/frontend/components/shared/Grid/index.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx

[td] Adjust chart width

---

docs/contributing/README.md
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/models/widget/constants.py
mage_ai/data_preparation/models/widget/utils.py
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/utils.ts
mage_ai/frontend/components/charts/LineSeries.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts

[td] Add line chart

---

mage_ai/data_preparation/models/widget/utils.py
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts

[td] Support multi-lines in line chart

---

mage_ai/server/server.py

Fix pipeline creation.
tested locally
cc:

[xy] Fix pipeline creation.

---

mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/models/widget/charts.py
mage_ai/data_preparation/models/widget/utils.py
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/charts/Histogram.tsx
mage_ai/frontend/components/charts/LineSeries.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/server/server.py
mage_ai/shared/parsers.py

[td] Fix histogram and bar charts

---

mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts

[td] Add legend names to line series

---

mage_ai/__init__.py
mage_ai/command_line.py
mage_ai/data_cleaner/shared/utils.py
mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/templates/template.py
mage_ai/data_preparation/templates/utils.py
mage_ai/io/export_utils.py
mage_ai/shared/utils.py

Speed up `mage init` by reducing unnecessary dependency import when executing the command line.
tested locally
mage init time was reduced from 1.3s to 0.5s
cc:

[xy] Speed up mage init.

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/models/widget/utils.py
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/charts/BarChartHorizontal.tsx
mage_ai/frontend/components/charts/Histogram.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/server/utils/output_display.py
mage_ai/shared/parsers.py

[td] Histogram no code

---

README.md

Add docs of running pipeline to README.
n/a
cc:

[xy] Add docs of running pipeline to README

---

mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/models/widget/charts.py
mage_ai/data_preparation/models/widget/constants.py
mage_ai/data_preparation/models/widget/utils.py
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/charts/BarChartHorizontal.tsx
mage_ai/frontend/components/charts/Histogram.tsx
mage_ai/frontend/components/charts/LineSeries.tsx
mage_ai/frontend/components/charts/PieChart.tsx
mage_ai/frontend/components/charts/shared/YAxisLabelContainer.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/server/app.py
mage_ai/server/data/base.py
mage_ai/shared/parsers.py
requirements.txt

[td] Support time series line chart

---

mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/models/widget/constants.py
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/charts/Histogram.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts

[td] Time series bar chart

---

mage_ai/data_preparation/models/block.py

Delete chart file when deleting it from pipeline.
tested locally
cc:

[xy] Delete chart file when deleting it from pipeline.

---

mage_ai/data_preparation/models/widget/charts.py
mage_ai/data_preparation/models/widget/utils.py
mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/charts/BarChart/constants.ts
mage_ai/frontend/components/charts/BarChart/utils.tsx
mage_ai/frontend/components/charts/BarChartHorizontal.tsx
mage_ai/frontend/components/charts/BarChartVertical.tsx
mage_ai/frontend/utils/string.ts

[td] Multi bar chart

---

mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/CodeBlock/CommandButtons/index.style.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/charts/BarChartHorizontal.tsx

[td] Add template for missing values

---

mage_ai/frontend/components/CodeBlock/index.tsx

[td] Automatically add parent block

---

mage_ai/frontend/components/CodeBlock/index.tsx

[sp] expand output when running block

---

mage_ai/data_cleaner/shared/utils.py
mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/variable_manager.py
mage_ai/server/kernels.py
mage_ai/server/server.py
mage_ai/server/utils/output_display.py
mage_ai/server/websocket.py
requirements.txt

Support running pipelines in pyspark
* Add RepoConfig, which allows user to specify variables_dir path
* Support storing variables in S3 path
* Pass pipeline_config and repo_config to code execution
tested with a spark cluster
cc:

[xy] Support running pipelines in pyspark

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/interfaces/BlockType.ts

- See title
cc:
@tommydangerous @wangxiaoyou1993

[jk] Add text to expand table button

---

mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DataTable/index.tsx
mage_ai/frontend/components/charts/BarChart/utils.tsx

[td] Add feature profile

---

docs/kernels/README.md

[xy] Add doc for kernels.

---

mage_ai/data_preparation/templates/data_loaders/api.py
mage_ai/io/base.py
mage_ai/tests/data_preparation/test_templates.py

Added data loader template to load data from the result of an API request (launched through the `requests` library)
Tested locally + updated unit tests for template generation.
cc:

[sk] Added API-based data loader template

---

mage_ai/frontend/components/ChartBlock/ChartController.tsx
mage_ai/frontend/components/charts/BarChart/constants.ts
mage_ai/frontend/components/charts/BarChart/utils.tsx
mage_ai/frontend/components/charts/BarChartHorizontal.tsx
mage_ai/frontend/components/charts/BarChartVertical.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Chart empty state

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/DataTable/index.tsx

[td] Fix scrolling code output table

---

docs/kernels/README.md

Add how to set variables dir to spark kernel doc.
n/a
cc:

[xy] Update spark kernel doc

---

mage_ai/frontend/components/CodeBlock/CommandButtons/AddChartMenu.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Add menu for adding chart

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx

[td] Don’t add upstream if data loader

---

mage_ai/data_preparation/models/widget/charts.py
mage_ai/frontend/components/ChartBlock/constants.ts

[td] Fix bugs again

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/DataTable/index.tsx

[td] Adjust code output table max height

---

mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.style.tsx
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/AddChartMenu.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/Sidekick/Charts/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/charts/BarChart/utils.tsx
mage_ai/frontend/components/charts/BarChartVertical.tsx
mage_ai/frontend/oracle/elements/Link/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Edit chart block names

---

mage_ai/frontend/components/FileBrowser/Folder.tsx

[td] Update pipeline icon

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/widget/__init__.py

When deleting a block, all downstream charts are removed. If a block has both downstream blocks and downstream charts, the block cannot be deleted until all downstream blocks are removed. Chart block files are deleted when their upstream block is deleted.
cc:

[sk] Deleting a block also removes downstream charts

---

setup.py

[td] Bump version to 0.1.4

---

mage_ai/data_cleaner/data_cleaner.py
mage_ai/data_cleaner/statistics/calculator.py
mage_ai/data_preparation/models/block.py
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/PipelineDetail/utils.ts
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/io/base.py
mage_ai/io/file.py

Move the rows and columns indicator into the extra content block. Also, show the indicator on refresh.
cc: @wangxiaoyou1993 for backend changes. not sure if the way I calculated the df shape is the best

[dy] Update df size

---

mage_ai/frontend/components/Sidekick/index.tsx

- Fixed minor UI bug.
- Local
cc:

[jk] Hide message when no block selected on data view

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/interfaces/KernelOutputType.ts
mage_ai/server/kernel_output_parser.py
mage_ai/server/kernels.py
mage_ai/server/utils/output_display.py
mage_ai/server/websocket.py

Show spark kernel output. The `FloatProgress` doesn't render properly atm. I'll see if I can get it to render properly in a future PR.
local

[dy] Support spark kernel output

---

mage_ai/frontend/api/utils/url.ts
mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

Added code to dynamically get the websocket URL from the current host and port.
Tested by running app on AWS EC2, was able to run code on the kernel when not connected through local host.
cc:
@johnson-mage

[sk] Dynamic WebSocket URL Resolution

---

mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeEditor/autocomplete/constants.ts
mage_ai/frontend/components/CodeEditor/autocomplete/index.ts
mage_ai/frontend/components/CodeEditor/autocomplete/test.ts
mage_ai/frontend/components/CodeEditor/autocomplete/utils.ts
mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/Sidekick/GlobalVariables.tsx
mage_ai/frontend/components/charts/Histogram.tsx
mage_ai/server/websocket.py

[td] Add autocomplete

---

mage_ai/frontend/components/CodeEditor/autocomplete/index.ts

[td] Get the most recent defined variable and its columns

---

mage_ai/autocomplete/utils.py
mage_ai/data_cleaner/transformer_actions/constants.py
mage_ai/frontend/components/CodeEditor/autocomplete/constants.ts
mage_ai/frontend/components/CodeEditor/autocomplete/importLibraries.ts
mage_ai/frontend/components/CodeEditor/autocomplete/index.ts
mage_ai/frontend/components/CodeEditor/autocomplete/test.json
mage_ai/frontend/components/CodeEditor/autocomplete/utils.ts
mage_ai/frontend/components/CodeEditor/index.tsx
mage_ai/server/utils/output_display.py
mage_ai/shared/utils.py

[td] Autocomplete for imports

---

mage_ai/autocomplete/utils.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeEditor/autocomplete/constants.ts
mage_ai/frontend/components/CodeEditor/autocomplete/importLibraries.ts
mage_ai/frontend/components/CodeEditor/autocomplete/index.ts
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/AutocompleteItemType.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/server/api/autocomplete_items.py
mage_ai/server/server.py

[td] Add API for autocomplete items

---

docs/tutorials/train_titanic_model/README.md

Added the steps to run the pipeline from docker and UI
NA, as it is a doc update
cc:

[docs update] Add how to run pipepline from docker and UI

---

mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[jk] Open sidekick when expanding table if it's hidden

---

mage_ai/data_preparation/models/block.py
mage_ai/server/utils/output_display.py
mage_ai/server/websocket.py

Save pyspark output to local and analyze result.
* `%%spark -o df --maxrows 10000`: save a remote variable to local
* `%%local`: execute code locally
This PR also supports building charts for output of pyspark blocks.
tested locally
cc: @dy46

[xy] Save pyspark output to local and analyze result.

---

mage_ai/frontend/components/DataTable/index.tsx

- See title.
Before:
After:
cc:
@skunichetty

[jk] Fix column header alignment in block output table

---

mage_ai/frontend/components/CodeEditor/autocomplete/functions.ts
mage_ai/frontend/components/CodeEditor/autocomplete/index.ts

[td] Autocomplete functions from imported modules

---

mage_ai/data_cleaner/cleaning_rules/remove_collinear_columns.py

Fix collinear rule.
tested locally
cc:

[xy] Fix collinear rule.

---

mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/ChartBlock/index.style.tsx
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeEditor/autocomplete/constants.ts
mage_ai/frontend/components/CodeEditor/autocomplete/functions.ts
mage_ai/frontend/components/CodeEditor/autocomplete/index.ts
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/charts/BarChartVertical.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Autocomplete for chart blocks

---

mage_ai/data_preparation/templates/data_loaders/snowflake.py

Fix snowflake data loader.
tested locally
cc:

[xy] Fix snowflake data loader.

---

mage_ai/frontend/components/ChartBlock/constants.ts
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeEditor/autocomplete/functions.ts
mage_ai/frontend/components/CodeEditor/autocomplete/index.ts
mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/io/base.py

[td] Autocomplete bug tweaks

---

mage_ai/data_preparation/templates/data_exporters/postgres.py

Added parameter to Postgres data exporter.
cc:
@tommydangerous @wangxiaoyou1993

[sk] Fixed Postgres template

---

docs/production/runtime_variables.md

Added docs for using runtime variables. The `Creating Runtime Variables In-Editor` section is left empty since in-editor support for adding runtime variables hasn't been added yet.
cc:

[sk] Added runtime variable docs

---

mage_ai/frontend/components/CodeBlock/CommandButtons/AddChartMenu.tsx
mage_ai/frontend/components/CodeBlock/index.style.tsx
mage_ai/frontend/components/CodeBlock/index.tsx

[td] Show timer when running block

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx

- See title.
Before:
After:
cc:

[jk] Fix addNewBlockMenu dropdown hiding bug when hovering over another block

---

mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Do not save when file not active

---

mage_ai/server/server.py

Don't save empty content in file update endpoint.
tested locally
cc:

[xy] Don't save empty content in file update endpoint.

---

mage_ai/data_cleaner/column_types/column_type_detector.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/models/widget/charts.py
mage_ai/io/snowflake.py

This PR includes a couple of fixes and improves performance
* Fix empty response from Snowflake loader execute method
For a dataset with 10 million rows
* Speed up column type detection. Reduce summary overview chart plot time from 98s to 2s.
* Speed up histogram calculation. Reduce time from 7.3s to 1.2s
tested locally
cc:

[xy] Fix data loaders and improve performance

---

mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/api/utils/fetcher.ts
mage_ai/frontend/api/utils/use.ts
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Save content when updating names

---

mage_ai/data_preparation/models/widget/__init__.py
mage_ai/frontend/components/ChartBlock/constants.ts

Speed up multiple charts.
Benchmark: for a dataset with 10 million rows
* Pie chart: 1s -> 0.6s
* Unique values: 2.9s -> 1s
* Most frequent values: 3.1s -> 2.4s
tested locally
cc:

[xy] Speed up charts.

---

docs/production/airflow.md
mage_ai/orchestration/airflow.py

Add script to create airflow dags.
tested in airflow
cc:

[xy] Add script to create airflow dags.

---

mage_ai/frontend/components/CodeBlock/index.tsx

[td] Fix shift enter double outputs

---

mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Click enter to update pipeline and block names

---

mage_ai/data_preparation/models/constants.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/server/active_kernel.py
mage_ai/server/kernel_output_parser.py
mage_ai/server/kernels.py
mage_ai/server/server.py
mage_ai/server/subscriber.py
mage_ai/server/websocket.py

Allow users to configure their kernel from the frontend.
For the backend, I created an `active_kernel` module that keeps track of which kernel is currently active. It provides helper methods for switching the active kernel as well as other methods for interacting with the kernel.
tested locally

[dy] Kernel selection

---

mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] When adding a chart, scroll it into view

---

mage_ai/data_preparation/models/pipeline.py

Update widget's upstream blocks correctly when updating block name.
Airtable story: https://airtable.com/app1CBJ4fMHEq1S9t/tblciQzZZoqLRPTKR/viwkAKwAPcuOkucn9/rec2jXdsrT96PgfWo?blocks=hide
tested locally
cc:

[xy] Fix pipeline update

---

mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/ContextMenu/index.tsx
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/components/PipelineDetail/utils.ts
mage_ai/frontend/components/utils.ts
mage_ai/frontend/oracle/components/FlyoutMenu/index.style.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

- add "Delete" and "Duplicate" to the file browser context menu when right clicking on a block

[sp] add "delete" and "duplicate" functionality for pipelines

---

mage_ai/server/utils/output_display.py

Use raw string for code. Fix the issue below:
tested locally

[xy] Use raw string for code.

---

mage_ai/frontend/components/PipelineDetail/index.tsx

[td] When navigating with arrow, scroll block into view

---

mage_ai/server/utils/output_display.py

Escape three single quotes in code to fix syntax error.
tested locally
cc:

[xy] Escape three single quotes in code.

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/RecommendationsWindow/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[jk] Include upstream dependency when adding block from rec

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/server/api/widgets.py
mage_ai/server/server.py

* Cache pipeline, and block content and outputs. Reduce the API of fetching a pipeline from 400ms to 20ms.
tested locally
cc:

[xy] Speed up Mage APIs

---

mage_ai/data_preparation/models/block.py

Fetch outputs from disk when it's empty.
tested locally
cc:

[xy] Fetch outputs from disk when it's empty.

---

mage_ai/data_preparation/models/pipeline.py

Disable cache temporarily to fix block status update issue.
tested locally
cc:

[xy] Disable cache temporarily.

---

mage_ai/autocomplete/utils.py
mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/utils/block/convert_content.py
mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/server/server.py
mage_ai/server/utils/output_display.py

[td] Improve block conversion

---

mage_ai/frontend/components/RecommendationsWindow/index.style.ts
mage_ai/frontend/components/RecommendationsWindow/index.tsx

[jk] Disable hover effect when no recs available

---

mage_ai/server/utils/output_display.py

[td] Fix warning message from pandas messing up table output

---

setup.py

[td] Bump version 0.1.5

---

mage_ai/data_preparation/models/pipeline.py
setup.py

[td] Upgrade to 0.2.0

---

mage_ai/data_preparation/templates/data_loaders/bigquery.py
mage_ai/data_preparation/templates/data_loaders/default.jinja
mage_ai/data_preparation/templates/data_loaders/postgres.py
mage_ai/data_preparation/templates/data_loaders/redshift.py
mage_ai/data_preparation/templates/data_loaders/s3.py
mage_ai/data_preparation/templates/data_loaders/snowflake.py
mage_ai/data_preparation/templates/transformers/data_warehouse_transformer.jinja
mage_ai/data_preparation/templates/transformers/default.jinja
mage_ai/data_preparation/templates/transformers/transformer_actions/column/average.py
mage_ai/data_preparation/templates/transformers/transformer_actions/column/count.py
mage_ai/data_preparation/templates/transformers/transformer_actions/column/count_distinct.py
mage_ai/data_preparation/templates/transformers/transformer_actions/column/first.py
mage_ai/data_preparation/templates/transformers/transformer_actions/column/last.py
mage_ai/data_preparation/templates/transformers/transformer_actions/column/max.py
mage_ai/data_preparation/templates/transformers/transformer_actions/column/median.py
mage_ai/data_preparation/templates/transformers/transformer_actions/column/min.py
mage_ai/data_preparation/templates/transformers/transformer_actions/column/sum.py
mage_ai/tests/data_preparation/test_templates.py

Update code templates.
* Remove unnecessary import
* Reduce the outputs to only contain one item
tested locally
cc:

[xy] Update code templates.

---

mage_ai/server/api/autocomplete_items.py
setup.py

[td] Fix autocomplete file loading and bump 0.2.1

---

mage_ai/autocomplete/utils.py
mage_ai/server/api/autocomplete_items.py

[td] Fix autocomplete file path reading and bump to 0.2.2

---

Dockerfile
docs/kernels/README.md
mage_ai/server/active_kernel.py
mage_ai/server/utils/frontend_renderer.py
requirements.txt

Reduce the dependencies for mage-ai library
tested locally
cc:

[xy] Reduce the dependencies for mage-ai library

---

mage_ai/frontend/components/ChartBlock/index.tsx
setup.py

[td] Resize chart even when sliding the width of sidekick

---

mage_ai/autocomplete/utils.py
setup.py

[td] Fix imports and bump 0.2.3

---

mage_ai/deployment/templates/ecs.yaml
scripts/deploy/ecs.sh
scripts/deploy/ecs.yaml

Add cloudformation template for deploying to ecs cluster.
Create ECS cluster
```
./scripts/deploy/create_ecs.sh [subnet_id]
```
Update ECS cluster
```
./scripts/deploy/update_ecs.sh [subnet_id]
```
TODOs
tested by running the script
Issues fixed during testing
* exec format error: https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error
cc:

[xy] Add cloudformation template for deploying to ecs cluster.

---

mage_ai/orchestration/airflow.py

[td] Fix airflow callable args ds

---

docs/production/airflow.md
mage_ai/orchestration/airflow.py

[td] Add globals_dict to airflow create_dags

---

setup.py

[td] Bump version 0.2.4

---

mage_ai/orchestration/airflow.py
setup.py

[td] Don’t create DAG unless 1 or more blocks

---

mage_ai/autocomplete/utils.py
mage_ai/server/api/autocomplete_items.py
setup.py

[td] Bump 0.2.6 and fix autocomplete

---

mage_ai/services/emr/config.py
mage_ai/services/emr/emr.py
scripts/spark/create_cluster.py

Add script to create emr cluster.
tested locally
cc:

[xy] Add script to create emr cluster.

---

mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/templates/repo/data_exporters/export_titanic_clean.py
mage_ai/data_preparation/templates/repo/data_loaders/load_titanic.py
mage_ai/data_preparation/templates/repo/pipelines/example_pipeline/metadata.yaml
mage_ai/data_preparation/templates/repo/transformers/fill_in_missing_values.py

Add example pipeline when initiating a project.
tested locally
cc:

[xy] Add example pipeline.

---

.github/workflows/publish_docker_image.yml
Dockerfile_prod

Add github action to publish docker image.
to be tested in production
cc:

[xy] Add github action to publish docker image.

---

.github/workflows/publish_docker_image.yml

Update the tag of mageai image. 
to be tested on production
cc:

[xy] Update the tag of mageai image.

---

.github/workflows/publish_docker_image.yml

Set up docker buildx to fix multi-platform build issue.
Error: https://github.com/mage-ai/mage-ai/runs/7735478317?check_suite_focus=true
Fix: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
to be tested in production.
cc:

[xy] Set up docker buildx.

---

docs/tutorials/airflow/integrate_into_existing_project/README.md

[td] Update Docker image in README

---

README.md
docs/tutorials/airflow/integrate_into_existing_project/README.md
docs/tutorials/quick_start/setup.md

[td] Update docker in readme

---

mage_ai/data_preparation/pipeline_executor.py
mage_ai/data_preparation/repo_manager.py
mage_ai/services/emr/emr.py
mage_ai/services/emr/resource_manager.py
scripts/spark/create_cluster.py

Upload bootstrap script before launching cluster.
tested locally
cc:

[xy] Upload bootstrap script before launching cluster.

---

README.md
docs/kernels/README.md

Update doc for using spark kernel
n/a
cc:

[xy] Update doc for spark kernel

---

mage_ai/data_preparation/models/block.py
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/server/utils/output_display.py

[td] Limit the number of columns returned to output table

---

setup.py

[td] Bump v0.2.7

---

mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/models/constants.py
mage_ai/tests/data_preparation/models/test_block.py
mage_ai/tests/data_preparation/models/test_pipeline.py

[td] Add block language

---

mage_ai/data_preparation/templates/data_loaders/api.py
mage_ai/data_preparation/templates/repo/data_loaders/load_titanic.py
mage_ai/tests/data_preparation/test_templates.py

Fix code template for load_data_from_api.
tested locally
cc:

[xy] Fix code template for load_data_from_api.

---

setup.py

Bump version to 0.2.8.
n/a
cc:

[xy] Bump version to 0.2.8.

---

mage_ai/command_line.py

[dy] Add help command

---

mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

Add execute and cancel pipe line to run menu
tested locally
cc:

[dy] Add execute pipeline to run menu

---

mage_ai/data_preparation/variable_manager.py

Fix get variable. Pass the `spark` parameter to `get_variable_object` method.
to be tested on spark
cc:

[xy] Fix get variable.

---

docs/production/airflow.md
mage_ai/__init__.py
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/executors/ecs_block_executor.py
mage_ai/data_preparation/executors/executor_factory.py
mage_ai/data_preparation/executors/k8s_block_executor.py
mage_ai/data_preparation/executors/pipeline_executor.py
mage_ai/data_preparation/executors/pyspark_block_executor.py
mage_ai/data_preparation/executors/pyspark_pipeline_executor.py
mage_ai/data_preparation/models/constants.py
mage_ai/data_preparation/templates/pipeline_execution/spark_script.jinja
mage_ai/orchestration/airflow.py

Create executors module, which include the following executors
* Block executors
* Base block executor
* PySpark block executor
* Ecs block executor (to be implemented)
* K8s block executor (to be implemented)
* Pipeline executor
* Base pipeline executor
* PySpark block executor
tested block executors with airflow dags
cc:

[xy] Create executors module.

---

mage_ai/services/emr/config.py

[td] Comment out required EMR config values

---

docs/kernels/README.md
mage_ai/services/emr/config.py

Make security group optional. Use EMR-managed security groups by default: https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-man-sec-groups.html
tested locally
cc:

[xy] Make security group optional.

---

mage_ai/command_line.py
mage_ai/data_preparation/models/block.py
mage_ai/data_preparation/variable_manager.py
mage_ai/services/emr/launcher.py
scripts/spark/create_cluster.py

This PR includes some polish for pyspark kernel
* Support fetching variables with spark context
* Add command line for creating spark cluster
* Convert pandas dataframe to pyspark dataframe before storing variable
tested with spark cluster
cc:

[xy] Some polish for pyspark kernel

---

README.md
docker-compose.yml
docs/README.md
docs/spark/setup/README.md

[td] Add Spark tutorial

---

setup.py

Bump version to 0.2.9.
n/a
cc:

[xy] Bump version to 0.2.9.

---

mage_ai/data_preparation/models/block/__init__.py

[td] Move block.py to block init

---

Dockerfile_prod

Update Dockerfile prod to install the whole mage-ai package.
tested locally
cc:

[xy] Update Dockerfile prod to install the whole mage-ai package.

---

docs/kernels/README.md
mage_ai/data_preparation/templates/repo/metadata.yaml

Include ec2_key_name in project's metadata.yaml template
n/a
cc:

[xy] Include ec2_key_name in project's metadata.yaml template

---

setup.py

Bump version to 0.2.10.
n/a
cc:

[xy] Bump version to 0.2.10.

---

docker-compose.yml
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/models/widget/__init__.py
mage_ai/data_preparation/templates/template.py
mage_ai/frontend/api/index.ts
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/FileEditor/index.tsx
mage_ai/frontend/components/FileTree/utils.ts
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.ts
mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/BlockType.ts
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/frontend/interfaces/DataProviderType.ts
mage_ai/frontend/interfaces/FileType.ts
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/io/postgres.py
mage_ai/server/api/blocks.py
mage_ai/server/api/data_providers.py
mage_ai/server/api/widgets.py
mage_ai/server/server.py
mage_ai/server/utils/output_display.py
mage_ai/tests/data_preparation/models/test_block.py
mage_ai/tests/data_preparation/models/test_pipeline.py

[td] Add SQL block

---

mage_ai/services/emr/config.py

Use on demand instance for EMR cluster.
tested locally
cc:

[xy] Use on demand instance for EMR cluster.

---

Dockerfile
README.md
docs/README.md
docs/spark/setup/README.md
mage_ai/services/emr/emr.py

[td] Update PySpark setup docs

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/frontend/components/ChartBlock/index.tsx
mage_ai/frontend/components/CodeBlock/CommandButtons/AddChartMenu.tsx
mage_ai/server/api/widgets.py

[td] SQL block charts

---

docs/spark/setup/README.md
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/server/active_kernel.py

[td] Don’t show SQL blocks for PySpark kernel

---

mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx

[jk] Fix positioning of nested flyout menus

---

requirements.txt
setup.py

Make sqlalchemy a required dependency to resolve import errors.
tested locally
cc:

[xy] Make sqlalchemy required.

---

mage_ai/cli/main.py
scripts/init.sh
scripts/run.sh
scripts/run_ec2.sh
scripts/start.sh

Update scripts to use the new cli module.

[dy] Update scripts

---

scripts/deploy/ecs.yaml

Update cloudformation template to mount EFS to ECS task.
tested locally by updating the stack. EFS is successfully mounted to the ECS Fargate task.
cc:

[xy] Mount EFS to ECS task.

---

scripts/deploy/ecs.yaml

Update EFS mount path to /home/src so that the pipeline code can be shared across tasks.
tested by updating the stack. verify the pipeline code can be shared across tasks.
cc:

[xy] Update EFS mount path.

---

mage_ai/data_preparation/templates/repo/io_config.yaml

[td] Remove optional text in SNOWFLAKE_DEFAULT_WH

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/orchestration/db/models.py
mage_ai/server/api/orchestration.py
mage_ai/server/server.py

Add PipelineRun and BlockRun APIs.
Tech design: https://www.notion.so/mageai/Orchestration-engine-a5ed63c71c594801897fb9df3c9fefb7#8c2a9a1075194ead9ae5bfcd388c4944
tested locally
cc:

[xy] Add PipelineRun and BlockRun APIs.

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/snowflake.py
mage_ai/data_preparation/templates/data_exporters/snowflake.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/io/postgres.py
mage_ai/io/snowflake.py
mage_ai/server/api/data_providers.py
mage_ai/tests/data_preparation/test_templates.py

[td] Support Snowflake SQL block

---

scripts/deploy/ecs.yaml

Use image from docker hub.
tested locally by updating the stack
cc:

[xy] Use image from docker hub.

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/io/postgres.py
mage_ai/io/snowflake.py

[td] Improve verbose for SQL blocks

---

docs/production/runtime_variables.md

Update runtime variables documentation

[dy] Update docs

---

mage_ai/server/websocket.py

Accidentally was saving the pipeline config twice. Also, fixed another bug related to runtime variables.
tested locally
cc:

[dy] Fix duplicate folder bug

---

mage_ai/data_cleaner/column_types/column_type_detector.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/redshift.py
mage_ai/data_preparation/templates/data_exporters/redshift.py
mage_ai/io/redshift.py
mage_ai/server/api/data_providers.py
mage_ai/shared/utils.py

Support SQL blocks using Redshift data provider.
cc:

[td] Support Redshift as a data provider

---

mage_ai/cli/main.py
mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/orchestration/db/migrations/versions/c07a23ff782b_add_initial_tables.py
mage_ai/orchestration/db/models.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/orchestration/scheduler_manager.py
mage_ai/orchestration/triggers/loop_time_trigger.py
mage_ai/orchestration/triggers/time_trigger.py
mage_ai/server/api/orchestration.py
mage_ai/server/server.py

Add pipeline scheduler.
Tech design: https://www.notion.so/mageai/Orchestration-engine-a5ed63c71c594801897fb9df3c9fefb7
tested locally
Create a pipeline schedule with hourly interval
New pipeline runs get created and completed every hour.
cc: @dy46

[xy] Add pipeline scheduler.

---

mage_ai/server/api/blocks.py

Fix the issue of adding duplicate block dependency.
tested locally
cc:

[xy] Not add duplicate block dependency.

---

mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Save content before running block to always persist changes

---

mage_ai/frontend/pages/pipelines/[...slug].tsx

[dy] Add null check

---

mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/data_preparation/models/block/sql/redshift.py
mage_ai/data_preparation/models/block/sql/snowflake.py
mage_ai/data_preparation/models/block/sql/utils/shared.py

[td] Support SQL block regex with no spaces

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py

Save outputs for other block types.
tested locally
cc:

[xy] Save outputs for other block types.

---

mage_ai/data_preparation/models/block/__init__.py

Return all variables in response.
tested locally
cc:

[xy] Return all variables in response.

---

setup.py

Bump version to 0.3.0.
n/a
cc:

[xy] Bump version to 0.3.0.

---

mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Fix scratchpad double outputs

---

setup.py

[td] Bump version to 0.3.1

---

docs/tutorials/quick_start/etl_restaurant/README.md
docs/tutorials/quick_start/train_titanic_model/README.md

[td] Update tutorials

---

mage_ai/cli/main.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/pipeline_executor.py
mage_ai/io/config.py

Since we make some dependencies optional, we shouldn't require some import statements when starting the server or running the pipelines.
tested locally
cc:

[xy] Update dependencies

---

setup.py

Bump version to 0.3.2.
n/a
cc:

[xy] Bump version to 0.3.2.

---

mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/PipelineDetail/Header.tsx
mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
mage_ai/frontend/components/PipelineDetail/index.style.tsx
mage_ai/frontend/components/Sidekick/index.style.ts
mage_ai/frontend/components/Sidekick/index.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/oracle/icons/custom/Develop.tsx
mage_ai/frontend/oracle/icons/custom/Orchestrate.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

Add page header according to figma designs. Also add ability to switch between develop and jobs view. The "Jobs" button is hidden for now.
local

[dy] Add page header

---

.github/workflows/publish_docker_image.yml

Allow selecting branch and name when building and pushing docker image
to be tested in Github Action after this PR is merged
cc:

[xy] Allow selecting branch and name when building and pushing docker image

---

setup.py

Bump version to 0.3.3.
n/a
cc:

[xy] Bump version to 0.3.3.

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx

[td] Fix outputs of blocks flickering

---

mage_ai/frontend/components/Sidekick/GlobalVariables/index.tsx

Update copy text for block variables to include the import statement and single quotes for proper python syntax.
locally
cc:

[dy] Fix copy for block variables

---

mage_ai/data_preparation/templates/repo/io_config.yaml
mage_ai/server/api/data_providers.py
mage_ai/server/server.py

[td] Fix profiles not showing

---

setup.py

[td] Bump to 0.3.4

---

scripts/deploy/ecs.yaml

Update cloudformation template to create load balancer.
The hosted tool can be accessed via http://demo.mage.ai now.
tested by running the update-stack command
cc:

[xy] Update cloudformation template to create load balancer.

---

mage_ai/data_preparation/models/file.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/variable_manager.py
mage_ai/tests/data_preparation/test_variable_manager.py

Only fetch variables from block uuid folder or global folder.
Skip scanning variables and logs folders when fetching file list.
tested locally
cc:

[xy] Fix fetching variables.

---

.gitignore

Ignore db files.
tested locally
cc:

[xy] Ignore db files.

---

mage_ai/frontend/components/PipelineDetail/Header.tsx
mage_ai/frontend/components/PipelineDetail/utils.ts
mage_ai/frontend/components/PipelineList/index.tsx
mage_ai/frontend/pages/index.tsx
mage_ai/frontend/pages/pipelines/[...slug].tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/server/server.py

[td] Update pipelines index API endpoint to return data

---

mage_ai/server/api/orchestration.py

Catch DB error to not return stacktrace.
tested locally
cc:

[xy] Catch DB error.

---

mage_ai/server/server.py

This fixes the issue when executing the pipeline on mac, but it won't work for windows. I'll continue looking into the issue. 
tested locally

[dy] Temporary execute pipeline fix

---

mage_ai/server/server.py

Revert "[dy] Temporary execute pipeline fix"

---

mage_ai/frontend/components/Dashboard/Subheader.tsx
mage_ai/frontend/components/Dashboard/index.style.tsx
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
mage_ai/frontend/oracle/styles/colors/gradients.ts
mage_ai/frontend/pages/_app.tsx
mage_ai/frontend/pages/pipelines/index.tsx

[td] Add subheader to dashboard

---

mage_ai/frontend/components/Dashboard/index.style.tsx
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/oracle/components/FlexTable/index.tsx
mage_ai/frontend/oracle/styles/themes/dark.ts
mage_ai/frontend/pages/pipelines/[pipeline].tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/frontend/styles/globals.css

[td] Display table for pipelines

---

.gitignore
scripts/deploy/terraform/iam.tf
scripts/deploy/terraform/main.tf
scripts/deploy/terraform/networking.tf
scripts/deploy/terraform/variables.tf
scripts/deploy/terraform/vpc.tf

Add terraform script to deploy to ECS.
Follow the blog post: https://dev.to/thnery/create-an-aws-ecs-cluster-using-terraform-g80
TODOs
tested locally by running
```
terraform init
terraform validate
terraform apply
```
cc:

[xy] Add terraform script to deploy to ECS.

---

mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/FileBrowser/Folder.tsx
mage_ai/frontend/components/FileBrowser/index.tsx
mage_ai/frontend/components/PipelineDetail/constants.ts
mage_ai/frontend/components/PipelineLayout/index.tsx
mage_ai/frontend/components/TripleLayout/index.style.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline].tsx

[td] Update nav with new header

---

mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/pages/pipelines/index.tsx

[td] Change pipeline to edit

---

scripts/deploy/ecs.yaml
scripts/deploy/terraform/alb.tf
scripts/deploy/terraform/efs.tf
scripts/deploy/terraform/main.tf
scripts/deploy/terraform/variables.tf

Add load balancer and EFS to terraform script.
tested locally with `terraform apply`
cc:

[xy] Add load balancer and EFS to terraform script

---

mage_ai/frontend/interfaces/PipelineType.ts
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/server/server.py

[td] Pause pipeline schedules from pipelines list view

---

mage_ai/server/execution_manager.py
mage_ai/server/websocket.py

I was having trouble writing messages to the web socket server in the new process, so I decided to have the separate process write to the multithreading queue. Then, a task on the main process would periodically poll the queue for new messages and publish it to the web socket server. 
tested locally

[dy] Fix pipeline execution bug 

---

mage_ai/io/base.py

Fix s3 loading.
tested locally
cc:

[xy] Fix s3 loading.

---

mage_ai/frontend/components/Dashboard/index.style.tsx
mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/pages/pipeline-runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/block-runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx

[td] Add triple layout to dashboard

---

mage_ai/frontend/components/Orchestration/CreateSchedule/index.tsx
mage_ai/frontend/components/Sidekick/utils.ts
mage_ai/frontend/oracle/elements/Inputs/ToggleSwitch.tsx

Overwrite global variables in schedule creation page.
tested locally.
cc:

[dy] Runtime variables

---

requirements.txt

Remove unused dependencies.
tested locally
cc:

[xy] Reduce dependencies.

---

mage_ai/data_preparation/models/block/__init__.py

Fix None issue when saving outputs.
tested locally
cc:

[xy] Fix None issue when saving outputs.

---

mage_ai/data_preparation/models/block/__init__.py

Log block run stacktrace.
tested locally
cc:

[xy] Log block run exception stacktrace.

---

mage_ai/data_preparation/models/pipeline.py

Fix nonetype error when loading pipeline.
Issue: https://github.com/mage-ai/mage-ai/issues/968
tested locally
cc:

[xy] Fix nonetype error when loading pipeline.

---

mage_ai/server/websocket.py

The output for scratchpad was not being shown in the UI correctly. This fixes that issue.
local
cc:

[dy] Fix output error

---

mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/Logs/Filter/index.style.tsx
mage_ai/frontend/components/Logs/Filter/index.tsx
mage_ai/frontend/components/Logs/index.style.tsx
mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/components/TripleLayout/index.tsx
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/interfaces/LogType.ts
mage_ai/frontend/oracle/elements/Checkbox/index.tsx
mage_ai/frontend/oracle/styles/themes/dark.ts
mage_ai/frontend/oracle/styles/units/borders.ts
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/frontend/utils/hash.ts
mage_ai/frontend/utils/url.ts

[td] Filter logs by level and block type

---

mage_ai/frontend/pages/pipelines/[pipeline]/schedules/[...slug].tsx
mage_ai/frontend/pages/pipelines/[pipeline]/schedules/index.tsx

Change edit icon to a more meaningful edit icon. Also update the breadcrumbs for the edit page
tested locally 
cc:

[dy] Change edit icon

---

mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx

[td] Load more logs

---

mage_ai/frontend/components/Logs/Filter/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/server/api/logs.py

[td] Filter logs by block UUIDs

---

mage_ai/frontend/components/VariableOverwrites/index.style.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/schedules/index.tsx

Add variables overwrites to sidekick even if it's empty.
local
cc:

[dy] Add variable overwrites

---

mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
mage_ai/frontend/components/Logs/Filter/index.tsx
mage_ai/frontend/components/shared/Table/index.style.tsx
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/block-runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/pipeline-runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/schedules/index.tsx
mage_ai/server/api/logs.py

[td] Filter logs

---

mage_ai/server/api/events.py
mage_ai/services/aws/events/events.py

Update event rule targets: set lambda function as the target.
TODO
tested locally
cc:

[xy] Update event rule targets.

---

mage_ai/frontend/components/Logs/Detail/index.style.tsx
mage_ai/frontend/components/Logs/Detail/index.tsx
mage_ai/frontend/components/Logs/index.style.tsx
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/interfaces/LogType.ts
mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
mage_ai/frontend/oracle/elements/Button/GradientButton.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx
mage_ai/frontend/oracle/elements/Divider/index.tsx
mage_ai/frontend/oracle/styles/themes/dark.ts
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/frontend/utils/models/log.ts

[td] Add log detail

---

mage_ai/frontend/components/Orchestration/CreateSchedule/index.style.tsx
mage_ai/frontend/components/Orchestration/CreateSchedule/index.tsx
mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
mage_ai/frontend/package.json
mage_ai/frontend/styles/globals.css
mage_ai/frontend/yarn.lock

Add calendar to select start date.
cc:

[dy] Update start date selection

---

mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/components/PipelineLayout/index.tsx
mage_ai/frontend/components/shared/Header/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/block-runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/pipeline-runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/schedules/index.tsx

[td] Improve buttons for edit pipeline

---

mage_ai/frontend/components/Logs/Filter/index.tsx
mage_ai/frontend/components/Orchestration/CreateSchedule/index.tsx
mage_ai/frontend/components/Orchestration/OrchestrationDetail/index.tsx
mage_ai/frontend/components/Orchestration/Sidebar/index.tsx
mage_ai/frontend/components/PipelineDetailPage/constants.ts
mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/pages/pipeline-runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

[td] Change schedules to triggers

---

mage_ai/frontend/components/Dashboard/index.tsx
mage_ai/frontend/components/Logs/Filter/index.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/PipelineDetail/shared/index.style.tsx
mage_ai/frontend/components/PipelineDetailPage/index.tsx
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/shared/Table/index.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx
mage_ai/frontend/oracle/styles/units/spacing.ts
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx

[td] Add trigger detail page

---

.gitignore
scripts/deploy/terraform/alb.tf
scripts/deploy/terraform/iam.tf
scripts/deploy/terraform/lambda.tf
scripts/deploy/terraform/python/event_handler.py

Create lambda function in terraform script.
References
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function
* https://spacelift.io/blog/terraform-aws-lambda
tested locally
cc:

[xy] Create lambda function in terraform script.

---

mage_ai/frontend/components/Orchestration/OrchestrationDetail/index.tsx
mage_ai/frontend/components/Sidekick/utils.ts
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/VariableOverwrites/index.tsx

Remove the variable overwrites component from sidekick in the trigger detail page.
tested locally
cc:

[dy] Update runtime variable UI

---

mage_ai/frontend/components/Triggers/Edit/index.tsx

Treat startDate as UTC
tested locally
cc:

[dy] Fix start date issue

---

scripts/deploy/terraform/env_vars.json

Add AWS access key id and secret access key to env_vars.json
tested locally
cc:

[xy] Add AWS access key id and secret access key to env_vars.json

---

mage_ai/data_preparation/templates/repo/io_config.yaml

Update IO config template to use env var for AWS credentials.
tested locally
cc:

[xy] Update IO config template.

---

mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/shared/Table/index.style.tsx
mage_ai/frontend/components/shared/Table/index.tsx

[td] Update event pattern when adding

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/orchestration/db/models.py
mage_ai/orchestration/pipeline_scheduler.py

Fix block execution.
tested locally
cc:

[xy] Fix block execution.

---

mage_ai/frontend/components/Sidekick/utils.ts
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/server/server.py

[dy] Update server routes

---

mage_ai/frontend/components/Triggers/Detail/index.tsx

Add block run status to dependency graph in pipeline schedule detail page.
tested locally
cc:

[dy] Add block status

---

scripts/deploy/terraform/aws/alb.tf

Whitelist myip in security group.
tested by executing `terraform apply`
cc:

[xy] Whitelist myip in security group.

---

setup.py

[td] Version 0.4.0

---

scripts/deploy/terraform/aws/env_vars.json
scripts/deploy/terraform/aws/main.tf

Include lambda function arn and name env vars.
testing locally
cc:

[xy] Include lambda function arn and name env vars.

---

mage_ai/frontend/components/Triggers/Detail/index.tsx

I thought I committed this change on my last PR, but I didn't.
local
cc:

[dy] Update import

---

mage_ai/frontend/components/Triggers/Edit/index.tsx

Make calendar relative so that the user can scroll the page.
tested locally
cc:

[dy] Update calendar css

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/logging/logger.py
mage_ai/orchestration/pipeline_scheduler.py

When installing the library with `pip install`, the pipeline run is failed to executor in a separate process because local method can't be pickled. This PR fixes the issue.
tested locally
cc:

[xy] Fix multiprocessing pickle issue

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/interfaces/ChartBlockType.ts
mage_ai/frontend/interfaces/DataProviderType.ts
mage_ai/frontend/oracle/components/Tooltip/TooltipWrapper.tsx
mage_ai/io/bigquery.py
mage_ai/io/postgres.py
mage_ai/io/redshift.py
mage_ai/io/snowflake.py

[td] Configure write policy for existing tables

---

setup.py

[td] Version 0.4.1

---

docs/deploy/terraform/README.md
mage_ai/frontend/components/FileBrowser/index.tsx

[td] Update Terraform instructions

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/services/aws/emr/emr.py

[td] Don’t loop forever

---

mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/PipelineRun/shared/buildTableSidekick.tsx
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/interfaces/PipelineRunType.ts
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
mage_ai/frontend/pages/pipelines/index.tsx
mage_ai/server/api/orchestration.py

[td] Fix more bugs

---

README.md
setup.py

[td] 0.4.2

---

mage_ai/services/aws/emr/config.py
scripts/spark/create_cluster.py

Update spark driver memory based on instance size.
tested locally
cc:

[xy] Update spark driver memory based on instance size.

---

mage_ai/io/postgres.py

[td] Only insert Postgres if append and table exists

---

setup.py

[td] 0.4.3

---

docs/production/README.md
docs/production/compute_resource.md

Add doc for customizing compute resource
n/a
cc:

[xy] Add doc for customizing compute resource

---

README.md
docs/core/abstractions.md
docs/core/design_principles.md

[td] Add core abstractions doc

---

mage_ai/data_preparation/repo_manager.py
mage_ai/data_preparation/templates/repo/metadata.yaml
mage_ai/orchestration/notification/config.py
mage_ai/orchestration/notification/sender.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/services/slack/config.py
mage_ai/services/slack/slack.py

Integrate with slack for notification.
tested locally
cc:

[xy] Integrate with slack for notification.

---

mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/orchestration/db/models.py
requirements.txt

Add support for cron expressions for `schedule_interval` field. The UI right now just allows users to write their own cron syntax at the moment.

[dy] Support cron expressions

---

mage_ai/data_preparation/repo_manager.py

Fix None notification config.
tested locally
cc: @dy46

[xy] Fix None notification config.

---

mage_ai/orchestration/db/models.py

Fix execution date for schedule_interval @once.
tested locally
cc:

[xy] Fix execution date for once schedule_interval.

---

mage_ai/orchestration/notification/sender.py
mage_ai/services/slack/config.py

Ignore None slack webhook url.
tested locally
cc:

[xy] Ignore None slack webhook url.

---

mage_ai/orchestration/notification/config.py
mage_ai/orchestration/notification/sender.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/services/email/config.py
mage_ai/services/email/email.py

Support sending email notifications.
Example notification config
```
email_config:
smtp_host: email-smtp.us-west-2.amazonaws.com 
smtp_mail_from: alerts.engineering@mage.ai  
smtp_user: xxxxxxx
smtp_password: yyyyyyy
to_emails:
- test@mage.ai
```
TODOs
tested locally
cc:

[xy] Support sending email notifications.

---

mage_ai/data_preparation/executors/block_executor.py
mage_ai/data_preparation/executors/pipeline_executor.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py

Run tests by default. Stop executing the pipeline if any tests failed.
tested locally
cc:

[xy] Run tests by default.

---

mage_ai/orchestration/db/models.py
mage_ai/server/api/base.py
mage_ai/server/api/orchestration.py

Fetch pipeline run and pipeline schedule with pagination
Refactor the code for fetching pipeline run list and pipeline schedule list.
tested locally
Fetch pipeline schedules with pagination
Fetch pipeline runs with pagination
cc:

[xy] Fetch pipeline run and pipeline schedule with pagination

---

setup.py

Bump version to 0.4.4.
n/a
cc:

[xy] Bump version to 0.4.4.

---

mage_ai/data_cleaner/shared/utils.py
mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/variable_manager.py
mage_ai/server/server.py
mage_ai/server/utils/output_display.py

Support geo dataframe in block output.
Ticket: https://github.com/mage-ai/mage-ai/issues/995
tested locally
cc:

[xy] Support geo dataframe.

---

mage_ai/server/server.py

Add separate handler for pipeline-runs page so that it doesn't redirect to pipelines page.
tested locally
cc:

[xy] Add separate handler for pipeline-runs page.

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/variable.py
mage_ai/data_preparation/variable_manager.py

Allow saving extra block output variables in addition to required variables.
tested locally
cc:

[xy] Allow saving extra block output variables.

---

mage_ai/data_preparation/templates/transformers/transformer_actions/column/impute.py

Add missing import for impute transformer action.
tested locally
cc:

[xy] Add missing import for impute transformer action.

---

mage_ai/cluster_manager/aws/emr_cluster_manager.py
mage_ai/cluster_manager/cluster_manager.py
mage_ai/server/api/clusters.py
mage_ai/server/server.py
mage_ai/services/aws/emr/emr.py
mage_ai/services/aws/emr/launcher.py

Manage EMR clusters.
Add APIs to manage clusters
* Get a list of clusters
```
GET /api/v1/clusters/emr
{
"clusters": [
{
"id": "j-xxxxxxx",
"name": "2022-09-15T17:36:13.155431-mage-data-prepartion",
"status": "BOOTSTRAPPING",
"is_active": false
},
{
"id": "j-yyyyyyyy",
"name": "2022-09-15T16:35:24.218978-mage-data-prepartion",
"status": "WAITING",
"is_active": false
}
]
}
```
* Create a new cluster
```
POST /api/v1/clusters/emr
{
"cluster": {
"action": "create_new_cluster"
}
}
```
* Set a cluster id to be active
```
POST /api/v1/clusters/emr
{
"cluster": {
"action": "set_active_cluster2",
"cluster_id": "j-xxxxxxxxxx"
}
}
```
tested locally
cc:

[xy] Manage EMR clusters.

---

mage_ai/frontend/components/CodeBlock/index.tsx
mage_ai/frontend/components/CodeBlock/utils.ts
mage_ai/frontend/components/DependencyGraph/index.style.tsx
mage_ai/frontend/components/DependencyGraph/index.tsx
mage_ai/frontend/components/PipelineDetail/index.tsx
mage_ai/frontend/interfaces/BlockType.ts

[td] Data loaders can have parents

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/pipeline.py
mage_ai/data_preparation/templates/sensors/default.py
mage_ai/data_preparation/templates/sensors/s3.py
mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
mage_ai/server/websocket.py

Getting sensors to work in the UI. Going to refactor some of the sensor code in a future PR.
tested locally
cc:

[dy] Update sensor backend

---

README.md
docs/blocks/README.md
docs/core/abstractions.md
mage_ai/data_preparation/templates/sensors/default.py

[td] Updated more docs

---

mage_ai/orchestration/run_status_checker.py

[dy] Fix NoneType refresh

---

mage_ai/orchestration/run_status_checker.py

Fix error with iterator. Also, fail the sensor on certain conditions.
tested locally

[dy] Update run_status_checker

---

mage_ai/data_preparation/executors/executor_factory.py
mage_ai/server/utils/output_display.py
mage_ai/shared/code.py

Support running sensor in pyspark kernel.
tested locally
cc:

[xy] Run sensor in pyspark kernel.

---

mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/utils/shared.py

Support interpolate variables in sql.
tested locally
cc:

[xy] Support interpolate variables in sql.

---

mage_ai/data_preparation/models/block/sql/__init__.py

Preview results for data exporters.
tested locally

[xy] Preview results for data exporters.

---

mage_ai/orchestration/pipeline_scheduler.py
mage_ai/services/aws/emr/launcher.py

[xy] Fix EMR cluster name.

---

mage_ai/orchestration/pipeline_scheduler.py
mage_ai/orchestration/run_status_checker.py

Refresh block as well
tested locally
cc:

[dy] Refresh block too

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/data_preparation/templates/data_exporters/default.jinja
mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
mage_ai/frontend/utils/models/output.ts
mage_ai/io/postgres.py
mage_ai/tests/data_preparation/test_templates.py

[td] Update data exporter template

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py

[td] Add global vars to table name

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/models/block/sql/__init__.py
mage_ai/data_preparation/models/block/sql/bigquery.py
mage_ai/data_preparation/models/block/sql/postgres.py
mage_ai/data_preparation/models/block/sql/redshift.py
mage_ai/data_preparation/models/block/sql/snowflake.py

Get variable with partition in sql block. Partitions are generated for production pipeline runs.
tested locally
cc:

[xy] Get variable with partition in sql block.

---

mage_ai/server/server.py

Catch pipeline load exception. Still load other pipelines when failing to load one pipeline.
tested locally
cc:

[xy] Catch pipeline load exception.

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/components/Triggers/Detail/index.tsx
mage_ai/frontend/components/Triggers/Edit/index.tsx
mage_ai/frontend/components/Triggers/utils.ts
mage_ai/frontend/components/shared/Table/index.style.tsx
mage_ai/frontend/interfaces/PipelineRunType.ts
mage_ai/frontend/oracle/components/FlyoutMenu/index.style.tsx
mage_ai/frontend/oracle/elements/Button/index.tsx
mage_ai/frontend/oracle/icons/index.tsx
mage_ai/frontend/oracle/styles/colors/main.ts
mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/server/api/orchestration.py

Allows users to retry runs that are not successful.
cc:

[dy] Retry unsuccessful runs

---

mage_ai/data_preparation/models/block/__init__.py
mage_ai/data_preparation/templates/data_exporters/pyspark/default.jinja
mage_ai/data_preparation/templates/data_exporters/pyspark/s3.py
mage_ai/data_preparation/templates/data_loaders/pyspark/default.jinja
mage_ai/data_preparation/templates/data_loaders/pyspark/s3.py
mage_ai/data_preparation/templates/repo/metadata.yaml
mage_ai/data_preparation/templates/template.py
mage_ai/data_preparation/templates/transformers/default_pyspark.jinja
mage_ai/data_preparation/templates/utils.py
mage_ai/server/websocket.py
mage_ai/services/aws/emr/resource_manager.py

* Show good error message when creating emr cluster without s3_bucket
* Update config template for EMR cluster.
* Allow overwriting execution_date in dev environment
* Update code template for spark kernel
TODOs
tested locally with pyspark kernel
cc:

[xy] Some improvements on spark kernel

---

mage_ai/orchestration/execution_process_manager.py
mage_ai/orchestration/pipeline_scheduler.py
mage_ai/server/api/orchestration.py

* Add endpoint to cancel pipeline run.
* Stop block run processes once pipeline run is cancelled
```
PUT /api/pipeline_runs/[pipeline_run_id]
{
"pipeline_run": {
"status": "cancelled"
}
}
```
TODOs
tested locally
cc:

[xy] Add endpoint to cancel pipeline run.

---

mage_ai/server/api/orchestration.py

Add default execution date to pipeline run creation.
tested locally
cc:

[xy] Add default execution date to pipeline run creation.

---

mage_ai/data_preparation/models/pipeline.py

Fix malformed pipeline metadata.
tested locally
cc:

[xy] Fix malformed pipeline metadata.

---

mage_ai/frontend/components/PipelineDetail/Runs/Table.style.tsx
mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
mage_ai/frontend/oracle/components/FlyoutMenu/index.style.tsx

[dy] Cancel running pipeline

---

mage_ai/frontend/pages/index.tsx

Don't always route to the `/pipelines` route.
tested locally
cc:

[dy] Fix routing issue
