- setup.py
Add package_dir to setup.py. This fixes the error of `error: package directory 'xxx' does not exist`.
ref: https://packaging.python.org/en/latest/tutorials/packaging-projects/
tested locally
cc:
> [xy] Add package_dir to setup.py

- mage_ai/data_cleaner/analysis/calculator.py
- mage_ai/data_cleaner/analysis/charts.py
Reduce duplicate clean methods for timeseries charts.
tested locally. It reduces insights calculator time from 14s to 11s.
cc:
> [xy] Reduce duplicate clean for timeseries charts.

- mage_ai/frontend/components/charts/Histogram.tsx
- mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
- mage_ai/frontend/components/datasets/Insights/Overview.tsx
Add set width to histogram in column view so it doesn't keep expanding. I'm not sure what exactly is causing it in the first place.
cc:
> [dy] Add set width

- mage_ai/__init__.py
- mage_ai/server/app.py
Support killing a flask app.
```
import mage_ai
mage_ai.launch()
mage_ai.kill()
```
Reference: https://www.geeksforgeeks.org/python-different-ways-to-kill-a-thread/
tested locally
cc:
> [xy] Support killing a flask app.

- mage_ai/frontend/pages/datasets/[slug]/features/[column].tsx
Column view button goes to the dataset details view instead of the dataset list.
https://user-images.githubusercontent.com/90282975/171523219-401a15ce-21de-490a-b369-4066f08c86e6.mov
cc:
@tommydangerous @johnson-mage @dy46
> [nt] Change route to dataset instead of list and clean up code styling.

- mage_ai/data_cleaner/cleaning_rules/impute_values.py
- mage_ai/data_cleaner/pipelines/base.py
- mage_ai/data_cleaner/shared/utils.py
- mage_ai/data_cleaner/statistics/calculator.py
- mage_ai/data_cleaner/transformer_actions/column.py
- mage_ai/data_cleaner/transformer_actions/constants.py
- mage_ai/tests/data_cleaner/cleaning_rules/test_impute_values.py
- mage_ai/tests/data_cleaner/statistics/test_calculator.py
- mage_ai/tests/data_cleaner/transformer_actions/test_column.py
Default imputation strategy is to now fill missing entries with some non-null marker that represents the missing value. By type, these markers are:
- Category/String: `'missing'`
- Datetime: `pd.Timestamp.min` (1677-09-21 00:12:43.145224193)
- Number: `0`
Along with these changes relevant bug fixes were made to other parts of the program.
Changes were tested locally against unit tests alongside more rigorous testing on sample testing datasets.
cc:
> [sk] Added default impute value

- mage_ai/data_cleaner/analysis/calculator.py
Calculate correlation for number types. For some number columns with 2 values, the columns are detected as type true_or_false. Thus, the correlation was not calculated. This PR fixes this issue.
tested locally
cc:
> [xy] Calculate correlation for number types.

- mage_ai/frontend/components/datasets/overview/index.tsx
- mage_ai/frontend/oracle/components/Table/BaseTable.tsx
- mage_ai/frontend/oracle/components/Table/Table.style.tsx
- mage_ai/frontend/oracle/components/Table/helpers.tsx
- Adds left Align to the column header
- Adds striped look to match Figma
- Fix bug with certain column headers not stretching enough
- Fix bottom border not showing up bug
- Refactor/create a new component that calls the api given the dataset version. (Currently is done on page level)
- Change px to rem and em, find another way to style that works with the react-table without passing in a style prop.
- Display the datatype on top of the column
- Add a sticky column header.
cc:
@johnson-mage @dy46 @tommydangerous
> [nt]  oracle basetable polish

- mage_ai/server/app.py
- mage_ai/server/data/base.py
- mage_ai/server/data/models.py
Fixed a couple of bugs in Flask endpoints:
- When a non-integer id is used for a pipeline, originally it would try to be converted to an integer and throw a hard to find error. Now the error is raised directly, letting the user know that someone an invalid id had been created.
Usually the error is raised when the user manually adds in their own feature set or pipeline incorrectly to the files folder.
- When a dataset with some id xx does not exist, accessing the Flask GET endpoint (feature_sets/xx or pipelines/xx) with creates an empty pipeline and feature set in files (a ghost storage model). Now when this is attempted an internal server error gets raised. The PUT endpoint is not modified.
This is the error now generated when accessing http://localhost:3000/datasets/329423 when the …
> [sk] Fixed Flask resource loading bugs

- mage_ai/data_cleaner/transformer_actions/base.py
- mage_ai/data_cleaner/transformer_actions/dependency_resolution.py
- mage_ai/tests/data_cleaner/transformer_actions/test_row.py
Added logic to enforce that some conditions are met before cleaning actions are taken. Currently, the main dependency is that any filter action requires column types to be cleaned beforehand (no whitespace otherwise row filtering breaks). If dependencies are not met then an error is raised.
There are some reformatting edits as well.
Prior unit tests were re-evaluated alongside newly added unit tests to confirm that an error is raised when dependencies are not satisfied but otherwise functionality remains the same.
cc:
> [sk] Adding cleaning action dependencies

- mage_ai/server/app.py
Previously, the cleaning pipeline sent by the client frontend would get directly written to file, even if the contained cleaning actions failed to execute due to some error. This PR updates the backend so the new pipeline is written to file only if the action is successfully applied without any error. If the action throws an error then the cleaning step has not been fully executed, and so the action should not be written to file as if it has been completed.
If no feature set ID is given (that is, the pipeline exists separately from a feature set to apply the action to), then always write the pipeline to file. This is for the case when users are building their own custom pipeline to apply on any data.
Local tests were performed by manually throwing errors in the cleaning step and asserting …
> [sk] Write pipeline to file only after action is successfully applied

- mage_ai/frontend/components/datasets/overview/index.tsx
- mage_ai/frontend/components/datasets/overview/utils.ts
- mage_ai/frontend/oracle/components/Table/Cell.tsx
- mage_ai/frontend/oracle/components/Table/SimpleDataTable.tsx
- If a table is given a list inside it, it'll look for a pair. The first being a boolean to determine whether to include a progress bar, followed by the value.
- Updates cell file to display progress bars using the "showProgress" prop.
- Change default flex values to get the table to closer match figma, though the cell's padding makes it difficult for the chart to be exactly like Figma where the progress bar and percentage are both closer to each other.
Ran on localhost 
* The progress bar is off center... I think this is due to how it renders inside a cell. 
* I also added the danger property for the red version of the progress bar when it's below average (C = 75%). We can extend this with a constant in the future when we do good/bad/average.
cc:
@johnson-mage @dy46 @tommydangerous
> [nt] Add progress bar to cell and simple datatable

- mage_ai/data_cleaner/pipelines/base.py
- mage_ai/server/app.py
Backend now rescues all internal server errors thrown and sends a response with the error message and stack trace back to the client. All endpoint functions are wrapped with the `rescue_errors` decorator which catch all exceptions thrown and reroute them to the client through a JSON response. This response object contains
- `error_code`: The error code (default is currently 500)
- `error_msg`: The message reported by the error object
- `error_stack_trace`: The formatted error message with stack trace (as usually printed by Python)
- `full_stack_trace`: A list of the entire stack trace up to the point of the error being thrown
**Note**: As decorators wrap all inner functions with the same outer function, Flask natively will detect duplicate endpoints and fail to run (Flask by default uses …
> [sk] Backend reports internal server errors to the client

- mage_ai/data_cleaner/cleaning_rules/reformat_values.py
- mage_ai/tests/data_cleaner/cleaning_rules/test_reformat_values.py
Only apply ReformatDateSubRule to datetime type. I tested this rule on a dateset with 26k rows and multiple text column. It originally took 100 seconds. This change reduced the time to 8 seconds.
tested locally
cc:
> [xy] Speed up reformat values

- mage_ai/frontend/components/datasets/columns/ColumnDetail.tsx
- mage_ai/frontend/components/datasets/columns/ColumnList.tsx
- mage_ai/frontend/components/datasets/overview/index.tsx
- mage_ai/frontend/oracle/components/Layout/index.tsx
- mage_ai/frontend/oracle/elements/Head/index.tsx
- mage_ai/frontend/pages/datasets/index.tsx
- Adds a new element called Head to contain the page title, can be later extended for a page description for search/SEO.
- Integrates the head component with the layout (i.e you can now set titles within the layout component)
- Adds basic names based on file names to the pages. (see video)
https://user-images.githubusercontent.com/90282975/171983112-454f0e44-de0b-4b00-871d-6b6a145b0465.mov
cc:
@johnson-mage @dy46
> [nt] Add all page titles for existing pages

- mage_ai/frontend/oracle/components/Table/BaseTable.tsx
- mage_ai/frontend/oracle/components/Table/SimpleDataTable.tsx
- mage_ai/frontend/oracle/components/Table/Table.style.tsx
- mage_ai/frontend/oracle/components/Table/helpers.tsx
- Add rounded corners
- Removed fancy layout hooks
- Improved styling on the inside of the table
- Shrunk the size of table down for more apparent vertical scrolling
Localhost 
**Doesn't look that good since the borders don't align**
- Change px to rem and em, 
- Find another way to style that works with the react-table without passing in a style prop.
- Display the datatype on top of the column
- Add a sticky column header.
- There is a bug where if the table is at max scroll it will scroll the page by the direction. Can be annoying at times.
cc:
@johnson-mage @dy46 @tommydangerous
> [nt]  Basetable polish p2

- mage_ai/frontend/components/datasets/overview/utils.ts
- mage_ai/frontend/oracle/components/Table/BaseTable.tsx
Localhost, pull up the statistics table.
cc:
@johnson-mage
> [nt] Add divide by zero edge cases

- mage_ai/frontend/oracle/components/Table/BaseTable.tsx
- mage_ai/frontend/oracle/components/Table/Table.style.tsx
- Fix alignment issue using wordbreaks
- Style datatable with the colors and borders to match Figma design.
- Resize datatable to better fit screen height to enable vertical scrolling.
Went on localhost and opened the long files.
cc: @johnson-mage 
All that's left to do for the Datatable is the sticky header now.
> [nt]  datatable polish v3

- mage_ai/data_cleaner/statistics/calculator.py
- mage_ai/tests/data_cleaner/statistics/test_calculator.py
Updates to speed up statistics calculation. 
Performance was evaluated on dataset with 100000 rows and 28 columns (total of 2.8 million entries) with numbers, categories, boolean, and text columns. All times are averaged over 100 trials. 
**Baseline**: 1.463 seconds
- No multithreading - 1.408 seconds (likely because statistics calculation is CPU bound rather than IO bound)
- Deduplicated null value calculation between null_value_rate and null_value_count - 1.362 seconds      
- Switched to inbuilt mean calculation - 1.344 seconds
- Switched from quantile to inbuilt median calculation - 1.323 seconds
- Refactored timeseries check to avoid manually calculating the null value rate - 1.285 seconds
- Optimizing longest null sequence:
- Switched from pandas series to Numpy ndarray - 1.211 …
> [sk] Statistics performance updates

- mage_ai/data_cleaner/column_type_detector.py
- mage_ai/data_cleaner/shared/utils.py
- mage_ai/tests/data_cleaner/test_column_type_detector.py
Fixed two bugs with column type detection:
- Object types sometimes contained mixed types and so string functions failed to work on these objects. Fixed by casting object columns to string
- `infer_column_types` sometimes (incorrectly) identified a column as a phone number due being formatted as a phone number, despite column names suggesting otherwise. To resolve this problem, phone number and zip code detection now must match column names against a set of reserved keywords most often associated with phone number and zip code columns in order for the inference to report those columns as phone numbers or zip codes.
Previous unit tests were reran to confirm correctness. New tests were written to test the new phone number and zip code detection system.
cc:
> [sk] Fixed bugs with column type detector

- mage_ai/data_cleaner/statistics/calculator.py
Fixed bug where the statistics calculator was accidentally writing Pandas series and Timestamp to the statistics metadata, throwing an error when the metadata was attempted to be serialized. This was a previous bug that re-arose due to updating the value counts after dates have been parsed (and the string conversion was improperly handled).
Tested locally on user data.
cc:
> [sk] Fixed json serialization bug

- mage_ai/frontend/components/datasets/FeatureProfiles.tsx
- reworked feature profiles table to follow the chosen Figma design
Long column names are truncated as shown below:
cc: @wangxiaoyou1993 @johnson-mage
> [sp] improve feature profiles layout

- mage_ai/frontend/oracle/components/Table/BaseTable.tsx
- mage_ai/frontend/oracle/components/Table/Cell.tsx
- Add table tooltips to BaseTable for the Dataset details page
- Show full value as tooltip instead of truncated text
- Fix bug with progress bar alignment.
Localhost
cc:
@johnson-mage
> [nt]  table tooltips polish

- mage_ai/data_cleaner/column_type_detector.py
- mage_ai/tests/data_cleaner/test_column_type_detector.py
Fixed bug where certain datetime formats were not being detected, such as "DD/MM/YYYY HH:MM:SS". Fixed by updating the regex string to handle this case.
Unit tests were run to confirm correctness of code, alongside testing on the dataset associated with this bug to confirm the date is now parsed.
cc:
> [sk] Fixed datetime detection bug

- mage_ai/data_cleaner/analysis/charts.py
- mage_ai/data_cleaner/data_cleaner.py
Fix wrong histogram bucket. Distribution chart showed values higher than maximum value.
tested locally
cc:
> [xy] Fix wrong histogram bucket.

- mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
- mage_ai/frontend/oracle/components/Table/Cell.tsx
- mage_ai/frontend/oracle/components/Table/SimpleDataTable.tsx
- mage_ai/frontend/oracle/components/Table/index.style.tsx
- On the column detail visualization view, add table for "Columns with high correlation" next to the correlations heatmap, for all correlation values of abs(0.5) or more.
> [nt] Add correlation table for high correlations

- mage_ai/frontend/components/charts/LineSeries.tsx
- mage_ai/frontend/components/charts/ScatterPlot.tsx
- mage_ai/frontend/components/datasets/Insights/Overview.tsx
- mage_ai/frontend/interfaces/FeatureType.ts
* Add some padding on each side
* Add `duplicate` text to label
* Make circles a bit bigger
For some reason the `voronoi` function keeps erroring out when we select the same feature for X and Y, so I just added a try catch. I'll continue to look into that issue after other P0 issues.
local test
> [dy] Update scatter plot

- mage_ai/frontend/oracle/components/Table/SimpleDataTable.tsx
- mage_ai/frontend/utils/string.ts
- fixed case where `removePercent()` logic was being performed on strings not containing percentages
Using the following dataset and clicking on the "Visualizations" tab used to crash the frontend. This is now fixed.
[dirty_dataset.csv](https://github.com/mage-ai/mage-ai/files/8857768/dirty_dataset.csv)
> [sp] metrics warnings hotfix

- mage_ai/frontend/components/ActionForm/index.tsx
- mage_ai/frontend/components/suggestions/SuggestionRow.tsx
- mage_ai/frontend/components/suggestions/index.tsx
- add `useEffect()` hook to `SuggestionRow` to update custom action payload state in sync with backend changes
1. Apply a "Remove outliers" suggestion.
2. Edit the next available "remove outliers" suggestion.
3. The action code editor still displays the action code for the "remove outliers" suggestion that was just applied.
This PR fixes this behavior, and should fix future issues as we expand custom actions.
> [sp] fix out-of-sync action code editor

- mage_ai/frontend/components/suggestions/SuggestionRow.tsx
- mage_ai/frontend/oracle/elements/Link/index.tsx
- extremely long column name links now wrap instead of overflowing `SuggestionRow`
There's still an issue with "Remove outliers" because it needs to display the super long column name variable, which I'm not sure if we can do much about. It should be a very rare edge case.
> [sp] fix suggestions overflow

- mage_ai/frontend/components/ActionForm/actions.ts
- mage_ai/frontend/components/ActionForm/constants.ts
- mage_ai/frontend/components/ActionForm/index.tsx
- Removed placeholder
- Update `CODE_EXAMPLE` to be more instructional
Localhost and ran some queries.
_You can tell it's a value because it's colored_
cc: @johnson-mage 
Is this what you were thinking of @tommydangerous? Or did you want to display it somewhere else?
> [nt] Change example placeholder to editable text

- mage_ai/frontend/components/ActionForm/index.tsx
- mage_ai/frontend/components/suggestions/SuggestionRow.tsx
- remove side padding when action form is embedded in a suggestion row
- fix first column name not being linked in a suggestion row
- fix extraneous "0" next to column name when there are no action arguments
> [sp] action form fixes

- mage_ai/data_cleaner/analysis/calculator.py
- mage_ai/data_cleaner/statistics/calculator.py
- mage_ai/data_cleaner/transformer_actions/column.py
- mage_ai/data_cleaner/transformer_actions/utils.py
- mage_ai/tests/data_cleaner/transformer_actions/test_column.py
Updated reformat action to accept all datatypes, but only perform the reformatting if the datatype is correct. 
Note: unit tests were added alongside reformatting them, causing a very messy git blame.
Changes were tested locally on sample datasets by trying to apply custom actions to incorrect datatypes. Unit tests were also written to confirm that there is no failure on inputs with the wrong datatype.
cc:
> [sk] Reformat values doesn't fail on bad input datatypes

- mage_ai/frontend/components/datasets/columns/ColumnReports.tsx
- see title
max/min/average/etc values no longer showing
cc: @nathaniel-mage
> [jk] Filter out null column stats

- mage_ai/data_cleaner/statistics/calculator.py
- mage_ai/tests/data_cleaner/transformer_actions/test_column.py
- requirements.txt
Bump up pandas version to improve perf. pandas [1.4.0](https://github.com/pandas-dev/pandas/releases/tag/v1.4.0), [1.3.0](https://github.com/pandas-dev/pandas/releases/tag/v1.3.0) and [1.2.0](https://github.com/pandas-dev/pandas/releases/tag/v1.2.0) all have perf improvements.
The old pandas version was slow on computing nunique (it took 5 seconds to calculate nunique for 100k unique rows). It's instant using the new pandas version.
Performance comparison (a dataset with 100k rows and 32 columns.
Old pandas version
* infer_column_types took 10s.
* calculate_statistics took 15s
New pandas version
* infer_column_types took 5s.
* calculate_statistics took 1.1s
tested locally
cc:
> [xy] Bump up pandas version to improve perf.

- requirements.txt
Use pandas version ~1.3.0. Pandas ~1.4.0 is only supported for python version 3.8 and higher. https://pandas.pydata.org/docs/whatsnew/v1.4.0.html#increased-minimum-version-for-python
tested locally. unit tests.
cc:
> [xy] Use pandas version ~1.3.0

- mage_ai/data_cleaner/transformer_actions/action_code.py
Set python engine in pandas query.
Filtering with null value throws error in Google colab.
Reference: https://stackoverflow.com/questions/59647839/typeerror-unhashable-type-numpy-ndarray-how-to-fix-this-error-when-doing-a
tested on google colab
Before fix
After fix
cc:
> [xy] Set python engine in pandas query.

- mage_ai/frontend/components/datasets/overview/utils.tsx
Before: the values were sorted in reverse order so the highest frequency value was not showing.
After: show the highest frequency values first.
cc:
@shrey-mage @nathaniel-mage
> [td] Sort bar chart horizontal so largest count at the top

- mage_ai/data_cleaner/column_type_detector.py
- mage_ai/data_cleaner/shared/constants.py
- mage_ai/data_cleaner/statistics/calculator.py
- mage_ai/data_cleaner/transformer_actions/column.py
- mage_ai/server/data/models.py
- mage_ai/tests/data_cleaner/statistics/test_calculator.py
- mage_ai/tests/data_cleaner/test_column_type_detector.py
Backend now calculates indices of invalid values for phone numbers, zip codes, and emails. This can be used by the frontend to highlight these entries as invalid.
Unit tests were developed locally to test that the invalid indices are calculated correctly, alongside testing on user datasets to confirm that the validity metric still reports outputs correctly.
cc:
> [sk] Calculate the indices of invalid values

- mage_ai/data_cleaner/column_type_detector.py
- mage_ai/data_cleaner/statistics/calculator.py
- mage_ai/data_cleaner/transformer_actions/base.py
- mage_ai/data_cleaner/transformer_actions/column.py
- mage_ai/data_cleaner/transformer_actions/constants.py
- mage_ai/tests/data_cleaner/statistics/test_calculator.py
- mage_ai/tests/data_cleaner/transformer_actions/test_column.py
Added transformer action to clean syntax errors by replacing invalid values with an 'invalid' marker. Some notable changes:
- `find_syntax_errors` now supports cleaning integers and datetimes (however as of now they still can't be used with the cleaning suggestion since the dataset gets automatically cleaned).
- `find_syntax_errors` filters out null values (null values are null, not invalid)
- Added `invalid_value_distribution` entry in statistics which can be used to generate a visualization on the distribution of the invalid values in a column
Unit tests were written to test that invalid values are recognized and replaced properly, and also the backend was tested with API calls to the pipeline to remove syntax errors.
cc:
@wangxiaoyou1993 @nathaniel-mage
> [sk] Adding syntax error cleaning action

- mage_ai/server/app.py
Fix bug: ![unnamed](https://user-images.githubusercontent.com/80284865/173280269-5c3b25e5-76ae-43d5-975d-6ac82c32af57.png)
Thread's method isAlive() was renamed to is_alive() in python version 3.9.
This PR catches AttributeError and fall back to call is_alive() method.
tested locally
cc:
> [xy] Fallback to thread.is_alive().

- mage_ai/data_cleaner/analysis/calculator.py
- mage_ai/data_cleaner/analysis/charts.py
Speed up analysis calculator. Tested on a dataset with 100k rows and 32 columns (with datetime column). Original time was 2.1s. This PR reduced the analysis calculation time by 66% to 0.7s.
* Speed up timestamp calculation: 2.1s -> 1.5s
*  https://stackoverflow.com/questions/54313463/pandas-datetime-to-unix-timestamp-seconds
* Optimize stats calculation in timeseries chart: 1.5s -> 1.15s 
* Update histogram calculation to use np.histogram method: 1.15s -> 0.78s
* Only dropna when necessary for histogram calculation: 0.78s -> 0.7s
tested locally
cc:
> [xy] Speed up analysis calculator

- mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
- mage_ai/frontend/components/datasets/Insights/Overview.tsx
- mage_ai/frontend/components/datasets/columns/ColumnReports.tsx
- mage_ai/frontend/components/datasets/overview/index.tsx
- mage_ai/frontend/oracle/components/FlexContainer.tsx
- mage_ai/frontend/oracle/components/Layout/MultiColumn.style.tsx
- Use single blocks instead of two columns for tables/charts on smaller screens.
> [jk] Responsive tab content

- mage_ai/frontend/components/datasets/overview/index.tsx
- mage_ai/frontend/components/datasets/overview/utils.tsx
- Displays Timeseries chart for Datetime types as a Histogram
- Excludes zeroes to free up space
- Display ranges when hovering over the chart.
Visit Localhost and hover over a chart
> [nt]  datatable datetime chart

- mage_ai/frontend/components/datasets/overview/utils.tsx
- Fix bug where chart wasn't rendering at full width. The margin was being offset which made it look weird. I changed it to match what other histogram charts did.
Localhost, pull up a chart for datetime columns
> [nt] Reset margins to match other histogram charts.

- mage_ai/__init__.py
Fix iframe on google colab. When we directly specifying the src of iframe, the iframe was not shown in colab.
tested on google colab
cc:
> [xy] Fix iframe on google colab.

- mage_ai/frontend/components/DataTable/index.tsx
- mage_ai/frontend/oracle/elements/Link/index.tsx
- The reports page has a table containing invalid values, accessed by the reports tab or clicking an invalid cell.
- In a future branch, we'll rework the reports page to be 'value': 'count' to increase readability/reduce duplicates.
Tested on the Localhost app. I broke this off into two versions due to some UX decisions to get input.
View all is side by side with the cell, but the onClick is triggered when clicking on the cell
View all is not side by side but the onClick is triggered when clicking on the text
Let me know which version is preferred and I can edit it accordingly.
cc: @dy46 @johnson-mage
> [nt] table invalid redirect

- mage_ai/frontend/components/datasets/StatsTable/index.tsx
- mage_ai/frontend/components/datasets/columns/ColumnReports.tsx
- fix unique values warning from `n > 0` to `n > 80%`
- refactor `Warning` in `StatsTable` to `WarningType` for clarity
cc: @johnson-mage @dy46 @wangxiaoyou1993
> [sp] fix warning for column stats

- mage_ai/frontend/oracle/components/Layout/MultiColumn.tsx
- mage_ai/frontend/oracle/components/Menu/index.tsx
- After cleaning column names, it appeared like the dropdown wasn't updating the names, but they were just getting capitalized.
cc:
> [jk] Don't capitalize links in Menu

- mage_ai/__init__.py
- mage_ai/frontend/components/datasets/Export/index.tsx
- mage_ai/server/app.py
- mage_ai/server/client/mage.py
- mage_ai/server/data/models.py
- requirements.txt
Launch the data cleaning tool with a group API key to sync pipelines with the Mage database. Calling `mage_ai.launch` with an api_key will kick off the `sync_pipelines()` method which will sync the pipelines between the user's local storage and Mage's database. Right now, we will automatically upload all of the local pipelines to Mage associated to the api key's group.
Usage:
```
import mage_ai
df = pd.read_csv('./testfiles/life_expectancy.csv')
mage_ai.launch(api_key="ErLVkWVZMJVSVDHDpembT7sPpom6cl0Vl8jR1dlg")
mage_ai.clean(df, remote_pipeline_uuid=1)
```
tested locally
> [dy] Launch with API key

- mage_ai/frontend/components/charts/ScatterPlot.tsx
- mage_ai/frontend/components/charts/utils/label.ts
Set left margin of the scatter plot based on the length of the y values. This way we can avoid having the labels being cut off.
local
cc: @johnson-mage @nathaniel-mage @shrey-mage
> [dy] Fix scatter plot labels

- mage_ai/__init__.py
- mage_ai/server/app.py
Support databricks notebook type.
Web server url: `https://{databricks_host}/driver-proxy-api/o/{workspace_id}/{cluster_id}/{port}/?token={token}`
to be tested in databricks notebook after merged.
tested printing out the url
cc:
> [xy] Support databricks notebook type.

- mage_ai/data_cleaner/transformer_actions/custom_action.py
- mage_ai/frontend/components/ActionForm/index.tsx
- mage_ai/frontend/components/suggestions/SuggestionRow.tsx
- fix backend error when user applies code example
- replace tabs with spaces
- add optional chaining to displayed action arguments
- Click "New Action" > make no changes, click "Apply". Backend no longer returns an error, and code is applied.
- Write a line with four manual spaces. Write a line with a tab. Backend no longer returns an error, and code is applied.
cc: @johnson-mage @dy46 @tommydangerous @wangxiaoyou1993
> [sp] action code editor fixes

- mage_ai/frontend/oracle/components/RowDataTable/index.tsx
- fixed RowDataTable to clone each child element correctly
- Dataset Dashboard now correctly displays "No datasets available again"
- No unexpected errors when no datasets are added to the tool
> [sp] fix RowDataTable element cloning

- docs/contributing/testing.md
- mage_ai/frontend/api/utils/url.ts
We need to use the current URL protocol and port when making API calls from the front-end to the backend server.
Testing this branch on http://18.237.55.91:5789/datasets
```bash
$ pip3 install git+https://github.com/mage-ai/mage-ai.git@td--host_protocol_fix#egg=mage-ai
```
cc:
> [td] Fix host and protocol for cloud

- mage_ai/frontend/components/charts/HeatMap.tsx
- mage_ai/frontend/components/datasets/Insights/ColumnAnalysis.tsx
- mage_ai/frontend/components/datasets/Insights/Overview.tsx
- mage_ai/frontend/components/datasets/overview/index.tsx
- mage_ai/frontend/oracle/elements/Link/index.tsx
Add links to correlation heat map so that users can easily navigate to the column page.
local
cc: @johnson-mage @shrey-mage
> [dy] Add links to correlation labels

- mage_ai/__init__.py
Add iframe_host and iframe_port back.
The host that the server is running on could be different the host we use in iframe. When running the app on a ec2 host, we use 0.0.0.0 as the host and use the EC2 instance IP as the iframe host.
tested locally
cc:
> [xy] Add iframe_host and iframe_port back.

- mage_ai/data_cleaner/column_types/column_type_detector.py
- mage_ai/tests/data_cleaner/test_column_type_detector.py
Previously, the mean of an integer valued column would be a decimal, shifting the column type from `NUMBER` to `NUMBER_WITH_DECIMALS`. This was actually caused by the column type inference incorrectly mapping integer-valued columns with `np.nan` values to floats despite the rest of the column being an integer. 
Column type inference is now fixed to detect these columns as integers. Additionally, float-valued column with all values of the from `x.0000` are labeled as `NUMBER` type since all values in the decimal places are zero.
As a result, the `impute` transformer action now correctly maps these columns back to integers, truncating the mean in the process.
Previous (without update to column type inference)
Current (with update to column type inference)
A new unit test was written to …
> [sk] Mean Imputation with Integer Values is truncated

- mage_ai/frontend/components/ActionForm/index.tsx
Frontend no longer sends default transformer function as action code payload.
This fixes a code editor being displayed on every custom action.
However, this will cause an error when the user does not type any new code into the code editor, and should ideally be handled on the backend.
Apply any custom action that doesn't require code. Code editor should no longer be displayed.
cc: @johnson-mage @wangxiaoyou1993
> [sp] empty action code hotfix

- mage_ai/data_cleaner/transformer_actions/column.py
- mage_ai/data_cleaner/transformer_actions/spark/transformers.py
- mage_ai/data_cleaner/transformer_actions/utils.py
* Support clean_column_name transformer in spark.
* Remove used __row_number_lit__, __row_number__, __group_mod__ columns
* Use udf for filter transformer
tested on databricks notebook
cc:
> [xy] Support more spark transformers and make some fixes

- mage_ai/frontend/components/DataTable/index.tsx
- mage_ai/frontend/components/datasets/FeatureProfiles.tsx
- mage_ai/frontend/components/datasets/overview/utils.tsx
- mage_ai/frontend/components/suggestions/SuggestionRow.tsx
- mage_ai/frontend/oracle/elements/Link/index.tsx
- standardize underline colors (eg. purple column links now have purple underlines as expected)
- remove unnecessary nested `Text` components inside of links
- adjust disabled column link color to dark gray
> [sp] fix link styling throughout app

- mage_ai/frontend/components/datasets/FeatureProfiles.tsx
- percentages in feature profiles should never be higher than 100% now (pulled from backend)
> [sp] fix percentages in feature profiles

- mage_ai/__init__.py
- mage_ai/data_cleaner/analysis/calculator.py
- mage_ai/data_cleaner/data_cleaner.py
- mage_ai/data_cleaner/pipelines/base.py
- mage_ai/data_cleaner/shared/conversions.py
- mage_ai/data_cleaner/shared/logger.py
- mage_ai/data_cleaner/statistics/calculator.py
- mage_ai/data_cleaner/transformer_actions/column.py
- mage_ai/data_cleaner/transformer_actions/utils.py
- mage_ai/server/app.py
- mage_ai/server/client/mage.py
- mage_ai/server/data/base.py
- mage_ai/server/data/models.py
- mage_ai/tests/data_cleaner/cleaning_rules/test_reformat_values.py
- mage_ai/tests/data_cleaner/statistics/test_calculator.py
- mage_ai/tests/data_cleaner/test_column_type_detector.py
Two major changes are made to the `mage_ai` package:
- All debug, warning, and error message now use Python's `logging` package in order to have finer control over the amount of debugging output printed. By default, the logging level is `WARNING`, so debug messages (like timing functions) are no longer printed by default. Contributors can enable them by setting the logging level to `DEBUG`:
```python
import logging
logging.getLogger('mage_ai').setLevel(logging.DEBUG)
```
- The following functions now have a `verbose` keyword argument (set to False by default) that when enabled describes the current steps the pipeline is performing:
- `connect_data`
- `connect_df`
- `clean` (supports cleaning with pipeline and without pipeline)
An example output is displayed below when `clean(dataframe, …
> [sk] Added verbose pipeline argument

- mage_ai/data_cleaner/statistics/calculator.py
- mage_ai/tests/data_cleaner/statistics/test_calculator.py
Added list statistics for the new list datatype:
- Minimum list length per column
- Maximum list length per column
- Average list length per column
- Distribution of list lengths per column
- Most frequent element that appears in all lists in a column
- Least frequent element that appears in all lists in a column
- Distribution of the elements that appear in lists in a column
To motivate these statistics, consider a scenario where tags are assigned to a product. For each product, the tags assigned are stored as lists in the dataframe. Then:
- The list length corresponds to the number of tags that have been assigned to the product. Thus looking at the min, max, average, and distribution of list lengths, a data scientist can gain insight into how many tags are being assigned by users
- The …
> [sk] Added list statistics

- mage_ai/frontend/components/datasets/Detail/index.tsx
- mage_ai/frontend/components/datasets/overview/index.tsx
- mage_ai/frontend/components/datasets/overview/utils.tsx
- mage_ai/frontend/pages/datasets/[...slug].tsx
- mage_ai/frontend/utils/number.ts
- Initial empty feature set version response was causing issues with the displaying of metrics percentage diffs when there shouldn't be any since no actions have been applied yet.
Before:
After:
> [jk]  Fix diffs bug when empty fsv response

- mage_ai/server/app.py
When writing a new pipeline, the column types loaded from file are updated to reflect changes in column names.
cc:
> [sk] Fixed column type detection error

- mage_ai/data_cleaner/cleaning_rules/impute_values.py
- mage_ai/data_cleaner/data_cleaner.py
- mage_ai/data_cleaner/shared/utils.py
- mage_ai/data_cleaner/transformer_actions/column.py
- mage_ai/data_cleaner/transformer_actions/constants.py
- mage_ai/data_cleaner/transformer_actions/helpers.py
- mage_ai/server/app.py
- mage_ai/tests/data_cleaner/cleaning_rules/test_impute_values.py
- mage_ai/tests/data_cleaner/statistics/test_calculator.py
- mage_ai/tests/data_cleaner/transformer_actions/test_column.py
Added imputation strategy for list datatypes:
1. If the list column is part of timeseries data, sequential imputation is used
2. If the list column has more than 40% of its values as a single value, mode imputation is used
3. If fewer than 30% of all entries are empty, then random imputation is used
4. Else constant imputation is used with a default value of `'[]'`
The motivation behind these rules is that (ideally) lists will act as aggregations of categories (like tags for a product, or genres for a movie), instead of a numerical object such as a vector (vectors should be stored by creating a column per dimension if so to allow for column-by-column analysis). As a result, I borrowed heavily from the imputation strategy for categories to define how lists should be imputed. Average and …
> [sk] Added list imputation strategy

- mage_ai/frontend/api/utils/url.ts
- mage_ai/frontend/next.config.js
- mage_ai/frontend/pages/index.tsx
- mage_ai/server/utils/frontend_renderer.py
- If there are additional query parameters or paths outside of the domain name, we need to redirect to pages while retaining all parts of the URL.
- Local
1. Add assetPrefix in html files.
- Replace all instances of `"nextExport":true` in the frontend_dist folder with `"assetPrefix":"/base/path","nextExport":true`.
- For example, the string replacement could be `"assetPrefix":"/proxy/5789","nextExport":true`.
2. Replace cloud base path placeholder with the relevant base path in order to make the correct API requests.
- Find the following exact string to replace in the frontend_dist folder: `CLOUD_NOTEBOOK_BASE_PATH_PLACEHOLDER_`
- It is important to include the `_` at the end of the placeholder string. Excluding it may cause issues.
- Do not prefix the base path with a forward slash. For …
> [jk] Update home page redirect

- mage_ai/data_cleaner/statistics/calculator.py
- mage_ai/tests/data_cleaner/statistics/test_calculator.py
Generates five number summary + outliers found through the 1.5 IQR method, as used to generate a box plot visualization. This can be accessed using `column/box_plot_data`
There are three reasons for creating these statistics as their own object within the statistics dictionary instead of using already existing statistics
- Min/Max for a box plot may not equal the overall min/max as the overall min/max might be an outlier, requiring two different statistics for both the minimum and maximum. To avoid confusion, keep the box plot specific pair local to the box plot data.
- Outliers for a box plot (calculated using the 1.5 IQR method) differ from the outlier calculation method from the rest of the statistics object (calculated using the 3 standard deviations rule). Makes sense to separate …
> [sk] Added box plot statistics calculation

- mage_ai/data_cleaner/shared/utils.py
Speed up clean_dataframe: only apply str cleaning on object dtype.
This reduces the time of clean_dataframe from 1.9s to 0.8s on a dataframe with 100k rows and 32 columns.
tested locally
cc:
> [xy] Speed up clean_dataframe.

- mage_ai/data_loader/base.py
- mage_ai/data_loader/file.py
- mage_ai/data_loader/postgres.py
- mage_ai/data_preparation/templates/data_loaders/file.py
- mage_ai/data_preparation/templates/data_loaders/postgres.py
- requirements.txt
This PR adds the basic framework for the different types of data loaders, and implements two specific data loaders in 
- `File` - loads data frame from file using automatic format inference to select the correct pandas loading method. Currently the filetypes supported are: CSV, JSON, Parquet, and HDF5 (another high compression file format used in machine learning).
- `Postgres` - loads data frame from a select query applied to a PostgreSQL database, either local or external.
Templates were also written for users to load data with these methods and extend functionality from.
Data loading was tested locally with loading local files of different formats. Postgres connections were tested by starting a database in memory, connecting to database, and loading data by making queries.
cc: …
> [sk] Added File and PostgreSQL data loaders

- mage_ai/data_loader/base.py
- mage_ai/data_loader/redshift.py
- mage_ai/data_loader/s3.py
- mage_ai/data_preparation/templates/data_loaders/file.py
- mage_ai/data_preparation/templates/data_loaders/postgres.py
- mage_ai/data_preparation/templates/data_loaders/redshift.py
- mage_ai/data_preparation/templates/data_loaders/s3.py
- requirements.txt
Added data loaders and templates for loading data from either an S3 bucket or a Redshift cluster. These data loaders are more complex since AWS offers multiple different authentication and authorization methods. I've designed support for the more common methods.
To perform these connections, two new libraries were added:
- `boto3` is used to access S3 buckets
- `redshift-connector` is used to access Redshift clusters
Note: The `redshift-connector` library (used to connect to a Redshift cluster) requires an older version of the `requests` library, so I downgraded it from version 2.28 to version 2.27. No other conflicts have emerged so far, but I can revert this change if need be.
Tests were performed by testing loading and querying data from S3 buckets and Redshift clusters.
cc: …
> [sk] Added data loaders + templates for S3 and Redshift

- mage_ai/data_preparation/models/block.py
- mage_ai/data_preparation/models/pipeline.py
- mage_ai/data_preparation/variable_manager.py
- mage_ai/server/server.py
This PR supports saving outputs for scratchpad
If 'outputs' is specified in scratchpad block of Pipeline PUT request, we'll save the outputs to disk and return them when fetching block outputs.
cc:
> [xy] Save outputs for scratchpad

- mage_ai/frontend/api/index.ts
- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/FileTree/constants.ts
- mage_ai/frontend/components/FileTree/index.tsx
- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/context/Pipeline.tsx
- mage_ai/frontend/pages/pipelines/[...slug].tsx
- add file tree component to notebook view & sync with backend
- update file tree when adding or renaming blocks
- jump to block when its corresponding file is clicked in the file tree
cc: @johnson-mage @tommydangerous @dy46
> [sp] file tree integration

- mage_ai/frontend/components/FileTree/index.tsx
- add bottom padding to stop browser link preview from obscuring last file node
> [sp] add bottom padding to file tree

- mage_ai/data_preparation/models/pipeline.py
Fix deleting non-empty folder.
Exception: `exception: "[Errno 39] Directory not empty: '/home/src/default_repo/pipelines/morning_sound/.variables/holy_water'"`
tested locally
cc:
> [xy] Fix deleting non-empty folder.

- mage_ai/frontend/components/FileTree/index.tsx
- mage_ai/frontend/oracle/icons/BaseIcon.tsx
- adjust folder caret icon color to match Figma design
> [sp] adjust folder caret icon color

- mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
- mage_ai/frontend/oracle/elements/Text/index.tsx
Add white-space: pre-wrap to the code output text for traceback formatting. Otherwise, it was just ignoring the white space in the string.
cc: @tommydangerous @johnson-mage @shrey-mage
> [dy] Add pre wrap property

- mage_ai/data_cleaner/column_types/column_type_detector.py
Fixed error in syntax error detection where some datetime datatypes returned by `type()` were not actually valid Python or NumPy types, causing the syntax error detection to crash. Now for these types alone, the actual underlying type is extracted and used instead.
Local test and were performed alongside running previous unit tests.
cc:
> [sk] Fixed bug in datetime syntax error detection

- mage_ai/data_preparation/models/block.py
- mage_ai/data_preparation/templates/transformers/default.py
- mage_ai/data_preparation/templates/transformers/suggestion_fmt.jinja
- mage_ai/data_preparation/templates/transformers/transformer_action_fmt.jinja
- mage_ai/tests/data_preparation/test_templates.py
Added `*args` to transformer templates so errors are not thrown if parameters are unused. 
In addition, updated error checking so that if `*args` is specified as an input, a function with `n` upstream blocks can have _at most_ `n` parameters in the function signature (excluding `*args`). If more than `n` parameters are specified (excluding `*args`), an error is thrown since there are more parameters than inputs. If `*args` is not specified as an input, then the regular error checking is performed.
Local tests were performed to make sure that errors are thrown properly.
cc:
@wangxiaoyou1993 @tommydangerous (bought up the issue)
> [sk] Added *args to transformer template

- mage_ai/data_preparation/models/block.py
- mage_ai/data_preparation/models/pipeline.py
- mage_ai/server/server.py
- mage_ai/server/websocket.py
Running the pipeline from the command line now all debug messages from the block. This was done by selectively enabling stdout redirection only when a server-side API call is made.
Local tests were performed to confirm that the command line print debug messages as well as the frontend notebook.
cc:
> [sk] Running pipeline from command line now prints block debug messages

- mage_ai/data_preparation/templates/data_exporters/bigquery.py
- mage_ai/data_preparation/templates/data_exporters/file.py
- mage_ai/data_preparation/templates/data_exporters/postgres.py
- mage_ai/data_preparation/templates/data_exporters/redshift.py
- mage_ai/data_preparation/templates/data_exporters/s3.py
- mage_ai/data_preparation/templates/data_exporters/snowflake.py
- mage_ai/data_preparation/templates/data_loaders/bigquery.py
- mage_ai/data_preparation/templates/data_loaders/file.py
- mage_ai/data_preparation/templates/data_loaders/postgres.py
- mage_ai/data_preparation/templates/data_loaders/redshift.py
- mage_ai/data_preparation/templates/data_loaders/s3.py
- mage_ai/data_preparation/templates/data_loaders/snowflake.py
- mage_ai/data_preparation/templates/repo/io_config.yaml
- mage_ai/io/base.py
- mage_ai/io/bigquery.py
- mage_ai/io/file.py
- mage_ai/io/io_config.py
- mage_ai/io/postgres.py
- mage_ai/io/redshift.py
- mage_ai/io/s3.py
- mage_ai/io/snowflake.py
- mage_ai/tests/data_preparation/test_templates.py
This code enables the user to define data IO configuration settings via a configuration file. In every repo created with `mage 
init`, a new file named `io_config.yaml` will be created, in which all IO configurations can be stored (alternatively from manually specifying the arguments in code). This is more useful, for example, when storing secret keys and access tokens where the secrets can be handled separately from code execution.
Here is a sample config file (contains only the default profile with credentials only for AWS data sources):
```yaml
default:
AWS:
Redshift:
database: your_redshift_database_name
user: your_authentication_user_name
password: your_authentication_password
host: your_redshift_cluster_hostname
port: your_redshift_cluster_port
cluster_identifier: …
```
> [sk] Added IO config handler

- mage_ai/data_preparation/models/file.py
File tree now excludes `venv` and `env`, which often include the virtual environment.
cc:
> [sk] Filter out virtual environment

- mage_ai/io/snowflake.py
Decreased timeout period for Snowflake requests to 20 seconds at max so failure to connect is more obvious. Users can still override default timeout period using configuration settings.
cc:
> [sk] Decreased timeout period for Snowflake connection

- mage_ai/data_preparation/models/block.py
When renaming a block, checks are now performed to make sure that the block name is not used in the same pipeline already, regardless of block type. This check if performed only if the block is tied to a specific pipeline (it has the `self.pipeline` attribute).
Tested locally to make sure errors are raised when trying to name blocks of different types the same name within the same pipeline.
cc:
> [sk] Validation on unique block name per pipeline

- mage_ai/server/utils/output_display.py
Escape single quotes so that the comment syntax doesn't cause issues when running the custom code
> [dy] Escape single quotes in custom code

- mage_ai/data_preparation/models/variable.py
Catch empty sample data exception and read from full path as a fallback.
```
server_1  | HTTPServerRequest(protocol='http', host='localhost:6789', method='GET', uri='/api/pipelines/demo_pipeline1', version='HTTP/1.1', remote_ip='172.20.0.1')
server_1  | Traceback (most recent call last):
server_1  |   File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1702, in _execute
server_1  |     result = method(*self.path_args, **self.path_kwargs)
server_1  |   File "/home/src/mage_ai/server/server.py", line 122, in get
server_1  |     pipeline=pipeline.to_dict(
server_1  |   File "/home/src/mage_ai/data_preparation/models/pipeline.py", line 156, in to_dict
server_1  |     blocks=[
server_1  |   File "/home/src/mage_ai/data_preparation/models/pipeline.py", line 157, in <listcomp> …
```
> [xy] Catch empty sample data exception.

- mage_ai/frontend/pages/index.tsx
`/pipelines/{uuid}` was getting appended to the url every time I refreshed the page.
tested locally
> [dy] Fix frontend routing

- mage_ai/data_cleaner/shared/utils.py
- mage_ai/data_cleaner/statistics/calculator.py
- mage_ai/shared/custom_types.py
- mage_ai/tests/data_cleaner/statistics/test_calculator.py
A small edge case occurred when a list of dictionary objects was stored within a Pandas data frame. While support for lists was handled before, handling dictionary objects within these lists causes various problems throughout the data cleaning pipeline due to an inability to hash a dictionary (including in statistics calculation and graph generation). 
To solve this problem a `FrozenDict` type was created, an immutable key-value store that doesn't permit mutations. For this reason, this type can be hashable without any major concerns of mutability. All non-mutating operations are still supported (such as fetching values from the dictionary).
When parsing a dictionary item in a list, the dictionary is converted to a `FrozenDict`, allowing the dictionary objects to be handled by Pandas …
> [sk] Added frozen dictionary type to handle lists with dictionary objects

- mage_ai/frontend/components/Sidekick/GlobalVariables.tsx
> [sp] fix typo on variables tab

- mage_ai/frontend/components/BlockCharts/utils.ts
- see above
Click on graphs tab, reload the page, select a block. The frontend should no longer crash.
> [sp] fix graphs tab crash on reload

- mage_ai/data_preparation/models/block.py
- mage_ai/data_preparation/templates/data_exporters/default.jinja
- mage_ai/data_preparation/templates/data_loaders/default.jinja
- mage_ai/data_preparation/templates/template.py
- mage_ai/data_preparation/templates/transformers/default.jinja
- mage_ai/server/server.py
- mage_ai/tests/data_preparation/test_templates.py
Support updating block type from scratchpad to data_loader, transformer, data_exporter
API for updating block type (Only allow updating from scratchpad to other block types)
```
PUT /api/pipelines/[pipeline_uuid]/blocks/[block_uuid]
{
"block": {
"type": "data_loader"/"transformer"/"data_exporter"
}
}
```
tested locally
cc:
> [xy] Support updating block type.

- mage_ai/frontend/components/ContextMenu/index.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/index.style.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
- added a `compact` prop to `FlyoutMenu` that reduces the min width to `UNIT * 20`
> [sp] fix min width of right click menu

- mage_ai/data_cleaner/cleaning_rules/remove_collinear_columns.py
Fixed error in collinear columns calculation where the correlation matrix reported `nan` when evaluating constant columns (since $\frac{0}{0} = undefined$). Added `self.EPSILON` to standard deviations to prevent full division by zero.
cc:
> [sk] Fixed undefined division error in collinearity check

- mage_ai/frontend/components/ActionForm/index.tsx
- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/FileEditor/index.tsx
- mage_ai/frontend/interfaces/BlockType.ts
- mage_ai/frontend/oracle/components/FlyoutMenu/FlyoutMenuClickOutside.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/FlyoutMenuInteractive.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/FlyoutMenuWrapper.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/index.style.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
- add dropdown to scratchpad blocks to convert into other block types
- remove "Add to current pipeline" button for scratchpad block files
- implement nested menu items for `FlyoutMenu`
cc: @johnson-mage @tommydangerous @dy46 @wangxiaoyou1993
> [sp] add "convert scratchpad block" functionality

- mage_ai/data_cleaner/column_types/column_type_detector.py
- mage_ai/tests/data_cleaner/test_column_type_detector.py
Any overflowing integers (including integer strings) that exist will now get mapped to `CATEGORY_HIGH_CARDINALITY` (as often these integers are ID numbers that technically are categorical). Note: when considering overflow, only signed types are considered currently (unsigned integers can hold larger values, but require manipulation on frontend to handle these values since JavaScript will overflow these integers)
Local testing was performed, along with the addition of more unit tests to check how large integers are mapped.
cc:
@wangxiaoyou1993 @dy46
> [sk] Overflowing integers don't raise errors

- mage_ai/data_preparation/models/pipeline.py
Support only updating one block when saving a pipeline. Right now when a block is executed, we are updating the entire pipeline metadata config which can overwrite updates that happened during the block execution. This is a temporary fix until we can have locks on pipeline editing.
tested locally 
> [dy] Support only updating one block

- mage_ai/frontend/components/datasets/overview/utils.tsx
- update datetime charts in the data table column header to match dark theme
> [sp] fix datetime chart tooltips not being visible

- mage_ai/frontend/styles/globals.css
- see above (browser history is preserved, but swiping left/right will not go back/forward in browser history)
- seems to work correctly regardless of mouse's location / selected element when scrolling
- all existing scrollable elements still seem to function correctly
> [sp] disable going back in browser when swiping

- mage_ai/data_preparation/models/pipeline.py
When duplicating pipelines, scratchpad blocks are ignored.
cc:
@wangxiaoyou1993 @shrey-mage
> [sk] Don't duplicate scratchpads in pipeline

- mage_ai/data_preparation/models/block.py
- mage_ai/server/websocket.py
Show error trace when the pipeline execution fails. Also, fix bug where the execute pipeline button just keeps spinning.
local
> [dy] Publish error trace for pipeline failure

- docs/production/native_cloud.md
Added docs on how to run Mage on open EC2 port as an alternative method to port forwarding from local host, along with some polish to the pre-existing docs.
Tested locally by using this method to connect to Mage app.
cc:
> [sk] Added docs on how to run Mage on open EC2 port

- docs/blocks/README.md
- docs/blocks/data_loading.md
- mage_ai/io/config.py
Added documentation for data loaders, including
- Example usage guide
- APIs for all clients
- How to use configuration settings for storing and loading secrets.
This new documentation was linked to `blocks/README.md` under the `data_loader` and `data_exporter` sections. In addition, some polish was performed to clean up some source code docs for configuration setting loaders.
cc:
> [sk] Added docs for data loaders

- mage_ai/frontend/components/ChartBlock/index.tsx
- mage_ai/frontend/components/FileBrowser/Folder.tsx
- mage_ai/frontend/components/FileBrowser/index.tsx
- mage_ai/frontend/components/Sidekick/Charts/index.tsx
- mage_ai/frontend/components/Sidekick/index.tsx
- mage_ai/frontend/interfaces/BlockType.ts
- mage_ai/frontend/interfaces/FileType.ts
- mage_ai/frontend/pages/pipelines/[...slug].tsx
- expand sideview, switch to charts tab, and scroll to chart when its corresponding file is clicked in the file browser
- refresh file browser when chart block is deleted
- update charts folder icon
cc: @johnson-mage @tommydangerous @wangxiaoyou1993
> [sp] jump to chart when selecting file

- mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
- mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
- mage_ai/frontend/pages/pipelines/[...slug].tsx
- Expands code block output when deleting block (should have no effect on successful block delete)
- Format error messages with newlines so that they can be read like a stack trace (done for chart blocks too)
- Indicate error block status when error deleting block (red outline, error symbol, etc)
> [sp] expand output on error deleting block

- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
- mage_ai/frontend/interfaces/DataSourceType.ts
- mage_ai/frontend/interfaces/TransformerActionType.ts
- add data exporter templates menu when adding a new block
- update data loader templates menu to include loading data from API
cc: @johnson-mage @wangxiaoyou1993
> [sp] update block templates on frontend

- mage_ai/server/websocket.py
The pyspark kernel should be using the `add_internal_output_info` method as well.
tested locally
cc:
> [dy] Fix rebase issue

- mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/CodeBlock/utils.ts
- mage_ai/frontend/components/ContextMenu/index.tsx
- mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/FlyoutMenuWrapper.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/index.style.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
- mage_ai/frontend/oracle/icons/custom/Convert.tsx
- add "convert block" icon to command buttons for scratchpad blocks
- reuse same "convert block" menu items for block dropdown & command button icon
- update `FlyoutMenuWrapper` to pass down props to `FlyoutMenu` (useful for relative positioning)
> [sp] update "convert scratchpad block"

- docs/production/native_cloud.md
Added guides for running Mage in an ECS cluster in two ways:
- Running the Mage code editor in cluster
- Running a complete Mage pipeline
Followed guides to both run Mage app and deploy Mage pipeline on ECS
cc:
> [sk] Added docs for running Mage in ECS

- mage_ai/data_preparation/templates/template.py
- mage_ai/data_preparation/templates/transformers/data_warehouse_transformer.jinja
- mage_ai/tests/data_preparation/test_templates.py
Fixed some bugs in data warehouse templates
- Switched from old configuration method (`IOConfig`) to new configuration method
- Fixed error with two types of payload values for `data_source` (`str` vs `DataSource` enum) throwing errors
Tested locally and validated against unit tests.
cc:
@wangxiaoyou1993 @shrey-mage
> [sk] Updated data loader and fixed data source bug

- mage_ai/io/base.py
- mage_ai/io/bigquery.py
- mage_ai/io/postgres.py
- mage_ai/io/redshift.py
- mage_ai/io/snowflake.py
Strips whitespace and newlines from around query to prevent formatting errors when used inside limiting subquery.
Tested locally by trying out different combinations of newlines, tabs, and whitespace around main query and testing if query can be successfully made.
cc:
> [sk] Strip whitespace and newlines from around query

- mage_ai/frontend/components/CodeBlock/utils.ts
- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.ts
- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/interfaces/BlockType.ts
- mage_ai/frontend/interfaces/DataSourceType.ts
- mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
- refactor data source menu items into builder util function
- add data source menu items to "add transformer block" dropdown
(Waiting on backend bugfix from Sachchit, will update w/ live test then)
cc: @johnson-mage @skunichetty @wangxiaoyou1993
> [sp] add data source transformer templates

- mage_ai/data_preparation/templates/repo/io_config.yaml
Updated base configuration file template to have better defaults:
- Default ports are provided for PostgreSQL and Redshift
- Added sample mappings for Google Service Account Key
- Added other default values where applicable:
- Added sample hostname for Redshift based off of existing structure
- Added default IAM profile name (default profile name is `default`)
- Added sample Snowflake account id based off of `account_id.region` format
- Added default Postgres DB name (`postgres` is a default database created when installing Postgres)
cc:
> [sk] Improved default values for configuration template

- README.md
Edited Quick Start to mention that MIT Kerberos development headers + libs need to be installed to use the `krb5` python package (used to connect to PySpark kernel). MacOS doesn't have this problem (Kerberos comes installed) but not all Linux distros have this library installed.
cc:
> [sk] Added MIT Kerberos install message to docs

- mage_ai/data_preparation/models/pipeline.py
- mage_ai/tests/data_preparation/models/test_pipeline.py
Added `validate` function which checks for cycles in pipeline. If a cycle exists, an `InvalidPipelineError` is raised. The algorithm used to perform this check is a modified depth-first search which recursively checks if each subtree path contains a cycle - for some given block in the pipeline, does there exist a path of downstream blocks back to itself? If so, a cycle exists. This can be done efficiently by making use of the recursive nature of the problem - if a subgraph is validated to not have any cycles, there is no need to check that subgraph when considering its parents.
If a cycle is found, the error message printed shows the path of blocks that form the cycle:
```
bitter_frost --> crimson_dust --> cool_feather --> crimson_thunder --> proud_forest --> shy_haze --> silent_frog --> …
```
> [sk] Added check for cycles in pipeline upon update

- mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
- submenus are now placed directly right of the parent menu
> [sp] fix flyout submenu positioning

- README.md
- requirements.txt
- setup.py
Make tables dependency optional since HDF5 is not a commonly used file format and it caused installation error.
https://github.com/mage-ai/mage-ai/issues/870
tested locally
cc:
> [xy] Make tables dependency optional.

- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
- mage_ai/frontend/pages/pipelines/[...slug].tsx
- Group more items in transformer action flyout menu to minimize scrolling.
- Prevent flashing transformer action flyout menu when scrolled all the way to the bottom of the screen.
> [jk] Improve transformer action flyout menus

- mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
- mage_ai/frontend/components/DependencyGraph/GraphNode.tsx
- mage_ai/frontend/components/DependencyGraph/index.tsx
- mage_ai/frontend/oracle/components/Tooltip/index.tsx
- mage_ai/frontend/pages/pipelines/[...slug].tsx
- Refresh block status in dependency graph after running a block.
Block execution (Note: The status changes to a circle first to indicate that it was "updated"):
Pipeline execution:
cc:
> [jk] Fetch pipeline after running block

- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
- When clicking on a pipeline or block name but not changing the name and then pressing "Enter", the name input would immediately unfocus (i.e. blur) when clicking back into the input. This PR resolves this bug.
Before:
After:
> [jk] Fix auto-unfocus bug when renaming pipeline or block with "Enter" keyboard shortcut

- mage_ai/frontend/components/RecommendationsWindow/index.tsx
- Recommendation blocks were empty when added to pipeline after updating block configuration to handle SQL blocks.
cc:
> [jk] Fix empty recommendation code blocks bug

- mage_ai/data_preparation/executors/block_executor.py
- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/data_preparation/models/variable.py
- mage_ai/data_preparation/variable_manager.py
- mage_ai/orchestration/db/models.py
- mage_ai/orchestration/pipeline_scheduler.py
- mage_ai/server/api/base.py
- mage_ai/server/api/orchestration.py
- mage_ai/server/server.py
* Store block run outputs with partitions when execution pipelines with schedules
* Path: `{variables_dir}/{pipeline_uuid}/.variables/{pipeline_schedule_id}/{execution_date}/{block_uuid}/..`
* Add API to fetch block run outputs
Tech design: https://www.notion.so/mageai/Orchestration-engine-a5ed63c71c594801897fb9df3c9fefb7
tested locally
cc: @dy46
> [xy] Store block run outputs with partitions.

- mage_ai/orchestration/db/models.py
- mage_ai/orchestration/pipeline_scheduler.py
Run blocks in separate processes so that we can run blocks in parallel.
TODO: handle race condition
tested locally
Execution logs for the pipeline below
cc:
> [xy] Run blocks in separate processes.

- mage_ai/frontend/components/FileBrowser/Folder.tsx
- mage_ai/frontend/components/FileBrowser/index.tsx
- mage_ai/frontend/components/FileBrowser/utils.ts
- mage_ai/frontend/interfaces/FileType.ts
- mage_ai/frontend/pages/pipelines/[...slug].tsx
- Unused files (files that don't have a corresponding code block that exists in the currently selected pipeline) will appear as muted and italicized in the file browser.
cc:
@wangxiaoyou1993 @tommydangerous @dy46
> [jk] Indicate unused block files in FileBrowser

- mage_ai/frontend/components/ContextMenu/index.tsx
- mage_ai/frontend/components/FileBrowser/Folder.tsx
- mage_ai/frontend/components/FileBrowser/index.tsx
- mage_ai/frontend/components/FileBrowser/utils.ts
- mage_ai/frontend/pages/pipelines/[...slug].tsx
- There was an error when deleting chart files from the file browser, so this PR resolves that.
- Move pipelines folder to top of file browser so it's more accessible.
> [jk] Update API request for deleting chart file from file browser

- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
- Navigating up and down in the flyout menus with the keyboard when adding a `Data loader`, `Transformer`, or `Data exporter` block had issues and would behave inconsistently, so this PR disables that functionality specific to those buttons.
- The keyboard navigation still works for other components using flyout menus, such as the `File` and `Run` buttons in the file browser header.
Bug (keyboard navigation doesn't work as intended):
> [jk] Disable keyboard navigation in flyout menus for adding blocks

- scripts/deploy/terraform/env_vars.json
- scripts/deploy/terraform/main.tf
Support env vars in ecs task definition.
tested locally with `terraform apply`
cc:
> [xy] Support env vars in ecs task definition.

- mage_ai/frontend/components/PipelineDetailPage/index.tsx
- mage_ai/frontend/components/VariableOverwrites/index.style.tsx
- mage_ai/frontend/components/VariableOverwrites/index.tsx
- mage_ai/frontend/oracle/components/FlexTable/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/pipeline-runs/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/schedules/[...slug].tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/schedules/index.tsx
Show variables overwrites when a schedule is selected in the schedules list view. Also update navigation from schedules page.
cc:
> [dy] Add variable overwrites to schedules sidekick

- mage_ai/data_preparation/models/block/__init__.py
Only pass global_vars when method definition has kwargs.
tested locally with the data loader
before and after fix
cc:
> [xy] Only pass global_vars when method definition has kwargs.

- scripts/deploy/terraform/aws/env_vars.json
- scripts/deploy/terraform/aws/main.tf
- scripts/deploy/terraform/aws/variables.tf
Allow pass aws access key via env var.
* `TF_VAR_AWS_ACCESS_KEY_ID` for AWS_ACCESS_KEY_ID variable
* `TF_VAR_AWS_SECRET_ACCESS_KEY` for AWS_SECRET_ACCESS_KEY variable
Example usage
```
export TF_VAR_AWS_ACCESS_KEY_ID=xxxx
export TF_VAR_AWS_SECRET_ACCESS_KEY=yyyy
terraform apply
```
or
```
TF_VAR_AWS_ACCESS_KEY_ID=xxxx TF_VAR_AWS_SECRET_ACCESS_KEY=yyyy terraform apply
```
tested locally
> [xy] Allow pass aws access key via env var.

- mage_ai/frontend/components/DependencyGraph/index.tsx
Increasing the width was causing the nodes in the dependency graph to overlap.
cc:
> [dy] Fix dependency graph spacing

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/data_preparation/models/pipeline.py
- mage_ai/server/api/blocks.py
- mage_ai/server/websocket.py
- mage_ai/shared/logger.py
Show print statements in pipeline execution. I also refactored the logging logic for block execution to remove the `log_func` and `redirect_outputs` arguments and replaced it with `build_block_output_stdout`.
tested locally. verified that existing functionality still works
> [dy] Show print statements when executing pipeline

- mage_ai/server/execution_manager.py
- mage_ai/server/websocket.py
Not copy variables and logs when executing pipelines. Otherwise, it'll take very long to copy the pipeline config folder.
tested locally
cc:
> [xy] Not copy variables and logs when executing pipelines.

- mage_ai/cluster_manager/aws/emr_cluster_manager.py
- mage_ai/server/active_kernel.py
- mage_ai/services/aws/emr/emr.py
- mage_ai/services/aws/emr/launcher.py
Automatically set active cluster when switching to pyspark kernel
tested locally
cc:
> [xy] Automatically set active cluster when switching to pyspark kernel

- scripts/deploy/terraform/gcp/main.tf
- scripts/deploy/terraform/gcp/variables.tf
Add terraform script to deploy Mage to GCP.
References
* https://ruanmartinelli.com/posts/terraform-cloud-run
* https://www.fpgmaas.com/blog/deploying-a-flask-api-to-cloudrun
tested locally
* Add GOOGLE_CREDENTIALS env variable
* Provide project id and docker image
* Run `terraform apply`
cc:
> [xy] Add terraform script to deploy to GCP.

- mage_ai/data_preparation/variable_manager.py
Fix setting global variable. Using get_repo_path in method definition could cause the default being set before the actual repo_path is set in env var.
tested locally
cc:
> [xy] Fix setting global variable.

- dev.Dockerfile
- mage_ai/data_preparation/executors/block_executor.py
- mage_ai/data_preparation/executors/pyspark_block_executor.py
- mage_ai/data_preparation/logger_manager.py
- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/data_preparation/repo_manager.py
- mage_ai/data_preparation/templates/pipeline_execution/spark_script.jinja
- mage_ai/orchestration/pipeline_scheduler.py
- mage_ai/server/active_kernel.py
- mage_ai/server/api/blocks.py
- mage_ai/server/utils/output_display.py
- mage_ai/services/aws/emr/emr.py
* Not return print output when fetching block output. (Otherwise, expanding table doesn't show the correct data)
* Enable spark kernel in dev dockerfile by default
* Update block execution status correctly
* Fix "FileNotFoundError: [Errno 2] No such file or directory: '/mnt/var/lib/livy/metadata.yaml'" error in data exporter block
* Fix pyspark executor initialization.
* Fix missing import in pyspark execution script.
* Update block status when pyspark executor completes.
* Include execution_partition in pyspark block execution.
* Speed up EMR status polling.
* Add more pyspark executor loggings
TODOs
tested with spark kernel locally
cc:
> [xy] More improvements on spark kernel

- scripts/deploy/cloudformation/ecs.sh
- scripts/dev.sh
- scripts/frontend/add.sh
- scripts/init.sh
- scripts/run.sh
- scripts/run_ec2.sh
- scripts/start.sh
My default sh is dash, which does not support things like empty array assignment. Not sure exactly why.
Ex: POSITIONAL=()
The space in '# !/bin/bash' caused the shebang line to be ignore, and ran using the default sh.
```
~ % cat /tmp/bar.sh           
ps aux | grep "$$"
~ % /tmp/bar.sh          
kestrel   260579  0.0  0.0   2704   912 pts/1    S+   23:02   0:00 sh /tmp/bar.sh
kestrel   260581  0.0  0.0   6336  2104 pts/1    S+   23:02   0:00 grep 260579
~ % cat /tmp/foo.sh
#!/bin/bash
ps aux | grep "$$"
~ % /tmp/foo.sh  
kestrel   260726  0.0  0.0   7028  3240 pts/1    S+   23:02   0:00 /bin/bash /tmp/foo.sh
kestrel   260728  0.0  0.0   6336  2232 pts/1    S+   23:02   0:00 grep 260726
```
> Fix #! in shell scripts

- mage_ai/data_preparation/templates/pipeline_execution/spark_script.jinja
- mage_ai/server/server.py
- mage_ai/server/utils/output_display.py
- mage_ai/server/websocket.py
- mage_ai/services/aws/emr/emr.py
- mage_ai/services/aws/emr/launcher.py
* Run tests when executing pyspark blocks
* Not return printed outputs when fetching variables
* Allow running magic commands that start with "%%"
* Filter out empty websocket messages
* Auto-terminate cluster if it’s idle for 30 minutes
TODOs
cc:
> [xy] Continue improving spark kernel and pipeline

- mage_ai/frontend/components/charts/LineSeries.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runs.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runtime.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/monitors/index.tsx
They were getting cut off before, so updated the formatting and margins for the charts
tested locally
cc:
> [dy] Update axis labels

- mage_ai/frontend/components/PipelineDetail/index.style.tsx
- See title.
- When there are many tabs for adding back blocks, some tabs may be hidden. Will need to address in separate PR.
cc:
> [jk] Remove overflow so kernel dropdown is visible

- mage_ai/frontend/components/charts/LineSeries.tsx
- mage_ai/frontend/components/charts/utils/label.ts
- Fix tooltip cutoff issue in line series charts.
Before:
After:
> [jk] Reposition tooltips in line series chart

- mage_ai/frontend/components/ChartBlock/ChartController.tsx
- Some x-axis labels were missing in the vertical bar charts.
Before:
After:
> [jk] Increase number of axis tick labels for vertical bar chart

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/data_preparation/models/constants.py
- mage_ai/data_preparation/models/pipeline.py
- mage_ai/data_preparation/templates/data_exporters/streaming/opensearch.yaml
- mage_ai/data_preparation/templates/data_loaders/streaming/kafka.yaml
- mage_ai/data_preparation/templates/template.py
- mage_ai/io/base.py
- mage_ai/io/file.py
- mage_ai/server/kernels.py
- mage_ai/server/server.py
- mage_ai/server/websocket.py
- mage_ai/shared/strings.py
- mage_ai/tests/data_preparation/models/test_block.py
- mage_ai/tests/data_preparation/models/test_pipeline.py
- mage_ai/tests/data_preparation/models/test_variable.py
- mage_ai/tests/data_preparation/test_templates.py
- mage_ai/tests/data_preparation/test_variable_manager.py
Update API for streaming pipelines.
* Add pipeline type: streaming
* Support yaml as a block language
* Add code template for kafka and opensearch
API doc: https://www.notion.so/mageai/Streaming-pipelines-Kafka-source-8abc1b65547c4982ba6568ccbba512ce#e25fb4ad7a3744878b6fa58a255ad052
TODOs
tested locally
cc:
> [xy] Update API for streaming pipelines.

- mage_ai/data_preparation/executors/streaming_pipeline_executor.py
- mage_ai/streaming/sources/kafka.py
Batch consume events from kafka to improve performance.
Default batch size is 100. Batch size can be configured in the data loader block.
tested locally. Increasing batch size can support more QPS.
cc:
> [xy] Batch consume events from kafka to improve performance

- Dockerfile
- dev.Dockerfile
- mage_ai/data_integrations/logger/utils.py
- mage_ai/orchestration/pipeline_scheduler.py
- requirements.txt
- Add `mage-integrations` package to Dockerfiles (dev and prod)
- Lazy import `mage_integrations` only when it’s needed
In order to use this, you must use Mage in Docker.
Currently, it won’t work if you install via `pip` or `conda`.
TODO:
> [td] Install mage-integrations in Dockerfiles

- requirements.txt
When I started a local development environment with the following commands:
```
$ ./scripts/init.sh demo_project
$ ./scripts/dev.sh demo_project
```
the following error message was encountered:
```
"ModuleNotFoundError: No module named 'singer'"
```
Tested the changes locally with the above error messages resolved.
cc:
@dy46
> Add a missing "singer-python" module when running locally with a development environment

- mage_integrations/sources/salesforce/client/tap_salesforce/__init__.py
- mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/__init__.py
- mage_integrations/sources/salesforce/client/tap_salesforce/sync.py
- Update Salesforce source to use `bookmark_properties` instead of `replication-key`.
State output:
```
{"current_stream": null, "bookmarks": {"Account": {"version": 1666126272702, "SystemModstamp": "2022-10-17T15:55:07.000000Z"}}}
```
> [td] Use bookmark properties instead of replication-key

- mage_ai/server/server.py
Kill scheduler before autoreload so that there won't be multiple schedulers running simultaneously.
tested locally
cc:
> [xy] Kill scheduler before autoreload.

- mage_ai/data_preparation/templates/data_exporters/streaming/opensearch.yaml
- mage_ai/streaming/sinks/opensearch.py
- mage_ai/tests/data_preparation/test_templates.py
Support configuring Opensearch authentication and authenticate with local opensearch.
Example config
```yaml
connector_type: opensearch
host: https://host.docker.internal:9200
index_name: test_index
verify_certs: false
http_auth: 'admin:admin'
```
tested locally
cc:
> [xy] Support configuring Opensearch authentication.

- mage_ai/frontend/components/Logs/Toolbar/constants.ts
- mage_ai/frontend/components/Logs/Toolbar/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
- Sort logs in chronological order, but only show latest logs initially. User can load older logs at the top of page.
- Move button to load latest logs to bottom of page.
> [jk] Log improvements

- Dockerfile
- dev.Dockerfile
Set docker image python version to 3.10.
Python 11 was released yesterday, which caused pip install errors. https://github.com/mage-ai/mage-ai/actions/runs/3319811249/jobs/5485428962
tested locally
cc:
> [xy] Set docker image python version to 3.10.

- mage_ai/frontend/components/Logs/Filter/index.tsx
- mage_ai/frontend/components/Logs/Toolbar/index.tsx
- mage_ai/frontend/interfaces/LogType.ts
- mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
- Initially fetch only the last day's worth of logs to prevent unnecessary loading of excessive logs.
- Require time range on logs to mitigate large response payloads.
> [jk] Fetch default log range

- Dockerfile
- dev.Dockerfile
The built-in `pip` version in the docker image was not the latest, which led to unnecessary warnings.
The added step completed without issues:
```
Step 11/26 : RUN ${PIP} install --upgrade pip
---> Running in d78a238520dd
Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (22.2.2)
Collecting pip
Downloading pip-22.3-py3-none-any.whl (2.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 1.3 MB/s eta 0:00:00
Installing collected packages: pip
Attempting uninstall: pip
Found existing installation: pip 22.2.2
Uninstalling pip-22.2.2:
Successfully uninstalled pip-22.2.2
Successfully installed pip-22.3
```
cc:
> Upgrade pip to the latest version to avoid warning messages in docker 

- mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
> [dy] Update grouping logic

- mage_ai/frontend/components/Logs/Detail/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
- User can hover over a log message to view its full content in a tooltip.
> [jk] Add tooltip for log message

- mage_ai/server/api/clusters.py
* Only return emr clusters for pyspark kernel to fix errors.
tested locally
cc:
> [xy] Only return emr clusters for pyspark kernel to fix errors.

- mage_integrations/mage_integrations/sources/google_search_console/streams.py
- mage_integrations/mage_integrations/transformers/base.py
Fix transformer script.
```
Exception: Transformer process failed with error [Errno 2] No such file or directory: '/home/src/default_repo/pipelines/integration_search_console/.variables/114/20221102T200000/fragrant_meadow/df/data.parquet'. {"error": "[Errno 2] No such file or directory: '/home/src/default_repo/pipelines/integration_search_console/.variables/114/20221102T200000/fragrant_meadow/df/data.parquet'", "errors": [" File \"/usr/local/lib/python3.10/site-packages/mage_integrations/transformers/base.py\", line 154, in <module>
transformer.process(sys.stdin.buffer)
", " File \"/usr/local/lib/python3.10/site-packages/mage_integrations/transformers/base.py\", line 145, in process
self.transform_input(input_buffer)
", " File \"/usr/local/lib/python3.10/site-packages/mage_integrations/tra …
```
> [xy] Fix transformer script.

- mage_integrations/mage_integrations/connections/mysql/__init__.py
- mage_integrations/mage_integrations/connections/sql/base.py
- mage_integrations/mage_integrations/destinations/mysql/README.md
- mage_integrations/mage_integrations/sources/mysql/__init__.py
- mage_integrations/mage_integrations/sources/mysql/templates/config.json
- mage_integrations/requirements.txt
Support connecting to MySQL via SSH tunnel.
tested locally
`python3 mage_integrations/sources/mysql/__init__.py --config TEST_CONFIG_MYSQL_SSH.json  --discover > TEST_CATALOG_MYSQL_SSH.json`
cc:
> [xy] Support connecting to MySQL via SSH tunnel.

- mage_integrations/mage_integrations/sources/postgresql/__init__.py
Update postgres query to fix ambiguous `table_name` column error.
tested locally
cc:
> [dy] Update postgres query

- mage_ai/io/bigquery.py
Clean dataframe column names before exporting to bigquery. Column names can't contain empty spaces.
tested locally
cc:
> [xy] Clean dataframe column names before exporting to bigquery.

- mage_ai/frontend/components/charts/utils/label.ts
- mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runtime.tsx
- Fix bug when rendering tooltips in Block Runtime line charts.
> [jk] Bugfix block runtime charts

- mage_integrations/mage_integrations/destinations/base.py
- mage_integrations/mage_integrations/destinations/bigquery/__init__.py
- mage_integrations/mage_integrations/destinations/sql/base.py
- mage_integrations/mage_integrations/destinations/sql/utils.py
- mage_integrations/mage_integrations/sources/base.py
- mage_integrations/mage_integrations/sources/bigquery/__init__.py
- mage_integrations/mage_integrations/sources/catalog.py
Allow automatically add new fields.
If `auto_add_new_fields` field is set to true in stream metadata, we'll automatically discover and add new fields.
For destination, if new columns are in records, we'll alter table schema automatically. Example alter command:
`ALTER TABLE test_dataset.test_table_google_search_console ADD COLUMN ctr FLOAT64, ADD COLUMN position FLOAT64`
This PR only adds the alter command for bigquery. Will add alter commands for other destinations in a later PR.
tested locally
cc:
> [xy] Allow automatically add new fields.

- mage_integrations/mage_integrations/sources/google_sheets/__init__.py
Fix google sheets number type. "integer" type was not added to number columns.
tested locally
cc:
> [xy] Fix google sheets number type.

- mage_integrations/mage_integrations/sources/sql/base.py
Fix sql column names. Use raw column names in the records so that the column name matches the schema.
Otherwise, we got null values from the postgres source due to mismatch column names.
tested locally
cc:
> [xy] Fix sql column names.

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/data_preparation/models/pipelines/integration_pipeline.py
- mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
- mage_ai/frontend/components/IntegrationPipeline/index.tsx
- mage_ai/frontend/utils/string.ts
- mage_ai/orchestration/pipeline_scheduler.py
- mage_integrations/mage_integrations/destinations/base.py
- mage_integrations/mage_integrations/sources/base.py
- mage_integrations/mage_integrations/sources/sql/base.py
- mage_integrations/mage_integrations/sources/sql/utils.py
- mage_integrations/mage_integrations/sources/utils.py
- Use `singer.write_bookmark` to nest bookmarks in a bookmark key
- Then pass that to `write_state`; now state messages contain top level bookmark key in the dictionary
- Support bookmarks for multiple streams
- Always write state for successfully saved streams even if error from another stream
cc:
> [td] Update bookmark and state logic

- docker-compose.yml
- mage_ai/data_preparation/logging/logger_manager.py
- mage_ai/data_preparation/models/pipeline.py
- mage_ai/data_preparation/models/pipelines/integration_pipeline.py
- mage_ai/data_preparation/repo_manager.py
- mage_ai/data_preparation/templates/repo/metadata.yaml
- mage_ai/data_preparation/variable_manager.py
- mage_ai/orchestration/db/__init__.py
- mage_ai/server/server.py
- mage_ai/tests/data_preparation/models/test_block.py
- mage_ai/tests/data_preparation/test_variable_manager.py
- mage_ai/tests/orchestration/db/test_models.py
Separate data and code directories. The default directory is `~/.mage_data`. Default directory can be provided via `MAGE_DATA_DIR` environment variable. User can override it in the project's metata.yaml via `variables_dir` field.
* Move variables to separate directory
* Move logs to separate directory.
TODOs
tested locally
cc:
> [xy] Separate data and code directories.

- mage_integrations/mage_integrations/destinations/base.py
- mage_integrations/mage_integrations/destinations/bigquery/__init__.py
- mage_integrations/mage_integrations/destinations/bigquery/utils.py
- mage_integrations/mage_integrations/destinations/constants.py
- mage_integrations/mage_integrations/sources/base.py
- mage_integrations/mage_integrations/sources/catalog.py
- mage_integrations/mage_integrations/sources/messages.py
Support partition keys for big query. Bigquery only supports one partition key field, but other destinations can support more, so the `partition_keys` field is an array. This adds the `partition_keys` field to the schema field in the data loader yaml.
tested locally
> [dy] Add partition keys to schema for Bigquery

- mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
- mage_ai/frontend/components/IntegrationPipeline/index.tsx
Only allow 1 column to be selected for partition key, and only show the column when the destination is bigquery.
tested locally
> [dy] Add frontend restrictions on partition key

- mage_ai/frontend/components/IntegrationPipeline/index.style.tsx
- Transformer action dropdown was hidden in integration pipeline, so this PR removes that.
cc:
> [jk] Fix hidden overflow in integration pipeline section

- mage_ai/io/bigquery.py
Fix bigquery sql block.
Create table command should be `CREATE TABLE {table_id} AS ...`
tested locally
cc:
> [xy] Fix bigquery sql block.

- mage_ai/frontend/components/FileEditor/index.tsx
- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- Added a comment in new dbt model block referencing docs. This also fixes the bug where new sql files would NOT be immediately created when adding a new dbt model (some content was needed in the code block for the new file to appear; otherwise, the new file would only be created after adding some content to the block and manually saving). 
- UX improvement: Automatically scroll to top when switching to file editor tab (could be confusing if user sees blank space when switching tabs).
File immediately created when adding new dbt model:
Scroll file editor block into view when switching tabs:
> [jk] Link to docs in sql comment when adding new dbt model

- mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/index.tsx
- mage_ai/frontend/components/shared/Table/index.style.tsx
- mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.style.ts
- mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
- Make streams tabs scrollable so it doesn't overflow container.
- Make first column of summary table sticky for better UX.
> [jk] Bugfixes: Streams tabs overflow and Summary table sticky first column

- mage_ai/orchestration/db/__init__.py
Got error below when running multiple schedules at the same time on GCP.
```
psycopg2.OperationalError: connection to server on socket "...." failed: FATAL: remaining connection slots are reserved for non-replication superuser connections
```
Increase pool size for postgres. Default value is 5.
https://docs.sqlalchemy.org/en/14/core/pooling.html
tested locally
cc:
> [xy] Increase pool size for postgres.

- mage_ai/frontend/components/Logs/Filter/index.tsx
- mage_ai/frontend/components/Logs/Toolbar/constants.ts
- mage_ai/frontend/components/Logs/Toolbar/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
- mage_ai/server/api/logs.py
- Fetch logs in intervals instead of all at once.
- Fixed issue where clicking on a log detail would reset the logs viewed if viewing past logs.
cc:
> [jk] Limit log fetching

- mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
- There was a "Rendered fewer hooks than expected" error that occurred when resizing the window on the Pipeline runs > Block runs page, so this PR fixes it.
Before:
After:
> [jk] Remove useMemo call causing frontend error

- mage_integrations/mage_integrations/destinations/sql/utils.py
Got the error:
```
2022-12-01T23:15:28 PostgreSQL process failed with error invalid input syntax for type json LINE 2: ...opify/Order/4202236117070' AS VARCHAR(255)), CAST('[{''''id'... ^ DETAIL: Token "'" is invalid. CONTEXT: JSON data, line 1: [{'... .
```
Convert list value to json. 
tested locally
cc:
> [xy] Convert list value to json.

- mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
- mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/index.tsx
- Alphabetize columns listed in stream settings, as well as rows in stream table.
Columns were added to properties out of order but automatically sorted:
> [jk] Alphabetize stream setting properties and table rows

- mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
- mage_ai/orchestration/pipeline_scheduler.py
- Updates pipeline schedule pertaining to a pipeline run to `inactive` status if the trigger was scheduled to run only once and was `active` status. Changes made on the backend.
- Added refresh interval to Triggers list page so it periodically checks for updates to the trigger and latest run statuses.
> [jk] Update once trigger with completed run to inactive

- mage_ai/orchestration/pipeline_scheduler.py
- mage_ai/server/api/orchestration.py
Restart block runs that are in the running state, but do not have a process running. This should only occur when the app is restarted after crashing. For integration pipelines, this will restart from the source block run.
One side effect of this change is that restarting the server when developing locally may create duplicate processes. I could just terminate all the active processes when they restart, but that doesn't seem ideal either. Since it would only effect local dev, I don't think it's a blocker for now.
tested locally
> [dy] Restart crashed block runs after app start

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/data_preparation/models/block/dbt/__init__.py
Fix 'outputs' referenced before assignment error.
tested locally
cc:
> [xy] Fix 'outputs' referenced before assignment error.

- mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
- When clicking on logs for an individual pipeline run or block run, only show the relevant logs (previously showed logs for all subsequent and previous pipeline/block runs if it was re-ran).
> [jk] Show specific pipeline or block run logs

- mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
- mage_ai/frontend/interfaces/IntegrationSourceType.ts
- Add `uuid` as column type option when configuring integration source.
> [jk] Add uuid column type option

- mage_integrations/mage_integrations/destinations/bigquery/__init__.py
- mage_integrations/mage_integrations/destinations/sql/utils.py
Column names can contain reserved keywords, and it causes the bigquery queries to fail. Adding backticks to the column name fixes that issue.
tested locally
> [dy] Add backticks for bigquery

- mage_integrations/mage_integrations/connections/sql/base.py
- mage_integrations/mage_integrations/destinations/bigquery/__init__.py
Add `clean_column_name` to the partition_key. Also added a try/except to the sql connection execute method because right now, the error doesn't get logged.
tested locally
> [dy] Update partition key column name

- mage_ai/orchestration/pipeline_scheduler.py
Set default value of schedule_after_complete to false to reduce concurrent writes.
tested locally
cc:
> [xy] Set default value of schedule_after_complete to false.

- mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
- mage_ai/frontend/components/Sidekick/index.tsx
- The number of columns in the code block output preview is limited to 30, so this adds a note to the footer. User can see row number for number of rows displayed.
No note for less than 31 columns:
> [jk] Indicate number of columns displayed in code block output footer

- mage_ai/frontend/components/IntegrationPipeline/index.tsx
- Resolves frontend error when user toggles "automatically add new fields" or "disable column type check" setting for integration pipeline when no streams have been selected.
- Local. Toggles are disabled when no stream selected.
> [jk] Disable setting toggles when no stream selected

- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
In the editor, if you click on a block file after opening a regular file, the block file doesn't load. Instead, it scrolls down in the regular file.
This PR removes the open regular files so that clicking the block file shows the file and scrolls to the appropriate place.
| Before | After |
| - | - |
| <video src="https://user-images.githubusercontent.com/3804139/208254235-9a889d3d-6a57-46cc-9fa7-ffb76820339d.mov"> | <video src="https://user-images.githubusercontent.com/3804139/208254241-fb7db0a2-d239-4cc8-b1fb-03da854c5a8c.mov"> |
> [Frontend][Bug] Fix selecting block file

- mage_ai/data_preparation/templates/repo/pipelines/example_pipeline/metadata.yaml
The example pipeline has a duplicate entry in `downstream_blocks`. This PR removes the duplicate so there's only one `export_titanic_clean`.
Successfully executed the pipeline.
> Remove duplicate downstream block in example pipeline

- mage_ai/cli/main.py
Start db_connection session from `cli/main.py` because it's possible the server isn't running already.
if the session already exists, the session won't be created, so should be safe.
> [dy] Start db session from mage run

- mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
- mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
- mage_ai/frontend/components/DataTable/index.tsx
- Horizontal scrollbar in code block output is no longer cut off.
- Trimmed excess padding in block output.
Horizontal scrollbar not cut off:
Before (with excess padding):
After:
cc:
> [jk] Code block output spacing

- mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
- mage_ai/frontend/utils/date.ts
- "Running pipeline once" would start in the future in certain situations (e.g. sometimes with local Postgres sources), so timezone should not affect the pipeline running immediately with the trigger date set in the past 1 day.
> [jk] Create trigger 1 day ago to avoid timezone issues

- mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
- Commenting out code from https://github.com/mage-ai/mage-ai/pull/1530 since it was filtering out certain logs when viewing by individual pipeline or block run.
- N/A
cc:
> [jk] Revert "Show specific pipeline or block run logs" PR

- mage_ai/frontend/components/FileEditor/index.tsx
- mage_ai/frontend/components/Terminal/index.tsx
- mage_ai/frontend/interfaces/FileType.ts
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- mage_ai/server/server.py
- mage_ai/server/websocket.py
- When user clicks on `requirements.txt` file in root project folder, they can pip install the packages saved in that file by clicking on a button (instead of having to enter a command through the Sidekick terminal). This automatically opens up the terminal to see the output from the `pip install -r requirements.txt` command.
cc:
> [jk] Add button for installing  packages from requirements.txt file

- mage_ai/frontend/components/CodeBlock/index.style.tsx
- Fix z-index issue on "More actions" dropdown.
> [jk] Bugfix - More actions dropdown

- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.ts
- mage_ai/frontend/components/PipelineDetail/index.tsx
- Add clarification that Scratchpad blocks are not executed in the pipeline.
cc:
> [jk] Add note to Scratchpad blocks

- mage_ai/orchestration/pipeline_scheduler.py
Fix retrying integration pipeline. Currently, if a pipeline run crashes and reruns, it'll rerun all block runs.
Fix: for each subbatch, check whether data_exporter completes from the executable block runs instead of all block runs. If the data exporter block run doesn't complete, rerun that subbatch of data loader, transformer, data exporter block runs.
tested locally
cc:
> [xy] Fix retrying integration pipeline.

- mage_ai/frontend/components/CodeBlock/index.tsx
- When the following block was selected, its header would block the AddNewBlocks dropdown so this PR fixes that issue.
Before:
After:
cc:
> [jk] Fix AddNewBlocks dropdown from being blocked by following block header

- mage_ai/orchestration/execution_process_manager.py
- mage_ai/orchestration/pipeline_scheduler.py
- mage_ai/orchestration/utils/resources.py
- mage_ai/tests/orchestration/test_pipeline_scheduler.py
Sample log:
```
Pipeline black_morning for run 4266 in schedule 162 is alive.
```
Tags:
```json
{
"pipeline_run_id": 4266,
"pipeline_schedule_id": 162,
"pipeline_uuid": "black_morning",
"cpu": 0.35,
"cpu_total": 8,
"cpu_usage": 0.04375,
"memory": 2209,
"memory_total": 17010,
"memory_usage": 0.12986478542034097
}
```
cc:
> [td] Show pipeline heartbeat in logs

- mage_ai/frontend/components/DataTable/index.tsx
- mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
- Block output was not appearing in certain scenarios, so this PR parses and displays text data (in addition to existing table data).
> [jk] Show block output for non-table output data.

- mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
- Filters logs by individual pipeline runs and block runs when the same pipeline has been run (re-ran) multiple times.
- Originally added in https://github.com/mage-ai/mage-ai/pull/1530 but reverted until tags were added to additional logs in https://github.com/mage-ai/mage-ai/pull/1676.
Only logs displayed for a particular run instead of all logs included in other re-runs:
> [jk]  Add back run log filter

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- Position new code blocks directly after block where it was added instead of always at the bottom.
- Scroll newly added code block into view (including code blocks added from existing files).
- Clicking on code block header will select that block (previously had to click on the body to select the block).
> [jk] Improve UX for newly added code blocks

- mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
- Pipeline runs page was showing an infinite spinner if the trigger (pipeline schedule) had been deleted, so this PR checks if the trigger exists.
- Local
cc:
> [jk] Only show spinner for runs with triggers that exist

- mage_ai/frontend/components/DependencyGraph/index.tsx
- Only allow deletion of edges (dependencies between nodes in dependency graph) in the Pipeline Editor page.
- Local
> [jk] Disable deleting dependency on non-pipeline-editor page

- mage_ai/orchestration/db/models.py
- mage_ai/orchestration/pipeline_scheduler.py
- mage_ai/server/api/orchestration.py
* Batch update block run status to improve perf.
* Batch update block run status to CANCELLED when cancelling pipeline run
* Batch update block run status to INITIAL when retrying pipeline run
* Not run scheduler for same pipeline run twice. API server and Scheduler don't share the same execution_process_manager. They could run the pipeline run at the same time. Thus, don't schedule pipeline run in API server.
tested locally
cc:
> [xy] Batch update block run status to improve perf.

- docs/design/data-loading.mdx
- mage_ai/io/azure_blob_storage.py
- mage_ai/io/base.py
- mage_ai/io/bigquery.py
- mage_ai/io/google_cloud_storage.py
- mage_ai/io/postgres.py
- mage_ai/io/redshift.py
- mage_ai/io/s3.py
- mage_ai/io/snowflake.py
Update the documentation for the **default row limit when loading data**. Increased it from 100,000 to 10,000,000 due to changes in #779.
> [jl] Update default query limit in docs

- mage_ai/data_preparation/logging/logger_manager.py
- mage_ai/data_preparation/logging/s3_logger_manager.py
- mage_ai/data_preparation/models/file.py
- mage_ai/orchestration/db/models.py
- mage_ai/server/api/logs.py
- mage_ai/server/api/orchestration.py
* Speed up `/api/pipeline_runs` endpoint by using `selectinload` instead of `joinedload` (reduce time by 30%~50%)
* Speed up `/api/logs` endpoint
tested locally
Before updating the logs endpoint
After updating the logs endpoint
cc:
> [xy] Speed up more API endpoints

- mage_ai/frontend/components/PipelineDetailPage/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runs.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runtime.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/monitors/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx
Reverts mage-ai/mage-ai#1735
There're frontend errors if we don't return block content.
> Revert "[xy] Fix url params include_content and include_outputs"

- mage_ai/data_integrations/utils/config.py
- mage_ai/server/server.py
- mage_ai/services/aws/secrets_manager/secrets_manager.py
- requirements.txt
- setup.py
Add `secret_var` variable. Syntax is `"secret_var('secret_id', True/False)"`. Right now it will only check AWS secret manager. I was wondering if we should name the variable like `aws_secret_var` to specify AWS because there may be other secret managers in the future.
I also added caching because every request to the API costs money, but you can fetch directly from AWS with by setting the second argument as `False`. 
> [dy] Add secret var

- mage_integrations/mage_integrations/sources/amazon_s3/README.md
- mage_integrations/mage_integrations/sources/amazon_s3/__init__.py
Multi stream configs are stored in key `table_configs`
Example table configs
```
"table_configs": [
{
"prefix": "test/",
"search_pattern": ".*?/.*?test_table\\.csv$",
"table_name": "table_1"
},
{
"prefix": "test/",
"search_pattern": ".*?/.*?test_table\\.csv$",
"table_name": "table_2"
}
]
```
tested locally
cc:
> [xy] Support multi streams in s3 source.

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- Scratchpad blocks were not being positioned immediately after the block where it was added due to the priority being excluded, so this PR includes the priority even for scratchpad blocks.
> [jk] Include priority when adding all blocks

- mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- Maintain order of new blocks when using name change modal.
- Fix issue with transformer block not appearing between loader and exporter blocks in integration pipelines.
Add blocks in batch pipeline:
Add transformer block in integration pipeline:
cc:
> [jk] Pass props when using name change modal

- mage_ai/frontend/components/CodeBlock/index.style.tsx
- mage_ai/frontend/components/CodeBlock/index.tsx
- Fix z-index issues with code block dropdowns and dividers.
Before:
After:
> [jk] Fix partially covered AddNewBlocks buttons between code blocks

- mage_ai/frontend/components/DependencyGraph/index.tsx
- mage_ai/frontend/components/DependencyGraph/utils.ts
- mage_ai/frontend/components/Sidekick/index.tsx
- Disabled the drag and drop to create dependencies feature on integration pipelines since it is not necessary with only 1 loader, 1 exporter, and max 1 transformer block.
- Hide the ports on other blocks when a dependency drag is active (since there are no other ports, it should be more intuitive to simply drop the dependency line on another block).
> [jk] Improve drag and drop dependencies

- mage_ai/server/constants.py
- setup.py
- Bump to version 0.7.73
- Includes https://github.com/mage-ai/mage-ai/pull/1784
> [jk] Bump to version 0.7.73

- mage_integrations/mage_integrations/destinations/snowflake/__init__.py
- mage_integrations/mage_integrations/utils/strings.py
The queries with arrays in them were failing because the strings weren't being enclosed by quotes. Now the syntax should look something like this `('value1', 'value2', ...)`
tested locally
> [dy] Update snowflake convert array

- mage_ai/server/constants.py
- setup.py
- Bump to version 0.7.74
- Includes FE PRs: https://github.com/mage-ai/mage-ai/pull/1790 and https://github.com/mage-ai/mage-ai/pull/1794
> [jk] Bump to v0.7.74

- mage_ai/io/azure_blob_storage.py
- mage_ai/io/base.py
- mage_ai/io/bigquery.py
- mage_ai/io/config.py
- mage_ai/io/export_utils.py
- mage_ai/io/file.py
- mage_ai/io/google_cloud_storage.py
- mage_ai/io/io_config.py
- mage_ai/io/mysql.py
- mage_ai/io/postgres.py
- mage_ai/io/redshift.py
- mage_ai/io/s3.py
- mage_ai/io/snowflake.py
- mage_ai/io/sql.py
Updates type annotations of IO modules. Specifically targetted arguments that:
1. Had no type annotation (e.g. `def foo(a): ...`)
2. Had a default value that was not included in the list of expected types (e.g. `def bar(a: str = None): ...`)
Tested locally following the contribution guideline.
> Update type hints of IO modules

- mage_ai/tests/base_test.py
- mage_ai/tests/orchestration/db/test_models.py
- requirements.txt
Restrict sqlalchemy version. SQLAlchemy 2.0.0 was released 2 hours ago, which broke our unit tests. Thus, add one more constraint to not upgrade SQLAlchemy to above 2.0.0.
unit tests
cc:
> [xy] Restrict sqlalchemy version.

- setup.py
Added a missing comma that would beak the installation of Mage.
After #1814, installing Mage with `pip` would fail due to a missing comma in the list of `postgres` extra requirements.
1. Uninstall Mage from your environment
2. Install it from the latest GitHub distribution `pip install git+https://github.com/mage-ai/mage-ai`
Installed it from source. The installation ran smoothly.
> Fix bug when installing Mage

- mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
- mage_ai/frontend/interfaces/IntegrationSourceType.ts
- When clicking "Apply (to all streams)" for a column's bookmark property in the data integration schema table, only apply it to other streams if that stream's bookmark column is a valid replication key.
- When clicking "Apply (to all streams)" for a column's unique property in the data integration schema table, only apply it to other streams if that stream's unique column is a valid key property.
- Fix formatting in "Unique conflict method" tooltip when several columns are selected.
Unique and bookmark prop APPLIED to other streams:
Unique and bookmark prop NOT APPLIED to other streams:
> [jk] Apply bookmark property only to relevant streams

- .github/workflows/build_and_test.yml
- mage_integrations/mage_integrations/connections/utils/google.py
- mage_integrations/mage_integrations/tests/sources/bigquery/test_bigquery.py
- mage_integrations/mage_integrations/tests/sources/mysql/test_mysql.py
- mage_integrations/mage_integrations/tests/sources/sql/test_base.py
- mage_integrations/mage_integrations/tests/sources/test_base.py
- mage_integrations/requirements.txt
- Include mage integrations unit tests as part of GitHub Actions
- Runs unit tests in `mage-ai/mage_integrations/mage_integrations/tests` directory.
> [jk] Add mage integrations unit tests to GitHub Actions

- mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
- mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
- mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/interfaces/OSType.ts
- mage_ai/frontend/utils/os.ts
- Add `ctrl+s` keyboard shortcut for saving pipeline in Pipeline Editor.
- Display appropriate keyboard shortcut depending on user's OS.
> [jk] Windows keyboard shortcuts

- mage_integrations/mage_integrations/tests/sources/test_base.py
- Fix unit test that was inconsistently throwing an error (though passed most of the time).
- Reran `test_sync` unit test many times in order for the error to appear. Reran test many times after updating it, and the error stopped appearing.
cc:
> [jk] Add return value to mock

- mage_integrations/mage_integrations/sources/sql/base.py
- mage_integrations/mage_integrations/transformers/utils.py
- mage_integrations/mage_integrations/utils/schema_helpers.py
Filter order_by_columns by column types. Some column types can't be used as order by columns.
```
Error while executing query: 400 ORDER BY does not support expressions of type ARRAY<STRUCT<type STRING, id INT64, role STRING>> at [11:80]
```
tested locally
cc:
> [xy] Filter order_by_columns by column types.

- mage_ai/cli/main.py
- mage_ai/cli/utils.py
- mage_ai/data_preparation/executors/block_executor.py
- mage_ai/data_preparation/executors/executor_factory.py
- mage_ai/data_preparation/repo_manager.py
- mage_ai/server/server.py
- mage_ai/tests/cli/test_init.py
- mage_ai/tests/cli/test_run.py
- mage_ai/tests/cli/test_start.py
- requirements.txt
- setup.py
Migrate the CLI to [Typer](https://github.com/tiangolo/typer) in order to:
1. Make future development of the CLI easier
2. Allow growth in complexity
3. Improve user interaction via better formatting
I'll write them in future commits if the idea is approved
@tommydangerous is this in line with the company's goals?
> Migrate CLI to Typer

- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.style.tsx
- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
- See title.
Before:
After (No more button overlap):
> [jk] Fix z-index issue with AddNewBlocks buttons

- mage_integrations/requirements.txt
Upgrade deltalake library to 0.7.0
Upgrading the library fixes the error
```
Error performing complete multipart request: response error “
<Error>
<Code>EntityTooSmall</Code>
<Message>Your proposed upload is smaller than the minimum allowed size</Message>
<ProposedSize>5112949</ProposedSize>
<MinSizeAllowed>5242880</MinSizeAllowed>
<PartNumber>1</PartNumber>
<ETag>fdd3a4cad7deb06d2273ee18baed284b</ETag>
<RequestId>VVXWA5N53JEJNE3R</RequestId>
<HostId>xTNhBnJhZv0rLpc3LLrSILS6cyzfzM5qr8l8G2F7KtPYoVqqq6kCIj47cvlU6W/sW9GrZZsEckg=</HostId>
</Error>“, after 0 retries: HTTP status client error (400 Bad Request) for url
```
tested locally
cc:
> [xy] Upgrade deltalake library to 0.7.0

- mage_ai/frontend/components/Sidekick/utils.ts
- mage_ai/frontend/components/Triggers/RunPipelinePopup/index.style.ts
- mage_ai/frontend/components/Triggers/RunPipelinePopup/index.tsx
- mage_ai/frontend/oracle/components/Panel/index.tsx
- mage_ai/frontend/oracle/elements/Button/index.tsx
- mage_ai/frontend/oracle/elements/Inputs/TextArea.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
- Add modal for overwriting runtime variables when clicking "Run pipeline now" button.
- If no global variables exist, the modal will not appear and the pipeline will be run immediately after clicking the "Run pipeline now" button.
Run pipeline immediately (no modal appears since no runtime variables):
Overwrite variables:
> [jk] Overwrite runtime variables when "running pipeline now"

- mage_ai/data_preparation/models/variable.py
Fix dtype for saving dataframe to parquet. Not convert type if the dtype is not object.
tested locally
cc:
> [xy] Fix dtype for saving dataframe to parquet.

- mage_ai/frontend/components/Terminal/index.tsx
- mage_ai/frontend/utils/hooks/keyboardShortcuts/constants.ts
- Support copy/paste in Mage terminal in chrome, safari, and firefox browsers.
- Users need to allow permissions for clipboard paste in the terminal. If permissions are not granted, an alert will appear telling users how they can enable it.
- Allow paste with `ctrl+V` keyboard shortcut (in addition to `cmd+V`) so Windows users can paste. Windows users can copy selected text in the terminal by selecting "Copy" in the context menu. The `ctrl+C` keyboard shortcut is reserved for interrupting the kernel.
Chrome:
Safari:
Firefox:
> [jk] Allow copy/paste in Mage terminal

- mage_ai/frontend/components/Dashboard/index.tsx
- Fix issue with width of `after` element taking up whole screen.
Bug:
Fix:
cc:
> [jk] Revert afterWidth change

- mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/__init__.py
Fix N+1 query in facebook ads source adsets stream.
tested locally
cc:
> [xy] Fix N+1 query in facebook ads source adsets stream.

- mage_ai/frontend/components/shared/Header/index.tsx
- The header flyout menu was cutoff when aligned left, so this aligns it in the other direction.
> [jk] Align Header flyout menu right

- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/components/Terminal/index.tsx
- mage_ai/frontend/context/Keyboard/index.tsx
- mage_ai/frontend/pages/_app.tsx
- mage_ai/frontend/utils/hooks/keyboardShortcuts/useGlobalKeyboardShortcuts.tsx
- Add properties to the keyboard context so that we can customize which keyboard shortcuts are available when focused on a specific component.
- When focused on the Terminal, disable keyboard shortcuts from the PipelineDetail page (i.e. `cmd+s` or `ctrl+s` to save).
cc:
> [jk] Disable other keyboard shortcuts 

- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/interfaces/DataProviderType.ts
- mage_ai/server/api/data_providers.py
- User can choose MySQL as a connection for the SQL block in their pipeline.
- Hide `schema` input in code block if MySQL is selected since it is not necessary for MySQL connections (but required for other SQL connections).
- Add reference to [docs](https://docs.mage.ai/guides/sql-blocks) in comment.
cc:
> [jk] Add SQL block from MySQL to pipeline

- mage_ai/server/constants.py
- setup.py
- Bump to v0.7.95
- Includes https://github.com/mage-ai/mage-ai/pull/1984 and https://github.com/mage-ai/mage-ai/pull/1977
> [jk] Bump to v0.7.95

- mage_integrations/mage_integrations/connections/couchbase/__init__.py
- mage_integrations/mage_integrations/sources/couchbase/README.md
- mage_integrations/mage_integrations/sources/couchbase/__init__.py
- mage_integrations/mage_integrations/sources/couchbase/templates/config.json
Change `host` to `connection_string` because the prefix can either be `couchbase` or `couchbases` based on the cluster security.
tested locally
> [dy] Update config

- mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
- mage_ai/frontend/components/IntegrationPipeline/index.tsx
- mage_integrations/mage_integrations/utils/schema_helpers.py
- Make all columns in schema tables optional.
- Ran pipeline with `automatic` inclusion column deselected and confirmed it was not included when migrating the data from the original table.
Before (contains selected and disabled column):
After (all columns can be deselected):
> [jk] All schema columns optional

- mage_ai/server/constants.py
- setup.py
- Bump to version 0.7.101
- https://github.com/mage-ai/mage-ai/pull/2015
- https://github.com/mage-ai/mage-ai/pull/2018
- https://github.com/mage-ai/mage-ai/pull/2022
N/A
> [jk] Bump to v0.7.101

- mage_ai/frontend/components/PipelineRun/shared/buildTableSidekick.tsx
- mage_ai/frontend/components/Sidekick/index.tsx
- Hide blank area in code block output column headers if block analysis is not available.
> [jk] Hide column header analysis output

- mage_ai/frontend/pages/pipeline-runs/index.tsx
- Fix "circular structure in getInitialProps" error on pipeline runs page.
- Confirmed no error upon refreshing pipeline runs page.
> [jk] Fix error when refreshing Pipeline Runs page

- mage_integrations/mage_integrations/destinations/bigquery/utils.py
Fix error
```
GigQuery process failed with error 400 Syntax error: Illegal escape sequence:
Unicode value \ud83d is invalid at [1:180360]
```
Remove emoji code in bigquery quey.
Reference: https://stackoverflow.com/questions/33404752/removing-emojis-from-a-string-in-python
tested locally
cc:
> [xy] Fix encode emoji.

- mage_ai/frontend/components/PipelineDetail/FileTabs/index.tsx
- mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
- mage_ai/frontend/components/PipelineDetail/index.style.tsx
- The header for the Pipeline Editor main content was hidden for Firefox browsers specifically (which prevented users from being able to change their pipeline names on Firefox), so this PR fixes that. 
Firefox:
Chrome:
Safari:
> [jk] Show Pipeline Editor main content header on Firefox

- docs/mint.json
- docs/production/observability/datadog.mdx
- mage_ai/services/datadog/__init__.py
- requirements.txt
Add some basic datadog logging methods. Not entirely sure what the difference is between using the api and the `statsd` library.
tested locally
> [dy] Add initial datadog logging library

- mage_ai/frontend/components/Triggers/Edit/index.tsx
- mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
- mage_ai/frontend/oracle/elements/Inputs/Select.tsx
- mage_ai/frontend/utils/os.ts
- The coloring was off for the Frequency dropdown menu on the Trigger edit page for Windows users. The dropdown items had white font against a white background after an item was selected and the dropdown reopened (the items were visible initially when no item was selected). This PR fixes the coloring for Select dropdowns on Windows.
Before (dropdown items not visible):
After:
> [jk] Dropdown formatting for Windows

- mage_ai/api/policies/BackfillPolicy.py
- mage_ai/api/presenters/BackfillPresenter.py
- mage_ai/api/resources/BackfillResource.py
- mage_ai/frontend/components/Backfills/Detail/index.tsx
- mage_ai/frontend/components/Backfills/Edit/constants.ts
- mage_ai/frontend/components/Backfills/Edit/index.tsx
- mage_ai/frontend/components/Backfills/Table/index.tsx
- mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
- mage_ai/frontend/interfaces/BackfillType.ts
- mage_ai/frontend/oracle/elements/Button/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/backfills/[...slug].tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/backfills/index.tsx
- mage_ai/orchestration/backfills/service.py
- mage_ai/orchestration/pipeline_scheduler.py
- Show preview of total pipeline runs created and timestamps of pipeline runs that will be created before starting backfill.
- Misc UX improvements with the backfills pages (e.g. disabling or hiding irrelevant items depending on backfill status, updating backfill table columns that previously weren't updating as needed)
Preview runs:
Update columns in backfill table:
> [jk] Backfill preview runs

- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/components/Sidekick/GlobalVariables/Secrets.tsx
- mage_ai/frontend/components/Sidekick/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- See title.
Before - shortcuts NOT disabled:
After - shortcuts disabled on input focus:
> [jk] Disable keyboard shortcuts while focused in Sidekick inputs

- docs/guides/data-integration-pipeline.mdx
- mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
- mage_ai/frontend/oracle/elements/Inputs/ToggleSwitch.tsx
- Fixed bug where users could edit bookmark values before selecting destination. A destination must be selected first so we have the folder path for where to save the updated bookmark values.
- Updated documentation for editing bookmark values. https://docs.mage.ai/guides/data-integration-pipeline#editing-bookmark-property-values
- Locally
> [jk]  Require destination to edit bookmarks / Update docs

- mage_ai/data_preparation/models/block/dbt/__init__.py
Sometimes, the run results JSON doesn’t exist. Loading it to print out will fail the block run and fail the pipeline. We want to prevent failing the pipeline.
> [td] Don’t error if run results JSON does not exist

- mage_integrations/mage_integrations/destinations/snowflake/__init__.py
- mage_integrations/mage_integrations/destinations/sql/utils.py
Fix Snowflake alter table command.
Fix error:
```
syntax error line 1 at position 69 unexpected 'COLUMN'.
```
https://stephenallwright.com/snowflake-add-multiple-columns/
to be tested
cc:
> [xy] Fix Snowflake alter table command.

- mage_ai/data_preparation/models/utils.py
- mage_ai/server/utils/output_display.py
- Fixes `OverflowError: Overlong 2 byte UTF-8 sequence detected when encoding string`
- Fixes `ObjectId` not being serializable
> [td] Fix MongoDB type and overflow errors

- mage_ai/data_preparation/models/pipeline.py
- mage_ai/tests/data_preparation/models/test_pipeline.py
- When renaming a pipeline, transfer existing triggers, backfills, pipeline runs, and block runs (blocks already transferred currently).
- Prevent users from renaming pipeline to a name already in use by another pipeline.
- Added unit tests.
- Renaming a pipeline with an existing pipeline name:
- Renaming pipeline:
> [jk] Migrate additional resources when pipeline renamed

- mage_ai/api/policies/BackfillPolicy.py
- mage_ai/api/policies/BasePolicy.py
- mage_ai/api/policies/BlockPolicy.py
- mage_ai/api/policies/FileContentPolicy.py
- mage_ai/api/policies/FilePolicy.py
- mage_ai/api/policies/KernelPolicy.py
- mage_ai/api/policies/PipelinePolicy.py
- mage_ai/api/policies/SecretPolicy.py
- mage_ai/api/policies/VariablePolicy.py
- mage_ai/api/policies/WidgetPolicy.py
- mage_ai/api/utils.py
- mage_ai/server/websocket_server.py
- mage_ai/settings/__init__.py
- mage_ai/tests/api/operations/test_operations.py
Support disabling edit access for endpoints related to the notebook. I had to make some changes to the authentication middleware to support the new policy condition.
tested locally. trying to perform an edit action will lead to an error pop up
> [dy] Add env var to disable edit access

- mage_integrations/requirements.txt
- requirements.txt
- setup.py
Update psycopg2 package to fix error `SCRAM authentication requires libpq version 10 or above.`
Ref: https://stackoverflow.com/questions/62807717/how-can-i-solve-postgresql-scram-authentication-problem
tested locally
cc:
> [xy] Update psycopg2 package.

- mage_ai/frontend/components/Terminal/index.tsx
- Paste error was occurring in Firefox browsers when users didn't have certain browser settings enabled. Added details to alert to inform users how to enable these settings.
- Was able to recreate user's error (`navigator.clipboard.read is not a function`) and resolved it.
- New alert: ![image](https://user-images.githubusercontent.com/78053898/224122950-fbb59d20-a4a1-4cde-be17-6c7636696585.png)
> [jk] Add more messaging around how to configure pasting

- mage_ai/orchestration/pipeline_scheduler.py
- mage_ai/tests/factory.py
- mage_ai/tests/orchestration/test_pipeline_scheduler.py
Update `allow_block_to_fail` logic for pipelines that have dynamic blocks. A block with upstream dynamic blocks will only not run if *all* of the upstream dynamic blocks failed.
tested locally. added some dynamic block unit tests, but it's hard to mock everything that happens for the dynamic blocks :(
> [dy] Update block run status logic

- mage_ai/data_preparation/models/variable.py
Issue: Failure to load s3 parquet file
Root Cause: dataframe loaded contains columns that are of `numpy.ndarray` type, resulting in the following error
```
File /usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/variable.py:399, in Variable.__write_parquet(self, data)
396         pass
398 if coltype.__module__ == np.__name__:
--> 399     column_types[c] = type(series_non_null.iloc[0].item()).__name__
400 else:
401     column_types[c] = coltype.__name__
ValueError: can only convert an array of size 1 to a Python scalar
```
fix: add conditional checking of `numpy.ndarray` column type
local tests
> fix failure to obtain numpy array type from dataframe

- mage_ai/server/websocket_server.py
- mage_ai/settings/__init__.py
- mage_ai/shared/security.py
- mage_ai/tests/shared/test_security.py
For env var values that have length larger than 5, we mask the values with `***` in the terminal and block output.
Setting `HIDE_ENV_VAR_VALUES` to 1 (default value) to enable this feature. Setting it to 0 to disable the feature.
tested locally
cc:
> [xy] Mask env var values with stars in terminal output

- mage_ai/data_preparation/repo_manager.py
Fix repo creation with empty MAGE_DATA_DIR_ENV_VAR str.
tested locally
cc:
> [xy] Fix repo creation with empty MAGE_DATA_DIR_ENV_VAR str.

- mage_ai/data_preparation/logging/logger_manager.py
Use RotatingFileHandler for logs so that the log file doesn't get very big.
https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler
tested locally
cc:
> [xy] Use RotatingFileHandler for logs.

- mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
- When clicking `Execute pipeline` in Pipeline Editor, the output is limited to rendering 100 messages to mitigate app performance issues.
Local
> [jk] Truncate messages in pipeline execution to prevent app freezing

- README.md
The airflow and dbt tutorial links were switched
cc:
> Fix tutorial links in README

- mage_ai/server/utils/output_display.py
- mage_ai/server/websocket_server.py
Add some regex to remove the `Block` specific parts of the stack trace to reduce the amount of useless information in the output. It works the best on standard blocks, and doesn't completely remove the mage specific error logging for sql and dbt blocks, but it does reduce the clutter.
tested on normal blocks, sql blocks, and dbt blocks. 
for normal blocks:
before:
after: 
> [dy] Update notebook error display

- mage_integrations/mage_integrations/destinations/snowflake/__init__.py
* Fix Snowflake destination column comparison when alter table
* Use uppercase if disable_double_quotes is True
* Use correct `clean_column_name` method
* Escape single quote when converting array values.
tested locally
cc:
> [xy] Fix Snowflake destination column comparison and escape quote

- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/CodeEditor/index.tsx
- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- Update code editor keyboard shortcut (i.e. execute code) block dependencies when they change. There was an issue with the original block being run with outdated upstream dependencies when using the code editor keyboard shortcut (not to be confused with the custom app keyboard shortcuts).
Before (upstream dependency not updated when running a block, so block is run without new upstream dependency and is removed):
After (blocks are run with upstream dependencies as expected):
> [jk] Fix disappearing upstream connections when running block in editor

- mage_integrations/mage_integrations/sources/outreach/__init__.py
- mage_integrations/mage_integrations/sources/outreach/tap_outreach/client.py
Fix Outreach rate limit issue
Error
```
File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/outreach/tap_outreach/client.py\", line 62, in sleep_for_reset_period
int(response.headers['x-ratelimit-reset']))
File \"/usr/local/lib/python3.10/site-packages/requests/structures.py\", line 54, in __getitem__
return self._store[key.lower()][1]
KeyError: 'x-ratelimit-reset'
```
tested with outreach source
cc:
> [xy] Fix Outreach rate limit issue

- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
- mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
- Fix issue with SQL block content being used for new non-SQL blocks.
- Left-align items in flyout menu when adding new custom block.
> [jk] Use correct content for new non-SQL block added between blocks

- mage_ai/frontend/components/DependencyGraph/constants.ts
- mage_ai/frontend/components/DependencyGraph/index.tsx
- Increase canvas size for dependency graph to allow 60+ blocks to be visible.
> [jk] Increase dependency graph canvas size

- mage_ai/frontend/components/Monitor/constants.ts
- mage_ai/frontend/components/charts/BarStack.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runs.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/monitors/index.tsx
- Tooltips on the very right of the Pipeline Runs and Block Runs charts would cause a horizontal overflow and not be readable as users hovered off of the bar. This PR centers the tooltips to stay within view.
> [jk] Fix tooltip spacing in runs charts

- mage_ai/server/constants.py
- setup.py
- Bump to v0.8.28
- Includes:
- https://github.com/mage-ai/mage-ai/pull/2229
- https://github.com/mage-ai/mage-ai/pull/2235
- https://github.com/mage-ai/mage-ai/pull/2242
- https://github.com/mage-ai/mage-ai/pull/2231
- https://github.com/mage-ai/mage-ai/pull/2244
- https://github.com/mage-ai/mage-ai/pull/2246
- https://github.com/mage-ai/mage-ai/pull/2247
- https://github.com/mage-ai/mage-ai/pull/2252
- https://github.com/mage-ai/mage-ai/pull/2253
- https://github.com/mage-ai/mage-ai/pull/2254
N/A
> [jk] Bump to v0.8.28

- mage_ai/frontend/components/DependencyGraph/constants.ts
- Increase canvas size of dependency graph to accommodate longer block names.
- Local
> [jk] Accommodate longer block names in dep graph by increasing canvas size further

- mage_ai/server/server.py
When the app starts listening in the defined `host:port`, a new tab on the default browser is opened.
Solves #2233. It doesn't work with Docker, and the explanation is in the issue's comments.
Tested locally with MacOS/Chrome, but since it's a standard library from Python, it shouldn't have any issues with other OS/browser.
> Automatically open app in a new tab using default browser

- mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
- mage_ai/frontend/utils/date.ts
- Fix issue with logs not appearing for timestamp filters.
- Use now timestamp as execution date for pipeline re-runs. Previously, the execution date of the original pipeline run was used when re-running a pipeline run, which caused the log timestamp filters to use only the original pipeline run's date even on reruns that occurred later.
Before (original run execution date used on re-runs; past hour/day logs don't appear even for a rerun that just happened):
After (now timestamp used for execution date of re-run; past hour/day logs appear immediately for new rerun):
> [jk] Fix execution date used for re-run pipeline runs

- mage_integrations/mage_integrations/destinations/amazon_s3/README.md
- mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py
- mage_integrations/mage_integrations/destinations/amazon_s3/templates/config.json
Support using date partition for s3 destination.
| Key | Description | Sample value
| --- | --- | --- |
| `date_partition_format` | (Optional) The datetime format of the partition. If it's null, files will not be saved into paratitions. | `null`, `%Y%m%d`, `%Y%m%dT%H` |
tested locally
cc:
> [xy] Support using date partition for s3 destination.

- mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
- mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
- mage_ai/frontend/components/Sidekick/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- mage_ai/server/execution_manager.py
- mage_ai/server/websocket_server.py
- Close streaming pipeline on refresh or page change.
- Add `Running status` button to let user check if the pipeline is currently running or not.
- Hide `Pipeline execution` section in standard/batch pipelines.
> [jk] Fix streaming pipeline not closing

- mage_integrations/mage_integrations/destinations/bigquery/utils.py
Fix bigquery replace str.
Error
```
File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/bigquery/utils.py\", line 19, in replace_single_quotes_with_double
v = re.sub(r'(\\\\ud83d\\\\ude[0-4][0-f])|(\\\\ud83c\\\\udf[0-f][0-f])|(\\\\ud83d\\\\u[0-d][-d][0-f][0-f]])|(\\\\ud83d\\\\ude[8-f][0-f])|(\\\\ud83c\\\\udd[e-f][0-f])|(\\\\ud83e\\\\udd[1-f][0-f])', '', v)
File \"/usr/local/lib/python3.10/re.py\", line 209, in sub
return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
", "caller": "BigQuery", "level": "EXCEPTION", "timestamp": 1679852652, "uuid": "40dda5aac4f743a0b378ba7b9260d63a", "type": "LOG"}
```
tested locally
cc:
> [xy] Fix bigquery replace str.

- mage_ai/data_preparation/models/file.py
When trying to create a file in a nested folder, if the folder doesn’t exist, create it.
> [td] Create dir if it doesnt exist for dbt files

- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/CodeEditor/index.tsx
- mage_ai/frontend/components/TripleLayout/index.tsx
- See "Before" and "After" under `Tests`.
Before - The code block scrolls out of view when a block inside the code block editor is folded/collapsed and user clicks underneath it:
After - The block inside the code block editor is folded but does not scroll out of focus when clicking beneath it. Scroll position stays in place as expected:
> [jk] Fix scrolling issue when code block is folded inside code editor

- mage_ai/orchestration/notification/config.py
- mage_ai/orchestration/notification/sender.py
- mage_ai/services/google_chat/config.py
- mage_ai/services/google_chat/google_chat.py
- mage_ai/tests/orchestration/notification/constants.py
- mage_ai/tests/orchestration/notification/test_config.py
Added option to send an alert to Google Chat in the same way as Teams/Slack using a webhook.
Tested a successful and failing flow. Both runs produced a messages in a Google Chat room.
> Add alerting option for Google Chat

- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- mage_ai/frontend/utils/string.ts
- Fix issue with sample data not rendering in Sidekick for streams that had capital letters and/or spaces in their names.
cc:
> [jk] Show sample data for streams with non-clean names

- mage_ai/data_preparation/models/pipeline.py
When saving a pipeline:
- If the content that is about to be saved to a YAML file is invalid YAML, raise an exception
- If the block UUIDs from the current pipeline and the content that is about to be saved differs, raise an exception
> [td] Prevent saving bad content for pipelines

- mage_ai/data_preparation/models/block/utils.py
- Don’t require metadata for dynamic blocks
> [td] Don’t require metadata for dynamic blocks

- mage_ai/api/resources/PipelineRunResource.py
- mage_ai/data_preparation/models/pipeline.py
- mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
- mage_ai/frontend/pages/pipeline-runs/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/syncs/index.tsx
- mage_ai/frontend/utils/models/pipelineRun.ts
- mage_ai/orchestration/pipeline_scheduler.py
- If a pipeline is deleted while a pipeline run is still running, users weren't able to cancel those pipeline runs in the UI, so this PR allows users to cancel pipeline runs even if their related pipeline was deleted.
Before (cannot cancel running pipeline run):
After (can cancel running run, but not retry because the pipeline no longer exists):
> [jk] Cancel pipeline runs without associated pipelines

- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/server/constants.py
- setup.py
- Don’t save block configuration until finish typing for 1 second using debounce
- https://github.com/mage-ai/mage-ai/pull/2343
- https://github.com/mage-ai/mage-ai/pull/2342
- https://github.com/mage-ai/mage-ai/pull/2341
> [td] 0.8.40

- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/FileEditor/index.tsx
- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/components/Sidekick/GlobalVariables/index.tsx
- mage_ai/frontend/components/Sidekick/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- Disable keyboard shortcuts while in File Editor for individual file.
- The `allowCodeBlockShortcuts` prop was added so users can still run blocks with keyboard shortcut (CMD + ENTER) when clicking on a node in the Sidekick dependency graph and running it with shortcut.
Before - shortcuts enabled on file editor:
After - shortcuts disabled on file editor:
> [jk] Disable shortcuts from file editor

- mage_ai/data_preparation/models/pipelines/integration_pipeline.py
- mage_ai/frontend/components/IntegrationPipeline/SelectStreams/index.tsx
- mage_ai/frontend/components/IntegrationPipeline/index.tsx
- mage_ai/frontend/oracle/elements/Checkbox/index.tsx
- Show more descriptive error (instead of `{}`) when a stream that was previously selected may have been deleted or renamed.
- If a previously selected stream was deleted or renamed, it will still appear in the `SelectStreams` modal but will automatically be deselected and indicate that the stream is no longer available in red font. User needs to click "Confirm" to remove the deleted stream from the schema.
> [jk] Load sample data from deleted stream

- mage_ai/api/resources/BlockResource.py
- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/data_preparation/models/block/errors.py
- mage_ai/data_preparation/models/pipeline.py
- mage_ai/frontend/components/FileBrowser/index.tsx
- mage_ai/frontend/oracle/components/PopupMenu/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- mage_ai/tests/data_preparation/models/test_block.py
I added another modal that pops up when a user tries to delete a block file that has downstream dependencies. They can override the safeguards we have in place for blocks with downstream dependencies and choose to overwrite them.
unit tests and local testing
cc:
> [dy] Allow users to force delete block file

- .gitignore
- scripts/dev.sh
- scripts/init.sh
Init file `./scripts/init.sh` will not work with docker-compose version greater than 2.0, made changes to make it compatible with latest docker-compose version
Ran init script with docker-compose versions greater than and less than 2.0
cc:
> init file update to support docker latest versions

- mage_ai/api/resources/BlockResource.py
- mage_ai/frontend/components/FileBrowser/utils.ts
- mage_ai/frontend/utils/string.ts
Use the last index of `parts` to determine the extension, and use the first n-1 elements of `parts` to determine the block uuid. For a block named `block.py.sql`, the extension is `.sql`, and the block uuid would be `block.py`.
tested locally
> [dy] Fix dbt file delete error

- mage_ai/data_preparation/models/block/dbt/__init__.py
- mage_ai/data_preparation/models/block/dbt/utils/__init__.py
- Support +schema in dbt profile
- Don’t store entire dbt model output to disk unless there is at least 1 non-dbt model as a downstream block
> [td] Fix dbt staging and dbt data saving

- mage_ai/server/constants.py
- setup.py
- https://github.com/mage-ai/mage-ai/pull/2392
- https://github.com/mage-ai/mage-ai/pull/2393
- https://github.com/mage-ai/mage-ai/pull/2391
- Support +schema in dbt profile
- Don’t store entire dbt model output to disk unless there is at least 1 non-dbt model as a downstream block
> [td] 0.8.46

- mage_ai/data_preparation/models/block/utils.py
- mage_ai/orchestration/db/models/schedules.py
Update the logic for creating reduce block.
* If any dynamic ancestors doesn't have reduce block as the descendants, skip creating this downstream reduce block.
* If an upstream block needs to be reduced but it's not the same with the current block that's being reduced, skip the downstream reduce block creation.
* Avoid creating block runs with same block uuid
tested locally
cc:
> [xy] Update the logic for creating reduce block.

- mage_ai/io/bigquery.py
- mage_ai/io/config.py
- mage_ai/io/mssql.py
- mage_ai/io/snowflake.py
- mage_ai/io/sql.py
- mage_ai/io/trino.py
When executing a list of queries, the results of execution-only query do not need to be added to the final returned query results.
For some methods, missing return type hints are added back.
CI
cc:
@dy46 @wangxiaoyou1993 @tommydangerous
> [hw] Add return type hints for some methods

- mage_ai/cli/main.py
- mage_ai/orchestration/queue/process_queue.py
- mage_ai/settings/__init__.py
- requirements.txt
Add sentry integration to output exceptions from pipeline runs and block runs as well as from `mage run` commands. The integration can be enabled by setting the `SENTRY_DSN` environment variable.
tested locally
cc:
> [dy] Add sentry integration

- mage_ai/frontend/components/Backfills/Detail/index.tsx
- mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
- mage_ai/frontend/components/Triggers/utils.ts
- mage_ai/frontend/interfaces/BackfillType.ts
- mage_ai/frontend/interfaces/PipelineRunType.ts
- mage_ai/frontend/utils/date.ts
- Dates in the postgres metadata db (compared to the sqlite db) had an additional `+00:00` that was causing dates in the UI to be formatted incorrectly (included timezone hour difference). For example, the pg db would store a date as `2023-04-01T00:00:00+00:00`, while the sqlite db would store the date as `2023-04-01T00:00:00`.
- Updated date utility method to account for this difference and make the date format displayed in the UI consistent.
Dates using postgres db are consistent with start date and time:
Dates using sqlite db:
> [jk] Fix timezone inconsistencies between pg and sqlite metadata db pipeline run dates

- mage_ai/data_preparation/models/block/utils.py
Only skip creating downstream reduce block when there are more than two upstream dynamic block that shouldn't be reduced.
tested locally
cc:
> [xy] Another fix for dynamic block.

- docs/development/blocks/sql/trino.mdx
- mage_ai/io/config.py
- mage_ai/io/trino.py
Add support for more Trino settings:
```
catalog
host
http_headers
http_scheme
password
port
schema
session_properties
source
user
verify
```
```yaml
version: 0.1.1
default:
trino:
catalog: postgresql                       # Change this to the catalog of your choice
host: 127.0.0.1
http_headers:
X-Something: 'mage=power'
http_scheme: http
password: mage1337                        # Optional
port: 8080
schema: core_data
session_properties:                       # Optional
acc01.optimize_locality_enabled: false
optimize_hash_generation: true
source: trino-cli                         # Optional
user: admin
verify: /path/to/your/ca.crt              # Optional
```
> [td] Support more Trino settings

- docs/mint.json
This PR re-enables the feedback buttons for the documentation that were recently set to be hidden by default.
> Re-enable feedback buttons

- mage_ai/data_preparation/models/block/sql/utils/shared.py
Update block table name logic to account for the use of the `WITH` or `with` keyword.
```sql
CREATE TABLE IF NOT EXISTS april.test_with
with (parallel_workers = 1) AS
SELECT 1 AS uuid;
INSERT INTO april.test_with
SELECT *
FROM april.test_with
UNION ALL
SELECT *
FROM april.test_with;
```
> [td] Fix table names that use WITH

- mage_ai/frontend/components/Backfills/Detail/index.tsx
- Fixed issue with backfills pagination redirecting to triggers page instead of staying on backfills page.
- Added spinner when loading backfills.
> [jk] Fix backfills pagination

- mage_ai/data_preparation/templates/custom/python/default.jinja
- mage_ai/data_preparation/templates/data_exporters/default.jinja
- mage_ai/data_preparation/templates/transformers/default.jinja
- mage_ai/frontend/components/Sidekick/GlobalVariables/index.tsx
- mage_ai/tests/data_preparation/test_templates.py
- Update generic block templates for custom, transformer, and data exporter blocks so it's easier for users to pass the output from upstream blocks.
- Clarified language for block output variables in Sidekick.
> [jk] Update generic block templates

- mage_ai/api/operations/base.py
- mage_ai/api/resources/PipelineResource.py
- Error was occurring when trying to delete pyspark pipelines due to an attempt to switch kernels. For DELETE actions, we do not need to switch kernels.
Before (error when trying to delete):
After (no issues deleting same pipeline):
> [jk] Do not switch kernels when deleting pipeline

- docs/guides/streaming-pipeline.mdx
The Kafka container's default name has been changed, resulting in the failure of the 5th step ` docker ps | grep docker_kafka` returns empty. To resolve this issue, you need to specify the container_name in the configuration.
cc:
@dy46
> Update streaming pipeline documentation with kafka container name

- mage_ai/data_preparation/models/block/sql/__init__.py
- mage_ai/data_preparation/models/block/sql/trino.py
- mage_ai/data_preparation/models/block/sql/utils/shared.py
- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/interfaces/ChartBlockType.ts
If checked, upstream blocks that aren’t SQL blocks will have their data exported into a table that is uniquely named upon each block run. 
For example, `[pipeline_uuid]_[block_uuid]_[unique_timestamp]`.
> [td] Trino SQL blocks can use unique table names for exported upstream blocks

- mage_ai/server/server.py
- mage_ai/settings/__init__.py
Add `USE_UNIQUE_TERMINAL` environment variable to use a unique terminal each time instead of a shared terminal.
tested locally
cc:
> [dy] Update terminal

- mage_ai/frontend/components/Sidekick/GlobalVariables/Secrets.tsx
- Syntax for secret variable may require double quotes.
cc:
> [jk] Update secrets syntax

- mage_ai/io/trino.py
Catch this error:
```
TrinoUserError(type=USER_ERROR, name=TABLE_NOT_FOUND, message="line 1:15: Table 'hudi_ingest.etl_tmp.cwang_test_changes_yeah' does not exist", query_id=20230420_180015_34890_xnaun)
```
> [td] Catch TrinoUserError instead of internal error

- mage_ai/frontend/api/utils/url.ts
- Instead of hardcoding port 6789 for localhost, use the window location port so that a different port can be used to run Mage via Docker.
- Tested changing port locally and building local docker containers to run Mage on that port.
> [jk] Allow Mage default port on Docker to be changed

- scripts/dev.sh
Check if `docker-compose` exists before running it. If it doesn't exist, use `docker compose` instead. 
local
cc:
> [dg] Fix dev script to always use 'docker-compose' if it exists

- mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
- mage_ai/frontend/components/TripleLayout/index.tsx
- mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- Restarting or interrupting kernel will reset running blocks so spinner is not perpetually spinning.
- Fix broken overflow of browser navigation tabs (tabs scroll now).
Before - perpetual spinner:
After - Running blocks reset after restarting kernel / Interrupting kernel stops spinner:
> [jk] Fix perpetual run block spinner when restarting kernel.

- mage_ai/api/resources/PipelineResource.py
- mage_ai/data_preparation/models/pipeline.py
- mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
- mage_ai/frontend/interfaces/PipelineType.ts
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
- mage_ai/orchestration/db/models/schedules.py
- Allow all pipeline runs on a page to be selected and retried.
- Bulk retry runs not enabled for streaming pipelines.
Standard pipeline:
Integration pipeline:
cc:
> [jk] Bulk retry pipeline runs

- docs/production/configuring-production-settings/compute-resource.mdx
- mage_ai/data_preparation/executors/ecs_block_executor.py
- mage_ai/data_preparation/executors/executor_factory.py
- mage_ai/data_preparation/executors/k8s_block_executor.py
- mage_ai/data_preparation/models/constants.py
- mage_ai/data_preparation/repo_manager.py
Support setting default executor type. User can set `DEFAULT_EXECUTOR_TYPE` environment variable to select the default executor type (e.g. DEFAULT_EXECUTOR_TYPE=k8s)
For k8s executor, also provide the option to configure executor config in project's metadata.yaml
```
resource_limits:
cpu: 1000m
memory: 2048Mi
resource_requests:
cpu: 500m
memory: 1024Mi
```
tested locally
cc:
> [xy] Support setting default executor type.

- README.md
When installing `Mage` locally through `pip` or `conda`, run it a virtual environment to be safe.
Manually tested the newly added commands on a local Mac.
cc:
> [hw] Add a virtual environment when installing `Mage` locally with `pip` or `conda`

- mage_ai/data_preparation/executors/block_executor.py
- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/frontend/components/PipelineDetail/Extensions/GreatExpectations/CodeBlockExtraContent.tsx
- mage_ai/frontend/components/PipelineDetail/Extensions/GreatExpectations/index.tsx
- Support callbacks for data integrations
- Pass in stream, destination table, and whether block run is the last one
```
{'ds': '2023-04-26', 'hr': '20', 'env': 'prod', 'event': {}, 'execution_date': datetime.datetime(2023, 4, 26, 20, 28, 17, 335254, tzinfo=datetime.timezone.utc), 'execution_partition': '207/20230426T202817', 'pipeline_uuid': 'withered_violet', 'block_uuid': 'bold_shadow', 'pipeline_run': PipelineRun(id=2357, pipeline_uuid=withered_violet, execution_date=2023-04-26 20:28:17.335254+00:00), 'index': 1, 'is_last_block_run': True, 'stream': 'account_sf_v22_dev', 'destination_table': 'account_sf_v22_dev_copy'}
```
> [td] Support callbacks for data integrations

- mage_ai/data_preparation/templates/callbacks/orchestration/triggers/default.jinja
- mage_ai/data_preparation/templates/constants.py
```
from mage_ai.orchestration.triggers.api import trigger_pipeline
if 'callback' not in globals():
from mage_ai.data_preparation.decorators import callback
@callback('success')
def trigger(**kwargs):
"""
Trigger another pipeline to run.
Documentation: https://docs.mage.ai/orchestration/triggers/trigger-pipeline
"""
trigger_pipeline(
'pipeline_uuid',        # Required: enter the UUID of the pipeline to trigger
variables={},           # Optional: runtime variables for the pipeline
check_status=False,     # Optional: poll and check the status of the triggered pipeline
error_on_failure=False, # Optional: if triggered pipeline fails, raise an exception
poll_interval=60,       # Optional: check the status of triggered pipeline every N seconds
poll_timeout=None,      # Optional: raise an …
```
> [td] Callback trigger template

- mage_ai/frontend/oracle/components/Markdown/index.tsx
- mage_ai/frontend/oracle/styles/themes/dark.ts
- See title.
- Confirmed link opens new tab
-More transparent markdown block border when not focused:
> [jk] Fix markdown links and make border more transparent

- mage_integrations/mage_integrations/sources/intercom/__init__.py
Fix parsing int timestamp in intercom source.
tested locally
cc:
> [xy] Fix parsing int timestamp in intercom source.

- mage_ai/api/policies/PipelinePolicy.py
- See title.
- Updated `PipelinePolicy` to allow bulk retry runs (individual run retries were already allowed due to less strict policy in `PipelineRunPolicy`).
Before - Cannot cancel all runs or bulk retry runs:
After - Can cancel all runs and bulk retry runs:
> [jk] Allow bulk retry runs when DISABLE_NOTEBOOK_EDIT_ACCESS enabled

- mage_ai/api/policies/UserPolicy.py
- mage_ai/api/resources/UserResource.py
- mage_ai/frontend/components/settings/Dashboard/constants.ts
- mage_ai/frontend/components/users/edit/Form/index.tsx
- mage_ai/frontend/pages/settings/workspace/users/index.tsx
- mage_ai/orchestration/db/models/oauth.py
- Allow admins to view and update existing users' usernames/emails/roles/passwords (except for owners and other admins).
- Admins can only view Viewers/Editors and adjust their roles between those two.
- Admins cannot create or delete users (only owners can).
- Admins cannot make other users owners or admins (only owners can).
> [jk] Update admin abilities

- mage_ai/frontend/components/Dashboard/index.tsx
- mage_ai/frontend/components/Monitor/index.tsx
- mage_ai/frontend/components/PipelineDetailPage/index.tsx
- mage_ai/frontend/components/PipelineLayout/index.tsx
- mage_ai/frontend/components/shared/Header/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/monitors/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/settings/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/syncs/index.tsx
- The error when loading the pipeline wasn't being displayed to users after clicking a pipeline from the Dashboard and redirecting to the Triggers page. This PR makes the error popup visible with the stack trace. Also shows "Error loading pipeline" in red font in the header to make it more apparent.
- Update various pages to display error popup, including Triggers, Backfills, Logs, Monitors, Settings, and Syncs pages.
cc:
> [jk] Make pipeline error on PipelineDetailPage visible to user

- docs/development/environment-variables.mdx
- docs/production/data-sync/git.mdx
- mage_ai/data_preparation/git/__init__.py
- mage_ai/data_preparation/preferences.py
- mage_ai/data_preparation/sync/git_sync.py
Support passing in git settings as environment variables. If Mage detects git environment variables, it will try to use the environment variables to fill out the git config and to set up the git repo.
tested locally
cc:
> [dy] Pass in git settings as environment variables

- docs/mint.json
- docs/orchestration/pipeline-runs/retrying-block-runs.mdx
- mage_ai/api/policies/PipelineRunPolicy.py
- mage_ai/api/resources/PipelineRunResource.py
- mage_ai/data_preparation/models/pipeline.py
- mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
- mage_ai/frontend/components/PipelineRun/shared/buildTableSidekick.tsx
- mage_ai/frontend/interfaces/PipelineRunType.ts
- mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
- For standard python pipelines, retry block runs from a selected block. The selected block and all downstream blocks will be re-ran after clicking the `Retry from selected block` button.
- This feature is not available for other types of pipelines (e.g. streaming or integration). Streaming pipelines don't have block runs, and users can still retry from failed block runs in integration pipelines.
> [jk] Retry block runs from specific block

- mage_ai/frontend/components/DependencyGraph/index.tsx
- Show all ports on the data loader/exporter blocks. Previously, the top port for data loader blocks with no upstream blocks was not displayed, and the bottom port for data exporter blocks with no downstream blocks was not displayed.
> [jk] Show all ports for data loader and exporter blocks

- docs/tutorials/setup-dbt.mdx
Encountered the following error following the current user guide for dbt:
```
root@488dc9529cf3:/home/src# bash echo dbt-postgres > demo_project/requirements.txt
/bin/echo: /bin/echo: cannot execute binary file
```
It was caused by a wrong format for a code section in the user guide, which has been fixed in this PR.
Manually tested in the Mage terminal:
```
root@488dc9529cf3:/home/src# echo dbt-postgres > demo_project/requirements.txt
root@488dc9529cf3:/home/src# ls demo_project/requirements.txt
demo_project/requirements.txt
root@488dc9529cf3:/home/src# cat demo_project/requirements.txt
dbt-postgres
```
cc:
> [hw] Fix a format issue with a terminal bash command and update instructions based on the latest UI

- mage_ai/frontend/components/TripleLayout/index.style.tsx
- mage_ai/frontend/components/TripleLayout/index.tsx
- Set higher min widths for File Browser (before panel) and Sidekick (after panel) so they don't become hidden behind the expanding navigation buttons.
- Fix positioning of "Show sidebar" tooltip for left panel.
> [jk] Sidekick resizing

- mage_integrations/mage_integrations/destinations/bigquery/__init__.py
The batch load method expects a full table name, but it was only being passed the table name when creating the temp table to resolve unique conflicts.
tested locally
cc:
> [dy] Fix unique conflict for bigquery

- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/CodeBlock/utils.ts
- mage_ai/frontend/components/IntegrationPipeline/index.tsx
- mage_ai/frontend/components/PipelineDetail/index.tsx
- If a new block is added between two blocks, include the downstream connection.
- If a new block is added after a block that has multiple downstream blocks, the downstream connections will not be added since it is unclear which downstream connections should be made.
- Hide Add transformer block button in integration pipelines if a transformer block already exists (Mage currently only supports 1 transformer block for integration pipelines).
> [jk]  Add new block with downstream blocks connected

- mage_ai/frontend/components/Dashboard/index.style.tsx
- mage_ai/frontend/components/DependencyGraph/constants.ts
- mage_ai/frontend/components/DependencyGraph/index.style.tsx
- mage_ai/frontend/components/DependencyGraph/index.tsx
- mage_ai/frontend/components/Sidekick/Header.tsx
- mage_ai/frontend/components/Sidekick/index.style.ts
- mage_ai/frontend/components/Sidekick/index.tsx
- mage_ai/frontend/components/TripleLayout/index.style.tsx
- mage_ai/frontend/components/TripleLayout/index.tsx
- mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
- mage_ai/frontend/oracle/components/Tooltip/TooltipWrapper.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- Add buttons for zooming in/out of and resetting dependency graph.
- Added shortcut to reset dependency graph view (double-clicking anywhere on the canvas).
- Fixed positioning of left chevron icon to minimize left panel in Pipeline Editor.
> [jk] Update zoom on dependency graph

- mage_ai/api/resources/LogResource.py
- mage_ai/orchestration/db/models/schedules.py
- mage_ai/orchestration/pipeline_scheduler.py
- mage_ai/tests/orchestration/db/test_models.py
Fix race conditions for multiple runs within one second.
* Use `%Y%m%dT%H%M%S_%f` format when triggering pipeline runs from API or code
* Set the execution_partition in variables.
* If execution_partition is not in variables, fall back to `%Y%m%dT%H%M%S` format (for backward compability)
unit tests
tested locally
cc:
> [xy] Fix race conditions for multiple runs within one second.

- mage_ai/frontend/components/CodeBlock/utils.ts
If dbt block is language YAML, hide the option to add upstream dbt refs
> [td] Hide add upstream models for dbt yaml

- mage_ai/api/policies/PipelineRunPolicy.py
- mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
- Update policy to include `event_variables` when creating pipeline run.
- Default `variables` to empty object to avoid `NoneType` error.
- Local
> [jk] Update pipeline run policy

- mage_ai/data_preparation/models/widget/charts.py
- mage_ai/frontend/components/ChartBlock/index.tsx
- mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
If you manually convert a column to Python `datetime`, then the time series logic will convert that to a `numpy.datetime64`. 
Add logic in the time series chart to convert `numpy.datetime64` to `datetime`.
> [td] Fix time series parsing numpy datetime64

- requirements.txt
Lock typing extension version to fix error `TypeError: Instance and class checks can only be used with @runtime protocols`
CI
cc:
> [xy] Lock typing extension version.

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/data_preparation/repo_manager.py
- mage_ai/data_preparation/templates/main/metadata.yaml
- mage_ai/data_preparation/templates/repo/metadata.yaml
Enable custom settings for the Spark session used by PySpark. The behavior for Spark session is summarized below:
```
A custom SparkSession is created based on pipeline-level settings in `metadata.yaml`, and will be re-used for all blocks in the same Mage pipeline.
```
The following behavior is not supported with the current implementation:
```
1. Inside each block, the user creates and destroys a new custom SparkSession instance
2. User may replace the global kwargs['spark'] with a new SparkSession instance any time with a custom created new instance, and keep it till another new instance was created
```
Manually tested in a local development environment, with the following steps:
1. Initiate a new Mage pipeline with the following command in a terminal:
```
% ./scripts/init.sh …
```
> [hw] Add pipeline-level configuration settings for the Spark session

- mage_ai/frontend/api/utils/response.ts
- mage_ai/frontend/pages/pipelines/index.tsx
- The "Too many open files" error may occur on other pages outside of the Pipelines Dashboard, so this PR will guide users to the docs for resolving it in other pages of the Mage app.
- Before, the link to the docs in the error popup only appeared on the Pipelines Dashboard.
Pipeline Editor:
Triggers Page:
> [jk] Check for too many open files error whenever calling displayErrorFromReadResponse util method

- docs/dbt/run-single-model.mdx
- mage_ai/data_preparation/models/block/dbt/utils/__init__.py
- Interpolate user-defined variables (i.e. through `--vars`) with the other variables (e.g. env vars and global vars) when running a yaml dbt block.
- Variables must be formatted with json syntax (double-quotes around keys and string values). The variables object can have spaces in it and optionally be surrounded with single quotes.
- Related docs will be located at https://docs.mage.ai/dbt/run-single-model after this PR is merged.
Before (spaces not allowed in variables value and they would not be merged with the existing variables in the dbt command):
After - The variables defined in the block could be seen combined with the other vars in the output (screenshots include differently formatted vars with single quotes and without single quotes):
> [jk] Interpolate user-defined variables in dbt command

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/server/utils/output_display.py
Fix runtime and global variables not available in the keyword arguments when executing block with upstream blocks from the edit pipeline page.
> [td] Include runtime variables when executing upstream

- mage_ai/api/resources/GenericResource.py
- mage_ai/data_preparation/models/block/__init__.py
- If generic resource model isn’t a dictionary, don’t use `get` function.
- Fix kwargs none
> [td] Fix generic resource

- docs/integrations/spark-pyspark.mdx
- integrations/hadoop/Dockerfile
- integrations/hadoop/run_app_with_hadoop.sh
- mage_ai/data_preparation/models/block/__init__.py
For testing Spark sessions running on Hadoop Yarn with Mage, additional docker image setup is needed.
Manually tested the changes locally with the following procedure:
(1) In a terminal, switch to the following folder in the Mage code repository:
```
% cd integrations/hadoop/
```
(2) Build the docker image with the following command:
```
% docker build -t mage_hadoop .
```
(3) Type this command in your terminal to start Mage using docker:
```
docker run -it --name mage_hadoop -p 6789:6789 -v $(pwd):/home/src mage_hadoop \
/app/run_app_with_hadoop.sh mage start demo_project
```
(4) Change the `metadata.yaml` file in the main pipeline folder to include the following Spark settings:
```
spark_config:
app_name: 'my spark yarn app'
spark_master: 'yarn'
executor_env: {}
spark_jars: [] …
```
> [hw] Add support for a Mage docker image with a Hadoop Yarn cluster

- mage_ai/cli/main.py
- mage_ai/server/scheduler_manager.py
- mage_ai/server/server.py
- mage_ai/shared/constants.py
Support running Mage server and scheduler separately.
Run scheduler only
```
mage start project_name --instance-type scheduler
```
Run web server only
```
mage start project_name --instance-type web_server
```
Run both server and scheduler
```
mage start project_name --instance-type server_and_scheduler
```
tested locally
cc:
> [xy] Support running Mage server and scheduler separately.

- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/CodeBlock/utils.ts
- mage_ai/frontend/components/PipelineDetail/index.tsx
- When adding a new block between blocks, do not include downstream connections for standard pipelines, but include downstream connections for streaming pipelines.
- Adding block between blocks on standard pipeline:
- Adding block between blocks on streaming pipeline:
> [jk] Fix lost upstream connections when adding block between blocks

- docs/integrations/databases/Snowflake.mdx
- mage_ai/data_preparation/models/block/sql/__init__.py
- mage_ai/data_preparation/models/block/sql/utils/shared.py
- mage_ai/frontend/components/Logs/Table/index.style.ts
- mage_ai/frontend/components/Logs/Table/index.tsx
- mage_ai/io/snowflake.py
- mage_ai/tests/data_preparation/models/block/test_sql.py
- Allow more flexibility in Snowflake sql block queries. Users only need to include the database and schema config in one of these 3 places, in order of priority (so if all 3 are included, `#1` takes priority, then `#2`, then `#3`):
1. Users can include the db and schema directly in the query (e.g. `select * from demo_db.mage_dev2.jk_demo_table;`)
2. Users can include the db and schema in the SQL code block header inputs. For example:
3. Users can include the default db and schema in the `io_config.yaml using these fields:
```
SNOWFLAKE_DEFAULT_DB: DEMO_DB
SNOWFLAKE_DEFAULT_SCHEMA: MAGE_DEV2
``` 
- Also confirmed snowflake queries were successful with the priorities in the scenarios above.
> [jk] Snowflake sql block defaults

- mage_ai/data_preparation/models/block/dbt/__init__.py
- mage_ai/data_preparation/models/block/dbt/utils/__init__.py
- Check for `file_path` before calling `parse_attributes` method to avoid KeyError.
- Confirmed pipeline with dbt yaml block loads successfully.
cc:
> [jk] Check for file_path in config for dbt pipelines

- .flake8
- docs/getting-started/setup.mdx
- docs/production/configuring-production-settings/overview.mdx
- docs/production/databases/default.mdx
- mage_ai/orchestration/db/models/schedules.py
Mage currently only supports SQLite and PostgreSQL as backend database engines. This PR contains the code changes and documents to support MSSQL as well.
Manually tested the setup procedure following the steps described in the added document.
To connect to the MSSQL instance running in the docker container, a tool called `sql-cli` has been used, which could be installed by the following commands
```
% npm install -g sql-cli
```
Using the following command to connect to the local MSSQL instance running in the docker container:
```
% mssql -u sa -p test_Username123
```
To show all the available databases and tables on the server:
```
mssql> sp_databases;
mssql> sp_tables;
```
The mage related tables are generated in the `master` database with `dbo` as the owner:
```
TABLE_QUALIFIER …
```
> [hw] Add the support for using MSSQL as the database engine

- mage_ai/orchestration/notification/config.py
- mage_ai/orchestration/notification/sender.py
- mage_ai/orchestration/pipeline_scheduler.py
- mage_ai/settings/__init__.py
- mage_ai/shared/config.py
- mage_ai/tests/factory.py
- mage_ai/tests/orchestration/notification/constants.py
- mage_ai/tests/orchestration/notification/test_sender.py
This PR makes the following changes
* Personalize notification messages
* Update the url to pipeline run url instead of trigger url in the default message
* Update the BaseConfig to support parsing nested dataclass
Example config in project's metadata.yaml
```
slack_config:
webhook_url: "{{ env_var('MAGE_SLACK_WEBHOOK_URL') }}"
message_templates:
failure:
details: >
Failure to execute pipeline {pipeline_run_url}.
Pipeline uuid: {pipeline_uuid}. Trigger name: {pipeline_schedule_name}.
Test custom message."
```
added unit test
tested locally
cc:
> [xy] Personalize notification messages

- mage_ai/data_preparation/models/file.py
Fix file upload. If write_type is `wb`, don't set encoding param in the file open method.
```
Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1704, in _execute result = await result
File "/usr/local/lib/python3.10/site-packages/mage_ai/server/api/v1.py", line 64, in post return await execute_operation(self, resource)
File "/usr/local/lib/python3.10/site-packages/mage_ai/api/views.py", line 66, in execute_operation raise err
File "/usr/local/lib/python3.10/site-packages/mage_ai/api/views.py", line 44, in execute_operation response = await BaseOperation(
File "/usr/local/lib/python3.10/site-packages/mage_ai/api/operations/base.py", line 60, in execute result = await self.__executed_result()
File …
```
> [xy] Fix file upload.

- mage_ai/io/mssql.py
- mage_ai/io/sql.py
The command CREATE SCHEMA IF NOT EXISTS is not supported by MSSQL. Provided a default command in BaseSQL -> build_create_schema_command, and an overridden implementation in MSSQL -> build_create_schema_command containing compatible syntax.
Called `build_create_schema_command('my_schema')` in REPL and executed returned string on Azure Sql database.
cc:
> Gjvv fix mssql

- mage_ai/server/server.py
- The regex for the block output download endpoint would not capture block_uuids with slashes in them, so this fixes that.
- Added a nested block with a `/` in the block_uuid and successfully downloaded block output.
> [jk] Allow slashes in block_uuid when downloading block output

- mage_ai/services/spark/spark.py
There was a bug related to `setAll`: the parameter needs to be a list of key-value tuples.
Tested in a local enviornment.
cc:
> [hw] Fix an issue with setAll parameter passing

- mage_ai/data_preparation/executors/streaming_pipeline_executor.py
Fix copy output in streaming pipeline. Catch deepcopy error and fallback to copy method.
`TypeError: cannot pickle '_thread.lock' object in the deepcopy from the handle_batch_events_recursively`
tested locally
cc:
> [xy] Fix copy output in streaming pipeline.

- mage_ai/frontend/components/CodeEditor/index.tsx
- There was a CDN outage for the jsdeliver.net default CDN that Monaco Editor uses, as reported in this Github issue https://github.com/mage-ai/mage-ai/issues/2776. There no longer appears to be an outage, and upon testing, the Mage editor (which uses Monaco Editor) currently loads fine.
- However, for posterity if a future CDN outage causes an issue, we can uncomment the code from this PR to quickly load the Monaco Editor from a different CDN, but for now, that doesn't seem necessary.
Default network request for loading Monaco Editor (cdn.jsdelivr.net):
Network request for loading Monaco Editor after uncommenting out call to `loader.config` (cdnjs.cloudflare.com):
The jsdelivr.net CDN was not down as of 6/19/23 11:51 AM PDT:
> [jk] Add commented-out method for changing Monaco Editor CDN if necessary

- mage_ai/authentication/oauth2.py
- mage_ai/frontend/api/utils/AuthToken.ts
- The `JWT_SECRET` for encoding and decoding access tokens is currently hardcoded, so PR allows users to update it through an environment variable.
- Built Docker container using different `JWT_SECRET` and confirmed the value of `JWT_SECRET` had changed.
> [jk] Allow JWT_SECRET to be modified via env var

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/data_preparation/models/block/dbt/utils/__init__.py
- mage_ai/frontend/components/CodeBlock/index.tsx
- Running dbt block preview would sometimes not use sample limit amount.
- Existing upstream block would get overwritten when adding a dbt block with a ref to that existing upstream block.
- Duplicate upstream block added when new block contains upstream block ref and upstream block already exists. 
Temporarily changed default sample limit to `1` and previewed output without adjusting the sample limit:
> [jk] Add dbt block fixes

- mage_integrations/mage_integrations/connections/bigquery/__init__.py
- mage_integrations/mage_integrations/destinations/bigquery/__init__.py
- mage_integrations/mage_integrations/sources/bigquery/__init__.py
Not require key file for bigquery source and destination. When Mage is deployed on GCP, it can use the service account to authenticate.
tested on gcp
cc:
> [xy] Not require key file for bigquery source and destination.

- mage_ai/data_preparation/models/pipelines/integration_pipeline.py
- mage_integrations/mage_integrations/sources/base.py
- mage_integrations/mage_integrations/sources/chargebee/__init__.py
- mage_integrations/mage_integrations/sources/commercetools/__init__.py
- mage_integrations/mage_integrations/sources/datadog/__init__.py
- mage_integrations/mage_integrations/sources/freshdesk/__init__.py
- mage_integrations/mage_integrations/sources/front/__init__.py
- mage_integrations/mage_integrations/sources/hubspot/__init__.py
- mage_integrations/mage_integrations/sources/intercom/__init__.py
- mage_integrations/mage_integrations/sources/monday/__init__.py
- mage_integrations/mage_integrations/sources/pipedrive/__init__.py
- mage_integrations/mage_integrations/sources/postmark/__init__.py
- mage_integrations/mage_integrations/sources/stripe/__init__.py
Improve visibility into non-functioning "test connection" and "load sample data" features for integration pipelines:
- Show unsupported error is "Test connection" is not implemented for an integration source.
- Update error messaging for "Load sample data" to let user know that it may not be supported for the currently selected integration source.
Testing connection when `test_connection` method not implemented (tested on all sources where the `test_connection` method was removed):
Load sample data error (a bit verbose but if the `load_data` method is not implemented, a clear exception message is not provided otherwise):
cc:
> [jk]  Update error messaging for testing connection and loading sample data

- mage_ai/data_preparation/templates/utils.py
When changing the name of a block or creating a new block, auto-create non-existant folders if the block name is using nested block names.
> [td] Create folders when saving nested block names

- mage_integrations/mage_integrations/destinations/amazon_s3/README.md
- mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py
- mage_integrations/mage_integrations/sources/amazon_s3/README.md
- mage_integrations/mage_integrations/sources/amazon_s3/__init__.py
Adding MinIO support for both Source and Destination blocks
Added docs example
Tested using https://play.min.io buckets, by transfering parquet files.
Pipeline Logs:
cc:
> adding MinIO support for S3 in Data integrations pipeline

- docs/integrations/databases/ClickHouse.mdx
Manually creating destination table is strong recommended for ClickHouse when using `Data Exporter` due to the complexity involved when defining a table.
CI
cc:
> [hw] Update doc on creating destination table in ClickHouse data exporter

- docs/production/configuring-production-settings/compute-resource.mdx
- mage_ai/services/k8s/config.py
- mage_ai/services/k8s/job_manager.py
Allow setting service account name for k8s executor.
Example k8s executor config:
```yaml
resource_limits:
cpu: 1000m
memory: 2048Mi
resource_requests:
cpu: 500m
memory: 1024Mi
service_account_name: custom_service_account_name
```
tested locally
cc:
> [xy] Allow setting service account name for k8s executor.

- mage_ai/data_integrations/destinations/constants.py
- mage_integrations/mage_integrations/destinations/oracledb/README.md
- mage_integrations/mage_integrations/destinations/oracledb/__init__.py
- mage_integrations/mage_integrations/destinations/oracledb/templates/config.json
- mage_integrations/mage_integrations/destinations/oracledb/utils.py
- mage_integrations/mage_integrations/sources/oracledb/__init__.py
Tested with S3 source, destination is oracle DB.
Scenarios tested:
1. It can create table and export data.
2. If table already exists, it can export data directly.
3. If table schema is different, it can alter table
4. If insert data with unique keys or not and can update records if duplicated unique key records found with SQL/PL command.
Screenshot of the created table, exported records:
Screenshot of the alter table schema:
cc:
@wangxiaoyou1993 @dy46
> [xh]Add OracleDB Destination

- docs/production/observability/logging.mdx
- mage_ai/api/resources/LogResource.py
- mage_ai/data_preparation/logging/logger_manager.py
- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/data_preparation/models/block/constants.py
- mage_ai/frontend/components/PipelineDetail/Settings/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- mage_ai/frontend/storage/constants.ts
- mage_ai/server/utils/output_display.py
- mage_ai/server/websocket_server.py
Optionally enable the notebook to output block execution messages to logs when running a block on the edit pipeline page.
> [td] Turn on output to logs when running a single block in the notebook

- docs/production/configuring-production-settings/compute-resource.mdx
- mage_ai/services/gcp/cloud_run/cloud_run.py
- mage_ai/services/gcp/cloud_run/config.py
Support customizing the timeout seconds in gcp cloud run config.
tested on gcp
cc:
> [xy] Support customizing the timeout seconds in gcp cloud run config.

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/CodeBlock/utils.ts
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- mage_ai/server/utils/output_display.py
- mage_ai/server/websocket_server.py
When running a block in the notebook, provide an option to only run the upstream blocks that haven’t been executed successfully.
> [td] Execute incomplete upstream blocks from another block

- mage_ai/data_preparation/models/block/dbt/__init__.py
Fix this error:
```
File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 34, in retry_func
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 109, in __execute_with_retry
return self._execute(
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 200, in _execute
result = self.block.execute_sync(
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 840, in execute_sync
raise err
File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 779, in execute_sync
output = self.execute_block(
File …
```
> [td] Use UTF-8 encoding when logging output from dbt blocks

- mage_ai/frontend/components/CodeBlock/index.tsx
- mage_ai/frontend/components/CodeBlock/utils.ts
- mage_ai/frontend/components/DependencyGraph/index.tsx
- mage_ai/frontend/components/Sidekick/index.tsx
- mage_ai/frontend/interfaces/KernelOutputType.ts
When in the edit pipeline page, after an individual block executes and fails, when executing that block again and it succeeds, the block’s status (e.g. checkmark, red cross, etc) in the tree UI doesn’t update to reflect the success status of the block.
> [td] Update tree node when block status changes

- mage_integrations/mage_integrations/destinations/bigquery/__init__.py
- mage_integrations/mage_integrations/destinations/sql/base.py
- mage_integrations/mage_integrations/destinations/trino/connectors/base.py
Introduce a new constant `TABLE_CONFIG_KEY` to be consistent with `DATABASE_CONFIG_KEY` and `SCHEMA_CONFIG_KEY`, to avoid using the hard-coded `table` string.
CI
cc:
> [hw] Define a new TABLE_CONFIG_KEY to replace the hard-coded 'table' constant

- mage_ai/data_preparation/models/block/__init__.py
If a callback has multiple upstream blocks, only fetch input variables from 1 upstream block at at time.
> [td] Fix callbacks to only get input from 1 upstream

- mage_ai/io/mysql.py
- mage_ai/io/sql.py
- mage_integrations/mage_integrations/destinations/snowflake/utils.py
Update snowflake to cast strings as `VARCHAR` instead of `VARCHAR(255)`. Also update the `mysql` io loader to use `TEXT` for strings so they don't get cut off at 255 characters.
tested locally
> [dy] Update snowflake to use VARCHAR

- mage_ai/frontend/components/Triggers/Edit/index.tsx
When refreshing the page, the cron settings weren’t being set properly. It was setting it to `custom` on the UI when it should’ve been the actual cron expression string.
cc:
@dy46
> [td] Fix cron settings when editing trigger

- mage_ai/io/config.py
Fixes a bug in `ConfigFileUploader`.  
```
432         else:
433             if filepath is None:
--> 434                 filepath = get_repo_path() / 'io_config.yaml'
435             self.filepath = Path(filepath)
436             self.profile = profile
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
[Link to slack thread](https://mageai.slack.com/archives/C03HTTWFEKE/p1689202141593109)
Ran the code locally and confirmed the unit tests are all still passing.
cc:
@mattppal - Let me know if there's anything else I should include in this request. Thanks!
> fix default filepath in ConfigFileLoader __init__

- mage_ai/data_preparation/executors/azure_container_instance_executor.py
- mage_ai/data_preparation/executors/block_executor.py
- mage_ai/data_preparation/executors/ecs_block_executor.py
- mage_ai/data_preparation/executors/gcp_cloud_run_block_executor.py
- mage_ai/data_preparation/executors/k8s_block_executor.py
- mage_ai/tests/data_preparation/executors/test_block_executor.py
Fix retry when using k8s executor
* Only retry in BlockExecutor inside the k8s pod
* Fetch retry config from repo_config and block config when it's None
tested on local k8s cluster
cc:
> [xy] Fix retry when using k8s executor

- .github/workflows/build_and_test.yml
- Dockerfile
- dev.Dockerfile
Replace the use of `apt` instead with `apt-get`.
While [apt](https://manpages.ubuntu.com/manpages/xenial/man8/apt.8.html) is newer, it is meant to be a high-level, user-friendly tool, better suited for interactive use. In contrast, [apt-get](https://manpages.ubuntu.com/manpages/xenial/man8/apt-get.8.html) is intended to be the "backend" that multiple other UIs utilize for programmatic control.
This doesn't matter when I tested with Docker Desktop on Mac, but I found that using `apt` was broken when using Docker on Minikube. For example, one dependency that failed was `msodbcsql18`.
Updating the Dockerfile and dev.Dockerfile to `apt-get` successfully allowed me to build using Docker on Minikube. I have not tested the 2nd commit, which is for the GitHub Action defined in build_and_test.yml, …
> Use apt-get when invoking from scripts

- docs/production/configuring-production-settings/compute-resource.mdx
- mage_ai/data_preparation/executors/k8s_block_executor.py
- mage_ai/services/k8s/config.py
- mage_ai/services/k8s/job_manager.py
- mage_ai/tests/data_preparation/executors/test_k8s_block_executor.py
Support custom k8s executor job prefix.
Example k8s executor config:
```yaml
job_name_prefix: data-prep
resource_limits:
cpu: 1000m
memory: 2048Mi
resource_requests:
cpu: 500m
memory: 1024Mi
service_account_name: default
```
tested locally
cc:
> [xy] Support custom k8s executor job prefix.

- mage_ai/data_integrations/logger/utils.py
- mage_ai/data_integrations/utils/config.py
- mage_ai/data_integrations/utils/parsers.py
- mage_ai/data_preparation/models/block/integration/__init__.py
- mage_ai/data_preparation/models/pipelines/integration_pipeline.py
- mage_ai/shared/security.py
I added filtering to data integration logging to hide string source/destination config values. 
At some point we should make the data integration logging more organized since we log things in a lot of places.
tested locally
> [dy] Remove data integration config from logs

- mage_ai/data_preparation/models/block/sql/__init__.py
- mage_ai/data_preparation/models/block/sql/clickhouse.py
- mage_ai/data_preparation/models/block/sql/utils/shared.py
- mage_ai/io/clickhouse.py
Storing ClickHouse data to a custom database caused exceptions, as described in https://github.com/mage-ai/mage-ai/issues/2988
Manually tested in a local development environment, with the following custom ClickHouse settings:
```
CLICKHOUSE_DATABASE: helloworld
CLICKHOUSE_HOST: host.docker.internal
CLICKHOUSE_INTERFACE: http
CLICKHOUSE_PASSWORD: null
CLICKHOUSE_PORT: 8123
CLICKHOUSE_USERNAME: null
```
The data generated from the previous `Data loader` block was from the following code:
```
@data_loader
def load_data(*args, **kwargs):
"""
Template code for loading data from any source.
Returns:
Anything (e.g. data frame, dictionary, array, int, str, etc.)
"""
import pandas as pd
return pd.DataFrame({'num_legs': [2, 4, 8, 0],
'num_wings': [2, 0, 0, 0],
'num_specimen_seen': [10, 2, 1, 8]}, …
```
> [hw] Fix the issue with database setting when running ClickHouse in SQL blocks

- mage_ai/data_integrations/utils/scheduler.py
- mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
- mage_ai/frontend/interfaces/IntegrationSourceType.ts
- mage_ai/frontend/oracle/elements/Inputs/ToggleSwitch.tsx
- mage_ai/orchestration/job_manager.py
- mage_ai/orchestration/pipeline_scheduler.py
- mage_integrations/mage_integrations/sources/catalog.py
Run streams in parallel if they are marked as parallel. I added the `run_in_parallel` config to the stream catalog entry.
I updated the `run_integration_pipeline` method in `pipeline_scheduler` to queue a job for each parallel stream and another job for all non-parallel streams. The code that is run for each stream should be unchanged, but the structure of an integration pipeline run is different.
tested locally
> [dy] Add option to run integration streams in parallel

- .github/releases.yml
**Note**: this is very much a WIP and will still require human eyes/edits 😀
Via [this](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) doc, we can semi-automate release note generation. This should simplify the process for building release notes while maintaining a human element.
The workflow can look like GitHub automated release notes -> edit -> share. A bonus is that releases can now automatically include shout outs for first time contributors, e.g. 
```
- @ethanbrown3 made their first contribution in https://github.com/mage-ai/mage-ai/pull/2976
- @erictse made their first contribution in https://github.com/mage-ai/mage-ai/pull/2977
```
cc:
@wangxiaoyou1993 
@thomaschung408
> automate release note generation

- mage_ai/api/resources/BlockResource.py
Fix deleting block.
>   File "/home/xxx/.local/lib/python3.10/site-packages/mage_ai/api/resources/BaseResource.py", line 212, in process_delete
>     res = await res
>   File "/home/xxx/.local/lib/python3.10/site-packages/mage_ai/api/resources/BlockResource.py", line 171, in delete
>     cache.remove_pipeline(self.model, pipeline.uuid)
> AttributeError: 'NoneType' object has no attribute 'uuid'
tested locally
cc:
> [xy] Fix deleting block.

- mage_ai/frontend/components/FileBrowser/utils.ts
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Instead of opening the file browser and showing the file versions when clicking on a file on the edit pipeline page, select the block and scroll to it if the file exists in the pipeline.
> [td] When clicking a file in file browser, select block if in pipeline

- mage_ai/frontend/components/IntegrationPipeline/SelectStreams/index.tsx
- For integration pipelines, if the configured source user/role does not have schema permissions, it may not be apparent to the Mage user since no error is displayed but no streams are displayed.
- Show warning for user to check schema permissions if no streams are displayed.
> [jk] Show warning if no streams displayed

- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- If user has a syntax error in their `io_config.yaml` file, it may cause an error when fetching the data providers and profiles for SQL blocks. This PR will parse the error from the data provider response and display it in the UI.
> [jk] Display error when fetching data providers

- mage_ai/api/presenters/GitCustomBranchPresenter.py
There is an edge case where 17K file names are being returned from the API response.
This causes too much data to be transferred over the network and slows down the entire app.
> [td] Limit number of files returned from Git Custom Branch API

- mage_ai/frontend/components/FileEditor/index.tsx
- mage_ai/server/server.py
- Add `/files` route so that it is accessible from frontend production build.
- Resolve TypeError related to unmatched regex in FileEditor.
- Confirmed TypeError no longer appeared locally after adding default file extension and optional chaining.
- Can access `/files` route directly from url (previously would throw 404 error):
> [jk] Add /files route to backend server and fix TypeError in FileEditor

- mage_ai/data_preparation/executors/azure_container_instance_executor.py
- mage_ai/data_preparation/executors/block_executor.py
- mage_ai/data_preparation/executors/ecs_block_executor.py
- mage_ai/data_preparation/executors/gcp_cloud_run_block_executor.py
- mage_ai/data_preparation/executors/k8s_block_executor.py
- mage_ai/data_preparation/models/block/utils.py
- mage_ai/orchestration/pipeline_scheduler.py
- mage_ai/tests/data_preparation/executors/test_block_executor.py
- mage_ai/tests/data_preparation/executors/test_k8s_block_executor.py
Fix running dynamic blocks in k8s/gcp_cloud_run/ecs/azure_container_instance executors
* Create dynamic child block runs in block executor after block execution completes.
* Move dynamic_upstream_block_uuids generation logic into block executor
tested locally
cc:
> [xy] Create dynamic block runs in block executor.

- mage_ai/api/policies/BlockPolicy.py
The block settings aren’t updating because of a policy issue.
> [td] Fix block settings not updating after saving

- mage_ai/frontend/pages/pipelines/index.tsx
- See title. Hovering over `Updated at` value shows the timestamp with seconds.
> [jk] Add "Updated at" column to Pipelines list page

- mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
- mage_ai/frontend/components/Logs/Detail/index.tsx
- mage_ai/frontend/components/Logs/Table/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
- When user clicks on a log row from the Logs table, default to opening the Errors tab in the Log Detail instead of the Details tab if the log is an error log.
> [jk] Default error log to Errors tab when opening log detail

- mage_ai/ai/gen_doc_for_pipeline.py
- mage_ai/ai/generator.py
- mage_ai/ai/llm_pipeline_wizard.py
Update llm block generation function to by async. In this way, it takes less time to generate documentation for pipeline.
Commands:
`python mage_ai/ai/gen_doc_for_pipeline.py generate-pipeline-documentation documentation documentation_standard_pipeline_test_1 --print-block-doc`
`python mage_ai/ai/gen_doc_for_pipeline.py generate-block-documentation documentation documentation_standard_pipeline_test_1 polished_fire`
cc:
> [xh]Update documentation generation as async

- docs/guides/schedule-pipelines.mdx
- docs/orchestration/backfills/overview.mdx
- mage_ai/orchestration/backfills/service.py
- mage_ai/orchestration/db/models/schedules.py
- mage_ai/server/websocket_server.py
A block will now have variables of when the pipeline run was schedule for, the datetime of the next scheduled pipeline run, and the number of seconds between.
- https://docs.mage.ai/orchestration/backfills/overview
- https://docs.mage.ai/guides/schedule-pipelines
> [td] Include interval datetimes and intervals in block variables

- mage_ai/frontend/pages/pipelines/index.tsx
- mage_ai/frontend/storage/pipelines.ts
When filtering or grouping the pipelines on the pipelines list page, preserve those settings so that when a user comes back to that page, those filters and group bys persist.
> [td] Save pipelines list filters and group bys

- mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
- mage_ai/frontend/oracle/components/ToggleMenu/index.tsx
- mage_ai/frontend/pages/pipelines/index.tsx
The filters and group by values weren’t being removed when there are no more selections.
> [td] Fix pipelines list filters and group bys not removing

- mage_ai/frontend/components/Files/index.tsx
The file content could not be fetched because we weren’t encoding the file path.
> [td] Encode URI component for file path on files page

- docs/guides/schedule-pipelines.mdx
- docs/orchestration/backfills/overview.mdx
- mage_ai/orchestration/backfills/service.py
- mage_ai/orchestration/db/models/schedules.py
- mage_ai/server/websocket_server.py
Include the previous run’s `interval_start_datetime` as the keyword argument `interval_start_datetime_previous`.
> [td] Add interval_start_datetime_previous for the previous run’s interval_start_datetime

- docs/mint.json
- docs/production/deploying-to-cloud/gcp/gcp-artifact-registry.mdx
- docs/production/deploying-to-cloud/gcp/setup.mdx
Google Cloud Run now supports running Docker images from Docker Hub directly. This resolves the issue mentioned in https://github.com/mage-ai/mage-ai/issues/3033 and drastically simplifies steps to configure Mage on GCP. 
An updated Terraform template PR is available [here](https://github.com/mage-ai/mage-ai-terraform-templates/pull/39).
Followed instructions to spin up Mage instance via Terraform.
> [mp] simplify GCP terraform docs to use cloud run

- mage_ai/ai/constants.py
- mage_ai/ai/generator.py
- mage_ai/ai/generator_cmds.py
- mage_ai/ai/llm_pipeline_wizard.py
Use latest openai function call API: https://platform.openai.com/docs/guides/gpt/function-calling to classify the block description with different block attributes.
Then pass the attributes to `fetch_template_source` function to return the block template.
Recorded my evaluation in this spreadsheet: https://docs.google.com/spreadsheets/d/1vp0UB6EqM3vnY4f0hYV0nB36X7ngiRIVZZU4FFcybH0/edit#gid=0
Feel free to try more and add the samples into the spreadsheet. Eventually we can use the data in spreadsheet as integration test/verification for this feature iteration.
cc:
> [xh]Generate block template based on block description

- mage_ai/frontend/components/CodeBlock/index.tsx
- If the default `target` was not set in the `profiles.yml` file for a dbt project, the target input in the UI was a bit confusing since it was unclear that users were required to enter or select a target. If user did not select a target and no default target was set, an error would occur.
If default dbt target is set in `profiles.yml` file ([sample config](https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml)), then user does not need to select target when adding a new dbt block:
If default dbt target is NOT set in `profiles.yml`, then the target input will now say "Select target" or "Enter target" instead of displaying a dbt target that is not actually selected:
Github issue: #3046
> [jk] Clarify input for dbt profile target if a default target is not configured

- docs/getting-started/setup.mdx
- docs/production/configuring-production-settings/overview.mdx
- docs/production/databases/default.mdx
- mage_ai/orchestration/db/__init__.py
Add the schema creation step to support running multiple Mage instances with the same PostgreSQL databases, but in different schemas. The PostgreSQL connection URL should have the `options` parameter passed in through a special query string format:
```
export MAGE_DATABASE_CONNECTION_URL=postgresql+psycopg2://user:password@host:port/dbname?options=-c%%20search_path%%3Dschema_name'
```
where `schema_name` needs to be changed to the schema name specific to the Mage instance.
For example,
```
export DATABASE_CONNECTION_URL='postgresql+psycopg2://test_username:test_password@postgres_db:5432/test_database?options=-c%%20search_path%%3Dtest_schema_8'
```
Manually tested with a local development environment, with the following steps:
1. Build the Mage docker image:
```
./scripts/init.sh …
```
> [hw] Support PostgreSQL schema based on the connection URL

- mage_ai/orchestration/db/__init__.py
```
mage-ai-server-1  |   File "/home/src/mage_ai/orchestration/db/__init__.py", line 87, in <module>
mage-ai-server-1  |     db_schema = get_postgresql_schema(db_connection_url)
mage-ai-server-1  |   File "/home/src/mage_ai/orchestration/db/__init__.py", line 78, in get_postgresql_schema
mage-ai-server-1  |     params = parse_qs(
mage-ai-server-1  | KeyError: 'options'
```
> [td] Fix db init on start

- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- Fix logic for making API requests for block outputs or analyses that were throwing errors due to invalid pipeline_uuids.
- Local
> [jk] Do not make block outputs API request if after panel hidden

- mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
- See title. Previously, clicking the `Defaults` button would not clear the pipeline filters and persist it.
> [jk] Clear pipeline list filters when clicking Defaults

- mage_ai/api/policies/VariablePolicy.py
- mage_ai/api/resources/VariableResource.py
- mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
- Pipeline Editor and Triggers List pages were fetching unnecessary output data in the variables response that could lead to the response payload being many MB in size.
- Add query param to Variables API that only fetches global variables.
Using `global_only` query param in `/api/pipelines/[pipeline_uuid]/variables?global_only=true` API request only returned global variables (FE still had necessary data for rendering components):
> [jk] Decrease variables response size

- mage_ai/orchestration/pipeline_scheduler.py
For pipeline runs that don't have `allow blocks to fail` enabled, we will cancel the in progress block runs if the pipeline run fails.
tested locally
> [dy] Cancel block runs when pipeline run fails

- mage_ai/data_preparation/models/block/dbt/utils/__init__.py
Hotfix to resolve a dbt snowflake issue where roles are not fetched.
https://mage-ai.slack.com/archives/C05CNS7S7LL/p1690334217653419
> [mp] fetch snowflake role

- mage_ai/api/policies/PipelineSchedulePolicy.py
- mage_ai/api/presenters/PipelineSchedulePresenter.py
- mage_ai/frontend/components/Triggers/Edit/index.tsx
- mage_ai/frontend/interfaces/PipelineScheduleType.ts
- mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx
- mage_ai/frontend/utils/string.ts
- mage_ai/orchestration/db/models/schedules.py
- Enable landing time on trigger edit page
- Show trigger’s average runtime
- Edit the landing time
> [td] Added UI for landing times

- docs/design/blocks/sensor.mdx
- docs/design/core-abstractions.mdx
- docs/development/blocks/sensors/templates.mdx
- mage_ai/data_preparation/templates/sensors/default.py
- mage_ai/orchestration/run_status_checker.py
There was a bug with check_status method in orchestration while compared exact execution_datetime with pipeline run datetime which is not the purpose of the method. Rather it should check if pipeline was ran within a specific time period. Hence included another parameter hours. Now the method checks if pipeline had a successful run between execution_date - hours and execution_date
Tested locally
cc:
> {orchestration] check_status method bug fix to look at pipelines ran between specific time period

- mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
- mage_ai/frontend/components/PipelineRun/shared/utils.ts
- mage_ai/orchestration/monitor/monitor_stats.py
- Account for pipeline runs without associated triggers (e.g. if the trigger was deleted) on the Overview page stats.
Before (runs without associated triggers not factored in counts):
After (Overall pipeline run counts include runs without associated triggers in the metric summary as well as bar chart):
> [jk] Include runs without associated triggers in pipeline run count

- mage_ai/api/resources/DataProviderResource.py
Throw correct exception about io config.
tested locally
Old exception: `"exception": "free variable 'profiles' referenced before assignment in enclosing scope",`
New exception shows the invalid yaml error: 
cc:
> [xy] Throw correct exception about io config.

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/data_preparation/models/block/dbt/__init__.py
- mage_ai/data_preparation/models/block/integration/__init__.py
- mage_ai/data_preparation/models/block/sql/__init__.py
- mage_ai/server/utils/output_display.py
- mage_ai/server/websocket_server.py
- mage_ai/tests/data_preparation/models/test_block.py
Updated how python blocks are executed when run from the notebook. Instead of running the block function directly from the file, we will import the block function and then execute it so that the error logging is more readable. 
I also changed the `test_execution` parameter to `from_notebook` to be consistent across the Block functions.
tested locally with different blocks
examples:
> [dy] Import block function from file for test execution

- mage_ai/services/k8s/config.py
- mage_ai/services/k8s/job_manager.py
- mage_ai/tests/services/k8s/test_job_manager.py
Support custom k8s executor config.
```
service_account_name: mageai
job_name_prefix: "{{ env_var('KUBE_NAMESPACE') }}"
container_config:
image: mageai/mageai:0.9.7
env:
- name: USER_CODE_PATH
value: /home/src/k8s_project
```
tested locally
unit tests
cc:
> [xy] Support custom k8s executor config.

- mage_ai/orchestration/db/models/schedules.py
- mage_ai/tests/orchestration/db/test_models.py
- mage_ai/tests/orchestration/test_pipeline_scheduler.py
Add tests for:
`PipelineSchedule`
- `current_execution_date`
- `landing_time_enabled`
- `runtime_history`
- `runtime_average`
- `should_schedule`
`pipeline_scheduler`
- `schedule_all`
> [td] Add unit test for landing time

- mage_ai/api/resources/CustomTemplateResource.py
- mage_ai/api/resources/SearchResultResource.py
- mage_ai/api/resources/VariableResource.py
- mage_ai/data_preparation/sync/git_sync.py
- mage_ai/orchestration/monitor/monitor_stats.py
- mage_ai/orchestration/pipeline_scheduler.py
- mage_ai/orchestration/triggers/api.py
- mage_ai/orchestration/utils/git.py
- mage_ai/tests/orchestration/test_pipeline_scheduler.py
Currently, git syncs are run every time a pipeline run is started. However, it is possible for many pipeline runs to get created at the same time which could start a large number of git syncs which can cause problems. I changed the logic in the `pipeline_scheduler` to only perform 1 git sync for all active pipeline schedules.
This can be an issue for event and api triggers as well, but I'll fix that in the future since it's a more difficult problem to solve.
tested locally
> [dy] Batch git sync in pipeline_scheduler

- mage_ai/data_preparation/models/pipelines/integration_pipeline.py
The `test_connection` subprocess has a timeout, so if it times out, it will raise not raise a `subprocess.CalledProcessError`. This PR will catch the other exceptions and hide the config values in them.
tested locally
cc:
> [dy] Catch timeout exception for test_connection

- docs/production/configuring-production-settings/compute-resource.mdx
- mage_ai/services/aws/ecs/config.py
- mage_ai/services/aws/ecs/ecs.py
Allow customize the timeout for the ECS task. The default timeout is 10 minutes.
```yaml
ecs_config:
cpu: 1024
memory: 2048
wait_timeout: 1200
```
tested on ECS
cc:
> [xy] Allow customize the timeout for the ECS task.

- mage_ai/io/azure_blob_storage.py
Added options to pass azure blob upload_kwargs to allow overwriting an existing file or use any other options as described [here](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-upload-blob)
Test locally
cc:
> azure blob storage upload kwargs to allow file overwrite

- mage_ai/frontend/components/charts/LineSeries.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runtime.tsx
> [jk] Add block runtime chart for all blocks

- docs/tutorials/load-api-data.mdx
- docs/tutorials/setup-dbt.mdx
Apparently Supabase has a 1 week timeout on free projects. This swaps ElephantDB to avoid the limit— inspired by a [community suggestion](https://mageai.slack.com/archives/C03KW780J2F/p1690957394440159?thread_ts=1690855264.337059&cid=C03KW780J2F).
Tested with dev instance
cc:
> [mp] swap elephantdb for supabase

- mage_integrations/mage_integrations/destinations/bigquery/__init__.py
The calling to the super method does not need "self" as the parameter. It causes a bug: https://mageai.slack.com/archives/C03HTTWFEKE/p1690989837657589
CI
cc:
> [hw] Fix an issue in the bigquery init method

- mage_ai/orchestration/queue/queue_factory.py
- mage_ai/orchestration/triggers/utils.py
Do not start pipeline run immediately after creation. The pipeline run is started in scheduler when there's enough concurrency quota to start a new pipeline run.
https://github.com/mage-ai/mage-ai/blob/master/mage_ai/orchestration/pipeline_scheduler.py#L1413-L1422
tested locally
cc:
> [xy] Do not start pipeline run immediately after creation.

- mage_ai/shared/utils.py
When a boolean field is present in the source DataFrame, an exception was thrown when running with a ClickHouse exporter.
Manually tested in a local development environment, with a Standard Batch pipeline consisting of a Data Loader `Python/Generic (no template)` and a Data Exporter `SQL/ClickHouse`:
Data Loader:
```
if 'data_loader' not in globals():
from mage_ai.data_preparation.decorators import data_loader
if 'test' not in globals():
from mage_ai.data_preparation.decorators import test
@data_loader
def load_data(*args, **kwargs):
"""
Template code for loading data from any source.
Returns:
Anything (e.g. data frame, dictionary, array, int, str, etc.)
"""
import pandas as pd
return pd.DataFrame({'num_legs': [2, 4, 8, 0],
'num_wings': [2, 0, 0, 0],
'num_specimen_seen': [10, 2, 1, 8], …
```
> [hw] Fix the `bool` data type conversion issue with the ClickHouse exporter

- docs/design/blocks/transformer.mdx
Just fixing a typo
https://www.dictionary.com/e/then-vs-than/
> fix: Typo in transformer.mdx

- mage_ai/cluster_manager/aws/ecs_task_manager.py
- mage_ai/services/aws/__init__.py
- mage_ai/services/aws/ecs/ecs.py
- mage_ai/services/aws/emr/emr.py
- mage_ai/services/aws/events/events.py
- mage_ai/services/aws/secrets_manager/secrets_manager.py
Fixes issue: https://github.com/mage-ai/mage-ai/issues/2929
Use `AWS_REGION_NAME` but default to `AWS_DEFAULT_REGION` for aws region environment variable.
tested locally
> [dy] Consolidate aws region variables

- docs/getting-started/setup.mdx
- docs/production/configuring-production-settings/overview.mdx
- docs/production/databases/default.mdx
There are issues with pipeline/block status checking in Mage with MySQL, i.e., SQLAcademy syntax was quite different in MySQL from other databases (SQLite/PostgreSQL/MSSQL), which lead to wrong pipeline/block status checking results, then hanging of pipeline/block executions. Therefore, MySQL is temporarily removed from the list of the supported backend databases.
CI
cc:
> [hw] Remove MySQL from the supported backend databases due to some unexpected issues

- mage_ai/cluster_manager/kubernetes/workload_manager.py
- mage_ai/frontend/components/workspaces/ConfigureWorkspace/constants.ts
- mage_ai/orchestration/db/__init__.py
- mage_ai/orchestration/db/database_manager.py
- mage_ai/server/scheduler_manager.py
We can now support adding a workspace to a k8s ingress by adding a path to the ingress rules. The added rule will look like this
```
paths:
...
backend:
service:
name: <service-name>
port: 6789
path: /<workspace-name>
path_type: Prefix
```
tested locally with k8s ingress
cc:
> [dy] Support updating ingress when creating k8s workspace

- mage_ai/data_preparation/repo_manager.py
- mage_ai/tests/data_preparation/test_repo_manager.py
Call `os.expanduser` on the variables dir when it comes from the project metadata or the default path.
tested locally
> [dy] Fix variables dir construction

- mage_ai/orchestration/db/__init__.py
- mage_ai/orchestration/db/database_manager.py
We currently don't escape characters in the db_connection_url, but the sqlalchemy and alembic docs do suggest doing so. I also ran into an error when I had a special character in the password which caused the alembic migrations to fail.
Docs:
https://docs.sqlalchemy.org/en/14/core/engines.html#database-urls
https://alembic.sqlalchemy.org/en/latest/api/config.html#alembic.config.Config.set_main_option
tested locally with postgres and sqlite
> [dy] Escape password in db_connection_url

- mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
- See title.
- Ran integration pipeline with manually set bookmark value and confirmed destination contained values starting from that bookmark value.
- Bookmark values can be edited properly now:
Fixes https://github.com/mage-ai/mage-ai/issues/3153
> [jk] Fix infinite rendering loop in SchemaTable

- mage_ai/frontend/components/Logs/Detail/index.tsx
- mage_ai/frontend/components/Logs/Table/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
- When clicking on certain logs that have metrics in the log detail, app will crash if the metrics is a javascript object (React cannot have a js object as the child of a React component).
- Fixed issue with logs scrolling to bottom any time an individual log was clicked and "Auto-scroll to bottom of logs" setting turned on.
Metrics property rendering properly in the log detail panel:
> [jk] Fix log detail metrics object rendering issue

- mage_ai/frontend/components/Triggers/Detail/index.tsx
- mage_ai/frontend/components/Triggers/Edit/index.tsx
- mage_ai/frontend/components/Triggers/Table.tsx
- mage_ai/frontend/interfaces/PipelineScheduleType.ts
- Show tags for each pipeline schedule (trigger) in the row
- Show tags in the pipeline schedule detail page on the left side
- Add/Remove tags while on edit pipeline schedule page
cc:
> [td] Add pipeline schedule tags

- mage_ai/data_preparation/models/block/dbt/utils/__init__.py
When using Key Pair authentication with dbt and Snowflake, if the `password` key in the `profiles.yml` is present but the value is null or empty, an error occurs:
cc:
> [td] Fix dbt snowflake when password null

- mage_ai/frontend/components/GlobalDataProductDetail/SettingsField.tsx
- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
Adding a global data product block was available in the v2 flow of adding block.
This change enables this block for v1.
cc:
> [td] Add global data product block to add block v1

- mage_ai/io/clickhouse.py
When running the following SQL statement on the ClickHouse Cloud, it threw exceptions:
```
clickhouse-cloud :) CREATE TABLE IF NOT EXISTS test_002 ENGINE = Memory AS select * from insert_select_testtable;
CREATE TABLE IF NOT EXISTS helloworld_2.test_002
ENGINE = Memory AS
SELECT *
FROM insert_select_testtable
Query id: 900ee1d8-ed25-4c44-b4b2-bb21dceb6350
0 rows in set. Elapsed: 0.169 sec. 
Received exception from server (version 23.8.1):
Code: 344. DB::Exception: Received from fadpvrevk3.us-west-2.aws.clickhouse.cloud:9440. DB::Exception: CREATE AS SELECT is not supported with Replicated databases. Use separate CREATE and INSERT queries. (SUPPORT_IS_DISABLED)
```
Thus the following 2-step procedure is used instead to work-around this issue:
1. Create an empty table:
```
CREATE TABLE IF …
```
> Change the table creation into two steps as required by the ClickHouse Cloud

- mage_ai/data_preparation/repo_manager.py
Fix exception
```
An error was encountered:
[Errno 13] Permission denied: '/home/.mage_data'
File "/usr/local/lib/python3.7/site-packages/mage_ai/orchestration/db/__init__.py", line 48, in <module>
db_connection_url = f'sqlite:///{get_variables_dir()}/mage-ai.db'
File "/usr/local/lib/python3.7/site-packages/mage_ai/data_preparation/repo_manager.py", line 287, in get_variables_dir
os.makedirs(variables_dir, exist_ok=True)
File "/usr/lib64/python3.7/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/lib64/python3.7/os.py", line 223, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/.mage_data
```
When executing code on EMR via pyspark kernel, we don't use DB. So catch the exception of creating dir. …
> [xy] Fix EMR pyspark kernel permission error

- mage_ai/api/resources/BackfillResource.py
- mage_ai/frontend/components/DependencyGraph/index.tsx
- mage_ai/frontend/components/Triggers/Detail/index.tsx
- mage_ai/orchestration/db/models/schedules.py
- mage_ai/orchestration/pipeline_scheduler.py
- If the timezone setting on a VM or Docker container running Mage was changed from UTC (which Mage uses across the app), the block and pipeline run completion times would be set in that timezone, although the start times were still in UTC. This caused confusion as a run could seem like it took a lot longer than it actually did. For example, if the timezone was set to UTC+3 (3 hours ahead of UTC) and a pipeline was run, its completion time appeared 3 hours after the start time even though the run did not take 3 hours.
- This PR makes the completion time for block and pipeline runs in UTC even if the VM or Docker container is set to a different timezone. This also updates the backfill start and completion time as those were also set to the system's timezone setting.
- Resolves …
> [jk] Block run and pipeline run start/completion times in UTC

- mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- Fix error when adding a block via the "Search for a block..." input in the V2 Add Block flow.
Before (adding a block would throw an error):
After (Adding a searched block is allowed--it's assumed a user wants to reuse a block if they are searching for it. If user searches for a block already existing in the pipeline, an error is displayed.):
> [jk] Allow adding block from search

- docs/guides/sql-blocks.mdx
- mage_ai/data_preparation/models/block/sql/__init__.py
Limit the number of rows of sql block output in pipeline run. The original limit is only applied to the notebook.
When running the sql block in pipeline run, it fetches maximum 10 million rows, which could slow the the pipeline run execution and could be unnecessary. So this PR makes the row limit configurable when running the sql block in pipeline run.
Example block config:
```
blocks:
- all_upstream_blocks_executed: true
color: null
configuration:
data_provider: sqlserver
data_provider_profile: default
export_write_policy: replace
limit: 1000
limit_in_pipeline_run: 2000
use_raw_sql: false
....
```
This PR also made a fix on limiting the number of rows fetched from MSSQL.
cc:
> [xy] Limit the number of rows of sql block output in pipeline run

- mage_ai/data_preparation/models/custom_templates/utils.py
- mage_ai/tests/data_preparation/models/custom_templates/test_utils.py
Fix this error:
`TypeError: posixpath.join() argument after * must be an iterable, not NoneType`
cc:
> [td] Fix custom templates with empty parent names

- mage_integrations/mage_integrations/sources/sql/base.py
Per suggestion from ticket https://github.com/mage-ai/mage-ai/issues/3198#issuecomment-1672496332, this PR updates the data integration source to use "greater than" operator instead :greater than or equal" operator to compare bookmark values for unique columns.
Without this change, there's always one row synced:
cc:
> [xy] Use greater than operator for unique columns in source sql bookmark comparison.

- mage_ai/ai/generator.py
- mage_ai/ai/generator_cmds.py
- mage_ai/ai/llm_pipeline_wizard.py
Add upstream block Ids when generating pipeline code
The block split function return the following response instead:
```
BLOCK 1: function: load data from MySQL. upstream:
BLOCK 2: function: load data from Postgres. upstream:
BLOCK 3: function: merge data from MySQL and Postgres. upstream: 1, 2
BLOCK 4: function: filter row that block_id > 10. upstream: 3
BLOCK 5: function: export data to Postgres. upstream: 4
BLOCK 6: function: export data to Amazon S3. upstream: 4
```
I parse the `upstream` and add field `upstream_blocks` in the block configuration.
cc:
> [xh]Add upstream block Ids when generating pipeline code

- mage_ai/data_preparation/models/block/integration/__init__.py
Issue:
```
I’m setting up a data integration pipeline for Google Search Console to be loaded into BigQuery, and for some reason
two of the fields are being loaded into BigQuery obfuscated as *************, site_url and date.  There doesn’t
seem to be any options to configure field level obfuscation that I can see, what’s happening?
```
The bug was introduced in version 0.9.4
Thus, this PR removes filter_out_config_values method call when writing the source output to file.
cc:
> [xy] Not obfuscate data in data integration records.

- mage_ai/data_preparation/models/variable.py
Improve error message for duplicate column name.
The current error message "AttributeError: 'DataFrame' object has no attribute 'dtype'" is misleading
Before this change
After this change
cc:
> [xy] Improve error message for duplicate column name.

- mage_ai/services/spark/spark.py
- mage_ai/tests/services/spark/test_spark.py
In the original `spark_config` settings, the jar files are set as:
```
/home/spark-jars/aws-java-sdk-core-1.11.1026.jar
```
However, when retrieved from the Spark context, the names of jar files are changed:
``` 
spark://************:2222/jars/aws-java-sdk-core-1.11.1026.jar
```
Thus, code changes are made to ensure the parity checking between the above two jar paths to be equivalent, to work around this issue. More details are available in [the Slack thread](https://mageai.slack.com/archives/C03GGQTS8CT/p1690897341882629).
Run the following commands in a Python3 shell:
```
>>> import os
... 
>>> a = ['/home/spark-jars/aws-java-sdk-core-1.11.1026.jar']
>>> b = ['spark://************:2222/jars/aws-java-sdk-core-1.11.1026.jar']
>>> contains_same_jars(a, b)
True
```
cc:
@dy46 …
> [hw] When comparing spark.jars, use the file names and neglect paths

- mage_ai/data_preparation/models/block/__init__.py
- mage_ai/tests/data_preparation/models/test_block.py
Import block decorators in the module in case they aren't defined in the block code. The module will not be exec-ed properly because it will fail due to the decorator not being defined, and will fall back to the default block execution:
> [dy] Import decorators when executing block module

- mage_ai/data_preparation/models/block/dbt/utils/__init__.py
- mage_ai/data_preparation/models/variable.py
Fix using location in dbt bigquery.
Original issue
```
I’m having some issues with Bigquery data loading from GCS with a downstream dbt model block.
When pulling the data from the GCS block as source, my dbt profile expects this data to be in the EU,
however the mage configuration seems to auto-load the data into location: US by default and I cannot
find a place to change this even though all of my dbt settings are set as EU. Any suggestions on this?
```
cc:
> [xy] Fix using location in dbt bigquery.

- mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
- mage_ai/frontend/components/PipelineDetail/Syncs/SyncRowDetail/index.tsx
- mage_ai/frontend/components/Triggers/Table.tsx
- Add spaces to block runs count in pipeline runs table so the link is easier to click.
- Make all Logs icons consistent.
- Confirmed minor UI fixes locally
> [jk] Block run count formatting in PipelineRuns table

- mage_ai/frontend/components/FileBrowser/Folder.tsx
- mage_ai/frontend/components/FileEditor/index.tsx
- mage_ai/frontend/components/FileVersions/index.tsx
- mage_ai/frontend/components/PipelineDetail/index.tsx
- mage_ai/frontend/components/Sidekick/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- Allow opening and editing any file via the file browser.
- Open any file even if it’s an existing block in a pipeline
cc:
> [td] Open and edit any file, including prefix .

- docs/api-reference/pipeline-schedules/create-pipeline-schedule.mdx
- docs/api-reference/pipeline-schedules/delete-pipeline-schedule.mdx
- docs/data-integrations/destinations/adapt-existing-destination.mdx
- docs/data-integrations/overview.mdx
- docs/data-integrations/sources/adapt-existing-source.mdx
- docs/design/core-abstractions.mdx
- docs/guides/transformer-blocks.mdx
- docs/integrations/spark-pyspark.mdx
A user felt that WIP sections in our docs did not convey the best message. This PR removes those sections. Notes have been made to track WIP sections for future work. 
https://mageai.slack.com/archives/C03GGQTS8CT/p1691774680116499?thread_ts=1691774418.401199&cid=C03GGQTS8CT
- `mintlify dev`
- `mintlify broken-links`
> [mp] Remove WIP sections from documentation

- docs/design/data-loading.mdx
- mage_ai/io/base.py
Add support for reading & writing XML documents on the base io class.
Manually tested by reading and writing to minio using the S3 loader/exporter. Ran all the existing tests.
- [X ] I have performed a self-review of my own code
> base.py: add XML support

- mage_ai/data_preparation/executors/block_executor.py
- mage_ai/orchestration/pipeline_scheduler.py
- mage_ai/shared/retry.py
Looking into the issue for [this slack thread](https://mageai.slack.com/archives/C03HTTWFEKE/p1689936582602419?thread_ts=1689928310.536919&cid=C03HTTWFEKE). It seems like the logs from the block runs are not getting logged for this user which I think is a separate issue or maybe is a result of the user's setup.
For now, I changed the logging to print one error log in the block run and one error log in the pipeline run. I also removed the error logging from the `retry` method because it doesn't really add any information and can be confusing.
> [dy] Update error logging for block runs

- mage_ai/frontend/components/DependencyGraph/index.tsx
- [Firefox browser] Allow dependency graph connecting lines to go through nodes. This was already doable in Chrome and Safari.
- [Chrome browser] Center dependency graph when loading the Pipeline Editor page. The dependency graph would already center itself on Firefox and Safari.
Before [Firefox]: Connecting lines cannot go through nodes.
After [Firefox]: Connecting lines CAN go through nodes.
Before [Chrome]: Dep graph does not center automatically.
After [Chrome]: Dep graph DOES center automatically.
> [jk] Browser-specific dependency graph improvements

- docs/production/configuring-production-settings/compute-resource.mdx
- mage_ai/data_preparation/executors/k8s_block_executor.py
- mage_ai/services/k8s/config.py
- mage_ai/tests/data_preparation/executors/test_k8s_block_executor.py
Add a config param to control block executor namespace
This has been tested locally as much as possible but really needs to be deployed into a kubernetes cluster to work.
> Add namespace to K8sBlockExecutor config

- mage_ai/api/policies/PipelineRunPolicy.py
- mage_ai/api/resources/PipelineRunResource.py
- mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
- mage_ai/frontend/components/shared/Paginate/index.tsx
- mage_ai/frontend/interfaces/PipelineRunType.ts
- mage_ai/frontend/pages/pipeline-runs/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
- When viewing pipeline runs for an individual pipeline, the number of pipeline runs on each page was inconsistent due to grouping of retried pipeline runs with the same execution date (this was so users can see all run retries on the same page). This also led to certain runs being displayed on multiple pages, which could be confusing for users performing bulk actions like retry/cancel on specific runs across pages.
- This PR makes the number of pipeline runs on each page consistent (30 runs per page) and avoids having the same run appear on multiple pages.
- Confirmed pipeline run count on each page was consistent.
Before (same pipeline run appears on Page 1 and 2):
After (no overlap of runs between pages):
> [jk] Make pipeline run count pagination consistent

- docs/development/environment-variables.mdx
- docs/getting-started/setup.mdx
- mage_ai/server/server.py
- mage_ai/settings/__init__.py
- mage_ai/tests/server/test_server.py
This should be able to resolve this github issue: https://github.com/mage-ai/mage-ai/issues/1040.
I added two new base path variables called `MAGE_REQUESTS_BASE_PATH` and `MAGE_ROUTES_BASE_PATH` because in some cases, only the frontend paths need to be updated. In sagemaker studio, when the app is accessed through the url `<sagemaker-url>/proxy/6789/pipelines`, the backend route that is called is actually just `/pipelines`. Right now, when the `MAGE_BASE_PATH` variable is set, the backend routes will also get updated, so calling the `/pipelines` route will return a 404. The `MAGE_REQUESTS_BASE_PATH` variable will overwrite the urls in the frontend, and the `MAGE_ROUTES_BASE_PATH` variable will overwrite the routes in the server. The behavior of `MAGE_BASE_PATH` stays the same.
The names …
> [dy] Add new base path environment variables

- mage_integrations/mage_integrations/destinations/trino/connectors/base.py
Resolves this issue: https://github.com/mage-ai/mage-ai/issues/3267. Adds double quotes around column names in Trino `CREATE TABLE` query.
cc:
> [dy] Add column identifier for trino

- docs/production/configuring-production-settings/runtime-variable.mdx
- mage_ai/cli/main.py
- mage_ai/cli/utils.py
Fix mage run cli command with variables.
Example usage: `mage run default_repo default_pipeline --runtime-vars '{"name": "default", "ds": "2022-08-18"}'`
`Typer` doesn't support a list of values as arg value: https://github.com/tiangolo/typer/issues/110
cc:
> [xy] Fix mage run cli command with variables

- mage_ai/api/presenters/PipelinePresenter.py
- mage_ai/data_preparation/models/pipeline.py
- mage_ai/frontend/interfaces/PipelineType.ts
- mage_ai/frontend/pages/pipelines/index.tsx
- mage_ai/tests/data_preparation/models/test_pipeline.py
- Add `created_at` property to pipeline model and display in the Pipelines dashboard table, which users can use to sort the pipelines table by when sorting is implemented.
- Updated unit tests
- New pipelines will now have the `created_at` property (old pipelines are not applicable since they were already created):
> [jk] Add pipeline "created_at" property

- mage_ai/api/policies/PipelineRunPolicy.py
- mage_ai/api/presenters/PipelineRunPresenter.py
- mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
- mage_ai/frontend/interfaces/BlockRunType.ts
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
- Add pagination to Block Runs page (for a specific pipeline run). Helps to organize block runs, especially for dynamic pipelines that create many block runs.
Before (no pagination):
After (with pagination):
> [jk] Add pagination to pipeline run block runs page

- mage_integrations/mage_integrations/sources/sql/base.py
- mage_integrations/mage_integrations/tests/sources/bigquery/test_bigquery.py
- mage_integrations/mage_integrations/tests/sources/mysql/test_mysql.py
- mage_integrations/mage_integrations/tests/sources/sql/test_base.py
Added all SQL generated columns as replication_key, allowing for all columns to be used as bookmarks.
Tested on a local mage instance using PostgreSQL -> Clickhouse
Catalog before enhancement:
Catalog after:
Incremental run tests:
> Added all columns as replication key

- mage_integrations/mage_integrations/sources/bigquery/__init__.py
Fix bigquery bookmark datetime comparison
cc:
> [xy] Fix bigquery bookmark datetime comparison

- mage_ai/data_preparation/executors/streaming_pipeline_executor.py
- mage_ai/streaming/sinks/amazon_s3.py
- mage_ai/streaming/sinks/base.py
- mage_ai/streaming/sources/amazon_sqs.py
- mage_ai/streaming/sources/base.py
This PR improves the stability of the streaming pipeline
* When there're exceptions thrown in streaming pipeline, the processes might not be fully terminated due to hanging threads. Thus, this PR adds the destroy method to the source and sink. It make sure the hanging threads are destroyed on exception.
* This PR removes the redundant code in S3 sink for uploading the data on timeout. This reduces the race conditions.
cc:
> [xy] Improve streaming pipeline stability

- mage_ai/cli/main.py
- mage_ai/data_preparation/repo_manager.py
- mage_ai/server/server.py
- mage_ai/tests/data_preparation/test_repo_manager.py
Because of the project_uuid bug that was introduced a couple of versions ago, the `project_uuid` value for a workspace may not be what was originally set. To fix this, I'm changing the `init_project_uuid` method to overwrite the existing `project_uuid` if an `overwrite_uuid` is passed in. Only workspaces should have the `project_uuid` argument set when the server is started.
> [dy] Overwrite existing project_uuid if a project_uuid is set when starting the server

- mage_ai/data_preparation/executors/pipeline_executor.py
Fix passing variables to run_blocks.
cc:
> [xy] Fix passing variables to run_blocks.

- mage_ai/data_preparation/models/pipeline.py
- mage_ai/frontend/components/PipelineDetail/Settings/index.tsx
- mage_ai/frontend/interfaces/PipelineType.ts
Add the `run_pipeline_in_one_process` setting it the UI in pipeline settings.
cc:
> [td] Add run_pipeline_in_one_process in pipeline settings

- mage_ai/api/policies/PipelineSchedulePolicy.py
- mage_ai/api/presenters/PipelineSchedulePresenter.py
- mage_ai/frontend/components/Triggers/Detail/index.tsx
- mage_ai/frontend/components/Triggers/Table.tsx
- mage_ai/frontend/interfaces/PipelineScheduleType.ts
- mage_ai/frontend/utils/date.ts
- mage_ai/orchestration/db/models/schedules.py
- mage_ai/tests/orchestration/db/models/test_schedules.py
- Show the next pipeline run datetime for triggers on the Triggers list page for an individual pipeline, as well as an individual trigger's detail page.
Triggers list page:
Trigger detail page (under the "Settings" section):
> [jk] Preview next pipeline run time for triggers

- mage_ai/frontend/components/Triggers/Edit/index.tsx
- mage_ai/frontend/components/shared/Table/index.tsx
- mage_ai/frontend/package.json
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
- mage_ai/frontend/yarn.lock
- When editing a trigger and using a custom interval with cron expressions, explain the cron expression in a human readable way directly in the app so that users don't have to refer to an outside resource like crontab.guru.
- Also fix small bug when switching between the Pipeline runs and Block runs tabs for a pipeline.
- Only show Actions dropdown on Pipeline runs tab (and hide it on the Block runs tab).
Invalid cron expression:
Valid cron expression:
> [jk] Explain cron syntax in a human readable way

- mage_ai/services/gcp/cloud_run/cloud_run.py
Not pass liveness_probe to cloud run jobs.
This fixes the error
cc:
> [xy] Not pass liveness_probe to cloud run jobs.

- mage_ai/frontend/components/VersionControl/GitActions.tsx
- mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
- mage_ai/frontend/pages/terminal/index.tsx
- mage_ai/server/terminal_server.py
When initially creating the terminal websocket connection, we were passing the api key and oauth token through the query params which is a security risk. This PR removes the need to pass in those fields for the initial request.
cc:
> [dy] Update terminal server user token handling

- mage_ai/api/policies/IntegrationSourcePolicy.py
- mage_ai/frontend/components/IntegrationPipeline/index.style.tsx
- mage_ai/frontend/components/IntegrationPipeline/index.tsx
- mage_ai/server/api/integration_sources.py
- mage_integrations/mage_integrations/sources/github/README.md
Adds inline docs to integration pipeline sources UI
The integration pipeline sources have separate links out to github for the documentation. It would be cooler to show this documentation inline!
Step 1 - Read the `README.md` files that are included within each integration source when listing the source collections via the API, add to a 'docs' parameter.
Step 2 - Look for that 'docs' param and render an Accordian > Markdown block with the docs contents when the source dropdown changes, or when loading a pipeline config and it's already set.
I've run the PR changes on my local development setup, and verified that the 'docs' param is present in each item in the API response, and that selecting a source in the pipeline updates the documentation block accordingly.
Update:
Additionally, the …
> Integration pipeline source docs - inline display in the UI

- mage_integrations/mage_integrations/sources/sql/base.py
- mage_integrations/mage_integrations/tests/sources/mysql/test_mysql.py
Issue:
In Data integrations SQL Sources,if defined, only rows set as `Unique` will be eligible to be set as `Bookmark` 
All rows should be eligible as `Bookmark`
Tested on a local mage instance
cc:
> Removed unique_constraints from valid_replication_keys definition

- mage_ai/data_preparation/models/block/dbt/__init__.py
- mage_ai/data_preparation/models/block/dbt/utils/__init__.py
* Fix dbt command failure due to empty content args
* Print dbt command errors to stdout
Close: https://github.com/mage-ai/mage-ai/issues/3271
Before this change:
The command was 
After this change
cc:
> [xy] Fix dbt command failure due to empty content args

- docs/mint.json
- docs/production/databases/default.mdx
- mage_ai/cluster_manager/kubernetes/workload_manager.py
- mage_ai/orchestration/constants.py
- mage_ai/orchestration/db/__init__.py
- mage_ai/orchestration/db/setup.py
Add a way to populate the `db_connection_url` from AWS secret manager. The environment variable is called `AWS_DB_SECRETS_NAME`, and expects the name of the AWS secret manager secret. I will update the documentation once this PR is finalized.
> [dy] Read DB credentials from AWS secret manager

- docs/design/data-loading.mdx
Adds a note to the # Configuration Settings section with links to using secrets for other secret providers
While searching for how to use Azure Key Vault secrets in Mage, I came across the docs for the AWS secret loader, but didn't notice anything there for Azure Key Vault. I found some relevant information with broken links while searching Slack, and eventually made it to other secrets docs. I thought it would be nice to have a little note in the docs that point folks directly to the relevant ways to use secrets for Azure Key Vault and GCP Secret Manager.
No code, no tests. I didn't see any guidance specifically related to docs contributions in the Contributing.md, but I'm happy to do whatever in order to verify.
> Add note to Update data-loading.mdx

- mage_ai/api/policies/PipelineRunPolicy.py
- mage_ai/api/resources/PipelineRunResource.py
- mage_ai/frontend/components/Orchestration/Sidebar/index.tsx
- mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
- mage_ai/frontend/components/Triggers/Table.tsx
- mage_ai/frontend/components/shared/Table/constants.ts
- mage_ai/frontend/interfaces/PipelineScheduleType.ts
- mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
- mage_ai/orchestration/db/models/schedules.py
- Add optional button for deleting individual pipeline runs from pipeline runs table.
- Support deleting individual pipeline runs on `/pipelines/[pipeline_uuid]/runs` page.
- Allows users to clean up pipeline runs table (e.g. if they prefer to remove all failed runs). Bulk deleting pipeline runs would be a separate feature/PR.
DELETE `http://localhost:6789/api/pipeline_runs/479`
Response:
```
{
"pipeline_run": {
"id": 479,
"created_at": "2023-03-04 00:27:08",
"updated_at": "2023-03-04 00:27:10",
"pipeline_schedule_id": 227,
"pipeline_uuid": "little_fog",
"execution_date": "2023-03-04 00:25:40.075355",
"status": "cancelled",
"started_at": null,
"completed_at": null,
"variables": null,
"passed_sla": false,
"event_variables": null,
"metrics": null,
"backfill_id": null,
"executor_type": null …
```
> [jk] Delete individual run from pipeline runs table
